### ISSUE TITLE
422 Unprocessable Entity on GitHub signup

### ISSUE THREAD

**Issue by stephenkao** [lemurheavy/coveralls-public#1007]
Hey there!

I'm currently trying to sign up on coveralls.io, but I keep getting a `422 Unprocessable Entity` for the https://coveralls.io/authorize/github/ call, and I get the following message:

![screen shot 2017-08-31 at 6 05 31 pm](https://user-images.githubusercontent.com/2421042/29947338-18c94558-8e77-11e7-96e3-d67c07788374.png)

I've seen a couple of other 422 issues that were resolved by using a different browser or clearing coveralls.io cookies, but nothing's working for my account.  Any ideas as to what's going on?

Thanks in advance!

**Comment by levrik** [comment]
I have this issue for over a month now (see https://twitter.com/levrik_io/status/918547275412058113).

**Comment by levrik** [comment]
One week later and it still doesn't work. We're paying for your service. Please fix it!
