### ISSUE TITLE
Log in in coveralls blocked by too many redirects

### ISSUE THREAD

**Issue by Thimxx** [lemurheavy/coveralls-public#1008]
I might be linked to this issue previously closed: #999.

Currently I am not able to access to my coveralls. When I delete the cookies (as explained in #999) I am getting back access to (or I use a different browser). More specifically I am using Chrome as main browser and for checking this issue I am using internet explorer.

What also is happening:

- Although travis has performed some executions, there is no update of coverage since 29th August, first built not accounted is 31 August
-  The images that are provide about coverage show a coverage value I had on 7th August. However, before the 29th August it was showing more recent values.
- When clicking on a specific file to see coverage information, the webpage fails and asks me for new authorization. In chrome this ends in no longer able to log in and the need to delete cookiers, internet explorer allows me to continue entering but not reading the file coverage.

What can I check?

**Comment by Thimxx** [comment]
The issue still exists, simply it has not been addressed yet...

**Comment by afinetooth** [comment]
@Thimxx did you try unlinking and relinking GitHub like the user did issuehttps://github.com/lemurheavy/coveralls-public/issues/999, here:
https://coveralls.io/account

![Screen Shot 2020-04-13 at 1 03 08 PM](https://user-images.githubusercontent.com/918667/79156195-4b8fe580-7d87-11ea-80db-8ad205459b2d.png)

**Comment by Thimxx** [comment]
This is fixed now.

Sorry, when I reopen it I thought it was a different issue... it was created 3 years ago :)
