### ISSUE TITLE
Add repositories automatically

### ISSUE THREAD

**Issue by leusonmario** [lemurheavy/coveralls-public#1012]
Is there a way for adding repositories on Coveralls automatically? I mean using an API or something like that. I searched, but I only found how to get information about coverage of projects already configured.

Once I could do it, I also could get the repotokens and add it on `pom configuration files`, without human intervention.

**Comment by rcmachado** [comment]
It seems this would be possible by using the API: https://coveralls.io/api/docs

**Comment by tobyink** [comment]
This API doesn't seem to work. `GET https://coveralls.io/api/repos/github/tobyink/p5-type-tiny` seems to fail, even with a seeingly correct `Authorization` header.

**Comment by afinetooth** [comment]
@tobyink assuming you worked this out per https://github.com/lemurheavy/coveralls-public/issues/1501.

For anyone who's still trying to add repos via the API (/[repos endpoint](https://coveralls.io/api/docs#repos-v1-add-a-new-repo-to-coveralls)), here's a cURL example:

```
curl --location --request POST 'https://coveralls.io/api/repos' \
--header 'Content-Type: application/json' \
--header 'Authorization: token zFGkQwy5ROxOlNPgpzOAUmAwE1hTByUz7n' \
--data-raw '{
    "repo": {
        "service": "github",
        "name": "<your_github_username>/<your_github_repo_name>",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 80.0,
        "commit_status_fail_change_threshold": null
    }
}'
```

Token used for above example has been changed/deleted. Get yours here:
https://coveralls.io/account

UI looks like this:

![Screen Shot 2020-11-16 at 4 27 56 PM](https://user-images.githubusercontent.com/918667/99324240-b119e800-2828-11eb-8e1b-8eab01d35bee.png)

Biggest hurdle tends to be formatting the personal access token in the Authorization header. 

The format is specific to our API:

```
Authorization: token zFGkQwy5ROxOlNPgpzOAUmAwE1hTByUz7n 
```

**Comment by tobyink** [comment]
@afinetooth the format of the Authorization header isn't that unique to Coveralls. The GitHub API and codecov.io API use basically the same format.
