### ISSUE TITLE
upload twice

### ISSUE THREAD

**Issue by piem** [lemurheavy/coveralls-public#1014]
hi,

is there a way to upload twice from a single build? for instance both C and python coverage results?

i tried this in [aubio](/aubio/aubio)'s coveralls branch: both POST requests were successful, but only the results of the second one seem to appear.

cheers, piem

**Comment by piem** [comment]
Hi @afinetooth,

fyi, this question was legit, and never got answered.

not a huge deal, but someone might want to know a bot is closing issues that were maybe never looked at.

bye, piem

**Comment by afinetooth** [comment]
@piem we're resource-limited and so just using an automated strategy to prioritize issues by closing older ones. Thanks for replying. I've labeled the issue. Core team will address asap.
