### ISSUE TITLE
Circle-CI: Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by blueyed** [lemurheavy/coveralls-public#1018]
```
$ coveralls -v
Missing .coveralls.yml file. Using only env variables.
Submitting coverage to coveralls.io...
{
   "service_pull_request" : "3",
   "service_name" : "circle-ci",
   "service_job_id" : "153",
   "source_files" : [],
   "config_file" : ".coveragerc",
   "git" : {
      "branch" : "develop",
      "remotes" : [
         {
            "name" : "origin",
            "url" : "https://github.com/Vimjas/covimerage.git"
         }
      ],
      "head" : {
         "committer_email" : "XXX",
         "committer_name" : "XXX",
         "author_email" : "XXX",
         "id" : "9294f4e52f3bb5dc6cf86f67ce390c1bdac889a6",
         "author_name" : "XXX",
         "message" : "improve run and tests"
      }
   }
}
==
Reporting 0 files
==

Coverage submitted!
Couldn't find a repository matching this job.
'url'
```

I've read through https://github.com/lemurheavy/coveralls-public/issues/487, but it does not seem to be related.
Maybe it is caused by using CircleCI 2.0?

**Comment by blueyed** [comment]
Please note that it originally sends `"url": "git@github.com:Vimjas/covimerage.git"` - which it gets via `git remote -v`, and circleci has this `~/.gitconfig`:
``` [url "ssh://git@github.com"]
	insteadOf = https://github.com
```

**Comment by blueyed** [comment]
Hard to tell where this error is coming from.  The code for this is not open source, is it?
It should also be more verbose in general, which would help users to debug this.

**Comment by blueyed** [comment]
Setting COVERALLS_REPO_TOKEN fixes it, but I think that it is supposed to work automatically for open projects?!

**Comment by txomon** [comment]
Same problem here, and I see it's yet not fixed...

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861

**Comment by txomon** [comment]
Just in case, the COVERALLS_REPO_TOKEN fixes this issue, @bytewalls maybe we could document this? It's just adding an small text to the instructions you already have to point to people using circle ci in the good direction.
