### ISSUE TITLE
Wrong coverage difference in PR

### ISSUE THREAD

**Issue by ValentinH** [lemurheavy/coveralls-public#1019]
It's basically a similar issue to #463 which was closed 2 years ago so I prefer opening a new one.

**Current behavior**
I have noticed that when I create a PR and I make several commits in it, the coveralls check is incorrect. Basically, it presents the coverage difference between the two last commits.

**Expected behavior**
The coveralls difference should compare the last commit of the PR with the latest commit on master.

What do you think?

**Comment by alexmuller** [comment]
Yeah, I'm also seeing this problem and it confuses me. I assume I have something configured incorrectly. With these commits on a branch:

- PASS coverage/coveralls — First build on _branch-name_ at 64.889% 
- FAIL coverage/coveralls — Coverage decreased (-0.3%) to 64.548% 
- FAIL coverage/coveralls — Coverage decreased (-1.6%) to 62.9% 
- PASS coverage/coveralls — Coverage increased (+0.08%) to 63.262%

**Comment by pawelad** [comment]
This really confused our team as well, and should _at least_ be configurable.

**Comment by pawelad** [comment]
Coming back to this after a couple of days, I'd even go as far as saying that this is a really annoying bug.

**Comment by bytewalls** [comment]
@pawelad @alexmuller which CI provider are you using and how our your submitting to the API? Can you provide a link to a coveralls build that has this issue?

If our system knows that your checking coverage as a pull request, it will run the coverage change check against the master branch. It is possible something has updated on a CI provider which we need to account for, or perhaps we need to help update a community provided coveralls integration tool.

Thanks!

**Comment by ValentinH** [comment]
I use GitHub, but my issues are on private repos.

**Comment by yomed** [comment]
@bytewalls Here's an example where the PR increased coverage by 5% as shown in the top Coveralls comment, but for each commit it showed the coverage difference between it and the previous commit in the Github status check.
https://github.com/eBay/ebayui-core/pull/81 
https://github.com/eBay/ebayui-core/pull/81#issuecomment-384736522

**Comment by pawelad** [comment]
Thanks for getting back to us @bytewalls !

We're running Travis CI Pro with Coveralls Pro for a private GitHub repository, but I'll try to reproduce it for a personal open source project that I can link to when I get some free time.

The behaviour is basically what alexmuller listed - the description and value of what's in the GitHub PR checks is value of the latest commit, not the PR as a whole. If the first commit in the PR increased it from 15% to 18%, and then the next commit decreased it to 17% the _overall_ Coveralls check for that PR would indicate failure because coverage was decreased by 1%.

**Comment by bytewalls** [comment]
@pawelad @ValentinH if you all don't mind point to the url of the repo on coveralls that would be a good starting point for me to dig in, obviously I won't be able to see your codebase.

@yomed in this instance was the PR comment correct and updated correctly as time went on but the new build statuses were to the previous build as opposed to the last build on master? (our PR comments should now automatically do an edit instead of commenting multiple times)

**Comment by yomed** [comment]
@bytewalls Yes, exactly. The PR comment worked great with the real-time edits, and showed the correct numbers. It was just the status check that was comparing against the wrong commit.

**Comment by bytewalls** [comment]
@yomed Thanks that's very helpful, I'll dig in and hopefully with that information we can and get this resolved.

**Comment by coderanger** [comment]
Having this same issue with goveralls and CircleCI.

**Comment by reinout** [comment]
I also have the same problem, with https://coveralls.io/github/nens/ThreeDiToolbox (travis + github).
My https://github.com/nens/ThreeDiToolbox/pull/416 pull request often showed the same "stayed the same/increased 0.02%" messages even though the PR was all about adding coverage.

If I look at this piece of coveralls output, I'm getting an idea:

![Screenshot from 2019-06-19 17-32-34](https://user-images.githubusercontent.com/121433/59779561-c3e95f80-92b8-11e9-8a4d-5df422df0a3a.png)

The PR builds often finish a bit earlier than the branch builds. The PR builds show the correct "coverage increased" picture, the branch builds have the "stayed the same" picture as the coverage doesn't differentiate from the corresponding PR build.

I'm now trying to only submit the coverage to coveralls on pull requests, see https://github.com/nens/ThreeDiToolbox/pull/416/commits/510fc76e595f2449d242ff6277eade9f220bec04

I'll report back if that works :-)

**Comment by reinout** [comment]
No, it didn't.

- Well, the "if" in my travis config works. Only PR builds are send to coveralls now.
- But the difference still doesn't get compared to master. See https://coveralls.io/builds/24103101, "coverage remained the same".
- Somehow coveralls stopped reporting the coverage back to github. Might be unrelated.

**Comment by shreyasbharath** [comment]
Bump, any progress on this?

**Comment by bryce-cahill** [comment]
For those still having this issue I think it is related to the issue described in #1167 and I was able to resolve it by making sure that each build had a unique `service_job_id`.
