### ISSUE TITLE
NodeJS + Travis: Coveralls never finishes

### ISSUE THREAD

**Issue by aeimer** [lemurheavy/coveralls-public#1024]
Hi there,

we want to use Coveralls in our OpenSource-Project https://github.com/h-da/geli
We are producing a LCOV-File with Mocha and Instanbul which we then send to Coveralls.
Sadly this does not work as supposed. Coveralls gets the Pullrequest but it seems like it couldn't process the data of the lcov-file...

- https://github.com/h-da/geli/pull/220
- https://github.com/h-da/geli/blob/bugfix/coverage/.travis/coveralls.sh
- https://github.com/h-da/geli/blob/bugfix/coverage/.travis/package.json
- https://github.com/h-da/geli/blob/bugfix/coverage/.travis.yml#L85
- https://coveralls.io/github/h-da/geli

It would be great if you could analyse the problem with us.

@grosspersky and I can help you.

Best regards,
Alex

**Comment by grosspersky** [comment]
We have created a new PR for coveralls to get our other coverage fixes from this PR live.
You can find the new PR here: https://github.com/h-da/geli/pull/220

**Comment by khase** [comment]
the source of this Problem is that `remap-istanbul` does not correctly remap the source files so that the check `if (fs.existsSync(currentFilePath))` fails and does not push the file to the coveralls source.

fixing this with a `sed` before piping the .lcof to `node-coveralls` module
h-da/geli#272

**Comment by aeimer** [comment]
See h-da/geli for more info
