### ISSUE TITLE
Integration with Jenkins

### ISSUE THREAD

**Issue by goldbergyoni** [lemurheavy/coveralls-public#1026]
Hi,

I'd like to integrate Coverall.io with Jenkins but I'm unable to find documentation that explains how to peer the two. More than anything else I'd like to understand (a) what exactly is Coveralls role in that integration? does it only receive reports (e.g. clover) and beautify and results or it actually analyzes the source code itself? help me to communicate Coveralls.io value (b) how do you suggest to glue them together

Yoni

**Comment by milind-shakya-sp** [comment]
@nickmerwin  any update on this?
