### ISSUE TITLE
Coveralls lists builds and branches entirely unrelated to my repository

### ISSUE THREAD

**Issue by zoechi** [lemurheavy/coveralls-public#1028]
https://coveralls.io/github/lookAtYouInc/lookatmybaby?branch=master

"Sync Branches" doesn't seem to do anything. 
Sometimes my active branches `master` and `develop` are shown, sometimes entirely unrelated ones are shown instead of in addition to mine.

I also get 27% coverage on master even though I haven't uploaded any data for master yet.

**Comment by mdevar** [comment]
Same here, i see a list of branches that are not related to my repo

**Comment by 71FIL** [comment]
Same here - no update? I don't have a master branch and all reports are assigned to that branch which does not exist. This leads to coverage swings as reports are all collapsed to the same master branch. Syncing shows a single branch which does not even exist.
