### ISSUE TITLE
Bad documentation for c++

### ISSUE THREAD

**Issue by PanicSheep** [lemurheavy/coveralls-public#1034]
In the File with the title "C++ SET UP FOR COVERALLS" there's written: "Add our gem to your Gemfile".
Gemfiles in a C++ project???

And later on "At the very top of your spec_helper.rb or test_helper.rb or what have you". The documentation says c++ not ruby.

**Comment by ObiWahn** [comment]
This does not work well at all! The suggested python module does not handle builds created with CMake correctly. I have tried it for a few hours. Now I will either fork the tool and make it work for my usecase or maybe I just use the CDash coverage.
