### ISSUE TITLE
Coveralls commenting multiple times

### ISSUE THREAD

**Issue by gempir** [lemurheavy/coveralls-public#1037]
Coveralls is way to chatty and comments the same 3 times somehow.

https://github.com/gempir/go-twitch-irc/pull/16

**Comment by bxm156** [comment]
I noticed mine is commenting 10 times, (it shows the original comment was edited 9 times)

https://github.com/Miserlou/Zappa/pull/1230

**Comment by gempir** [comment]
Happend again https://github.com/gempir/go-twitch-irc/pull/18
