### ISSUE TITLE
badge not updating on github 

### ISSUE THREAD

**Issue by leogoesger** [lemurheavy/coveralls-public#1039]
https://coveralls.io/github/leogoesger/gutsy-api
https://github.com/leogoesger/gutsy-api

It seems like a common problem. The coveralls site have it to be 80%, but not on github.

**Comment by leogoesger** [comment]
caching issue. If you have similar issue, make sure you clean your browser.

**Comment by afinetooth** [comment]
https://github.com/lemurheavy/coveralls-public/issues/1828
