### ISSUE TITLE
Multiple JSON coverage files

### ISSUE THREAD

**Issue by apanzerj** [lemurheavy/coveralls-public#1044]
Our team generates coverage from several test runners. Do we have to combine these into one JSON file or can we ship them individually and have them combined by your service?

**Comment by pabarcgar** [comment]
I have a repository with python and java code, and I have found the way to do it using the coveralls-python:

http://coveralls-python.readthedocs.io/en/latest/usage/multilang.html#multilang

**Comment by apanzerj** [comment]
More like we need something that lets me send multiple coverage files not just one large one.

**Comment by mathieuboudreau** [comment]
This is a feature I'd also be interested in.

**Comment by apanzerj** [comment]
Too bad it never got added. I took our org and switched to a competitor. It's not as sexy but it works.
