### ISSUE TITLE
Serious security/data integrity issue

### ISSUE THREAD

**Issue by JacobEvelyn** [lemurheavy/coveralls-public#1049]
I haven't looked at my Coveralls data in a while but just checked today and something is seriously wrong, leading me to believe there may be a serious security or data integrity issue. I'm including screenshots in case triggering a rebuild fixes this issue in this case, because I still think it's important that someone on the Coveralls team investigates how this happened and whether there are broader security or data integrity issues.

On my repository's [Coveralls page](https://coveralls.io/github/JacobEvelyn/friends), here's what I see:

<img width="1012" alt="screen shot 2018-01-01 at 3 18 41 pm" src="https://user-images.githubusercontent.com/1114569/34470942-6120d570-ef0a-11e7-9b43-a8aface126c9.png">

And:

<img width="975" alt="screen shot 2018-01-01 at 3 33 12 pm" src="https://user-images.githubusercontent.com/1114569/34470897-7d236fd6-ef09-11e7-98f7-5d4161e42ea4.png">

And:

<img width="974" alt="screen shot 2018-01-01 at 3 36 49 pm" src="https://user-images.githubusercontent.com/1114569/34470934-18765c78-ef0a-11e7-94c5-3cd9aa727b48.png">

You can verify all of my commits [here](https://github.com/JacobEvelyn/friends/commits/master) (and no, I haven't rewritten `git` history or anything like that) to compare them against what you see in the screenshots.

**Comment by nanno77** [comment]
We are seeing the same thing. Why is this issue 24 days old with no response? That is frightening.

**Comment by nickmerwin** [comment]
Hi all, seeing a public repo's builds in your private repo is a symptom of having service_name: travis-ci instead of service_name: travis-pro. No private data is being leaked the other direction.

More info here: https://docs.coveralls.io/troubleshooting#i-see-random-commits-on-my-travis-pro-private-repo

**Comment by JacobEvelyn** [comment]
@nickmerwin I'm not sure I understand. I'm not seeing a public repo's builds in my private repo, I'm seeing some repo's data in my _public_ repo. [My repo](https://github.com/JacobEvelyn/friends) is public and always has been.

Does that mean that this "data leakage" is possible for all public repos? And why aren't you guys using unique IDs?
