### ISSUE TITLE
Coverage report "Loading..." indefinitely on coveralls.io (recurring issue)

### ISSUE THREAD

**Issue by tom-lord** [lemurheavy/coveralls-public#1050]
For example, see [here](https://coveralls.io/jobs/32368451):

![Coverage "loading" indefinitely](https://user-images.githubusercontent.com/7573396/34471861-6e5bc024-ef4b-11e7-8be6-55abc15e54c1.png)

I suspect the problem is caused by a backlogged/failed/blocked processing queue for these jobs. Could you please re-trigger the jobs as necessary?

After some research, I believe that these "queue backlogs" have been a recurring issue for quite a while - for instance, in May 2017 ([Incident Report](http://status.coveralls.io/incidents/ynqhpvsbrd96); [Github issue](https://github.com/lemurheavy/coveralls-public/issues/969)) and in December 2016 ([Incident Report](http://status.coveralls.io/incidents/yh1xjbhx6zk4); [Github issue](https://github.com/lemurheavy/coveralls-public/issues/892)).

However, in this case the jobs have been "backlogged"(?) for at least 4 days with no incident report. Which is somewhat understandable as this is over Christmas, and I suspect your staff are all away, but nevertheless I'd recommend adding some form of automation to detect blocked jobs and raise an incident report?

**Comment by mdarby** [comment]
Same issues nearly a year later? I've wasted half a day on this?

**Comment by jingpengw** [comment]
I got `no data` message
