### ISSUE TITLE
Missing coverage

### ISSUE THREAD

**Issue by bgantaume** [lemurheavy/coveralls-public#1055]
Hi,
I have 2 projects with 2 parallel builds on semaphore:  rspec and cucumber.
I have set the environmnent variable (COVERALLS_PARALLEL : true).
Both are sending data.
The first one seems to merge data correctly while the second one doesn't...
It puts red lines while telling me it's only covered on one build...
Why is it red if covered at least once?
<img width="1022" alt="screen shot 2018-01-17 at 12 46 42" src="https://user-images.githubusercontent.com/1662023/35041297-8e326688-fb84-11e7-9c5c-3d7c3f5946bf.png">

On top of this, it gives me 60% of coverage where the firsts job has much more...

[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #65.2
[Coveralls] https://coveralls.io/jobs/32889282
Coverage is at 93.02%.
Coverage report sent to Coveralls.

[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #65.4
[Coveralls] https://coveralls.io/jobs/32889290
Coverage is at 16.48%.
Coverage report sent to Coveralls.

Any idea? 
Kind regards

**Comment by bgantaume** [comment]
btw, when I click on botch job link, I get an infinite 'Loading' message...
Did I do something wrong?
Kind regards
<img width="881" alt="screen shot 2018-01-17 at 12 55 25" src="https://user-images.githubusercontent.com/1662023/35041644-bcb92c66-fb85-11e7-9b73-48726985ae11.png">

**Comment by bgantaume** [comment]
The infinite loading is fixed, but the coverage is still not counted correctly...
It says 'Only 2.1', but does not count the line...
Will you try to fix it or should I give up trying?

**Comment by bgantaume** [comment]
Guys,
I'am sorry this is not fixed yet... 
The data is not consistent and the coverage measure is misleading. 
I am sorry I have to close my subscription and remove all repos because I really love your product.
Ping me when it works.
Kind regards,

![screen shot 2018-02-12 at 09 43 05](https://user-images.githubusercontent.com/1662023/36088876-506b1e76-0fd9-11e8-9c4d-f92e69902871.png)

**Comment by atodorov** [comment]
I think I'm having the same or very close issue. There's at least one file for which I know we have proper coverage (at least for one function). coverage.py shows around 30% of coverage when executed from the terminal. Coveralls shows around 10% for the same file. 

See:
https://coveralls.io/jobs/34516185/source_files/593094173#L183

this is a coverage report which I submitted manually from my development computer. 

1) Executed the test suite locally and it generates .coverage file (Python coverage.py)
2) Then I configured COVERALLS_REPO_TOKEN and executed `coveralls -v`. The above Job was produced.

Locally coverage.py report -m shows that the function `def tag()` is coverred almost entirely. While Coveralls does not.  Interestingly enough I see similar behavior with CodeCov for the same file so it may be something with the .coverage format and how coveralls interprets it. 

Please help me debug this and figure out what's going on.

**Comment by bgantaume** [comment]
I did quit coverall. The service looks promising, but no support...
