### ISSUE TITLE
Coverage counted for skipped lines

### ISSUE THREAD

**Issue by ambethia** [lemurheavy/coveralls-public#1059]
In `SimpleCov`, lines between `# :nocov:` blocks are not counted, but they count against you in Coveralls, for example, this file shows as 100% covered in `SimpleCov`, but only ` 83.33%` on Coveralls:

https://coveralls.io/builds/15161469/source?filename=lib%2Fneo%2Fvm%2Fhelper.rb

<img width="1719" alt="screen shot 2018-01-22 at 2 48 06 pm" src="https://user-images.githubusercontent.com/298/35241074-576f782c-ff83-11e7-910c-0d79c042aa9d.png">

Thanks!

**Comment by bytewalls** [comment]
This has been fixed. Thanks.
