### ISSUE TITLE
Python Documentation Seems Incorrect

### ISSUE THREAD

**Issue by paulkorir** [lemurheavy/coveralls-public#1060]
I'm about to integrate coveralls to my Python project and going through the documentation it seemed to be tailored for Ruby instead of Python. Can someone please verify whether this is the case?
![coveralls-issue](https://user-images.githubusercontent.com/31738053/35333764-e422e242-0107-11e8-9ec7-44c75b596ddb.png)

**Comment by BebeSparkelSparkel** [comment]
This was pissing me off so much.
Then you go to more docs and it redirects you to third party tools?
WTF
Then those tools don't even have helpful docs.
coveralls.io get it together please!

**Comment by Artanicus** [comment]
Any updates to this? Still an issue today and makes getting started with a Python project painful when the instructions displayed are instead for Ruby.

**Comment by pydo** [comment]
So 6 months passed without a response from any coveralls.io member... I just signed up for a PRO account, so I find it pretty lame that a paid SaaS has such terrible documentation.

Here are the 2 problems I have the python documentation:
1. The docs are actually for a ruby project
2. Conflicting documentation, one page says I should use this third-party 
tool https://github.com/z4r/python-coveralls and the other tells me follow the ruby setup


@bytewalls Could you please respond to this thread?

**Comment by bytewalls** [comment]
@pydo,

Sorry about the documentation issues, working on a fix for the page showing incorrect information about how to setup coveralls in your repo.

Right now the two best libraries for sending data to the coveralls api for a python app are these community built libraries:

-  [python-coveralls](https://github.com/z4r/python-coveralls)
- [coveralls-python](https://github.com/coveralls-clients/coveralls-python)
