### ISSUE TITLE
oauth redirect loop after Github repo move

### ISSUE THREAD

**Issue by flihp** [lemurheavy/coveralls-public#1066]
Recently I've migrated a source repo from one gihtub organization to another. As part of this I've had to reauthorize the coveralls service for access to this new org. The organization UI on github shows coveralls and "coveralls pro" (I'm not sure what the what's 'pro' version is?), as does my personal github account. 

Now when I try to log into coveralls now using my Github account I'm redirected to the 'reauthorization required' page. If I click the "Authorize lemurheavy" button I'm brought right back to the same page. I can click this button repeatedly and the results are the same / loop. This effectively makes it impossible for me to login to the coveralls.io site which makes debugging this pretty hard or even impossible? I've tried to clear my authorizations and reauthorize coveralls a number of times but the results are always the same redirect loop on the reauthorization page.

I've found mention of this issue on github in another repo: https://github.com/mapbox/protozero/issues/68 but it looks like theirwork-around was is to use codecov.io instead of coveralls.io: https://github.com/mapbox/protozero/pull/78 which I'd rather not do.

Is this a known issue? (I was unable to find a similar issue in the coveralls-public tracker)
Is there a work around other than the one I've found (switching to codecov.io)?

**Comment by bytewalls** [comment]
When you go to the [Coveralls Pro](https://github.com/settings/connections/applications/5b064d049aaeb3438e8e) settings, has the new organization been granted access?

**Comment by nothingismagick** [comment]
I am having the same issue - and can't even get into any settings on coveralls.io - when I try to login with github I also enter the redirect loop. Clearing the auth doesn't change anything.

**Comment by flihp** [comment]
Oddly enough I got past the login loop this morning after seeing activity on this thread. I managed to get one of my repos working which unfortunately required deleting the old repo (and losing all of my scan history) and then enabling scans from the repos new location. Got everything hooked up to travis with the new repo token and everything, worked great. Then I went to "fix" my other repos and got hit by the same authorization redirect loop. Can't login to coveralls.io any longer.

**Comment by flihp** [comment]
Just got a github "woah there!" message when I tried to login just now. The error message says:
```
You have triggered an abuse detection mechanism.
Please wait a few minutes before you try again.
```
So this loop is hammering the github API enough to trigger their API abuse prevention mechanisms :frowning_face:

**Comment by nothingismagick** [comment]
Yeah - I saw that too. It seems, however, that my code updates are still being checked (and modified) for code coverage. Just can't use the interface to see exactly why...

**Comment by nothingismagick** [comment]
@bytewalls - yes.
![screen shot 2018-03-10 at 00 27 13](https://user-images.githubusercontent.com/35242872/37234737-df64350c-23f9-11e8-8b66-b48b5ff891b1.png)

**Comment by bytewalls** [comment]
We are looking into this. In order to get back in at all, try resetting cookies for now. We are working on a proper solution for this.

The portion that requires group access is directly below the permissions in the "organization access". If a repo was transferred to a new org which the Coveralls Pro app has not been given access to actual contents of the repo will not be available, only the coverage data. We believe the loss of access to files causes the initial request, but the loop is another issue which we are looking into.

**Comment by flihp** [comment]
Any news on this? I just noticed that I'm not able to log into coveralls.io which is progress, but my repo has been effectively removed / deleted (when I click on it I'm prompted to configure it).

**Comment by bytewalls** [comment]
@flihp what was the before the move and after the move? I can look into figuring out what occurred and what the status of your repos is.

We have released some bug fixes to deal with the OAuth redirect circles since this bug was filed.

Thanks,
Sorry for the inconvenience.

**Comment by bytewalls** [comment]
@flihp,

I have merged the builds from the old repo on Coveralls to the new repo on Coveralls ([here](https://coveralls.io/github/tpm2-software/tpm2-tss)). Please let me know if you have any other issues at this.

I have created an issue ticket for us to evaluate how we can make this process more seamless in the future.

I am closing this issue ticket, since as noted we did release updates to fix the OAuth loop cycle (and I believe your current issues are resolved, please let me know if not and I'll gladly reopen it).

**Comment by flihp** [comment]
Looks great @bytewalls. Thanks for the help. I've got another repo that needs the same treatment. Any chance I can get you to migrate another?

**Comment by bytewalls** [comment]
@flihp, absolutely. If you have repos you haven't created copies of I can also update those instead of merging the two.  

Let me know whatever you need updated. We are working on a longer term fix for this issue as well.

**Comment by flihp** [comment]
#1159 should wrap all of this up. Thanks again @bytewalls !
