### ISSUE TITLE
Some of our repositories are no longer getting coverage reports

### ISSUE THREAD

**Issue by robojeff** [lemurheavy/coveralls-public#1067]
Several of our repos have not gotten a coverage report from Coveralls for several months.

Is there a procedure to restart coverage (like, force a coverage report to run) without having to delete the repository and re-add it to Coveralls?

**Comment by bytewalls** [comment]
Can you give us an example repository so we can go issue searching?

**Comment by kuanb** [comment]
Same here, GitHub.com/kuanb/peartree

**Comment by Retro64** [comment]
We got a similar problem. After coveralls stopped reporting coverage for our repo github.com/zalando-incubator/authmosphere we deactivated the repo an re-activated it. After that, no coverage nor repository information was shown. We just got the "private key warning" in our Travis logs, so we expect the data is passed to coveralls. 

Builds are linked and coveralls build overview page is linked within the PR,  but "No data" is shown on the coverage of jobs on the overview page. All files are shown with 100% coverage in the source files section, but we are not able to see any information on repository level. Furthermore, we do not get any feedback on github (still stays yellow). And even if we merge to master, no information is shown on repository level (and badge stays "coverage: unknown").

**Comment by AlCalzone** [comment]
For my recent builds, coveralls shows no coverage data under jobs, but correctly shows changes in the source files, see:
![unbenannt](https://user-images.githubusercontent.com/17641229/37042996-e1bad0f0-215f-11e8-947c-88d8ab71b356.PNG)
This was for a test commit (PR) where I removed almost all test cases to see if things change:
https://github.com/AlCalzone/node-tradfri-client/pull/34

The same thing currently happens on the master branch. My `.travis.yml` looks like this:
```yaml
language: node_js
node_js:
  - '6'
  - '8'
os:
  - linux
script: 
  - npm run coverage
after_success: 
  - npm run coveralls
notifications:
  email: false
```
with the following scripts defined in `package.json`:
```js
// ... more ...
"scripts": {
    // ... more ...
    "coverage": "node_modules/.bin/nyc npm test",
    "coveralls": "node_modules/.bin/nyc report --reporter=text-lcov | coveralls -v",
}
```

**Comment by bytewalls** [comment]
@Retro64 it appears as though your branch 205 is working with the js coveralls package set to use `-v` verbose flag I will make a card for our team to look into that package and see if we need to submit a PR to update the community package.

**Comment by bytewalls** [comment]
@AlCalzone and @kuanb We had an issue with our API earlier today related to background job processing which has since been resolved, backed up background jobs have been processed. It looks like your builds with that fix.

**Comment by kuanb** [comment]
Thanks, sorry for being intense!

**Comment by Retro64** [comment]
@bytewalls We just added the flag to ensure anything was send to the API. Our problem also seem so be related to the API issue, as it works fine now and looked like the screenshot of @AlCalzone. So no need for further investigation from our side. Thanks!
