### ISSUE TITLE
Issue with reporting coverage from CircleCI from a public repo

### ISSUE THREAD

**Issue by astrofrog** [lemurheavy/coveralls-public#1069]
We use coveralls for the Astropy project and have been reported results from Travis CI for a while

https://coveralls.io/github/astropy/astropy

However, I'm now also trying to report coverage from CircleCI -but I'm getting:

```
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Exited with code 2
```

Here's the output of ``coveralls --verbose``:

```
                         
==================== 318 passed, 3 skipped in 24.79 seconds ====================
Saving coverage data in .coverage...
Saving HTML coverage report in htmlcov...
Missing .coveralls.yml file. Using only env variables.
Submitting coverage to coveralls.io...
{"source_files": [...], "service_job_id": "4725", "service_pull_request": "7150", 
"config_file": ".coveragerc", "git": {"head": {"author_name": "Thomas Robitaille", 
"author_email": "thomas.robitaille@gmail.com", "id": "852b018d9f7088caeb523b46ae2774d5a9a5b7cd", 
"message": "DEBUG2 [skip appveyor] [skip travis]",
"committer_email": "thomas.robitaille@gmail.com", "committer_name": "Thomas Robitaille"}, 
"branch": "pull/7150", "remotes": [{"name": "origin", 
"url": "git@github.com:astropy/astropy.git"}]}, "service_name": "circle-ci"}
==
Reporting 347 files
==

astropy/config/__init__.py - 4/11
astropy/config/affiliated.py - 2/7
...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Exited with code 2
```

and the full build:

https://circleci.com/gh/astropy/astropy/4725

Is this something to do with the fact the GitHub URL is the ssh one? (this is how CircleCI was set up automatically)

I don't think I can set ``COVERALLS_REPO_TOKEN`` as this would need to be passed to forked pull requests which could then reveal the token, so I think this would be a security issue?

**Comment by bytewalls** [comment]
Happy to see this resolved itself, we will make note of it and track if future such issues occur.
