### ISSUE TITLE
0% coverage

### ISSUE THREAD

**Issue by BertrandBordage** [lemurheavy/coveralls-public#107]
After doing a trivial commit, coverage suddenly dropped to 0%: https://coveralls.io/r/BertrandBordage/django-terms

**Comment by mozillazg** [comment]
Same here: https://coveralls.io/builds/1858445

**Comment by monolithed** [comment]
Same here:  https://coveralls.io/r/monolithed/polyfiller

**Comment by fukuball** [comment]
Same here: https://coveralls.io/builds/3147103
