### ISSUE TITLE
Repositories not showing up in add new repository

### ISSUE THREAD

**Issue by beattyml1** [lemurheavy/coveralls-public#1072]
It seems that all the repos added since probably the last time I logged in like a year ago aren't showing.

Went in to add a new repo for a new project and it isn't there.

Particularly would like to add metatonic-platform (this github account).

**Comment by bytewalls** [comment]
You likely need to sync your new repos from the [Add Repos](https://coveralls.io/repos/new) page.

**Comment by beattyml1** [comment]
I've done that multiple times over the past few days. I've also try disconnecting and reconnecting the my Github OAuth. I've also tried with and without .coveralls.yml. 

The particular repo I'm trying is but I'm not seeing any other new repos either:
https://github.com/beattyml1/metatonic-platform/

**Comment by beattyml1** [comment]
I end up going with code climate for my code coverage for now, so I'm not too worried about it on my end but if you want to pursue the issue further to keep it from happening to another user I'd be happy to continue working with you.

**Comment by causztic** [comment]
I am facing the same issue as well. Tried re-adding my OAuth token and refreshing it multiple times did not make my new public repositories visible.

**Comment by bytewalls** [comment]
We are looking into this, sorry for the delay.

**Comment by beattyml1** [comment]
No worries, you're providing a free service I'm just grateful for having support period. Thanks for all your hard work!
