### ISSUE TITLE
Issue with merging results from Travis and CircleCI

### ISSUE THREAD

**Issue by astrofrog** [lemurheavy/coveralls-public#1073]
For Astropy we are now using the coveralls command to push results from both Travis and CircleCI, but it looks like the results aren't getting merged correctly on the CircleCI side:

https://coveralls.io/github/astropy/astropy

See in particular the recent change in the coverage graph:

<img width="563" alt="screen shot 2018-02-16 at 09 49 16" src="https://user-images.githubusercontent.com/314716/36301989-aff66fa8-12fe-11e8-96ad-b9321dd7230b.png">

What seems to be happening now is that Travis and CircleCI entries are treated as separate issues, and pull requests on CircleCI are reporting 0% coverage, probably because secure variables aren't passed to forks by default on CircleCI. Is there a way to make sure that CircleCI and Travis results for the same commit are merged?

**Comment by duncanmmacleod** [comment]
@astrofrog, did you get any response to this offline?

**Comment by astrofrog** [comment]
@duncanmmacleod - unfortunately not

**Comment by bytewalls** [comment]
@astrofrog, unfortunately, we don't currently support merging builds across different CI services. It is a feature that we are hoping to add soon though.
