### ISSUE TITLE
GitHub repository names are treated as case sensitive

### ISSUE THREAD

**Issue by jnothman** [lemurheavy/coveralls-public#1074]
GitHub repository names are case insensitive. Coveralls treats them as case sensitive.

This is an issue where the user renames the repo to change case between activating Travis and activating Coveralls.

It is also an issue that Coveralls is pedantic about the repository name case in badge URLs.

**Comment by clicky** [comment]
I have a similar issue with case sensitivity. I really don't want to have to rename an entire module in my project to $name<2>, effectively changing probably 40k lines and then commit changing the name back to $name so I can get that 'lowercase' to not be an issue.

This is mainly an issue with one of my modules in a repo follows this pattern ABcD, but locally always clones locally as abcd.

**Comment by afinetooth** [comment]
@clicketyclackety if you want to share the Coveralls URL for your repo and what coveralls integration you're using, we can try to find a few lines you can modify in a fork or something.
