### ISSUE TITLE
Unable to access to details of a repository ending with '.json' 

### ISSUE THREAD

**Issue by fmichaud** [lemurheavy/coveralls-public#1076]
Hello,

A repository of my project is named [pigalle.serializers.json](https://github.com/pigalle-io/pigalle.serializers.json).

HTTP front servers seems set the content-type to application/json when I'm requesting the URL of [Coveralls](https://coveralls.io) details : https://coveralls.io/github/pigalle-io/pigalle.serializers.json

Thank you for your help !

Regards,

PS. I can't change the name of my repository ;-)

**Comment by fmichaud** [comment]
Ok I will change my repository name...
But I think it's a real bug.

**Comment by bytewalls** [comment]
Thanks for the report, we will investigate this.
