### ISSUE TITLE
Branch coverage never shows up in coveralls.io

### ISSUE THREAD

**Issue by plroebuck** [lemurheavy/coveralls-public#1079]
<https://coveralls.io/github/cybertk/abao?branch=0.5.1>
<https://travis-ci.org/cybertk/abao/builds/348026800>

Tried using both grunt:coveralls module as well as input redirection to coveralls binary.
Both methods imply successfully completed (according to TravisCI), but no data for jobs coverage and no source files displayed by Coveralls.

How do I debug this issue?

**Comment by bytewalls** [comment]
@plroebuck closing this as it looks as though you have resolved the issue.

**Comment by plroebuck** [comment]
No, not resolved; @bytewalls, please reopen this issue.

Coveralls now shows 10 files (those that exist on [master](https://github.com/cybertk/abao/tree/master/lib)), yet the [0.5.1 branch](https://github.com/cybertk/abao/tree/0.5.1/lib) has 11 (`"cli.coffee"` only exists in this branch).

So where's the other file?

**Comment by bytewalls** [comment]
It looks as though your test suite, which is not generating any coverage information for that file. 

When I pull your repository locally and run tests of branch [0.5.1](https://github.com/cybertk/abao/tree/0.5.1), looking at the generated coverage information it does not appears as though there is any data for the `cli.coffee` file.

**Comment by plroebuck** [comment]
You're right. After more research, I see I need a different coverage setup to get my e2e tests (which run our code via CLI) to count lines for subprocesses as well. I also sadly concur that `cli.coffee` is not in the coverage file. So how do I get Coveralls to at least display the file with 0% coverage? Manually append `SF cli.coffee` to `coverage.lcov`?

**Comment by bytewalls** [comment]
That could be one solution. It sounds like it might fixing the symptom though, where the real issue might be that all source files don't automatically have coverage information generated by the test suite. I'm not really certain of your toolset and how to configure them to run as such though.

**Comment by plroebuck** [comment]
We have both unit and e2e tests. The e2e test exercises `cli.coffee` when our app (script) runs. Since the e2e tests from a user perspective, we're launching a subprocess to run our script for each test. Unfortunately, coverage isn't updated in subprocesses; therefore `cli.coffee` will never have coverage. Seems like this is the problem `nyc` solves for `instanbul`...
