### ISSUE TITLE
Multiple builds getting no data

### ISSUE THREAD

**Issue by bmw** [lemurheavy/coveralls-public#1080]
Starting between 6 - 7:30 AM UTC today, the coveralls site started reporting no data for multiple projects I work that have no relation to each other and use different coveralls clients. One example of this is https://coveralls.io/builds/15838092 who was sent data by https://travis-ci.org/certbot/certbot/jobs/349990410#L1306.

As of writing this there is no incident on http://status.coveralls.io/. Any idea what's going wrong?

**Comment by nickmerwin** [comment]
Hi @bmw we're working on mitigating: http://status.coveralls.io/incidents/x56my9j39368

**Comment by nickmerwin** [comment]
Ok this is resolved, thank you for your patience!
