### ISSUE TITLE
Coveralls builds are not finishing

### ISSUE THREAD

**Issue by ssmereka** [lemurheavy/coveralls-public#1081]
We have a private repository that is receiving coverage reports, creating a build, but the results of the build are not showing up in the coveralls repository screen.  It was working fine for over a year until today, nothing about how we submit coverage reports has changed.

**Comment by dcastil** [comment]
Same here, Coveralls doesn't finish checks in the latest [PR](https://github.com/dcastil/concrete/pull/8) of my public repo.

**Comment by nickmerwin** [comment]
Currently working on mitigating: http://status.coveralls.io/incidents/x56my9j39368

**Comment by nickmerwin** [comment]
Ok this is resolved, thank you for your patience!

**Comment by bhazelton** [comment]
We are experiencing this same issue now on our public repo.
See this [PR](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/485).
The coveralls build number is listed in the Travis log as 41913860
When I go to [build page](https://coveralls.io/jobs/41913860) it says `pending completion`
