### ISSUE TITLE
SOURCE NOT AVAILABLE for npm packages using files option

### ISSUE THREAD

**Issue by taras** [lemurheavy/coveralls-public#1085]
<img width="1138" alt="screen shot 2018-03-13 at 8 35 23 am" src="https://user-images.githubusercontent.com/74687/37341945-8c06df48-2699-11e8-8501-d910a63673df.png">

One of my projects is published as an `npm` package. A few months ago, we changed the setup to run tests against built assets rather than `src` files. This allows us to catch missing exports from the main package. 

When we made the switch, our coveralls results got all messed up. Our coverage dropped by about 20%. We'd like to figure out what's missing but we're not able to look at the reports because coveralls can't find our `dist` files. 

We do not include our dist files in the repository. Instead, we use [package.json#files](https://docs.npmjs.com/files/package.json#files) option to include the files in the package during `npm publish`. 

It would be awesome if coveralls was able to look up files in dist directory either from NPM or unpkg.com. You can see the built file [here](https://unpkg.com/microstates@0.6.1/dist/microstates.umd.js).

[Link to the report](https://coveralls.io/builds/15948571/source?filename=dist/microstates.umd.js)

**Comment by bytewalls** [comment]
Hi @taras, this sounds like a feature some people might find useful (well obviously you would, but perhaps others as well). I'm going to create a feature request for this on our product board.

I am closing the ticket for now but will let you know if this is something that we release.

**Comment by taras** [comment]
@bytewalls any chance you might have made this work?
