### ISSUE TITLE
Coverage reported as 0%

### ISSUE THREAD

**Issue by HyperBrain** [lemurheavy/coveralls-public#1086]
I did a README change today in my repo and coveralls reports 0% coverage now. According to the NYC/Istanbul output the lcov files are exactly as before. On Travis nothing changed and a merge build some hours ago still worked properly (that was a merge that changed source files).

![image](https://user-images.githubusercontent.com/5524702/37422036-d25f14de-27ba-11e8-8647-83601756fe84.png)

Specific build: https://coveralls.io/builds/15976175

I am sure that this did not happen the last time I did a release preparation commit/merge of my README.

**Comment by Kirill89** [comment]
Looks like even if [source files](https://github.com/Trax-retail/mahsan/commit/259434ee08e53aac0c701a18966712f9c018f8fc) changed.

**Comment by HyperBrain** [comment]
Changed the title to reflect @Kirill89 's findings

**Comment by HyperBrain** [comment]
Just checked. My referenced build above now shows the correct statistics again and all NaN's are gone.
Seems to be fixed. Closing now.
