### ISSUE TITLE
Typescript setup instructions are actually Ruby

### ISSUE THREAD

**Issue by robsimmons** [lemurheavy/coveralls-public#1089]
When I visit

https://coveralls.io/github/calculemuscode/abt-js

It claims it's going to give me TYPESCRIPT SET UP FOR COVERALLS. Which is great! Except that it then very clearly gives me Ruby setup for Coveralls. 😂

**Comment by bytewalls** [comment]
Sorry about that hopefully you will find this link much more useful! https://github.com/nickmerwin/node-coveralls

**Comment by praveendath92** [comment]
An year later and it still shows the same  😂

**Comment by fogfish** [comment]
Years are counting but issue still remains!

**Comment by BlueGhostAlt** [comment]
Still an issue!
