### ISSUE TITLE
Unable to see private repositories

### ISSUE THREAD

**Issue by cheekytinker** [lemurheavy/coveralls-public#1092]
We have an account, ElateralLtd, which we have been using successfully to cover private repositories. At some point recently our private repos have disappeared from the site. We have checked that our git hub account used to allow coveralls to access our private repos has access to the projects that are missing. We have hit the refresh private repos button, but with no success, Can you investigate please

**Comment by bytewalls** [comment]
Can you tell me one private repo which you used to have access to and now do not see so we can trace where the problem might be? Thanks! Sorry for the inconvenience.
