### ISSUE TITLE
Can't see organization repositories

### ISSUE THREAD

**Issue by addicted2sounds** [lemurheavy/coveralls-public#1094]
A member of my organization `WBS` have purchased Pro plan, but I can't see the repo to see the coverage generated. My personal is free plan. Let me know how what should I accomplish to be able to setup?

**Comment by xn** [comment]
same

**Comment by bytewalls** [comment]
Hi @addicted2sounds @xn, you'll need to upgrade your OAuth scope here to access those private repos:

https://coveralls.io/refresh?private=true

Thanks!

**Comment by addicted2sounds** [comment]
@bytewalls That was done with help of manuals. Nonetheless, I can't see the repo after update too

**Comment by addicted2sounds** [comment]
@xn thanks :) finally I got that working
