### ISSUE TITLE
Error 500 from travis_ci when calling coveralls

### ISSUE THREAD

**Issue by C0chett0** [lemurheavy/coveralls-public#1096]
Since last friday we keep getting the same error from coveralls when building in travis_ci

Command used : 
cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

Result :
.................................................../node_modules/coveralls/bin/coveralls.js:19
       throw err;
       ^
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}

We've tried to debug on our side, it looks ok.

Any idea ?

**Comment by bytewalls** [comment]
Which repo is giving you issues?

**Comment by C0chett0** [comment]
Personnaly this one : https://github.com/Interencheres/indb-thor-api/
It's private but I'm confident almost all the repos from our organization have the same issue.

**Comment by somentelucas** [comment]
Having the same issue here, did you find any solution for this?
