### ISSUE TITLE
Renaming a repo loses history

### ISSUE THREAD

**Issue by pranaygp** [lemurheavy/coveralls-public#1097]
We had a github project setup with coveralls. Github repo is`zeit/abc` and the corresponding coveralls link is `https://coveralls.io/github/zeit/abc`

However, we later renamed the repo on github to `zeit/def`. However, now, accessing 
`https://coveralls.io/github/zeit/abc` results in 'ACCESS DENIED', however going to `https://coveralls.io/github/zeit/def` gives me what seems to be a brand new project on coveralls. All my history on coveralls from the project are lost, and a new `repo_token` was generated.

History should be carried over when a repo is renamed

**Comment by aronisstav** [comment]
Have you checked the 'Change source' link to do this (following your naming scheme the link should be visible at `https://coveralls.io/github/parapluu/zeit/abc/settings`)?
