### ISSUE TITLE
The coverage badge isn't updated

### ISSUE THREAD

**Issue by vahancho** [lemurheavy/coveralls-public#1099]
After the last commit [coverage report says](https://coveralls.io/github/vahancho/nkar): "COVERAGE INCREASED (+65.7%) TO 91.791%". The title also indicates 92% test coverage. However the corresponding badge still shows the old value 26%. GitHub repository page shows the same badge. I saw many reports about outdated badges, but this is case, when badge is not updated on Coveralls' page itself.

**Comment by bytewalls** [comment]
It appears as though this issue has been fixed from my look over to your repo.
