### ISSUE TITLE
How do we get a tree view of our source?

### ISSUE THREAD

**Issue by pabender** [lemurheavy/coveralls-public#1101]
This is more of a question than a problem.

One of our developers sees a tree view of the source for our project for his fork:

https://coveralls.io/github/rhwood/JMRI

All we see in the main repository is the list of sources:

https://coveralls.io/github/JMRI/JMRI

How do we add the tree view?

**Comment by bytewalls** [comment]
@pabender This is a small new feature we are currently in the process of rolling out to make it easier to navigate your coverage information on the site. 

Currently, newer repositories have the feature, but we are working on some performance improvements before rolling out for all.

**Comment by pabender** [comment]
Thans
