### ISSUE TITLE
Wrong coverage result for a file

### ISSUE THREAD

**Issue by MaxLap** [lemurheavy/coveralls-public#1102]
If you look at this build: https://coveralls.io/builds/16335942

You can see that a single file is not at 100% of coverage. (active_record_compat.rb) However, if you open that file, then you will see it displayed as 100%.

https://coveralls.io/builds/16335942/source?filename=lib/active_record_where_assoc/active_record_compat.rb

Different jobs have different results in that file because it deals with different versions of my dependencies. I expect this file, in the list of file, to display 100% and at the same time, to make the coverage result of that build to be 100%.

Looking at the list of builds, the problem started happening on March 15th (The previous build that had 100% was on March 11th). https://coveralls.io/repos/173089/builds

Thank you

**Comment by bytewalls** [comment]
@MaxLap we are looking this issue, sorry for the inconvenience.

**Comment by bytewalls** [comment]
We have deployed a fix for this. Sorry again for the inconvenience.

**Comment by MaxLap** [comment]
Thank you! That is indeed solved... except something else seems broken?

If you look at the badge, its now showing 52% while the project shows 100%:
https://coveralls.io/github/MaxLap/activerecord_where_assoc

Want me to open a new issue or it's related?

**Comment by bytewalls** [comment]
Should be fixed now, sorry about that.
