### ISSUE TITLE
Missing coverage information for Vim

### ISSUE THREAD

**Issue by chrisbra** [lemurheavy/coveralls-public#1105]
Hi,
I am missing coverage information for the latest [vim build](https://coveralls.io/builds/16455928). Can someone explain what is going on?

**Comment by bytewalls** [comment]
@chrisbra it looks like there were two patches added to the vim repository altering the way coverage was reported that resulted in first a large decrease in reported coverage, and then the coverage data being sent being empty. I suspect that given that these two changes happen to coincide with the coverage changes issues, they are likely related.

Looking at the last build before `patch 8.0.1693` [here](https://coveralls.io/builds/16444996) you see that before there were two jobs being sent one with `BUILD=yes` and one with `BUILD=no`, and [after](https://coveralls.io/builds/16446254) only receive the `BUILD=no`. Perhaps this change broke something with coverage in the `BUILD=yes` job?

The other change is `patch 8.0.1696` after this looking through our system it appears as though the coverage information we received via API was empty.

**Comment by chrisbra** [comment]
Yes, patch [8.0.1693](https://github.com/vim/vim/commit/1acdb3f30104576c36f83d422fb67a805b0ce58a) removed excluding the xxd subproject from coverage. Because we finally got a test for xxd (patch [8.0.1689](https://github.com/vim/vim/commit/29f9ed20b42e7badea6cfb82fb1fb8d71f33e282)) so it made sense to remove that restriction. However, looking at the corresponding Travis-CI log (e.g. [here](https://travis-ci.org/vim/vim/jobs/364771625)), we can see that coverage crashed because `src/xxd.c` could not be found. This made sense, because it actually is `src/xxd/xxd.c`. So Patch [8.0.1696](https://github.com/vim/vim/commit/d60e0a1d202d49503ba95a40c165172c8f61db7a) we started includeing the `xxd` directory explicitly to the coverage call. In the coresponding Travis CI log (e.g. [here](https://travis-ci.org/vim/vim/jobs/364994605)) you can see, that at least coverage does not crash anymore, and runs through successfully:
```
xxd.c: No such file or directory
File 'xxd.c'
Lines executed:59.22% of 385
xxd.c:creating 'xxd.c.gcov'
```
However it complains about the missing `xxd.c` file. However, from the logs it looks like the statistics have been sent successfully. 

So if `-i src/xxd` is not the right way to include another subproject build directory, what would be the correct parameter option? Do we need to link `src/xxd/xxd.c` to the `src/xxd.c` to make it work? Or are there other alternatives? 

This was also discussed on the [vim-dev mailinglist](https://groups.google.com/forum/#!topic/vim_dev/D2mfdAAZR7g). If you have anything to add, please chime in :)

Thanks for your help. CC'ing Bram so he knows what we are talking about @brammool
