### ISSUE TITLE
Coverage decrease threshold for failure under 0.02% not work

### ISSUE THREAD

**Issue by kelly-apollo** [lemurheavy/coveralls-public#1106]
Coveralls settings

![image](https://user-images.githubusercontent.com/4319332/38909501-6a731980-42f7-11e8-8b33-9c11084829e5.png)

PR coverage decrease 0.06% is pass still.

![image](https://user-images.githubusercontent.com/4319332/38909566-b19966ca-42f7-11e8-9d04-750884d100ab.png)

**Comment by bytewalls** [comment]
If you want the system to fail for any coverage decrease you should not set the coverage thresholds here.

Currently default behavior is fail for any decrease. If your coverage threshold for failure is set, the coverage decrease threshold for failure is ignored. 

We have a fix in the pipeline to make this functionality behave as we think most would expect it to.
