### ISSUE TITLE
Unknown commit and drop in coverage

### ISSUE THREAD

**Issue by ben-manes** [lemurheavy/coveralls-public#1109]
Coverage dropped from 94% to 15% with a commit that is under my name, but not mine. The commit shows 3 Scala files, whereas my project is in Java. The source cannot be opened. It looks like some one else's commit was bled into my project due to a bug in Coveralls, as the credentials are private.

https://coveralls.io/builds/16642851

**Comment by bytewalls** [comment]
@ben-manes thanks for the report, we will look into ways which we can further confirm builds belong to the repo.
