### ISSUE TITLE
Source Code Tree

### ISSUE THREAD

**Issue by mikemhenry** [lemurheavy/coveralls-public#1110]
I really love the new source code tree, but I've recently restructured where my tests are in my repo and now the tree looks like this:
 
![image](https://user-images.githubusercontent.com/11765982/39318642-e2cebdd6-493b-11e8-8d53-a1e7aacf7186.png)

I was able to to modify the url so that I can see the source code when I click on files:
https://coveralls.io/builds/16712827/source?filename=/opt/atlassian/pipelines/agent/build/epoxpy/abc_type_epoxy_dpdfene_simulation.py

But it looks like the tree view doesn't take that into account.
Do you have any suggestions? If this feature is still in flux then consider using similar logic for viewing source code, so folders can be ignored.

Thanks!
Mike

**Comment by bytewalls** [comment]
Mike,

Thanks for your feedback. The individual file names are links to the source view (the link you provided) in the new tree view.

That said I can see how the user experience of clicking 7 times to see the first file would be very annoying. I will create a ticket on our end around improving this user experience.

FYI: You can also still see the old list view by clicking on the `LIST` tab.
