### ISSUE TITLE
"0 of 0 (NaN%) changed or added relevant lines in 0 files are covered."

### ISSUE THREAD

**Issue by papandreou** [lemurheavy/coveralls-public#1111]
I received a weird comment from coveralls: https://github.com/Munter/subfont/pull/21#issuecomment-384692236 -- what's the deal with NaN%?

**Comment by bytewalls** [comment]
@papandreou thanks for reporting this. Looks like a simple divide by zero error, we should have a patch ready to go out to solve this in our next release.
