### ISSUE TITLE
All source files isn't listed and coverage rate is wrong

### ISSUE THREAD

**Issue by hakdogan** [lemurheavy/coveralls-public#1113]
Hi all,

Coverage rate of my [project](https://github.com/hakdogan/Vert.x) is %0 

The reason for this is that the all source files of my project isn't listed under the project source files section.

![screen shot 2018-05-03 at 13 26 28](https://user-images.githubusercontent.com/657846/39571888-b71cb4a0-4ed5-11e8-934b-6e82c4f0f5bc.png)

For similar reasons the coverage rate is %100 in another [repository](https://github.com/hakdogan/ElasticSearch).

![screen shot 2018-05-03 at 13 30 20](https://user-images.githubusercontent.com/657846/39572017-46a1708e-4ed6-11e8-90f8-133e4f41ebf4.png)

What is the reason of this, any idea?

**Comment by bytewalls** [comment]
@hakdogan,

Coveralls only lists coverage data which is reported to us, if you have files with zero coverage which are not reported as a part of your coverage suite we do not keep track of those files. 

You should make sure you configure your test suite is logging coverage for all relevant files, and reporting that information to coveralls.

**Comment by hakdogan** [comment]
Hi @bytewalls 

> You should make sure you configure your test suite for logging coverage for all relevant files, and reporting that information to coveralls.

How can I be sure of this?
