### ISSUE TITLE
Report submission failures - error 500

### ISSUE THREAD

**Issue by ledoyen** [lemurheavy/coveralls-public#1114]
Hello,

Building on travis-ci.**com** for the first time (was using .**org** before), I encounter a non-deterministic failure when submitting a coverage report :
```
[INFO] Starting Coveralls job for travis-ci (122742988)
[INFO] Using repository token <secret>
[INFO] Git commit c4962ed in master
[INFO] Writing Coveralls data to /home/travis/build/fridujo/rabbitmq-mock/target/coveralls.json...
[INFO] Processing coverage report from /home/travis/build/fridujo/rabbitmq-mock/target/site/cobertura/coverage.xml
[INFO] Successfully wrote Coveralls data in 194ms
[INFO] Gathered code coverage metrics for 13 source files with 1205 lines of code:
[INFO] - 311 relevant lines
[INFO] - 172 covered lines
[INFO] - 139 missed lines
[INFO] Submitting Coveralls data to API
[ERROR] Submission failed in 414ms while handling I/O operations
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.791 s
[INFO] Finished at: 2018-05-07T15:24:27Z
[INFO] Final Memory: 49M/979M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project rabbitmq-mock: I/O operation failed: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Coveralls API internal error) -> [Help 1]
```

After restarting the same build a few times, submission worked, by the linked commit is not the right one (in fact it is not related to the project I'm building) : https://coveralls.io/builds/16866813
Committer and commit message are false.

Is there any correction possible about the related commit linked in Coveralls ?

Thanks in advance,

**Comment by bytewalls** [comment]
@ledoyen we are investigating this right now, thanks for your report.

**Comment by bytewalls** [comment]
@ledoyen you will need to update your `.coveralls.yml` file to have to have the service-name set to `travis-pro.` 

When set to `travis-ci` (the default if you have nothing set) our system is pulling data from the travis-ci.org api as opposed to the travis-ci.com api. We are looking into ways to automatically detect this in the future, but right now you will need to update the specification. 

Please let me know if this does not solve your problem and I will reopen the issue.

**Comment by ledoyen** [comment]
Thanks for the quick answser.

However, setting `service-name` to `travis-pro` led to another submission error :
```
[INFO] Starting Coveralls job for travis-pro (122896798)
[INFO] Using repository token <secret>
[INFO] Git commit a667a95 in master
[INFO] Writing Coveralls data to /home/travis/build/fridujo/rabbitmq-mock/target/coveralls.json...
[INFO] Processing coverage report from /home/travis/build/fridujo/rabbitmq-mock/target/site/cobertura/coverage.xml
[INFO] Successfully wrote Coveralls data in 183ms
[INFO] Gathered code coverage metrics for 13 source files with 1205 lines of code:
[INFO] - 311 relevant lines
[INFO] - 172 covered lines
[INFO] - 139 missed lines
[INFO] Submitting Coveralls data to API
[ERROR] Submission failed in 397ms while processing data
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.181 s
[INFO] Finished at: 2018-05-08T09:50:11Z
[INFO] Final Memory: 50M/989M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project rabbitmq-mock: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]
```

**Comment by wallynm** [comment]
i was getting this 500 error into my application but i've forgot to update my COVERALLS_REPO_TOKEN into circleci settings, it wasn't working because it couldn't certify it was an authorized access...
We've updated the config into coveralls but forgot to sync into CI config.

After the update took 3 days to our coveralls stop working, we understood that coveralls have some kind of cache, at some point it expired and CI couldn't authenticate returning error 500.
At our point of view the error 500 could have some kind of possible fixes like double check if the CI it's correctly configured...
