### ISSUE TITLE
integration with VSTS

### ISSUE THREAD

**Issue by tvald** [lemurheavy/coveralls-public#1115]
I know you're still working on GitLab support, but what are the chances that you'll be able to integrate with Visual Studio Team Services git repositories at some point?

I've enjoyed using Coveralls for various projects in the past, and would love to continue using it as I move to a new organization and new projects which happen to be hosted in VSTS.

(VSTS also does CI, btw.)

**Comment by bytewalls** [comment]
@tvald We will certainly look into integrating with VSTS. I've created a feature request for this for the team to discuss.

**Comment by FSM1** [comment]
if this does come up for discussion I also vote in favor of 👍
