### ISSUE TITLE
"Source files on master: 100%", Master Badge: "coverage unknown"

### ISSUE THREAD

**Issue by dfee** [lemurheavy/coveralls-public#1116]
Is there something I'm missing here? I have 100% coverage, but the badge doesn't show anything.

The project is located here: https://coveralls.io/github/dfee/forge

**Comment by francisbrito** [comment]
Hello @dfee,

It seems test coverage is being reported for the branch `asclass`, while the badge is being generated for the branch `master`. Can you try manually triggering a `coveralls` build for `master` branch?

**Comment by dfee** [comment]
It's now showing for `master`. Does that coverage badge only reflect the last commit? Should I somehow limit pushing data to coveralls if not on `master`?

**Comment by francisbrito** [comment]
> Does that coverage badge only reflect the last commit?

It seems to me that it will reflect the total coverage in the branch specified by the `?branch=<branch_name>` query parameter of the URL the badge points to.

> Should I somehow limit pushing data to coveralls if not on master?

I don't see a reason why. Travis-CI should be able to trigger coveralls builds for any branch you push to. The only consideration to keep in mind is making sure the badge points to the branch you're expecting.

**Comment by bytewalls** [comment]
@dfee,

The badge will point at the master build only, it looks like there might be something else going on with the timing and coverage results of your various jobs. It looks like you might have parallel jobs running but are not using the parallel webhook, which may result in your job being processed as finished before all the job results are in. 

This should help with setting that up correctly: http://docs.coveralls.io/parallel-build-webhook
