### ISSUE TITLE
Coverage percent is NaN

### ISSUE THREAD

**Issue by mrix** [lemurheavy/coveralls-public#1117]
Hi all. Please take a look at this build https://coveralls.io/builds/16935420 (`src/AnnotationsReader/` or `src/Errors` directories have NaN coverage percent). The corresponding [Travis build](https://travis-ci.org/xiag-ag/typescript-to-json-schema/builds/377631140) looks correct.

And [the previous build](https://coveralls.io/builds/16886678) was OK.

**Comment by bytewalls** [comment]
Thanks for the report, we will look into this.

**Comment by danielx0328** [comment]
I am also seeing this issue...
https://coveralls.io/builds/17038494

**Comment by avakar** [comment]
The same issue is happening to me: https://coveralls.io/builds/17994080
