### ISSUE TITLE
Coverage percentage on badge shows different than what is reported for repository

### ISSUE THREAD

**Issue by monocongo** [lemurheavy/coveralls-public#1120]
There seems to be a lag between when the coverage percentage changes and the image displayed by the badge is updated. For me this seems to happen more on the README for my [GitHub project](https://github.com/monocongo/climate_indices) than it does for the associated [documentation](https://climate-indices.readthedocs.io/en/latest/) that's hosted on readthedocs.io.

For example, I recently added some additional tests that brought my project's coverage up from 89% to 91%. On the documentation page the badge correctly displays 91%, but on the README it still shows as 89%. I'd like to do something to force the badge image to update to the correct percentage for both, but I've not found a way to do this yet. Maybe this has something to do with the README being Markdown and the documentation being reStructuredText, so when the badge image is fetched it's more up-to-date on the documentation page whereas the GitHub project is maybe using a cached badge image that's being displayed by the README? Or maybe it's related to a difference between how GitHub and readthedocs.io cache images that are included on pages they host?

In case it's of interest I've also posted [a question about this on StackOverflow](https://stackoverflow.com/questions/50355516/how-to-update-coveralls-badge-image-to-reflect-actual-coverage-percentage).

Thanks in advance for any help with this issue.

**Comment by monocongo** [comment]
Thanks! If I can help please let me know.

**Comment by shivajivarma** [comment]
@bytewalls : don't think the issue is with github, because other badges like travis-ci working fine.

**Comment by bcullman** [comment]
we are still seeing this in our repo:

https://github.com/SAP/fundamental-react

89% in the readme.md, 92% at the coverall.io site.

**Comment by ruscon** [comment]
+1, not fixed

**Comment by nickmerwin** [comment]
@ruscon can you link to the repo in question?

**Comment by ruscon** [comment]
> @ruscon can you link to the repo in question?

https://github.com/go-parrot/geocoder

**Comment by nickmerwin** [comment]
@ruscon thanks, i'm seeing both as 90%, are you showing otherwise?

![image](https://user-images.githubusercontent.com/1129/53501720-850d7080-3a61-11e9-9501-8fb9ed73b51c.png)

![image](https://user-images.githubusercontent.com/1129/53501730-8b035180-3a61-11e9-9dc7-da85a2b99a05.png)

**Comment by ruscon** [comment]
84%
http://take.ms/IYRtr

**Comment by nickmerwin** [comment]
@ruscon could you copy the image address on Github, then `curl -I` it like so?

```$ curl -I https://camo.githubusercontent.com/5c44723ccd236cf159b9d0b4a880fe932f1f2257/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f676f2d706172726f742f67656f636f6465722f62616467652e7376673f6272616e63683d6d6173746572
HTTP/1.1 200 OK
Content-Type: image/svg+xml
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Last-Modified: Tue, 20 Jan 2015 21:33:45 GMT
Server: github-camo (cdda9389)
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-GitHub-Request-Id: 9A98:7D3E:24EF7:2694A:5C76B07A
Content-Length: 724
Accept-Ranges: bytes
Date: Wed, 27 Feb 2019 15:45:09 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-lax8651-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1551282310.615662,VS0,VE336
Vary: Accept-Encoding
X-Fastly-Request-ID: 2886adbcc8c9d485d34ab3799e44e7bb3f03b1c3```

**Comment by ruscon** [comment]
```
$ curl -I https://coveralls.io/github/go-parrot/geocoder\?branch\=master\&service\=github

HTTP/1.1 200 OK
Date: Wed, 27 Feb 2019 15:47:24 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=dac93f59a49b30d93352c4749205fa0631551282443; expires=Thu, 27-Feb-20 15:47:23 GMT; path=/; domain=.coveralls.io; HttpOnly
Cache-Control: max-age=0, private, must-revalidate
ETag: W/"b681e82d5abfa5868002111f5cf6050c"
Set-Cookie: _coveralls_session=aCs1cndEWUp5RWs4T2JXZ1dDVzhJNU9oOGl4b1dUK2J1Um9KZFNvMjcxeFhBNWgzKzVSaWtPbXlOMHEzODRhZzhjOHh0OXExcXB6Q3dvQ0szS01na1hHcU1qT3RQVXZraGxOZmdscHNTelMyanJNNkF1QWNNeDFHazZZQkFmSmMyazdkdzFGOCtqY1NiYkU1TXd5NjFLa2VqZ3BPMmpGYjQvbXlKZkdaTmRCL0xPOUU2V0VlTkJvQ3ppdjBJSEhHLS1wenFwVlR3WHc3cVAwT2tBcmRBUFJnPT0%3D--d0b6bdfa992495269a01415fef501505067e4552; path=/; expires=Wed, 13 Mar 2019 14:47:24 -0000; secure; HttpOnly
Status: 200 OK
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger Enterprise 5.3.7
X-Powered-By: cloud66
X-Request-Id: 7b04690d-edee-4287-8520-12b77ddcab92
X-Runtime: 0.647977
X-XSS-Protection: 1; mode=block
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4afbca278ecdb6da-KIV
```

**Comment by nickmerwin** [comment]
@ruscon ah actually meant the badge on the Github repo:

https://github.com/go-parrot/geocoder

**Comment by ruscon** [comment]
```
$ curl -I https://camo.githubusercontent.com/5c44723ccd236cf159b9d0b4a880fe932f1f2257/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f676f2d706172726f742f67656f636f6465722f62616467652e7376673f6272616e63683d6d6173746572

HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Content-Type: image/svg+xml
Last-Modified: Tue, 20 Jan 2015 21:33:52 GMT
Server: github-camo (cdda9389)
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-GitHub-Request-Id: 4950:6B7F:F51FC:10AEFF:5C7678AA
Content-Length: 724
Accept-Ranges: bytes
Date: Wed, 27 Feb 2019 15:52:31 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-fra19131-FRA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1551282751.832473,VS0,VE300
X-Fastly-Request-ID: c766e48fdbb25f9f92d2e08fd1cf83c4afec38e6
Timing-Allow-Origin: https://github.com
```

**Comment by ruscon** [comment]
I opened it on incognito and it became 90%
Browser cache

**Comment by nickmerwin** [comment]
Ok thanks @ruscon I'll close the issue for now.
