### ISSUE TITLE
Build list not related to project

### ISSUE THREAD

**Issue by funilrys** [lemurheavy/coveralls-public#1121]
I just setup coveralls into a non-master branch and it's weird to see that the build which are listed at https://coveralls.io/repos/214298/builds are not related to [my project](https://github.com/funilrys/PyFunceble) ... 

Thanks in advance for any clarification/help.

**Comment by bytewalls** [comment]
@funilrys,

We had some issues with travis-ci builds after travis started allowing free on travis-ci.com and started transition .org to .com for free services. We have released a patch to solve these issues, sorry for the inconvenience please let us know if you see any other problems in the future.
