### ISSUE TITLE
Combine python-coveralls with jest 'collectCoverage'

### ISSUE THREAD

**Issue by jeff1evesque** [lemurheavy/coveralls-public#1123]
I am implementing [`python-coveralls`](https://github.com/jeff1evesque/machine-learning/blob/196ec400a51741b0c7d1030646f67c2c5dec93e2/.travis.yml#L27-L28) (which is successfully being sent to coveralls), with newly added jest [coverage](https://github.com/jeff1evesque/machine-learning/blob/193f864d77311c271d0ea894f562a033ec70badb/test/jest/jest.config.js#L3-L4).  But, I'm not sure how to combine the two into a single result, before being sent to [coveralls.io](https://coveralls.io/github/jeff1evesque/machine-learning?branch=master). 

Coverage from Jest:

```bash
root@browserify:/var/machine-learning# ls -l
total 380
-rw-r--r--  1 root root  84923 May 19 19:43 clover.xml
-rw-r--r--  1 root root 246408 May 19 19:43 coverage-final.json
drwxr-xr-x  4 root root   4096 May 19 19:41 interface
drwxr-xr-x 16 root root   4096 May 19 19:43 lcov-report
-rw-r--r--  1 root root  39877 May 19 19:43 lcov.info
drwxr-xr-x  9 root root   4096 May 19 19:40 src
```

**Note:** the full [issue](https://github.com/jeff1evesque/machine-learning/issues/3087) can be further reviewed.

**Comment by bytewalls** [comment]
@jeff1evesque,

I would recommend reporting the two test suite results separately and using our parrallel builds webhook. You can use the [coveralls node module](https://www.npmjs.com/package/coveralls) to report the jest coverage.  This will report 2 jobs which will be aggregate into to the same build on coveralls. On the coveralls site you would be able to view the total coverage or coverage only from each independent test suite.

The parallel webhook ensures that we don't comment on pull requests until all coverage data has been processed. You can see documentation on it [here](http://docs.coveralls.io/parallel-build-webhook)

Hope this helps!

**Comment by jeff1evesque** [comment]
@bytewalls, how do I implement the webhook? I was looking at the [documentation](http://docs.coveralls.io/parallel-build-webhook) you suggested. Do I need to define all three lines:

```bash
COVERALLS_PARALLEL=true
https://coveralls.io/webhook?repo_token=(your repo token)
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
```

Specifically, where do I define the first two lines. Can they go into the [`.coveragerc`](https://github.com/jeff1evesque/machine-learning/blob/d995dab7a0aed0e8b6a5371c604c6abaad48aaf1/.coveragerc)? Also, is there any difference between `(your repo token)`, and `COVERALLS_REPO_TOKEN`. Since I version control my [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/196ec400a51741b0c7d1030646f67c2c5dec93e2/.travis.yml), I probably don't want to add my repository token in there.

**Comment by jeff1evesque** [comment]
Made some additional changes to my [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/82cb93bc3a0aa16fbd1a64395f422041498de8fa/.travis.yml#L11-L20):

```yaml
env:
  - COVERALLS_PARALLEL=true

##
## implement coveralls.io webhook
##
##     https://github.com/lemurheavy/coveralls-public/issues/1123#issuecomment-390699100
##     https://github.com/lemurheavy/coveralls-public/issues/1123#issuecomment-391030777
##
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
```

My builds are [failing](https://travis-ci.org/jeff1evesque/machine-learning/builds/382708610), and likely a result of poorly defining the corresponding [`npm run test:coveralls`](https://github.com/jeff1evesque/machine-learning/blob/9bdcda434d3aecc29bb3f51a66aa5dc7937346c5/test/unit-tests#L78) within the `docker` constructs. But, just wondering if you could confirm that my coveralls definitions within my `.travis.yml` is properly defined.

**Comment by jeff1evesque** [comment]
@bytewalls, thanks for your help. Finally got it working:

- https://github.com/nickmerwin/node-coveralls/issues/126#issuecomment-393643393
- https://github.com/jeff1evesque/machine-learning/pull/3235
