### ISSUE TITLE
Switched my repos to travis-ci.com and it can't push to coveralls anymore

### ISSUE THREAD

**Issue by bitboxer** [lemurheavy/coveralls-public#1124]
Hi, 

I moved my open source repos to the [new travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) infrastructure. Sadly now my builds fail because coveralls can't find the repo:

`** (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, body = {"message":"Couldn't find a repository matching this job.","error":true}).`

Can you help me debug this?

Thanks <3

* [the build](https://travis-ci.com/signdict/website/builds/73911116)
* [my project](https://github.com/signdict/website/)

**Comment by bytewalls** [comment]
Hi @bitboxer,

We are aware of issues with the transfer from travis-ci.org to travis-ci.com, I am told we have a fix in the pipeline that should be released soon, I will update you when I can confirm it is working again.

Sorry for the inconvenience!.

**Comment by bitboxer** [comment]
Awesome. Thank you 👍
