### ISSUE TITLE
Coverage reports stopped working for a while for two of our repositories

### ISSUE THREAD

**Issue by quetzyg** [lemurheavy/coveralls-public#1125]
Hi there!

Like stated in the title, the coverage reports we've been sending from **TravisCI** `after_success`, haven't been picked up for a few months, now.

These are the two (private) repos:
https://coveralls.io/github/VICEMedia/video-library
https://coveralls.io/github/VICEMedia/service-video-library

On the last one, we even regenerated the repo token and did a resync with github, but got the message: `No new info detected.`

This seems a similar issue to #1067 and other issues I've found.

How can we solve this?

**Comment by bytewalls** [comment]
@quetzyg,
We are investigating these issues, sorry for the inconvenience. What library are you using to report coverage?

**Comment by quetzyg** [comment]
Hi @bytewalls,

On one of the repos we were using `satooshi/php-coveralls`, but given it has been abandoned (and suspecting it might be the issue), we replaced it with `php-coveralls/php-coveralls` (2.0.0).

On another one, we're using node coveralls (2.12.0).

**Comment by valendesigns** [comment]
It's not abandoned `satooshi/php-coveralls` is the old location of `php-coveralls/php-coveralls` on GitHub which should redirect automatically.

**Comment by quetzyg** [comment]
In any case, we're now using `php-coveralls/php-coveralls`, which still didn't sort the issue, but we had to try anyway.

**Comment by valendesigns** [comment]
I'm dealing with the same issue. Troubleshooting it now, but I suspect it's on the coveralls.io side.

**Comment by quetzyg** [comment]
Hi @bytewalls, any progress with the issue?

**Comment by bytewalls** [comment]
@quetzyg,

We released a fix that got your builds started processing, but they weren't pulling in some important information with regards to the git branch data belongs to (likely the cause of initial errors).

I'm told we have a patch that will fix this coming out soon. I'll let you know when that has been deployed.

Thanks for you patience, sorry for the inconveniences.

**Comment by bytewalls** [comment]
@quetzyg,

We released that second patch yesterday, and things appear to be resolved on your repos.
