### ISSUE TITLE
Coveralls no longer showing new points on the history of coverage

### ISSUE THREAD

**Issue by hbursk** [lemurheavy/coveralls-public#1126]
I made a change to my coveralls setup to exclude some files that had not been excluded previously. Since then, Coveralls has seen all my new commits as a single data point rather than an evolving history. Now to see the current coverage, I need to dive into the last job and take a look at the number at the top of folder tree which is about 89%, while the dashboard and the coverage markdown badge currently shows 80%. 

Is it possible to correct this issue without deleting and re-adding the repo?

**Comment by bytewalls** [comment]
@hbursk, can you provide me a link to the repo and I can take a look into it? Thanks.

**Comment by hbursk** [comment]
Hey Jordan. It's a private repo, but here's the coveralls link. https://coveralls.io/github/fenderdigital/fd-instrument-toolbox
