### ISSUE TITLE
100% coverage but badge showing coverage unknown

### ISSUE THREAD

**Issue by pensierinmusica** [lemurheavy/coveralls-public#1127]
Hi,

For a library that I built Coveralls correctly reports 100% code coverage on the build, but the badge then reports coverage as unknown: https://coveralls.io/github/pensierinmusica/js-promisify

Can you please look into it?

Thanks!

**Comment by bytewalls** [comment]
@pensierinmusica,

We have found the issue with this and are working on getting a fix put together. Sorry for the inconvenience, we will let you know when it has been resolved.

**Comment by pensierinmusica** [comment]
👍 Thanks!

**Comment by bytewalls** [comment]
@pensierinmusica We released a patch for this yesterday. Thanks for your patience, sorry for the inconvenience.

**Comment by pensierinmusica** [comment]
thanks @bytewalls!
