### ISSUE TITLE
Coveralls website - Code on github error 404

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [lemurheavy/coveralls-public#1134]
The **code on github** link on the repositories coverall status page links to an unexisting page.

**Comment by bytewalls** [comment]
@Mixone-FinallyHere what repo are you seeing this issue with? The url should be `github.com/<username>/<repo>/tree/<branch>`, I can look over your repo and see if there have been issues pulling branch information for it.

**Comment by Mixone-FinallyHere** [comment]
It is a private repo, could that be the case?

bbrfc-celtic / website-dev
