### ISSUE TITLE
Unchanged coverage received negative coverage

### ISSUE THREAD

**Issue by h3xstream** [lemurheavy/coveralls-public#1135]
I am integrating a pull request : 
https://github.com/find-sec-bugs/find-sec-bugs/pull/394

There is a file that is unrelated to the changes that received negative coverage. The thing is that looking at the upstream master build coverage we can see that the coverage is unchanged in this file.

Master branch:
https://coveralls.io/builds/17241747/source?filename=plugin-graph/src/main/java/com/h3xstream/findsecbugs/graph/GraphInstance.java

## Problematic changeset

Initialy I had 3 commits in the PR.

1. Merge with remote
2. Actual change
3. Merge with remote

The result coverage was pointing to builds/17241747 (master branch) With negative coverage. (-0.3%) and therefore failing the build.

## Temporary solution

I rebase my changeset to place my change in the last commit. This solve the issue. I am now +0.004% with the same commits.

1. Merge with remote
2. Merge with remote
3. Actual change

**Comment by newtrat** [comment]
Maybe caused by #1019? For at least some users Coveralls reports % change relative to the last commit in the PR's branch, not relative to the current state of `master`.

**Comment by h3xstream** [comment]
Duplicate see @newtrat comment
