### ISSUE TITLE
Use GitHub Checks API

### ISSUE THREAD

**Issue by webknjaz** [lemurheavy/coveralls-public#1137]
Hi,

Can we expect coveralls posting checks via brand new Checks API?

I've created a CLI tool, which can do that: https://github.com/webknjaz/check-in.

Feel free to explore it if you need some insights on how it works and how it can be integrated into your bot flow.

**Comment by bytewalls** [comment]
@webknjaz,

Thanks! We are looking into how we might use GitHub checks to give people a better experience with Coveralls, it is something we may start taking advantage of in the near future.
