### ISSUE TITLE
Coveralls not working with open-source repo migrated to travis-ci.com

### ISSUE THREAD

**Issue by duncanmmacleod** [lemurheavy/coveralls-public#1138]
I have recently migrated https://github.com/gwpy/gwpy from travis-ci.org to travis-ci.com, and it seems this has broken the uploads from travis-ci to coveralls.

The coveralls page for this repo is here: https://coveralls.io/github/gwpy/gwpy

![image](https://user-images.githubusercontent.com/1618530/40919516-95f1959e-6801-11e8-832f-aa60b08998bf.png)

Note the following

- the first and third entries in the table are from a completely unrelated repo,
- entries 2, 4, 5 (which are from gwpy/gwpy) have no git information, especially the branch, meaning coveralls doesn't know what to do with the data,
- if you select one of these entries, the link to the travis job goes to travis-ci.org, which is incorrect,

Is there something special that needs to be done to re-link my open-source project to coveralls now that the CI runs on travis-ci.com?

Any help is greatly appreciated, apologies if this question has already been answered.

**Comment by duncanmmacleod** [comment]
This is probably a duplicate of #1124.

**Comment by bytewalls** [comment]
@duncanmmacleod, we released a patch yesterday to resolve the builds with missing information.

We are working on some pieces to ensure that commits belong to the repo they are being pushed to.

**Comment by duncanmmacleod** [comment]
@bytewalls, does your first statement mean that my new builds will report correctly? sorry if I misunderstood.

**Comment by bytewalls** [comment]
@duncanmmacleod, Correct and looking over your page it looks as though things are now working correctly. Let me know if not and I will reopen this ticket.
