### ISSUE TITLE
Parallel builds on Travis CI with a public repository

### ISSUE THREAD

**Issue by agduncan94** [lemurheavy/coveralls-public#1139]
I have a public repository that uses multiple jobs on travis ci that I want to wait for the jobs to finish before doing the coverage. I followed the steps at http://docs.coveralls.io/parallel-build-webhook. However to my understanding since I have a public repository I do not have a COVERALLS_REPO_TOKEN. How do I format the webook shown below without this variable?
webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN

**Comment by bytewalls** [comment]
All repositories have coveralls repo tokens, when you navigate to your repo on coveralls you should be able to see it in the top right of the details about your repo. 

I'm guessing your are using travis as it is the only CI which we currently support not setting the coveralls repo token on, as we are able to pull your repo information from their API. I recommend you set this as a private environment variable in your travis ci setup.

**Comment by cjw296** [comment]
This feels related to the problems I've been having: https://github.com/lemurheavy/coveralls-public/issues/1133

**Comment by denis-yuen** [comment]
(FYI, the private environment variable seems to have worked. We're still seeing some issues like those in #1133, so subscribing to that ticket instead)

**Comment by ltalirz** [comment]
Do I understand correctly that the solution with encrypted environment variables [does not work for pull requests from forks](https://docs.travis-ci.com/user/encryption-keys/)?
Almost all of our PRs come from forks.

Is there currently a solution (for public repositories on travis) that works for pull requests from forks?

**Comment by cjw296** [comment]
@ltalirz - you beat me to it, I raised the issue thinking it might be a bug on Travis, but no: https://github.com/travis-ci/travis-ci/issues/10117#issuecomment-421360558

So, this is back in Coveralls' court... @agduncan94, what are your thoughts?

**Comment by cjw296** [comment]
I mean, it's incredibly frustrating to not be able to check coverage on PRs, simply because the one step of notifying the end of a parallel build requires an API token, and Travis doesn't support those on PRs from another repo...

**Comment by bytewalls** [comment]
@ltalirz an update was created recently for `travis-ci` builds do not require access to secrets you can simply use this url webhook now for public travis repos: https://coveralls.io/webhook

**Comment by ltalirz** [comment]
@bytewalls fantastic, we'll try that

**Comment by cjw296** [comment]
@bytewalls - that sounds great, so what do I need to hit with curl to mark the end of a parallel build when using build steps in Travis CI?

**Comment by cjw296** [comment]
@bytewalls - also, a GET to https://coveralls.io/webhook with a browser currently gives me a 404...

**Comment by bytewalls** [comment]
@cjw296 it only accepts a post.

You need to add this to your .travis.yml as a top level item:

```notifications:
  webhooks: https://coveralls.io/webhook```

**Comment by ltalirz** [comment]
@bytewalls We've [added the notification as suggested](https://github.com/aiidateam/aiida_core/pull/1977/files) but the build [still does not show up on coveralls.io](https://coveralls.io/github/aiidateam/aiida_core) (and no report on coverage on the PR).
I'm unable to spot what we are doing wrong... any hints?

**Comment by cjw296** [comment]
@bytewalls - how would I add that notifications section when using build stages?

The `.travis.yml` in question is [here](https://github.com/Simplistix/testfixtures/blob/9a88b14e509827ae91a6e3cbfb19d3a518ea0aa5/.travis.yml). Coverage information is submitted [here](https://github.com/Simplistix/testfixtures/blob/9a88b14e509827ae91a6e3cbfb19d3a518ea0aa5/.travis.yml#L42) and then I have to send the notification of "all builds finished"  [here](https://github.com/Simplistix/testfixtures/blob/9a88b14e509827ae91a6e3cbfb19d3a518ea0aa5/.travis.yml#L54); `coveralls-check` sends the ["all builds finished" notification](https://github.com/cjw296/coveralls-check/blob/master/coveralls_check.py#L43-L52) before [hitting your api](https://github.com/cjw296/coveralls-check/blob/master/coveralls_check.py#L26-L29) to check that 100% coverage has been met.

How would I replace my call to `coveralls-check` with your notification step. Honestly, if you could do a PR to the testfixtures repo with the change you're proposing, it might be the easiest way to show what you mean...

**Comment by cjw296** [comment]
@bytewalls - any chance you could re-open this issue until either mine or @ltalirz problems are solved, or would it be better to open new issues for each?

**Comment by cjw296** [comment]
@bytewalls - any news on this? I now have a PR failing CI because of this, see https://github.com/Simplistix/testfixtures/pull/91

**Comment by ltalirz** [comment]
Looking at the issue tracker, it seems like coveralls & @bytewalls have a lot on their hands at the moment and need to prioritize, which is completely understandable and normal for open source projects.

In order to help them make these tough decisions, I suggest that everyone affected by this issue +1 the [comment by @cjw296 above](https://github.com/lemurheavy/coveralls-public/issues/1139#issuecomment-423890755), asking to reopen this issue.

**Comment by cjw296** [comment]
@ltalirz - you may wish to follow up on this forum thread: https://travis-ci.community/t/how-can-i-share-coverage-information-between-build-stages-in-prs-from-forks/859/4
