### ISSUE TITLE
No coverage info available after Travis build

### ISSUE THREAD

**Issue by ledestin** [lemurheavy/coveralls-public#114]
Hi,

I seem to have done everything to enable Coveralls for my project, but there's still no info about coverage for my project.
https://github.com/ledestin/frugal_timeout

**Comment by rajatguptarg** [comment]
My badge is not updated.
https://coveralls.io/github/rajatguptarg/beacons

**Comment by zhengqingxin** [comment]
Same issue for my repo:[https://github.com/thinkjs/think-mysql](url)
Travis:[https://travis-ci.org/thinkjs/think-mysql](url)
