### ISSUE TITLE
no data in gui when the command reports successful transmission

### ISSUE THREAD

**Issue by tomato42** [lemurheavy/coveralls-public#1140]
I have a run that is stuck in Pending (I've re-pushed it with changes twice, both failed the same way) with individual jobs being marked as "no data" when the travis runs reported successful submissions.

https://coveralls.io/builds/17331990

https://github.com/tomato42/tlsfuzzer/pull/396

https://travis-ci.org/tomato42/tlsfuzzer/builds/388391092

https://travis-ci.org/tomato42/tlsfuzzer/jobs/388391098#L1035
output from coveralls is
```
Submitting coverage to coveralls.io...
Coverage submitted!
Job #654.6
https://coveralls.io/jobs/37179630
```

**Comment by bytewalls** [comment]
We had some backlog that led to jobs taking longer than usual to report for a brief period last week.

http://status.coveralls.io/incidents/rcp6dfwcnqnz
