### ISSUE TITLE
PR not showing the coverage status on github UI

### ISSUE THREAD

**Issue by reasonerjt** [lemurheavy/coveralls-public#1149]
Take this PR for example:
https://github.com/vmware/harbor/pull/5194

I can see the coverage status on coveralls website:
https://coveralls.io/builds/17710727

But on the UI of github it's blocked at `Expected — Waiting for status to be reported`

See screenshot:
![screen shot 2018-06-27 at 6 36 54 pm](https://user-images.githubusercontent.com/2390463/41969336-a9dc5c66-7a39-11e8-802f-a01eef8cd651.png)

A PR that was opened 2 days ago looks fine:
https://github.com/vmware/harbor/pull/5176

**Comment by tomato42** [comment]
same here, no coveralls PR status is being added to projects

looks like it is related to the migration to github Apps API

**Comment by bytewalls** [comment]
@reasonerjt, 

We are investigating this issue, thanks. I will update when we know more, sorry for the inconvenience.

**Comment by bytewalls** [comment]
@reasonerjt,

Not sure what the cause of this issue is but it appears as though the commit sha in travis and on github don't match. We rely on the commit sha from travis to tell us which commit to update statuses on GitHub currently, and the commit sha travis is reporting does not exist on your repo.

Perhaps there was a rebase/squash and push that replaced the data on github but without pushing to travis for updates?

**Comment by bytewalls** [comment]
@tomato42 which repo are you seeing issues with? Is there a specific build you can point to?

**Comment by tomato42** [comment]
@bytewalls sure:
https://github.com/tomato42/tlsfuzzer/pull/414
https://github.com/tomato42/tlsfuzzer/pull/416
https://github.com/tomato42/tlslite-ng/pull/281

**Comment by bmw** [comment]
I'm seeing similar problems on my project. Here's one example:

https://coveralls.io/builds/17721962
https://github.com/certbot/certbot/pull/6145

I also started seeing issues about 2 days ago.

Both mine and the original poster's coveralls builds are saying

> FIRST BUILD ON MASTER AT ...

but there certainly should be coverage history for these builds.

**Comment by bytewalls** [comment]
We have identified the problem and are working on getting a fix deployed. After that is done we will be able to update these missing statuses. Sorry for the inconvenience.

**Comment by bytewalls** [comment]
We have released a fix, it appears to have fixed the issues you were both seeing @bmw and @tomato42.

@reasonerjt It looks like we are having an additional issue with your OAuth token. I'm working to figure out what is going on with this right now. Can you go [here to check your Coveralls Pro OAuth settings](https://github.com/settings/connections/applications/5b064d049aaeb3438e8e). If this app has permission but does not have access in the vmware organization that would be the issue there. Thanks!

**Comment by reasonerjt** [comment]
@bytewalls thanks for the update.  I'll need to figure out who to talk to for the approval.  Please kindly leave this issue open for a few more days.
But I'm curious why it worked previously?  Was the permission revoked recently?  Or is it due to some recent change on github or coveralls?

**Comment by bytewalls** [comment]
@reasonerjt We hadn't changed anything around this until after this ticket was made. To be honest, I'm not sure exactly what caused the change or issue. I've reached out to GitHub to try and get more information so we can ensure the issue doesn't happen again.

**Comment by bmw** [comment]
I'm seeing this issue again, although the details are a little different from the version I provided before.

Starting in the last 48 hours, Coverage builds are finishing but aren't being reported to GitHub. Here's one instance of it:

Coverage: https://coveralls.io/builds/17906070
PR: https://github.com/certbot/certbot/pull/6189

This is affecting all PRs against our repo.

**Comment by bytewalls** [comment]
@bmw,

Sorry for the delayed response. This is something we are looking into, has the owner of the repo in coveralls possibly had their access level to the `cerbot/cerbot` repo altered recently?

I've also reached out to GitHub again to see if they can help shed some light on what is happening here.

**Comment by bmw** [comment]
> has the owner of the repo in coveralls possibly had their access level to the cerbot/cerbot repo altered recently?

Oh that's almost certainly it. I was cleaning up some of our permissions earlier this week and didn't put the two together. Since I think this is the problem, you can consider my issues here resolved and I'll report back if I still have problems.

**Comment by danielcroft** [comment]
Hi Coveralls, we're experiencing this on some of our repos as well. Some are reporting and others aren't. There's one repo in particular that I've been trying to sort out, even tried deleting out of coveralls and recreating. That seemed to clean up the link on your side but hasn't started showing coveralls status on the GH side.

Coveralls Pro application has all access as well as to our org
Repo is building and passing all the travis checks

Looking for some assistance here.

**Comment by bytewalls** [comment]
@danielcroft,

Which repo are you having issues with?

**Comment by artekr** [comment]
Hi @bytewalls ,
We've experienced similar issues on Coveralls status reported to Github.
We have private repos under an orgnization, with Coveralls Pro setup.
**coverage/coveralls status check passes.**

If we set this as Required, Github will not allow us to merge.
<img width="720" alt="screen shot 2018-08-01 at 10 55 08 pm" src="https://user-images.githubusercontent.com/2516988/43560108-00157174-95df-11e8-8190-1936c48e45cf.png">

If we take off the Required, then we are able to merge.
<img width="722" alt="screen shot 2018-08-01 at 10 55 44 pm" src="https://user-images.githubusercontent.com/2516988/43560141-1adb57e4-95df-11e8-9532-5904f2ac7c85.png">

It seems Github did not get the status from Coveralls.
Please help as this blcoks our pr to merge. Thanks!

**Comment by artekr** [comment]
@bytewalls Any updates on this issue?

**Comment by phantomphildius** [comment]
Hi @bytewalls i am having some similar issues as well. I have coverage reporting in coveralls and I can see it happening in my travis build. However the github check ends up just waiting for data to be reported back `coverage/coveralls Expected — Waiting for status to be reported` and it blocks our merge. We disabled the check, but would prefer to have it included in our workflow. There could have been token revocation issues but I'm not exactly sure where to check that out. Do you have any other potential solutions?

Thanks for all your help

**Comment by amastracci** [comment]
Hi @bytewalls We are currently seeing a similar issue on our repos. Travis successfully completes the build step to push coverage reports to coveralls.io, however, we never get a coverage report generated nor do we see github checks completed. This is currently blocking our CI/CD pipeline. 

Please see the bluzelle/swarmdb public repo configuration.

Please let us know if there is a potential workaround for the solution or if you need more info.

**Comment by MarcusDEFGH** [comment]
I'm still experiencing this issue

**Comment by nickmerwin** [comment]
@MarcusDEFGH could you link me to the repo, please?

**Comment by MarcusDEFGH** [comment]
@nickmerwin it's a private repo from the company I work on, I don't know if it may help you but here it is https://github.com/intelivix/aldra/

**Comment by nickmerwin** [comment]
@MarcusDEFGH I see notifications for your latest build here have been posted successfully:

https://coveralls.io/builds/25840584

Can you confirm?

**Comment by MarcusDEFGH** [comment]
@nickmerwin Yes, that is the repo.

I actually managed to fix it by re-running the travis build process.
The issue is probably related to the communication with github, since it was the only place where it wasn't being updated

**Comment by rajaanova** [comment]
@nickmerwin i see some of the repos are getting the coveralls coverage status but for few i am not getting at all. 
Difference i see between repo which is working and repo for which this thing is not working is When build number(serial continuous number) is proper and comitted by "GIT-FLOW" the status can be seen on github ui. But for repos which doesnt show status are having commited by "GITHUB" and build number is quite random and very large.

**Comment by rajaanova** [comment]
Below is the reason for coverall status not being shown.

When a github user leaves the organization (loses access to repositories), if they initially added the repos to Coveralls, there becomes a failure to exchange the Coveralls status between Coveralls and Github.

How we fixed the issue :

We recreated the coverall profile for corresponding repositories. The only problem is that we loose all our historical data for those repos.

**Comment by mauriciojost** [comment]
News here? It impacts my projects too :(

**Comment by jchung05** [comment]
This issue has also popped up for us; is there a solution other than recreating the profile which does not impact historical coverage data?

**Comment by afinetooth** [comment]
@jchung05 can you please share the Coveralls URL(s) for the repo(s) with the issue?

To avoid re-creating the profile we can typically change the owner of the repo for you.

If your repo(s) are private, you can email them to support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1149#issuecomment-782290483).

**Comment by StrikerRUS** [comment]
Hi! We are facing this issue as well during using python package from GitHub Actions.
Reports are always successfully sent to coveralls.io 
```
Submitting coverage to coveralls.io...
Coverage submitted!
Job #715132143.1
https://coveralls.io/jobs/77850492
```
and then are visible there. But commit status for `coverage/coveralls` are almost always is `Expected`. After I click `RESYNC WITH GITHUB` at coveralls.io site and close-reopen a PR, status is successfully reported back. I'm not 100% sure that these actions help, tried only 2 times as of moment of writing this comment.

Example PR: https://github.com/BayesWitnesses/m2cgen/pull/360.

Access for Coveralls OAuth app is granted under the both organization account 

![image](https://user-images.githubusercontent.com/25141164/113491793-f7bc6600-94db-11eb-9bbf-4d5e6a830e9a.png)

and personal one

![image](https://user-images.githubusercontent.com/25141164/113491807-29cdc800-94dc-11eb-9b8e-065ce9a07b77.png)


Any help is really appreciated!

**Comment by afinetooth** [comment]
@StrikerRUS it is honestly hard to say what the issue was. On a hunch, I have changed the owner of the repo to you (who are apparently active and have Admin status on the repo (to get around any branch protection rules)). Please let me know if this changes the behavior.

**Update**: 
After changing ownership to you the Github Status API started throwing "401 Bad credentials" errors, so I switched to another user with Admin permission on the repo (izeigerman). You should try unlinking and relinking Github to your account, and/or revoking access to any/all Github Oauth Apps and login fresh to https://coveralls.io via Github Oauth.

Steps:

Unlink / re-link account:

1. Login to https://coveralls.io
2. Go to [ACCOUNT](https://coveralls.io/account) page (YOUR USERNAME)
3. Click UNLINK next to your Github account
4. Log out and back in to https://coveralls.io

Revoke OAuth Apps / Start fresh:

1. Login to https://github.com
2. Go to Developer Settings > Applications > Authorized OAuth Apps
3. Revoke any/all Coveralls apps
4. Log into https://coveralls.io again

**Comment by TheOutdoorProgrammer** [comment]
We are seeing this exact issue, intermittently, on our private repositories. Sometimes it posts fine, others we have to use admin privileges to merge the PR because it gets blocked. I've followed almost every example in this issue and we are still seeing the problem.

https://coveralls.io/builds/38685530

This build is one example ^^. 

When we tell coveralls the build is complete, we even get a good response.
```
curl -k https://coveralls.io/webhook?repo_token=REDACTED \
  -d "payload[build_num]=11042&payload[status]=done"
 
{"done":true,"url":"https://coveralls.io/builds/38685530","jobs":17}
```

But its never reflected in the PR status checks.

**Comment by afinetooth** [comment]
Hi @Apollorion did you try the steps mentioned in my comment above? 

Namely:

1. (Have us) switch the owner
2. Unlink / re-link account
3. Revoke OAuth Apps / Start fresh

I can't see your PR because your repo is private, but I see a status was sent. I tried to force-push a comment, but I'm getting a 404 on the PR, which might be because it's been merged/deleted.

Is there another PR build I can check for you that's still live?

Feel free to email support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1149#issuecomment-816867821).
