### ISSUE TITLE
[Coveralls][Jenkins] Outside the Travis environment, not sending data.

### ISSUE THREAD

**Issue by sameergautam** [lemurheavy/coveralls-public#1150]
All my configs for the repo are set according the [documentation](https://docs.coveralls.io/ruby-on-rails). I'm using Jenkins for running all my CI needs. However, I'm constantly getting the error:
`[Coveralls] Outside the Travis environment, not sending data.`. Rest of the test suite runs fine, however, nothing is posted to coveralls.

**Comment by alexxed** [comment]
Try setting `COVERALLS_SERVICE_NAME=jenkins`.
