### ISSUE TITLE
CircleCI 2.0 compatibility

### ISSUE THREAD

**Issue by ain** [lemurheavy/coveralls-public#1151]
The current guidance for CircleCI Coveralls integration is for 1.0. Support for CircleCI 1.0 will end on August 31, 2018 which would effectively obsolete much of the documentation, incl. [Parallel Builds docu for CircleCI](https://docs.coveralls.io/parallel-build-webhook#circleci-setup).

**Comment by bytewalls** [comment]
@ain,

The notify webhooks behaivior continue to function the same on Circle 2.0, despite incomplete proper documentation of it. We have confirmed this with both circle support and our own testing.

**Comment by blueyed** [comment]
Unfortunately there appear to be problems with it: https://discuss.circleci.com/t/circleci-2-0-notifications-webhooks/19075

Maybe the documentation could/should be updated to post the notification manually, e.g. using curl?

**Comment by blueyed** [comment]
I've tried posting it manually via curl, but the build number is not recognized then:
```
% curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"
{"error":"No build matching CI build number 2295 found"}
```

Would be nice to a) have more info in the error message, and b) update the doc (https://docs.coveralls.io/parallel-build-webhook).
