### ISSUE TITLE
Jobs stuck in Pending Completion state

### ISSUE THREAD

**Issue by alexchao** [lemurheavy/coveralls-public#1152]
Around June 21st, all of our repos on Coveralls stopped reporting coverage. Digging a bit further, I discovered that all of our builds since around that date have jobs that are stuck in a Pending Completion state.

We use Semaphore CI w/ parallel builds (`COVERALLS_PARALLEL` env variable is set to `true`), and I can see in the build output that coveralls is reporting status to the API:

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #321.1
[Coveralls] https://coveralls.io/jobs/37944020
```

Both jobs in that build are still in Pending Completion state. We haven't changed how coveralls is run within the test suite recently, so not sure what could have caused this. Wondering if maybe we're missing something that will aggregate the results of the jobs...

Let me know if there are further details I can provide.

**Comment by asartalo** [comment]
I'm experiencing the same thing on my recent on my public repos. I had to manually mark the task as done.

**Comment by pbelskiy** [comment]
Same problem here

**Comment by hunterae** [comment]
Same

**Comment by berserkhmdvhb** [comment]
Same

**Comment by afinetooth** [comment]
Hi, @berserkhmdvhb.

I'm almost certain your issues were related to one of these [incidents](https://status.coveralls.io/) [[1](https://status.coveralls.io/incidents/c81d01kx59f4) | [2](https://status.coveralls.io/incidents/mghkqwljy99z)] we had earlier this week. Are you still experiencing them?

Check out status page whenever you experience issues to make sure they're not system-related:
https://status.coveralls.io/

You can subscribe for updates there as well.
