### ISSUE TITLE
Uploading coverage data from CircleCI times out

### ISSUE THREAD

**Issue by vuspenskiy** [lemurheavy/coveralls-public#1154]
Hi, I am trying to configure Coveralls to work with CircleCI for a Scala project (hence using sbt-scoverage and sbt-coveralls). When I am trying to run the build locally it works and uploads the coverage data (even though it takes much time). When I run it in CircleCI it times out:

```
[info] Loading project definition from /home/circleci/project/project
[info] Resolving key references (23089 settings) ...
[build.sbt] Suppressing Ivy update logging because CI detected
[build.sbt] Suppressing Ivy update logging because CI detected
[build.sbt] Suppressing Ivy update logging because CI detected
[build.sbt] Suppressing Ivy update logging because CI detected
[info] Set current project to domino (in build file:/home/circleci/project/)
[info] Set current project to server (in build file:/home/circleci/project/)
[info] Set current project to domino (in build file:/home/circleci/project/)
[info] Repository = ./.git
Too long with no output (exceeded 10m0s) <--- an output from CircleCI
```

Are there any availability issues with Coveralls or should I configure the network access somehow?

(also reloading https://coveralls.io/stories page in browser takes a lot of time, that makes me think that there might be some performance issues)

**Comment by bytewalls** [comment]
@vuspenskiy,

You shouldn't need to do anything with coveralls network access, it sounds to me like an issue with `sbt-scoverage` or `sbt-coveralls`.

As for the stories page, that page could use some performance tweaks I've created an issue card for us to dive into that.

**Comment by vuspenskiy** [comment]
Thanks @bytewalls! Looking forward to use Coveralls for our project.

**Comment by vuspenskiy** [comment]
Hey @bytewalls can you please take a look at https://github.com/scoverage/sbt-coveralls/pull/123
It works much faster. I know Scala parallel collections are not hyped anymore, but they're simple nonetheless.
