### ISSUE TITLE
Changing source does not work

### ISSUE THREAD

**Issue by julianoes** [lemurheavy/coveralls-public#1156]
I'm trying to change the source from:
`DroneCore/DroneCore` to `Dronecode/DronecodeSDK`
When I click change source, I get redirected to a blank page and the change is not reflected.

Before doing that I accidentally clicked on the ON switch of the new repo but I have since switched it back to off.

I would appreciate any help, thank you.

https://coveralls.io/repos/182893

**Comment by bytewalls** [comment]
@julianoes,

I have manually updated your repo. Please let me know if it is not working. I'm going to create a ticket for the team to look at the functionality around changing repo names so we can make this process more seamless in the future.

**Comment by julianoes** [comment]
@bytewalls great thank you.
