### ISSUE TITLE
Coveralls badge says "coverage: unknown"

### ISSUE THREAD

**Issue by alex-murashkin** [lemurheavy/coveralls-public#1157]
Hi all,

Coveralls seems to have coverage information for one of the branches (`develop`), however, when I get a badge for it, it says "coverage: unknown" despite a long history of coverage information.

I am using coveralls for Python: https://pypi.org/project/coveralls/

Thoughts on how to fix this issue?

**Comment by alex-murashkin** [comment]
@bytewalls . It's a private repo. Is there a way to contact the support privately?

**Comment by bytewalls** [comment]
@alex-murashkin, sure thing. 

Send us an email and we will help you get things sorted out: support@coveralls.io
