### ISSUE TITLE
Problem Adding Organization: Adds Wrong Connection to GitHub?

### ISSUE THREAD

**Issue by WardLT** [lemurheavy/coveralls-public#1158]
I ran into issues today trying to add an organization to the non-Pro version of Coveralls.

When clicking the "GitHub Settings" button on `https://coveralls.io/repos/new`, I am routed to a page for giving access to [Coveralls Pro](https://github.com/settings/connections/applications/5b064d049aaeb3438e8e). After adding permissions to my organization, that organization fails to appear on my list of organizations in Coveralls. 

My workaround resolution for this was find the [access control page for the non-Pro version of Coveralls ](https://github.com/settings/connections/applications/5b064d049aaeb3438e8e) from one of my organizations that already works with Coveralls, and grant access that way. Once access was granted to the non-Pro version, Coveralls worked as expected.

**Comment by djhoese** [comment]
Thank you @WardLT! I thought it was weird that it was asking for the "Pro" application's permission. After googling for "coveralls github app" I got to the github marketplace, found the non-pro "Coveralls" app, and was able to grant access to my organization. Now my organization and org repositories show up in coveralls.
