### ISSUE TITLE
History merge after organisation move

### ISSUE THREAD

**Issue by joshuagl** [lemurheavy/coveralls-public#1159]
As discussed in #1066 we recently moved our project to a new Github organisation (from 01org to tpm2-software) and have been updating our coveralls usage to use the new repositories.

Is it possible to merge the history of our old repo https://coveralls.io/github/01org/tpm2-tools?branch=master into the new one at https://coveralls.io/github/tpm2-software/tpm2-tools?branch=master ?

Many thanks!

**Comment by bytewalls** [comment]
@joshuagl, Sure thing. Should be done let me know if it causes any issues for you.
