### ISSUE TITLE
Badge is not updated / showing unknown status

### ISSUE THREAD

**Issue by marigan** [lemurheavy/coveralls-public#116]
On the repository:

https://coveralls.io/r/CAS-FAMU/narra_core

the badge is not updating even if submissions from travis are fine.

**Comment by jehoshua02** [comment]
This looks like an issue with Github caching images. When I inspect the element in my rendered README.md page on Github, I see this:

```html
<img src="https://camo.githubusercontent.com/c918b0a723bd60b92f759c99d83e08fa387b8d19/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f7265757361626c65732f64697374616e63652f62616467652e737667" alt="Coverage Status" data-canonical-src="https://coveralls.io/repos/reusables/distance/badge.svg" style="max-width:100%;">
```

There is a `data-canonical-src` attribute, with [this url](https://coveralls.io/repos/reusables/distance/badge.svg).

But instead, Github serves up [this url](https://camo.githubusercontent.com/c918b0a723bd60b92f759c99d83e08fa387b8d19/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f7265757361626c65732f64697374616e63652f62616467652e737667) for the img src.

I think we might be barking up the wrong tree y'all.

**Comment by jehoshua02** [comment]
I added a dummy query param on the badge url in my README.md and it tricked Github into thinking it was a new image to cache.

**Comment by chamilad** [comment]
@jehoshua02 That actually solved my problem. Thanks for the tip!

**Comment by arekkas** [comment]
Same issue

**Comment by arekkas** [comment]
* https://github.com/github/markup/issues/224#issuecomment-33454537
* https://github.com/github/markup/issues/224#issuecomment-33969171

**Comment by Skarlso** [comment]
Yepp, worked for me too!

**Comment by courtney-miles** [comment]
For those who don't know, GitHub will *proxy* your images using package named Camo - [Why do my images have strange URLs](https://help.github.com/articles/why-do-my-images-have-strange-urls/)

That page provides some troubleshooting techniques for where Camo is not delivering your images correctly -- which involves checking the images response include appropriate headers.

Coveralls does set all the correct headers, so the immediate solution is to call the URL yourself with the request method of `PURGE` to force Camo to drop the cached copy.  For example.

```sh
curl -X PURGE "https://camo.githubusercontent.com/..."
```

**Note:** GitHub asks that you do this sparingly.

If you don't see an instant change when you reload your GitHub, it's probably because you browser still has its own cached copy of the image.

**Comment by wu-sheng** [comment]
This bug is also existed. Thanks to @jehoshua02, it has been solved.

**Comment by okv** [comment]
same thing, thanks to @jehoshua02

**Comment by anderson-dan-w** [comment]
It was unclear from context - does adding the dummy parameter to the coveralls URL only work at refreshing the badge for that commit? Presumably, it now caches the URL that contains the dummy parameter and then gets cached (by both browser and github-camo), so I don't see how that's a long-term solution, but maybe I'm missing something about parameters.

Regardless, doesn't seem like coveralls' issue, but just trying to follow up to keep the history clear

**Comment by hustcc** [comment]
Same issue [here](https://github.com/hustcc/variable-type)

So the so solution is update the badge url to force GitHub update the image cache? I think it is a not very nice way!

Why shield.io and travis can update the cache when updated? I suppose it will modify the badge image header every time when new task finished or new version published.

**Comment by aayush26** [comment]
The badge doesn't get updated in the README.md as it gets stored in cache and only on force refresh ```shift+command+R``` , the badge is updated. While using shields.io endpoints, this issue doesn't exist. I think you should reconsider the cache strategy.

**Comment by gangelo** [comment]
I read somewhere that github's caching is "too aggresive." I had the same problem, and the only way I could force an update was to append "?v=2.0.0" (for example) to my github version badge url in my README.md mark up. Terrible solution I know, but in my case my repository version was incorrectly tagged.

**Comment by aayush26** [comment]
Changing everytime the badge version doesnt seem a good practice.
**Alternative solution:** 
Use Shields 
Example: https://img.shields.io/coveralls/jekyll/jekyll.svg

**Comment by sachinlala** [comment]
My [badge](https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_68.svg) is showing correct percentage when it's still showing dated/old percentage when it is referenced from [README file](https://github.com/sachinlala/SimplifyLearning).

@nickmerwin please could you advice ?

**Comment by sachinlala** [comment]
As @jehoshua02 had commented earlier, I added a dummy variable to the URL and image cache got force-refreshed. So the issue at hand is resolved. Thanks @jehoshua02.

But this is at best a tactical solution in absence of a fix from coveralls/github.

**Comment by giuscri** [comment]
I used docker from travis and run `coveralls` from there. If I started the container locally, it would have updated the badge correctly. When travis started the container the update didn't happen though.

My idea is that travis force the git repository to stay in a detatched mode, making coveralls think updates are not coming from master. As coveralls wanted to show coverage of master, that could be what did prevented updates.

I've added `RUN git branch -f master HEAD` to my Dockerfile, to move master _down_ current HEAD and coveralls started to receive updates.

![screenshot 89905bf46c96c410fd3cead00d502596](https://user-images.githubusercontent.com/4048120/39960132-6b03814e-561d-11e8-8ecb-5e7479d66ccb.png)

**Comment by jobboz** [comment]
hi made a build up to two days now,an so far the badge status is still unknown..please assist me!

**Comment by courtney-miles** [comment]
Hey @jobboz ,

I see your completed tests at https://travis-ci.org/jobboz/fast-food-app/jobs/426096516 with the coverage report.  But it does not look like you are submitting this report to Coveralls -- Coveralls is reporting, "This repo has not recieved any jobs yet." https://coveralls.io/github/jobboz/fast-food-app

I'm not a node.js guy, but I expect as a part of your Travis build you will need to install a package that can submit your coverage.

Perhaps check out [StrongLoop - Building Better npm Modules with Travis and Coveralls](https://strongloop.com/strongblog/npm-modules-travis-coveralls/). There's a section on that page that reads:

> Now, how do you send istanbul’s coverage output to Coveralls? Like just about everything these days, there’s an npm module for that. The coveralls npm module contains an executable file coveralls.js that you can use to send coverage output to Coveralls. You just need to add coveralls to your package.json:

**Comment by disney-streaming-osc** [comment]
Hi, hope someone can help. Im having trouble with the coveralls badge, coverage seems to be reporting fine, however the badge returned when `branch=master` is passed always says `Unknown`. It returns the correct number if a commit hash is passed as the value, but that would mean id need to update the badge on every commit which doesn't seem correct.

https://coveralls.io/github/disneystreaming/pg2k4j

for a specific commit ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg?branch=bb12d734f195ddb91524145418741f89cf47b75f)](https://coveralls.io/github/disneystreaming/pg2k4j?branch=bb12d734f195ddb91524145418741f89cf47b75f)

for a master ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg?branch=master)](https://coveralls.io/github/disneystreaming/pg2k4j?branch=master)

with no branch ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg)](https://coveralls.io/github/disneystreaming/pg2k4j)

Any help would be greatly appreciated,
