### ISSUE TITLE
Can add repos from organization to coveralls, but cannot access settings on one

### ISSUE THREAD

**Issue by davidlowryduda** [lemurheavy/coveralls-public#1163]
## Description of the problem

I am a member of the LMFDB organization (https://github.com/lmfdb) and I have somewhat recently set up one of our repos to use coveralls (https://github.com/lmfdb/lmfdb). I want to change the threshold for a passing/failing build, but I cannot access the settings page from the coveralls site page for that repo (https://coveralls.io/github/LMFDB/lmfdb). If I go to the settings page directly (https://coveralls.io/github/LMFDB/lmfdb/settings), I see only a "Badge and Token" settings.

However, I can add a different repo from the LFMDB organization from my new repos page (https://coveralls.io/repos/new), and if I do this then I can also adjust the settings for that repo on coveralls.io.

Finally, it seems that I cannot remove coveralls from our main repository (LMFDB/lmfdb). When I click on the `On` toggler from https://coveralls.io/repos/new, the popup saying `Remove LMFDB/lmfdb and its data from Coveralls?` appears and I hit `OK`, but then nothing happens. Or rather a spinny circle appears on that line, but nothing appears to change.

## Additional thoughts

This seems to be a permissions issue somewhere, but I can't decide where. The fact that I'm able to add/remove other repos from my organization indicates to me that coveralls is aware that I'm in this organization and should have some permissions. I don't know how to interpret my inability to either access the settings or remove the LMFDB/lmfdb repo, though.

Can you help me resolve this issue? Thank you for your time, effort, and great product.

**Comment by bytewalls** [comment]
@davidlowryduda,

It is odd that you are seeing the option to add the repo even though it is already added, I will look into that. As for why you don't have the ability to access the full settings, currently @edgarcosta is the owner of this repo and has access to edit the full settings for it.

**Comment by davidlowryduda** [comment]
Thank you for your response. I hadn't realized that only one member of an organization is to have access to the settings. Is there a way to give the ability to adjust the settings to others?

**Comment by edgarcosta** [comment]
Or pass the rights to the whole organization?

**Comment by bytewalls** [comment]
@davidlowryduda @edgarcosta,

There is not currently, sorry for the inconvenience.

**Comment by davidlowryduda** [comment]
I understand. Thank you for following up with us so quickly.

Cheers.
