### ISSUE TITLE
Incorrect computation of test coverage

### ISSUE THREAD

**Issue by desilinguist** [lemurheavy/coveralls-public#1164]
I am the maintainer for the [RSMTool](https://github.com/educationalTestingService/rsmtool) repository on GitHub. We have been using coveralls for our test coverage for a few years and it has always worked well.

However, recently we have been noticing that coverage is not being computed correctly for our PRs. The "push" build on Travis will have the expected coverage (matching the coverage computed locally) but the "PR" build for some reason has lower coverage. 

As an example, consider the builds for a really stupid [PR](https://github.com/EducationalTestingService/rsmtool/pull/223) that only adds a newline in our README. This should not affect the test coverage at all. And this is what we see on the [push build](https://coveralls.io/builds/17977377) but the [PR build](https://coveralls.io/builds/17977600), for some reason, reports a 14% drop in coverage! 

We are unable to figure out why this is happening as the raw coverage output from the travis builds remains unchanged. Any help would be greatly appreciated.

**Comment by chuckgreenman** [comment]
Do you use a random seed in your testing process?  It's very possible that each time you run your tests a different execution path is taken, meaning your coverage will change.

**Comment by desilinguist** [comment]
@chuckgreenman thanks for the pointer! 

1. Only a couple of our small unit tests rely on randomness and _all_ of those use explicit seeds. 
2. More importantly, the raw coverage numbers for all of our python files have not changed. Somehow, the computation of the overall coverage is inaccurate on the coveralls side.

**Comment by bytewalls** [comment]
@desilinguist, it looks like you have many jobs being built but aren't using the parallel build webhook: https://docs.coveralls.io/parallel-build-webhook. 

This webhook lets us know when we have received all the coverage information, otherwise race conditions can arise in the arrival of coverage and queuing the processing of the build before we have received all coverage information.

**Comment by desilinguist** [comment]
@bytewalls thanks so much for letting me know! I will try and fix this right away in the builds.

**Comment by bytewalls** [comment]
@desilinguist,

No problem, please let me know if you continue to see these issues in your builds after it is setup.
