### ISSUE TITLE
Parallel webhook jobs stuck in pending state

### ISSUE THREAD

**Issue by desilinguist** [lemurheavy/coveralls-public#1165]
As a solution to our [previous issue](https://github.com/lemurheavy/coveralls-public/issues/1164) about incorrect coverage computation, it was suggested that we add the parallel webhook to our Travis builds. However, it doesn't seem like the notification is going through to the webhook even though the Travis builds have completed. 

[Here's](https://github.com/EducationalTestingService/rsmtool/blob/fix-parllel-coveralls/.travis.yml) the updated `.travis.yml` file that includes the parallel webhook as detailed in [these](https://docs.coveralls.io/parallel-build-webhook) instructions.

@bytewalls any help would be greatly appreciated. Thanks!

**Comment by bytewalls** [comment]
@desilinguist,

I have confirmed that the webhook endpoint is working correctly (manually hit it to finish one of your builds, and also confirmed with [travis documentation](https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications) that our webhook information is not stale. 

Going to have to dive a bit deeper and try to figure out what is going on. Are your slack notifications working correctly? If so could you try changing the URL for testing purposes to point to a webhook tester such as [this](https://webhook.site/), and confirm that it works if you do? I want to ensure that both the notifications sections in general working, and that the webhooks url section is firing. I believe that the webhook post isn't being made, although at the moment I'm not sure why, want to confirm that is the case before I dig down that hole.

As an aside, you might want to set your repo token (we typically use `COVERALLS_REPO_TOKEN`) as a secure environment variable on travis and then reference it in the webhook like this: 
```yaml
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
```

**Comment by desilinguist** [comment]
@bytewalls thank you so much for your continued help!

The Slack notifications work just fine. I also replaced the coveralls webhook with a test webhook and it seems to work as well (see attached screenshot below with two POST requests, one for each build). So, it seems that the webhook section is indeed firing. Is it something on the coveralls side then?

Thank you also for the reminder about secure environment variables. It had totally slipped my mind. I have now set it up properly.

<img width="314" alt="screen shot 2018-07-18 at 9 50 38 am" src="https://user-images.githubusercontent.com/161680/42885954-6129a838-8a70-11e8-9c85-a09f45a96b69.png">

**Comment by bytewalls** [comment]
@desilinguist,

I think I have found the source of this issue and am working on a solution, sorry for the delay in getting back to you.

**Comment by bytewalls** [comment]
@desilinguist I have found the issue and am working on a fix. Sorry for the inconvenience.

**Comment by desilinguist** [comment]
Thank you so much @bytewalls!

**Comment by cjshawMIT** [comment]
I'm seeing similar coverage drop behavior in my parallel Travis builds, and I have also followed the documentation in an attempt to fix it ... no luck so far. +1 and waiting for a fix. Thanks @bytewalls !

**Comment by desilinguist** [comment]
Hi @bytewalls, any updates on this? Thanks again for your help.

**Comment by bytewalls** [comment]
@desilinguist we released an update earlier this week, which also removes the requirement of the repo_token parameter for public travis-ci repos. For these calls we use the information in the webhook to locate the appropriate build.

Try using this webhook setup and please let me know if it doesn't work for you still.
```
notifications:
  webhooks: https://coveralls.io/webhook
```

**Comment by desilinguist** [comment]
Fixed it for me too! Thanks again @bytewalls!
