### ISSUE TITLE
Getting data from Coveralls for private repo

### ISSUE THREAD

**Issue by laisti** [lemurheavy/coveralls-public#1166]
Hello!

I would like to get data from Coveralls using the following option:
https://coveralls.io/github/lemurheavy/coveralls-ruby.json
(ref https://docs.coveralls.io/api-introduction)

I have a private repo at Github.
What API auth should I use?
I tried:
- token which was setup in Coveralls account
- token which was setup at Github account
- login and password from Github account
- repo_token
None of these options was working for me. Only session cookie was working but I can't use it using proxy, and it has short expiration time.

Is it possible to get data form Coveralls for private repo?

**Comment by bytewalls** [comment]
@laisti,

Yes! You will need to generate an API token for your account [here](https://coveralls.io/account), and then in your request set a header `Authentication` with the content `token XXXX` where `XXXX` is your token.

**Comment by codingrhythm** [comment]
@bytewalls I've tried to generate an API token from my account, and set as auth header. still gives me 403

**Comment by deepakkt-a** [comment]
Hello, is there a solution to the issue posted by @codingrhythm ?

I am running into the same issue and there seems to be no proper way to authenticate with the Coveralls API! @joroshiba ??

**Comment by jaimeoconor** [comment]
Hello, I am having the same problem, gives 403 to me. Any solutions?

**Comment by aswerlein511** [comment]
I am also seeing the same issue.  I am using Ruby and the rest-client gem.

**Comment by afinetooth** [comment]
Cleaning house on an old issue, but if it helps @jaimeoconor:

Technically, the example URL from the OP:
https://coveralls.io/github/lemurheavy/coveralls-ruby.json

Is a web-only resource. 

But in regards to accessing repo data via the API according to:
https://docs.coveralls.io/api-introduction

And:
https://coveralls.io/api/docs

Here's a cURL command showing how to request info for an existing, public repo. Just change for your purposes:

```
curl --location --request GET 'https://coveralls.io/api/repos/gitlab/my-awesome-group305/my-awesome-subgroup/my-awesome-subgroup-test-project-1' --header 'Authorization: token zFGkQwy5ROxOlNPgpzOAUmAwE1hTByLVyUz7n'
```

The format is:

```
curl --location --request GET 'https://coveralls.io/api/repos/<GIT_SERVICE>/<GIT_USERNAME_OR_ORG>/<GIT_REPO_NAME>' --header 'Authorization: token <YOUR_PERSONAL_ACCESS_TOKEN>'
```

You will need to generate your own Personal access token for Coveralls, by logging into https://coveralls.io and going to https://coveralls.io/account:

![Screen Shot 2020-11-30 at 4 07 30 PM](https://user-images.githubusercontent.com/918667/100680320-2a840100-3326-11eb-9647-a784e67b3c6f.png)
