### ISSUE TITLE
Ruby quickstart shown for Python project

### ISSUE THREAD

**Issue by JaredLGillespie** [lemurheavy/coveralls-public#1168]
When initially adding a Python project, some instructions are shown titled "PYTHON SET UP FOR COVERALLS" as a quick start for setting up coveralls for Travis CI and whatnot. However, the instructions shown are actually for a Ruby project and not in-fact Python.

**Comment by omry** [comment]
really guys, can you spend 10 minutes so your docs are actually helpful?
