### ISSUE TITLE
Coverage report not displayed

### ISSUE THREAD

**Issue by ain** [lemurheavy/coveralls-public#1169]
We've added a private repo for coverage, running CircleCI in the background. Since last week we didn't get coverage updates anymore. Today I've removed the repo on Coveralls, re-added it, no change. The coverage page at `https://coveralls.io/github/<organisation>/<repo>` remains empty.

CircleCI reports:

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #10559.1
[Coveralls] https://coveralls.io/jobs/38626697
Coverage is at …%.
```

Please advise.

**Comment by bytewalls** [comment]
@ain,

It looks like the issues likely related to the parallel builds. Are you using the parallel build webhook notification hook?

**Comment by ain** [comment]
I did not get this hook working with CircleCI 2.0 Workflows. It simply did not trigger.

**Comment by ain** [comment]
I can confirm the problem is parallelism. Turning it off does publish the results correctly.

**Comment by bytewalls** [comment]
@ain,

Is this how you have the webhook configured:
```
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
```

This is pulled out of our own codebase which is working on Circle 2.0, with the environment variable `COVERALLS_REPO_TOKEN` set.

**Comment by ain** [comment]
I'm having trouble matching it with up to date documentation, see https://circleci.com/docs/2.0/configuration-reference/

@bytewalls are you sure the config you have is for 2.0? 1.0 support ends on Aug 31st, it's still working currently.

**Comment by bytewalls** [comment]
@ain,

Yes we are using Circle 2.0. You are correct that the documentation does not talk about the webhooks in 2.0 but their team confirmed it worked the same when I reached out to the CircleCI team a couple months ago, and I further tested it when we created our circle instance on 2.0 to test it.

**Comment by bytewalls** [comment]
@ain, at the root level.

**Comment by ain** [comment]
Just a note here: when using CircleCI Workflows, `notify` does not work as documented. 

Details in the exchange on Twitter: https://twitter.com/FelicianoTech/status/1034131044981727233

**Comment by ain** [comment]
The above exchange was by CircleCI's Dev Advocate who confirmed the problem. 

I'd call for reopening the ticket as well as considering the same for #1151.
