### ISSUE TITLE
Using Coveralls with CircleCI parallelism 

### ISSUE THREAD

**Issue by dennmart** [lemurheavy/coveralls-public#117]
I've set up Coveralls with CircleCI and it all works great - tests are run and results are being pushed into Coveralls. However, our CircleCI test setup has [parallelism](https://circleci.com/docs/how-parallelism-works) set up and this seems to be collecting incorrect coverage data. We run our tests using two separate containers, and it seems that the coverage results that Coveralls is showing is only from the last batch of tests instead of the aggregate of both.

We can't use `Coveralls.wear_merged!` because the tests are run in two separate servers that don't share any info. Is there some additional setup I need to do to get this working properly?

**Comment by drewvanstone** [comment]
Me too!!

**Comment by nickmerwin** [comment]
hi @nhodges @drewvanstone @barclay @coryschires @dennmart we've recently released support for this feature, please see our new docs here:

https://coveralls.zendesk.com/hc/en-us/articles/203484329

Thanks!

**Comment by barclay** [comment]
@nickmerwin Godbless you. Can't wait to try it out.

**Comment by zamiang** [comment]
How does one get access to those documents?

**Comment by jalerson** [comment]
@zamiang https://docs.coveralls.io/parallel-build-webhook
