### ISSUE TITLE
Support for Bitbucket pipelines build

### ISSUE THREAD

**Issue by hnhegde** [lemurheavy/coveralls-public#1172]
Hello,
Is Bitbucket pipelines build system supported by coveralls?

Thanks,
Harsha

**Comment by Themanwithoutaplan** [comment]
I have coveralls running fine with pipelines.

**Comment by solkimicreb** [comment]
Hi @Themanwithoutaplan!

I am having some trouble with the pipeline. I added an npm script and the repo token (as env var) to the pipeline and it sends the coverage data to coveralls fine, but the coveralls page can not fetch the source code somewhy when I try to check my coverage. Do you have experience with coveralls integration of private repos on bitbucket?

Thanks! 🙂

**Comment by Themanwithoutaplan** [comment]
I have no experience with private repos but I think you just have to make sure the GIT_URL is exposed. See https://bitbucket.org/openpyxl/openpyxl/addon/pipelines/home#!/results/543 (I'm using Mercurial so have to expose it explicitly).

**Comment by solkimicreb** [comment]
Thanks, I will try that!

**Comment by bizob2828** [comment]
@solkimicreb I have this working by using https://github.com/nickmerwin/node-coveralls.  I had to add the `COVERALLS_REPO_TOKEN` env var to my bitbucket administration dashboard.  I'm trying to fork that repo and get it to report PRs and such
