### ISSUE TITLE
Overall reported coverage is incorrect

### ISSUE THREAD

**Issue by paulromano** [lemurheavy/coveralls-public#1173]
I'm running into a strange issue where the overall reported coverage for a build is incorrect when compared to the reported coverage for the individual jobs that make it up. For example, for [this build](https://coveralls.io/builds/18456842)
- The overall coverage reported is 70.9%
- Each of the individual jobs has coverage of about 76.6%
- When I look at individual files under the "Source Files" section, some of them have a question mark and a "No data" tooltip. However, when I click one of them, the coverage for the individual file is successfully shown.

Any idea what could be going on?

**Comment by bytewalls** [comment]
@paulromano It looks like you have a lot of jobs running in parallel but may not be using the parallel build webhook. This can result in race conditions in the calculation of coverage data.
 Which integration library are you using with Coveralls?

**Comment by paulromano** [comment]
Thanks for looking into this @bytewalls! I'm using pytest-cov. I wasn't aware of the parallel build webhook but that sounds exactly like what I need.

**Comment by paulromano** [comment]
Sorry, meant to say python-coveralls.

**Comment by paulromano** [comment]
After using the parallel build webhook, things are looking good. I'll go ahead and close this. Thanks again for the help @bytewalls!
