### ISSUE TITLE
Coveralls not reporting data after successful upload by CircleCI

### ISSUE THREAD

**Issue by acravenho** [lemurheavy/coveralls-public#1176]
Github Repo: https://github.com/poanetwork/blockscout
Coveralls Repo: https://coveralls.io/github/poanetwork/blockscout
CircleCI Reporting: https://circleci.com/gh/poanetwork/blockscout/20940 (at the bottom)

We've been experiencing an issue where Coveralls is not reporting any data that are being received from CircleCI regarding our builds. 

### Events
1. Changed our Github Repo name from `poa-explorer` to `blockscout`
2. Clicked `sync` on Coveralls repo once we renamed hoping our data would transfer over. This did not work.
3. Generated a new token on Coveralls and added it to CirceCI which did not work either.

I'm not sure what to do from here.

<img width="588" alt="screen shot 2018-08-22 at 3 36 49 pm" src="https://user-images.githubusercontent.com/17620007/44486329-449be880-a621-11e8-93d4-b39d2888ff0e.png">

<img width="1049" alt="screen shot 2018-08-22 at 3 37 04 pm" src="https://user-images.githubusercontent.com/17620007/44486342-4a91c980-a621-11e8-90fb-4aef055bac00.png">

**Comment by bytewalls** [comment]
@acravenho,

Couple things, first I was able to transfer over data from the old repo to the new one.

Second, it looks like you are creating multiple parallel jobs and correctly reporting that but not using the webhook to inform coveralls servers that all jobs are done running in your `.circleci/config.yml` file you will want this to inform coveralls that all jobs have been sent so we can aggregate the data and mark the build as done.

This should be a top level piece (not nested under jobs) of the yaml file

```
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
```

**Comment by bytewalls** [comment]
@acravenho you can use it exactly as typed when a secure environment variable called `COVERALLS_REPO_TOKEN` is set and circle uses the secure token so you don't need to expose the repo_token.

**Comment by acravenho** [comment]
@bytewalls I believe I'm doing everything correctly and our builds are still not populating to Coveralls. Here is my pull request which should have caused a build to populate: https://github.com/poanetwork/blockscout/pull/595.

Please let me know if there is something else I can try. Thank you for your time.
