### ISSUE TITLE
Badge not detected

### ISSUE THREAD

**Issue by daurnimator** [lemurheavy/coveralls-public#1179]
On https://coveralls.io/github/daurnimator/lua-http I see 

>  Badge your Repo: lua-http
> We detected this repo isn’t badged! Grab the embed code to the right, add it to your repo to show off your code coverage, and when the badge is live hit the refresh button to remove this message. 

However the badge is present: https://github.com/daurnimator/lua-http/blob/master/README.md#status

**Comment by daurnimator** [comment]
.

**Comment by afinetooth** [comment]
@daurnimator the badge warning message appears to be gone for your repo now:

![Screen Shot 2020-04-13 at 12 58 01 PM](https://user-images.githubusercontent.com/918667/79155788-89d8d500-7d86-11ea-9cf2-540eb82611bb.png)

Sometimes, re-syncing your repo in Settings will resolve that:

![Screen Shot 2020-04-13 at 12 57 45 PM](https://user-images.githubusercontent.com/918667/79155802-8e9d8900-7d86-11ea-9a46-567368a91140.png)

Can you confirm it's working as expected now?

**Comment by daurnimator** [comment]
Yeah I think its working now.....
