### ISSUE TITLE
Question about a setting to count a line as covered if any build covers it

### ISSUE THREAD

**Issue by acravenho** [lemurheavy/coveralls-public#1181]
Is there a setting so that we can tell Coveralls.io to count a line as covered if any build covers it?

In our case, only some of the parallel jobs cover the line, so it is counting as uncovered. 

![screen_shot_2018-08-31_at_4 09 37_pm](https://user-images.githubusercontent.com/17620007/44954652-22049d80-ae73-11e8-8442-4c142a42acc0.png)

We want the line to count as covered in this case because we only expect certain lines to be covered by `mox` or `parity` or `geth`.

Is there a setting for this?

**Comment by bytewalls** [comment]
@acravenho can you point me to this file in Coveralls for me? This line shouldn't be counted as uncov obviously, we will take a look and work to rectify the error that caused this, thanks.
