### ISSUE TITLE
Unjustified decrease in coverage reported

### ISSUE THREAD

**Issue by skion** [lemurheavy/coveralls-public#1182]
We're [not quite sure](https://github.com/oauthlib/oauthlib/issues/582) why Coveralls is reporting a decrease in coverage for [this build](https://coveralls.io/builds/18710527), as there have been no code changes in the [corresponding PR](https://github.com/oauthlib/oauthlib/pull/581). In fact, many of our PRs report a inconsistent numbers. Can you help find the problem?

**Comment by JonathanHuot** [comment]
I'm wondering if restricting the `coveralls` command to a single build (instead of each Travis Matrix combination) can help.

Moving from 

     after_success: coveralls

Into 

     after_success:
        if [[ "$TOXENV" == "py36" ]]; then
            coveralls
        fi

**Comment by bytewalls** [comment]
When running the jobs in a parallel matrix you will want to mark the job as "parallel" by setting the environment varialb `COVERALLS_PARALLEL=true` and then add this webhook to your travis config: 

```notifications:
  webhooks: https://coveralls.io/webhook
```

**Comment by JonathanHuot** [comment]
@bytewalls: it seems it fixed the coverage increase/decrease, but it removed the Github status API notifications on PR. Odd!

Previous PR with previous version of `.travis-ci.yml`: https://github.com/oauthlib/oauthlib/pull/565
Updated PR with new version of `.travis-ci.yml`: https://github.com/oauthlib/oauthlib/pull/587

Also, you can see my `.travis-ci.yml` updates: https://github.com/oauthlib/oauthlib/commit/b02809db83ad490f6ff3f1b86037272bebb4e041

Any additional clues ? Thanks !

**Comment by skion** [comment]
Oddly the status is back again on [this PR](https://github.com/oauthlib/oauthlib/pull/630), but missing on e.g. [this](https://github.com/oauthlib/oauthlib/pull/617) or [this](https://github.com/oauthlib/oauthlib/pull/627).
