### ISSUE TITLE
Coveralls creates PR comment but does not update status

### ISSUE THREAD

**Issue by leofeyer** [lemurheavy/coveralls-public#1183]
I am referring to https://github.com/contao/contao/pull/47. Coveralls has created a PR comment but it does not update the status:

<img width="812" alt="" src="https://user-images.githubusercontent.com/1192057/45019060-ac8ffd00-b02b-11e8-88dc-f43f459d8c1b.png">

Any idea why this is?

**Comment by leofeyer** [comment]
To clarify this: I know why the status is "Waiting for status to be reported". However I don't know why coveralls.io is not reporting the status to GitHub.

**Comment by bytewalls** [comment]
@leofeyer, I'm investigating this, there appears to be some sort of OAuth issue in creating comments. Can you verify for me that on this page for [Coveralls 
 OAuth connection with Github ](https://github.com/settings/connections/applications/ad4c01c89848a307e228), that the contao group has given access? Thanks, sorry for the delay in response.

**Comment by leofeyer** [comment]
> that the contao group has given access?

It does:

<img width="773" alt="" src="https://user-images.githubusercontent.com/1192057/45341153-d2705100-b599-11e8-98a6-9446d9949d9f.png">

Thank you for your help.

**Comment by wmarra** [comment]
We have the same issue here.
