### ISSUE TITLE
API to report on coverage for a private repo/org

### ISSUE THREAD

**Issue by prologic** [lemurheavy/coveralls-public#1189]
I'm having a bit of difficulty following your API Documentation:

* https://docs.coveralls.io/api-introduction
* https://docs.coveralls.io/api-reference

Through the Web UI (_logged in_) I can easily access the coverage data for a repo using the following URI:

* https://coveralls.io/github/org/repo.json

Which gives me what I need:

```#!json
  "created_at": "...",
  "url": null,
  "commit_message": "",
  "branch": "",
  "committer_name": "",
  "committer_email": "",
  "commit_sha": "",
  "repo_name": ",
  "badge_url": "",
  "coverage_change": -0.0,
  "covered_percent": 10.00
}
```

For example.

How do I programatically _(say using `curl`_) access this data via the API without resorting to web browser craping via some robot?

**Comment by prologic** [comment]
Possibly related but unclear as to proper usage. #773

**Comment by prologic** [comment]
**NB:** This works fine for public repos:

```#!bash
$ curl -q -s -o - https://coveralls.io/github/circuits/circuits.json | jq -r '.covered_percent'
87.5435835724644
```

**Comment by bytewalls** [comment]
The Coveralls API is authenticated using Personal Access Tokens, which can be found on your [Coveralls Account page](https://coveralls.io/account).

The `Authentication` header is used to send this token, in the format `token XXX` where `XXX` is replaced with your token.

Your personal account token(s) should be kept private as it gives access to information from your private repos. You can access non-private/public information without authentication, as you see from using the curl command to access a public repos.

**Comment by prologic** [comment]
What seems to be missing is an endpoint with the data I'm after.

**Comment by bytewalls** [comment]
@prologic what data are you after?

**Comment by jbarrieClassy** [comment]
Hi I also have the same question the documentation is very lacking. I would like to see the coverage percentage by lines, like it is displayed in the ui report.

**Comment by prologic** [comment]
> @prologic what data are you after?

Was my original request not clear? I want the same data that can be retrieved from:

```
$ curl -q -s -o - https://coveralls.io/github/circuits/circuits.json | jq -r '.covered_percent'
87.5435835724644
```

Using the Coveralls API. AFAICT my work-around shell pipeline:

* Uses the `.json` resource of the repository
* Requires access to a `repo_token` for private repositories

**Comment by cabello** [comment]
I am facing similuar issues as @prologic .

I want to get reports from all of my repos by hitting `GET https://coveralls.io/repos.json?page=N` until I hit an empty page then hit `GET https://coveralls.io/github/org/username.json?branch=master` for each repo to get the latest report.

With that data I will prepare a report for my organization.

The issue we are facing:
- Using `Authentication` header we are unable to hit these endpoints, only using my browser I can get those.
- The API documentation only covers POST and we are looking after reading this data: https://coveralls.io/api/docs

**Comment by cabello** [comment]
I can get coverage result hitting `GET https://coveralls.io/github/org/username.json?branch=master` if I use the `repo_token` parameter, however there is no API call to fetch all repo tokens, so I hit a dead end for automation.

**Comment by cabello** [comment]
@prologic I ended up resorting into using Cookie based authentication in order to obtain the coverage data I needed, I extracted a single file script people can use to build on top of it: https://gist.github.com/cabello/678142fac8ccb4244b2749831621ee7f

It's not ideal as obtaining the Cookie value requires logging in on the website but it works for now.

**Comment by cabello** [comment]
Bump stale bot. 🤖

**Comment by afinetooth** [comment]
@cabello You're correct that our API doesn't support reading cross-repo coverage results in bulk. It would be a great feature, so I've added a card to our backlog of features for consideration, containing your description and referring to this issue. I'll feedback here with any updates to the related card.

Thanks for the ingenious workaround; I'm sure others in the community will find it useful.

**Comment by nychang** [comment]
@cabello @afinetooth Where do I find this mysterious `repo_token`?

I tried using the following but both options still give me 403s:

- personal api token generated from coveralls.io/account
- personal access token with all permissions generated from github.com/settings/tokens

I am using Postman with:
```
Accept: application/json
Content-Type: application/json
Authorization: token <Coveralls personal api token>
Method: GET
Url: https://coveralls.io/github/github_username/repo_name.json?repo_token=<TOKEN>
```

Where `<TOKEN>` is the PAT I got from either Coveralls or GitHub, both of which still give 403s.

Thank you for your help! 🙌

**Comment by cabello** [comment]
@nychang I am no longer using Coveralls. I was not using the API as it did not fit my use case, I was using the Cookie solution I shared in gist. The repo token according to the [docs](https://docs.coveralls.io/api-reference) can be found: 
> The secret token for your repository, found at the bottom of your repository’s page on Coveralls.

Hope that helps you.

**Comment by nychang** [comment]
@cabello Thank you! Sadly, I don't see a token at the bottom of the page. Oh well. Still a mystery! 🤔 🤷‍♀️

**Comment by nychang** [comment]
In case anyone else runs into this issue, you need GitHub admin access to a private repo in order to see the `repo_token` at the **top** of the Coveralls repo page.

It should look like this:
<img width="2282" alt="coveralls-demo-repo-token" src="https://user-images.githubusercontent.com/7375189/144324512-bb6670f9-c3b3-43a9-97ef-d2b1152638c3.png">

I didn't see the token because I wasn't an admin.

**Comment by afinetooth** [comment]
Hi @nychang. I think we may have crossed paths about this in support email as well. In any case, you have found the Coveralls repo token for your repo. Great.

The other token you may need to use is the PAT (personal access token), which is needed for direct queries to the [/repos endpoint of the Coveralls API](https://coveralls.io/api/docs).

You can generate your PAT from your [account page](https://coveralls.io/account), which you'll find at: https://coveralls.io/account.

Let me know if i missed any of your open issues here.

**Comment by cabello** [comment]
Activity
