### ISSUE TITLE
Error on the calculated Coverage?

### ISSUE THREAD

**Issue by hgrecco** [lemurheavy/coveralls-public#1190]
In a recent PR (see [here](https://github.com/hgrecco/pint/pull/697)) Coveralls repors a reduction that I was not able to explain. Basically, only the AUTHORS and some docstring was changed and Coveralls reported a reduction of 6.9%. It seems to me that this is because  the file has now 2 lines less. But this does not make sense to me as the number of tested lines has not decreased. Is there something that I am missing?

**Comment by hgrecco** [comment]
It seems that some files appear twice (see for example, pint/context.py)

**Comment by znicholls** [comment]
could this be because of my fiddling around with the `.travis.yml` file in an attempt to get the coverage to only count the pandas files on the pandas tests?
