### ISSUE TITLE
Coverage is reported against "HEAD detached..." instead of the actual branch

### ISSUE THREAD

**Issue by courtney-miles** [lemurheavy/coveralls-public#1194]
At some point in the last month or two, all coverage is reported against a detached HEAD rather than the branch the commit belongs to.  Which means we are not getting a history of coverage on our branches any more because each coverage report is for a unique branch.

These builds are for a private repo, but for Coveralls staff who may have access, you can see an example of this at https://coveralls.io/builds/19294254.

The coverage is generated on Travis CI. I can see that Travis CI will clone `develop` and then checkout the commit to test, such that "HEAD detached ..." is obviously the name of the branch.  And this is what php-coveralls/php-coveralls is picking up as the branch name.

It used to work that coverage would be linked to the associated branches, and I don't know if Travis CI changes, php-coveralls/php-coveralls changed, Coveralls.io changed, or if it's something I have done.

Any assistance on how to get reports linked back to the regular branches would be appreciated.

Note that we recently adopt workflow that involved each developer having their own private fork.  But I would expect the merge of PR to still track coverage to the branch it is merged to.

---

**Update:** I realised that this issue might occur if my `service_name` of "travis-pro" was not being loaded from `.coveralls.yml`.  So ran the Travis build with debug and modified `php-coveralls/php-coveralls` to confirm it is loading my `.coveralls.yml` file and that `\PhpCoveralls\Bundle\CoverallsBundle\Config\Configuration::getServiceName()` does indeed return "travis-pro".

So I can confirm my coveralls configuration is being loaded correctly.

**Comment by courtney-miles** [comment]
Is there another way to get support here?

I can't see that there's any fault with our setup between Travis CI and Coveralls.

I have enjoyed Coveralls until now. But with no support and us no longer getting any useful coverage reports from Coveralls anymore, we will have no choice but to take our business elsewhere.

**Comment by NeilJ247** [comment]
I am seeing the issue as well on one of our private repos master branch.  I am not sure if it is because I possibly rebased at some point whilst initially working on master and it screwed things things up.  I deleted the repo in cloveralls and re-added it but still the same.

**Comment by afinetooth** [comment]
@courtney-miles apologies for the long delay. I checked your project and see that you got this resolved. In the future, you can email support@coveralls.io. 

There are a number of reasons why CI builds report `HEAD` or `HEAD detached at <commit>` and fixes usually entail a change on the CI side. The [Coveralls API](https://docs.coveralls.io/api-reference) simply accepts whatever your POST from Travis CI passes as the branch name in the `git` hash defined [here](https://docs.coveralls.io/api-reference). We don't modify that incoming value in any way. 

In addition to emailing us, prior to doing so it's always helpful to run one or two builds in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v). 

The option, and way, to invoke [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) depends on your integration. For [php-coveralls](https://github.com/php-coveralls/php-coveralls), there appears to be the `--verbose` flag, per [README > CLI options](https://github.com/php-coveralls/php-coveralls#cli-options). Ideally, the [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for the integration will show the exact JSON you're POSTing to the [Coveralls API](https://docs.coveralls.io/api-reference). You can then inspect that for `params[git][branch]`.

Finally, a suggestion for this particular issue: You can try setting a custom CI env var, `CI_BRANCH`, and/or `COVERALLS_GIT_BRANCH`, where you are setting it to the Travis CI env var `TRAVIS_BRANCH` for `push` builds, and `TRAVIS_PULL_REQUEST_BRANCH` for `pull_request` builds per docs on [Default Travis CI Environment Variables](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables). If you're getting `HEAD detached ...` for those, that also indicates those are the values coming from your CI.
