### ISSUE TITLE
Website not updating correctly

### ISSUE THREAD

**Issue by Themanwithoutaplan** [lemurheavy/coveralls-public#1195]
For about the last week the coveralls website has not been updating with the deltas for the various builds. The coverage information in the various builds is there, just not in the overview. Not sure if it's relevant but one of the JS files isn't loading: https://coveralls.io/builds/19251477/source_files.js returns a 500 code.

**Comment by bytewalls** [comment]
@Themanwithoutaplan thanks for the report, we have identified what is causing this issue and are working on rolling out a fix.

**Comment by bytewalls** [comment]
@Themanwithoutaplan a bug fix was released and it looks as though your builds are back to working as expected.
