### ISSUE TITLE
Coveralls updates check status, but doesn't provide Comment on PR

### ISSUE THREAD

**Issue by Barryrowe** [lemurheavy/coveralls-public#1198]
This is likely related to #1183 but I'm seeing the exact opposite where the coveralls status is reporting fine, but I never get a comment on the PR.

Status Reporting:
<img width="780" alt="screen shot 2018-10-04 at 3 55 32 pm" src="https://user-images.githubusercontent.com/1013426/46499398-fc5e1180-c7ed-11e8-90b2-9d6f1b514cf8.png">

No Comment over several commits and builds:
<img width="796" alt="screen shot 2018-10-04 at 3 55 38 pm" src="https://user-images.githubusercontent.com/1013426/46499454-20215780-c7ee-11e8-8a2f-c0e4c9832955.png">

Settings in Coveralls Dashboard:
<img width="623" alt="screen shot 2018-10-04 at 3 59 09 pm" src="https://user-images.githubusercontent.com/1013426/46499576-768e9600-c7ee-11e8-827e-b533906fc326.png">

**Comment by Barryrowe** [comment]
The PR in question is: https://github.com/Barryrowe/android-coveralls-example/pull/1

**Comment by bytewalls** [comment]
@Barryrowe, we don't leave comments on the first build of the repo. In this instance since there is no build on the branch you are merging into, comments will not be made.

The reason for this is that the comments just don't make sense or provide meaningful information without a comparison build.

**Comment by Barryrowe** [comment]
@bytewalls Thanks, this makes sense.
