### ISSUE TITLE
Coveralls Response time on

### ISSUE THREAD

**Issue by datadidit** [lemurheavy/coveralls-public#1203]
We recently moved to a mono repo for some of our Python projects. Things were working fine but in the last 2-3 days we appear to be getting slow response times at this url: https://coveralls.io/github/PhilliesAnalytics/phy . It either responds slowly or we get a gateway timeout.
<img width="1609" alt="screen shot 2018-10-16 at 6 33 06 am" src="https://user-images.githubusercontent.com/10933169/47010575-6c816700-d10d-11e8-9f9c-536d77bf65c4.png">

I've checked the status.coveralls.io link and all appears to be well there. Any suggestions on how we can avoid timeouts and get better response times from that URL.

**Comment by dansteele** [comment]
We have the same issue

**Comment by dansteele** [comment]
The page was returning the above error

Tried to go to the homepage instead of my app URL. Same issue.

Checked the status website, all seems fine

Deleted my cookies, home page loaded fine

Visited my app url, the 'HALT' page loaded fine

Tried to sign in via GitHub,issue arose again

**Comment by bytewalls** [comment]
Thanks all for the reports, we found an issue causing degraded performance, and have released a bug fix.

There is a backlog of data to process, but we are back up to full capacity and working on getting through the backlog. We will continue to monitor the situation. Sorry for the inconvenience.

**Comment by datadidit** [comment]
Any idea on when all the backlog data will be processed? Just trying to see when I should expect the GUI to perform normal again.

**Comment by bytewalls** [comment]
@datadit sorry for delayed response, everything is performing as usual again now.

**Comment by datadidit** [comment]
@bytewalls thanks
