### ISSUE TITLE
Coveralls job hanging.

### ISSUE THREAD

**Issue by linkdata** [lemurheavy/coveralls-public#1204]
Travis passed fine. Coveralls job is hung.

https://coveralls.io/jobs/41245920

Previous job seems to be incomplete?

https://coveralls.io/jobs/41245046

**Comment by ohmybrew** [comment]
I am having the same issue, all jobs simply say "Loading..." but they say they are completed.

**Comment by linkdata** [comment]
It's caught up. Closing as resolved.
