### ISSUE TITLE
Can't remove coveralls from repo

### ISSUE THREAD

**Issue by rowanseymour** [lemurheavy/coveralls-public#1208]
I'm unable to remove coveralls from [this repo](https://github.com/nyaruka/goflow) and it's still appearing as a check on PRs e.g. https://github.com/nyaruka/goflow/pull/426

I deleted the repo on the coveralls side so it no longer exists there:

https://coveralls.io/github/nyaruka/goflow -> 404
https://coveralls.io/github/nyaruka/goflow/settings -> 500

**Comment by bytewalls** [comment]
Coveralls is set as a required check on your github repo, github is creating the check as soon as the PR is created since it is required.
