### ISSUE TITLE
Error while initializing daemon

### ISSUE THREAD

**Issue by tswiftma** [lemurheavy/coveralls-public#1211]
After installing Coveralls Enterprise on CentOS 7.4.1708 (core) I get an error bringing up the browser https://(IP):8800/initializing?redirect=/

"Error while initializing daemon: Error cannot GET /api/v1/status/retraced/await (500)"

I saw a warning about SELinux running in enforcing mode so I disabled that mode and reinstalled but I still get the same error.

![image](https://user-images.githubusercontent.com/11710469/47739129-0fc49700-dc4b-11e8-8cf4-68159a37d09c.png)

**Comment by tswiftma** [comment]
Only occurs on CentOS install not on Ubuntu

**Comment by neuashish** [comment]
I have installed on Ubantu, and I am dealing with the same error @tswiftma
