### ISSUE TITLE
Coveralls does not consider #:nocov; upgrading gem makes coveralls not run.

### ISSUE THREAD

**Issue by weiyunlu** [lemurheavy/coveralls-public#1213]
Hello,

It appears that coveralls is not seeing the :nocov: tag in our Ruby on Rails app and is still including it in coverage reports.

A link to an affected file:
https://coveralls.io/builds/19829973/source?filename=lib/ext/string.rb

A link to a previous ticket for the same problem that does not appear resolved:
https://github.com/lemurheavy/coveralls-public/issues/1122

One thing we tried in troubleshooting was to upgrade the coveralls gem to the latest version.  This may or may not be related, but is another issue on its own in any case.  For some reason, going through standard setup instructions got us coveralls 0.7.1.  We tried running `bundle update coveralls` on local and pushing, with coveralls 0.8.22.  But doing this, Coveralls seems to not pick up on that branch.  

Links here: https://github.com/Zetatango/zetatango/pull/2449 vs. https://github.com/Zetatango/zetatango/pull/2386

**Comment by weiyunlu** [comment]
Hi, any updates on this issue?

**Comment by kotovalexarian** [comment]
I confirm the issue. While no lines are highlighted with red, the total file coverage is less than 100%.

https://coveralls.io/builds/20397862/source?filename=app/policies/application_policy.rb
