### ISSUE TITLE
Change timezone?

### ISSUE THREAD

**Issue by weiyunlu** [lemurheavy/coveralls-public#1214]
Hello,

Coveralls displays time zone in UTC and we would like to change this to EST to match the time zone of our office.  We have not found anything in the documentation, settings, or a google search that indicates how to do this.  Is it possible?

**Comment by weiyunlu** [comment]
Any updates on this?

**Comment by unageek** [comment]
Please reopen this.

**Comment by NaagAlgates** [comment]
I think this is a valid ticket and request you to reopen.

**Comment by afinetooth** [comment]
Hi @NaagAlgates, @unageek, @weiyunlu.

I have added this as an enhancement request to our development backlog. Cannot give an ETA, but it will be reviewed in the few weeks. I'll post updates here, but you can also email us for status at support@coveralls.io.

Thanks.
