### ISSUE TITLE
Coverage calculation seems to be broken

### ISSUE THREAD

**Issue by PetrKryslUCSD** [lemurheavy/coveralls-public#1217]
![image](https://user-images.githubusercontent.com/9855832/47967658-a959c300-e014-11e8-8cff-46b394cd93dc.png)
Notice that some lines are marked red, which is an impossibility since there is no branch.

**Comment by p-snft** [comment]
I have seen something similar in https://coveralls.io/builds/20962916/source?filename=src/PS/PhaseSpace.cpp#L463:
![grafik](https://user-images.githubusercontent.com/4871848/50843355-d2763700-1368-11e9-983f-96231eda858b.png)
