### ISSUE TITLE
"Source not available" for mgedmin/check-manifest

### ISSUE THREAD

**Issue by mgedmin** [lemurheavy/coveralls-public#1220]
Here's a recent build that shows this problem: https://coveralls.io/builds/19988219 (although, as far as I can tell, all builds have it).

Near the bottom of the page it shows a list of source files, but when I click on my sole source file, I get a [page](https://coveralls.io/builds/19988219/source?filename=check_manifest.py) that says SOURCE NOT AVAILABLE.

If instead I click on any _job_ in this build, e.g. https://coveralls.io/jobs/42029015, and _then_ click on my source file, I end up on a [page](https://coveralls.io/jobs/42029015/source_files/206826220) that shows the source just fine.

**Comment by jonhoo** [comment]
From what I can tell, this has been the case in a bunch of repositories for a while. #263 was the first, but [all of these](https://github.com/lemurheavy/coveralls-public/issues?utf8=%E2%9C%93&q=%22source+not+available%22) are basically the same. I just wish they'd fix it..

**Comment by jonhoo** [comment]
I do not believe this is stale.

**Comment by mgedmin** [comment]
Hm, the problem seems to be fixed for mgedmin/check-manifest builds.  Even the one in the original bug description now works.

**Comment by jonhoo** [comment]
I _believe_ have still seen this crop up for _new_ jobs, though you're right that old jobs that exhibited this issue seem to have been processed. Maybe there's just a very high processing delay for some jobs?

**Comment by georgedorn** [comment]
This issue continues to exist or has gotten worse.  For example, I have found no path to show which lines have coverage in this recent build: https://coveralls.io/builds/68748380
