### ISSUE TITLE
Deprecated usage of SimpleCov::Formatter::MultiFormatter in docs

### ISSUE THREAD

**Issue by chrisma** [lemurheavy/coveralls-public#1223]
In https://docs.coveralls.io/ruby-on-rails#simplecov-customization usage of `SimpleCov::Formatter::MultiFormatter` for using multiple formatters is recommended.

Using coveralls (0.7.1), simplecov (0.16.1), rails (~> 5.2.1), this is no longer supported:
![image](https://user-images.githubusercontent.com/1652117/48356144-e0c01380-e695-11e8-8e83-ea7645a9d638.png)

The recommended way of specifying multiple formatters is described here: https://github.com/colszowka/simplecov/blob/master/features/config_formatters.feature

In the documentation, the code

```
require 'simplecov'
require 'coveralls'

SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter([
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
])
SimpleCov.start
```

should instead be

```
require 'simplecov'
require 'coveralls'

SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
SimpleCov.start
```

**Comment by chrisma** [comment]
As of today (2020-04-07), the documentation at [https://docs.coveralls.io/ruby-on-rails#simplecov-customization](https://docs.coveralls.io/ruby-on-rails#simplecov-customization) has not been updated and still includes the non-functional code. 

![image](https://user-images.githubusercontent.com/1652117/78677850-822db200-78e8-11ea-8e92-b546e541022d.png)

**Comment by chrisma** [comment]
As of 2021-07-08 the coveralls.io documentation still shows the outdated `MultiFormatter.new ` (https://docs.coveralls.io/ruby-on-rails#simplecov-customization):

```ruby
require 'simplecov'
require 'coveralls'

SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
])
SimpleCov.start
```

**Comment by afinetooth** [comment]
@chrisma apologies for the delay. thanks for the contribution. have submitted a PR with your updated example. it should appear [here](https://docs.coveralls.io/ruby-on-rails#simplecov-customization) shortly. Thanks again!

**Comment by chrisma** [comment]
This issue probably shows that persistence can pay off :)
Thanks for taking care of this issue! Looks good.

![image](https://user-images.githubusercontent.com/1652117/125162864-851def00-e18a-11eb-86d9-5735b4011136.png)

**Comment by afinetooth** [comment]
@chrisma it definitely does. Thanks for that.
