### ISSUE TITLE
Folders with the PHP Interfaces are shown as 0%

### ISSUE THREAD

**Issue by dmitry-ivanov** [lemurheavy/coveralls-public#1225]
While the PHP Interfaces are marked as 100%, the folder is marked as 0%.

Would be nice to have the folders marked as 100% too.

https://coveralls.io/builds/20097697 (see the "Contracts" folder)

![contracts](https://user-images.githubusercontent.com/1286821/48482439-57d1e500-e819-11e8-98c7-7c4294aaa0cf.png)

**Comment by kapxapot** [comment]
This is still relevant.

**Comment by szepeviktor** [comment]
@lemurheavy @coverallsapp Yes, 14*100.0% equals 0.0% :)

![kép](https://user-images.githubusercontent.com/952007/94366754-9c4b8e80-00da-11eb-89f8-44d9cfbda199.png)

**Comment by afinetooth** [comment]
@dmitry-ivanov @szepeviktor I ran a procedure on your build that corrects for a potential race condition during the original (parallel) build. That appears to have fixed it:

![Screen Shot 2020-10-02 at 5 34 19 PM](https://user-images.githubusercontent.com/918667/94979057-81f82300-04d5-11eb-81de-e4135e019f77.png)

If it doesn't, or if it happens again (it shouldn't), let us know.

Thanks.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by dmitry-ivanov** [comment]
@afinetooth Thanks for the update! 👍

I've run a new Travis build ([#327](https://travis-ci.com/github/dmitry-ivanov/dark-sky-api/builds/184442882)), and in the proper [Coveralls build](https://coveralls.io/builds/33480981) - I still see the same issue:

![coveralls](https://user-images.githubusercontent.com/1286821/94986098-83bcf780-0564-11eb-8d8e-93fc61af0140.png)

**Comment by afinetooth** [comment]
@dmitry-ivanov likewise, thanks for the update. two issues here then i suppose: 

1. one was the fact that your build wasn't being recognized as parallel and therefore wasn't checking for a race condition between background jobs that do individual and aggregate calculations. (fixed.) 

2. the other is this issue of some folders not reflecting the aggregate percentage of their folders. happens for some and not for others. (persists.)

i have submitted an internal issue for (2) and will feedback as soon as I have an update.
