### ISSUE TITLE
Does not sync any public repos from github

### ISSUE THREAD

**Issue by cckrause** [lemurheavy/coveralls-public#1227]
When i try to add a repo its showing: "Your repos are syncing..." and nothing is happening. I tried to hit the manual button to sync again. I logged out and in, i tried to delete the account and revoked permissions on github.com. Also signed up again with github.

Services seem to be OK.
https://status.github.com/messages
http://status.coveralls.io/

My Github account is PRO and my account doesn't belong to any organization.

**Comment by arbulu89** [comment]
Same issue here. Synchronization is still in progress since 3-4 hours ago.

**Comment by ismay** [comment]
I'm having the same problem. Syncing takes forever. Hasn't finished yet. Also tried signing out and in like @cckrause.

**Comment by Peter554** [comment]
Same issue here
