### ISSUE TITLE
Coverage has stopped running 

### ISSUE THREAD

**Issue by adambratt** [lemurheavy/coveralls-public#1230]
On all of our PRs in the last 24 hours or so it looks like Coveralls is just completely hanging and never responds back:

![image](https://user-images.githubusercontent.com/674271/49555674-84779a80-f8b5-11e8-91fb-b19db58c98c5.png)

I'm not seeing anything wrong with the configuration so I'm not sure why this is happening

**Comment by yurenji** [comment]
+1 same problem here

**Comment by maxsam4** [comment]
Facing the same issue since the 4th of December.

**Comment by purbanow** [comment]
Same here +1

**Comment by pkiraly** [comment]
Same here +1

**Comment by datadidit** [comment]
+1 also is it possible to update the webapp(http://status.coveralls.io/) to not say operational when stuff like this is going on. Or maybe have operational be `yellow` since the fix is being implemented.

**Comment by DarkGhostHunter** [comment]
Still happening. I have no coveralls metrics or nothing all this day.
