### ISSUE TITLE
API documentation: how to use service_pull_request ?

### ISSUE THREAD

**Issue by fingolfin** [lemurheavy/coveralls-public#1244]
On https://docs.coveralls.io/faq it says:
> Also, any CI integration can support this if they implement this API post parameter: `service_pull_request`

But no indication is given to what value one should / could set it, and the API "documentation" does not mention it either.

**Comment by k1o0** [comment]
I would also like to see more detail in the documentation for this.

**Comment by donmahallem** [comment]
It does look like its the Pull Request Number from Github for example. In case of travis its: [TRAVIS_PULL_REQUEST](https://docs.travis-ci.com/user/environment-variables/) environment variable
