### ISSUE TITLE
Not Detecting TravisCI.com Open Source Builds

### ISSUE THREAD

**Issue by pathaugen** [lemurheavy/coveralls-public#1247]
So I've been experimenting with Coveralls however the service doesn't detect and work with TravisCI.com builds.

Example:
https://travis-ci.com/pathaugen/doitall-golang
https://coveralls.io/github/pathaugen/doitall-golang

From the documentation, public builds on Travis should be detected and work so I'm not sure the issue here. I'm aware of config files but in public repos Coveralls recommends two things: 1) You don't need that for public repos and 2) Don't expose your key which means for public repos you wouldn't make that config file anyway.

So.. what gives?

**Comment by nick-woodward** [comment]
**Hitting the same issue:**

* https://github.com/salte-io/salte-auth-angularjs/pull/213
* https://coveralls.io/builds/21585670

Everything seems to be getting sent correctly, it just isn't sending a status back to the PR.
