### ISSUE TITLE
GitLab Support ETA?

### ISSUE THREAD

**Issue by micheljung** [lemurheavy/coveralls-public#1248]
I've been reading "Gitlab support coming very soon!" on the front page for quite a while now.
Is there any ETA?

**Comment by nick-woodward** [comment]
I've noticed a couple of updates over on coveralls.io. Not exactly sure when they were implemented.

* Linking your GitLab account with Coveralls is now supported.
* Syncing your repositories from GitLab also seems to work.

This isn't documented anywhere in the Coveralls docs (it still says "Gitlab support coming very soon!").
Also upon attempting to publish to GitLab I get the following error.

```sh
$ coveralls < coverage/lcov.info

/usr/local/lib/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
ERROR: Job failed: exit code 1
```

I'm guessing some of the GitLab integration is finished, but publishing from the `gitlab-ci` service isn't currently supported / enabled.

**Comment by mathstuf** [comment]
The homepage says that GitLab is supported now, but does this mean just `gitlab.com`? Or are self-hosted public instances also supported?

**Comment by micheljung** [comment]
@mathstuf where did you see that? One can sign up/in with GitLab, but https://docs.coveralls.io/ still says `Gitlab support coming very soon!`

**Comment by mathstuf** [comment]
coveralls.io has an icon in the top-left saying that Bitbucket and GitLab are now supported.

**Comment by rogersachan** [comment]
this issue should probably be closed

**Comment by mathstuf** [comment]
If there's another issue to reconcile the internal dissonance here:

> Your code must be hosted on GitHub, BitBucket, or GitLab

and:

> Gitlab support coming very soon!

sure, closing this one seems fine.

**Comment by earonesty** [comment]
Can't see private repos on gitlab tho.

**Comment by Alir3z4** [comment]
I can see Gitlab is supported and I have enabled private repositories already and the job shows the coverage percentage

![image](https://user-images.githubusercontent.com/591113/77622030-9c61aa80-6f4e-11ea-8620-0e486e97935e.png)


However, I cannot find a way to enable pull requests comments ? Similar to https://gitlab.com/nickmerwin/coveralls-demo/-/merge_requests/3#note_229046643

We already have added `@coveralls` gitlab user to our repo with developer access as well, but not sure why we get nothing yet.

**Comment by afinetooth** [comment]
If it helps anyone here, GitLab setup instruction are here:
https://docs.coveralls.io/gitlab

They have been up since Oct, 2019.

FYI @earonesty support for private Gitlab repos is supported as of Spring 2020.

Closing for now. Just reply for follow-up.

**Comment by Alir3z4** [comment]
@afinetooth I've followed up the link you provided before and explained the problem on my comment  https://github.com/lemurheavy/coveralls-public/issues/1248#issuecomment-604279986 and so far it has not been any progress or response from coveralls about it

**Comment by afinetooth** [comment]
@Alir3z4 apologies. Re-opening the issue. I've re-labeled it for core team. Someone will get to it asap.

**Comment by ndbroadbent** [comment]
I was wondering if I could please request some better documentation for parallel builds on GitLab CI? I have a CI pipeline set up with multiple jobs to run my RSpec tests. It looks the `coveralls` SimpleCov formatter is working ok, but it was difficult to piece together the instructions from the ["Parallel Builds" docs](https://docs.coveralls.io/parallel-build-webhook).

I've set `COVERALLS_PARALLEL=true`, and I have something like this in my `.gitlab-ci.yml` config:

```
variables:
    COVERALLS_GIT_COMMIT: '$$CI_BUILD_REF'
    COVERALLS_GIT_BRANCH: '$$CI_BUILD_REF_NAME'
...
script:
  - ... COVERALLS_PARALLEL=true rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL
after_script:
  - curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN \
    -d "payload[build_num]=$CI_PIPELINE_ID&payload[status]=done"
```

This will send the webhook 7 times, after each individual job is completed. Is this correct? I'm not sure how to set up a webhook that only fires once after ALL jobs are completed.

Also, is it correct to group the builds using the pipeline ID as build_num?

**Comment by afinetooth** [comment]
@ndbroadbent and others still struggling with Gitlab CI. We are updating our docs to match the latest Gitlab config changes.

In the meantime, here is the [.gitlab-ci.yml](https://gitlab.com/graphql-devise/graphql_devise/-/blob/b9ab09e8bc2dd0b1a3e359c0c1f409764f16f248/.gitlab-ci.yml) of a [public Gitlab project](https://gitlab.com/graphql-devise/graphql_devise/-/tree/b9ab09e8bc2dd0b1a3e359c0c1f409764f16f248) pushing coverage from parallel builds to Coveralls.

**Comment by MuellerSeb** [comment]
> In the meantime, here is the [.gitlab-ci.yml](https://gitlab.com/graphql-devise/graphql_devise/-/blob/master/.gitlab-ci.yml) of a [public Gitlab project](https://gitlab.com/graphql-devise/graphql_devise) pushing coverage from parallel builds to Coveralls.

The linked project doesn't provide a `.gilab-ci.yml` anymore.

**Comment by afinetooth** [comment]
@MuellerSeb I have updated the links above to point to a snapshot of the code from Apr 2021. Here is that [.gitlab-ci.yml](https://gitlab.com/graphql-devise/graphql_devise/-/blob/b9ab09e8bc2dd0b1a3e359c0c1f409764f16f248/.gitlab-ci.yml).

**Comment by mathstuf** [comment]
I don't think this is complete.

**Comment by mathstuf** [comment]
Was it just for `gitlab.com` or are self-hosted instances supported as well?

**Comment by afinetooth** [comment]
[Coveralls Cloud](https://coveralls.io/) supports Gitlab.com only; but [Coveralls Enterprise](https://enterprise.coveralls.io/) supports both Gitlab.com and self-hosted Gitlab Enterprise.

**Comment by mathstuf** [comment]
Ok, thanks.
