### ISSUE TITLE
Billing quetion

### ISSUE THREAD

**Issue by ledio** [lemurheavy/coveralls-public#1250]
I'm trying to close an account, and I can't seem to be able to do it.  I have a separate github account that it used to manage billing, and I can't seem to be able "unsubscribe" to anything, so it can stop charging me.  Who do I talk to about this?

**Comment by afinetooth** [comment]
@ledio for more timely support on issues like billing, please email us at support@coveralls.io. Someone will expedite handling billing issues for you.
