### ISSUE TITLE
Github status stuck with "Expected — Waiting for status to be reported"  

### ISSUE THREAD

**Issue by pallavi2209** [lemurheavy/coveralls-public#1251]
Hi,
Our open source project on GitHub usually works with Coveralls, but it gets stuck with following error now and then (nothing updated recently):
<img width="779" alt="screen shot 2019-01-18 at 3 50 20 pm" src="https://user-images.githubusercontent.com/11909235/51418533-ce040800-1b38-11e9-8e80-dd57b0ed5ae6.png">

I have tried following:
1. Restarting Travis CI build multiple times.
2. Closing and re-opening the PR (idea from issue: https://github.com/lemurheavy/coveralls-public/issues/905)

Please advise what else we can try to get this to work.

**Comment by markrity** [comment]
Having the same issue (not using Travic CI)
