### ISSUE TITLE
Check not even showing on GH PRs

### ISSUE THREAD

**Issue by poncianodiego** [lemurheavy/coveralls-public#1254]
coverage/coveralls check is not even showing on PRs for our private repo, all info is on coveralls.io but no check showing only our CircleCi checks are showing.

**Comment by JetFault** [comment]
same with our repo for the last month

**Comment by nozkok** [comment]
@poncianodiego @JetFault  
did you find any solution?

**Comment by nickmerwin** [comment]
@poncianodiego @JetFault @nozkok could you add the names of the repos in question?

**Comment by nozkok** [comment]
@nickmerwin    useinsider/alfred  (it is private repo)

**Comment by nickmerwin** [comment]
@nozkok ok looks like the user that added that repo is no longer in the system, so I've assigned it to you and re-triggered the build statuses. Can you confirm they came through?

**Comment by JetFault** [comment]
@nickmerwin   perka/cloverdotcom

**Comment by nickmerwin** [comment]
@JetFault ok same issue, I've re-assigned the repo to your user.

**Comment by nozkok** [comment]
@nickmerwin   thanks a lot 👍
