### ISSUE TITLE
Cannot reference coverall repo by name

### ISSUE THREAD

**Issue by rjriel** [lemurheavy/coveralls-public#1258]
I've added one of our open source repos to coveralls. I am able to find the repo by repo number:

https://coveralls.io/repos/247499

But for some reason I can't reference the repo by repo name in the URL:

https://coveralls.io/github/Qlik-Branch/tesseract.js

Unfortunately all links that coveralls.io references is the latter rather than the former

**Comment by rjriel** [comment]
An update on this in case it helps. Referencing sub pages like settings:
https://coveralls.io/github/Qlik-Branch/tesseract.js/settings
seems to work. It's just the main page that doesn't

**Comment by rjriel** [comment]
Couple more pieces in case they're useful...

it gives a 406 HTTP error when attempting to view this on chrome, however when I use Postman I get a 200 code and everything seems fine.

Also I can reproduce the problem with a different repo: https://coveralls.io/github/qlik-oss/halyard.js

**Comment by afinetooth** [comment]
@rjriel I'm going to close this issue since it appears to be resolved. Please reply if you need follow-up. Thanks.
