### ISSUE TITLE
Rust projects are showing ruby set up documentations

### ISSUE THREAD

**Issue by abbychau** [lemurheavy/coveralls-public#1260]
my repo: https://coveralls.io/github/abbychau/diesel_cli_ext?branch=master

expected: rust documentations
<img width="1072" alt="screen shot 2019-02-04 at 10 55 16" src="https://user-images.githubusercontent.com/350283/52186560-66092d80-286b-11e9-899a-41bf8a7d4ec8.png">
these seem to be for ruby

**Comment by afinetooth** [comment]
@abbychau apologies for the issue. We currently have no community support for Rust.
