### ISSUE TITLE
Instructions for JavaScript repo setup erroneously show Ruby setup

### ISSUE THREAD

**Issue by lucaong** [lemurheavy/coveralls-public#1261]
I am adding a JavaScript repo to Coveralls. The setup page title correctly says "JavaScript set up for Coveralls", but it shows the Ruby instructions instead (add gem to Gemfile, etc.).

**Comment by lucasgcb** [comment]
This also shows up for Python. 
Instructions for Travis are also very unclear.
Pretty messy.

**Comment by afinetooth** [comment]
Fixed. Thanks for your patience.
