### ISSUE TITLE
Got a `406` error when the repository name ends with `.js`

### ISSUE THREAD

**Issue by Lanfei** [lemurheavy/coveralls-public#1262]
I have a project names [playable.js](https://github.com/Lanfei/playable.js), but I can't visit the detail page because I got a `406` error:

https://coveralls.io/github/Lanfei/playable.js

**Comment by cedx** [comment]
Confirmed on my side: all my projects whose name ends with `.js` results in a HTTP 406 error.
Some examples:

- https://coveralls.io/github/cedx/cookies.js
- https://coveralls.io/github/cedx/coveralls.js
- https://coveralls.io/github/cedx/free-mobile.js
(and the list goes on....)

This reminds me another issue: #897
(two years after, it is still not resolved... I gave up)

**Comment by taras** [comment]
Same here: https://coveralls.io/github/microstates/microstates.js

**Comment by nickmerwin** [comment]
Hi all, repo names with extensions are supported now!

The only caveat is that appending `.json` to the repo url won't behave as expected. You'll need to use `https://coveralls.io/repos/:id.json` instead.

**Comment by xPaw** [comment]
@nickmerwin `.php` still throws 403 though: https://coveralls.io/github/xPaw/SteamID.php

And I noticed that the served `content-type` changes depending on the type.

https://coveralls.io/github/test/test.js sends javascript content-type  
https://coveralls.io/github/test/test.png sends image/png content-type

**Comment by cedx** [comment]
@xPaw You can append a final slash to the URL to make it work:
https://coveralls.io/github/xPaw/SteamID.php/
