### ISSUE TITLE
Coverage missing for random builds

### ISSUE THREAD

**Issue by Flamefire** [lemurheavy/coveralls-public#1263]
On some builds the coverage data seems to be completely missing.

Recent example: https://coveralls.io/jobs/45247903

Logs don't show anything bad: 

```
Fetching coveralls-lcov-1.5.1.gem
Successfully installed coveralls-lcov-1.5.1
Parsing documentation for coveralls-lcov-1.5.1
Installing ri documentation for coveralls-lcov-1.5.1
Done installing documentation for coveralls-lcov after 0 seconds
1 gem installed
#<Net::HTTPOK 200 OK readbody=true>
{"message":"Job #387.2","url":"https://coveralls.io/jobs/45247903"}
```

We are building C++ code and uploading the generated coverage.info from lcov:

```
gem install coveralls-lcov
coveralls-lcov coverage.info
```

Any ideas?

**Comment by nickmerwin** [comment]
Hi @Flamefire there may have been a lag in processing that job; coverage data is there now.
