### ISSUE TITLE
Branch master commiter web-flow

### ISSUE THREAD

**Issue by rauny-brandao** [lemurheavy/coveralls-public#1265]
Hello there,

In one of our repositories, the branch master is being build by the user **web-flow**.

![screenshot_2019-02-18 coveralls io - test coverage history and statistics](https://user-images.githubusercontent.com/13734862/52951406-81426580-3360-11e9-9b71-3ac60940328f.png)

But we don't have any user with this name, where do I find this configuration?

Thank you!

**Comment by nickmerwin** [comment]
Hi @rauny-brandao could you email us the repo name please? support@coveralls.io

**Comment by nickmerwin** [comment]
To recap, @web-flow turned out to be a Github owned account::

> This account is the Git committer for all web commits (merge/revert/edit/etc...) made on GitHub.com.

https://github.com/web-flow

**Comment by rauny-brandao** [comment]
Thank you @nickmerwin!
