### ISSUE TITLE
Docs & Support link now broken

### ISSUE THREAD

**Issue by kortschak** [lemurheavy/coveralls-public#1266]
http://support.coveralls.io/ now lands at [this page](https://www.zendesk.com/help-center-closed/?utm_content=support.coveralls.io&utm_source=helpcenter-closed&utm_medium=poweredbyzendesk), "Oops, this help center no longer exists".

**Comment by anjin** [comment]
The new docs URL is http://docs.coveralls.io/ and for issues we are using GitHub as you already know. Where did you see a support.coveralls link still live?

**Comment by kortschak** [comment]
It's on https://blog.coveralls.io/.

**Comment by anjin** [comment]
Thanks!
