### ISSUE TITLE
node project coveralls travis-ci integration is broken

### ISSUE THREAD

**Issue by kanekotic** [lemurheavy/coveralls-public#1267]
Since today all my builds that integrate node coveralls in travis-ci are failing. More users have been reporting the same issue so seems to be a more general situation. Has there been any changes in the last hours on how to integrate with travis?

https://github.com/nickmerwin/node-coveralls/issues/166

**Comment by ericmorand** [comment]
Same here, with all my projects.

**Comment by kortschak** [comment]
Dup of #1264?

**Comment by kanekotic** [comment]
yes, duplicate....sorry
