### ISSUE TITLE
Unable to publish report to coveralls

### ISSUE THREAD

**Issue by maheshsubramanian** [lemurheavy/coveralls-public#1269]
We have been using coveralls for all repos (public) in our organisation (https://github.com/CJSCommonPlatform).  Since last evening, we are noticing issues with publishing report to coveralls.  These are existing repos which already have coveralls information published. 

Coveralls link for existing repo: https://coveralls.io/github/CJSCommonPlatform/framework-api

Sample failure on travis for above repo: `https://travis-ci.org/CJSCommonPlatform/framework-api`

Specific error message. 

`[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project framework-api: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]`

This is now happening across a few repos.  Can you please advise.

**Comment by nickmerwin** [comment]
Hi @maheshsubramanian, turned out we had our webserver IPs accidentally blacklisted by Travis, so we couldn't query their API to get job info as coverage data was posted.

Apologies for the gap in service here! We're adding failsafes to warn us early about this in the future.
