### ISSUE TITLE
Can't find repo I am admin of on coinbase account

### ISSUE THREAD

**Issue by ntucker** [lemurheavy/coveralls-public#1270]
Repo is open: https://github.com/coinbase/rest-hooks
I am admin of said repo.
I am publicly known to be a member of coinbase org: https://github.com/orgs/coinbase/people

I can see repos for other people's projects that they gave me only write access to, but not rest-hooks.

Note: they did not authorize the private data access; but that doesn't seem needed for public repos, right?

**Comment by nickmerwin** [comment]
Hi @ntucker, we only show repos on your Coveralls dashboard that we know you have write access for. I checked your account and it appears Coveralls can't see your Coinbase repos (only other ntucker repos), likely due to 3rd party access restrictions on the org.
