### ISSUE TITLE
SOURCE NOT AVAILABLE

### ISSUE THREAD

**Issue by tosyama** [lemurheavy/coveralls-public#1273]
Hi,
I can’t see my repo’s source by “SOURCE NOT AVAILABLE” from travisCI trouble before a week.
https://coveralls.io/builds/21532635/

I predicted github auth information mismatch because I did something to try to fix repo not found error.

So, I tried login and logout many times. But it not works. I also changed and back some related settings, but not improved neither.

I give up now.
Is there any ways to recover?

**Comment by nickmerwin** [comment]
Hi @tosyama, ok I've reassigned the repo to your correct user. Thanks!

**Comment by tosyama** [comment]
@nickmerwin, Now, I able to see my source code again! Thanks.
