### ISSUE TITLE
Coverage unknown

### ISSUE THREAD

**Issue by danielcondemarin** [lemurheavy/coveralls-public#1274]
I believe having set up correctly coveralls for my repo, but no matter what I try always says coverage unknown. The repo is https://github.com/danielcondemarin/serverless-nextjs-plugin

Can you advice please?  Thanks!

**Comment by ericmorand** [comment]
I have the same issue with this project:

https://coveralls.io/github/NightlyCommit/stromboli

I have been able to find the build by adding log to the npm coveralls package:

https://coveralls.io/builds/21893721

Everything looks fine in that build except it doesn't have a coverage value and it doesn't appears on the project page.

**Comment by nickmerwin** [comment]
Hi @danielcondemarin @ericmorand your builds are processed now, we had a brief queue backlog that they got stuck behind.

Thanks!
