### ISSUE TITLE
New branch not showing up in the UI?

### ISSUE THREAD

**Issue by NathanWailes** [lemurheavy/coveralls-public#1275]
I seem to be encountering the same issue described [here](https://github.com/lemurheavy/coveralls-public/issues/97) and [here](https://github.com/lemurheavy/coveralls-public/issues/788):

![Screenshot of what I'm seeing](https://i.imgur.com/1364ypK.png)

Here's the view from the TravisCI build:
![Screenshot of the TravisCI build](https://i.imgur.com/wrBft9v.png)

**Comment by nickmerwin** [comment]
Hi @NathanWailes could you link me to that repo please?

**Comment by NathanWailes** [comment]
@nickmerwin https://coveralls.io/github/Doohken/DKPlayer

Thanks for your help!

**Comment by nickmerwin** [comment]
Hey @NathanWailes, thank you for the link -- your other branches will populate once there's a non-PR build. That's to prevent branch name pollution from PR builds on forks.

Closing for now, let me know if it's still not populating after a non-PR build.

Thanks!

**Comment by NathanWailes** [comment]
@nickmerwin Thank you for your help!  Can you give some more explanation of what needs to be done?  A build on *any* branch should make it work?  I'm not seeing Coveralls update, despite builds on various branches.

How the repo works:
- There is a "master" branch which is very rarely updated at the moment.
- There is a "dev" branch which we submit all PRs to.
- There are numerous "DKPLAYER-###" branches (e.g. 123, 145, 190) where the numbers correspond to the number of an associated Jira ticket.  I push code from my computer to the origin DKPLAYER-### branch, and then create a PR from that branch (in the origin repo) into the "origin dev" branch.

I've had "origin DKPLAYER-###" branches build and also the "origin dev" branch build and Coveralls still does not look any different than it did before.

**Comment by nickmerwin** [comment]
@NathanWailes without seeing your Travis setup, it sounds like non-PR branch builds aren't being posted to Coveralls. You could check the build output logs of those to confirm.

**Comment by NathanWailes** [comment]
@nickmerwin 
Below is the Travis CI log for a commit I pushed directly to the `dev` branch without doing a PR.  The build succeeded, the `coveralls` command seemed to get run, and the `coveralls` command seems to have taken a while to complete.

![2019-03-04 23_49_13-build 40 - doohken_dkplayer - travis ci](https://user-images.githubusercontent.com/1755791/53789032-469c0980-3ed8-11e9-8bde-3e4bd47b07c8.png)


![2019-03-04 23_49_29-microsoft store](https://user-images.githubusercontent.com/1755791/53789033-4865cd00-3ed8-11e9-9c86-3545346c457a.png)

**Comment by nickmerwin** [comment]
@NathanWailes it looks like there's already a PR opened on the `dev` branch, so any builds that come in from it are considered to be PR builds.

One option would be to create a new branch and build on it before creating a PR.

**Comment by liamzhang40** [comment]
@nickmerwin Does it matter if a specific branch is a BASE or HEAD branch in a PR?
