### ISSUE TITLE
Empty page on the repo

### ISSUE THREAD

**Issue by briwa** [lemurheavy/coveralls-public#1276]
Hello, not sure if my setup is wrong but for some reason the coverage page is showing an empty page:
https://coveralls.io/github/briwa/js-jest-pkg-starter

The build is fine and the coverage is reporting properly on Travis:
https://travis-ci.org/briwa/js-jest-pkg-starter

I did syncing and deleting the repo from Coveralls and adding it back, re-run the build in Travis. However the results are the same. Not sure why, maybe I've missed an obvious step? Any help would be appreciated. Thanks.

**Comment by nickmerwin** [comment]
Hi @briwa your builds have processed now, apologies for the delay!

**Comment by briwa** [comment]
@nickmerwin Thanks for the fix! Appreciate it.
