### ISSUE TITLE
Coverage report contains no data, despite line coverage listings being complete

### ISSUE THREAD

**Issue by danieljabailey** [lemurheavy/coveralls-public#1277]
I have a build that has completed and the file view shows which lines are covered but the report contains no data.
Same as issue #579 

https://coveralls.io/jobs/45897103/source_files/12228095

![image](https://user-images.githubusercontent.com/4355293/53919206-39f6ed00-4061-11e9-82ec-524fac09f55f.png)

**Comment by nickmerwin** [comment]
Hi @danieljabailey sorry about that, we had a queue backlog. Your build is processed now.
