### ISSUE TITLE
Page showing no coverage data

### ISSUE THREAD

**Issue by DivineOmega** [lemurheavy/coveralls-public#1278]
The coverage page for one of my repositories was not updating at all. After disabling and re-enabling the repo on Coveralls, the page for the project is not showing any coverage data (percentages, graphs, etc.).

The problematic page is as follows.

https://coveralls.io/github/DivineOmega/laravel-extendable-basket

The builds on Travis are correctly submitted coverage data, as shown below.

https://travis-ci.com/DivineOmega/laravel-extendable-basket/jobs/182801544

**Comment by nickmerwin** [comment]
Hi @DivineOmega, sorry about that, we had a queue backlog earlier today. Your build is processed now.
