### ISSUE TITLE
Removing repository does not clean coverage data

### ISSUE THREAD

**Issue by jonatasbaldin** [lemurheavy/coveralls-public#1279]
Hey there, how are you doing?

I accidentally committed a coverage file with the data from my whole `venv`, which put the stats to 44%. 

I removed the repo from Coveralls, created it again and send the correct coverage data, but the old data from the `venv` is still there.

This is a private repo running Python and Pytest.

How can I clean that old data?

Thanks!

**Comment by nickmerwin** [comment]
Hi @jonatasbaldin, as owner of the repo you can delete individual builds from their details pages.

If there's still an issue, please email us with the name of the repo here: support@coveralls.io

Thanks!
