### ISSUE TITLE
Coverage decreased then restored after changes to README

### ISSUE THREAD

**Issue by calumcraig** [lemurheavy/coveralls-public#1281]
We recently experienced a large drop in reported coverage after a [PR](https://coveralls.io/builds/21881299) which only made a very minor change to the README. Upon a subsequent [PR](https://coveralls.io/builds/22026135) which again made change only to the README the coverage returned to the previous level:
![image](https://user-images.githubusercontent.com/44327924/54211903-faedef00-44d9-11e9-8ee3-935247bf8ec4.png)
Coveralls is reporting coverage changes in 24 files but these have not been touched in either PRs. Any suggestions as to what went on here? Since then there have been further [PRs](https://coveralls.io/repos/157972/builds) which have not caused any similar issues.

**Comment by nickmerwin** [comment]
Hi @calumcraig the drop in coverage on Coveralls is consistent with the displayed coverage summary from your Travis logs:

https://travis-ci.com/maidsafe/safe_app_nodejs/jobs/180949463

```
=============================== Coverage summary ===============================
Statements   : 80.49% ( 1485/1845 )
Branches     : 66.79% ( 376/563 )
Functions    : 80.7% ( 368/456 )
Lines        : 81.06% ( 1459/1800 )
================================================================================
```

https://travis-ci.com/maidsafe/safe_app_nodejs/jobs/182833010

```
=============================== Coverage summary ===============================
Statements   : 98.05% ( 1809/1845 )
Branches     : 91.3% ( 514/563 )
Functions    : 99.12% ( 452/456 )
Lines        : 98.11% ( 1766/1800 )
================================================================================
```

This implies the issue occurred during that build, as opposed to a calculation error on Coveralls.

You can delete the specific build from the Coveralls UI if you'd like.

Thanks.

**Comment by calumcraig** [comment]
OK, thanks for the confirmation @nickmerwin.
