### ISSUE TITLE
Reported code coverage is incorrect

### ISSUE THREAD

**Issue by bsarrazin** [lemurheavy/coveralls-public#1282]
![image](https://user-images.githubusercontent.com/1077441/54222453-d559e900-44cb-11e9-9fec-8bb8bf6a97a1.png)

Yet the local version has the proper values:
![image](https://user-images.githubusercontent.com/1077441/54222494-e86cb900-44cb-11e9-994c-17b71451ae18.png)

Sample repo can be found here:
https://github.com/bsarrazin/Coveralls-iOS

**Comment by nickmerwin** [comment]
Hi @bsarrazin it looks like the data you're posting to Coveralls is incomplete; there's no line-by-line coverage hits, nor branch/commit info.

Questions:
1) What Coveralls integration library are you using?
2) Are you building on a CI or locally?
