### ISSUE TITLE
How to integrate open source project with coveralls?

### ISSUE THREAD

**Issue by simonhf** [lemurheavy/coveralls-public#1283]
Hello! I'm building a CI coverage version of an open source project here [1] using the command "make release coverage" and outputs the following lines "make: coverage: Lines executed:96.63% of 800". How to integrate this open source project with coveralls?

[1] https://travis-ci.org/simonhf/sharedhashfile

**Comment by nickmerwin** [comment]
Hi @simonhf I see that your latest build on Travis posted successfully to Coveralls:

https://coveralls.io/jobs/46186300

https://coveralls.io/github/simonhf/sharedhashfile

Closing the issue for now, let me know if you have any additional questions.

Thanks!
