### ISSUE TITLE
Source not available - private org repo

### ISSUE THREAD

**Issue by kbakk** [lemurheavy/coveralls-public#1284]
Hi,

We've set up Coveralls and have coverage report sent over, but there seems to be issues with connecting to our GitHub repo (private, belongs to org).

E.g. [this page](https://coveralls.io/builds/22178615/source?filename=maestro/maestro.py) shows this error:

> SOURCE NOT AVAILABLE
> The file "maestro/maestro.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

The path to the file exists in our repo

Hope you can help figuring out what causes this issue.

**Comment by nickmerwin** [comment]
Hi @kbakk since this is a private repo, we'll continue the discussion over email.

Thanks!
