### ISSUE TITLE
Hi @AndreasAZiegler I see a build on your repo here:

### ISSUE THREAD

**Issue by AndreasAZiegler** [lemurheavy/coveralls-public#1286]
Hi @AndreasAZiegler I see a build on your repo here:

https://coveralls.io/github/AndreasAZiegler/poly-exploration

Closing for now, but please let me know if there's still an issue. Thanks!

_Originally posted by @nickmerwin in https://github.com/lemurheavy/coveralls-public/issues/1285#issuecomment-473424138_

**Comment by AndreasAZiegler** [comment]
The build you mentioned is the first and only build that was recognized by coveralls. As you can see in the screenshot below, there were quite a few builds happening on circleci after this first build which coveralls did not get.

<img width="1675" alt="Screenshot 2019-03-16 at 06 56 33" src="https://user-images.githubusercontent.com/6949508/54471451-78a34a80-47b9-11e9-9640-bd4553cc25ad.png">

**Comment by nickmerwin** [comment]
@AndreasAZiegler can you please try switching to https://github.com/nickmerwin/node-coveralls as the integration library?

cpp-coveralls doesn't support CircleCI at this time, only Travis for open-source.

Thanks!
