### ISSUE TITLE
Independance day?

### ISSUE THREAD

**Issue by dlech** [lemurheavy/coveralls-public#1287]
Maybe this is a case of "its not a bug, its a feature"... but I find it a bit odd that the president's speech from the movie _Independence Day_ is on the [Support for Private Repos](https://docs.coveralls.io/support-for-private-repos) page.

![Selection_017](https://user-images.githubusercontent.com/963645/54481701-318f7680-4806-11e9-9421-1bb87687a608.png)

**Comment by jrfnl** [comment]
Looks like this is gone. Should this issue be closed ?

**Comment by dlech** [comment]
Haha, I forgot about this!
