### ISSUE TITLE
Coveralls is not working with public travis CI

### ISSUE THREAD

**Issue by dotronglong** [lemurheavy/coveralls-public#1288]
I have set up travis-ci.org correctly and passed test, however it does not show on coveralls
Travis CI: https://travis-ci.org/dotronglong/dart-api-client
Coveralls: https://coveralls.io/github/dotronglong/dart-api-client?branch=master

Do you know what was wrong here?

**Comment by nickmerwin** [comment]
Hi @dotronglong it's not clear from your Travis logs that a test suite is actually running during the build:
https://api.travis-ci.org/v3/job/507653287/log.txt

I also don't see anything regarding coveralls integration here:
https://github.com/dotronglong/dart-api-client/blob/master/.travis.yml

You'll need to use the Coveralls dart package here:
https://pub.dartlang.org/packages/coveralls

**Comment by dotronglong** [comment]
From what I am seeing in the documentation of coveralls at https://coveralls.io/github/dotronglong/dart-api-client?branch=master I don't need to insert any thing to project if I am using travis ci public. Hence, I don't understand, what's wrong here, I eventually put coveralls as devDependecies and run tests again but not working @nickmerwin

**Comment by dotronglong** [comment]
I added both COVERALLS_REPO_TOKEN and COVERALLS_TOKEN as runtime environment in Travis CI, but still not working.

**Comment by nickmerwin** [comment]
@dotronglong you'll need to add the command to run coveralls after your Travis build completes:

https://dev.belin.io/coveralls.dart/usage/cli/

**Comment by dotronglong** [comment]
Thank you @nickmerwin , however, I am referring to this project https://github.com/dart-lang/shelf and I don't see any configuration regarding coveralls but they still have coveralls, I guess it should be something else meanwhile from the document I see that TravisCI does not need extra information to have coverage.

**Comment by nickmerwin** [comment]
@dotronglong ok that repo looks to be currently misconfigured, as the latest builds are showing 0 files (https://coveralls.io/github/dart-lang/shelf). The most recent correct build is:

https://coveralls.io/builds/5294462

In which this script is used to call coveralls:

https://github.com/dart-lang/shelf/blob/55067ed3fe2547334190dec621fce88e6ff3707f/tool/travis.sh

```bash
# Install dart_coveralls; gather and send coverage data.
if [ "$COVERALLS_TOKEN" ] && [ "$TRAVIS_DART_VERSION" = "stable" ]; then
  pub global activate dart_coveralls

  pub global run dart_coveralls report \
    --exclude-test-files \
    test/test_all.dart
fi
```

You can see the output from the associated build log here:

https://api.travis-ci.org/v3/job/113498930/log.txt

```
Coveralls Job #69.1 â€“Â https://coveralls.io/jobs/12498265
```
