### ISSUE TITLE
Cannot create a public access token

### ISSUE THREAD

**Issue by nickmeldrum** [lemurheavy/coveralls-public#1290]
On the page: https://coveralls.io/account

I click the button: `'Create new token'`

It just directs me to page: https://coveralls.io/account/personal_access_tokens

with the text: 

> 
> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.
> 
> Also, you might want to check out the Coveralls Status page to see if there is a system outage: http://status.coveralls.io
> 

I am on the free account as I am using coveralls for open source projects hosted on github.

I can see nothing in the documentation saying that I would need a different level account?

Looking on the https://status.coveralls.io/ status page apparently "ALL SYSTEMS OPERATIONAL"

**Comment by nickmerwin** [comment]
@nickmeldrum do you have javascript enabled in your browser?

Could you check your javascript console for errors?

Thanks.
