### ISSUE TITLE
The commit  wasn't found on the repo

### ISSUE THREAD

**Issue by gow** [lemurheavy/coveralls-public#1291]
I recently setup coveralls in our CircleCI builds.  I followed the instructions provided here - https://github.com/mattn/goveralls. But I'm running into this issue (debug info below). 
The mentioned git commit does exist on the master branch. Is this a permission issue? Am I missing something?
```
  .
  .
  .
  ],
  "parallel": true,
  "git": {
    "head": {
      "id": "**************************480faba",
      "author_name": "<author_name>",
      "author_email": "<author>@bolt.com",
      "committer_name": "GitHub",
      "committer_email": "noreply@github.com",
      "message": "<commit message>"
    },
    "branch": "master"
  },
  "run_at": "2019-04-12T05:41:53.12111486Z"
}
Bad response status from coveralls: 422
{"message":"Travis API Error: #\u003cCoveralls::Mash message=\"The job(22466) couldn't be found\"\u003e. The commit  wasn't found on the repo BoltApp/hail","error":true}
```

**Comment by msolimans** [comment]
@gow were you able to fix this issue, any one knows how to fix this?

**Comment by gow** [comment]
No. We just stopped using the service.

**Comment by msolimans** [comment]
@nickmerwin would you please help, any suggestions?

**Comment by msolimans** [comment]
I was able to fix this by changing the service to `circle-ci`
