### ISSUE TITLE
Coverage from CircleCI builds doesn't appear in Coveralls

### ISSUE THREAD

**Issue by dawlib** [lemurheavy/coveralls-public#1295]
I'm struggling with making Coveralls working properly with CircleCI parallel builds that run RSpec and Cucumber tests.

I created the repo in Coveralls, set up the app configs, created on GitHub a PR with a custom branch into the master branch and received the first commit that was triggered, but that's it. Coveralls receives builds information, at least the number of builds is incrementing in the main section on the repo page but builds are not showing up in the "RECENT BUILDS" section at the bottom of the page. No new commits there as well. "RELEVANT LINES COVERED" section is blank. There is only the first triggered build showing up and its details (including coverage value in the "LAST BUILD ON BRANCH MASTER"/"RUN DETAILS" section). However, builds details are showing up on the "LATEST UPDATES FOR ..." page (https://coveralls.io/stories) but without any data and coverage information.

<img width="1282" alt="screenshot" src="https://user-images.githubusercontent.com/6200561/56205817-215bf880-604b-11e9-8530-83a87be8cd5d.png">

Things I did in order to make this working:
1. Installed `coveralls_reborn` gem in version 0.12.0 (also tried `coveralls` gem in version 0.8.22)
2. Set up env variables on CircleCI:
```
CI=true
SIMPLECOV=1
COVERALLS_PARALLEL=true
COVERALLS_REPO_TOKEN=<repo_token>
```
3. Added at the top of the `spec_helper.rb` file:
```
if ENV['CI']
  require 'coveralls'
  Coveralls.wear_merged!('rails')
end

ENV['RAILS_ENV'] = 'test'

if ENV['SIMPLECOV'] == '1'
  require 'simplecov'
  SimpleCov.formatter = Coveralls::SimpleCov::Formatter
  SimpleCov.start do
    add_filter ...
    add_group ...
  end
end
```
4. Updated `.circleci/config.yml`, so it has information about the webhook URL and there is `CIRCLE_WORKFLOW_ID` env variable passed as `CIRCLE_BUILD_NUM`:
```
jobs:
...
  build:
    parallelism: 2
...
    steps:
...
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: CIRCLE_BUILD_NUM=$CIRCLE_WORKFLOW_ID bundle exec rspec --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run: CIRCLE_BUILD_NUM=$CIRCLE_WORKFLOW_ID bundle exec cucumber $(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
...
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
...
```

Moreover, I tried many different solutions without any success. For instance, adding:
`- run: bundle exec rake coveralls:push`
or
`- run: curl -k $COVERALLS_ENDPOINT/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$BUILD_NUMBER&payload[status]=done"`
commands after tests run and running tests with/without `CIRCLE_BUILD_NUM=$CIRCLE_WORKFLOW_ID` variable assignment but without any different result. What am I missing and how can I fix it?

**Comment by adlugopolski** [comment]
@dawlib Did you manage to solve this issue? I am able to get the parallel builds reported but there is no final notification. When I copy the ID reported in the test output and manually complete the build the coverage seems to be reported somewhat correctly.
