### ISSUE TITLE
Coveralls main page and badge for my project are "stuck"

### ISSUE THREAD

**Issue by michaelsbradleyjr** [lemurheavy/coveralls-public#1298]
See: https://coveralls.io/github/embark-framework/embark

It reports the "last build" as happening on 1 April 2019, and the coverage badge is stuck at the percentage for that build too.

If you scroll down to the "recent builds" section, it's clear that the system has continued to process builds since April 1.

**Comment by nickmerwin** [comment]
hi @michaelsbradleyjr it appears the coverage data from your CI is no longer including a branch name. 

Here's the last build from `master`:
https://coveralls.io/builds/22528100

Did your configuration change after that?

**Comment by michaelsbradleyjr** [comment]
As of April 1 we finished moving from Travis and AppVeyor to Azure Pipelines, but didn't otherwise change our coverage configuration. I will do a search re: AzP and coveralls but if you know a quick fix, that would be great!

**Comment by nickmerwin** [comment]
Ok simplest update would probably be to set `COVERALLS_GIT_BRANCH=$(Build.SourceBranchName)`  and `COVERALLS_SERVICE_NAME=azure`.

Also, here's an example of another possible solution:

https://github.com/gulpjs/gulp/blob/master/.ci/.azure-pipelines-steps.yml#L17

Closing for now, let me know if you run into any roadblocks. Thanks!

**Comment by michaelsbradleyjr** [comment]
In case someone else has the same problem and comes across this issue later:

Based on @nickmerwin's suggestion, I got it working: https://github.com/embark-framework/embark/pull/1556/commits/86e50ff24f4f298f520f772fdda032a01ac4d189

A slightly tricky thing is that my team tends to use branch names that are prefixed with things like `fix/` and `refactor/`. Per the docs for [Build.SourceBranchName](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml), it gives only the last path segment so I had to find another way to calculate the branch name from the "detached HEAD" state on Azure Pipelines.

**Comment by michaelsbradleyjr** [comment]
@nickmerwin is there a way, with environment variables or cli options, that I can get the type to switch to pull as seen with https://coveralls.io/github/zeit/next.js ?

**Comment by nickmerwin** [comment]
@michaelsbradleyjr `CI_PULL_REQUEST` should be all that's needed to differentiate a PR. Could you link me to an attempt that didn't work?

**Comment by michaelsbradleyjr** [comment]
I didn't try `CI_PULL_REQUEST` but will do so.

**Comment by michaelsbradleyjr** [comment]
It works, thanks so much @nickmerwin!
