### ISSUE TITLE
BUILD SHA NOT FOUND - CircleCI coverage details doesn't appear in coveralls

### ISSUE THREAD

**Issue by ajfisher** [lemurheavy/coveralls-public#1299]
I have coverage data being created as part of my build process and until now I've been simply uploading all of the coverage data as artefacts in circleci. This is on a private repo.

I've created a job which *should* be sending the data across to coveralls. My token has been configured as an environment variable.

the command I'm using is `cat coverage/lcov.info | ./node_modules/.bin/coveralls`

This command runs successfully however the detailed coverage information doesn't appear to be in coveralls. Specifically, I get this when I go down to an individual file:

<img width="1111" alt="Screen Shot 2019-05-01 at 20 42 34" src="https://user-images.githubusercontent.com/119203/57014093-d13b8380-6c51-11e9-846d-503c5c8cc5e2.png">

Which suggests some kind of misconfiguration between circleci and coveralls? Outside of the one command above and the env var, I have made no other config on circleci.

Any guidance would be greatly appreciated.

**Comment by nickmerwin** [comment]
Hi @ajfisher since this is on a private repo, can you please send us the details here: support@coveralls.io

Thanks.
