### ISSUE TITLE
Coveralls not showing coverage for new builds.

### ISSUE THREAD

**Issue by Clayton7510** [lemurheavy/coveralls-public#1300]
Coveralls hasn't registered any new builds today. The first one i did today was about 6.5 hours ago. I have since triggered about 4 additional builds today off of the same branch trying to get the coverage info to show up in Coveralls. It shows that Coveralls API was contacted in TravisCI logs and successfully published. But no updates in Coveralls and of course GitHub is not receiving any updated coverage info. The last update reflected in Coveralls was from yesterday. Looks like something might be going on Coveralls' end.

**Comment by nickmerwin** [comment]
@Clayton7510 sorry about that, we had a queue backup from an underlying infrastructure performance degradation. 

Your build should be processed now, please open another issue if not.

Thanks!

**Comment by Clayton7510** [comment]
Yep, I see it in there. Thanks. Next time I'll wait until the following morning before I raise an issue ;)
