### ISSUE TITLE
"No data" in builds on a new repo

### ISSUE THREAD

**Issue by devinivy** [lemurheavy/coveralls-public#1301]
I recently created a new repository, and I've been able to see new builds from TravisCI, but those builds have no coverage data.  Here's an example: https://coveralls.io/builds/23189127

I send coverage to Coveralls using the following command: `lab -r lcov test/index.js | coveralls`, which is a command I've been using on projects for a long time.  TravisCI indicates no failures.  I'm using the node coveralls client v3.  Here's a relevant Travis build: https://travis-ci.org/devinivy/lalalambda/jobs/527597761#L521.

So far the only things I've tried are 1. waiting 24 hours for coverage data to appear and 2. removing the repo from Coveralls, re-adding it, then restarting the latest Travis build.

I would very much appreciate any ideas!  Thanks for the great tool.

**Comment by nickmerwin** [comment]
@devinivy could you add the `verbose` flag to coveralls and run your build again please?

**Comment by devinivy** [comment]
Sure thing!  The output can be seen here: https://travis-ci.org/devinivy/lalalambda/jobs/528211394#L521

**Comment by nickmerwin** [comment]
@devinivy ok from the logs `{"source_files":[]` implies that the lcov file did not contain any individual file info. Could you check your configuration to ensure they’re being picked up?

**Comment by nickmerwin** [comment]
Closing for now, let me know if you’re still not able to get it working.

Thanks!

**Comment by devinivy** [comment]
Turns out the serverless framework was using `chdir()` to change the current working directory, which threw-off the filenames reported in lcov output.  Thanks for the help!
