### ISSUE TITLE
vendor directory is not reported

### ISSUE THREAD

**Issue by klahnakoski** [lemurheavy/coveralls-public#1302]
I can not get the `vendor` directory to report coverage for my project https://coveralls.io/github/mozilla/ActiveData

Here is the current config

```
[run]
source =
    ./active_data
    ./vendor

[report]
include = *
```

it woks fine locally

```
C:\Users\kyle\code\ActiveData>coverage report
Name                                                Stmts   Miss  Cover
-----------------------------------------------------------------------
active_data\__init__                                   19     10    47%
active_data\actions\__init__                          101     75    26%
active_data\actions\contribute                         14      5    64%
active_data\actions\json                               48     30    38%
active_data\actions\query                              63     43    32%
active_data\actions\save_query                         80     47    41%
active_data\actions\sql                               103     81    21%
active_data\actions\static                             40     25    38%
active_data\app                                       131     39    70%
vendor\jx_base\__init__                                41      3    93%
vendor\jx_base\container                               76     51    33%
vendor\jx_base\dimensions                             161    143    11%
<snip>
```

this next config shows the `tests` directory just fine, but still not the `vendor` directory

```
[run]
source =
    ./active_data
    ./tests
    ./vendor
```

A few other permutations did not work either:
https://github.com/mozilla/ActiveData/commit/6d001486a711136e385e84f0492fc101ee67051f
https://github.com/mozilla/ActiveData/commit/b1ac7e81bc2c2de7e8d7d54c8175a0665682caab
https://github.com/mozilla/ActiveData/commit/552e3cb74042e308f44e0dfcfce0907357682825
https://github.com/mozilla/ActiveData/commit/cb634569b8509789fc2d7ddd411b2a4eefd7ca51
https://github.com/mozilla/ActiveData/commit/a088b5aee2e4c0b6d68058d48d8f38de82e703bc
https://github.com/mozilla/ActiveData/commit/e406ef9783f320122e385469e5f6b811fde04cf5
https://github.com/mozilla/ActiveData/commit/7ab3a73da9767c07512db48943fac4fcecbfee9f

**Comment by nickmerwin** [comment]
Hi @klahnakoski, sorry for the confusion -- we're going to add a setting at the Repo level that will allow `/vendor` files to be included on Coveralls' side. I'll let you know when that's live, later today most likely.

**Comment by nickmerwin** [comment]
@klahnakoski ok that's live now, you can toggle it from your repo's settings page:

![image](https://user-images.githubusercontent.com/1129/57237322-ced38380-6fdb-11e9-8ca3-6ae03a9a154c.png)

Please let me know when you have a chance to re-run the build and confirm it's working as expected. Thank you!

**Comment by klahnakoski** [comment]
Thank you !  That was fast!

But, there seems to be a problem with UI showing in tree form:

![image](https://user-images.githubusercontent.com/2334429/57242710-3dc3d300-7002-11e9-86aa-5ec2b5213f36.png)

**Comment by nickmerwin** [comment]
Hi @klahnakoski it's looking correct now:

![image](https://user-images.githubusercontent.com/1129/57245739-6c38b280-6ff0-11e9-9eae-7eeb342f942d.png)

Can you confirm?

**Comment by klahnakoski** [comment]
@nickmerwin  confirmed
