### ISSUE TITLE
Public Repos in Private Organizations are no longer working

### ISSUE THREAD

**Issue by BrendanChou** [lemurheavy/coveralls-public#1304]
The page deals a "Halt!" message and the repos do not show up in the "Repos" page even though they show up as "active" in the "Add Repo" page

**Comment by arshdeeptinna** [comment]
I am having same issue. @BrendanChou did you find a fix?

**Comment by BrendanChou** [comment]
Had to delete and re-add the repo which wiped the history but I couldn't wait
