### ISSUE TITLE
How do I get the repo token for my repo via API?

### ISSUE THREAD

**Issue by deepakkt** [lemurheavy/coveralls-public#1312]
The API to submit coverage to coverall needs a repo token.

How can I get the token for my rep via API?
The API documentation makes no reference to this.

**Comment by afinetooth** [comment]
@deepakkt you can get your repo token in the Coveralls admin, from both the main repo page and the Settings page for your repo.

Main page:
![Screen Shot 2020-04-09 at 2 08 21 PM](https://user-images.githubusercontent.com/918667/78941044-bed5e680-7a6b-11ea-92b5-09e4967648b1.png)

Settings page:
![Screen Shot 2020-04-09 at 2 08 40 PM](https://user-images.githubusercontent.com/918667/78941055-c5fcf480-7a6b-11ea-9767-1e3d3dd7c3d9.png)

Hope that helps.
