### ISSUE TITLE
500 error on viewing code hosted on Bitbucket

### ISSUE THREAD

**Issue by Krolken** [lemurheavy/coveralls-public#1316]
I am having problem viewing code that is hosted on BitBucket. (python code) 

I am using CircleCI to push the coverage report and get ok from coveralls. Everything seems fine in web UI until I want to view code. Then I get 500 error. On all files.

Ran a build on another project where the code is hosted on Github and there was not problem.

**Comment by Krolken** [comment]
Update:
Not able to log in via Bitbucket either after logging out to check github projects.

**Comment by lsanders** [comment]
#1315 is duplicate

**Comment by tym-network** [comment]
Same problem here, unable to login using Bitbucket account (500 error) and unable to run Coveralls from Bitbucket Pipeline 
`Bad response: 500 {"message":"Build processing error.","error":true,"url":""}`

**Comment by rsaftoiu** [comment]
Same here.

**Comment by Krolken** [comment]
Update. Can log in via Bitbucket. When i try to view my files I don't get a 500, instead message in the view:

SOURCE NOT AVAILABLE
Sorry, the **Github API** returned an internal server error, please try refreshing this page in a moment.

**Comment by nickmerwin** [comment]
Hi all this is resolved now, BitBucket recently deprecated an API endpoint we relied on.

Apologies for the fire drill!

**Comment by seanmkauffman** [comment]
Sorry to bump this but I'm now seeing a very similar problem.  Bitbucket just updated their site, did they deprecate an API again?

**Comment by afinetooth** [comment]
Hi, @seanmkauffman. Thanks for reporting this. I do see that the client we use to access the Bitbucket API is throwing a new error. I'm not sure whether it's an additional deprecation for the API, or an issue with one of the client's dependencies. In any case, we modified the request to conform to the 2.0 API docs and just pushed a fix. Please let me know if it's not working for you tomorrow.

**Comment by seanmkauffman** [comment]
Hi @afinetooth I get a new error now:

Source Not Available
Sorry, the Github API returned an internal server error, please try refreshing this page in a moment.

I don't know if it's just misreporting which API it's using (github, not bitbucket) or if it is actually trying the wrong API, but it seems to still not be working.

**Comment by afinetooth** [comment]
Thanks @seanmkauffman. I'll find out.

**Comment by afinetooth** [comment]
Hi, @seanmkauffman. So, that error message _is_ misreporting the API. It's a legacy hard-coded message that should be changed (I've submitted a PR).

In the meantime, I've tested the series of requests to get the source file, from the command line, and get back this error from our Bitbucket client when I request the raw contents of an example file, `/src/analysis.c`&mdash;*same as what's returned under-the-hood when requesting this URL*:
https://coveralls.io/builds/47719071/source?filename=src%2Fanalysis.c

```
MultiJson::ParseError (767: unexpected token at '#include <stdlib.h>)
#include <stdio.h>

#include "types.h"
#include "dict.h"
#include "nfer.h"
#include "log.h"
#include "analysis.h"
#include "memory.h"


void log_event_groups(nfer_specification *spec, dictionary *name_dict) {

[...]

        for (j = 1; j <= new_group_num; j++) {
            if (group_counts[j - 1] > 1) {
                log_msg("Group %d:", j);
                first = true;

                for (i = 0; i < num_labels; i++) {
                    if (group_assignments[i] == j) {
                        if (!first) {
                            log_msg(",");
                        }
                        log_msg(" %s", get_word(name_dict, i));
                        first = false;
                    }
                }
                log_msg("\n");
            }
        }
        free(group_assignments);
        free(group_counts);
    }
}
'
```

The nature of the fix we made was to stop requesting the `raw` version of the source file in params passed in the request URL.

According to the [Bitbucket 2.0 API docs, here](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-commit-path-get):

> __Raw file contents__
> When `path` points to a file, this endpoint returns the raw contents. [...]

The rest of that doc indicates that the raw contents of the file will always be returned without the need to explicitly request `raw` in either of two previously used methods:

1. URL params
2. Adding `/raw/` to the URL

We used to request the file like this. This is the request that started returning the `500` error from the Bitbucket API:

```
# Ruby

> user.bitbucket_client.get_request("/2.0/repositories/#{build.repo.name}/src/#{build.commit_sha}/src/analysis.c", {}, raw:true)
```

When I request the file by removing the URL param, `raw:true`, I get back a text representation of the source file, but one that seems to include metadata&mdash;*info that in JSON format would probably be attached to different keys*. It looks like this:

```
# Ruby

> user.bitbucket_client.get_request("/2.0/repositories/#{build.repo.name}/src/#{build.commit_sha}/src/analysis.c", {})

=> "/*\n * analysis.c\n *\n *  Created on: Jun 2, 2017\n *      Author: skauffma\n *\n *    nfer - a system for inferring abstractions of event streams\n *   Copyright (C) 2017  Sean Kauffman\n *\n *   This file is part of nfer.\n *   nfer is free software: you can redistribute it and/or modify\n *   it under the terms of the GNU General Public License as published by\n *   the Free Software Foundation, either version 3 of the License, or\n *   (at your option) any later version.\n *\n *   This program is distributed in the hope that it will be useful,\n *   but WITHOUT ANY WARRANTY; without even the implied warranty of\n *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n *   GNU General Public License for more details.\n *\n *   You should have received a copy of the GNU General Public License\n *   along with this program.  If not, see <https://www.gnu.org/licenses/>.\n */\n\n#include <stdlib.h>\n#include <stdio.h>\n\n#include \"types.h\"\n#include \"dict.h\"\n#include \"nfer.h\"\n#include \"log.h\"\n#include \"analysis.h\"\n#include \"memory.h\"\n\n\nvoid log_event_groups(nfer_specification *spec, dictionary *name_dict) {\n    int i, j, new_group_num, *group_assignments, *group_counts, num_labels;\n    rule_id id;\n    nfer_rule *rule;\n    bool first;\n\n    if (spec->size > 0) {\n        filter_log_msg(LOG_LEVEL_DEBUG, \"Number of rules %d\\n\", spec->size);\n\n        // find the number of subscribed names\n        num_labels = name_dict->size;\n\n        // find event groups\n        group_assignments = malloc(sizeof(int) * num_labels);\n        clear_memory(group_assignments, sizeof(int) * num_labels);\n        // can't have more groups than num_labels\n        group_counts = malloc(sizeof(int) * num_labels);\n        clear_memory(group_counts, sizeof(int) * num_labels);\n        new_group_num = 0;\n\n        // iterate over the rules\n        for (id = 0; id < spec->size; id++) {\n            // get the rule\n            rule = &spec->rules[id];\n\n            // if neither left or right side has been assigned a group\n            // then pick a new group number and assign it to both\n            if (group_assignments[rule->left_label] == 0 && group_assignments[rule->right_label] == 0) {\n                new_group_num++;\n                group_assignments[rule->left_label]  = new_group_num;\n                group_assignments[rule->right_label] = new_group_num;\n                group_counts[new_group_num - 1] = 1;\n            } else {\n                // otherwise, at least one of them is assigned a group alread so copy that\n\n                // mark right side\n                if (group_assignments[rule->right_label] == 0) {\n                    group_assignments[rule->right_label] = group_assignments[rule->left_label];\n                    group_counts[group_assignments[rule->left_label] - 1]++;\n                }\n\n                // mark left side\n                if (group_assignments[rule->left_label] == 0) {\n                    group_assignments[rule->left_label] = group_assignments[rule->right_label];\n                    group_counts[group_assignments[rule->right_label] - 1]++;\n                }\n            }\n        }\n\n        for (j = 1; j <= new_group_num; j++) {\n            if (group_counts[j - 1] > 1) {\n                log_msg(\"Group %d:\", j);\n                first = true;\n\n                for (i = 0; i < num_labels; i++) {\n                    if (group_assignments[i] == j) {\n                        if (!first) {\n                            log_msg(\",\");\n                        }\n                        log_msg(\" %s\", get_word(name_dict, i));\n                        first = false;\n                    }\n                }\n                log_msg(\"\\n\");\n            }\n        }\n        free(group_assignments);\n        free(group_counts);\n    }\n}\n"
irb(main):054:0> 
```

We will need to dig deeper on how to request source files from the Bitbucket API and get _**only the source**_, in the manner that used to be returned with `raw:true`. 

Right now I'm having difficulty finding anything that works. The methods in the apparently up-to-date 2.0 docs don't seem to work, but, neither do some StackOverflow solutions from the past 2 years (which add `/raw/` to the URL).

Currently, I'm hoping the metadata version of the file described [here in the docs](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-commit-path-get) has a `source` key, but I don't see it mentioned in the docs, so it may take some testing / trial and error.

If you have any leads on up-to-date resources about how to obtain the same version of the file that used to be returned with `raw:true` that would help.

**Comment by afinetooth** [comment]
@seanmkauffman, quick update:

I've run out of time on this for today. I will have to start again tomorrow. 

In the meantime, I've been able to get a consistent response back from the Bitbucket API, which matches the first response I got above. We'll just need to find a way to modify our request to handle a non-JSON response from the API. I think it's atypical to return raw contents from an API without specifically asking for it. I could be wrong, but it is certainly the default expectation of our client library that it will be getting a response in JSON.

**Comment by seanmkauffman** [comment]
@afinetooth thanks for all the updates!  Unfortunately, I am not familiar with the BitBucket APIs, but it sounds like you have that part under control.  Certainly, if the client lib is expecting JSON in the response it's going to have a hard time.

**Comment by afinetooth** [comment]
@seanmkauffman, just wanted to TB and let you know that I've submitted a fix request, but don't foresee it being addressed until at least Mon (Apr 11). I'll follow up on it around then and will share updates here. Appreciate your patience.

**Comment by seanmkauffman** [comment]
Hey @afinetooth, any update on this?

**Comment by afinetooth** [comment]
@seanmkauffman still WIP, apologies. I'll do my best to raise the priority on it.

**Comment by afinetooth** [comment]
@seanmkauffman this issue should be fixed. 

Specifically, the ability to view source files from Bitbucket should be restored. (We are working on some other Bitbucket-related issues.)

Let me know if it's _not_ fixed your you.

Thanks.

**Comment by seanmkauffman** [comment]
It's fixed!  Thanks!
