### ISSUE TITLE
How do I use API to post results locally?

### ISSUE THREAD

**Issue by zjb421** [lemurheavy/coveralls-public#1328]
How to authenticate with token. I am trying to use token xxx format but its showing

> {"message":"Couldn't find a repository matching this job.","error":true}

my request

> curl -H "Authorization: token MYTOKEN"   -F "json_file=@.resultset.json" -F "service_name=coveralls-ruby" -F "source_files=[@.resultset.json]"   https://coveralls.io/api/v1/jobs -i

**Comment by afinetooth** [comment]
@zjb421 closing this issue, but in case you have not resolved, you'll want to make sure that all of the attributes you're passing after `-F` in your command live in a single JSON object in the body of the file you're passing (`.resultset.json`).

In addition, you don't technically need to pass an Authorization header when POSTing to the /api/v1/jobs endpoint, as long as the JSON object in your file contains `"repo_token": "<your repo token from coveralls settings page>"`.

The error message you received, `Couldn't find a repository matching this job.` indicates `repo_token` was missing or incorrect in the POST body (the JSON object in your file).

Hope that helps. If not, just comment and I'll re-open.
