### ISSUE TITLE
Coveralls reporting 0% code coverage with swift codebase?

### ISSUE THREAD

**Issue by jackjpark** [lemurheavy/coveralls-public#1329]
I am running xcov and outputting the report to coveralls, travic ci generates the reports fine (I can see my coverage report in the CI console), yet coveralls reports 0% on every build. 

I have run coverage on my default branch and several PR'd and there is a discrepancy between xcov output and coveralls stats

Any ideas here? i get a successfully sent message so am unsure how to proceed with debugging this issue

**Comment by donnie-jp** [comment]
I've been experiencing this problem too.

My coveralls page shows 0% coverage for a Swift project that is generating coverage using xcov and running CI on travis.

https://coveralls.io/github/rakutentech/ios-remote-config
https://coveralls.io/builds/25516715
https://travis-ci.com/rakutentech/ios-remote-config/builds/125836479#L2025 (shows real 90% coverage)

**Comment by donnie-jp** [comment]
I plan to try https://github.com/nakiostudio/danger-xcov to skip coverage backends entirely and report directly on the PR.

**Comment by jackjpark** [comment]
@donnie-jp  i tried that but the danger integration is different and doesnt send to coveralls, its just for code review it seems

**Comment by chrispomeroyhale** [comment]
Swift compilations via Xcode and Swift Package Manager use a new coverage format. Many of the existing Codecov tools deal with gcc. I was able to use `xcrun llvm-cov export -format=lcov` with the `coveralls-lcov` gem. I have working SPM example on `csv-dialect-swift`

The [documentation](https://docs.coveralls.io/swift) on Swift language support needs to be updated since it currently references a deprecated tool that has been superseded by built-in tooling.

**Comment by iRILLLL** [comment]
> Swift compilations via Xcode and Swift Package Manager use a new coverage format. Many of the existing Codecov tools deal with gcc. I was able to use `xcrun llvm-cov export -format=lcov` with the `coveralls-lcov` gem. I have working SPM example on `csv-dialect-swift`
> 
> 
> 
> The [documentation](https://docs.coveralls.io/swift) on Swift language support needs to be updated since it currently references a deprecated tool that has been superseded by built-in tooling.

Thank u very much. It works!

I am using some 3rd libs, Do you know how to ignore SPM. I ignore the folders but looks like doesn't work

My coverage still decreased because the SPM is included.

**Comment by chrispomeroyhale** [comment]
> Thank u very much. It works!
> 
> I am using some 3rd libs, Do you know how to ignore SPM. I ignore the folders but looks like doesn't work
> 
> My coverage still decreased because the SPM is included.

@iRILLLL I have a vague recollection of that. llvm-cov has an `-ignore-filename-regex` option ([llvm-cov export command documentation](https://llvm.org/docs/CommandGuide/llvm-cov.html)). It looks like I have [an example](https://github.com/frictionlessdata/datapackage-swift/blob/master/.travis.yml) of this in `datapackage-swift`, which has an SPM dependency, where I integrated [coveralls with travisci](https://coveralls.io/github/frictionlessdata/datapackage-swift?branch=master)
