### ISSUE TITLE
Service Not Updating Repo

### ISSUE THREAD

**Issue by bruce-dunwiddie** [lemurheavy/coveralls-public#1330]
For the past few days, I've been attempting to update my repo and the service is not seeing any updates. I've attempted to push updates through my existing AppVeyor CI integration , https://github.com/bruce-dunwiddie/tsql-parser/blob/master/appveyor.yml , as well as manually running the .Net console to push to the service, and no new builds are showing on the site, https://coveralls.io/github/bruce-dunwiddie/tsql-parser . They're both depending on the .Net console to push, but I've ran the console with the debug flag set and no additional information or errors were shown.

**Comment by afinetooth** [comment]
@bruce-dunwiddie is this still an issue for you?

**Comment by bruce-dunwiddie** [comment]
I've had the pushes disabled since back then when I couldn't get past the problems. I will try to reenable them in the next day and get back to you on the results.

**Comment by bruce-dunwiddie** [comment]
Yes, it's still a problem, but it appears to not technically be a coveralls problem, just not necessarily the best error messaging.

My appveyor build log at https://ci.appveyor.com/project/bruce-dunwiddie/tsql-parser shows:

```
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
TSQL_Parser\packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover TSQL_Parser\Tests\bin\Debug\CodeCoverageResult.xml -r %COVERALLS_REPO_TOKEN%
No coverage statistics files.
```

So it appears that OpenCover is saying that it can't find the tests, and then coveralls is obviously saying that it can't find OpenCover's output.

So I'm sure it's a pathing issue that I should be able to resolve, and then we'll see if the coveralls push works.

But then I guess the confusion came in that I was trying to verify the coveralls push using the console, and that still doesn't work.

If I run https://github.com/bruce-dunwiddie/tsql-parser/blob/master/TSQL_Parser/Tests/CodeCoverage.bat locally with the coveralls command line un-rem'd, OpenCover generates the output, ReportGenerator creates the HTML output, and coveralls runs, but does not display any errors, even with the -d switch. And yet, no new build is listed at https://coveralls.io/github/bruce-dunwiddie/tsql-parser?branch=master . Is there something I'm logically doing wrong there that would prevent me from being able to see a more recent build that got pushed?

I'll see if I can get the AppVeyor pathing fixed and then maybe the console issue becomes a non-issue.

**Comment by bruce-dunwiddie** [comment]
I resolved the AppVeyor/OpenCover issue by running OpenCover as administrator, see https://github.com/bruce-dunwiddie/tsql-parser/commit/3458b47a731351923147cac47ebc066eae5eb7b8 , per https://github.com/OpenCover/opencover/issues/849 , and that appears to have pushed a new coveralls build via https://coveralls.io/github/bruce-dunwiddie/tsql-parser?branch=master .

@afinetooth , I'd still be interested if you have any suggestions about my console push, but this is a non-issue for coveralls.

**Comment by afinetooth** [comment]
@bruce-dunwiddie thanks. Glad you got it resolved. We're resource-limited so I can't speak to a timeline, but we could look at improving our error message to give a better lead next time. Can you tell me which error message(s) you're referring to? Thanks.

**Comment by bruce-dunwiddie** [comment]
The biggest issue was with the console running locally that gave no output, but did not seem to create a push at all, even when using debug/verbose mode. I think this is the rare instance where I'd suggest more verbosity. I'm still not sure if there's an error, or if it's somehow pushing the coverage results to an unexpected place, or if my token is wrong, etc.

It's nitpicky, but instead of the simplistic message "No coverage statistics files." that was output by the console from the AppVeyor build, I'd rather see "ERROR: coveralls could not locate coverage statistics files at C:\projects\TSQL_Parser\Tests\bin\Debug\CodeCoverageResult.xml. No coverage results were pushed."

**Comment by afinetooth** [comment]
Got it. That helps. Thank you.
