### ISSUE TITLE
Accesss denied when accessing https://coveralls.io/builds/COMMIN_HASH.json

### ISSUE THREAD

**Issue by DenisPalnitsky** [lemurheavy/coveralls-public#1331]
I'm trying to get coverage percentage for a commit in private repo by using HTTP GET to `https://coveralls.io/builds/COMMIN_HASH.json` with API token in the header but getting "Access Denied"
Here is full request:

curl --request GET \
  --url https://coveralls.io/builds/COMMIT_HASH.json \
  --header 'authentication: AUTH-TOKEN' \

**Comment by nickmerwin** [comment]
Hi @DenisPalnitsky, your curl command should use the `repo_token` query parameter like so:

```bash
curl "https://coveralls.io/builds/<sha>.json?repo_token=<token>"
```

We'll add more examples like this to our docs now.

Thanks.

**Comment by DenisPalnitsky** [comment]
This does not work either

**Comment by ashishbedicn** [comment]
Can we re-open this issue pelase. The suggested method does not seem to work.
