### ISSUE TITLE
Website inaccessible, api not working

### ISSUE THREAD

**Issue by majorgilles** [lemurheavy/coveralls-public#1333]
https://coveralls.io/
=> "This website is under heavy load (queue full)"

Using the coveralls python lib:
"coveralls.exception.CoverallsException: Could not submit coverage: 503 Server Error: Service Unavailable for url: https://coveralls.io/api/v1/jobs"

Any ETA on this? This is blocking our release process.
https://status.coveralls.io/ shows everything as being operational but obviously this is not the case.

**Comment by JetUni** [comment]
Even now that this is "fixed" our org is unable to update the coverage on the repo we're working on through node

**Comment by nickmerwin** [comment]
Hi @majorgilles and @JetUni we're going through a major database upgrade currently and the site should be back up and running soon.

Apologies for the extended downtime!

**Comment by dafreels** [comment]
Any ETA on when the site may be back up?

**Comment by nickmerwin** [comment]
@dafreels we've been monitoring progress closely and it's in currently in a phase where we can't see exact numbers but based off past performance it's likely going to be a few more hours unfortunately.
