### ISSUE TITLE
It looks like the site crashed immediately after sending my report from travis

### ISSUE THREAD

**Issue by mitani-kun** [lemurheavy/coveralls-public#1334]
Perhaps this information will be useful for debug the error.
coverall.io worked before I start this travis build:
https://travis-ci.org/NikolayMakhonin/tree-state-manager/builds/570764151
and crashed after trying to send a report to coveralls

Report file (lcov.info):
https://drive.google.com/file/d/1MCtn3NoSLbnYcJ3UBv-nkhhZfIcjI0h9/view?usp=sharing

**Comment by nickmerwin** [comment]
Hi @mitani-kun we're going through a major database upgrade currently and the site should be back up and running soon.

Apologies for the extended downtime!

**Comment by afinetooth** [comment]
Closing this issue as it seems to have been resolved back in Aug.
