### ISSUE TITLE
Update OCaml integration instructions

### ISSUE THREAD

**Issue by aantron** [lemurheavy/coveralls-public#1335]
The instructions on https://docs.coveralls.io/ocaml are out of date: the [ocveralls](https://github.com/sagotch/ocveralls) tool mentioned there has been superseded by direct support in [Bisect_ppx](https://github.com/aantron/bisect_ppx), the tool on which ocveralls is based.

The new instructions can be found here: https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md#Coveralls.

See https://github.com/aantron/bisect_ppx/pull/176 for history of what happened.

Separately, "OCaml" should be capitalized that way, not "OCAML" :)

**Comment by aantron** [comment]
The changes to the docs should be:

1. Replace `# OCAML` by `# OCaml`.

2. Replace the body text with something like:

    ```md
    Use [Bisect_ppx](https://github.com/aantron/bisect_ppx) to generate the
    report; then run `bisect-ppx-report send-to Coveralls`. See the
    [README](https://github.com/aantron/bisect_ppx#Coveralls) for more
    details.
    ```

Regarding the current (old) instructions on the website, ocveralls is now fully deprecated, and the repo is [archived](https://github.com/sagotch/ocveralls).

**Comment by afinetooth** [comment]
@aantron we've updated our OCaml docs per your changes. Thank you for the contribution.

**Comment by aantron** [comment]
Thanks! I checked the instructions live, and they look right.

I still have the nit that the page title/heading is OCAML rather than OCaml, but fix at your leisure :)

**Comment by afinetooth** [comment]
@aantron thanks. Our current stylesheet auto-capitalizes all headers and unfortunately we didn't take that into consideration with proper names with lower-case characters. I'll pass it on to our front end team and it will likely get fixed in our next update in May.
