### ISSUE TITLE
Ajax query returned non 200 HTTP response codes

### ISSUE THREAD

**Issue by jbunce** [lemurheavy/coveralls-public#1336]
Opening https://coveralls.io/github/omisego/elixir-omg gives the notification:

```
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

From the Javascript console:

<img width="555" alt="Screen Shot 2019-08-14 at 14 28 29" src="https://user-images.githubusercontent.com/25642194/63002502-400ab880-bea0-11e9-98e1-9464db29f809.png">

**Comment by nickmerwin** [comment]
Hi @jbunce this is operational now, thanks.
