### ISSUE TITLE
Parallel build with Travis not grouped and never closed

### ISSUE THREAD

**Issue by aureplop** [lemurheavy/coveralls-public#1338]
## Description

Since the 15th July 2019, only coverage of lines is visible on coveralls WebUI for a private project which uses parallel jobs on Travis. There is no longer summary for a file, group of files, job or build (what I call "closed" report).

Also, each coveralls job URL (see output below) links to a unique job per build kind of report, instead of a build report that is composed by multiple jobs.

We noticed this change in our Travis build output between the 15th and 17th July. Don't know if it's related.

Before the date, coveralls API answers with the Travis Job Number:
```
# Job A of build 1
$ coveralls
INFO:coveralls:200
INFO:coveralls:{"message":"Job #12345.1","url":"https://coveralls.io/jobs/10020030"}

# Job B of build 1
$ coveralls
INFO:coveralls:200
INFO:coveralls:{"message":"Job #12345.2","url":"https://coveralls.io/jobs/10020040"}
```

And since this date, the API answers with the Travis Job ID, suffixed by '.1':
```
# Job A of build 2
$ coveralls
INFO:coveralls:200
INFO:coveralls:{"message":"Job #123456789.1","url":"https://coveralls.io/jobs/10020050"}

# Job B of build 2
$ coveralls
INFO:coveralls:200
INFO:coveralls:{"message":"Job #123456790.1","url":"https://coveralls.io/jobs/10020060"}
```

## Additional infos

- **Travis**: Pro account
- **Coveralls client**: [python-coveralls](https://github.com/z4r/python-coveralls), version 2.9.3
- **.coveralls.yml**:
```
parallel: true
service_name: travis-pro
repo_token: XXX
```

## What I checked

- No change found about Travis tweaking the env vars, that are used by coveralls client.

- No change related to this issue in coveralls client.

- Sending the TRAVIS_JOB_NUMBER instead of TRAVIS_JOB_ID → bad idea.

**Comment by jvesely** [comment]
I've faced similar issues. adding webhook notification to .travis.yml as described in [0] fixed the issue for me. The grouping is still unreliable but it works more often than not.

[0] https://docs.coveralls.io/parallel-build-webhook

**Comment by aureplop** [comment]
Hi @jvesely, thanks for the proposition.
Sadly, we are already using the webhook mechanism to "merge" the different job results of a build. It was working before the date I gave in my initial message.
