### ISSUE TITLE
Unable to delete repo

### ISSUE THREAD

**Issue by martycook** [lemurheavy/coveralls-public#1339]
I've tried to delete several old repo's and each time I get redirected to an error page. Not sure what else I can do.

**Comment by davidmurdoch** [comment]
Same thing is happening for me. If I try to just disable coveralls for the repo on the "Add Repos" page I can see there is a "{"status":500,"error":"Internal Server Error"}" response to the DELETE command.

For me though, I don't actually want to delete coveralls, but coveralls won't update github statuses, even though coveralls will leave a comment (sometimes), so I have really have no choice but to delete and start over.
