### ISSUE TITLE
Unable to see Coverage Result

### ISSUE THREAD

**Issue by yihyang** [lemurheavy/coveralls-public#1342]
Hi there,

We have recently sign up for coveralls.io pro through the website (instead of going through Github Market) however we were not able to see the coverall result on the website and also the badge always show 'unknown'.

On our travis-ci we were able to submit the coverage report through `php-coveralls` however the result are not showing up on coveralls.io website.

Looking forward to your reply soon.

Thanks.

### Additional information
```
# executed test using the following
./vendor/bin/phpunit --testdox --coverage-clover tests/logs/clover.xml

# executed php-coveralls using the following
./vendor/bin/php-coveralls -v
```

**Comment by yrodiere** [comment]
This is happening to me too for a Java project.

What is strange is that it used to work in my case... I tried deleting the project from Coverall.io and re-creating it, but still the same issue.

See for example: https://coveralls.io/jobs/52557543
... which was sent successfully as mentioned in these logs: https://ci.hibernate.org/view/Search/job/hibernate-search/job/master/402/execution/node/43/log/
(see the line "Successfully submitted Coveralls data in 2665ms for Job #402.1").
But nothing appears on the project page: https://coveralls.io/github/hibernate/hibernate-search

**Comment by yihyang** [comment]
Hi @yrodiere seems like we are not alone. I think https://github.com/lemurheavy/coveralls-public/issues/1342 is also facing the same issue. Is there any other channel that we can reach out to coveralls team to support for the issue?

**Comment by yrodiere** [comment]
Hi. I sent an email to the support; wait and see :)

**Comment by yihyang** [comment]
Hi @yrodiere it seems to work for me now, what about you?

**Comment by yrodiere** [comment]
Yep, looks like it was fixed :)

**Comment by yihyang** [comment]
Glad to hear that, cheers!
