### ISSUE TITLE
We can't see coverage percent

### ISSUE THREAD

**Issue by svenedik** [lemurheavy/coveralls-public#1343]
Hi. I've mailed you several times, but I haven't received a reply, so I opened issue. 
We are using coveralls for a few private repositories. But we can't see coverage percent for one project. What is the reason for this? [#1128](https://github.com/lemurheavy/coveralls-public/issues/1128) can it be related to?

I send screenshots in an attachment. Good works...

![image](https://user-images.githubusercontent.com/38247600/63758698-df7a7300-c8c4-11e9-90e9-8d6f89ea9291.png)

We run `vendor/bin/php-coveralls --verbose`. 👆🏼 this is exported jobs page.

![image](https://user-images.githubusercontent.com/38247600/63757985-bd342580-c8c3-11e9-89f4-8649a17bb6a3.png)

![image](https://user-images.githubusercontent.com/38247600/63757925-9b3aa300-c8c3-11e9-84ea-6ea24305eec1.png)

**Comment by svenedik** [comment]
Although there are 35 jobs. File, class reports and built branches do not appear.

![image](https://user-images.githubusercontent.com/38247600/63760578-43526b00-c8c8-11e9-8761-87f74e0180f5.png)

**Comment by yihyang** [comment]
Hi @svenedik I'm also facing similar issue with you https://github.com/lemurheavy/coveralls-public/issues/1342 . Is there any other channel that we can reach out to coveralls team to support for the issue?

I have tried sending email to `support@coveralls.io` and they have yet to reply to me

**Comment by yihyang** [comment]
Hi @svenedik it seems to be working for me now, is it working for you now?

**Comment by svenedik** [comment]
@yihyang hi, yes i check after your info. Working now for me. Thanks for information man. :)

**Comment by yihyang** [comment]
Cheers mate!

**Comment by svenedik** [comment]
hi @yihyang  i hope u are feel good today. I think the trouble is happening again. how about you ?

**Comment by yihyang** [comment]
Hi @svenedik ! Likewise, hope that you are feeling good too.
I just checked it seems my last build was at around `13 Sep 2019 08:52AM UTC` and coveralls doesn't seems to send reply back to my team's PR since then. What about your side?

**Comment by svenedik** [comment]
Hello again, @yihyang. 
Builds are coming but, sometimes doesn't show coverage percent and building content (classes), after than September 11 😞 

![image](https://user-images.githubusercontent.com/38247600/64904084-2346e800-d6cd-11e9-84e6-5bfee9b0879f.png)
![image](https://user-images.githubusercontent.com/38247600/64904089-3ce82f80-d6cd-11e9-8163-fd7c2a0d0a12.png)

**Comment by nickmerwin** [comment]
Hi @svenedik and @yihyang we recently fixed an infrastructure issue that was preventing some private coverage jobs from completing. Your builds missing coverage are reprocessing now.

Thank you.

**Comment by yihyang** [comment]
<img width="755" alt="Screenshot 2019-09-16 at 2 15 05 PM" src="https://user-images.githubusercontent.com/8537324/64937342-7b781880-d88c-11e9-99f4-8d61ebaca606.png">

@nickmerwin I'm seeing the above when I'm trying to view the build page and I think coveralls is still not functioning as it should be. Please check

**Comment by svenedik** [comment]
i checked it. This problem solved for me. Thanks all.

**Comment by nickmerwin** [comment]
@yihyang could you link me to that page please?

**Comment by yihyang** [comment]
Hi @nickmerwin just checked, seems to be working now. Thanks

**Comment by svenedik** [comment]
@nickmerwin hi we don't see coverage percent and folder statistics today? what's wrong according to you. 
@yihyang what about you?
![image](https://user-images.githubusercontent.com/38247600/68372667-5f894880-0152-11ea-86a3-118a03e69d0d.png)
