### ISSUE TITLE
coveralls.io/builds/<sha>.json?repo_token=<token> does not work 

### ISSUE THREAD

**Issue by DenisPalnitsky** [lemurheavy/coveralls-public#1345]
I have a private repo and try to get coverage for a recent commit hash using 
`curl "https://coveralls.io/builds/<sha>.json?repo_token=<token>"`
using newly generated token but I'm getting "Access Denied"

**Comment by ashishbedicn** [comment]
Not working for me either.

**Comment by eyal0** [comment]
Related #1380 

This is breaking the coveralls chrome extension.

**Comment by afinetooth** [comment]
@DenisPalnitsky is this still an issue for you? (Not able to reproduce at this time.)

Closing the issue for now. Just reply if you have questions or need follow-up.

**Comment by eyal0** [comment]
This is still an issue for me. The chrome extension doesn't work. I tested it yesterday.

**Comment by willgdjones** [comment]
I can also confirm that the Chrome Extension does not currently work for me :(.

**Comment by willgdjones** [comment]
This is what is what is currently blocking me buying a Coveralls subscription. Codecov setup was painful and more expensive but ultimately worked in the end.
