### ISSUE TITLE
All files and branches covered but coverage below 100%

### ISSUE THREAD

**Issue by icemac** [lemurheavy/coveralls-public#1346]
In the RestrictedPython project the run details the coverage looks like this (see [example](https://coveralls.io/builds/25484953)):

* 359 of 363 branches covered (98.9%)
* 2700 of 2706 relevant lines covered (99.78%)

But when looking through the coverage of the files, each file has neither lines nor branches missing from coverage, so I am unable to find those lines and branches which are not covered.

What am I missing there?

**Comment by loechel** [comment]
after looking a bit more into that issue, I have found that the Code of RestrictedPython do have 6 Statements: `# pragma: no cover` and one `# pragma: no branch` 

So those lines are not taken into account by the coverage analysis itself, but it seams that coveralls itself do count those lines internally.
