### ISSUE TITLE
Access Denied page when trying to view build, after sign in.

### ISSUE THREAD

**Issue by jbrownsc** [lemurheavy/coveralls-public#1349]
Description: User sees Access Denied page when trying to view build, after sign in.

Steps to reproduce
1) User goes to Coveralls.io build link 
2) User gets Access Denied page
3) User signs in via Github
4) User still gets Access Denied page (refresh doesn't help)

Expected Behavior
1) User goes to Coveralls.io build link 
2) User gets Access Denied page
3) User signs in via Github
4) User can see the build details

Workaround for now
1) Ask all users to go to https://coveralls.io/refresh?private=true after sign-in

**Comment by afinetooth** [comment]
@jbrownsc thanks for the workaround. tagged `troubleshooting` for easier issue search.

Closing for now. Just reply for follow-up.
