### ISSUE TITLE
Coveralls not receiving Github Status API

### ISSUE THREAD

**Issue by hcwong** [lemurheavy/coveralls-public#1350]
Hello, 
I have a private repo with coveralls installed. I've enabled Status events for the repository's webhooks and also enabled the Status API on option on coverall's settings. However, I am not getting anything from Github when coveralls is done checking the PR. The coveralls status checks on PRs pass though. 

Thanks!

**Comment by nickmerwin** [comment]
Hi @hcwong could you please email us at support@coveralls.io with the name of the private repo? We'll follow up there, thanks.
