### ISSUE TITLE
Coveralls is non-responsive to a private repo

### ISSUE THREAD

**Issue by StevenZuber** [lemurheavy/coveralls-public#1351]
We're using CircleCI 2.0 for our Python 2.7 app and I've added the token from Coveralls to our CircleCI environment variables. According to the steps in the documentation, this should be all that's required to generate coverage reports. I've been able to generate reports by running all of the tests locally and running `COVERALLS_REPO_TOKEN={token} coveralls`, and have a similar working command in my circleci/config.yml and I'm seeing success messages in the logs on CircleCI, but reports aren't being added to Coveralls. 

I'm also not able to see our branches in the dropdown on the details page for the successful report I managed to generate. I'm not sure if this means it isn't properly authorized/connected to Github, but I've given Coveralls all of the permissions it asked for. https://coveralls.io/github/GetAmbassador/ambassador-api

**Comment by afinetooth** [comment]
@StevenZuber is this still an issue for you? I noticed a successful report from today here:
https://coveralls.io/github/GetAmbassador/ambassador-api

Closing the issue for now. Just reply if you have questions or want follow-up.
