### ISSUE TITLE
Coveralls is not listed in the GitHub check list

### ISSUE THREAD

**Issue by Hongbo-Miao** [lemurheavy/coveralls-public#1352]
For example, for this [no. 193 pull request](https://github.com/Hongbo-Miao/hongbomiao.com/pull/193), Coveralls is not listed in the GitHub check list.
The corresponding Coveralls build is at https://coveralls.io/builds/25712992

**Comment by nickmerwin** [comment]
Hi @Hongbo-Miao I see that the Coveralls status has posted. Can you confirm?

**Comment by Hongbo-Miao** [comment]
Yeah, my bot detected it, it works again now. Thanks!
