### ISSUE TITLE
Support Github Actions CI

### ISSUE THREAD

**Issue by alerque** [lemurheavy/coveralls-public#1353]
Github has added support for a built in CI system called [Actions](https://github.com/features/actions). I just setup the reporter for Lua [`luacov-coveralls`](https://github.com/moteus/luacov-coveralls/pull/19) to support it. While doing so I spent an inordinate amount of time debugging the fact that `github` was disallowed as a service name by the Coveralls API. I ended up calling the service `actions` instead and got it to work fine.

That being said it would be nice if Coveralls.io would itself document the name of the services that are or are not valid, and for those that are valid what special parameters have to match. In the case of `github` what exactly would be required to get first level support?

**Comment by Smolevich** [comment]
I try use coveralls for [Golang](https://github.com/mattn/goveralls/) and after many failed attempts, goveralls works, i setted environment variables `COVERALLS_TOKEN` and `GIT_BRANCH`

**Comment by nickmerwin** [comment]
Hi @alerque, we have official support for Actions here:

https://github.com/marketplace/actions/coveralls-github-action

Using service name `github` is reserved for GitHub Actions -- Coveralls expects to receive a `github-token` parameter to use for updating the build status.

**Comment by alerque** [comment]
Thanks for the clarificatino @nickmerwin. Since the official app doesn't support Lua, or the output format generated by `luacov` I'm still going to need to setup `luacov-coveralls` for this. It's working now but only with our custom name. I'd like this to work in as **github** in combination with the official app (for projects with other languages.

What should the contents of `github-token` be?
