### ISSUE TITLE
coverage status not set; one job says "no data"

### ISSUE THREAD

**Issue by ljharb** [lemurheavy/coveralls-public#1354]
See https://github.com/airbnb/enzyme/pull/2221

The coverage status isn't being set - although on prior pushes, it was successfully being set. I think I may have caused a failing job to notify coveralls, and then in successive pushes, filtered out that job - but now coveralls thinks there's no data and refuses to finish the coverage job?

**Comment by ljharb** [comment]
cc @nickmerwin

**Comment by nickmerwin** [comment]
Hi @ljharb, sorry about that, we had a notification outage that day -- it's been processed and updated now. Your next build on that repo will notify properly.

Thanks.

**Comment by ljharb** [comment]
@nickmerwin thank you! I've rerun the build and will comment here after it's done.

**Comment by ljharb** [comment]
Looks great, thanks!
