### ISSUE TITLE
500 errors when filtering coverage result lists

### ISSUE THREAD

**Issue by mfittko** [lemurheavy/coveralls-public#1355]
When trying to filter the results of our builds, we currently get 500 errors, so datatables cannot fetch the filtered data. For example when requesting following url: https://coveralls.io/builds/25925755/source_files.js?filter=all&sEcho=3&iColumns=10&sColumns=%2C%2C%2C%2C%2C%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=&bRegex_6=false&bSearchable_6=true&bSortable_6=true&mDataProp_7=7&sSearch_7=&bRegex_7=false&bSearchable_7=true&bSortable_7=true&mDataProp_8=8&sSearch_8=&bRegex_8=false&bSearchable_8=true&bSortable_8=true&mDataProp_9=9&sSearch_9=&bRegex_9=false&bSearchable_9=true&bSortable_9=true&sSearch=u&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&_=1569440145475
<img width="451" alt="Screenshot 2019-09-25 at 21 41 14" src="https://user-images.githubusercontent.com/326798/65633827-40d55500-dfdd-11e9-8cec-8aa56706a024.png">

**Comment by cdeil** [comment]
I have the same problem at https://coveralls.io/github/gammapy/gammapy

Trying to search gives an error

> DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![Screenshot 2019-11-06 at 12 07 22](https://user-images.githubusercontent.com/852409/68293366-17085700-008e-11ea-8a2b-190babea5b3d.png)

Is `coveralls.io` still being maintained?
If no, could you please add a note somewhere?
Any chance to get this issue fixed?

I think there's been very little activity in the past years, but recently there was a tweet again suggesting it's an active project: https://twitter.com/coverallsapp?lang=en

**Comment by afinetooth** [comment]
@cdeil I'm a new team member, labeling issues for the team as we try to improve our support response. Someone will have a second look asap. 

As for the project, here's what I can tell you:

Coveralls is definitely still being maintained! We’re a small team and have been recently focused on back-end infrastructure improvements to make sure that the community's millions of builds get processed. Rest assured the project remains under development, and we have an update to the application coming out by the end of May, 2020.

We’ve also been looking for the best way to provide support to hundreds of thousands of active users across a growing number of platforms and languages, and thankfully, we have a great community supporting the projects you see [here](https://docs.coveralls.io/) under [Languages And Integrations](https://docs.coveralls.io/), and those that match your project are always good places to look for further support. 

Current circumstances allow us to turn more attention to support right now, and we’re hoping to address our backlog and give our team a more permanent presence here. Please bear with us as we try to improve both our support and our documentation.

**Comment by afinetooth** [comment]
@cdeil this error with search should be fixed now. let us know if not.

Going to close the issue. Just reply if you need follow-up.
