### ISSUE TITLE
coveralls down (api is returning 500)

### ISSUE THREAD

**Issue by mstdokumaci** [lemurheavy/coveralls-public#1358]
```
/node_modules/coveralls/bin/coveralls.js:18

        throw err;

        ^

Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
```

7 hours and going, from [status page](https://status.coveralls.io/):
![graph](https://i.imgur.com/7l2TRTT.png)

**Comment by majorgilles** [comment]
Same issue, cannot post coverage data with python client

coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

**Comment by MuellerSeb** [comment]
Same for here for [GSTools](https://github.com/GeoStat-Framework/GSTools).

**Comment by rahulatscore** [comment]
Same for Java and Kotlin Coverage from Circle CI. 

HTTP/1.1 500 Internal Server Error
[message:Build processing error., error:true, url:]

**Comment by Clayton7510** [comment]
Same issue with Maven. Looks like it just started happening this morning. :'(

**Comment by andrewstec** [comment]
Same issue. Spent time debugging this because no operational issues reported on the website:

![image](https://user-images.githubusercontent.com/7872295/65782305-3b255f80-e102-11e9-824a-b08de69140a1.png)

**Comment by daviddelpuerto** [comment]
Same for Node with coveralls, also trying to sign in with github returns 500 error but coverarlls status page states ALL SYSTEMS OPERATIONAL :/

**Comment by vaneseltine** [comment]
Some, using Python's coveralls client, whether local or via CircleCI. Going on eight hours now?

**Comment by andrewstec** [comment]
> Some, using Python's coveralls client, whether local or via CircleCI.

We had the same problem with the Node JS client. I think it's an API issue on their end.

**Comment by ekampf** [comment]
same here using Python.

**Comment by vaneseltine** [comment]
I got one through just now, but another crashed. Maybe it's being worked on.

**Comment by jbrownsc** [comment]
I don't believe anyone actually works at this company.

**Comment by nickmerwin** [comment]
Hi all, apologies for the outage -- we had a Redis server go down earlier today and are back to normal now.

Thanks.
