### ISSUE TITLE
Source files contain many duplicates since Sep 2019

### ISSUE THREAD

**Issue by peterbrittain** [lemurheavy/coveralls-public#1359]
When I look at my coverage numbers per file, I see 2 different styles:

- Since ~Sep 2019, I appear to get a duplicate for every version of Python that I run - e.g. https://coveralls.io/builds/25990862
- Prior to that all coverage data for each file was grouped into a single view - e.g. https://coveralls.io/builds/25066432

I also notice that the coverage history in my repo (https://coveralls.io/repos/104573/builds) looks a bit strange.  Note the following transition:

- 508 | master | 96.36 | Fix mouse events processing for _BaseListBox scroll bar (#226) | 28 Sep 2019 06:31PM UTC | travis-ci
- 214 | master | 96.68 | Added maps demo | | 06 Jun 2017 05:41PM UTC | travis-ci
- 506 | master | 96.36 | Fix mouse events processing for _BaseListBox scroll bar  | 28 Sep 2019 09:30AM UTC | travis-ci

I don't know if that's related.

**Comment by MaxLap** [comment]
I have the same problem. Instead of merging the results of multiple jobs, each of them seem to appear on its own. Which means that instead of having 100% coverage, I have less, because of the version-related code.
https://coveralls.io/builds/26348385

**Comment by alexmojaki** [comment]
+1

**Comment by alexmojaki** [comment]
See https://github.com/gristlabs/asttokens/pull/44

**Comment by peterbrittain** [comment]
Thanks @alexmojaki .  If anyone else has the problem, I see it is documented in https://docs.coveralls.io/parallel-build-webhook

Would have been nice to be notified of the change...

**Comment by peterbrittain** [comment]
Works like a charm!  Many thanks.
