### ISSUE TITLE
Parallel build total files and line numbers wrong

### ISSUE THREAD

**Issue by lucianopaz** [lemurheavy/coveralls-public#1360]
At [pymc3](https://github.com/pymc-devs/pymc3) we are using travis to run CI across multiple parallel jobs and coveralls to publish the coverage results. Coveralls seems to have changed how it calculates coverage and number of lines. We have two consecutive builds that didn't change much between each other but coverage dropped dramatically. These are the builds
1. https://coveralls.io/builds/25707085
2. https://coveralls.io/builds/25746555

The first one reads: Total Files 136, 18069 of 20119 relevant lines covered (89.81%)

The second one reads: Total Files 1088, 116599 of 160600 relevant lines covered (72.6%).

It looks as if coveralls is not merging the coverage results from the parallel travis builds correctly, and that leads to a very low and incorrect code coverage result

**Comment by alexmojaki** [comment]
See https://github.com/gristlabs/asttokens/pull/44

**Comment by afinetooth** [comment]
@lucianopaz I checked your latest build and things seem ok:
https://coveralls.io/builds/13054950

Hoping the above contributors helped you out.

I'm going to close the issue for now. Just reply if you need some follow-up.
