### ISSUE TITLE
why coverage change is so high?

### ISSUE THREAD

**Issue by LeonardoFurtado** [lemurheavy/coveralls-public#1361]
I don't understand why the API returns such a high coverage change to me, given the previous coverage. Can someone explain to me why? (coverage_change =  60.9)

`

0 |  
-- | --
created_at | "2019-10-04T19:40:44Z"
url | null
commit_message | "Jacoco version updated"
branch | "master"
committer_name | "GitHub"
committer_email | "noreply@github.com"
commit_sha | "818766f0fec3634dba9324d1be95d6ea10c904dc"
repo_name | "bitcoinj/bitcoinj"
badge_url | "https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_61.svg"
coverage_change | 60.9
covered_percent | 60.8510348119609
1 |  
created_at | "2018-05-01T14:46:12Z"
url | null
commit_message | "ECKey: Factor out findRecoveryId() from signMessage()."
branch | "master"
committer_name | "Andreas Schildbach"
committer_email | "andreas.schildbach@bloq.com"
commit_sha | "a6fd71b7675f5704c8a2f907aa988813323e1548"
repo_name | "bitcoinj/bitcoinj"
badge_url | "https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_67.svg"
coverage_change | 0.04
covered_percent | 66.9517523473087

`

**Comment by afinetooth** [comment]
@LeonardoFurtado is this still an issue for you? 

Closing for now, but please just reply to re-open. If you re-open. please paste a link to your coveralls project and build, and we'll have a closer look. Thanks.
