### ISSUE TITLE
Generated file included in report, but still "Source Not Available"

### ISSUE THREAD

**Issue by Nic30** [lemurheavy/coveralls-public#1363]
Hello,

it seems to me that combination "files in repository" + "source contents in report json" does not work.

In my project I am using a generated source files, 
https://coveralls.io/builds/25901601/source?filename=src/vhdlConvertor/vhdlParser/vhdlParser.cpp

Files are not in repository, however they are included in report.
https://travis-ci.org/Nic30/hdlConvertor/jobs/596193125
(At the end of log, I can not print whole report as file is too big and exceeds the travis-ci limits and job is killed.)

**Comment by afinetooth** [comment]
@Nic30 does this remain an issue for you?

**Comment by Nic30** [comment]
@afinetooth,  https://coveralls.io/builds/29887494/source?filename=src/svConvertor/sv2017Parser/sv2017Lexer.cpp
it seems that it does. this is a build from yesterday.

**Comment by Nic30** [comment]
Also the file is around 0.25MB in size. I can not make it smaller as it is generated file, but I need to know it's coverage even if it takes a while. Is there anything I can try to find out what is causing the issue?

**Comment by afinetooth** [comment]
Thanks @Nic30, I've noted. Someone from core team will get to it asap.

**Comment by timwoj** [comment]
I'm running into the same issue with https://coveralls.io/github/zeek/zeek. The files in the `build` directory are generated during the build. I've confirmed that we're including the generated source code in the JSON data sent to coveralls.

**Comment by timwoj** [comment]
@afinetooth Any news of a fix for this at all? One of my tasks for this year is chipping away at our coverage misses, and I'd really like to include the missing files in that work.

**Comment by Nic30** [comment]
I can also provide an example files, possibly also test the thing if required.

**Comment by afinetooth** [comment]
@Nic30 @timwoj apologies for the silence on this issue. I was new when I last replied. 

The answer here is simple, but unfortunately it won’t help you. 

We do not store source code. (It would be a violation of our security protocols.) Therefore, the only way we can display source code is to retrieve it in real-time from your repo host (GitHub et. al.), on your behalf, using the access permissions provided through your OAuth token.

If the source doesn’t exist in the repo, we simply can’t retrieve its contents.

No workaround occurs to me at this time outside of adding the source file to your repo. 

Let me know if I’m missing something and we can take it from there.

**Comment by Nic30** [comment]
How unpleasant.

So the workaround is to push generated code in to some other branch. Is there a better way? As this  would make my repo GB in size in just one year.

Also it would be nice to have a proper error message and possibly warning during upload.

Also service policy and security protocols is something entirely different, just to be clear...

**Comment by afinetooth** [comment]
@Nic30 yes, you're right, the more appropriate term would have been "service policy." 

I have submitted a request for workarounds and will share any insights as I receive them.
