### ISSUE TITLE
No coverage info after Travis build but info exists after local build

### ISSUE THREAD

**Issue by rlalik** [lemurheavy/coveralls-public#1368]
Travis-CI does not updates files coverage, however the same commands executed on my local machine updates the build and files info.

See https://coveralls.io/github/SiFi-CC/CmdLineArgs for details

Build 18 is by Travis-CI, build #2 is my local one.

**Comment by alexmojaki** [comment]
Just a guess from my recent experience, try adding:

```yml
notifications:
  webhooks: https://coveralls.io/webhook
```
