### ISSUE TITLE
Add support for https://scrutinizer-ci.com

### ISSUE THREAD

**Issue by gemal** [lemurheavy/coveralls-public#1372]
would be really really nice

**Comment by afinetooth** [comment]
@gemal while we don't provide official support or docs for `scrutinizer-ci`, you should be able to have it send coverage data to coveralls.

We specify some general requirements here to get coveralls working with almost any CI:
https://docs.coveralls.io/supported-ci-services#insert-your-ci-here

Have you tried using `scrutinizer-ci`'s build config to push test results to coveralls?:
https://scrutinizer-ci.com/docs/configuration/build_reference

I'm assuming you'll want to look at the `tests:after` section, there ^^.

If you want to try that and hit a snag, let us know.

I'll close this issue in the meantime, but just reply if you want some follow-up.
