### ISSUE TITLE
Source Not Available

### ISSUE THREAD

**Issue by mshuaibii** [lemurheavy/coveralls-public#1374]
I'm getting my coverage report and coverage breakdown per file - but if I want to explore the line by line nature of each file I get a "Source Not Available" error. For example - https://coveralls.io/builds/26787644/source?filename=home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/amptorch/utils.py. I think it's a simple issue but I'm not sure how to go about it. 

Thanks!

**Comment by afinetooth** [comment]
@mshuaibii i'm assuming this was a configuration issue for you and that it's resolved now given i saw this difference in filename formats between your Build #20 and recent (working) builds:

### Build #20: 
filename = `/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/amptorch/utils.py`

### Build 74:
filename = `/amptorch/utils.py`

I'm going to close the issue for now, but just reply if you have follow-up questions.
