### ISSUE TITLE
coverage unknown

### ISSUE THREAD

**Issue by naman1303** [lemurheavy/coveralls-public#1379]
The badge for my git repository "naman1303/find-quote" is shown as "unknown", despite of availability of .coveralls.yml (with correct token) and spec_helper.rb. 

Is there anything I am missing?

**Comment by afinetooth** [comment]
@naman1303 which of the Javascript-related options here did you use to add test coverage reporting to your projects?:
https://docs.coveralls.io/javascript

coveralls receives output from coverage reporting tools, like `mocha-lcov-reporter`, in one of several formats, specifically, `lcov` for the above.

without the coverage report, coveralls has no data to estimate your coverage.

hope it helps. closing the issue for now but available for follow-up if you have more questions.
