### ISSUE TITLE
Coveralls chrome extension is loading the wrong URL

### ISSUE THREAD

**Issue by eyal0** [lemurheavy/coveralls-public#1380]
The coveralls chrome extension is loading the wrong URL

It is currently loading:

https://coveralls.io/builds/527a3e6aba9d7ad6f30d3a32953d36ce06b0cf97.json?paths=outline_bridges.cpp

But it should be loading:

https://coveralls.io/builds/27282741/source.json?filename=outline_bridges.cpp

**Comment by afinetooth** [comment]
@eyal0 is this still an issue for you?

**Comment by eyal0** [comment]
Yes, it's still a problem.  The Chrome extension is not working due to this.  To see it, install the Chrome extension and then go here:

https://github.com/pcb2gcode/pcb2gcode

Wait a few seconds and eventually the coverage data will load.  That part is working.  Now click on a file, for example, go here:

https://github.com/pcb2gcode/pcb2gcode/blob/master/autoleveller.cpp

The coverage data for the file is not loading.  That's because the extension is loading the wrong URL.  Perhaps the URL format changed at some point and the Chrome extension was not updated.

If the Chrome extension's source code is online, I can file a PR for it.  I have been unable to find that source code.
