### ISSUE TITLE
Not getting coveralls status

### ISSUE THREAD

**Issue by eyal0** [lemurheavy/coveralls-public#1382]
I stopped getting emails and github comments on my repo pcb2gcode/pcb2gcode .  It worked just fine until about 4 days ago.  I have recently switched to Github CI so maybe that is related?

**Comment by eyal0** [comment]
Okay, I figured it out.  It's because the pull request is not coming from the same repo as the target for the merge.  The token provided to the pull request workflow doesn't have permissions to modify the status of the PR nor add comments.  So it isn't doing those.

If I make the PR between two branches on the same repo (no fork) then then it works fine.

Maybe this could be fixed by adding a secret with a token that has the right permissions, and then using that instead of the GITHUB_TOKEN that is automatically generated?  But to do that, I would need access to the settings of the target repo and I don't have that.  So I'm stuck.

**Comment by eyal0** [comment]
If coveralls were willing to go back to the old behavior of using the Coveralls OAuth, like it does with TravisCI, that would work.

**Comment by exarkun** [comment]
I've just run into this while trying to set up coveralls for https://github.com/tahoe-lafs/tahoe-lafs.  The PR where I'm working on configuring coveralls - https://github.com/tahoe-lafs/tahoe-lafs/pull/956 - never receives a status update from coveralls.

I see this is a somewhat long-standing issue.  Is it likely to remain outstanding for the foreseeable future?  What motivation would lead to this being fixed?

**Comment by afinetooth** [comment]
@exarkun this is a frustration for some customers using the Coveralls Github Action, because there's a known limitation on Github extending access permissions (on the action's token) to the forked repo. Here's [some background](https://github.community/t/token-permissions-for-forks-once-again/16468) on the issue.

Something that has worked for some customers is to add the coveralls commenter bot to the forked repo as a collaborator. Instructions [here](https://docs.coveralls.io/coveralls-notifications#pull-request-comments). 

I don't know if this will work in your case. If not, let me know and we'll take it from there.

**Comment by exarkun** [comment]
Thanks for the quick reply @afinetooth, and for the background reference.  For what it's worth, I had found the documentation at https://docs.coveralls.io/coveralls-notifications#pull-request-comments and tries this to see if it fixed the problem **but** I only tried it for the main repo, `tahoe-lafs/tahoe-lafs`.  It didn't occur to me to also try inviting coveralls to the forked repo.

Unfortunately I don't see any difference in behavior after also inviting coveralls to `LeastAuthority/tahoe-lafs`.

After inviting the bot and waiting to see that it accepted the invitation, I pushed a new revision to https://github.com/tahoe-lafs/tahoe-lafs/pull/956 which triggered a new build.  I see a new report at https://coveralls.io/builds/36188618 but I still don't see any coveralls updates on the PR.

**Comment by exarkun** [comment]
Okay - scratch that last result.  Sometime later I reloaded the GitHub PR page and discovered coveralls *had* made a comment right around the time it should have done.  I dunno why I couldn't see it earlier ... mumble mumble browser cache ...

Thanks again.

**Comment by afinetooth** [comment]
@exarkun Ok, good to know. It's possible you were between invitation and acceptance. In any case, glad it worked out.
