### ISSUE TITLE
Query API

### ISSUE THREAD

**Issue by Jericho** [lemurheavy/coveralls-public#1383]
Does coveralls API allow me to query some statistics (some examples off the top of my head: code coverage percentage in last build, average coverage in last X builds, etc.)?

Reading https://coveralls.io/api/docs leads me to believe it's not possible but figured I would ask.

**Comment by afinetooth** [comment]
@Jericho try these resources:

- https://docs.coveralls.io/api-introduction
- https://docs.coveralls.io/api-reference

https://coveralls.io/api/docs is about creating and updating repos. The above gives access to jobs and coverage data so should be what you're looking for.

Closing the issue for now, but will be available for followups if you have more questions.
