### ISSUE TITLE
Cannot run goveralls in circleci

### ISSUE THREAD

**Issue by sarah-sampan** [lemurheavy/coveralls-public#1389]
Cannot run:
goveralls -coverprofile=/tmp/test.coverprofile -service=floormap-svc -repotoken=$COVERALLS_REPO_TOKEN

Error encountered:
01:55:01 gitinfo.go:56: exit status 129: error: unknown option `format'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]

**Comment by afinetooth** [comment]
@sarah-sampan best place to get help on this would probably be in the [goveralls](https://github.com/mattn/goveralls/issues) project.

Specifically, from searching issues there I found this PR that adds CircleCI support:
https://github.com/mattn/goveralls/pull/43

That contributor, [vvakame](https://github.com/vvakame), points to a PR on their example project, apparently successfully running coveralls with circleCI, here:
https://github.com/vvakame/appengine-go-sample/pull/1

That project's `Makefile` and `circle.yml` look like a good place to start:
https://github.com/vvakame/appengine-go-sample

Hope that gives you a good lead.

**Comment by afinetooth** [comment]
Closing the issue for now, but will be available for followups if you have more questions.
