### ISSUE TITLE
Wrong Committer Showing

### ISSUE THREAD

**Issue by d1b1** [lemurheavy/coveralls-public#139]
I have just started using coveralls. I purchased coverage for a private repo. When I commit a change and it builds on travis, I see strange committer info. Each time the info and the commit message are incorrect.

For example, I get this for my current build:

It shows a build number that should be 'Build 44', and my username (d1b1) for the commit owner. In its place I see 'PH3NOL' and a commit message for his project. WHen I try to preview it on github I see the following link. It gets a 404.

https://github.com/nprds/composerAPI/commit/a736a38894a88a047047bba7b23f8935a1e5743e (gives 404)

Thanks

**Comment by khatchad** [comment]
@d1b1 I'm having the same issue, but I'm unsure why because in my .coveralls.yml has:
```yaml
service_name: travis-pro
repo_token: ...
```
Can you post the example?
