### ISSUE TITLE
Coveralls not combining data from multiple tests runs

### ISSUE THREAD

**Issue by tamccall** [lemurheavy/coveralls-public#1390]
I have a repo that has 3 different tests runs all of which report coverage data. 2 of the test runs test different language versions against the repository and the last runs a completely different set of tests. 

After all of these get ran the coveralls page shows all of the files in the repository 3 different times all with different coverage numbers. However, the build used to combine all of these runs into a single summary for each file see:

- https://coveralls.io/github/nukosuke/terraform-provider-zendesk?branch=master (current master branch)
- https://coveralls.io/builds/23885889 (old build with combined coverage data)

We use https://github.com/mattn/goveralls to report the coverage data if that helps

Please help!

**Comment by jrfnl** [comment]
I'm seeing the same thing happening for PHP projects using [php-coveralls](https://github.com/php-coveralls/php-coveralls)

Example problem report: https://coveralls.io/builds/27804200 (708 files)
Last good report I could find from mid September 2019: https://coveralls.io/builds/25691592 (118 files <- this is the correct number of files)

**Comment by jrfnl** [comment]
Related #1360, #1362

**Comment by williamfalconeruk** [comment]
I'm seeing something similar where we have 2 x node lcov reports inside of a parallel upload, along with a php-coveralls. it is only reporting the first run and the last run.
This was run on a job on a CircleCI docker container with php 7 CLI and node installed

here's the bash script: 
```bash
export COVERALLS_SERVICE_NAME=circleci
export COVERALLS_GIT_BRANCH=$CIRCLE_BRANCH
export COVERALLS_PARALLEL=true
./php-coveralls.phar -v \
--json_path build/coveralls-upload.json \
--coverage_clover build/service-api/phpunit/coverage-fixed.xml \
--coverage_clover build/service-front/phpunit/coverage-fixed.xml
cd /home/circleci/project/service-front/web/ && npm install
cd /home/circleci/project/
cat /home/circleci/project/build/web-js/coverage/lcov.info \
| ./service-front/web/node_modules/.bin/coveralls --verbose
cat /home/circleci/project/build/service-pdf/coverage/lcov.info \
| ./service-front/web/node_modules/.bin/coveralls --verbose
 curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"
```
what we're seeing is this for a typical job (the job completes ok in circleci):
https://coveralls.io/builds/29103343

here is the screenshot:
<img width="1139" alt="Screenshot 2020-02-28 at 12 27 33" src="https://user-images.githubusercontent.com/4677426/75863477-74bc6e00-5df8-11ea-816d-8d89357be7dd.png">
you will see that the list is missing number 2, which corresponds to the second node coveralls upload.
seems to be related to the above issue.

It could be related to the fact that both jobs 1 and 2 have captured data from the same root (service-front) folder, but one set of coverage is in the `app/...` folder and the other is in `web/...`.
any help with this is appreciated!
