### ISSUE TITLE
Getting 422 Unprocessable Entity when uploading from AppVeyor

### ISSUE THREAD

**Issue by morozov** [lemurheavy/coveralls-public#1392]
This is an exceprt from the [failing build](https://ci.appveyor.com/project/doctrine/dbal/builds/29887767/job/d0o3x3nt0okbll7w):

```
Submitting to https://coveralls.io/api/v1/jobs
Client error occurred. status: 422 Unprocessable Entity
Couldn't find a repository matching this job.
```

I'm trying to use [php-coveralls](https://github.com/php-coveralls/php-coveralls) to upload the coverage report which seems to support AppVeyor out of the box:
```
Set environment variables properly like the following.

For AppVeyor users:

  - APPVEYOR
  - APPVEYOR_BUILD_NUMBER
```

Assuming that this message is not displayed on AppVeyor, it picks up the environment correctly.

Using the same uploader in the same repository, I can upload the report from the local environment:
```
$ wget https://github.com/php-coveralls/php-coveralls/releases/latest/download/php-coveralls.phar
$ phpunit  --coverage-clover build/logs/clover.xml
$ export COVERALLS_RUN_LOCALLY=1
$ export COVERALLS_REPO_TOKEN=********
$ php php-coveralls.phar -v

Finish submitting. status: 200 OK
Accepted Job ##3229.1
You can see the build on https://coveralls.io/jobs/57424597
```
Is there something I'm missing in the configuration? Thanks.

**Comment by peter-gribanov** [comment]
I have a similar problem in [Travis CI](https://travis-ci.org/github/gpslab/sitemap/jobs/703190011). Is there any solution?
