### ISSUE TITLE
Broken HTML in COMMIT MESSAGE

### ISSUE THREAD

**Issue by bayashi** [lemurheavy/coveralls-public#1394]
For instance, https://coveralls.io/builds/28435208

**Comment by sebatyler** [comment]
We have the same issue on https://coveralls.io/builds/33195654

**Comment by LastTalon** [comment]
I'm also experiencing the same issue at https://coveralls.io/builds/34082881

**Comment by afinetooth** [comment]
Thanks @bayashi @sebatyler @LastTalon we've reproduced and reported the issue. It's in our backlog.

**Comment by exarkun** [comment]
I've just run into this as well, for what it's worth (if you're tracking user impact). Here's an example - https://coveralls.io/builds/36171060

**Comment by afinetooth** [comment]
Thanks @exarkun. No update on status, but noted.
