### ISSUE TITLE
API: Get current repository configuration

### ISSUE THREAD

**Issue by rcmachado** [lemurheavy/coveralls-public#1397]
Coveralls API provides an endpoint to update repository configuration (send build status, comment on pull requests, etc) but I didn't found an endpoint to return this configuration back. Does it exists?

I would like to implement a custom [Terraform](https://www.terraform.io) provider (so we can configure Coveralls automatically when creating a new service), but without a way to get this information back I don't see a way to do it.

**Comment by afinetooth** [comment]
@rcmachado checkout the API docs here:
https://coveralls.io/api/docs

Those are linked to from the top of the API Reference doc, here:
https://docs.coveralls.io/api-reference

Per https://coveralls.io/api/docs, you can get back your configuration information from any successful POST, PUT or GET, but best practice is to use the **GET** endpoint, like:

**Route**:

```
GET https://coveralls.io/api/repos/github/GithubUser2/repo-1
```

**Headers**:

```
Accept: application/json
Content-Type: application/json
Authorization: token heiNGAuzaYFuVBBZ53ujChNbPH8cRznDo
```

Then you should get a response like this:

**Status**:

```
200
```

**Headers**:

```
Content-Type: application/json; charset=utf-8
```

**Body**:

```
{
  "service": "github",
  "name": "GithubUser2/repo-1",
  "comment_on_pull_requests": true,
  "send_build_status": true,
  "commit_status_fail_threshold": 75.5,
  "commit_status_fail_change_threshold": null,
  "created_at": "2000-01-01T08:00:00Z",
  "updated_at": "2000-01-01T08:00:00Z",
  "id": 2,
  "has_badge": false,
  "token": "heiNGAuzaYFuVBBZ53ujChNbPH8cRznDo"
}
```

**Comment by afinetooth** [comment]
@rcmachado closing the issue for now, but will be available for followups if you have more questions.
