### ISSUE TITLE
I signed up to the Coveralls Org subscription using my account but not able to see the Organisation's private Github repos.

### ISSUE THREAD

**Issue by haroonzone** [lemurheavy/coveralls-public#1402]

**Comment by nickmerwin** [comment]
Hi @haroonzone could you confirm that your org does not have 3rd party access restrictions enabled?

https://docs.coveralls.io/troubleshooting#ive-enable-private-repo-access-on-github-but-still-cant-see-an-organizations-repos

https://help.github.com/articles/approving-third-party-applications-for-your-organization/

**Comment by haroonzone** [comment]
Hi @nickmerwin it was indeed due to the 3rd party access restrictions. It is sorted now.
