### ISSUE TITLE
Add official support for Azure Pipelines

### ISSUE THREAD

**Issue by bmw** [lemurheavy/coveralls-public#1406]
It would be nice if Coveralls added official support for Azure Pipelines similar to what it has for the providers listed at https://docs.coveralls.io/supported-ci-services.

I'm trying to use coveralls on Azure Pipelines with Python, but none of the Python clients I've found seem to support setting the variables described at the bottom of your supported CI services docs to submit information about the build.

**Comment by yitam** [comment]
I agree, or at least elaborate more in the section "INSERT YOUR CI HERE" by giving some examples for Azure Pipelines, similar to the one for "ATLASSIAN BAMBOO"

**Comment by afinetooth** [comment]
@bmw @yitam thanks for the request. It's in our backlog.

In the meantime, I don't know if it will help, but here is a file with some configuration for Azure Pipelines in our JS-based language integration, [node-coveralls](https://github.com/nickmerwin/node-coveralls):
https://github.com/nickmerwin/node-coveralls/blob/705c3b5963e3cc76f8e70381dbae20979008c9b8/lib/getOptions.js#L128

Starts at line 128:

```js
  if (process.env.TF_BUILD) {
    options.service_name = 'Azure Pipelines';
    options.service_job_id = process.env.BUILD_BUILDID;
    options.service_pull_request = process.env.SYSTEM_PULLREQUEST_PULLREQUESTNUMBER;
    git_commit = process.env.BUILD_SOURCEVERSION;
    git_branch = process.env.BUILD_SOURCEBRANCHNAME;
  }
```

There's also an associated test here:
https://github.com/nickmerwin/node-coveralls/blob/705c3b5963e3cc76f8e70381dbae20979008c9b8/test/getOptions.js#L686

```js
const testAzurePipelines = (sut, done) => {
  process.env.TF_BUILD = 'true';
  process.env.BUILD_SOURCEBRANCHNAME = 'hotfix';
  process.env.BUILD_SOURCEVERSION = 'e3e3e3e3e3e3e3e3e';
  process.env.BUILD_BUILDID = '1234';
  process.env.SYSTEM_PULLREQUEST_PULLREQUESTNUMBER = '123';

  const git = {
    head: {
      id: 'e3e3e3e3e3e3e3e3e',
      author_name: 'Unknown Author',
      author_email: '',
      committer_name: 'Unknown Committer',
      committer_email: '',
      message: 'Unknown Commit Message'
    },
    branch: 'hotfix',
    remotes: []
  };

  sut((err, options) => {
    should.not.exist(err);
    options.service_name.should.equal('Azure Pipelines');
    options.service_job_id.should.equal('1234');
    options.service_pull_request.should.equal('123');
    options.git.should.eql(git);
    done();
  });
};
```

Hope it helps.

**Comment by bmw** [comment]
Thanks for the info.

Is there a way for me to be notified when support is added? Can this issue be kept open and closed once it is resolved?
