### ISSUE TITLE
Coveralls says there is 'no data' for successful build that has data.

### ISSUE THREAD

**Issue by grahambleon** [lemurheavy/coveralls-public#1408]
Our PR checks have started hanging in github lately 
![image](https://user-images.githubusercontent.com/24468019/75700977-ec678d00-5c80-11ea-8038-dcba5ae75e1b.png)

After checkout out the recent build in coveralls it says there is no data for the current build.
![image](https://user-images.githubusercontent.com/24468019/75700916-d4900900-5c80-11ea-8c6e-4d5ddcc8189e.png)

However when I click on the build I can see coverage data displayed.
![image](https://user-images.githubusercontent.com/24468019/75700763-9a266c00-5c80-11ea-865e-59b6dfb8d806.png)

We haven't changed any repository info and this in now happening on multiple repos so resyncing as suggested in #905 doesn't seem to help.  Any ideas as to what could be wrong?

**Comment by bvasil-cb** [comment]
yeah I am getting similar issues as well. I have also tried the suggested fix.

**Comment by mzjp2** [comment]
Yep, same here.

**Comment by mzjp2** [comment]
What's the output of your `coveralls debug` on your CI system? Also, what version of `coverage` are you using?

**Comment by grahambleon** [comment]
I'm using the coveralls github action to send up an lcov file.  `coveralls debug` doesn't do anything because nothing is installed.  Not totally sure what you're referring to by `coverage`.

**Comment by grahambleon** [comment]
We managed to fix the issue by switching to sonarcloud.
