### ISSUE TITLE
Coverage reports are coming late

### ISSUE THREAD

**Issue by svenedik** [lemurheavy/coveralls-public#1409]
Hi... We are using coveralls for a few private repositories. Some of our repos are big and we have problems in these repos. XML reports, which we usually send to Coveralls after 4:00 PM, arrive too late on the report list. The report, which we sent on March 2 at 5:30PM UTC, came on March 3, UTC 1:26AM to Slack hooks. Why is this happening? @nickmerwin  FYI

**Comment by tayyab-anwar** [comment]
Having a similar problem. We have set up coverage reports for each pull request. Generally, they take 15 minutes, but recently have been taking a long time. For some PRs, even 6-7 hours.
