### ISSUE TITLE
CircleCI pull request commenting.

### ISSUE THREAD

**Issue by nickmerwin** [lemurheavy/coveralls-public#141]
This is in the works, please :+1: if it's something you want to be top priority. Thanks!

**Comment by darbyw** [comment]
:+1:

**Comment by nickmerwin** [comment]
Hi @darbyw et al, this feature is live now with the latest Coveralls Ruby gem. Other integration libraries can implement it using the ```CI_PULL_REQUEST``` environment variable.

Cheers!

**Comment by akshayrawat** [comment]
:+1:

**Comment by darbyw** [comment]
@nickmerwin thanks - it doesn't seem to be working for us (upgraded to the latest gem) :(  Do we need to add repository read permissions for a Coveralls bot or something like that?

**Comment by nickmerwin** [comment]
@darbyw ok I'll look into it -- could you email me a link to the repo on Coveralls here: support@coveralls.io

Thanks!
