### ISSUE TITLE
Search on changed files is broken

### ISSUE THREAD

**Issue by tayyab-anwar** [lemurheavy/coveralls-public#1410]
<img width="539" alt="Screen Shot 2020-03-06 at 3 33 48 PM" src="https://user-images.githubusercontent.com/58931172/76076051-e5fa4d80-5fbf-11ea-8c45-3ec28da2cc53.png">

Clicking on "changed" here in a coverage report pops up a search bar with which we can search the relevant files. Typing anything in the search bar is giving me this error:

<img width="447" alt="Screen Shot 2020-03-06 at 3 28 20 PM" src="https://user-images.githubusercontent.com/58931172/76076136-1215ce80-5fc0-11ea-9ee9-d63d3c4f7eb7.png">

I have tried on colleagues' systems as well and the problem persists.

**Comment by hunterjackson** [comment]
this is also failing for me, and also when I select a file it claims I'm not logged it

**Comment by nickmerwin** [comment]
Hi @tayyab-anwar, this is fixed.
