### ISSUE TITLE
Getting 404 on file coverage

### ISSUE THREAD

**Issue by tayyab-anwar** [lemurheavy/coveralls-public#1418]
I'm trying to access the coverage data of individual files inside a build.

<img width="1163" alt="Screen Shot 2020-03-31 at 12 16 47 PM" src="https://user-images.githubusercontent.com/58931172/77997824-8175a880-7349-11ea-85dc-82f82512a99a.png">

Clicking on any of these files gives me:

<img width="1665" alt="Screen Shot 2020-03-31 at 12 17 47 PM" src="https://user-images.githubusercontent.com/58931172/77997901-a36f2b00-7349-11ea-9608-62ea462ee4bb.png">

I also appear signed out.
Signing in takes me back to the repos page, and going from there trying to access a file takes me to the same page.

**Comment by nickmerwin** [comment]
Hi @tayyab-anwar, letting you know we've fixed the issue. Please let me know if you see anything else amiss.

Thank you!

**Comment by tayyab-anwar** [comment]
Thanks for the quick fix!
