### ISSUE TITLE
Getting Started page has stale CI information

### ISSUE THREAD

**Issue by nicowilliams** [lemurheavy/coveralls-public#1425]
It lists only three CIs as supported, while https://docs.coveralls.io/supported-ci-services lists many more.

**Comment by afinetooth** [comment]
Thanks @nicowilliams. We're in progress on new documentation that should cover this, but in the meantime, we've updated the Getting Started section of the current documentation to link to the full list of supported CIs:
https://docs.coveralls.io/#using-a-language-specific-wrapper
