### ISSUE TITLE
Coveralls reports 0% coverage

### ISSUE THREAD

**Issue by danielcondemarin** [lemurheavy/coveralls-public#1434]
In the last couple of builds coveralls has been reporting 0% coverage on my project. https://coveralls.io/github/danielcondemarin/serverless-next.js. 

`jest --runInBand --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"` executes successfully in travis and the lcov.info is definitely populated. 

Any ideas what may be causing this?

**Comment by kozzztik** [comment]
Same problem for me https://coveralls.io/github/kozzztik/tulius

**Comment by matthiaskeysermann-signavio** [comment]
We are facing the same problem using jest with `--coverage --coverageReporters=lcov`.

@kozzztik It looks like you no longer face this problem. What did you change to fix it?

**Comment by kozzztik** [comment]
@matthiaskeysermann-signavio I switched to coveralls-clients/coveralls-python.
Also, I tried to run coverage in docker, and then send results outside of container, maybe that was a reason too. I changed that behavior to send results from container guest system.

**Comment by afinetooth** [comment]
@danielcondemarin @kozzztik I was hoping to close this issue for housekeeping. I looked at your recent builds on the above projects and they look good, non-zero coverage, etc. Please just re-open if you're still having the issue.
