### ISSUE TITLE
Background graph shows only old coverage

### ISSUE THREAD

**Issue by ehuelsmann** [lemurheavy/coveralls-public#1437]
Hi,

The background coverage graph on https://coveralls.io/github/ledgersmb/LedgerSMB shows coverage between 0 and 25% where coverage has been over 25% for ages (it's at a much better, but still wanting, level of 43% today).

While I appreciate the fact that more measurements don't fit on the page, it'd make more sense to see the more recent coverage instead of the side of the graph.

Thanks for your service and for looking at it!

Regards,

Erik.

**Comment by ehuelsmann** [comment]
This has actually been resolved some months ago.

**Comment by afinetooth** [comment]
Thanks, @ehuelsmann.
