### ISSUE TITLE
URL in response doesn't seem to be valid

### ISSUE THREAD

**Issue by ioquatix** [lemurheavy/coveralls-public#1439]
Posting to the coverage API returns:

```
Got response: {:message=>"Job #248.5", :url=>"https://coveralls.io/jobs/44735828"}
```

But going to that URL returns 404.

**Comment by elijahr** [comment]
We're also seeing this. We have CircleCI running coveralls, and this is the output:

```
Submitting coverage to coveralls.io...
Coverage submitted!
Job #46091.11
https://coveralls.io/jobs/63555054
CircleCI received exit code 0 
```

But https://coveralls.io/jobs/63555054 gives a 404. I am logged into coveralls and can see other jobs from other private repos in my organization.

We are using python2.7 and coveralls = "~=1.11".

FWIW, we are paid coveralls subscribers, and this is a private repo. I am not the coveralls account manager but my github account is a member of the organization and has full R/W access to the repo.

There's also this old issue, which may be related: https://github.com/lemurheavy/coveralls-public/issues/112
