### ISSUE TITLE
Tree view randomly shows or does not show

### ISSUE THREAD

**Issue by transmissions11** [lemurheavy/coveralls-public#1444]
Seemingly at random, I will not get the tree view to see my files coverage, and sometimes I will get the option. The tree view is my favorite view, and I'd really like to be able to use it most of the time, instead of refreshing a few times to get it to appear. 

Examples below (these were taken right after each other after reloading):
![ScreenShot- 54](https://user-images.githubusercontent.com/26209401/81743262-3fff0f80-9456-11ea-947e-4c74a698b42e.png)
![ScreenShot- 55](https://user-images.githubusercontent.com/26209401/81743264-41c8d300-9456-11ea-8cf6-8eb84643cc80.png)

**Comment by transmissions11** [comment]
Update: No longer am I having this glitchy behavior, but the fact that that this did happen is odd, and doesn't seem like something that should ever happen.

**Comment by afinetooth** [comment]
@TransmissionsDev thanks. I was not able to reproduce myself, but have still submitted an issue ticket for review. Let us know if you see it again.
