### ISSUE TITLE
"Coverage decreased -0.0%" but JSON API reports identical coverage before and after

### ISSUE THREAD

**Issue by cspotcode** [lemurheavy/coveralls-public#1446]
Looking at the coverage for this commit:
https://github.com/TypeStrong/ts-node/commit/9840cb19421f5acfc700783660c1941b9e71c6c2
... which should have no effect on coverage because it does not affect code.

![image](https://user-images.githubusercontent.com/376504/82155780-4837c000-9845-11ea-9905-8f2765b17a3d.png)

Using coveralls' API, coverage for that commit is:
https://coveralls.io/jobs/62768110.json
```
{"repo_name":"TypeStrong/ts-node","full_number":"107236898.1","timestamp":"2020-05-17T11:35:13Z","covered_percent":81.1203319502075}
```
For the parent commit is:
https://coveralls.io/jobs/62761168.json
```
{"repo_name":"TypeStrong/ts-node","full_number":"106919259.1","timestamp":"2020-05-17T00:17:58Z","covered_percent":81.1203319502075}
```

Covered percent for each is `81.1203319502075`.

Why is coveralls reporting a coverage drop of 0.0%?

**Comment by afinetooth** [comment]
@nathany sorry for the delay. doing a sweep of old issues.

In case this response could still be helpful....

so, while you're correct that there appears to be no coverage difference between those two commits, they are both "push" type builds, both commits to master branch, and, as such, don't send PR checks to Github.

instead, the commit that would have sent that check to your PR is the "pull_request" type build that appears between the two builds above&mdash;here, according to the build history:

https://coveralls.io/repos/73727/builds?page=22

![Screen Shot 2021-02-04 at 11 06 51 AM](https://user-images.githubusercontent.com/918667/106942614-3ea6fe80-66d9-11eb-8648-af08f1cb26cc.png)

Although, based on the content of the commit, you may actually be referring to the build subsequent to the second example build&mdash;here:

https://coveralls.io/repos/73727/builds?page=22

![Screen Shot 2021-02-04 at 11 06 51 AM - 2](https://user-images.githubusercontent.com/918667/106942907-934a7980-66d9-11eb-9746-84546b301f80.png)

If you're talking about the first of those PRs, there would have been a small incremental decrease according to the build details:

Build:
https://coveralls.io/builds/30841528

![Screen Shot 2021-02-04 at 11 20 39 AM](https://user-images.githubusercontent.com/918667/106944063-043e6100-66db-11eb-92ec-ac08df5cb7f3.png)

Job:
https://coveralls.io/jobs/62767976.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "107232122.1",
timestamp: "2020-05-17T11:22:50Z",
covered_percent: 81.1088295687885
}
```

(I'm guessing that's the PR.)

If it's the other one, the second PR, taking place after the second example build on master, then this is the build:
https://coveralls.io/builds/30841614

(No change)

![Screen Shot 2021-02-04 at 11 21 20 AM](https://user-images.githubusercontent.com/918667/106944164-1cae7b80-66db-11eb-9820-fd7aec26d0c4.png)

Job:
https://coveralls.io/jobs/62768112.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "107236871.1",
timestamp: "2020-05-17T11:35:15Z",
covered_percent: 82.9875518672199
}
```

Which tracks with that build's base build:
https://coveralls.io/builds/30834806

![Screen Shot 2021-02-04 at 11 22 38 AM](https://user-images.githubusercontent.com/918667/106944327-4cf61a00-66db-11eb-96f9-1ec4f53d33b1.png)

Where Job 1 was:

https://coveralls.io/jobs/62754897.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "106706132.1",
timestamp: "2020-05-16T17:24:32Z",
covered_percent: 82.9875518672199
}
```

Can you verify which PR that PR check came from?

Closing for now given the age, please just reply to re-open.
