### ISSUE TITLE
Feature request: use actual hyperlinks instead of `onclick` handlers

### ISSUE THREAD

**Issue by fingolfin** [lemurheavy/coveralls-public#1447]
When navigating the source file tree, I can click on a file to get a detailed coverage report for that file. Unfortunately, this is not implemented via a hyperlink, but rather (I am guessing) via a JavaScript `onclick` handler. The problem with that is that right-clicking doesn't work, which means I can't open the file in a separate window or tab, or bookmark it, or whatever. This is very annoying. Luckily, it ought to be simple to fix, too?

**Comment by afinetooth** [comment]
@fingolfin Thanks for your suggestion. I have added the feature request to our backlog, suggesting an alternate approach that might work, if hyperlink is not possible, of a linked icon to open the source file in a new window.

Something like this:
![open-link-in-new-window](https://user-images.githubusercontent.com/918667/95530676-51136480-0993-11eb-94d9-e3b0f55aa778.png)

I will close this for now, now that we have a tracking task in our internal system.

Thanks again.
