### ISSUE TITLE
How to grant chat bot access to comment on PR in github enterprise?

### ISSUE THREAD

**Issue by mariaolivero-RL** [lemurheavy/coveralls-public#1449]
I have actually seen another ticket that asks almost exactly the same question, but there is no clear answer on it so I'm going to ask again.  https://github.com/lemurheavy/coveralls-public/issues/396 is the original I found without a real answer.

**Comment by afinetooth** [comment]
Hi @mariaolivero 

If you're talking about a private repo, here are the steps:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter **coveralls**
4. Click **Add coveralls to <your-app>**.
5. Coveralls will auto-accept your invitation within 1-4 hrs.

Please let me know if that doesn't work for you, or if you're looking at a different scenario.

**Comment by mariaolivero-RL** [comment]
Thanks, we'll give it a try...

**Comment by afinetooth** [comment]
Closing the issue. Hope it worked for you.
