### ISSUE TITLE
Not finding badge in README

### ISSUE THREAD

**Issue by cadorn** [lemurheavy/coveralls-public#145]
For this repo: https://coveralls.io/r/pinf/pinf-loader-js

I have added the badge to the `README.md` but it does not seem to be finding it on the status page.

Also, the badge image does not seem to switch from unknown to the report info even though there is report info.

**Comment by dhermes** [comment]
I set up https://coveralls.io/github/dhermes/berkeley-m273-s2016/ 24 hours ago and it still says "Could not find badge in README." and the [builds][1] on Travis seem to think they aren't:

```
coveralls runtests: commands[1] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis or CircleCI
ERROR: InvocationError: '/home/travis/build/dhermes/berkeley-m273-s2016/.tox/coveralls/bin/coveralls'
```

[1]: https://travis-ci.org/dhermes/berkeley-m273-s2016/builds/106147976

**Comment by dhermes** [comment]
Figured it out, I wasn't passing through the `TRAVIS*` environment variables to the `tox` environment.
