### ISSUE TITLE
Coverage for multiple languages/test suites (reopened)

### ISSUE THREAD

**Issue by nathany** [lemurheavy/coveralls-public#1451]
Today I ran into issues merging test coverage from Elixir and JavaScript and sending it to Coveralls.io. Apparently merging multiple test suites isn’t *really* a solved problem. (reopening #373)

* For JavaScript, Jest exports LCOV format, which the Coveralls GitHub Action converts to the JSON format used by Coveralls.
* ExCoveralls directly uploads JSON to Coveralls with no LCOV intermediary. Since LCOV is a flat text format, [if LCOV support existed for Elixir](https://github.com/parroty/excoveralls/issues/104), the two files could be merged with `cat` and uploaded.
* I found a RubyGem called Coveralls Multi that surprisingly supports Elixir’s ExCoveralls and can combine coverage from multiple formats, so it merges the LCOV from JavaScript and the Coveralls JSON for Elixir. Unfortunately [it doesn’t yet support GitHub Actions](https://github.com/radditude/coveralls-multi/issues/10) for CI. I managed to get it to export a file, which is in JSON format. Unfortunately the Coveralls GitHub Action [expects LCOV format](https://github.com/coverallsapp/github-action/issues/52#issuecomment-633699136) and appears to have no option of uploading Coveralls JSON format.

This is a good example of tools not following the Unix philosophy of *doing one thing well*. Instead of a tool to convert formats and a tool that uploads, all three of these tools take on multiple tasks and therefore can’t be used together. 

I’m sure there’s a solution somewhere, likely finding a fourth tool to upload the coveralls JSON output (from Coveralls Multi) instead of using the GitHub Action (even though that seems like the obvious choice).

I'm reopening this issue not only because it cost me a day (and I'd like it not to cost other developers a day in the future), but also because of what the competition is up to:

* "Codecov flawlessly supports all these setups." ([Merging Reports](https://docs.codecov.io/docs/merging-reports))
* "The Code Climate test reporter can join multiple test reports together from separate test suite processes." ([Multiple Test Suites](https://docs.codeclimate.com/docs/configuring-test-coverage#section-multiple-test-suites))

So I'm very curious what the Coveralls response is to this request. And to be clear, it's not a solution to the specific Elixir + JavaScript situation I'm hoping for, but more general support for multiple languages or multiple test runs.

**Comment by afinetooth** [comment]
@nathany sorry for the delay. doing a sweep of old issues.

If this can still be helpful....

so, while you're correct that there appears to be no coverage difference between those two commits, they are both "push" type builds, both commits to master branch, and such builds don't send PR checks to Github.

instead, the commit that would have sent that check to your PR is the "pull_request" type build that appears between the two builds above&mdash;here, according to the build history:

https://coveralls.io/repos/73727/builds?page=22

![Screen Shot 2021-02-04 at 11 06 51 AM](https://user-images.githubusercontent.com/918667/106942614-3ea6fe80-66d9-11eb-8648-af08f1cb26cc.png)

Although, based on the content of the commit, you may actually be referring to the build subsequent to the second example build&mdash;here:

https://coveralls.io/repos/73727/builds?page=22

![Screen Shot 2021-02-04 at 11 06 51 AM - 2](https://user-images.githubusercontent.com/918667/106942907-934a7980-66d9-11eb-9746-84546b301f80.png)

If you're talking about the first of those PRs, there would have been a small incremental decrease according to the build details:

Build:
https://coveralls.io/builds/30841528

![Screen Shot 2021-02-04 at 11 20 39 AM](https://user-images.githubusercontent.com/918667/106944063-043e6100-66db-11eb-92ec-ac08df5cb7f3.png)

Job:
https://coveralls.io/jobs/62767976.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "107232122.1",
timestamp: "2020-05-17T11:22:50Z",
covered_percent: 81.1088295687885
}
```

(I'm guessing that's the PR.)

If it's the other one, the second PR, taking place after the second example build on master, then this is the build:
https://coveralls.io/builds/30841614

(No change)
https://coveralls.io/builds/30841614

![Screen Shot 2021-02-04 at 11 21 20 AM](https://user-images.githubusercontent.com/918667/106944164-1cae7b80-66db-11eb-9820-fd7aec26d0c4.png)

Job:
https://coveralls.io/jobs/62768112.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "107236871.1",
timestamp: "2020-05-17T11:35:15Z",
covered_percent: 82.9875518672199
}
```

Which tracks with that build's base build:
https://coveralls.io/builds/30834806

![Screen Shot 2021-02-04 at 11 22 38 AM](https://user-images.githubusercontent.com/918667/106944327-4cf61a00-66db-11eb-96f9-1ec4f53d33b1.png)

Where Job 1 was:

https://coveralls.io/jobs/62754897.json

```
{
repo_name: "TypeStrong/ts-node",
full_number: "106706132.1",
timestamp: "2020-05-16T17:24:32Z",
covered_percent: 82.9875518672199
}
```

Can you verify which PR that PR check came from?

Closing for now given the age, please just reply to re-open.
