### ISSUE TITLE
Coverage shrank but no files have "shrunk coverage"

### ISSUE THREAD

**Issue by thoni56** [lemurheavy/coveralls-public#1452]
In [this build](https://coveralls.io/builds/31016330) I see that total coverage shrank, but I can't find any file that contributes to that lowered coverage.

Isn't it supposed to show downward arrows for files too?

**Comment by thoni56** [comment]
I found the file with the down-arrow, it was the last file which was on the next "page". Sorry about that. But a follow-up here is how to see differences in coverage between builds __inside__ files, is that possible or on the radar?

**Comment by afinetooth** [comment]
Hi @thoni56 

Thanks for the update.

Just linking readers here to our other issue discussing line-by-line coverage changes:
https://github.com/lemurheavy/coveralls-public/issues/1453
