### ISSUE TITLE
Source Not Available in ICU4X

### ISSUE THREAD

**Issue by zbraniecki** [lemurheavy/coveralls-public#1456]
All commits in https://coveralls.io/github/unicode-org/icu4x have `source not available`.

Seems like a bug in coveralls that require some server-side fix according to other reports in this repo.

Can I ask for help?

**Comment by afinetooth** [comment]
Hi @zbraniecki,

I'm seeing source files in your most recent builds:

Can I assume you're no longer having the issue?:

![Screen Shot 2020-08-05 at 5 54 24 PM](https://user-images.githubusercontent.com/918667/89478387-b43f0b80-d744-11ea-87b1-d883f91dd0e1.png)

I'll close, but please reply if so and I'll re-open. Thanks.

**Comment by zbraniecki** [comment]
Hmm, I still see "source not available" when I click on https://coveralls.io/builds/32470011/source?filename=components/locale/src/parser/langid.rs in a browser that I'm not logged in.

**Comment by afinetooth** [comment]
Interesting!

I see a source file at that URL:

![Screen Shot 2020-08-05 at 5 58 07 PM](https://user-images.githubusercontent.com/918667/89478571-3af3e880-d745-11ea-8419-f0e1be1f53a4.png)

I am logged into Coveralls, and I have administrative access.

Are you saying you're _not_ logged into Coveralls?

**Comment by zbraniecki** [comment]
Can you try from a non-logged browsing session?

> Are you saying you're not logged into Coveralls?

yes.
