### ISSUE TITLE
Coveralls error during Travis CI build on a Maven multi-module Java project

### ISSUE THREAD

**Issue by liuzzom** [lemurheavy/coveralls-public#1459]
Hi.
I'm working on Java project made of some Maven modules. I have a parent module that defines shared dependencies and plugins, and two submodules, a module called "front-end" and a module called "back-end". I also use an aggregator module for the overall buildind. I'm trying to measure the code coverage using Coveralls with JaCoCo and Travis CI. I added the JaCoCo plugin and the Coveralls plugin into the parent POM in this way:

```xml
<!-- Jacoco maven plugin -->
<plugin>
		<groupId>org.jacoco</groupId>
		<artifactId>jacoco-maven-plugin</artifactId>
		<version>0.8.3</version>
		<configuration>
		<excludes>
			<exclude>**/model/*.*</exclude>
			<exclude>**/TransactionManagerMongo.*</exclude>
		</excludes>
	</configuration>
	<executions>
		<execution>
			<goals>
				<!-- binds by default to the phase "initialize" -->
				<goal>prepare-agent</goal>
				<!-- binds by default to the phase "verify" -->
				<goal>report</goal>
			</goals>
		</execution>
	</executions>
</plugin>

<!-- Coveralls maven plugin -->
<plugin>
	<groupId>org.eluder.coveralls</groupId>
	<artifactId>coveralls-maven-plugin</artifactId>
	<version>4.3.0</version>
	<executions>
		<execution>
			<goals>
				<goal>report</goal>
			</goals>
			<phase>verify</phase>
		</execution>
	</executions>
</plugin>
```
So I expect that during the build Coveralls will perform the analysis on both the front-end and back-end modules.However, the build fails during the analysis of the front-end (after the back-end module build) module with the following error:

```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default) on project my-career-frontend: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (service_job_id (708298541) must be unique for Travis Jobs not supplying a Coveralls Repo Token) -> [Help 1]
```
It seems that the same job id used for both back-end and front-end coveralls analysis. If I try to run Coveralls only for one module, the build succeeds.

You can find the overall project here: https://github.com/liuzzom/my-career

**Comment by afinetooth** [comment]
Hi @liuzzom,

It sounds like you want to configure Travis to run your builds in parallel jobs. 

When you do this, Travis will run each job, assign it a unique id---like 5240.1, 5240.2, etc.---and send it to Coveralls. 

Then you'll want to add a line to your Travis config to call Coveralls' parallel webhook, when all jobs are done. That will tell Coveralls to combine the results of all jobs and calculate merged coverage results for your project.

Start here for how to configure parallel builds at Travis:
https://docs.travis-ci.com/user/speeding-up-the-build

When you're done there, here's how to send the parallel builds webhook at the end:
https://docs.coveralls.io/parallel-build-webhook
(Travis example there.)

Let me know if you need more help.
