### ISSUE TITLE
Delay between coverall and github

### ISSUE THREAD

**Issue by luisdalves** [lemurheavy/coveralls-public#1460]
Hey guys,

We are facing an important delay between Coverall and Github. We are waiting between 1-3 hours to get the green light from coverall to merge our code.
We didn't find any issues reported on status page.

Is there any way to force this hook against our github account?

Our github organization is **tiendanube**

Thanks!

**Comment by chloh** [comment]
This has been happening to us, too, for the last week or so. Sometimes it takes several hours or even until the next day, and we end up having to have an admin force merge it anyway, which significantly slows down our output. Our github org is goodtimeio.

**Comment by afinetooth** [comment]
Hi @luisdalves, @chloh,

This past Fri, Jul 17, we discovered an issue that was degrading performance for a segment of users for about 48-72 hrs. We've since fixed the issue, so hopefully that's improved things for you.

Let us know if not.
