### ISSUE TITLE
Gateway timeout when clicking on Updates link from Coveralls homepage

### ISSUE THREAD

**Issue by chuckdumont** [lemurheavy/coveralls-public#1462]
I'm consistently seeing Gateway Timeout errors whe I click on the Updates link in the https://coveralls.io homepage.

The web server reported a gateway time-out error.

    Ray ID: 5b7606673f17f0f2
    Your IP address: 47.14.38.78
    Error reference number: 504
    Cloudflare Location: Ashburn

**Comment by chuckdumont** [comment]
On a related note, how do I navigate to a PR build in the coveralls ui?  I was using the Updates link to find PR builds, but this is no longer working for me as indicated above.

The Recent Builds section in the Repos view doesn't include PR builds.  Is there any other way besides the Updates view to navigate to a PR build?

**Comment by chuckdumont** [comment]
On a related note, how do I navigate to a build that's in the PENDING COMPLETION state in the coveralls ui? I was using the Updates link to find these builds, but this is no longer working for me as indicated above.

The Recent Builds section in the Repos view doesn't include pending builds. Is there any other way besides the Updates view to navigate to these builds?  I need to do this because of the issue reported in #1461, which was closed by @afinetooth but is not resolved.

**Comment by afinetooth** [comment]
Hi @chuckdumont,

We've been experiencing some performance issues over the past week that are the cause of the Gateway Timeouts. We haven't fully resolved them but we're monitoring closely and are doing our best to clear backups quickly until we can fix. Thanks for letting us know.

As you've discovered, incomplete builds don't appear in the list of RECENT BUILDS on your main REPO page. 

Besides the UPDATES page, the best way to keep track of those is to call coveralls in verbose mode:

```
nyc report --reporter=text-lcov | coveralls -v
```

That way, you'll see the output amid your CI output indicating the current job/build ID and you can access its page by entering that into your browser (ex. https://coveralls.io/builds/31535895).

I will submit a feature request on your behalf to show and indicate unfinished builds among RECENT BUILDS.

Will follow up in #1461.
