### ISSUE TITLE
coveralls bot does not publish PR comment for private repo

### ISSUE THREAD

**Issue by nbaztec** [lemurheavy/coveralls-public#1464]
Hi,

We're trying to get the coveralls-bot to publish the report on the private PR, however so far we're only getting the status on the GitHub status report.

We have the coveralls bot as Outside Collaborator with `write` access to our private repo, and an initial PR which integrates & pushes coverage to coveralls. We're noticing that the coverage is pushed and the setting option for PR comments is enabled, yet no PR comment is posted (there is no coverage diff since this is the initial integration)

Is there something I'm missing?

**Comment by nbaztec** [comment]
The comments started coming in after a couple of merged PRs. Perhaps the initial PR isn't supposed to create a PR comment but I cannot confirm that for sure.

Closing.

**Comment by afinetooth** [comment]
@nbaztec The initial PR will post a comment, if you had previously established the the base branch as your default branch in coveralls. 

Glad to hear PR comments are coming in now, but if that stops or if you want us to have a look at the original project/builds above, just email us with the link to your coveralls project.
