### ISSUE TITLE
No PR comments on public repo

### ISSUE THREAD

**Issue by astrojuanlu** [lemurheavy/coveralls-public#1465]
We see no PR comments in this repository:

https://github.com/satellogic/quaternions/pull/31

However, it's getting updated in Coveralls:

https://coveralls.io/builds/32568322

the Coveralls application has access to the GitHub organization:

![Screenshot_2020-08-06 Build software better, together](https://user-images.githubusercontent.com/316517/89469699-4dd4e000-d77a-11ea-8b93-70cbb0714e49.png)

and I even added @coveralls as an outside collaborator with write access, even if that's only needed for private repositories (as far as I understand)

![Screenshot_2020-08-06 satellogic quaternions](https://user-images.githubusercontent.com/316517/89469599-0a7a7180-d77a-11ea-80a2-dbc94a7084df.png)

What am I missing?

**Comment by afinetooth** [comment]
Hi @astrojuanlu,

This is a known issue. Unfortunately, the access token we get for the original repo is read-only for forks. This keeps us from being able to write PR comments.

Here's some background on the issue:
https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839

Try adding @coveralls as a collaborator on your forked repo, if that's not what you've already done. (I do not know if that will work, but I can ask internally if we can make it work as a workaround for this issue.)

**Comment by afinetooth** [comment]
Hi @astrojuanlu,

Our token for the original repo's owner has rolled / expired. 

That would explain why it's stopped working, if it's worked before. 
Have you ever seen PR comments on a PR from your fork?

The owner user would have to log out and oauth back into coveralls.io. 
Are you able to communicate with them?
If not, email us at support@coveralls.io and reference this issue.

**Comment by astrojuanlu** [comment]
Will follow up by email, thanks for your quick response!

**Comment by afinetooth** [comment]
you bet. closing this issue for now.
