### ISSUE TITLE
Disable GitHub Status Checks

### ISSUE THREAD

**Issue by mxschmitt** [lemurheavy/coveralls-public#1466]
Hi,

is it possible to disable the GitHub status checks so a decreasing coverage won't result in a failing Status Check / Commit?

Best regards

Max

**Comment by afinetooth** [comment]
Hi @mxschmitt,

Yes, Status Checks is a Setting you can manage in your repo's SETTINGS page:

You can either fully disable by un-checking USE STATUS API:

![Screen Shot 2020-08-07 at 11 53 43 AM](https://user-images.githubusercontent.com/918667/89678775-a6080100-d8a4-11ea-9dfe-1e0fa6aa80f9.png)

![Screen Shot 2020-08-07 at 11 55 56 AM](https://user-images.githubusercontent.com/918667/89678960-f54e3180-d8a4-11ea-8b5b-287916b19b36.png)

Or you can leave the COVERAGE DECREASE THRESHOLD FOR FAILURE setting blank to avoid a check on decreased coverage:

![Screen Shot 2020-08-07 at 11 55 13 AM](https://user-images.githubusercontent.com/918667/89678904-db145380-d8a4-11ea-9228-4182d128cdfd.png)

![Screen Shot 2020-08-07 at 11 55 31 AM](https://user-images.githubusercontent.com/918667/89678921-e5cee880-d8a4-11ea-8547-aadecac2def6.png)
