### ISSUE TITLE
circleci build link does not link to specific workflow

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1467]
Very minor bug report:

The circleci build link on the left side does not link the specific workflow as one would assume.

https://coveralls.io/builds/32612699

![image](https://user-images.githubusercontent.com/46505081/89680379-af469d00-d8a7-11ea-8e82-536124df00f2.png)

Instead it just links to the circleci project overview https://app.circleci.com/pipelines/github/15five/fifteen5.

**Comment by afinetooth** [comment]
Thanks, @caleb15. I was able to reproduce. 

I've submitted it to our internal tracking system.

Here's an OSS project, which verifies the link goes to the CI project and not the specific build:
https://coveralls.io/builds/32019770
