### ISSUE TITLE
Pencil in delta column?

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1468]
What does the pencil in the delta column mean?

https://coveralls.io/builds/32613724

![image](https://user-images.githubusercontent.com/46505081/89681237-61329900-d8a9-11ea-8bd2-e046ddabce89.png)

**Comment by afinetooth** [comment]
Hi @caleb15, the pencil icon means there were changes to the original source files. They also appear under CHANGED, but only for files with source code changes, as opposed to coverage changes.

**Comment by caleb15** [comment]
Oh, so does the "delta" column just show whether the file was changed or not? I thought it would show the # of changes or % change as in codecov.
