### ISSUE TITLE
[question] What is the difference between "changed", "source changed", and "coverage changed"?

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1470]
The meaning of "source changed" and "coverage changed" is obvious†. But what does "changed" mean? What is the difference between "changed" and the other columns?

![image](https://user-images.githubusercontent.com/46505081/89682617-dacb8680-d8ab-11ea-9a97-411afa1cfbb2.png)

† Or at least I thought it was obvious. Now I'm not so sure. 🙈

**Comment by caleb15** [comment]
Actually, I think I get it now. "Changed" is a combination of "source changed" and "coverage changed", showing both, right?

**Comment by afinetooth** [comment]
Exactly! Thanks for your close examination. That part of our UI is in the process of an update, but I'm tracking this issue with the `documentation` label to make sure we cover details like these well in our updated docs.
