### ISSUE TITLE
[bug] wrong PR number

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1471]
Coveralls links to the wrong PR number.

![image](https://user-images.githubusercontent.com/46505081/89683959-562e3780-d8ae-11ea-9fbf-7cee3c8e1799.png)

The right number is 30344, not 19082

**Comment by caleb15** [comment]
This bug is due to a bug w/ circleci, closing:

https://discuss.circleci.com/t/circle-pull-request-env-var-incorrect/36978

**Comment by afinetooth** [comment]
thanks @caleb15.
