### ISSUE TITLE
feature request: indicate whether coverage is still being analyzed

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1472]
In https://coveralls.io/builds/32653014 I see "COVERAGE REMAINED THE SAME AT ?%" so presumably coverage is still being analyzed. This is odd because it's been 10+ minutes since the coverage was sent over, so looking at the job dequeue time (average 8 seconds) it should have completed by now. It would be nice to have a visual indicator of whether coverage is still being calculated.

**Comment by afinetooth** [comment]
@caleb15 yes, we're experiencing delays on some builds per:
https://status.coveralls.io/

We're in progress on an infrastructure upgrade to address.

In the meantime, your suggestion for a visual indicator of status for builds not-yet-completed is great and I've added it to our backlog. We would like to never see it, but when slowdowns do happen it will help. Thanks.
