### ISSUE TITLE
Coverage fell but subfolders indicate coverage rise

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1473]
![image](https://user-images.githubusercontent.com/46505081/89807738-ef975c80-daed-11ea-86b8-ade96c8ba546.png)

https://coveralls.io/builds/32632096

This seems to be a contradiction :thinking:

**Comment by afinetooth** [comment]
hi @caleb15, considering the overall stat is a roll-up of all the underlying stats per file, can you tell me how you totaled that up across your 3,237 files? The general prevalence of increase or decrease visually indicated by colors isn't necessarily a good gauge.

**Comment by caleb15** [comment]
I just looked at the colors. Are you saying that a folder might have downslid in coverage even if it shows a grey dash? I assumed that meant coverage was the exact same as before.

**Comment by afinetooth** [comment]
@caleb15 first of all, I misunderstood and was considering overall coverage. I see now that you were talking about just the `ff/` directory, and I see what you mean. 

You may have surfaced a bug, which I'd be happy to report, except that, when I compare this build to the base build (see below), I'm somewhat stuck to account for two extra files in the base branch (duplicates, but without any coverage data). 

That's compared to the PR build, in which both files exist (not in duplicate), with coverage data:

![Screen Shot 2020-08-13 at 4 59 52 PM](https://user-images.githubusercontent.com/918667/90198707-52efeb80-dd87-11ea-9d3c-cecd7b24d32c.png)

I'm now hard pressed to say for sure how I'd expect coverage to be calculated for the containing folder in that case.

I'm going to submit it as a bug and will share what I can discover about it. Thanks.

**Comment by caleb15** [comment]
Weird, not sure why there's duplicate files. Thanks for looking into it!
