### ISSUE TITLE
Codeship with multiple pipelines and parallel tests not reporting correctly most of the time

### ISSUE THREAD

**Issue by simonrentzke** [lemurheavy/coveralls-public#1476]
I'm using CodeShip, with multiple pipelines and also parallel tests.

But seem to be getting a varied set of results. It's wrong most of the time.

My setup on Simplecov is correct, as I've just moved from Codecov, which was giving accurate results.

Looking at https://docs.coveralls.io/parallel-build-webhook, doesn't seem to support Codeship, do I need to do a custom webhook on using Codeship's notification feature?

**Comment by afinetooth** [comment]
hi @simonrentzke yes, you'll need to post to our webhook, likely from within your codeship config, perhaps in an after_script hook, etc.

if you want to email us at support@coveralls.io with the URL to your coveralls project and reference this issue we'll look into it for you.

**Comment by simonrentzke** [comment]
Thanks @afinetooth I've fixed it with a Google Cloud Function being the intermediary. If anyone else needs to do this, the code looks something like this:

```node
const fetch = require('node-fetch');

exports.coveralls = async (req, res) => {
  let data;
  data = JSON.parse(req.rawBody);
  if (data.build.status == 'success') {
    coverallsResponse =
      await fetch(`https://coveralls.io/webhook.json?repo_token=${process.env.COVERALLS_REPO_TOKEN}`,
        {
          method: 'POST',
          body: JSON.stringify({
              payload: {
                build_num: data.build.build_id,
                status: 'done'
              }
          }),
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json'
          }
        }
      ).then((response) => {
        if (!response.ok) {
          console.error(`Error: Response from Coveralls was ${response.statusText}`);
        }
      }).catch((error) => {
        console.error(error.message);
      })
  }
  res.status(200).send(`Done.`);
}
```
