### ISSUE TITLE
Travis unique job id

### ISSUE THREAD

**Issue by Lucasjuv** [lemurheavy/coveralls-public#1477]
I provided the repo token and still get this error message. It has been months now we are running with coverage in the after_success block.

Will you guys ever fix this?

$HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN -coverprofile=coverage.out -service=travis-pro
`{"message":"service_job_id (375382350) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
`

**Comment by afinetooth** [comment]
Hi @Lucasjuv if you want to email us a support@coveralls.io with the link to your coveralls project, we'll look into it further for you.

Thanks,
James
