### ISSUE TITLE
SOURCE NOT AVAILABLE when Trying to View Diff

### ISSUE THREAD

**Issue by JCarmine** [lemurheavy/coveralls-public#1479]
We just installed Coveralls today, and most features are working correctly; badges, GitHub comments, etc.

However, when exploring a report, we noticed that a file had a decrease in coverage. When attempting to view the diff and figure out why, we received the following error. Actually, we receive this error for all files in the repo.

<img width="1123" alt="Screen Shot 2020-08-26 at 2 14 20 PM" src="https://user-images.githubusercontent.com/5695990/91358447-b6c2dd00-e7a7-11ea-9124-6efd76e41da1.png">

**Comment by afinetooth** [comment]
@JCarmine sorry for the delay. Looked at your project and see that digests of your source files weren't stored in our database. I'm uncertain as to the cause, but all the builds in your project happen to coincide with a time window in which we were upgrading our database infrastructure, so it's possible that's the cause. If you want to try a new build, and share the new build URL I'll be happy to look into it for you. 

I'm going to close the issue for housekeeping purposes, but feel free to comment and I'll re-open, or email us at support@coveralls.io and reference this issue. Thanks.
