### ISSUE TITLE
Status not reporting

### ISSUE THREAD

**Issue by devpow112** [lemurheavy/coveralls-public#1481]
For the last couple of days we have not been getting coveralls status reported in GitHub both on public and private repositories. An example of one is https://github.com/Brightspace/bunyan-firehose.

From within CI we get no errors when uploading the reports

![image](https://user-images.githubusercontent.com/9043211/92132333-02dbd600-edd5-11ea-9f06-b194df1e5858.png)

From the coveralls.io side we can view the reports.

https://coveralls.io/builds/33209592

`Brightspace/third-party-actions@coverallsapp/github-action` is simply a mirror (https://github.com/Brightspace/third-party-actions/tree/coverallsapp/github-action) of your repository (https://github.com/coverallsapp/github-action) and is up to date with your master `348853a262cc37fa2f8abe2827729d193cbb00dc`. Any help with this would be appreciated.

**Comment by afinetooth** [comment]
Hi @devpow112,

I doubt it's going to be this simple, but the first thing I see is that you have PR Comments turned OFF in your project settings, here:

**Comment by afinetooth** [comment]
Hi @devpow112,

Your repo is missing an owner. You will need to have someone claim it who has admin access to the repo:

https://coveralls.io/github/Brightspace/bunyan-firehose/settings:
![Screen Shot 2020-09-03 at 4 10 42 PM](https://user-images.githubusercontent.com/918667/92182231-059ff080-ee00-11ea-8364-016a1b45608e.png)

Or email us at support@coveralls.io referencing this issue and we can do it for you.

**Comment by devpow112** [comment]
But it's never been claimed and it worked until 2 days ago. As did all the others. This uses the coveralls github action that get's given the github token. Claiming this is not an option as the issue we are trying to avoid is having a single person be owner of these repo.

**Comment by devpow112** [comment]
@afinetooth but it's never been claimed and it worked until 2 days ago. As did all the others. This uses the coveralls github action that get's given a github token `${{ secrets.GITHUB_TOKEN }}`. Claiming this is not an option as the issue we are trying to avoid is having a single person be owner of these repo. This causes issues when people are removed from our organization since they no longer have access (i.e. a person leaves our company). In the past when this has happened we've had to delete and reset coveralls for all affected repositories which is a pain.

So why would this stop working all of a sudden when it had been working for weeks without an owner?

Example of PR that worked https://github.com/Brightspace/bunyan-firehose/pull/89

**Comment by afinetooth** [comment]
Hi @devpow112, sorry for the delay.

So the context in which I'm speaking about repo ownership is the coveralls context. In this context, the "owner" is the user who added the repo to coveralls. It's separate from whether members of your GH org have admin access to the repo. 

This form of ownership is normally inferred from the OAuth'd user adding a repo to coveralls via UI; and, in the case of the API, it's usually inferred from a personal access token. Some of our customers who create their repos solely via API designate a "bot" GH user that functions as a "build manager." 

The existence of a designated owner on our side is required for a number of functions, including sending status checks. Theoretically, it's possible you only engaged with features on this repo that didn't require this data up to now; but more likely, based on your explanation that the feature stopped working, I think there could have been an owner on the repo until the user account was deleted from coveralls. (It's not usually an issue if the original user leaves your organization or loses access to the given repo, as long as they had it when it was created.)

When I started looking at your other projects, I only saw repos with owners, for instance:

- https://coveralls.io/github/Brightspace/insights-self-serve-reporting
- https://coveralls.io/github/Brightspace/assigned-i9o-service
- https://coveralls.io/github/Brightspace/learning-groups-service

Hoping you wouldn't mind, I took the liberty of assigning your GH user ownership of the [brightspace/bunyan-firehose](https://coveralls.io/github/Brightspace/bunyan-firehose) repo in our system. This should re-establish basic functionality. It's not something that would risk you having to delete and reset your project(s); instead, if you see the offending behavior again, such as missing status checks, let us know and we'll examine for root causes like this.

**Comment by devpow112** [comment]
Thanks @afinetooth for the thorough explanation/help. Jut for my clarity in the case where if I was to leave the Brightspace org and no longer be associated with it what would happen? Would the status checks stop working again since my github user no longer had write access to that repo in github? I'm just curious if this is the case as this is what we thought we had observed before. I'm assuming yes hence why you mention the idea of a "bot" user to have ownership.
