### ISSUE TITLE
Provide documentation of GitHub integration step

### ISSUE THREAD

**Issue by TravisCarden** [lemurheavy/coveralls-public#1482]
I maintain an open source testing framework that runs PHPUnit tests for its users, generates code coverage, and sends it to Coveralls for them. All they need to do is connect their GitHub account to Coveralls and enable the integration on the appropriate repository. And I would like to link to official documentation covering this step. But the closest thing I could find anywhere was [this page on docs.travis-ci.com](https://docs.travis-ci.com/user/coveralls/), and even it is [buried do deep in the page content](https://docs.travis-ci.com/user/coveralls/#1-add-your-repository-to-coveralls) that it would be confusing to my users. Can there be a documentation page or a FAQ devoted to the mere process of getting a GitHub repository set up and integrated with Coveralls _in isolation_, i.e., without including a bunch of language-specific or low-level details like code APIs? It would be super helpful. Thanks!!

**Comment by thenineteen** [comment]
Does this help? The documentation does seem to be buried

- python: https://coveralls-python.readthedocs.io/en/latest/

- others: https://docs.coveralls.io

**Comment by TravisCarden** [comment]
Thanks, @thenineteen. That's still buried in too much language-specific code-side detail. Here's what I ended up doing: https://github.com/acquia/orca/blob/v2.10.0/docs/faq.md#coveralls.

**Comment by afinetooth** [comment]
Hi @TravisCarden. Sorry for the delay. We're in process on new documentation. It looks like you've covered it well, and succinctly, but if it helps you can use this copy excerpted from draft:

(Thanks for the assist, @thenineteen.)

---

### Add your project to Coveralls

To add your repo to [Coveralls](https://coveralls.io/sign-in), go to [http://coveralls.io/sign-in](http://coveralls.io/sign-in) and Sign In with GitHub:

![coveralls-sign-in](https://user-images.githubusercontent.com/918667/93146354-71f1de00-f6a3-11ea-82f6-8d4d9ac76495.png)

Upon first sign-in, you won’t have any active repos, so go to **Add Repos** and find a list of your public repos:

![coveralls-add-repo](https://user-images.githubusercontent.com/918667/93146395-8cc45280-f6a3-11ea-8e4a-47f602e6e015.png)

To add your repo, simply click the Toggle control next to your repo name, switching it to **ON**:

![coveralls-add-repo-turn-on](https://user-images.githubusercontent.com/918667/93146423-a36aa980-f6a3-11ea-987a-6625b23e4f77.png)

Great! Coveralls is now tracking your repo.

---

**Comment by TravisCarden** [comment]
Nice, thanks, @afinetooth!
