### ISSUE TITLE
Coveralls seems reports correct coverage on folders but has incorrect total

### ISSUE THREAD

**Issue by sam-enough** [lemurheavy/coveralls-public#1484]
This build: https://coveralls.io/builds/33273141

Is showing overall coverage of 82.68%, based on tracking coverage within 3 folders:
 - 93.76 app/
 - 85.35 lib/
 - 92.54 products/

Mathematically this cannot be correct.

Notably this build is a PR which is not changing any source files, branched from a master commit reporting 89% coverage (which also reports the same coverage as above for each of the tracked folders).

Also notably, same behaviour is not seen on all branches.

![image](https://user-images.githubusercontent.com/34237485/92384576-3afe5400-f108-11ea-8351-59f9d1a70bb6.png)

**Comment by afinetooth** [comment]
HI @sam-enough, taking this up with you via email, but will report our findings back here for reference. Thanks.
