### ISSUE TITLE
Make it clear what is meant by "Free for open source"

### ISSUE THREAD

**Issue by Zephilinox** [lemurheavy/coveralls-public#1485]
I wasn't able to find any expansion on this on the website. It's not clear if this is referring to being limited to things that are Open Source (OSI licenses), source-available (e.g. gitlab enterprise license, polyform non-commercial) or any publicly viewable repo (including those that lack licenses and/or explicitly reserve all rights)

I did see https://github.com/lemurheavy/coveralls-public/issues/747 but it's still unclear

**Comment by afinetooth** [comment]
Hi @Zephilinox, the response to #747 still applies. We don't look into the licensing models of individual repos. For our purposes, an "open source" repo is a repo that public on its given SCM. 

Thank you for the good suggestion though, its helpful. We've added a new answer to our FAQ, which will appear there in a day or two.

**Comment by Zephilinox** [comment]
awesome, thanks for clarifying :)
