### ISSUE TITLE
Coverage seems to be wrong

### ISSUE THREAD

**Issue by LostInDarkMath** [lemurheavy/coveralls-public#1489]
Hi there, 
please have a look at this: https://coveralls.io/builds/33694799

The coverage at the bottom tells `100.0 %` but at the top is stated `coverage decreased (-0.2%) to 99.818%`. This is very confusing to me. It also says ` 548 of 549 relevant lines covered (99.82%) `, but I'm unable to find that one missed line.

I think this behavior is a bug, isn't it?

**Comment by afinetooth** [comment]
Hi @LostInDarkMath,

I re-ran the jobs in your parallel build in a manner that blocked the overall coverage calculation until all six (6) jobs were able to complete. This seems to have fixed the issue:

https://coveralls.io/builds/33694799

![Screen Shot 2020-09-24 at 5 10 47 PM](https://user-images.githubusercontent.com/918667/94212388-e50c0900-fe88-11ea-8768-b810cd41f20a.png)

This can happen when incoming jobs (POSTs to https://coveralls.io/api/jobs) aren't recognized as parallel. I checked the build in our db and it wasn't recognized as parallel, so I then checked [your CI config at Travis](https://travis-ci.com/github/LostInDarkMath/pedantic-python-decorators/builds/186463881/config) and noticed it's not set up for parallel builds, per instructions here:
https://docs.coveralls.io/parallel-build-webhook

Here's the `.travis.yml` for a sample project that was created to demonstrate parallel builds:
https://github.com/coverallsapp/coveralls-node-demo/blob/master/.travis.yml

If you add the global env var `COVERALLS_PARALLEL=true` and call our parallel builds webhook at the end, under `notifications:`, you should be able to avoid this particular issue going forward.
