### ISSUE TITLE
coverage badge for gitlab is not located in readme

### ISSUE THREAD

**Issue by BishopWolf** [lemurheavy/coveralls-public#1490]
In gitlab you have the badge section in your configuration where your define your badges. You certainly don't need to add it to your readme. However you are expecting it to be there

**Comment by afinetooth** [comment]
Hi @BishopWolf,

Thanks for the heads up on badges in Gitlab.

I read up on the [Gitlab feature](https://gitlab.com/help/user/project/badges) and submitted a feature request to our backlog to more easily add badges to Gitlab repos.

On a scale from 1-10, how much of an effect does this have on your workflow? 
(Where: 1 = minor annoyance; 10 = blocker)

**Comment by BishopWolf** [comment]
This has quite effect on my workflow, I would say 1.

**Comment by afinetooth** [comment]
Ok, thank you. Will note it.
