### ISSUE TITLE
500 when trying to download an invoice

### ISSUE THREAD

**Issue by joseairosa** [lemurheavy/coveralls-public#1494]
Hi there!

When trying to download any of our invoices I'm getting a 500 error.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/288866/96017312-c5418280-0e41-11eb-9a07-47c2611b35df.png">

Anyone experiencing the same?

**Comment by afinetooth** [comment]
Hi @joseairosa, this should be fixed now. Thanks.

**Comment by electblake** [comment]
Happening again +1

**Comment by afinetooth** [comment]
@electblake still now? Can you please share the Coveralls URL to your project? I can't reproduce.

**Update**:
I can provide a workaround if you, or someone on your team, has access to your subscription email. Let me know.

Finally, if you have a subscription you can always email us directly for faster support at support@coveralls.io.
