### ISSUE TITLE
UI bug: notification enabled button is partially displayed

### ISSUE THREAD

**Issue by Jarvie8176** [lemurheavy/coveralls-public#1495]
I was trying to debug why coveralls couldn't send notification to slack, turned out there is a button displayed as "ABLED" that can toggle the integration.

![image](https://user-images.githubusercontent.com/3547456/96407388-45a01480-11af-11eb-925e-62b9b584821e.png)

Looks like the UI layout is broken and makes this button hard to find. I tested with Chrome and Edge, both browsers have the same symptom.

**Comment by afinetooth** [comment]
Thanks, @Jarvie8176. Reproduced and reported. Will update you with changes.
