### ISSUE TITLE
500 "Build processing error" from GitLab

### ISSUE THREAD

**Issue by dmfay** [lemurheavy/coveralls-public#1496]
Coveralls has been working fine from GitLab for a long time, but the first couple of builds I've had in a month or so have failed to upload coverage results.

[GitLab pipeline here](https://gitlab.com/dmfay/massive-js/-/jobs/800115581)

```
> nyc report --reporter=text-lcov | coveralls
/builds/dmfay/massive-js/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
```

**Comment by afinetooth** [comment]
Hi @dmfay so that we can get more insight into what you're sending to the coveralls API can you please re-run in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v)? If you're using the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration, you should be able to add the `-v` or `--verbose` flag to `coveralls`. If that doesn't work, try setting this environment variable in CI: `NODE_COVERALLS_DEBUG` = `1`.

**Comment by dmfay** [comment]
Sure, [here's a pipeline](https://gitlab.com/dmfay/massive-js/-/jobs/810117047) run in verbose mode.

**Comment by Alir3z4** [comment]
Same problem but using Python module.
Any update on this ?

**Comment by afinetooth** [comment]
Still investigating this one @dmfay @Alir3z4 . Will update asap.

**Comment by kolychev** [comment]
Having same issue with gitlab and github repos. I have simplified report as much as possible. Here is how I sent it:
curl -v -F json_file=@build/coveralls/report.json https://coveralls.io/api/v1/jobs
And the content of report.json is:

```
{
    "git": {
        "head": {
            "id": "99c8248ae2420bdfca9885d41818b1653ade2d48",
            "author_name": "Oleg Kolychev",
            "author_email": "oleg@softservice.org",
            "committer_name": "Oleg Kolychev",
            "committer_email": "oleg@softservice.org",
            "message": "Switch to codecov"
        },
        "branch": "master",
        "remotes": [
            {
                "name": "github",
                "url": "git@github.com:kolychev/coveralls-demo.git"
            }
        ]
    },
    "repo_token": "Q57cMafV0cZeeFcQAx8ApliZ4R6SYm0Xj",
    "service_name": "other",
    "source_files": [
        {
            "coverage": [
                null,
                null,
                null,
                null,
                null,
                null,
                1,
                null,
                null,
                null,
                null,
                null,
                null,
                1,
                1,
                null,
                0,
                null,
                1,
                null,
                null,
                0,
                0,
                null
            ],
            "source_digest": "ba45425de89355d398133932b8fbb03b",
            "name": "src/main/java/com/example/demo/TestServiceImpl.java"
        }
    ]
}
```
