### ISSUE TITLE
Coveralls change to double slash and can't find source

### ISSUE THREAD

**Issue by michal-shitrit** [lemurheavy/coveralls-public#1497]
Using Maven project, Coveralls picks up the coverage report correctly but I can't view the source, see double slash in the path:

![image](https://user-images.githubusercontent.com/18466507/97184994-353bfb00-17a8-11eb-9455-adc213836aad.png)
 
tree indicates on double directory of Java:

![image](https://user-images.githubusercontent.com/18466507/97185525-d2972f00-17a8-11eb-841d-1e413f310efd.png)

Don't see any indication for this in the source:

![image](https://user-images.githubusercontent.com/18466507/97185668-02463700-17a9-11eb-8bd6-dee2b54a8b0b.png)

**Comment by afinetooth** [comment]
Hi @michal-shitrit, based on what we have stored in our database, I believe those filenames were passed to our API with the extra forward slash.

We can verify what's being POSTed to coveralls API if you won't mind running a new build in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v).

I'm not familiar enough with the maven plugin to instruct you on exactly how to do that, but [this comment by the plugin's creator](https://github.com/trautonen/coveralls-maven-plugin/issues/38#issuecomment-52691142) indicates you can run the build with the `-X` flag to see verbose info.

> Could you at least add the full maven output to the issue and for debugging you could run the build with -X flag to see verbose information.

If you would please share the full maven output I suspect we'll be able to see how those filenames look in the POST body.

**Comment by michal-shitrit** [comment]
Thank you very much for the quick response, here is the full log:
I also attached jacoco folder from my local build if this might help. 


[full trace.txt](https://github.com/lemurheavy/coveralls-public/files/5457541/full.trace.txt)
[jacoco.zip](https://github.com/lemurheavy/coveralls-public/files/5457552/jacoco.zip)

**Comment by afinetooth** [comment]
hi @michal-shitrit,

Yes, as you can see here, the JSON you are passing contains filenames with the double slashes:

![Screen Shot 2020-10-31 at 8 17 46 PM](https://user-images.githubusercontent.com/918667/97794383-74a68500-1bb6-11eb-96d0-09ae33e2c9c0.png)

If you can correct that on your end, the POST should work and the source files should resolve for you.

**Comment by michal-shitrit** [comment]
Thank you @afinetooth  will see how to fix that!
