### ISSUE TITLE
404 on file Coverage

### ISSUE THREAD

**Issue by CraigChamberlain** [lemurheavy/coveralls-public#1498]
Same issue as https://github.com/lemurheavy/coveralls-public/issues/1418

Here is an example url

https://coveralls.io/builds/34653504/source?filename=C#/SolarLunarName/SolarLunarName.SharedTypes/Constants/Ranges.cs

I tried a few different base URL as this seems to effect the filename.

**Comment by afinetooth** [comment]
@CraigChamberlain can you please run a new build in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) and share the debug output? I'd like to see what you're sending to the coveralls API.

Notice that while browsing files in the build (Build 0):
https://coveralls.io/builds/34653504

You get the 404 error:
https://coveralls.io/builds/34653504/source?filename=C#/SolarLunarName/SolarLunarName.SharedTypes/Constants/Ranges.cs

But while browsing files in the build's one child job (Build 0, Job 1):
https://coveralls.io/jobs/70095719

The files display fine, albeit with a different URL scheme:
https://coveralls.io/jobs/70095719/source_files/3324284906

However, they also display in duplicate:

![Screen Shot 2020-11-02 at 7 28 36 PM](https://user-images.githubusercontent.com/918667/97947275-9c762400-1d41-11eb-94cd-fbe450a00223.png)
 
The differing behavior for the different URL schemes makes me think we're sensitive to the `#` character, which should have been encoded on incoming JSON. (That said, I don't see a related error in logs.)

The duplicate files in the job make me think the issue starts with the incoming JSON.

Therefore the best help to diagnose would be to see the JSON you're sending to the API.

**Comment by CraigChamberlain** [comment]
OK Thanks I'll look at verbose mode today.  About the duplication, this is
when I was just uploading one of two tests before I worked out how to
combine them.  I would delete this record if there was a way I could see.

I see what you mean about C# i was considering renaming that to src as I'm
unlikely to do any work outside of .NET as I originally intended.

C

**Comment by CraigChamberlain** [comment]
The -v option does not seem to be supported by my CLI but I've had another
go with relative paths to see if it skips the entire github repo structure
and starts at my PWD instead.

csmacnz.Coveralls (--opencover | --dynamiccodecoverage | --monocov |
--exportcodecoverage | --chutzpah | --lcov | --ncover | --reportgenerator |
--multiple) -i ./opencovertests.xml (--repoToken <repoToken> |
[--repoTokenVariable <repoTokenVariable>]) [-o ./opencovertests.json]
[--dryrun] [--useRelativePaths [--basePath <path>] ] [--commitId <commitId>
--commitBranch <commitBranch> [--commitAuthor <commitAuthor> --commitEmail
<commitEmail> --commitMessage <commitMessage>] ] [--jobId <jobId>]
[--serviceName <Name>] [--serviceNumber <Number>] [--pullRequest
<pullRequestId>] [--treatUploadErrorsAsWarnings] [--parallel]
  csmacnz.Coveralls --version
  csmacnz.Coveralls --help

**Comment by CraigChamberlain** [comment]
So I deleted the other builds as they were in a funny state.  I just tried
with relative path so no c#

This gives source not available:
https://coveralls.io/builds/34673456/source?filename=/SolarLunarName.SharedTypes/Constants/Ranges.cs

But the following is OK.
https://coveralls.io/builds/34673456/source?filename=/C%23/SolarLunarName/SolarLunarName.SharedTypes/Constants/Ranges.cs

Anyway I went ahead and just renamed the C# file src and it sorted itself
out.  I have an issue on coveralls.net now -https://github.com/csMACnz/coveralls.net/issues/100 as I think the baseUrl parameter isn't working nicely, but it looks like this can be set globally for the
repo anyway.

**Comment by afinetooth** [comment]
HI @CraigChamberlain. It looks like the builds associated with those example URLs are gone now. I'll assume you're good per:
> Anyway I went ahead and just renamed the C# file src and it sorted itself

But I'll submit this as a potential issue to see if we failed to carry over the encoding of `#` while building one of our source file links.

Thanks for submitting the `basePath` issue to the [coveralls.net](https://github.com/csmacnz/coveralls.net) project. Happy to help with any questions on that from our side of the fence.

Closing for now. Leave a comment if you need follow-up.

**Comment by CraigChamberlain** [comment]
Hi I closed the baseUrl issue as I think I had the wrong expectations.
https://github.com/csMACnz/coveralls.net/issues/100

However, I've opened an issue about the url encoding.  Not sure if it should be done in the client or by the receiver.
https://github.com/csMACnz/coveralls.net/issues/101

**Comment by CraigChamberlain** [comment]
Hi @afinetooth so I started looking at handling uri encoding in the .net core app but I started to think responsiblity for encoding probably should be with coveralls.io if it passed to your service as a file path.  A file path does not need the same encoding as a URL. 

Have you a specification for the payload your api excepts?

**Comment by CraigChamberlain** [comment]
https://docs.coveralls.io/api-reference

Looks like a file path.

name | StringREQUIREDRepresents the file path of this source file. Must be unique in the job. Can include slashes. The file type for syntax highlighting will be determined from the file extension in this parameter.
-- | --
