### ISSUE TITLE
travis-ci-com migration

### ISSUE THREAD

**Issue by vtjnash** [lemurheavy/coveralls-public#1500]
I noticed the job links in https://coveralls.io/builds/34894031 are pointing to .org instead of .com, though it recognizes the job has migrated to now run on .com. That's slowly changing (https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/)

**Comment by afinetooth** [comment]
Hi @vtjnash, I think adding a `.coveralls.yml` file to the base directory of [your repo](https://github.com/JuliaCI/Coverage.jl) should solve the issues you're having.

Per this [common issue](https://docs.coveralls.io/troubleshooting#i-see-random-commits-on-my-travis-pro-private-repo), you'll want to add at least this line:

> service_name: travis-pro

**Comment by vtjnash** [comment]
I've run the build with service_name = travis-pro, travis-ci, and travis-ci-com, and all have the wrong web link. Here's the one where I set travis-pro: https://coveralls.io/builds/34893491

**Comment by vtjnash** [comment]
I guess this won't be fixed, but I switched to GitHub Actions anyways

**Comment by afinetooth** [comment]
Hi, @vtjnash. Sorry I missed your post in Nov 2020. That link is built from looking at your repo, which retained the old travis host (.org). If you happen to migrate back to travis, let us know and we can address it.
