### ISSUE TITLE
Scary fascist 403 forbidden page?

### ISSUE THREAD

**Issue by moriah-rahamim** [lemurheavy/coveralls-public#1503]
I just tried opening a coveralls link on a repo I'm a part of, and landed (due to a 403 error) on a red page with an image of what looks to me like a fascist Schutzstaffel officer (or any police officer) pointing at me, with "You there, halt!"

I'm sure this is intended to be lighthearted -- but as a user I'm being asked to imagine I am being stopped/pointed at by the police, and this leaves me with no interest in logging in to actually see what's on the page I was originally trying to go to. Not sure how often people actually hit the 403 forbidden page, but I'd really recommend you change out this image/language. Folks have *drastically* different feelings about and interactions with the police (including many being genuinely afraid of encountering police brutality in their day to day lives), and it's not hard for an image and wording like that to seriously miss the mark in terms of tone.

Thanks in advance!

For reference, this is the page I landed on:
![Screen Shot 2020-11-17 at 1 07 51 PM](https://user-images.githubusercontent.com/30762282/99451236-c3eaf600-28d6-11eb-932f-23422d3d340c.png)

**Comment by moriah-rahamim** [comment]
To follow up -- After poking around I'm seeing that this kind of imagery pops up elsewhere on the Coveralls site, like on the [Careers page](https://coveralls.io/careers):
![image](https://user-images.githubusercontent.com/30762282/99454871-e16e8e80-28db-11eb-8ef7-8dcba8894340.png)

I can see how this is part of a military brand-theme, but truly from an inclusivity perspective this picture makes me want to run in the other direction, as a person for whom police imagery feels threatening. I think this sort of thing is worth evaluating broadly if it appears elsewhere, to avoid ostracizing diverse customers (and talent).

**Comment by afinetooth** [comment]
hi @moriah-rahamim, thanks for the input. Points understood and well-taken. We've had similar feedback and in response we're in progress on a design update that retires the old theme which was created back in 2010/11. 

FWIW, the original theme certainly was conceived, in fun, as a tongue-in-cheek send-up of 20th century propaganda with the point of poking fun at ourselves for having, to the uninitiated, an overblown sense of urgency about the danger of bugs in your codebase (vis-à-vis _uncovered code!_). 

Sadly, things have changed enough in the past ten years to make making fun of fascism and the fight against it a lot less funny and, as we've grown to reach more users, less inclusive, which was certainly never our intent.

That exact image on our access denied page, BTW, comes from [this WW1 British military recruitment](https://images.app.goo.gl/rKgAfokFqjC3m42M9) poster.

I don't have an exact date for release of our new design, but I know it's on target for early 2021.

Thanks again for the feedback.

**Comment by moriah-rahamim** [comment]
@afinetooth Thanks for the update! I'm glad to hear you're already working on it and appreciate the context 👍
