### ISSUE TITLE
allow adjusting thresholds

### ISSUE THREAD

**Issue by Licenser** [lemurheavy/coveralls-public#1506]
Hi,
it would be great to be able to specify the thresholds for badges. The defaults given are great defaults, but they're just that in the end, defaults. As a maintainer it feels wrong to that a tool dictates what I got to consider good, bad, or acceptable for my codebase.

**Comment by afinetooth** [comment]
hi @Licenser not sure what you mean here, can you please elaborate? we provide two (2) threshold settings for each repo:

- COVERAGE THRESHOLD FOR FAILURE
- COVERAGE DECREASE THRESHOLD FOR FAILURE

these apply to PR checks and determine whether they pass based on overall coverage % (or individual flagged/named check).

not sure how this would affect the badge as the badge merely reflects the current coverage on the repo's default branch. Thanks.

**Comment by Licenser** [comment]
Heya thanks for the quick answer,
the desire is to change the thresholds for bad / ok / good (red, orange, green) for the badge :)

**Comment by afinetooth** [comment]
Hi @Licenser, ah, I see. Not possible now but it's a good recommendation. I have added it as a feature request to our backlog. Thanks.
