### ISSUE TITLE
Unable to open source file in the tree view if the path contains “+” character

### ISSUE THREAD

**Issue by EFanZh** [lemurheavy/coveralls-public#1511]
I think it is because the JavaScript in the page doesn’t escape the path before building the result URL. Maybe it could be fixed like this:

```diff
  (function() {
    $(function() {
      var $tree;
      $tree = $('#tree').tree({
        autoEscape: false,
        useContextMenu: false,
        selectable: false,
        saveState: "BuildDecorator/35841708",
        onCreateLi: (function(_this) {
          return function(node, li) {
            var el, klass, name;
            el = li.find('.jqtree-title');
            name = node.data.name;
            klass = node.data.dir ? (name += "/", 'dirname') : 'filename';
            el.append($("<span class='tree-" + klass + "'>" + name + "</span>"));
            return el.prepend(node.data.badge);
          };
        })(this),
        onLoading: function(is_loading, node, el) {
          if (is_loading) {
            return el.find('.jqtree-toggler').html($("<img/>", {
              src: '/assets/loading.gif',
              style: 'height:15px; width:12px'
            }));
          }
        }
      }).bind('tree.click', function(e) {
        var is_job;
        if (!(e.node.load_on_demand || e.node.children.length > 0)) {
          is_job = false;
-         return window.location = is_job ? "/jobs/35841708/source_files/" + e.node.data.id : "/builds/35841708/source?filename=" + e.node.data.path;
+         return window.location = is_job ? "/jobs/35841708/source_files/" + e.node.data.id : "/builds/35841708/source?filename=" + encodeURIComponent(e.node.data.path);
        } else {
          return $tree.tree('toggle', e.node);
        }
      });
      return window.tree = $tree;
    });
  
  }).call(this);
```

**Comment by afinetooth** [comment]
@EFanZh can you please share your example with your project files? I have modified a local copy of source with your changes and tested against files with "+" in the pathnames. I am not seeing a difference, so I would like to reference your specific use case to make sure I'm not missing something.

**Comment by EFanZh** [comment]
See <https://coveralls.io/github/EFanZh/LeetCode?branch=master>. In the “TREE” tab, click on any file name under the “c++” directory leads to a 404 error.

The URL it tries to open is something like: <https://coveralls.io/builds/35977561/source?filename=c++/include/leet-code/data-structures/list-node.h>.

But the correct URL should be something like: <https://coveralls.io/builds/35977561/source?filename=c%2B%2B%2Finclude%2Fleet-code%2Fdata-structures%2Flist-node.h>.

**Comment by afinetooth** [comment]
@EFanZh great, this is helpful. I only tested filenames and forgot to test directory names. Your suggestion worked, so I  submitted a PR and am waiting for approval. 

Look for a fix in the next few days, but I'll update you here when released. Thanks.

**Comment by paulz** [comment]
we have same issue opening files with + in the name.

If we substitute broken link with `%2B` we are able to open it.

Here is example of our private repo project: https://coveralls.io/builds/36280198/source?filename=Testable/Array+Calculations.swift

which should be https://coveralls.io/builds/36280198/source?filename=Testable/Array%2BCalculations.swift

the broken link is on this page: https://coveralls.io/builds/36280198

**Comment by paulz** [comment]
we have same issue opening files with + in the name.

If we substitute broken link with `%2B` we are able to open it.

Here is example of our private repo project: https://coveralls.io/builds/36280198/source?filename=Testable/Array+Calculations.swift

which should be https://coveralls.io/builds/36280198/source?filename=Testable/Array%2BCalculations.swift

the broken link is on this page: https://coveralls.io/builds/36280198

**Comment by afinetooth** [comment]
@paulz yes, my PR hasn't been accepted yet. Sorry for the delay. I'll follow up on my side and feed back asap.

**Comment by afinetooth** [comment]
@paulz that's been merged and deployed. Look for it the next chance you get and let me know if it doesn't resolve your issue.

**Comment by paulz** [comment]
Thank you so much!

Works great and was perfect timing for the demo we did for our engineers.

**Comment by afinetooth** [comment]
Perfect. Glad to hear it. Going to close the issue. Just comment if nec to re-open.
