### ISSUE TITLE
CircleCI job link contains typo "com.com"

### ISSUE THREAD

**Issue by joeboyscout04** [lemurheavy/coveralls-public#1517]
Looks like there is a typo in the job link to CircleCI.  

<img width="1139" alt="Screen Shot 2021-01-20 at 10 00 31 AM" src="https://user-images.githubusercontent.com/1489809/105151665-812be100-5b06-11eb-8e37-146cff3508ed.png">

When I tap the "CircleCI Job" button, it links to: 
https://circleci.com.com/gh/fishbrain/iPhone/

The error is the inclusion of `com.com` in the URL.

**Comment by afinetooth** [comment]
thanks @joeboyscout04. reproduced and fix is in a PR. please give it a few days.

**Comment by afinetooth** [comment]
should be fixed now. lmk if not. closing the issue for now.
