### ISSUE TITLE
Build for specific PR does not send to coveralls

### ISSUE THREAD

**Issue by michal-shitrit** [lemurheavy/coveralls-public#1523]
I have Coveralls working with few repositories, for one of them - not always the PR shows up in coveralls, it is happening from time to time and usually "fixed" by  itself after few days.

can you please help?

This is a private repository so I don't want to send the links publicly

**Comment by Licenser** [comment]
We're seeing the same issue it's on a public repo so we can share details, perhaps that helps:

https://github.com/tremor-rs/tremor-runtime/pull/729/checks?check_run_id=1817173427

is one of the failing builds it also shows up in coveralls but it does fail with a 500 when clicking on it: https://coveralls.io/builds/36803106

**Comment by afinetooth** [comment]
@michal-shitrit @Licenser, we had an issues that affected performance for a short time this afternoon, as well as a longer [incident](https://status.coveralls.io/incidents/0v43zd9zvxjn) that occurred over several days last week. 

Either of those could have affected your recent builds based on description, but both are resolved now, so if your issues have not also resolved, please reply back here.

@michal-shitrit, please feel free to email support@coveralls.io and reference this issue. You can share your project URL there safely.

@Licenser the [build you referenced](https://coveralls.io/builds/36803106) now looks good:
