### ISSUE TITLE
Unable to view personal private repo coverage results

### ISSUE THREAD

**Issue by awadell1** [lemurheavy/coveralls-public#1526]
Hi,

I have commit access to a user private Github repository, but I can't access the coverage reports on coveralls.io.

The reports do exist (They're able to navigate to them), but I get the "You there, halt!" page instead.

Do I need a different set of permissions to access it?

Best,

Alex

**Comment by afinetooth** [comment]
@awadell1 yes, sounds like you need to OAuth into Coveralls with private scope enabled.

To do that, go to your ADD REPOS page (https://coveralls.io/repos/new), and click the REFRESH PRIVATE REPOS button.

**Comment by awadell1** [comment]
@afinetooth Thank you for the fast response!

I have clicked "REFRESH PRIVATE REPOS" on the following:
- https://coveralls.io/repos/new
- https://coveralls.io/repos/new?name=mguttenb&service=github

I've also clicked "SYNC REPOS" on both pages. I'm not seeing their repo show up, and I'm still getting the "You, Hault" message.

Best,

Alex

**Comment by afinetooth** [comment]
@awadell1 ok, since you're talking about a private repo, can you please email the coveralls URL to support@coveralls.io and reference this issue? I'll get it and feedback on whether it looks like you have access. Here now, so email when you can.

**Comment by afinetooth** [comment]
@awadell1 I took a guess at the repo and if I have the right one it looks like original creator no longer has a link to the project through their original github account (Is it possible they re-named their account?). Please ask that person to log into https://coveralls.io, go to their account page (https://coveralls.io/account) and UNLINK their account; then re-login through Github. If they can't access the repo after that, they'll need to email us. Closing for now.
