### ISSUE TITLE
Coveralls not updating with github action

### ISSUE THREAD

**Issue by LastTalon** [lemurheavy/coveralls-public#1532]
When using the github action nothing seems to happen on coveralls.io. This same step worked normally on a previous run. It appears to be finding the file correctly, but there is no build on coveralls.io and no coveralls check shows up that is normally created by the action either.

https://github.com/IsoLogicGames/Monolith/pull/36/checks?check_run_id=1983180345#step:8:9

**Comment by afinetooth** [comment]
@LastTalon I'm seeing a build associated with that GH Action run:
https://coveralls.io/builds/37462476

You've had three (3) builds against the project related to PR #36:

- https://coveralls.io/builds/37462476
- https://coveralls.io/builds/37462379
- https://coveralls.io/builds/37462269

The last two builds were both associated with the same (successful) run and have the same build number: 600939731.

Am I missing something?

**Comment by LastTalon** [comment]
I do not see this build, where are you seeing it?

What I see from https://coveralls.io/github/LastTalon/Monolith today's builds are not included.
![](https://puu.sh/HkcfD/32f5d4033c.png)

From https://coveralls.io/repos/322006/builds
![](https://puu.sh/Hkcj6/f4cb6d9843.png)

**Comment by LastTalon** [comment]
It seems that coveralls had lost track of the repo when I moved it to IsoLogicGames. Those builds belong to IsoLogicGames/Monolith and coveralls hasn't realized they're the same repo.

I can work with this as it is.

**Comment by afinetooth** [comment]
@LastTalon, I see. Yes, repos are identified by the combo of `user_or_org/reponame`. Per our [API docs](https://coveralls.io/api/docs) that defines the endpoint, for instance:

```
GET /api/repos/:service/:repo_user/:repo_name
```

Moving a repo to another organization is effectively the same as creating a new one. That said, I can try renaming the current repo for you to see if we can preserve the history. There's some confidence it will work, but if not we can roll back. If you want to do that, please email support@coveralls.io and reference this issue.

**Comment by LastTalon** [comment]
Thanks for the offer, I'm not worried about it though. This is all in early development still. Good to know.

**Comment by afinetooth** [comment]
@LastTalon sounds good. Good luck.
