### ISSUE TITLE
Gitlab public repo won't work without token

### ISSUE THREAD

**Issue by mcelicalderon** [lemurheavy/coveralls-public#1534]
Hi! 

I just setup coveralls for a public repo using Gitlab CI. It didn't work out of the box like Travis with public repos, was getting this error
```
Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Couldn't find a repository matching this job.
```
I tried a couple of things but finally setting `repo_token` on the `.coveralls.yml` file made it work. My only concern is that this is a public repo so the token is public too. Of course I can hide the token using a masked variable in Gitlab CI, but was wondering if there's a better way to make it work without providing the token at all as the repo is public.

Any information is appreciated, thanks!

PD: In case it's of any use, this is the repo https://github.com/graphql-devise/graphql_devise/pull/159 hosted in github, but CI is running on Gitlab. Already regenerated the coveralls token just in case it was not supposed to be exposed.

**Comment by afinetooth** [comment]
@mcelicalderon the safest way to add your repo token is set the Gitlab CI env var, `COVERALLS_REPO_TOKEN`, in **Settings > CI/CD > Variables**.

Not sure why the `repo_token` was required to make your private repo work, but we are moving toward that always being a requirement so it's never a bad move to include it. I would just protect it by using a CI env var.

As regards your coveralls repo being public:
https://coveralls.io/gitlab/graphql-devise/graphql_devise

The `repo_token` is hidden there from users who aren't collaborators on the repo. As is settings, so it remains private in that sense.

**Comment by mcelicalderon** [comment]
Thank you @afinetooth! I will make that change 👍 

Saw you added some documentation tags, so not sure if you want to keep this one open, but your answer pretty much solves my issue. But yes, docs can definitively give a little more detail on how to setup with gitlab.

**Comment by afinetooth** [comment]
@mcelicalderon great. Glad it helped.

We're doing a major update on our documentation due in the next few months. The `documentation` tag is just a reminder to sweep for issues that could be covered in docs (open or closed), which this one could. 

We're working on our Supported CI docs now, so thanks for the input.

Will close for now.
