### ISSUE TITLE
Carry forward of skipped jobs?

### ISSUE THREAD

**Issue by tgolsson** [lemurheavy/coveralls-public#1536]
Hello!

I've scoured the documentation but can't find any relevant info. I'm managing a repository which consists of multiple modules that depend on each other. To save CI time and minimize noise we track what content has been built/tested and generate a minimal rebuild set that's consistent across time.

For example, let's pretend we have two project, A and B. B depends on A. With this setup, B will run if *either* A or B changed, but A only runs if its own content changed. Due to how we manage our code, it  oftentimes also makes sense to test A's API surface from B, instead of mocking a consumer in A. This means that if we don't run ProjectB's tests, our coverage of A will decrease.

I'm wondering if coveralls has a feature somewhere which would let me "carry forward" test suites that did not run.

**Comment by afinetooth** [comment]
Hi, @tgolsson, question: By "modules" do you mean your repo is composed of literal [git submodules](https://git-scm.com/docs/gitsubmodules)?

I'm afraid we don't currently have a feature equivalent to [carryforward flags](https://docs.codecov.io/docs/carryforward-flags), but depending on how your project is organized we might be able to suggest a couple of different approaches to accomplish what you want.

**Comment by tgolsson** [comment]
Hi @afinetooth!

No, it's modules as in logical groupings of code. It's all one repo, but a bit on the monorepo-ish side hence why we don't test everything all the time. I guess in short form; my questions is really:

> If we don't run all tests on every commit, what does coveralls offer to help us make our coverage comparable over time?

I hope that is clearer!

**Comment by afinetooth** [comment]
@tgolsson ok, understood.

So the behavior on our side is that we expect all coverage reports to be sent every time. That is to say, if one is missing, the coverage it represents is not added to the aggregate calculation and aggregate coverage will therefore drop.

Dynamically excluding certain files on each run won’t work because change is being compared over time between builds and so, doing this sets up an apples / oranges comparison.

The closest thing that could work is if you could decompose your builds into a set of parallel jobs that don’t change from build to build, then configure your CI to re-send the last job for any job that’s excluded from a new build.

Hope that makes sense. You’ll have to figure that part out yourself but here if you have questions.

**Comment by tgolsson** [comment]
Thank you @afinetooth! Yes, our build already uses the parallel feature, so I'll have to add some artifact storage for the test outputs and spawn faux jobs for the ones that are omitted. A bit inconvenient but nothing I can't solve! Of course, it'd be lovely (and likely easier) if this was handled on the coveralls side instead so consider it a feature request. :sunglasses: 

Thanks a lot for your help!

**Comment by afinetooth** [comment]
Sure thing @tgolsson. I forgot to mention, this is definitely an open feature request internally, so I added your `+1` to it. 

I don't know if I was clear with the link under [carryforward flags](https://docs.codecov.io/docs/carryforward-flags) above, but the feature _is_ available at another vendor. The service may be more expensive depending on your situation, but it's available now if you don't want to spend time on the workaround.

**Comment by afinetooth** [comment]
Hi @tgolsson. I wanted to update you that we have released our Carryforward Flags feature. It's also supported in all of our official integrations.

You can read more about it here:
https://coveralls.io/better-monorepo-support

And here's an example of support for the feature from the Coveralls Github Action, one of our official integrations:

- [The `carryforward` input option](https://github.com/marketplace/actions/coveralls-github-action#:~:text=carryforward,parallel%2Dfinished.)
- [Usage example in a parallel build](https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example) (see the `finish:` step)

Let me know if you have any questions about using the feature.
