### ISSUE TITLE
No branch in the list but results exists for this branch

### ISSUE THREAD

**Issue by avtikhon** [lemurheavy/coveralls-public#1538]
There is available direct link to the results within branch `avtikhon/gh-5644-standalone`:
https://coveralls.io/builds/38138698

But results for the branch can't be found with link like:
https://coveralls.io/github/tarantool/tarantool?branch=avtikhon/gh-5644-standalone

We need it, to create direct links to results from Github PRs, like:
https://github.com/tarantool/tarantool/pull/5918#issuecomment-804269859

**Comment by caleb15** [comment]
We are experiencing a similar issue, I am only seeing the "dev" branch despite clicking on sync branches. Nothing happens when I try searching for other branches.

![image](https://user-images.githubusercontent.com/46505081/112873858-0ab3de00-9077-11eb-912c-5ee4e908b30c.png)

**Comment by szechyjs** [comment]
I'm seeing something similar. It seems none of our repo branches are syncing

**Comment by afinetooth** [comment]
@avtikhon (Cc: @caleb15, @szechyjs), thanks. 

Reproduced and reported. Will post updates here.

**Comment by kocolosk** [comment]
I know this one's a pretty stale ticket, but I'm seeing the same inability to sync branches other than `main` here. Should I file a new issue?

https://coveralls.io/github/apache/couchdb-erlfdb
