### ISSUE TITLE
Coveralls down - gateway time-out

### ISSUE THREAD

**Issue by kam193** [lemurheavy/coveralls-public#1539]
We experience the total down of Coveralls. https://status.coveralls.io/ reports no issue, but we get 500 gateway time-out in every Coveralls call in the CI & the even on the coveralls.io website

**Comment by kam193** [comment]
Looks okay now

**Comment by afinetooth** [comment]
Hi @kam193 yes, that was related to the issue from yesterday, Mar 29 here:
https://status.coveralls.io/

Thanks for the heads up. 

Closing for now, just reply if you see it again.
