### ISSUE TITLE
Syncing new bitbucket repos not working

### ISSUE THREAD

**Issue by scfast** [lemurheavy/coveralls-public#1541]
Attempting to sync a new Bitbucket repository to coveralls. Keep getting a 422 error. tried unlinking and re-linking bitbucket account with no luck

**Comment by afinetooth** [comment]
Hi @scfast. I'm not able to reproduce with our test account. 

When I test from a console with your user, I get the following error message:

`BitBucket::Error::Unauthorized "Access token expired.`

In context:

```
BitBucket::Error::Unauthorized (#<struct Faraday::Env method=:get, body="{\"type\": \"error\", \"error\": {\"message\": \"Access token expired.\"}}", url=#<URI::HTTPS https://bitbucket.org/api/2.0/user/permissions/repositories?page=1> [...]
```

So at this point, it's probably worth verifying that your token is indeed not expired.

According to this [SO post](https://stackoverflow.com/questions/34870000/bitbucket-api-access-token-expiry):

> Bitbucket don't have a published method to query an access token.

But you can at least check your tokens this way to make sure they haven't expired:
https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html

Best bet is probably to nuke your current one(s), create a new one and try logging into https://coveralls.io again. (You'll probably want to unlink your BB account first to make sure you're starting fresh.)
