### ISSUE TITLE
Problem logging into to coveralls ui using github integration

### ISSUE THREAD

**Issue by cheekytinker** [lemurheavy/coveralls-public#1542]
I get the following error when logging in using my github account

https://coveralls.io/authorize/github/callback?code=4c11451014700915cef4&state=4991d07c7959a1baa80ddc8d2d3868bb

Could you provide any additional info about the issue?

**Comment by j0k3r** [comment]
I can't either.
Maybe it's also related, uploading coverage fail when using the GitHub Action: https://github.com/serverless-heaven/serverless-webpack/pull/794/checks?check_run_id=2436462901

```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: ./coverage/lcov.info
    coveralls-endpoint: https://coveralls.io
Using lcov file: ./coverage/lcov.info
Error: Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
```

**Comment by MarciglianoIT** [comment]
I think this is a duplication to that one:
https://github.com/lemurheavy/coveralls-public/issues/1543

**Comment by afinetooth** [comment]
Yes, these both look like the carry-on effects of the general outage we just experienced. 

We're back now. Sorry for the inconvenience.

Closing for now. Thanks.
