### ISSUE TITLE
API responding with 500 (Build processing error)

### ISSUE THREAD

**Issue by mfittko** [lemurheavy/coveralls-public#1543]
node client throwing following error message since about 8:15 UTC;
`{"message":"Build processing error.","error":true,"url":""}`

Web page (https://coveralls.io/) also returning with error 500.

Nothing reported on https://status.coveralls.io/

**Comment by pheanex** [comment]
I've pinged support@coveralls.io also via mail

**Comment by harshal-moneylion** [comment]
+1 we are also facing the same since ~ 8:00 UTC;

**Comment by cheekytinker** [comment]
Same issue and also 500 error trying to login via github integration

**Comment by EmmaB** [comment]
+1 with thanks for looking in to it! Ours is failing via our GitHub Actions integration.

**Comment by mfittko** [comment]
hope this is soon tackled, our CI pipelines are blocked and we cannot merge to master since more than 3 hours now.

**Comment by GeorgiStavrev** [comment]
+1 We're also facing this issue, currently having some PRs blocked by this issue, unless we remove the coveralls step from the workflows.

**Comment by MarciglianoIT** [comment]
I do not think more pressure will make the work faster. But a feedback that you are working on it would be great!

**Comment by browniebroke** [comment]
In the meantime, we've made the coveralls steps optional

```diff
- coveralls
+ coveralls || echo 'Failed to submit coverage report'
```

**Comment by dtieber** [comment]
Same issue here. Would be great to get at least some updates on what's happening.

**Comment by damjankuznar** [comment]
Same here...

**Comment by afinetooth** [comment]
Thanks @mfittko et. al. We're looking into it.

**Comment by andy-maier** [comment]
At this point (6h after the site was down), the operational status page still shows all systems as operational... It would be good if such a status would be more reliable.

Anyway, thanks for looking into the issue!

**Comment by j0k3r** [comment]
@andy-maier at least, the chart speaks for itself
![image](https://user-images.githubusercontent.com/62333/116110708-38ac3280-a6b6-11eb-853f-1b11b9f2f4b5.png)

**Comment by thomaspoignant** [comment]
The status page is updated
<img width="994" alt="Screen Shot 2021-04-26 at 17 47 50" src="https://user-images.githubusercontent.com/17908063/116112165-9b51fe00-a6b7-11eb-8334-0b6db3d61f92.png">

**Comment by afinetooth** [comment]
We are operational again. Monitoring.

Our RDS instance failed to auto-scale, so we've done it manually and are watching for further issues.

**Comment by mfittko** [comment]
Yay, master branch is green again, thanks for the fix. Hope it's not coming back :crossed_fingers:

**Comment by afinetooth** [comment]
It shouldn't. Thanks for your patience.

Our standard notifications did not make it out of EC2 console for some reason. We will add enhanced monitoring this week to avoid future incidents.

Thanks for your patience, all.
