### ISSUE TITLE
Problematic copy on 500 error page

### ISSUE THREAD

**Issue by clok** [lemurheavy/coveralls-public#1544]
During today's outage, we noticed the copy on the 500 error page. "...after we stamp out the refuseniks." 

Here is a [link to the Wikipedia page for Refusnik](https://en.wikipedia.org/wiki/Refusenik)

From Wikipedia:
> Refusenik (Russian: отказник, otkaznik, from "отказ", otkaz "refusal") was an unofficial term for individuals—typically, but not exclusively, Soviet Jews—who were denied permission to emigrate, primarily to Israel, by the authorities of the Soviet Union and other countries of the Eastern bloc.[1] The term refusenik is derived from the "refusal" handed down to a prospective emigrant from the Soviet authorities.

Unintended or not, this is problematic, anti-Semitic language. I would like see this removed. The specific use of this derogatory term with ties to Jewish people is unacceptable. 

The language combined with the imagery is very frustrating. I am aware that Coveralls has responded to comments on their use of propaganda style imagery in the past (see #918), but satire and political commentary are fine lines to walk. I feel that when the line is "crossed", it is important to have the humility to admit the mistake. 

![image](https://user-images.githubusercontent.com/1429775/116116451-ca994880-a680-11eb-8c4c-7d757be4d48f.png)

**Comment by afinetooth** [comment]
@clok thanks. We've been trying to address objections to our original theme with a full design update that's still in progress as of this writing. Here's [a more recent issue](https://github.com/lemurheavy/coveralls-public/issues/1503) (https://github.com/lemurheavy/coveralls-public/issues/1503) in which we announced that.

That said, I assure you no one here was aware of the anti-Semitic aspect of the term "refusnik" and that the association was not intended. That information is new knowledge for us so we'll be changing the wording immediately.

**Update**:
Copy change deployed.

**Comment by clok** [comment]
@afinetooth Thank you for the response and the action. Sometimes the best we can do given new information is take action on it, so I appreciate Coveralls making the change.

I am going to keep an eye on #1503 for updates on the new UI. I am definitely looking forward to the redesign. Are there any updated timelines on it?

> NOTE: I, as the original poster, am closing this issue as I find the response from Coveralls adequate for the time being. I saw some consternation on #918 about who closed the issue and wanted to make it clear I am closing it.

**Comment by afinetooth** [comment]
Thanks, @clok. I'll update these related issues when we release our updated design.
