### ISSUE TITLE
Improve documentation for Golang with github actions

### ISSUE THREAD

**Issue by ae-ou** [lemurheavy/coveralls-public#1546]

**Comment by afinetooth** [comment]
@ae-ou Golang integrations for coveralls are documented here:
https://docs.coveralls.io/go

And the Golang integration listed there ([goveralls](https://docs.coveralls.io/gohttps://docs.coveralls.io/go)) has been documented for Github Actions by the creator here:
https://github.com/mattn/goveralls#github-actions

The creator of [goveralls](https://docs.coveralls.io/gohttps://docs.coveralls.io/go) also provides a Github Action using [goveralls](https://docs.coveralls.io/gohttps://docs.coveralls.io/go) under-the-hood, here:
https://github.com/marketplace/actions/actions-goveralls

Which documents [basic usage](https://github.com/marketplace/actions/actions-goveralls#basic-usage) instructions in its README:
https://github.com/marketplace/actions/actions-goveralls#basic-usage

Coveralls does not provide a native integration for every language. Most have been created by the community. We do our best to list them by language on the [coveralls website](https://docs.coveralls.io/), here:
https://docs.coveralls.io/

What is it that seems to be missing or incorrect from the [goveralls](https://docs.coveralls.io/gohttps://docs.coveralls.io/go) docs? Probably best to start by sharing it in [that project's issues](https://github.com/mattn/goveralls/issues):
https://github.com/mattn/goveralls/issues

We are here for support if, upon using the integration, you get unexpected behavior / errors back from the [Coveralls API](https://docs.coveralls.io/api-reference).
