### ISSUE TITLE
Need support for bitbucket pipelines CI

### ISSUE THREAD

**Issue by vrknetha** [lemurheavy/coveralls-public#1550]

**Comment by afinetooth** [comment]
Thanks @vrknetha. I have added the request to our backlog to provide first class support for Bitbucket Pipelines. 

In the meantime, you can probably get your project working by following the [setup instructions for a generic CI service]((https://docs.coveralls.io/supported-ci-services#insert-your-ci-here)). [This](https://docs.coveralls.io/supported-ci-services#insert-your-ci-here) is a good place to start, but to help I'll need to know your project's language and any pre-built coveralls integration you're using, as that might change the CI env vars you'll be setting.

I might be able to get this from your Coveralls project URL.

If your project is private, you can send it to support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1550).
