### ISSUE TITLE
Still being billed when there are no more pro subscriptions

### ISSUE THREAD

**Issue by jmhossler** [lemurheavy/coveralls-public#1556]
We decided to not use coveralls due to security concerns (too many permissions being requested to function). We removed the subscription and integration with our private org, but we still got billed recently.

This probably isn't the right place to post, but I don't get any response on the page when I click the 'support' button at the bottom of the coveralls.io page when signed in. This is the only place I can see to post about this issue.

I already checked the faq about this: https://docs.coveralls.io/faq

We don't have any orgs under the subscriptions tab, though, because we already removed that.

**Comment by jmhossler** [comment]
Found the support email, I'll continue reaching out over there since that seems like a better place to get help for this issue than here.

**Comment by afinetooth** [comment]
Thanks @jmhossler. I see your email in the support inbox. We'll resolve it for you today.
