### ISSUE TITLE
GitHub Actions parallel webhook fails, DataTables warning

### ISSUE THREAD

**Issue by achrinza** [lemurheavy/coveralls-public#1573]
Issue can be seen in PR https://github.com/loopbackio/loopback-next/pull/7387.

Coveralls status page indicates everything is OK with no incidents:

![image](https://user-images.githubusercontent.com/25147899/131217046-cfc19a42-aaf9-4bae-913b-01abfb6b9ab8.png)

![image](https://user-images.githubusercontent.com/25147899/131217074-dd1475c0-d066-4124-a936-b927f5b309dd.png)

Output of Coveralls "parallel finished webhook" job:

```sh
Run coverallsapp/github-action@master
/home/runner/work/_actions/coverallsapp/github-action/master/lib/run.js:97
                        throw new Error('Parallel webhook error:' + err + ', ' + JSON.stringify(data));
                        ^

Error: Parallel webhook error:TypeError: Cannot read property 'done' of undefined, undefined
    at Request._callback (/home/runner/work/_actions/coverallsapp/github-action/master/lib/run.js:97:31)
    at Request.self.callback (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/coverallsapp/github-action/master/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

GitHub Actions workflow:

https://github.com/loopbackio/loopback-next/blob/87cfbea1d9457f72cdb621330a1afe8c05a4bcc4/.github/workflows/continuous-integration.yml#L16-L67

On the Coveralls dashboard, we're able to see the incomplete builds (last 4, coverage % greyed out):

![image](https://user-images.githubusercontent.com/25147899/131215979-77d7a12e-e092-4f45-bf6a-fe6788023a74.png)

When trying to access to builds, a Gateway Timeout occurs:

![image](https://user-images.githubusercontent.com/25147899/131216031-f74b742a-e98c-4512-83b0-fc6cbfe1b3c8.png)

(IP address is redacted)

Sometimes, the build page is returned, but a "DataTables warning" alert is shown, and the build report is not accessible:

![image](https://user-images.githubusercontent.com/25147899/131216597-eeb5aaec-f40c-4ad1-91ed-a381b817be75.png)

(Token is redacted)

DataTables error alert:

```
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

Not sure if it's related, but when checking previous runs of the PR, this issue seems to have started occuring around the same time as the _average web/api response time_ spiked:

![image](https://user-images.githubusercontent.com/25147899/131216245-64fa4b20-08fa-4e4b-9bad-12af399b2202.png)

**Potentially-related:**
- https://github.com/lemurheavy/coveralls-public/issues/1574
- https://github.com/lemurheavy/coveralls-public/issues/1569
- https://github.com/coverallsapp/github-action/issues/91
- https://github.com/coverallsapp/github-action/issues/92

**Comment by achrinza** [comment]
Coveralls just added a new comment to the PR without a re-run of the CI pipeline, though it seems to be referencing an older build of the PR.

https://github.com/loopbackio/loopback-next/pull/7387#issuecomment-907612332

Not too sure what changed...

**Comment by achrinza** [comment]
The issue seems to be fixed :)

It seemed like Coveralls was overloaded; Though the UX could use some improvements (i.e. instead of giving cryptic errors).

**Comment by achrinza** [comment]
The issue seems to creep back in and out over time across several PRs. Is there any way to prevent this from happening?

Affected runs:
- https://github.com/loopbackio/loopback-next/pull/7802/checks?check_run_id=3460643819
- https://github.com/loopbackio/strong-soap/pull/333/checks?check_run_id=3460632324
- https://github.com/loopbackio/loopback-next/pull/7796/checks?check_run_id=3460032184

**Comment by mobilutz** [comment]
@achrinza Unfortunately, I am still seeing this issue today:
https://github.com/coverallsapp/github-action/issues/91

I added the issue on the github-actions and didn't check here, but now linking the two topics.

**Comment by afinetooth** [comment]
Hi @achrinza, @mobilutz,

This is due to an issue at the infrastructure level. We are aware and addressing it right now:
https://status.coveralls.io/

It looks like you started experiencing the effects ~48 hrs ago. The system is self-correcting and will keep going until it can't. We did not trip any of our normal metrics until this morning. Look like we'll need to start tracking these individual Gateway errors more closely.

The error you experienced, aside from the Gateway error, is normal for slow builds, which can be affected by performance related to traffic. Not typically an issue on weekends, so that seems like the pattern to look out for.

Related:
- https://github.com/lemurheavy/coveralls-public/issues/1576
- https://github.com/lemurheavy/coveralls-public/issues/1575

**Comment by afinetooth** [comment]
Hi @achrinza @mobilutz, we would like to consider this issue closed since the root cause has been resolved:
https://status.coveralls.io/

Thanks for reporting.

If you experience similar symptoms again, please re-report so we can address it as an individual issue with a different cause. Thanks.
