### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by limaofeng** [lemurheavy/coveralls-public#1574]
I can’t synchronize the results to the website, and I found out that there may be a problem

URL
```
https://coveralls.io/jobs/86104932
```

ERROR
```
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

**Comment by afinetooth** [comment]
Hi @limaofeng, this related to an underlying issue at the infrastructure level.

More info here:
https://github.com/lemurheavy/coveralls-public/issues/1573#issuecomment-908662057

Related:
- https://github.com/lemurheavy/coveralls-public/issues/1576
- https://github.com/lemurheavy/coveralls-public/issues/1575
- https://github.com/lemurheavy/coveralls-public/issues/1573

**Comment by afinetooth** [comment]
Hi @limaofeng we would like to consider this issue closed since the root cause has been resolved:
https://status.coveralls.io/

If you experience it again, please re-report so we can address it as an individual issue with a different cause. Thanks.
