### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1575]
When we ran the following

`export COVERALLS_PARALLEL=true;yarn coveralls -v < ff/static/coverage/lcov.info`

 we got:

```
/home/********/project/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 503 <h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
(Use `node --trace-uncaught ...` to show where the exception was thrown)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

I also got a gateway time-out error when loading https://coveralls.io
The page says FIVE ZERO ZERO - IT'S GONE PEAR SHAPED

```
Ray ID: 687076f72de0024e
Your IP address: 72.199.108.194
Error reference number: 504
Cloudflare Location: San Jose
```

**Comment by afinetooth** [comment]
Hi @caleb15. Thanks. We are aware and working on it right now:
https://status.coveralls.io/

**Comment by afinetooth** [comment]
Hi @caleb15, we would like to consider this issue closed since the root cause has been resolved:
https://status.coveralls.io/

If you experience it, or similar, again, please re-report so we can address it as an individual issue with a different cause. Thanks.

**Comment by caleb15** [comment]
Thanks. Do you have a post-mortem?

**Comment by afinetooth** [comment]
Hi @caleb15, yes. We always perform a post-mortem when an unexpected issue occurs.

Summarizing from internal notes:

> **Root cause**: 
> Infrastructure-level. Database availability. RDS. 
>
> **Explanation**: 
> When we swapped out our RDS instance last year due to the size limits of the previous type, the postgres parameters from our previous instance did not carry over to the new instance. Some of those parameters dealt with optimized auto-vacuum settings for our use case of huge tables/indexes, so this performance degradation was a result. 
>
> **Solution**: 
> Now that we have the parameters applied, we shouldn’t hit another vacuum bottleneck that starves resources from our app the next time it’s needed.

Thanks.

**Comment by caleb15** [comment]
Thanks
