### ISSUE TITLE
error 504

### ISSUE THREAD

**Issue by hurrycaner** [lemurheavy/coveralls-public#1576]
GATEWAY TIME-OUT
The web server reported a gateway time-out error.

Ray ID: 6870868cfdb351bf
Your IP address: 189.35.90.159
Error reference number: 504
Cloudflare Location: São Paulo

We are getting this in coveralls.io website and several actions (goveralls, ex_coveralls and coverallsapp/github-action).

**Comment by afinetooth** [comment]
Thanks @hurrycaner . We're aware and working on it right now:
https://status.coveralls.io/

See also:
- https://github.com/lemurheavy/coveralls-public/issues/1575

**Comment by afinetooth** [comment]
Hi @hurrycaner, we would like to consider this issue closed since the root cause has been resolved:
https://status.coveralls.io/

If you experience it again, please re-report so we can address it as an individual issue with a different cause. Thanks.
