### ISSUE TITLE
Floating point error in report statuses

### ISSUE THREAD

**Issue by DrHyde** [lemurheavy/coveralls-public#1586]
In this report <https://coveralls.io/builds/43235617>, triggered by a Github action, and where there were no changes in the tests or the code under test, I'm told that "coverage decreased (-0.0%) to 91.429%".

Note the -0.0%.

This appears to be a regression on your part, as the previous report <https://coveralls.io/builds/37411862>, where there was also no change in the code or the tests, said "coverage remained the same at 91.429%".

**Comment by afinetooth** [comment]
Hi @DrHyde,  we have an open ticket for this one. I have added your issue to it. Will update you here when status changes.

**Comment by DrHyde** [comment]
Thanks!

**Comment by maxatome** [comment]
@afinetooth same behavior here, no code change: https://coveralls.io/builds/43333447

**Comment by afinetooth** [comment]
Hi @maxatome. Confirmed. Have +1'd you on our ticket. Thanks.

**Comment by DrHyde** [comment]
Looks like it's fixed: https://coveralls.io/builds/43999016. Thanks!

**Comment by afinetooth** [comment]
@DrHyde I don't have an official update on that ticket, but it looks like you're right. I'll feed back here to confirm. Thanks.

**Comment by maxatome** [comment]
Hi @afinetooth, it is still broken here: https://coveralls.io/builds/44039515

**Comment by afinetooth** [comment]
Hi @maxatome (Cc: @DrHyde), yes, I don't have an update on the issue so it's likely another factor led to resolution for your build(s), @DrHyde. Thanks for reporting. We're still in progress. (And FWIW, at this point, we're not sure a floating point error is the root cause.)
