### ISSUE TITLE
Trouble adding a new repo

### ISSUE THREAD

**Issue by oshi97** [lemurheavy/coveralls-public#1587]
Hi, sorry if this is due to some error on my part, but I'm having trouble adding a new public repo to Coveralls.
On the Add Repos page, it looks like the repo has already been added

![image](https://user-images.githubusercontent.com/23005393/136453782-9aa0b90a-c414-4860-8a68-4541af67c270.png)

but clicking on the "Details" link brings me to a 404 page
https://coveralls.io/github/yext/answers-headless

I've run a through CI builds using the coverallsapp github action, and while the action itself passes, I don't see any Coveralls check saying something like "Your coverage is XX%" like I see in other repos that we've added Coveralls for.
https://github.com/yext/answers-headless/pull/31

Here's an example of coveralls working as expected in a different repo we have
https://github.com/yext/answers-headless-react/pull/40

Is there maybe a repo limit of 5 that I'm not aware of?

**Comment by afinetooth** [comment]
Hi @oshi97,

Your repo was marked private (note the lock icon):

![Screen Shot 2021-10-07 at 6 29 15 PM](https://user-images.githubusercontent.com/918667/136483977-c087af0c-ca65-465a-83cc-0085c14146f4.png)

Even though it is public on Github:
https://github.com/yext/answers-headless

When this happens, you can re-sync with Github, using this control in SETTINGS:
https://coveralls.io/github/yext/answers-headless/settings

![Screen Shot 2021-10-07 at 6 30 46 PM](https://user-images.githubusercontent.com/918667/136484083-7a52b60d-31d8-4b50-8a00-6c43a705f024.png)

I did that on your behalf and the repo changed status to public:

![Screen Shot 2021-10-07 at 6 31 07 PM](https://user-images.githubusercontent.com/918667/136484120-10a2af97-45e9-49bc-a579-dc1c4bf66b41.png)

So it shouldn't throw that `404` at you again.

**Comment by oshi97** [comment]
Thanks so much! I clicked the sync repos button on the Add Repos page a few times but wasn't able to find the URL you linked.

**Comment by afinetooth** [comment]
Hi @oshi97. That button is in the settings for the repo, here:
https://coveralls.io/github/yext/answers-headless/settings

You probably couldn't see it because you need Admin access to the repo at Github to see all settings.

In cases like this you'll need to request a re-sync from the repo owner or someone with Admin access on the project.
