### ISSUE TITLE
Coveralls PR Comment posts hours later

### ISSUE THREAD

**Issue by mjchang** [lemurheavy/coveralls-public#1588]
Coveralls CI runs runs in a short amount of time (< 1 min) but the Coveralls PR comment is posted hours later. In this case, it was 4 hours later.

<img width="926" alt="Screen Shot 2021-10-08 at 11 11 28 AM" src="https://user-images.githubusercontent.com/6496667/136603426-fdb94616-1fe7-4654-b501-8732a0ac14c1.png">

It does not always take this long though. In the morning it's relatively fast (~15 mins) but towards the end of the day it's lagging behind. Is there any way to speed this up?

**Comment by afinetooth** [comment]
Hi @mjchang, yes, sometimes, typically mid-day during US PST working hours, there will be a lot of traffic in the shared  queues containing the background jobs that complete builds. The timing for a given build depends mainly on this traffic, though, also project size, number of parallel jobs, etc.

Unfortunately, right now there's nothing you can do about the main factor, which is traffic on shared resources. We are evaluating a new service tier where customers can pay for dedicated resources and thereby tune their build times, but it's not yet in development.

If you want to share the coveralls URL for you project, I can see what was going on that day and get your timings for your last _n_ builds. It will give you a sense of your fastest build times, average build times, and how much those can be affected by busy hours. 

One thing I have seen recently with customers having long build times is that they themselves are sending hundreds of builds in a very short period of time, essentially creating their own traffic in the queues their project is routed to. I will be able to tell if that issue affects you once I know the coveralls repo URL.

**Comment by mjchang** [comment]
Okay understood - that's what I figured. This is our coveralls repo URL: https://coveralls.io/github/u21/lumos

**Comment by afinetooth** [comment]
Thanks @mjchang. The first thing I noticed about your repo is the number of builds is very high and apparently constant. You've sent us about 33 builds so far just today (and about 55 yesterday), about 5-7 per hour. The last 14 are now struggling to finish. We don't throttle API posts after a certain number of builds, but you are then competing against yourself for resources to process jobs off the same queue. I do see several PRs represented there, so I wonder, are you doing a sweep of outstanding PRs (infrequent) or is this regular build behavior on your project?

If you'd like to email us at support@coveralls.io referencing this issue, I'll send you a report of your last several hundred builds.

**Comment by mjchang** [comment]
@afinetooth The volume seems expected to me. My current coveralls setup is that every PR and every master push will trigger the coveralls CI and with a large team, we are constantly contributing. With this setup, do you see any optimization I can do?

**Comment by afinetooth** [comment]
@mjchang, received your email. Will reply there with your build history.

Unfortunately, there's not much you can do from your side with that pattern. One option is [Coveralls Enterprise](https://enterprise.coveralls.io/), the on-premise version of Coveralls, but it has a per-seat pricing model that can be prohibitive if you have many users.

As I mentioned, we are evaluating a new service tier where customers can pay for dedicated resources but it's not yet in development so I don't have an ETA to share.
