### ISSUE TITLE
Unable to see new coveralls build

### ISSUE THREAD

**Issue by sumedhreddy90** [lemurheavy/coveralls-public#1592]

**Comment by afinetooth** [comment]
Hi @sumedhreddy90. We'll need some info, like the Coveralls URL to your repo and any problematic builds to help you.

**Comment by sumedhreddy90** [comment]
Travis Build #17: https://app.travis-ci.com/github/SumedhKoppula/TX9PerceptionModule/builds/240618648

Repo: https://github.com/SumedhKoppula/TX9PerceptionModule/tree/devBranchPhaseII

**Comment by afinetooth** [comment]
Ok, so your Coveralls repo URL would be:
https://coveralls.io/github/sumedhreddy90/TX9PerceptionModule

It looks like you're either not set up yet, or more likely that we just haven't received a successful job POST from your CI yet. Which typically points to an issue with your CI configuration.

The error message on [your Travis build](https://app.travis-ci.com/github/SumedhKoppula/TX9PerceptionModule/builds/240618648) is:

```
coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.* -E ".*app/main.cpp"
/home/travis/.travis/functions: eval: line 109: unexpected EOF while looking for matching `"'
/home/travis/.travis/functions: eval: line 110: syntax error: unexpected end of file
```

Which indicates an issue parsing one or more of the coverage report files you're passing to that `coveralls` command (`unexpected EOF`).

We can only really help with issues in POSTs we're receiving at Coveralls, so assuming you're using the [cpp-coveralls](https://github.com/eddyxu/cpp-coveralls) integration, you'd be better off starting with [that project's issues board](https://github.com/eddyxu/cpp-coveralls/issues).

In the meantime, have you tried using the `--verbose` flag, per the [usage instructions](https://github.com/eddyxu/cpp-coveralls#usage)?

I would hope it gives you some more insight into what's happening there.
