### ISSUE TITLE
Is flag_name supported? 

### ISSUE THREAD

**Issue by theodorDiaconu** [lemurheavy/coveralls-public#1597]
I would like to have a way to publish multiple coverages from the same repository and I was using circleci orb and using specific flag_name per package, however I don't see anything in the UI nor a way to "group" the coverages in any way.

What should I use to achieve that in a monorepo? I'm talking about https://github.com/bluelibs/bluelibs with a standard mono-repo lerna like package.

**Comment by afinetooth** [comment]
Hi @theodorDiaconu. For specific advice, it will help if you can share the Coveralls URL for your project. If it's private or sensitive, you can send it to support@coveralls.io and refer to this issue.

In the meantime, I'll try to address each part of your question, as I'm not 100% sure I understand your use case at this point.

> I would like to have a way to publish multiple coverages from the same repository and I was using circleci orb and using specific flag_name per package, however I don't see anything in the UI nor a way to "group" the coverages in any way.

The `flag_name` parameter defined in the [usage examples](https://circleci.com/developer/orbs/orb/coveralls/coveralls#usage-examples) for the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls) surface a job-naming feature that's generally supported by the [Coveralls API](https://docs.coveralls.io/api-reference).

The incoming JSON param that you'll want to pass a value for is called `flag_name`, the same name it's given in the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls). You can read about it here in the [Coveralls API Reference](https://docs.coveralls.io/api-reference):

> `flag_name` - String (optional)
> If this is set, the job being reported will be named in the view and have it’s own independent status reported to your VCS provider.

Each job you send for a parallel build is named in this manner and the name you choose is displayed in the first part of the label the job has on your build page.

Example public repo with parallel builds:
https://coveralls.io/github/coverallsapp/coveralls-node-demo

Example build page:
https://coveralls.io/builds/40512044

Jobs section of page:
![Screen Shot 2021-11-26 at 2 05 12 PM](https://user-images.githubusercontent.com/918667/143657997-ccf597b0-ffb7-418b-8e0d-69558a34c10d.png)

(In this case, the values passed for `flag_name` were `test-1` and `test-2` respectively.)

You can examine how that was declared in this demo project, which was created to demonstrate how to configure parallel builds for Coveralls:
https://github.com/coverallsapp/coveralls-node-demo

Examples were created there for CircleCI, Travis CI and Github Actions, so just find the reference to the right configuration file in the [README](https://github.com/coverallsapp/coveralls-node-demo#coveralls-parallel-jobs-demo-).

> What should I use to achieve that in a monorepo? I'm talking about https://github.com/bluelibs/bluelibs with a standard mono-repo lerna like package.

This is a little tougher to say definitively. Coveralls does not have explicit, robust support for monorepos. For instance, it doesn't support line-by-line coverage for monorepos that make use of git submodules.

That said, many users configure monorepos for use with Coveralls, and in those cases it's very typical for them to separate the components into separate coverage reports and to name them (using the `flag_name` param) accordingly.

I'm a little confused about your reference. Are you saying [bluelibs](https://github.com/bluelibs/bluelibs) _is_ the monorepo you're referring to? Or just any project making use of a monorepo management tool like [lerna](https://github.com/lerna/lerna)?

**Comment by theodorDiaconu** [comment]
Hi @afinetooth 

Thank you for your response! Yes, bluelibs is my monorepo for which I am planning to show code-coverage for: https://github.com/bluelibs/bluelibs, inside circle ci I'm using flag_name: "package_name", however coveralls interprets it as if it was the same package, no distinction between others. This is why I asked if this is supported in anyway?

I've used verbose usage for the orb in circleci, and I can clearly see flag_name is sent to coveralls through it https://circleci.com/developer/orbs/orb/coveralls/coveralls

Also regarding your screen share, I do not see "Jobs" while logged into coveralls, only "Builds". Is there a special tier for having this?

Thank you!

**Comment by theodorDiaconu** [comment]
@afinetooth ping. I still can't use flag_name, and I have a different UI than what you've shown. Let me know if you need any aditional details.

**Comment by afinetooth** [comment]
Hi @theodorDiaconu. Looking at your latest build for that repo, it appears you've added a value for `flag_name` that _has_ actually been applied to the build's job(s)---that is, if the name you passed for your one job was `nova`.

Here's how it appear for me in the **JOBS** section of [this **build** page](https://coveralls.io/builds/44540765):

https://coveralls.io/builds/44540765
![Screen Shot 2021-12-03 at 11 56 26 AM](https://user-images.githubusercontent.com/918667/144664978-865559b6-56bd-4f21-9eeb-577154df46e3.png)

To answer your question: No, the **JOBS** table is a feature of all tiers.

It's located below the "build details" table and above the **SOURCE FILES** table:

![Screen Shot 2021-12-03 at 12 06 49 PM](https://user-images.githubusercontent.com/918667/144666187-2f13a6b1-0152-4aa0-9b5c-d04300c194d1.png)

It lists all the **jobs** received for a particular **build**, and each job links to its own separate **job page**. 

[Here is the **job page**](https://coveralls.io/jobs/90632364) linked to from the `nova - c01a7f7d-894a-40bf-9c20-f6f4940ebf54.1` job:
https://coveralls.io/jobs/90632364

If your build had been **parallel**, you would see several jobs listed there, typically with the value for `flag_name` pre-pended, and an incremented job number post-pended, like:

`<flag_name> - <build_number>.<job_number>`

Your example from [this build](https://coveralls.io/builds/44540765):

`nova - c01a7f7d-894a-40bf-9c20-f6f4940ebf54.1`

If the value for `flag_name` is not coming through as expected, please share your verbose build log so I can examine it. Again, if sensitive, send to support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1597).

**Comment by afinetooth** [comment]
@theodorDiaconu Sorry. I missed that you had _closed_ this issue after your last message. Glad you got it worked out.

**Comment by theodorDiaconu** [comment]
@afinetooth thank you very much for your detailed responses, apparently I can now see nova as flag_name. Sorry for closing the issue, I've mistakenly clicked "Close and comment".

Apparently, each individual publish affects the overall coverage even if I publish it with flag_name, it would be ideal to separate this especially for code coverage, either that, or worst-case scenario have an avg of all "flag_name" as the default total coverage. 

My questions are: is there a possibility I can create like a table in which I show each individual package/flag_name coverage? Also a sort of total coverage?

**Comment by afinetooth** [comment]
@theodorDiaconu not sure I understand. 

`flag_name` is really meant to be used in the context of parallel builds, to separately identify each job in your build.

Each job will indeed affect the overall coverage, and that's as you suggest, an "average" (actually a recalculation of all coverage reports form all jobs), which results in an aggregate coverage %. That's exactly how parallel builds work.

Moreover, from a UI standpoint, each of your jobs appears (with flag_name as you've used it) in the JOBS table in each of your builds, with its own separate coverage % for that job, and each links to its own "job" page. 

See [my previous comment](https://github.com/lemurheavy/coveralls-public/issues/1597#issuecomment-980452569) for an example with screenshot.

From the standpoint of your SCM / Github, you'll get a separate status update for each of your jobs, with their coverage %, labeled by `flag_name`, as well as a final status with the aggregate coverage %. And your PR's can receive comments which break down the aggregate coverage.

Am I getting close to what you're looking for?

If not, can you share some screenshots, or share your CI config?
