### ISSUE TITLE
Build processing error - Unable to upload report using coveralls.net as of today

### ISSUE THREAD

**Issue by sebastieng84** [lemurheavy/coveralls-public#1600]
Managed to upload the reports yesterday, but as of today we always get the Build processing error (private repository). Is there a way to get more information on what's wrong?

**Comment by afinetooth** [comment]
Hi @sebastieng84. Can you please share the Coveralls URL for your repo? If private/sensitive, you can email it to support@coveralls.io and reference [this issue](https://github.com/lemurheavy/coveralls-public/issues/1600). Thanks.
