### ISSUE TITLE
Incompatible Application::getDefinition()

### ISSUE THREAD

**Issue by ricardoboss** [lemurheavy/coveralls-public#1601]
https://github.com/elephox-dev/framework/runs/4385385836?check_suite_focus=true

This suddenly fails and the last working version is 4.3.0.

**Comment by afinetooth** [comment]
Thanks, @ricardoboss. For those with the same or similar issue, see [this issue/PR](https://github.com/php-coveralls/php-coveralls/pull/333), [this comment](https://github.com/php-coveralls/php-coveralls/pull/333#issuecomment-983991041).
