### ISSUE TITLE
DataTables error, 500 response from jobs/[id]/source_files

### ISSUE THREAD

**Issue by hovissimo** [lemurheavy/coveralls-public#1611]
I'm trying out coveralls, but so far this has been really painful.  What's even going on here?

I'm configured with parallel tests in Circle CI, and everything appears to be successful looking at the tasks run in CI. Here's a screenshot of the final "finish parallel" step:
![image](https://user-images.githubusercontent.com/6434414/149585475-c7f74999-4698-426f-877a-aae028b29d51.png)

There are no coverage results at that url:
![image](https://user-images.githubusercontent.com/6434414/149585570-d39821c0-7054-4d66-8619-0f9b59d50e13.png)

This build doesn't even appear in list of builds for the repo at https://coveralls.io/repos/361211/builds

Full url that got a 500: https://coveralls.io/jobs/92846331/source_files.js?filter=undefined&sEcho=1&iColumns=8&sColumns=%2C%2C%2C%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=&bRegex_6=false&bSearchable_6=true&bSortable_6=true&mDataProp_7=7&sSearch_7=&bRegex_7=false&bSearchable_7=true&bSortable_7=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&_=1642194458847

**Comment by afinetooth** [comment]
Hi @hovissimo. That error is a bit misleading. It indicates your build page is not finished rendering yet. 

In addition, a given build will not appear in your build history until it's UI related components are complete.

Rest assured that, if you're seeing that error, it _will_ resolve and you will, eventually, see your build in the form of a complete job/build page. (_See below if it's hanging around for a long time._)

Some quick background for context:

When you submit a coverage report to the Coveralls API, and you receive a 200 success response, the new job then _exists_ at https://coveralls.io and you can reach it at the URL delivered in your 200 success message.

However, after receipt, Coveralls runs a number of background jobs that calculate the stats that appear on your build page, and that render some interactive portions of the job's new job/build pages.

The DataTables error is being thrown by a Javascript component in the page that has been rendered into the DOM but has yet to receive all the data it needs to fully render _itself_.

Specifically, that component is, usually, the TREE view of your SOURCE FILES table, the last of said components to render.

Give it a few minutes and the error should go away and your build (or job) page will render.

_NOTE: When you're seeing that error a lot, and your builds aren't completing within 5-10 minutes, it could indicate a general performance issue at https://coveralls.io, which you may find info about at https://status.coveralls.io. If not, you can always notify us at support@coveralls.io_
