### ISSUE TITLE
Wrong `pages` count in the API response

### ISSUE THREAD

**Issue by vchrombie** [lemurheavy/coveralls-public#1612]
I was going through the documentation for [Getting data from Coveralls](https://docs.coveralls.io/api-introduction#getting-datafrom-coveralls).
```
https://coveralls.io/github/lemurheavy/coveralls-ruby.json?page=1
(get 10 builds at a time)
```

It says 10 builds, but only five are bring returned
```
$ curl https://coveralls.io/github/lemurheavy/coveralls-ruby.json\?page\=1 | jq -r '.builds | length'
5
```

- [ ] The docs have to be updated

Also, I see that the pages count is wrongly calculated.

Response for https://coveralls.io/github/lemurheavy/coveralls-ruby.json?page=72
```
{
  "page": 72,
  "pages": 36,
  "total": 357,
  "builds": [
    {
```

I think it is using the old logic of 10 builds per page (357/10 ≈ 36 pages), but since the page shows only 5 builds now I think the pages count has to be updated too (357/5 ≈ 72 pages).

- [ ] The logic for calculating the pages should be updated

Potential Labels : `api`, `documentation`

**Comment by afinetooth** [comment]
Hi @vchrombie. Confirmed, thank you. I've submitted a production bug. I will update you with status here.

**Comment by vchrombie** [comment]
> Hi @vchrombie. Confirmed, thank you. I've submitted a production bug. I will update you with status here.

Awesome, thank you.
