### ISSUE TITLE
Assembly of coveralls takes a long time 

### ISSUE THREAD

**Issue by Andranik7imonyan** [lemurheavy/coveralls-public#1615]
Hello.
We use coveralls in our project. For now the config covers only *.ts fiels(count of files is about 600). Now the process to show coverage takes about 2 mins. We also have tests which covers *.tsx files. After adding the *.tsx(count of files is about 2.5k) to the config the process takes about 1 hour. ->
<img width="230" alt="Capture" src="https://user-images.githubusercontent.com/93916952/154058342-756f250e-583e-47bb-9fb6-76610f04309b.PNG">

**added - 'src/somethng folders/*.tsx'**
That's not acceptable for us. The process triggers automatically on PR right after the tests executed.
So I have few questions:
Is there any way to speed this up?
Is it possible to cache the results and collect coverage just for the files which were changed in the exact PR and take the rest from the cache? Or collect the coverage in parts in parallel and then display the overall result?

**Comment by afinetooth** [comment]
Hi, @Andranik7imonyan. I'm not sure I understand your particular use case 100% but, in general, we've had some recent performance issues as traffic has increased at https://coveralls.io. We are doing our best to address those with changes to our infrastructure and are monitoring performance metrics to bring build times into a target range. 2 hours is beyond that range, so sorry for the problems you encountered with that.

Right now there is no way to leverage cache from previous builds, but it's something we're looking at to improve performance and to support partial builds. 

If you'd like me to get some historical data on your build times, please email us a support@coveralls.io, share your coveralls repo URL(s) and mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1615).

**Comment by afinetooth** [comment]
@Andranik7imonyan I'm not sure if you emailed your repo URL to support@coveralls.io, but we made some infrastructure upgrades over the past 2-weeks and build times have come way down for most users. If you find that's not the case for you, I'd encourage you to send your repo to us at support@coveralls.io and we'll analyze your stats.

I'm going to close this for now, but feel free to reopen.

**Comment by Andranik7imonyan** [comment]
OK, thank you
