### ISSUE TITLE
Sync Branches reports error 500

### ISSUE THREAD

**Issue by sineverba** [lemurheavy/coveralls-public#1617]
As title. Clicking on Synch Brances inside a report, XHR call returns a 500 error.

**Comment by afinetooth** [comment]
Hi, @sineverba. I have reported this internally. I am able to reproduce it in the UI, but not from a terminal, so it will take some further investigation. Will update with progress here.

**Comment by afinetooth** [comment]
Hi, @sineverba. This should be fixed. I tested on a couple of my repos. Please test on yours and let us know if you're still having issues. 

Closing for now. Just re-open if necessary.
