### ISSUE TITLE
Files containing multiple types

### ISSUE THREAD

**Issue by jnyrup** [lemurheavy/coveralls-public#1624]
First a big thanks. 
We recently added https://coveralls.io/github/fluentassertions/fluentassertions which has greatly helped us ensuring contributions are not lacking coverage.

Looking in the list view `GenericCollectionAssertions.cs` is missing coverage on 25 branches.
![image](https://user-images.githubusercontent.com/919634/160283753-2c0e6bdf-2c59-4c2e-8feb-f6bfe9114589.png)

Looking into the file no lines are colored yellow, or any other color for that sake.
https://coveralls.io/builds/47490925/source?filename=Src%2FFluentAssertions%2FCollections%2FGenericCollectionAssertions.cs#L32

We use [ReportGenerator](https://github.com/danielpalme/ReportGenerator) to process 13 Cobertura files outputted by from [Coverlet](https://github.com/coverlet-coverage/coverlet) into a single lcov file that is uploaded to coveralls.io

The html report that ReportGenerator also produces contains all the expected coloring.
![image](https://user-images.githubusercontent.com/919634/160283972-c8fe0142-f98f-4ef7-857e-2f156f82006c.png)

As far as I can I see the problems comes when a file contains multiple types, such that lcov.info contains multiple `SF:` pointing to the same file.
I'm a little if we are doing something wrong, the lcov produced by ReportGenerator is incorrect or coveralls.io not parsing the lcov correctly.

[The 13 processed cobertura files](https://github.com/lemurheavy/coveralls-public/files/8357792/cobertura.zip)

[reports.zip](https://github.com/lemurheavy/coveralls-public/files/8357700/reports.zip) containing both lcov.info and ReportGenerator reports.

**Comment by afinetooth** [comment]
Hi @jnyrup. Before we go deeper, have you seen the branch coverage notations in that file?

We do not color lines for branch stats, only for line coverage stats. Instead we put callouts in the margins and indicate the branch misses (with line numbers).

Your first branch missed starts at line `116`, so here is a side-by-side comparison of the **HTML coverage report for the file** (LEFT), and [**Coveralls source file view for GenericCollectionAssertions.cs**](https://coveralls.io/builds/47490925/source?filename=Src%2FFluentAssertions%2FCollections%2FGenericCollectionAssertions.cs#L32) (RIGHT). 

![Screen Shot 2022-03-28 at 3 17 00 PM](https://user-images.githubusercontent.com/918667/160496733-db6f840e-f1c4-4504-a434-c399da7eaad4.png)

Does that address your issue? If not, please help me understand where the gap is and if we're talking about what you consider to be a missing feature, or a broken feature. Thanks.

**Comment by jnyrup** [comment]
Hi @afinetooth, thanks for the reply.
You're right about branch stats, I got confused by looking for a yellow line like ReportGenerator.

Here are more complete examples about how a file containing a single type has the expected coloring, while files with multiple types does not.

For [`AndConstraint.cs`](https://coveralls.io/builds/47490925/source?filename=Src%2FFluentAssertions%2FAndConstraint.cs) there are four green lines in both coveralls (left) and ReportGenerator (right)
![image](https://user-images.githubusercontent.com/919634/160592802-5bbba3cf-db2b-4ea8-9807-e2729b8568dc.png)

For [`GenericCollectionAssertions.cs`](https://coveralls.io/builds/47490925/source?filename=Src%2FFluentAssertions%2FCollections%2FGenericCollectionAssertions.cs#L746) coveralls (left) has zero colored lines, while ReportGenerator (right) has several green and red lines.
![image](https://user-images.githubusercontent.com/919634/160593911-0bbecd7f-cace-4663-80ce-67e85663dd28.png)

Another example is [`MultiDimensionalArrayEquivalencyStep`](https://coveralls.io/builds/47490925/source?filename=Src%2FFluentAssertions%2FEquivalency%2FMultiDimensionalArrayEquivalencyStep.cs) which contains two types `MultiDimensionalArrayEquivalencyStep` and `Digit`.
coveralls has no coloring, while ReportGenerator has coloring in `FluentAssertions_Digit.html` and `FluentAssertions_MultiDimensionalArrayEquivalencyStep.html` (both included in the attached report.zip).

I'm not sure if this should be categorized as a broken or missing feature, that depends on whether multiple types per file is a supported scenario.

I hope this clears up the missing parts of my first question.

**Comment by afinetooth** [comment]
Hi @jnyrup. Thanks for the clarification. I see what you mean now.

It seems like a "broken" feature, since Coveralls does cover file stats for both line coverage and branch coverage if both are included in your LCOV file and you've enabled the setting, INCLUDE VENDOR DIRECTORY COVERAGE? (in your repo Settings). I believe you meet both of those conditions.

The issue though, I think, is not a bug in coveralls, per se, but the fact that I think you are sending multiple coverage reports for each source file in a single job. In that case, coveralls expects only one per job, so it is probably only processing the first (or last).

Can you verify that's the case?

The solution would be to send your coverage reports in parallel jobs, where each job contains one coverage report for each individual source file. 

Alternatively, the solution would be to merge all coverage reports into a single file on the CI side, so the same result happens: each source file is represented in the coverage report only once.

**Comment by jnyrup** [comment]
I've just enabled "Include Vendor Directory Coverage?" in the repo settings, that wasn't enabled before, but it doesn't seem to change anything. (I'm not really sure what that setting does though)

ReportGenerator merges the multiple Cobertura reports into a single lcov file (which contains both line coverage and branch coverage) and we then upload that single lcov file to Coveralls at the end of our CI pipeline.
So we're only sending a single coverage report to Coveralls.

By "each source file is represented in the coverage report only once" are you saying that having line below twice, because it contains two classes `MultiDimensionalArrayEquivalencyStep` and `Digit` is invalid?
```
SF:C:\dev\fluentassertions\fluentassertions\Src\FluentAssertions\Equivalency\MultiDimensionalArrayEquivalencyStep.cs
```
I've failed to find any specification on the lcov format, so I can't dig into whether the report we're uploading is valid.

cc:@eNeRGy164

**Comment by eNeRGy164** [comment]
What might be an issue is we run against multiple frameworks (net4x, net 6, etc.)
Maybe we should report per framework as a parallel run?

**Comment by jnyrup** [comment]
Seems like this was a problem with coverage reporter as upgrading to github-action@v2 and https://github.com/coverallsapp/coverage-reporter/issues/44 has solved the problem for us.

**Comment by afinetooth** [comment]
@jnyrup @eNeRGy164 thanks for the update. Sorry to have left you hanging on this one. 😔

**Comment by jnyrup** [comment]
No worries, we can't demand _anything_ when getting this for free.

**Comment by afinetooth** [comment]
Appreciate that. FWIW, we're finally getting into a position to respond to issues and feature requests in the way we've wanted to for years.(open source is just as important to us as paid as its part of our core mission.)
