### ISSUE TITLE
1 hour delay since DST

### ISSUE THREAD

**Issue by suculent** [lemurheavy/coveralls-public#1625]
Since there's been change from "winter" to "summer" time (from the UTC-based time to UTC-based time -1) here in Europe, I've noticed, that uploaded test results appear with 1-hour delay.

Before the DST change, uploaded results did appear in matter of minutes.

Is this because the time is somewhere parsed from somewhat incomplete String instead based on UTC timestamp?

**Comment by afinetooth** [comment]
Hi, @suculent. Just to clarify, you aren't saying that builds are taking longer to complete, right? Just that their creation / completion times appear to be `-1` hour off in UTC? 

Can you share an example?

FYI, we do not have any timezone settings at coveralls.io. Either for users or an individual repos. All times are shown in UTC. We obtain datetimes through our language's core library, but ultimately they come from the underlying system OS (Linux).

Thanks in advance for the clarification.

**Comment by suculent** [comment]
First of all, thanks a LOT for quick reaction! You're the best!

It's really not the builds, I'm talking about. The builds have start time and duration. Submission to Coveralls happens at the end of those events, to be the same page.

Current view in UTC+2 (DST):
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/221895/161111514-9c314dfa-6ec0-4998-b5f1-6fbc271c4dc0.png">

Actually the delay is just 30 minutes and not 1 hour, so it's not the DST. Is it just the processing time?
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/221895/161111687-f8ebdbaa-a55c-4695-a539-65e985c5122b.png">

**Comment by suculent** [comment]
Now, looking at the times, it’s not DST even not a 30 minutes! Just 7 which is OK. It seems it has been issue until yesterday for couple days and I didn’t have time to report it untill too late. Sorry.

**Comment by afinetooth** [comment]
No worries!

If you want some stats on your build times, let me know your Coveralls repo URL (or repo name and service). I can get you your last n builds---100 or 1,000---depending on how many you have.

If it's private or sensitive, you can send it to support@coveralls.io and mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1625).

**Comment by suculent** [comment]
The repo is open-source. 

https://github.com/suculent/thinx-device-api.git

There’s 10k builds in the history, but only last 1000 is relevant. 

Thanks.

**Comment by afinetooth** [comment]
Hi @suculent. I've attached stats on your last 1,000 builds here.

Most pretty normal (< 1-min). The longer times in Feb reflect a performance issue then that we've since resolved.

Let me know if you have any questions.

[last_1000_builds_suculent:thinx-device-api_2022-04-01.csv](https://github.com/lemurheavy/coveralls-public/files/8401117/last_1000_builds_suculent.thinx-device-api_2022-04-01.csv)

**Comment by suculent** [comment]
Awesome. And there it was 28-03-2022. Glad to know I'm not going crazy.

**Comment by afinetooth** [comment]
Aha. Yes, there’s a big anomaly that day, huh? It indicates a traffic surge, which we track with contemporaneous stats on our [status page](https://status.coveralls.io), but don’t keep historical stats on, so I don’t have a good picture of what happened besides, “heavy traffic.” 

FWIW, we have tuned our infrastructure to keep the majority of build times <5-min. (*Build times for larger projects and projects with parallel builds would increase roughly linearly from that range*), and to target a max build time of ~30-min during traffic surges, but there will always be outliers for reasons beyond our capacity to control.

I’m glad your build times have returned to normal. If they increase again for a period longer than 30-60 min, let us know.
