### ISSUE TITLE
Automate addition of Github organization private repo

### ISSUE THREAD

**Issue by dgmorales** [lemurheavy/coveralls-public#1626]
I am trying to automate github repository creation and its enablement on Coveralls.

I can successfully add the private repo with a POST on the /api/repos endpoint, and it returns a 201 response with the expected body. 

But then doing a GET on the repo after that returns 404. Doing a POST again returns 422 saying the name has already been taken. These things do not happen with a public repo. Public repos work great.

I then need to call https://coveralls.io/refresh?private=true, and then the GET works. But I can't do that using the API token used for the other calls.

Is there a way to refresh the new repo from the API? How can I automate it?

(I see the same problem reported years ago on https://github.com/lemurheavy/coveralls-public/issues/464, auto closed by bot.)

**Comment by afinetooth** [comment]
HI @dgmorales.

You need an additional token, a Personal Access Token (PAT), to read (`GET`) from the `/repos` endpoint. This should be the case in general, but I may be mistaken and it might only be absolutely required for private repos. This would be why you were able to create (`POST`) a new repo, but then, not `GET` it.

You can create a new PAT for yourself in your coveralls ACCOUNT page:
https://coveralls.io/account

Then you will want to pass that in the Authorization header, like this:

```
Authorization: token <your_PAT>
```

Here's a working example in cURL:

```
curl --location --request GET 'https://coveralls.io/api/repos/gitlab/my-awesome-group305/my-awesome-subgroup/my-awesome-subgroup-test-project-1' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token eOHdLJGkyIOirzbKfIJUau0D2CRPXLJCDfxyZ'
```

Here are the full instructions on working with the /repos endpoint:
https://coveralls.io/api/docs

Note: The Coveralls repo token is only required when POSTing to the `/jobs` endpoint.

> I then need to call https://coveralls.io/refresh?private=true, and then the GET works. But I can't do that using the API token used for the other calls.

For that call to work, you need an active web session, which means you need to have logged into https://coveralls.io, via Oauth.

**Comment by dgmorales** [comment]
@afinetooth thanks for such a fast response!

But I am already using a PAT, for both POST and GET. Showing as curl:

```shell
$ curl --location --request POST 'https://coveralls.io/api/repos \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my-token>' \
-d '{
  "repo": {
    "service": "github",
    "name": "my-org/example-app5",
    "comment_on_pull_requests": true,
    "send_build_status": true
  }
}'
# the above works, returns repo body

$ curl --verbose --location --request GET 'https://coveralls.io/api/repos/github/my-org/example-app5' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my-token>'

# returns 404
```

Calling the refresh private using the UI fix that. How can I do the same using my PAT?

**Comment by afinetooth** [comment]
Hmm, I can't reproduce this.

I request a private repo through the API (`/repos`) endpoint:

```
curl --location --request GET 'https://coveralls.io/api/repos/github/afinetooth/coveralls-node-demo-private' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my token>'
```

Successfully:

```
{
    "service": "github",
    "name": "afinetooth/coveralls-node-demo-private",
    "comment_on_pull_requests": true,
    "send_build_status": true,
    "commit_status_fail_threshold": null,
    "commit_status_fail_change_threshold": 10.0,
    "created_at": "2020-12-31T22:16:42Z",
    "updated_at": "2021-01-01T01:01:37Z",
    "id": 326117,
    "has_badge": false,
    "token": "<repo token>"
}
```

Then I revoke the Coveralls Pro Oauth app from my App settings at Github:
(Coveralls Pro is the Coveralls OAuth app that enables private scope access. Another app (Coveralls), covers public scope access.)

![Screen Shot 2022-03-31 at 2 02 33 PM](https://user-images.githubusercontent.com/918667/161149520-ddd4ae3d-72b7-4310-9e68-e3dd4a248923.png)

I verify that I cannot login to Coveralls without re-authing Coveralls Pro:

![Screen Shot 2022-03-31 at 2 08 26 PM](https://user-images.githubusercontent.com/918667/161149670-774db2fa-3fca-454d-8ca6-ee4cab81b8ff.png)

(But I do not authorize---I hit _Cancel_.)

Then I make the same request again:

```
curl --location --request GET 'https://coveralls.io/api/repos/github/afinetooth/coveralls-node-demo-private' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my token>'
```

And have success again:

```
{
    "service": "github",
    "name": "afinetooth/coveralls-node-demo-private",
    "comment_on_pull_requests": true,
    "send_build_status": true,
    "commit_status_fail_threshold": null,
    "commit_status_fail_change_threshold": 10.0,
    "created_at": "2020-12-31T22:16:42Z",
    "updated_at": "2021-01-01T01:01:37Z",
    "id": 326117,
    "has_badge": false,
    "token": "<repo token>"
}
```

I have always been under the impression that there is no relationship between the Coveralls Personal Access Token (PAT) and the same user's OAuth Token (from the given service), and this does seem to prove that, but I wanted to double check.

I think it's arguable that there _should_ be such a relationship, since the PAT represents the given user and should arguably reflect their current access. (But FWIW, there is no access to build data or source code through the API.)

And that *does* seem to be the behavior *you're* describing.

Given that, though---even assuming that's the way it works---I think you should be able to continue with your automation routine, as long as you first accept private scope (Coveralls Pro OAuth App) as the user who owns the PAT you're using. You could use a service account for your repo host as the Coveralls user, so that other developers on your team can access it if necessary. 

Is there something that would block you from doing that?

**Comment by dgmorales** [comment]
@afinetooth you say you can't reproduce this, but I see no mention to a POST on your message. 

Just:

1. Create a new private repo on Github      _(..... this is important, a new repo)_
2. Add this new private repo to Coveralls using the Coveralls API (POST)     _(...... works fine)_
3. Now GET the repo from Coveralls API. Don't do anything on the Coveralls UI    _(.... returns 404 for me)_
4. Refresh private repos on Coveralls (using the UI)
5. Retry the GET on Coveralls API      _(..... now it works, returns 200 with expected body)_

That's it.
 
- Do you see the same behavior?
- Is that what you expected?

_(sorry for not making the reproduction steps clear from the start)_

**Comment by afinetooth** [comment]
Hi @dgmorales.

You did a fine job of describing your steps. I think I was just being lazy and taking the first step for granted.

Here I will report on each step as I perform them:

> 1. Create a new private repo on Github (*..... this is important, a new repo*)

New private repo at Github:
https://github.com/afinetooth/coveralls-demo-ruby-private

> 2. Add this new private repo to Coveralls using the Coveralls API (POST) (*...... works fine*)

**POST request**:

```
curl --location --request POST 'https://coveralls.io/api/repos' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Authorization: token <my token>' \
--data-raw '{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null
    }
}'
```

**Result**: Success (200 OK)

```
{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null,
        "created_at": "2022-04-01T21:11:14Z",
        "updated_at": "2022-04-01T21:11:14Z"
    }
}
```

> 3. Now GET the repo from Coveralls API. Don't do anything on the Coveralls UI (*.... returns 404 for me*)

**GET request**:

```
curl --location --request GET 'https://coveralls.io/api/repos/github/afinetooth/coveralls-demo-ruby-private' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my token>'
```

**Result**: Success (200 OK)

```
{
    "service": "github",
    "name": "afinetooth/coveralls-demo-ruby-private",
    "comment_on_pull_requests": true,
    "send_build_status": true,
    "commit_status_fail_threshold": 75.5,
    "commit_status_fail_change_threshold": null,
    "created_at": "2022-04-01T21:11:14Z",
    "updated_at": "2022-04-01T21:11:14Z",
    "id": 369434,
    "has_badge": false,
    "token": "<repo token>"
}
```

// END

I'll stop there since the rest isn't required.

### Questions:

1) Per the [API docs for the `/repos` endpoint](https://coveralls.io/api/docs)---https://coveralls.io/api/docs---did you call `:service`, `:repo_user` and `:repo_name` in the URL?

2) Does your user have permissions to see the new repo at Github? (Even better is if they have Admin access, then they can do other things like roll the repo token.) The holder of the PAT must be the user (`:repo_user) OR belong to the org. Does your user have those permissions?

**Comment by afinetooth** [comment]
@dgmorales Hang tight. I just re-read my own comment and realized I did touch the UI in between steps. (I had to purchase a subscription for my personal user.) Running another test...

**Comment by dgmorales** [comment]
Anyway, answering your questions in advance:

1. For GET request, yes, for example: "https://coveralls.io/api/repos/github/my-org/example-app5". For the POST you just pass api/repos, as said by the docs.
2. Yes, I am an organization admin for my org.

**Comment by afinetooth** [comment]
> 1. Create a new private repo on Github (*..... this is important, a new repo*)

New private repo at Github:
https://github.com/afinetooth/coveralls-demo-ruby-private-001

> 2. Add this new private repo to Coveralls using the Coveralls API (POST) (*...... works fine*)

**POST request**:

```
curl --location --request POST 'https://coveralls.io/api/repos' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Authorization: token <my token>' \
--data-raw '{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private-001",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null
    }
}'
```

**Result**: Success (200 OK)

```
{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private-001",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null,
        "created_at": "2022-04-01T21:37:15Z",
        "updated_at": "2022-04-01T21:37:15Z"
    }
}
```

> 3. Now GET the repo from Coveralls API. Don't do anything on the Coveralls UI (*.... returns 404 for me*)

**GET request**:

```
curl --location --request GET 'https://coveralls.io/api/repos/github/afinetooth/coveralls-demo-ruby-private-001' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my token>'
```

**Result**: Success (200 OK)

```
{
    "service": "github",
    "name": "afinetooth/coveralls-demo-ruby-private-001",
    "comment_on_pull_requests": true,
    "send_build_status": true,
    "commit_status_fail_threshold": 75.5,
    "commit_status_fail_change_threshold": null,
    "created_at": "2022-04-01T21:37:15Z",
    "updated_at": "2022-04-01T21:37:15Z",
    "id": 369437,
    "has_badge": false,
    "token": "<repo token>"
}
```

// END

OK, so this time I didn't do anything with the UI.

But I _was_ logged in.

I will try again, _not_ logged in.

**Comment by afinetooth** [comment]
Ok, this time an extra step:

> 0. Log out of https://coveralls.io

Done.

![Screen Shot 2022-04-01 at 2 41 01 PM](https://user-images.githubusercontent.com/918667/161345037-17e9ce6d-cc63-496f-8fab-479128dbe28b.png)

> 1. Create a new private repo on Github (*..... this is important, a new repo*)

New private repo at Github:
https://github.com/afinetooth/coveralls-demo-ruby-private-002

> 2. Add this new private repo to Coveralls using the Coveralls API (POST) (*...... works fine*)

**POST request**:

```
curl --location --request POST 'https://coveralls.io/api/repos' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Authorization: token <my token>' \
--data-raw '{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private-002",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null
    }
}'
```

**Result**: Success (200 OK)

```
{
    "repo": {
        "service": "github",
        "name": "afinetooth/coveralls-demo-ruby-private-002",
        "comment_on_pull_requests": true,
        "send_build_status": true,
        "commit_status_fail_threshold": 75.5,
        "commit_status_fail_change_threshold": null,
        "created_at": "2022-04-01T21:46:18Z",
        "updated_at": "2022-04-01T21:46:18Z"
    }
}
```

> 3. Now GET the repo from Coveralls API. Don't do anything on the Coveralls UI (*.... returns 404 for me*)

**GET request**:

```
curl --location --request GET 'https://coveralls.io/api/repos/github/afinetooth/coveralls-demo-ruby-private-002' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: token <my token>'
```

**Result**: Success (200 OK)

```
{
    "service": "github",
    "name": "afinetooth/coveralls-demo-ruby-private-002",
    "comment_on_pull_requests": true,
    "send_build_status": true,
    "commit_status_fail_threshold": 75.5,
    "commit_status_fail_change_threshold": null,
    "created_at": "2022-04-01T21:46:18Z",
    "updated_at": "2022-04-01T21:46:18Z",
    "id": 369439,
    "has_badge": false,
    "token": "<repo token>"
}
```

// END

That's completely logged out of coveralls.io.

If we continue in an email thread, maybe I can examine your user to verify their token, and that they have private scope access to the repo(s) in question. I can also look for the 404 in our production logs to see if there are any clues there.

**Comment by afinetooth** [comment]
Customer requested update today.

I'll try to submit a PR tomorrow.

**Comment by afinetooth** [comment]
@dgmorales (also sent via email):

We just deployed the enhancement we discussed, so you should now be able to complete your use case as described here.

The least disruptive change for us was to make sure that, after the creation of any repo (by any means, including via API), we update the accessible repos of the **current user**.

For an API POST, the **current user** is the user that owns the **PAT** that came over with the `POST` request.

This ensures that the same user can (more-or-less) immediately `GET` the new repo via the API.

**Important note**: 
The update to the user's accessible repos happens via a background job that should be more or less immediate, but, during periods of heavy traffic, could take between 3-30-seconds, or perhaps longer in unusual circumstances. Just want to make you aware, as you'll want to give your script the time to allow for this, and that, under _unusually_ heavy traffic conditions, you may encounter a failure, and this would be the reason. That said, even in those conditions, the GET step should _usually_ be retry-able within a few minutes.

**I tested as follows**:

1) Logged out of coveralls.io:

![Screen Shot 2022-05-17 at 12 36 16 PM](https://user-images.githubusercontent.com/918667/168901877-f565094b-9ad8-4f7c-93f2-da6c83c560d4.png)

2) Created a **new private repo** at github: `coveralls-demo-ruby-private-008`:

![Screen Shot 2022-05-17 at 12 36 14 PM](https://user-images.githubusercontent.com/918667/168901977-5cf8a04c-2911-4543-837c-5d189fa6af3c.png)

3) `POST`-ed the new repo to https://coveralls.io/api/v1/repos (`200 success`):

![POST repo](https://user-images.githubusercontent.com/918667/168901736-d4b08ee7-705b-4026-a048-b1aa05e7e889.png)

4) Made `GET` request for the new repo (`200 success`):

![GET repo](https://user-images.githubusercontent.com/918667/168901761-1d98c5ab-03f8-4b5d-999e-a7efcbce20cb.png)
