### ISSUE TITLE
More complex webhook options

### ISSUE THREAD

**Issue by kizzie** [lemurheavy/coveralls-public#1628]
Heya,

I'd love to be able to send the webhook notifications through to one of our logging APIs but to do this I need to add some additional headers - is there any way to do this with the current config? Or is it on your radar somewhere?

**Comment by afinetooth** [comment]
Hi @kizzie.

I'll assume you're talking about our Notifications feature, specifically Webhook Notifications, which will send coverage updates in JSON format to any endpoint you configure in **Settings > Notifications > Webhooks**.

Unfortunately, there's no way to modify HTTP headers in the current UI. However, a solution that seems obvious to me would be to send the webhook notification to an iPaaS (integration-Platform-as-a-Service), like Zapier.com, where it will be the "trigger" to an "Action" that you should be able to configure with headers. 

Zapier has some generic Triggers and Actions. I have used their "Generic Webhook" Zap as a trigger to capture Coveralls Webhook Notifications, successfully, then sent the data on to other services. I'm sure there's a similar Zap, like a Generic HTTP Request, or the Generic Webhook itself, that you could use as an Action, add HTTP headers to it, and send it on to your own endpoint (which could be your logging service).

**Comment by kizzie** [comment]
I am currently thinking of sending it to a lambda type function to do exactly that! Glad to know I'm not just missing something entirely

**Comment by afinetooth** [comment]
@kizzie please share what you did if you're comfortable doing that, I'm sure other users would love to see your solution. Good luck.

**Comment by kizzie** [comment]
Oh I decided to go down another route entirely in the end - using coveralls for PR gatekeeping, but then pushing the metrics to the dashboard independently :)
