### ISSUE TITLE
How about issues on related coverall tools such as coveralls-node?

### ISSUE THREAD

**Issue by vikingair** [lemurheavy/coveralls-public#1647]
See here: [#331 | Is this repo not maintained anymore?](https://github.com/nickmerwin/node-coveralls/issues/331) (https://github.com/nickmerwin/node-coveralls/issues/331)

**Comment by afinetooth** [comment]
Hi, @fdc-viktor-luft.

We are behind on maintenance & support for some of the legacy integrations that originally came from coveralls or coveralls team members. In general, we're putting our limited resources behind this internal project, a cross-platform coverage reporter:
https://github.com/coverallsapp/coverage-reporter

That said, we don't intend to retire any legacy projects until the [universal coverage reporter](https://github.com/coverallsapp/coverage-reporter) is out of beta and supports 80%+ coverage report formats used by our different language communities. We will be putting more effort into promoting that project this fall, which will include soliciting contributions potentially incentivized by crowd-funding, free subscriptions and the like.

As for legacy integrations like:
- [node-coveralls](https://github.com/nickmerwin/node-coveralls)
- [coveralls-ruby](https://github.com/lemurheavy/coveralls-ruby)

We currently looking to promote more up-to-date and well-maintained forks of those projects, such as we do [here](https://docs.coveralls.io/ruby-and-rails) for [coveralls-ruby](https://github.com/lemurheavy/coveralls-ruby) with  [coveralls-ruby-reborn](https://github.com/tagliala/coveralls-ruby-reborn).

If you're looking for an integration that will support your project better, we'd encourage you to search through [forks of the base project](https://github.com/nickmerwin/node-coveralls/network/members), for example, [forks of node-coveralls](https://github.com/nickmerwin/node-coveralls/network/members).

If you or other users come across better maintained versions of an original project, we'd love to hear about them and promote them in our docs for the time being.

And if your coverage libraries already export reports in `LCOV` format, we'd encourage you to try the [universal coverage reporter](https://github.com/coverallsapp/coverage-reporter), which we hope will standardize, and greatly simplify, coveralls integrations across all of your projects.

**Comment by vikingair** [comment]
Thank you very much ❤️ 

Then I'll try the "universal coverage reporter"

**Comment by afinetooth** [comment]
Awesome. Let me know if you have any questions about it. If you're concerned about security there's a `checksums` branch that'll ensure secure downloads.
