### ISSUE TITLE
Issue when using coveralls.net

### ISSUE THREAD

**Issue by dejan-zdravkovski-snow** [lemurheavy/coveralls-public#1654]
Hello,

there is already an issue created on coveralls.net repo:
https://github.com/csMACnz/coveralls.net/issues/110

but I'm posting an issue here as well, since I assume it's not related to coveralls.net sdk.

For few days now, we're getting 400 Bad request on all .NET/C# source code base repos.
No changes in release versions being used for coveralls.net or dotnet-reportgenerator.
It looks like something changed on server-side endpoint.

Feel free if you need some more details.

Thank you in advance.

**Comment by Giorgi** [comment]
I have the same issue. Submitting the coverage information fails from Appveyor as well as my local machine

**Comment by afinetooth** [comment]
Thanks for the report. I will share these details in the other issue.

About 10-days ago, we migrated our app to different servers. Our DNS setup should have made this change invisible to end users, which it did for most users, but some users are reporting 404 Bad Request errors.

To address this we have purged cache and DNS cache at our edge service provider (Cloudflare), and we have recommended to end users that they clear any caches local to them, which could include: Browser Cache (for Web requests), Machine/OS-level cache, CI service cache, CI runner cache.

If after trying those things, users are still getting 400 Bad Request responses, in particular from the coveralls API at https://coveralls.io/api/v1, please let us know at support@coveralls.io. 

If you can provide a HAR file or verbose CI build log, that will help us investigate.

See my response in the other issue here:
https://github.com/csMACnz/coveralls.net/issues/110#issuecomment-1197064660

**Comment by Giorgi** [comment]
Hi James,

I deleted everything that I could delete on my local machine, and flushed the DNS cache but I still get the same 400 Bad Request error.

**Comment by afinetooth** [comment]
Hi @Giorgi. I think we're pursuing this together in email as well, which is fine. My next step is to test submitting your coverage report from my local machine where I'm not getting the 400 error. 

At the same time, I wonder if you've retried wince we purged DNS cache with our edge (& DNS) provider. I was hopeful about that step.

I'll make sure to report final outcome here as well as in email.

**Comment by dejan-zdravkovski-snow** [comment]
Hello @afinetooth ,
coveralls.net sdk has a new official nuget package version 4.0.1 published by the sdk owner yesterday, and using this version solves the coveralls issue.
I think this issue can be resolved, thanks for your collaboration.

**Comment by afinetooth** [comment]
Hi @dejan-zdravkovski-snow. That's great news. Thanks for the update!
