### ISSUE TITLE
BadRequest when trying to upload coverage report

### ISSUE THREAD

**Issue by tpodolak** [lemurheavy/coveralls-public#1658]
Hi
We've been using coveralls.io for years as part of [NSubstitute.Analyzers](https://github.com/nsubstitute/NSubstitute.Analyzers) pipline. Everything has been working great so far, however suddenly our [pull requests](https://github.com/nsubstitute/NSubstitute.Analyzers/pull/187) started failing during coverage report upload, with following response 
```
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
We didn't change anything in the coverage report generation or code responsible for upload(we use community created package https://github.com/csmacnz/coveralls.net for coveralls integration), so it is looks like that either there was a change in the API, or our code coverage report became invalid. Here is a payload sent by coveralls.net (captured from local machine, so some Appveyor specific bits might be missing)
[coveralls.txt](https://github.com/lemurheavy/coveralls-public/files/9330161/coveralls.txt)

Do you see any obvious issues with payload or can you point me where to look for an issue?

**Comment by afinetooth** [comment]
@tpodolak check out this issue to see if it matches yours:

https://github.com/csMACnz/coveralls.net/issues/110

We've seen it at least 2 other times in the past few weeks.

Let me know if it's something else.

**Comment by tpodolak** [comment]
Yes, that was it. Thanks for quick reply
