### ISSUE TITLE
Adding @coveralls user to private repo of organization uses paid license

### ISSUE THREAD

**Issue by elheck** [lemurheavy/coveralls-public#1664]
From the [documentation](https://github.com/marketplace/actions/coveralls-github-action) I understand that @coveralls user has to be added to the repository for access. This would use up one license of our github enterprise plan and effectively costing an additional 200$ a year on top of the coveralls org plan.

Am I understanding it correctly?

**Comment by afinetooth** [comment]
@elheck unfortunately, yes. I have come to understand that users are encountering this when they try to add the [Coveralls Bot](https://github.com/coveralls) to your repo [through their org](https://docs.coveralls.io/coveralls-notifications#how-can-i-avoid-giving-write-access-to-my-repo), which doesn't require giving the bot write access. 

However, you can avoid that by adding the bot directly to the repo(s):

![Screen Shot 2022-11-21 at 2 01 11 PM](https://user-images.githubusercontent.com/918667/203166770-ab7e1dc8-40b1-4a09-ad58-a4dcb9722dd4.png)

Please tell me if that's not the case for you.

AFAIK, that step will show you how many org seats you have left, but it won't use one for an outside collaborator.

Note that you'll need to add the bot with write privileges so it can leave PR Comments on your PRs. (Our current integration uses the [repo scope](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#:~:text=info%2C%20and%20gists)-,repo,-Grants%20full%20access) for Github OAuth Apps.)

We will be upgrading our integration with Github to leverage a Github App to send PR Comments, so you won't have to add the bot to your repos. We hope to release a beta in Jan. Let me know if I can add you to the beta list.

**Comment by elheck** [comment]
@afinetooth adding an external bot as outside collaborator unfortunately won't do it for us.
A GitHub App would be perfect, I would appreciate if you add me to the beta list, so I can evaluate it for our company.

**Comment by MGough** [comment]
> We will be upgrading our integration with Github to leverage a Github App to send PR Comments, so you won't have to add the bot to your repos. We hope to release a beta in Jan. Let me know if I can add you to the beta list.

Hi @afinetooth - I'd also be interested in being added to this beta list. I've been asked to evaluate Coveralls versus some alternatives. So far it's looking positive but this limitation may be a dealbreaker outside of my control, so if I can show progress towards the Github App approach it might make Coveralls a likely choice.
