### ISSUE TITLE
[bug] Coveralls API endpoint returns `null`

### ISSUE THREAD

**Issue by miguelnietoa** [lemurheavy/coveralls-public#1674]
Hello, I am getting "INVALID RESPONSE DATA" for my coveralls badge (with shields.io).
![image](https://user-images.githubusercontent.com/39246879/204359015-db5b7d69-515d-4b9e-8be9-5202c56a58c2.png)

**Helpful links:**
- Coveralls: https://coveralls.io/github/kommitters/kadena.ex
- Project: https://github.com/kommitters/kadena.ex
- How shields.io fetch data from Coveralls API: https://github.com/badges/shields/blob/master/services/coveralls/coveralls.service.js#L48-L63

---

**1.** Coveralls API endpoint returns `null`.
Request: `GET https://coveralls.io/github/kommitters/kadena.ex.json?branch=@`
Response: `null`

**2.**
If you enter this URL https://coveralls.io/github/kommitters/kadena.ex?branch=main
Coveralls does not show the builds:
![image](https://user-images.githubusercontent.com/39246879/204358651-dba9eca4-a054-48df-aee4-c4611420707f.png)

It seems like Coveralls does not recognize `main` as the default branch. 

**As additional info**, I noticed this happens after this PR: https://github.com/kommitters/kadena.ex/pull/140
Notice that the base branch changed, maybe that's the reason? 
![image](https://user-images.githubusercontent.com/39246879/204360634-fc0ad898-e702-4979-b0d1-2f04edd4a434.png)

---

Thanks for reading and hope this has a solution! 👍🏻

**Comment by afinetooth** [comment]
@miguelnietoa sorry for the delay here.

As of today I was not able to reproduce any of these issues, which is hopefully a good thing and, again I hope, suggests the issue may have been temporary?

For good measure, when this happens, it's always a good idea to re-sync your repo with Github, via [settings](https://coveralls.io/github/kommitters/kadena.ex/settings) (especially if you're aware of anything that may have changed on the Github side):

<img width="685" alt="Screenshot 2023-03-10 at 4 08 53 PM" src="https://user-images.githubusercontent.com/918667/224451792-35cf468e-eaf0-4b8b-a709-e357f933662e.png">

I did this (after not being able to reproduce any of the issues above, still), but we did register some change, however minor. But, after trying again, after that sync, still can't reproduce. 

Did this go away on its own, or did you have to take further measures to fix it?

**Comment by miguelnietoa** [comment]
Hey @afinetooth 👋🏻

Well, now it is fixed. I just re-sync via settings and in the next PR merged into main seems like the issue was fixed...

So yeah, it was temporary and now there is no problem! Hopefully, as you mention 😅

**Comment by miguelnietoa** [comment]
Closing this issue. Thanks @afinetooth
