### ISSUE TITLE
Doc https://docs.coveralls.io/api-reference  missing some informations

### ISSUE THREAD

**Issue by robsonpeixoto** [lemurheavy/coveralls-public#1681]
The documentation about https://coveralls.io/api/v1/jobs is missing a lot of informations.

1. Which status code can be returned e why?
2. What the response schema?
3. How to handle parallel builds?
4. How to get a job status? Is that possible?

**Comment by afinetooth** [comment]
@robsonpeixoto, sorry for the delay, but thanks for the input. We are working on a documentation update to be released this month (Mar). I will pass your request for more info on the `/jobs` endpoint on to our team working on that.

In the meantime, is there anything I can tell you right now that will help you with your current setup blockers?

**Comment by robsonpeixoto** [comment]
Hi @afinetooth, I'm not needing it anymore. Thanks.
