### ISSUE TITLE
Coverage is successfully posting to the API, but showing no data in the UI

### ISSUE THREAD

**Issue by nevinera** [lemurheavy/coveralls-public#1684]
We're trying to get our merged results posted into coveralls - we've got a script that performs the merging that looks like this:

```
require "rubygems"
require "bundler"
Bundler.setup(:test)

require "simplecov"
SimpleCov.collate(ARGV)
```

Which appears to do the job correctly. On the container in question, when we `bundle exec rake coveralls:push`, we get this output:
```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #7ed96b55-cde3-4871-8ff0-9f59c8321a07.1
[Coveralls] https://coveralls.io/jobs/112890793
Coverage is at 97.48%.
Coverage report sent to Coveralls.
```

But no new builds show up on the repository, and if we go to the url printed in the output there, it looks like this, appearing to show no file data at all:
<img width="1135" alt="Screen Shot 2023-01-13 at 2 41 30 PM" src="https://user-images.githubusercontent.com/366133/212405160-e697c2b0-5490-44f3-9fe9-e2c99a10a0e5.png">

If I get drop into the code on the container with a binding.pry [here](https://github.com/tagliala/coveralls-ruby-reborn/blob/main/lib/coveralls.rb#L35), the `result` looks like I expect - right set of files, accurate coverage percentages, etc. If I stop [here](https://github.com/tagliala/coveralls-ruby-reborn/blob/main/lib/coveralls/simplecov.rb#L82), I can see the api response is a 200, with this body: `{"message"=>"Job #7ed96b55-cde3-4871-8ff0-9f59c8321a07.4", "url"=>"https://coveralls.io/jobs/112892175"}` (no surprises there).

Everything seems like it's working _exactly right_.. except I can't see any useful information in the UI about those builds. 

(current versions of `coveralls_reborn` (0.25.0) and `simplecov` (0.21.2))

**Comment by avanbrunt-cb** [comment]
I am seeing the same issue with the following python package versions
```
coverage==6.5.0
coveralls==3.3.1

testingpython38 Submitting coverage to coveralls.io... 01:50 
testingpython38 Coverage submitted! 01:50
testingpython38 Job ##1001.1 01:50 
testingpython38 https://coveralls.io/jobs/113589086
```

**Comment by nevinera** [comment]
Oh, I meant to post back here! @avanbrunt-cb, I resolved this in my context by unsetting the `COVERALLS_PARALLEL` environment variable (which was set to "true" in my CI's config). I'm not sure why that would affect this behavior (and I couldn't find any difference in the api call being made), but the builds started showing up properly after that change.

**Comment by avanbrunt-cb** [comment]
hmm @nevinera I don't have that set either yet I only receive `No data available in table`

**Comment by tgrk** [comment]
We are facing the same issue (which started at the end of last year). Also not using `COVERALLS_PARALLEL` in our CI config.
