### ISSUE TITLE
Sign-in loop

### ISSUE THREAD

**Issue by edwh** [lemurheavy/coveralls-public#1686]
Hi there,

We have an open source repo which you are kindly providing Coveralls on, at https://coveralls.io/github/TheRestartProject/restarters.net.  When I try to sign in to Coveralls using either my personal GitHub account or an account at the organisational domain, I get stuck in a loop of this, which I can't get past:

![image](https://user-images.githubusercontent.com/56696/213242302-58f6d031-0a96-491b-8271-eb83af94b471.png)

I've tried revoking Coveralls access and reauthorising.

This means I can't see the line-by-line coverage.  Can you help?

**Comment by afinetooth** [comment]
Hi @edwh. Sorry for the delay here. It looks like you repo did not have an owner, which happens sometimes when users add repos to Coveralls.io via the API. Is that how you added this repo?

We leverage the token of the repo "owner" (the user who added the repo to coveralls.io) to perform certain Github API-related actions. When the owner is missing, sometimes authentication will fail.

I made on of your collaborators with a valid Github OAuth token the owner of the project and it seems to load fine now:
https://coveralls.io/github/TheRestartProject/restarters.net

<img width="1392" alt="Screenshot 2023-03-10 at 3 54 50 PM" src="https://user-images.githubusercontent.com/918667/224450653-f0dff4d3-6e68-44cc-b8ec-3448bc427932.png">

Let me know if that's not the case for you.

**Comment by edwh** [comment]
I can certainly see the line by line coverage now, so what you did worked.

I don't think I added it using the API, though - I used the web UI.

Thanks.
