### ISSUE TITLE
PR says "coverage remains the same", but it actually dropped.

### ISSUE THREAD

**Issue by guy-yogev-lmnd** [lemurheavy/coveralls-public#1688]
We added code with no test coverage, but the coverage drop wasn't detected.

Build: https://coveralls.io/builds/56310281

![SCR-20230126-i7v](https://user-images.githubusercontent.com/107366717/214821143-9b542e4e-9a63-4d29-8fb3-6de0362a6f72.png)

**Comment by afinetooth** [comment]
Hi @guy-yogev-lmnd. We got your support request to support@coveralls.io and have replied there.
