### ISSUE TITLE
Delete repo JS seems broken

### ISSUE THREAD

**Issue by snarfed** [lemurheavy/coveralls-public#1690]
Hi all! First, thanks for Coveralls, it's great!

It looks like your JS for the delete repo UI flow might be broken? I'm seeing this stack trace in the console when I enter the repo name in the confirmation prompt. Hope this helps!

```
Uncaught ReferenceError: does_match_to_delete_name is not defined
    setup_with_name https://coveralls.io/assets/application-3b3a9f76631600563eb584cec1a6dc5d4e7f1e8c17fb5e8d4566cdb186440b10.js:26
    dispatch https://coveralls.io/assets/application-3b3a9f76631600563eb584cec1a6dc5d4e7f1e8c17fb5e8d4566cdb186440b10.js:2
    handle https://coveralls.io/assets/application-3b3a9f76631600563eb584cec1a6dc5d4e7f1e8c17fb5e8d4566cdb186440b10.js:2
    nrWrapper https://coveralls.io/github/snarfed/bridgy-at/settings:12
```

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/778068/215305835-9520f860-6b81-4bb8-9a91-ab3f8e1e6606.png">

**Comment by afinetooth** [comment]
Hi @snarfed. Thank you! We're able to reproduce, so we've got someone on it. Should be fixed soon, but will update you here as well.

**Comment by afinetooth** [comment]
Hi @snarfed. This should be fixed. Would you mind checking on your end and letting us know if not?

**Comment by snarfed** [comment]
Yup, it works now, thank you!
