### ISSUE TITLE
Github Actions returns opaque 500 Error 

### ISSUE THREAD

**Issue by sam-wheeling** [lemurheavy/coveralls-public#1692]
Running our project locally I have been able to get my coverage report to upload to coveralls with the following commands:

`docker-compose exec cms-php composer run-script tests`

which runs

`"tests": [
			"cd tests ; ../vendor/bin/phpunit --verbose unit/"
		], `
		
and then

`docker-compose exec -e COVERALLS_REPO_TOKEN="INSERT_TOKEN_FROM_COVERALLS" cms-php composer run-script coverage`

which runs 

`"coverage":[
			"./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v"
		]`

when I run the same code with a custom Github Action, I get the "Server error occurred. status: 500 Internal Server Error"

This can been seen in our build runner 

``` - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=build/logs/clover.xml -v
 ```     
        

<img width="975" alt="Screen Shot 2023-02-06 at 3 03 46 PM" src="https://user-images.githubusercontent.com/105231470/217073505-451df27b-bd1a-43fa-8fd0-2b0e016ae781.png">

**Comment by sam-wheeling** [comment]
Note to self: Check GitHub for status update

Github Actions was having an issue yesterday around the time we were doing this

https://www.githubstatus.com/

**Comment by sam-wheeling** [comment]
Looks like its still happening.. going to go open an issue with github actions

**Comment by afinetooth** [comment]
Hi @sam-wheeling. Thanks for the update. Did you get this resolved?

**Comment by sam-wheeling** [comment]
@afinetooth looks like we had to delete the repo and start over..  got a new coveralls token and it seemed to go away.. but havent had issues since.. I can close this out..
