### ISSUE TITLE
500 signing in via github for trial account

### ISSUE THREAD

**Issue by alagos** [lemurheavy/coveralls-public#1693]
I'm in the process to integrate the coveralls service in one of the projects for the company where I work. 
We're using a trial and when I started with this some days ago I had some 500 as well at signing in time, but later they stopped.
Everything was working ok so far, but now, for some reason, I can't sign in anymore. 
I've tried removing coveralls and coveralls pro as authorised apps
<img width="1134" alt="Screen Shot 2023-02-10 at 4 51 15 PM" src="https://user-images.githubusercontent.com/475834/217996382-ecdf66a9-6f91-45d5-ba02-c9212617e36f.png">

also I've removed any coveralls cookie

<img width="732" alt="Screen Shot 2023-02-10 at 4 52 40 PM" src="https://user-images.githubusercontent.com/475834/217997160-182993e6-3e88-4bfb-b10a-d9552cf77084.png">

then I try to sign in with github

<img width="512" alt="Screen Shot 2023-02-10 at 4 54 32 PM" src="https://user-images.githubusercontent.com/475834/217997181-5dd1f59e-d1cd-4450-a400-d2a82261951d.png">
<img width="521" alt="Screen Shot 2023-02-10 at 4 54 56 PM" src="https://user-images.githubusercontent.com/475834/217997167-55defc45-dcc9-42ef-8f7a-93c10efffc78.png">

and this big guy stomps me

<img width="992" alt="Screen Shot 2023-02-10 at 4 55 24 PM" src="https://user-images.githubusercontent.com/475834/217997162-3b93f4e4-bdef-447e-b37d-f2491b6e8945.png">

so, no idea what else to do. Worth to mention the trial account isn't mine but for that `visfleet` organization you can see in one of the screenshots. 
Hopefully I hear you guys back soon, as we're evaluating with the trial if this service helps us in our development workflow.
Thanks

**Comment by afinetooth** [comment]
Hi @alagos. I was about to suggest that, as a paying customer (even on Trial), you can get a quicker response by submitting your issues to support@coveralls.io, but then I saw your recent submission there and wanted to let you know we will reply directly to it. Thanks.
