### ISSUE TITLE
SOC2 compliance?

### ISSUE THREAD

**Issue by Crell** [lemurheavy/coveralls-public#1694]
I am evaluating Coveralls (and similar tools) for my company.  One of the questions I've been asked is if it includes SOC2 compliance.  I haven't found anything in the documentation on that.  Does Coveralls have any SOC2 or similar compliance policies in place?

**Comment by afinetooth** [comment]
Hi @Crell we have a package we share with prospective customers performing security due diligence. If you don't mind sending your request to support@coveralls.io, we will share that with you. We do it through a third party that registers the distribution of that info for security purposes. Thanks.

**Comment by Crell** [comment]
Thanks!
