### ISSUE TITLE
Internal server error. Please contact Coveralls team.

### ISSUE THREAD

**Issue by dlech** [lemurheavy/coveralls-public#1708]
Our CI builds are failing today (didn't make any changes to coveralls config), so just doing what the error message says and making contact.

https://github.com/pybricks/pybricks-micropython/actions/runs/4832469595/jobs/8611286484#step:8:58

**Comment by samullen** [comment]
We're seeing a similar issue, but it's through GitHub actions. I'm not able to get to the lcov.info file, unfortunately:

<img width="953" alt="Screenshot 2023-04-28 at 11 13 31 AM" src="https://user-images.githubusercontent.com/59711/235199776-0baf7570-02ce-430b-a0f9-3fa68659faeb.png">

**Comment by noisersup** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/42322511/235203535-8cac8b43-f5eb-46a2-a430-928a6bb22443.png)

**Comment by skwashp** [comment]
My GitHub Actions are all failing with the following error:

```
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

Until today they worked fine.

**Comment by dcharkes** [comment]
Same for us, no changes to the configuration: https://github.com/dart-lang/native/actions/runs/4831943468/jobs/8612152056

**Comment by johnrb2** [comment]
I tried switching from `@master` to `@v2` and it didn't work. Ran with debug set to true and it still failed, and I didn't see anything wrong with the output it said at the bottom `⚠️ Internal server error. Please contact Coveralls team.
Error: Process completed with exit code 1.`

**Comment by cjstewart88** [comment]
![image](https://user-images.githubusercontent.com/534912/235215221-f55bbff5-c535-483e-b62e-5c2b9310d7b5.png)

We're having the same issue too.

**Comment by dlech** [comment]
The server issue seems to be resolved now.

**Comment by afinetooth** [comment]
Hello @dlech @cjstewart88 @johnrb2 @dcharkes @skwashp @noisersup @samullen (Cc: @mrexox ):

Thanks for reporting and sorry for the inconvenience.

We recently released two new versions (`0.3.8` and `0.3.9`) of the Coverage Reporter (the integration underlying the Coveralls Github Action), and we did see an issue with one of the new dependencies in `0.3.8`, so, since I see `0.3.9` in your screenshots, I suspect we didn't resolve that entirely.

If you can peg your version of the Coverage Reporter to `0.3.7` that should work as a temporary fix.

We'll update you here when we have a new release.

**Comment by afinetooth** [comment]
@ skwashp your issue (`422`) seems perhaps unrelated. Did it also just start today with no CI changes on your end?

If not, please you please share your Coveralls Repo / Build URL here, or to support@coveralls.io? Thanks.

**Comment by afinetooth** [comment]
NEVERMIND. I missed [your update](https://github.com/lemurheavy/coveralls-public/issues/1708#issuecomment-1528012871) @dlech. Thanks.

Operating under the assumption this was a temporary server-related issue.

Please let us know if you're still seeing it.

**Comment by mgdaily** [comment]
Also hitting a 422 here.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
resubmitting with id None
```

We're not using the official github action, but rather using the version from PyPI - 3.3.1

```
    - name: Generate and send coveralls report
      run: poetry run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

(full workflow here: https://github.com/observatorycontrolsystem/science-archive/blob/main/.github/workflows/build.yaml)

This is a new error as of today

**Comment by afinetooth** [comment]
Hello @skwashp are you also still seeing the same issues?

**Comment by woodsp-ibm** [comment]
Have the same issue in several repos eg https://github.com/Qiskit/qiskit-nature/actions/runs/4832024170/jobs/8616782439, https://github.com/Qiskit/qiskit-optimization/actions/runs/4831935328/jobs/8611894444?pr=501, https://github.com/Qiskit/qiskit-machine-learning/actions/runs/4831397835/jobs/8613246799?pr=610

Had been working earlier today
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/coveralls/api.py", line 294, in submit_report
    'Could not submit coverage: {}'.format(e)) from e
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

**Comment by anamileva** [comment]
Also still seeing this issue:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 4[22](https://github.com/blue-marble/gridpath/actions/runs/4832982418/jobs/8618771644#step:7:23) Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

https://github.com/blue-marble/gridpath/actions/runs/4832982418/jobs/8618771644

**Comment by skwashp** [comment]
@afinetooth still seeing 422s across the board. These are python jobs with no config changes for months.

**Comment by Beakerboy** [comment]
I reran a GitHub action that passed 3 weeks ago. Today I get:

    Traceback (most recent call last):
    [68](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:69)
    File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/cli.py", line 95, in main
    [69](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:70)
    result = coverallz.wear()
    [70](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:71)
     File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 257, in wear
    [71](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:72)
     return self.submit_report(json_string)
    [72](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:73)
     File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 293, in submit_report
    [73](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:74)
    raise CoverallsException(
    [74](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:75)
    coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
    [75](https://github.com/Beakerboy/MS-CFB/actions/runs/4623133199/jobs/8626677053#step:6:76)
    Error: Process completed with exit code 1.

**Comment by nhoening** [comment]
Same here, unchanged setup failing since two days or so. We were not using the Github Action, similar to @mgdaily.

**Comment by dgw** [comment]
Another Python project with the 422 Unprocessable Entity error, chiming in. Similar setup to @mgdaily's [posted above](https://github.com/lemurheavy/coveralls-public/issues/1708#issuecomment-1528103986), but not using Poetry. Full workflow: https://github.com/sopel-irc/sopel/blob/5c8202ec68e9705840f840179e6cadc0c5defac3/.github/workflows/ci.yml

Coveralls step has been unchanged since May 2021, working great until now:

```yaml
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
```

**Comment by SchrodingersGat** [comment]
We are also hitting the same issue over at https://github.com/inventree/inventree - anyone got a solid fix yet?

**Comment by skwashp** [comment]
As per the [incident on the status page](https://status.coveralls.io/incidents/y32m70t659tl) the 422 errors are being tracked under #1710.

**Comment by afinetooth** [comment]
Thanks, @skwashp. @SchrodingersGat @mgdaily, et. al., we believe a fix has resolved the issue, but are continuing to monitor:
https://status.coveralls.io/

There are indeed better updates with more context around this issue in #1710.

Regardless, we want to hear from you if you're a user of the coveralls-python integration with Github Actions for CI and are still experiencing the 422 (or other) errors. 🙏
