### ISSUE TITLE
coveralls fails with "422 Client Error: Unprocessable Entity"

### ISSUE THREAD

**Issue by andy-maier** [lemurheavy/coveralls-public#1709]
Since a few days, coveralls fails to upload from GitHub Actions as follows:
 
 ```
  coveralls --service=github
  shell: /usr/bin/bash -l {0}
  env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
    GITHUB_TOKEN: ***
    COVERALLS_PARALLEL: true
    COVERALLS_FLAG_NAME: ubuntu-latest,3.11,latest
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
resubmitting with id None
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/api.py", line 290, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
             ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

This happens on all Python versions we support (2.7, 3.5-3.11) and with and without `--service=github` specified.
The coveralls version is 2.1.2 for our minimum version runs and 3.3.1 for our latest version runs.

This started occurring only a few days ago. Before that, it ran fine.
The latest failing run with my attempts to fix it is: https://github.com/zhmcclient/python-zhmcclient/actions/runs/4839303086
The last run where it still ran fine is from 4/23 and is: https://github.com/zhmcclient/python-zhmcclient/actions/runs/4774941292 

I could not identify any relevant package version changes between the last run that worked and now.

**Comment by andy-maier** [comment]
I tried the recommendation in https://github.com/lemurheavy/coveralls-public/issues/1435#issuecomment-1335446698 but it did not help.

**Comment by andy-maier** [comment]
Sorry, wrong repo. This should have gone to TheKevJames/coveralls-python. Closing it.

**Comment by afinetooth** [comment]
All good, @andy-maier. We think this is actually being caused from our end right now and are looking for a fix. 

We think it relates to the issue in #1708 but noticed that when that issue resolved for users of the [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) and [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), it did not resolve for users of [coveralls-python](https://github.com/TheKevJames/coveralls-python).

I see you came back and opened #1710 about it, so we'll pick it up there.

**Comment by afinetooth** [comment]
We believe this issue has been resolved, but we are continuing to monitor:
https://status.coveralls.io/

If you are using the coveralls-python integration with Github Actions for CI, please let us know if the issue is not resolved for you: support@coveralls.io
