### ISSUE TITLE
422 error from Coveralls API using coveralls-maven-plugin and TravisCI

### ISSUE THREAD

**Issue by afinetooth** [lemurheavy/coveralls-public#1711]
From user @Glusk [here](https://github.com/lemurheavy/coveralls-public/issues/1710#issuecomment-1529926210):
https://github.com/lemurheavy/coveralls-public/issues/1710#issuecomment-1529926210

> I'm getting a very similar error when trying to push coverage report to Coveralls from my [Travis build](https://app.travis-ci.com/github/Glusk/srp6-variables/builds/262700090#L606):
> 
> ```
> [ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project srp6-variables: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (The commit  wasn't found on the repo anycable/anycableThe commit  wasn't found on the repo anycable/anycable) -> [Help 1]
> ```
> 
> I haven't changed any CI/CD configuration settings. The exact same configuration has worked for me as early as April 25 2023.

**Comment by afinetooth** [comment]
The conspicuous error here is:

> The commit  wasn't found on the repo anycable/anycable

When that coverage report is actually being submitted for:
https://coveralls.io/github/Glusk/srp6-variables

This _may_ relate to a temporary, or hard-coded, error message, because it's highly unlikely that we could ever have a duplicate repo token. 

**Update**:
I see that the other (open-source) repo mentioned:
https://coveralls.io/github/anycable/anycable

Has a `nil` token:

<img width="379" alt="Screenshot 2023-05-01 at 11 05 00 AM" src="https://user-images.githubusercontent.com/918667/235502721-275e21cc-e897-45cc-bc7c-9864663013c8.png">

@Glusk, can I ask: Are you passing a `repo_token` with your request?

_**Note**: It's a legacy condition that the CoverallsAPI will accept coverage uploads for open source repos from TravisCI, without requiring a value for `repo_token`. It's because TravisCI was our first supported CI service and, originally, only private repos required passing a `repo_token`._

**Comment by Glusk** [comment]
> @Glusk, can I ask: Are you passing a repo_token with your request?

@afinetooth No, I don't believe I am.

I'm not sure about the specifics, since it's only a plugin that I use. Here's what I've found on their [README page](https://github.com/trautonen/coveralls-maven-plugin):

> ### Complete plugin configuration
> ...
> | Parameter | Type | Description |
> | --------- | ---- | ----------- |
> | `serviceJobId` | `String` | CI service job id. Currently supported only with Travis CI. If this property is set, `repoToken` is not required. If not provided the supported service environments are used. | 
> | `serviceBuildNumber` | `String` | CI service build number. If not provided the supported service environments are used. |
> | `serviceBuildUrl` | `String` | CI service build url. If not provided the supported service environments are used. |
> | `serviceEnvironment` | `Properties` | CI service specific environment properties. If not provided the supported service environments are used. |
> | `repoToken` | `String` | Coveralls repository token. **Do not publish this parameter unencrypted in public GitHub repositories.** |

This section is also interesting:

> #### Configuration
> 
> If used as a standalone Maven build or with any continuous integration server other than Travis
> CI, the Coveralls repository token must be provided. This can be achieved by setting the
> configuration section in the plugin or setting the Maven property `repoToken` to your coveralls
> project repository token, using `-DrepoToken=yourcoverallsprojectrepositorytoken` when running the
> maven command. **Do not publish your repository token in public GitHub repositories.** If you do,
> anyone can submit coverage data without permission.
> 
> If you are using Travis CI, CircleCI, Codeship, Jenkins or Bamboo continuous integration services,
> no other configuration is required. The plugin's built-in service environment support take care of
> the rest. The plugin tries to find report files for any of the supported coverage tools and
> finally aggregates the coverage report. Java 8 is currently supported only by JaCoCo.
> 
> See [Complete plugin configuration](#complete-plugin-configuration) for all of the available
> configuration parameters.
> 

---

@afinetooth Are you saying I should try to reconfigure the plugin with the `repo_token`?

**Comment by afinetooth** [comment]
Hi @Glusk. Yes, I'm saying that, while it's a special case with TravisCI and public repos, it's really a best practice to send coverage reports with your `repo_token`, and I think it _will_ solve this issue for you. (It will at least get us past _this_ error, to a more useful one, if there _is_ an issue.)

While the Coveralls-facing parameter is called [repo_token](https://docs.coveralls.io/api-jobs-endpoint#:~:text=TYPE-,repo_token,-required), it looks like the [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin) wants you to pass that as [repoToken](https://github.com/trautonen/coveralls-maven-plugin#configuration:~:text=If%20used%20as,the%20maven%20command.).

You can find the value for your repo token on [your Coveralls Repo Page](https://coveralls.io/github/Glusk/srp6-variables).

**Comment by Glusk** [comment]
It looks like that did the trick, thanks!

**Comment by afinetooth** [comment]
@Glusk great! Glad to hear it.

I'll close this but just reopen / submit a comment if happens again.
