### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

### ISSUE THREAD

**Issue by JacobBas-Coalitioninc** [lemurheavy/coveralls-public#1713]
On python 3.8 with coveralls 3.3.1 we are getting 500 errors why trying to call to the `https://coveralls.io/api/v1/jobs` endpoint.

```
Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/coveralls/api.py", line 290, in submit_report
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/usr/local/lib/python3.8/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/usr/local/lib/python3.8/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
1
```

This issue began happening sometime around May 20th

**Comment by afinetooth** [comment]
Hi @JacobBas-Coalitioninc. 

Is this still happening? Often a `500` error from the Coveralls API is temporary, and I'm not aware of a known incident on Sat, May 20.

If so, then, just to clarify, you are using the [coverall-python](https://github.com/TheKevJames/coveralls-python) integration here, correct? That is one of our community-created [Language Integrations](https://docs.coveralls.io/integrations#language-integrations), so not an [official integration](https://docs.coveralls.io/integrations#official-integrations) maintained by us, but one of the most popular and well-maintained community-created [Coveralls Integrations](https://docs.coveralls.io/integrations).

Given that context, you might get better help, faster, by submitting an issue to [the coveralls-python issues board](https://github.com/TheKevJames/coveralls-python/issues).

That said, if the error is being thrown from the Coveralls API (looks likely) we can probably help determine why. However, to do so we'll need a look at your CI config and/or a verbose build log.

Can you please share:

1. **The Coveralls URL for your repo and the Coveralls URL for your last successful Coveralls build for that repo**. (If the project is private, or sensitive, please send it to support@coveralls.io and just reference this issue.)
2. **Your CI service and CI config file**. Particularly helpful if you're doing any custom configuration such as setting any Coveralls-related environment variables.
3. **A verbose build log**. Ideally, you'll re-run the same build, but invoke the `debug` option as described [here in coveralls-python docs](https://coveralls-python.readthedocs.io/en/latest/troubleshooting.html?highlight=debug#troubleshooting). Note that coveralls-python's `debug` mode won't actually submit coverage to Coveralls; but it will show us exactly what you're sending to the Coveralls API, which will be helpful.

**Comment by JacobBas-Coalitioninc** [comment]
Hey @afinetooth, sorry for the late response. Was OOO last week.

This seems to have resolved itself while I was away, but we were seeing these 500's throughout multiple repositories within our organization.

I do believe that all of the affected repositories are using [coverall-python](https://github.com/TheKevJames/coveralls-python). Seems like we may want to switch to using the Github Action since this integration may be better.

Since we are not getting the errors anymore I can't get those detailed logs, but will document this thread within a run-book for future reference.

Thank you for the response!

**Comment by afinetooth** [comment]
Hi, @JacobBas-Coalitioninc. Sounds good. Glad to hear it's working. 

If you do decide to transition, let us know if we can help with your first project.
