### ISSUE TITLE
Allow opening files from the file tree in a new tab

### ISSUE THREAD

**Issue by mrc0mmand** [lemurheavy/coveralls-public#1717]
Hey,

I have a minor request for the web interface - would it be possible to allow opening files from the file tree in a new tab? I.e. with

![image](https://github.com/lemurheavy/coveralls-public/assets/679338/ad0303b6-9ee6-427f-8fbd-0c0f67fa7994)

I'd like to open the `activate.c` file in a new tab, but neither middle-mouse-button nor ctrl-click does that, the latter one opens the file in the current tab instead. I quite often find myself in a situation where I need to open multiple files from the tree and this makes it slightly inconvenient.

Thanks!

**Comment by afinetooth** [comment]
Hi @mrc0mmand. Yes, I get stuck by that one myself. I have made this request on your behalf, which updates an outstanding backlog item. I think that, because of the way that **tree** view is rendered, it's non-trivial for us (those links aren't HTML links); otherwise it would have been done by now. In the meantime, just so you're aware of a potential workaround, it _is_ possible to right-click on the same files in the **table** view---but I do understand that, per your request, it would be most useful to be able to do so from the **tree** view.

**Comment by mrc0mmand** [comment]
> Hi @mrc0mmand. Yes, I get stuck by that one myself. I have made this request on your behalf, which updates an outstanding backlog item. 

Thank you!

> I think that, because of the way that **tree** view is rendered, it's non-trivial for us (those links aren't HTML links); otherwise it would have been done by now. 

Yeah, I suspected the solution would be non-trivial, as it would be already implemented otherwise.

> In the meantime, just so you're aware of a potential workaround, it _is_ possible to right-click on the same files in the **table** view---but I do understand that, per your request, it would be most useful to be able to do so from the **tree** view.

Indeed, being able to do that from the tree view would be ideal, especially when it comes to projects with a slightly more involved tree structure (systemd), where the table view is a bit unwieldy.

**Comment by afinetooth** [comment]
Hi @mrc0mmand. I'm happy to report that the ability to right-click on files in the TREE view was added by one of our engineers last night. They saw how to do it and just did it. (I ❤️ our team.)

Example:
https://coveralls.io/builds/60576062

<img width="997" alt="Screenshot 2023-06-13 at 11 12 54 AM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/f9ece854-1942-4d52-8b9a-e73986746e28">

**Comment by mrc0mmand** [comment]
> Hi @mrc0mmand. I'm happy to report that the ability to right-click on files in the TREE view was added by one of our engineers last night. They saw how to do it and just did it. (I heart our team.)
> 
> Example: https://coveralls.io/builds/60576062
> <img alt="Screenshot 2023-06-13 at 11 12 54 AM" width="997" src="https://user-images.githubusercontent.com/918667/245567912-f9ece854-1942-4d52-8b9a-e73986746e28.png">

I can confirm that it indeed works, thanks a lot (and please send a big thanks to the engineering team)!

**Comment by afinetooth** [comment]
Excellent. Have done, thank you!
