### ISSUE TITLE
Support file encoding

### ISSUE THREAD

**Issue by laingsimon** [lemurheavy/coveralls-public#1718]
Is there a means to specify the encoding that the file should be displayed using? Or is there an issue rendering UTF-8 file content?

See this file:
https://coveralls.io/builds/60682682/source?filename=CourageScores%2FClientApp%2Fsrc%2Fcomponents%2Fdivision_fixtures%2Fsayg%2FPlayerInput.js#L194

Unicode emoji characters are shown incorrectly, see below. The file is encoded in UTF-8, without a BOM.

![Screenshot_2023-06-12-22-16-05-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/lemurheavy/coveralls-public/assets/2243314/fac0f2f5-71fb-4319-8184-e6f54fe52cb3)

The source file is rendered correctly in GitHub directly
![Screenshot_2023-06-12-22-19-21-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/lemurheavy/coveralls-public/assets/2243314/68de5c92-fdae-4d0c-a664-6d3c735fff77)

This sounds similar to https://github.com/lemurheavy/coveralls-public/issues/273

**Comment by afinetooth** [comment]
Hi @laingsimon. Thanks for reporting this, with an example. I've created an internal ticket and will follow-up when its updated.

**Comment by nebolsin** [comment]
@laingsimon thank you for bringing this to our attention, this should be fixed now. Please, check it out and feel free to re-open the issue if anything doesn't look right still.

**Comment by laingsimon** [comment]
Thanks for your support and quick response, all working as expected.

**Comment by afinetooth** [comment]
Thanks, @laingsimon and @nebolsin!
