### ISSUE TITLE
Can't add a job to a build that is already closed. (again)

### ISSUE THREAD

**Issue by thibaultcha** [lemurheavy/coveralls-public#1720]
Hi there,

Opening a new issue to resume #1716 which isn't getting anymore attention since it has been closed.

However, two more issues persist:

1. The proposed fix in #1716 does not work with GitHub's [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) ([detailed here](https://github.com/lemurheavy/coveralls-public/issues/1716#issuecomment-1622852522))
2. The proposed fix also does not work when one or more of the CI jobs fails and the build is restarted, whether in a PR or even in the main branch. In other words, any single job failure will cause all subsequent restarts of the jobs to systematically fail at the "coveralls upload" step. [Detailed here](https://github.com/lemurheavy/coveralls-public/issues/1716#issuecomment-1613941964)

**Comment by afinetooth** [comment]
HI @thibaultcha. I had missed this new issue and just re-opened and continued the thread in #1716. It looks like you replied there as well, so let's continue there if that makes sense. We can keep this open for now / close it later if we're able to resolve things in #1716 (I also directed our engineers to #1716, so they should reply there.)
