### ISSUE TITLE
API Tokens are not working

### ISSUE THREAD

**Issue by CarlosCondor** [lemurheavy/coveralls-public#1727]
Since few days, API tokens are not working. 

We tried two ways of auth:

https://coveralls.io/github/org/repo.json?repo_token=XXXXXXX

and

using header Authorization: token XXXXXXXX

we tried generating some new tokens and those appears as "Never used".

API response is "Acces denied".

If i'm logged in to coveralls.io and I try to GET the url without authorization headers nor query param, its works because i'm previously logged in.

🤔

**Comment by afinetooth** [comment]
@CarlosCondor Can you please share your repo / org?

If you have a subscription (private repos, sensitive data) you can get priority support through support@coveralls.io.

Thanks.

**Comment by mrexox** [comment]
We had an issue with access to private repos, but now it must be resolved. Could you please check if API works for you now?

**Comment by CarlosCondor** [comment]
@mrexox It's working again, thanks you all.

@afinetooth we also sent an email to support but we could noticed the fix before your anwser (in your anwser, 1 day after the fix, you mentioned you couldn't reproduce the error)

Thanks again

**Comment by afinetooth** [comment]
Thanks for the update, @CarlosCondor!
