### ISSUE TITLE
Unable to access private repositories

### ISSUE THREAD

**Issue by brookslyrette** [lemurheavy/coveralls-public#1728]
Since 2023-08-22 we can not access our private repositories. We can list them, and refresh the list but when clicking on the details for a given project we get this error:

![Screenshot 2023-08-24 at 10 32 22 AM](https://github.com/lemurheavy/coveralls-public/assets/1881100/d13bb206-cc16-4fae-924a-858637bab040)

Clicking Enable Private Repo Access reloads the page with the same error message.

**Comment by afinetooth** [comment]
@brookslyrette Quick question: This public issues board is for free / public / open-source subscriptions, which don't have private repos.

If you have private repos that indicates you're a customer from a paid subscription.

In that case, you can get priority support through support@coveralls.io.

Can you share the (paid) subscription and repo your example comes from? 

Again, if private or sensitive please email us at support@coveralls.io. You can just reference this issue for background.

**Comment by tjchambers** [comment]
I also have same problem and got no response from support@coveralls.io. Please suggest an alternative.

**Comment by brookslyrette** [comment]
Same. I emailed support over 24 hours ago

**Comment by mrexox** [comment]
Thank you for reporting this issue. Could you please check if your repos are accessible now? We had an issue with access to private repos but now it must be resolved.

**Comment by tjchambers** [comment]
Works for me now. Please explain why response took So long.

**Comment by brookslyrette** [comment]
Working now, thanks for fixing

**Comment by afinetooth** [comment]
@brookslyrette and @tjchambers just want to apologize on behalf of Support here. We've been working through a larger than normal backlog of requests here and are simply behind, which is why we had not yet responded to your email requests. I'm sorry this affected you. We've reached out to both of you individually.
