### ISSUE TITLE
New in and Github Organisation repos won't load

### ISSUE THREAD

**Issue by Hannahmc8** [lemurheavy/coveralls-public#173]
Hi I've just signed up and the Repos for my org in github don't appear for me to sync them?

**Comment by GochoMugo** [comment]
> @jails commented:
>
> Sorry just see I was not a "publicized member" so I just clicked on "publicize membership" on the organization's member list and it's working fine now. Thanks.

This should really be put somewhere easily accessible :eyes: . Wasted an hour hitting the **refresh** and **sync** buttons for nothing!!!
