### ISSUE TITLE
I can't add any repository from GitLab anymore

### ISSUE THREAD

**Issue by ericmorand** [lemurheavy/coveralls-public#1738]
I'm unable to add repository from GitLab anymore. Typically, I'd like to add **NightylCommit/Twing** repository to Coveralls:

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/450c68bf-7865-4d09-aac6-e7ec20156f46)

When I click on the switch, I'm redirected to an authorization page on GitLab:

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/39f26a25-9379-4f3e-8705-9548d406ebda)

I click Authorize...and I'm redirected to Coveralls:

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/41304dde-1b08-46d5-9ef6-2c8e6a8549cf)

But the repo is still not added:

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/450c68bf-7865-4d09-aac6-e7ec20156f46)

No matter how many times I retry, the result is the same.

Not that every time I click on the Authorize button, the `Coveralls` application authorization date is updated on my GitLab profile:

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/3a83bd68-6f6d-45e5-9409-9202180aa6ba)

It looks like it is a new application ID that is authorized every time or something.

**Comment by ericmorand** [comment]
Can someone help? We have no coverage emitted anymore because of this issue.

**Comment by afinetooth** [comment]
Hi @ericmorand. Thanks for reporting. Apologies for the inconvenience. We're on it. We are challenged by team availability over the US holiday (Thanksgiving), but we're aiming to get it resolved for you by Mon.

**Comment by ericmorand** [comment]
Oh yes of course, I forgot about the US holidays. Thanks for the head up, enjoy the holidays and let's see how it goes next week. 🤗

**Comment by afinetooth** [comment]
Still WIP on this @ericmorand . Will update you as soon as there's a change from engineering. In the meantime, I'm trying to get you a workaround from the Support side. Appreciate your patience. 🙏

**Comment by ericmorand** [comment]
Fantastic. Thanks a lot. Note though that we don't have public coverage for Twing - especially - but it is OK because we are putting the next big release and it is still an alpha - so public coverage is not something that is blocking us. Take your time.

**Comment by afinetooth** [comment]
@ericmorand Apologies, I forgot to update you that this was fixed last TUE on NOV 28. Can you please verify and update me if that's not the case for you?

I'm going to close this, but please just reply to re-open.

**Comment by ericmorand** [comment]
Amazing!!! Thanks a lot. I was able to add twing and twig-lexer repositories. 🎉 

![image](https://github.com/lemurheavy/coveralls-public/assets/125664/7098877c-767d-4a31-9996-86900dce0c5a)

**Comment by afinetooth** [comment]
Nice. That's great. Thanks for the update!
