### ISSUE TITLE
Coveralls GitHub actions are stuck forever

### ISSUE THREAD

**Issue by anton-patrushev** [lemurheavy/coveralls-public#1742]
We have 2 things integrated into our repo
1. Total coverage check on PR
2. Patch coverage check on PR

Both of them have been stuck last days.

Sometimes `coverage/coveralls` (check for a total coverage) is resolved. But the patch coverage check (`coverage/coveralls/patch` was not resolved any single time for the last 1-2 weeks) 

<img width="837" alt="image" src="https://github.com/lemurheavy/coveralls-public/assets/62186274/08a32c1c-4292-472a-bb77-8e74f42a2434">

**Comment by afinetooth** [comment]
HI @anton-patrushev. I included you on a conversation about a known issue with build and patch status updates, where we're chasing a race condition that occasionally affects certain builds in certain repos. 

That said, this sounds like a permanent / persistent issue. 

We have been working to clear the race condition lately. Can you tell me if this has resolved to any degree in the last 24-48 hrs?

I believe I know which org and repo you're referring to and the builds I checked from today, at least, look normal from our end (I can see their final build status and patch status records were created). As we can't see your commits/PRs at GitHub, you will need to confirm for me what status updates you received for those builds.

If you could mention the build ID in your response that would be very helpful.

If you'd rather keep your (private) project info private, please follow up with a message to support@coveralle.io and you can just mention this public issue.

**Comment by anton-patrushev** [comment]
I believe it was restored ~1 month ago. Coveralls checks are working fine right now. Thanks!

The only issue we have right now is that our total coverage (according to the coveralls report) sometimes went down without explicit reasons while our real test coverage is still on the same level. Coveralls report it went down to about `5-10%`.
