### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jcubic** [lemurheavy/coveralls-public#1784]
The [status](https://status.coveralls.io) says that everything is ok, but the webiste is down.

![Przechwycenie obrazu ekranu_2024-12-09_17-11-21](https://github.com/user-attachments/assets/634221e4-00a9-4851-8660-9099f19e4924)

**Comment by afinetooth** [comment]
@jcubic Thank you. This appears to be a partial outage. For instance, I am able to load the app after logging in: 

<img width="1392" alt="Screenshot 2024-12-09 at 9 32 02 AM" src="https://github.com/user-attachments/assets/693a8006-87f0-4ac3-92d5-d733e38f3994">

But having tried from an other IP address, I see the error on the home page.

Are you able to login or access any other app pages besides the home page?

We have posted the incident on our status page here:
https://status.coveralls.io/

You can subscribe to updates there.

**Comment by afinetooth** [comment]
@jcubic Are you able to access https://coveralls.io via an Incognito browser tab? How about the app, upon login.

I have had consistent success with that, so we are investigating an issue with current sessions. 

We have deployed no code changes since Fri.

**Comment by afinetooth** [comment]
**Update**:
We have deployed a fix and are monitoring to verify.

**Comment by jcubic** [comment]
I needed to remove all the stuff the website was adding into localstorage and cookies and now it works.

I was not asked to login via GitHub when clicking sign in, it only redirected immediately. Maybe the website was thinking that I'm login, but there was no token from GitHub.

**Comment by afinetooth** [comment]
@jcubic thanks for the update. Glad you're in.

We think there was an underlying data issue that might have surfaced in a stored cookie value (or not), but either way, it should be resolved.

Thanks for the heads up!

Closing this. 

If anyone experiences anything like the inability to login, or a 500 error while trying to access your Coveralls Dashboard _after_ logging in, please reach out to us at support@coveralls.io.
