### ISSUE TITLE
Can't add public repo's belonging to my organization

### ISSUE THREAD

**Issue by shahata** [lemurheavy/coveralls-public#196]
Do I need to purchase a subscription also if I want to track coverage of public repositories belonging to an organization? I thought a subscription is only required for private repositories and open source repo's are always free....

**Comment by rreitmann** [comment]
Hi, I have exactly the same problem. I am the owner of the organization dzhw and we currently have two public repositories. Non of them is available in coveralls. Do I really need to grant coveralls pro access, although they are public?

**Comment by rreitmann** [comment]
Sorry, just saw the option of making a membership public here: https://github.com/orgs/dzhw/people
Now it works.
