### ISSUE TITLE
Can't get to GitHub Organization repos

### ISSUE THREAD

**Issue by nwilson-eol** [lemurheavy/coveralls-public#199]
My GitHub user, nwilson-eol, is an owner of the EOL GitHub Organization, but when I go to Coveralls and click on 'REPOS' all I see are the GitHub repos that I own.  I was trying to add the repo EOL/taxon_reporter (https://github.com/EOL/taxon_reporter).  One of the other owners of the EOL organization (dimus) can see all the repos in the EOL organization and was able to add the repo with no problem.

A few other possibly relevant details:
1) Initially I wasn't seeing any repos at all, but this user didn't have any of its own repos.  After adding a couple they showed up, but I still can't see the ones that are in the organization.

2) I have a second GitHub user, mo-nathan, that is an owner of the Mushroom Observer GitHub Organization (https://github.com/MushroomObserver).  This user had no problem setting up coveralls for the project MushroomObserver/taxoneval repo (https://github.com/MushroomObserver/taxoneval).

3) The nwilson-eol user has been given access to a private repo: https://github.com/vickenstein/Seabase
All of the other repos associated with either of my users are public and open source.

Any ideas what might be going on?

Thanks!
-Nathan

**Comment by chfw** [comment]
Still not able to get my organisation after making membership public. Does it matter if I am the owner or not? The repo in question is: https://github.com/pyexcel/pyexcel

**Comment by Bilge** [comment]
Some of my organization's repos are not appearing no matter how many times I sync.

**Comment by chasevida** [comment]
Hey, I'm pretty much having the same problem. I signed up for a plan and am now paying but cannot even see the organisation I'm paying for - it disappeared from the available list. So I've been billed now for something that I can't and haven't used.

My team is large and I cannot get each of them to make their membership public, nor does the `https://coveralls.io/refresh?private=true` trick work. I've tried the suggested steps in #692 also which haven't worked either.

**Comment by chasevida** [comment]
Hmm... I had to remove remove all restrictions for third-party applications access. Not sure I'm comfortable with this but it worked temporarily.

**Comment by jescalan** [comment]
Also having this issue

**Comment by SSUHan** [comment]
Removing all restrictions solved this problem for my case.
So I tested that after linking between slack and github, I resetup restriction. 
Then, it works well.

**Comment by neilepalmer** [comment]
Removing restrictions definitely worked - re-enabling them afterwards recreated the problem for me.

**Comment by LiHaoTan** [comment]
I also faced the same issues and could get the organization repos to show up for Github.

Here's the solution that worked for me:
1. Upgrade the OAuth token to allow private access: https://coveralls.io/refresh?private=true
2. Re-authorize Github 3rd-party access: https://coveralls.io/reauthorize/github
3. Unlink the Github account: https://coveralls.io/account

Account will get logged out.

4. Now sign in with Github again.
5. The organization repos should now show up on: https://coveralls.io/repos/new

**Comment by harwoeck** [comment]
@LiHaoTan Fixed my problem! thx 👍

**Comment by hardersen** [comment]
@harwoeck worked for me as well - intuitive...

**Comment by anjin** [comment]
The reason this sometimes causes hiccups is that we don't want to force every user to upgrade their GitHub OAuth scope since for private repos we have to use the scope that GitHub provides - which also allows Coveralls write access to repos. We don't use that write access, but we need that level of scope just to read the source files. 

We've asked GitHub a number of times to provide an OAuth scope that would be read only, and if they implemented that we'd switch to that and force everyone through the better defined flow on every sign-in for every user...whether accessing private repos or not. But it seems pretty onerous to force every user to approve Coveralls to have write access to source code if they are only consuming data regarding open-source projects.

**Comment by kirill-chilingarashvili** [comment]
I faced the same issue
I had to go through the following steps:
1) make membership public
2) revoked access for Google Cloud Platform https://github.com/settings/applications#authorized
3) tried to connect to github from GCP - and on confirmation page specifically had to click "grant" next to organization, and then clicked allow for granting access to my repos and granted org repos
