### ISSUE TITLE
Can't add a repo from my organizations

### ISSUE THREAD

**Issue by arikfr** [lemurheavy/coveralls-public#206]
I want to add a repo from one of my organizations, but I only see repos from my own account and some other repos I have access to. But I don't see any repos from the organizations I'm member of or manage.

**Comment by paranoiabla** [comment]
Hello,
I have the same problem - "The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API."
I tried logging-out and logging-in but it didn't work.

**Comment by nickmerwin** [comment]
@paranoiabla what's the repo in question?

**Comment by paranoiabla** [comment]
nemesis-platform (it's a private repo)

**Comment by nickmerwin** [comment]
@paranoiabla ok could you email me the details (support@coveralls.io) and include a link to the repo on Coveralls?
