### ISSUE TITLE
Partial line coverage

### ISSUE THREAD

**Issue by bfontaine** [lemurheavy/coveralls-public#216]
[Cloverage](https://github.com/lshift/cloverage) is a form-level Clojure test coverage tool which [now](https://github.com/lshift/cloverage/pull/39) supports Coveralls, but because you don’t support partial line coverage, it relies on a trick where we use the hits count to tell if the line is fully covered (`2`), partially covered (`1`), or not covered at all (`0`). Do you plan to support partial line coverage in the future?

**Comment by cichli** [comment]
:+1:

**Comment by sagotch** [comment]
I know this has been here for two years now, but it stills an issue for many people...
