### ISSUE TITLE
No relevant lines does not mean 0% coverage, but it actually does.

### ISSUE THREAD

**Issue by sagotch** [lemurheavy/coveralls-public#218]
Sending data to you v1 API, I ran an unexpected behavior.

Look at https://coveralls.io/builds/522707 and see `src/tomlLexer.mll   69  0   0   0   0.0`

I have a file with no relevant line. I probably could remove it from data I send to coveralls, but if I do not, it should not be a 0%, but do not score or score 100%.

EDIT: I am not sure if it modifies the final score (I think it does not).

**Comment by timholy** [comment]
This doesn't harm the "final score," but in a large project with hundreds of files, it can mean that the first page (or first several pages) are dominated by files with 0/0 coverage.

It might be nicer to report the coverage for such files as "NaN" (or something) and move them to the end of the list (after the 100% coverage files).
