### ISSUE TITLE
Support for coverage on different languages?

### ISSUE THREAD

**Issue by justinabrahms** [lemurheavy/coveralls-public#237]
I have a repo with both javascript test coverage (currently using coveralls) and python coverage (not using coveralls). If I send reports via the relevant coveralls plugins for each language, will one overwrite the other? Be presented in aggregate? Does it just work?

**Comment by josephspurrier** [comment]
I was able to achieve this for Go and JavaScript (Vue) by converting Go to lcov format (https://github.com/josephspurrier/covfmt), concatenating with the lcov generated by Jest, and then using the coveralls node module to upload (https://github.com/nickmerwin/node-coveralls). You can see the coverage combined here: https://coveralls.io/github/josephspurrier/govueapp?branch=master. The travis example is here: https://github.com/josephspurrier/govueapp/blob/b530517e5448a88b8a1861bf9ce54e0b1b59661c/.travis.yml#L43
