### ISSUE TITLE
Update documentation for Scala

### ISSUE THREAD

**Issue by fernandoacorreia** [lemurheavy/coveralls-public#240]
The [COVERALLS FOR SCALA](https://coveralls.io/docs/scala) page links to [xsbt-coveralls-plugin](https://github.com/theon/xsbt-coveralls-plugin), which states:

> This project is largely unmaintained. Check out sbt-scoverage for a replacement. The old README.md is still available here

It seems it would be better to update the link to point directly to [sbt-scoverage](https://github.com/scoverage/sbt-scoverage) and also to mention [the sbt-coveralls plugin](https://github.com/scoverage/sbt-coveralls).

**Comment by JoshRosen** [comment]
It looks like this has now been fixed: https://coveralls.zendesk.com/hc/en-us/articles/201342879-Scala

**Comment by fernandoacorreia** [comment]
Thanks.
