### ISSUE TITLE
Support Bitbucket - coming SOOOOOON! (see last comment)

### ISSUE THREAD

**Issue by matrixik** [lemurheavy/coveralls-public#241]
Hello,

would be nice if you could add support for public repos on bitbucket.org

Best regards

**Comment by barryokane** [comment]
:+1:  for this, I would love to use coveralls but can't move from BitBucket

**Comment by giggio** [comment]
:+1:

**Comment by fourq** [comment]
:+1:

**Comment by jaketay** [comment]
+1

**Comment by Andersmholmgren** [comment]
I hope support for open source bitbucket repos will be free like for os GitHub repos

**Comment by apobbati** [comment]
+1

**Comment by akramhussein** [comment]
:+1:

**Comment by tonic20** [comment]
+1

**Comment by taisph** [comment]
+1

**Comment by n9ti** [comment]
+1

**Comment by HenrikOssipoff** [comment]
+1

**Comment by jbernalvallejo** [comment]
+1

**Comment by alastairtree** [comment]
+1

**Comment by GaijinKa** [comment]
+1

**Comment by colorfulgrayscale** [comment]
+1

**Comment by moglash** [comment]
+1

**Comment by anjin** [comment]
We have the Bitbucket support in and are finishing final touches and optimizations.

**Comment by chesleybrown** [comment]
OMGS! :astonished: 

:ship: it!!! ^_^

**Comment by Andersmholmgren** [comment]
\o/

**Comment by Surgo** [comment]
\o/

**Comment by n9ti** [comment]
\o/

**Comment by anjin** [comment]
![screen shot 2015-07-02 at 10 30 42 am](https://cloud.githubusercontent.com/assets/2884/8483399/796d7b50-20a5-11e5-9b02-45c0c16f8c92.png)

**Comment by anjin** [comment]
We've soft-launched this today. Mailer is going out tomorrow, check it out!
