### ISSUE TITLE
Coveralls page gives 500 error

### ISSUE THREAD

**Issue by pathikrit** [lemurheavy/coveralls-public#257]
I checked in [coveralls support](https://github.com/pathikrit/dijon/commit/89415445b34cd5bd82ec8d4b1573ee7f2dec6ea1) for my [project](https://github.com/pathikrit/dijon) to auto-generate reports from Travis. 

Travis [says](https://travis-ci.org/pathikrit/dijon/builds/20789773) that the report should be available at https://coveralls.io/jobs/1398366.

When I click on the [one file](https://coveralls.io/files/153695644) in there, I get a "five zero zero" error.

Also, this was my first coveralls build. But, why does it start with [build number 38](https://coveralls.io/r/pathikrit/dijon)?

This is the coveralls homepage of [dijon](https://github.com/pathikrit/dijon): https://coveralls.io/r/pathikrit/dijon

**Comment by lucasfeliciano** [comment]
:+1: 
I'm getting the same error.
Anyone had some progress?
