### ISSUE TITLE
Please improve the documentation for C/C++

### ISSUE THREAD

**Issue by tbastos** [lemurheavy/coveralls-public#259]
After wasting many hours trying to make "cpp-coveralls" work for my project, I gave up and looked into alternatives based on lcov. And indeed the lcov route is both easier and significantly more powerful. I suggest you update the C/C++ doc to reflect this observation...

Instead of using `cpp-coveralls` (a new front-end for gcov with coveralls integration), any native GCC project (in c/c++/objective-c) is better off using `lcov` (a mature front-end for gcov) and then either of these tools to upload the lcov file to coveralls:
- Ruby: https://github.com/okkez/coveralls-lcov
- Grunt/JS: https://github.com/pimterry/grunt-coveralls

**Comment by SimonKagstrom** [comment]
Well, to push my own project, there's kcov:

  https://github.com/SimonKagstrom/kcov

where you can generate and upload coverage for C/C++/Rust/Python/Bash with

```
kcov --coveralls-id=$TRAVIS_JOB_ID /path/to/outdir executable
```

**Comment by afinetooth** [comment]
This is a very old issue, but just in case there's someone searching for this same info...

First. some background:
- [cpp-coveralls](https://github.com/eddyxu/cpp-coveralls) is a community-created [language integration](https://docs.coveralls.io/integrations#language-integrations) not supported by Coveralls.
- These days we recommend you choose one of our [official integrations](https://docs.coveralls.io/integrations#official-integrations), which support many coverage report formats, of which `lcov` is one.
  
Your task in using one of the [official integrations](https://docs.coveralls.io/integrations#official-integrations) is to get your C/C++ coverage into that `lcov` format.

For help with that, check out these two resources:

- https://medium.com/@xianpeng.shen/use-gcov-and-lcov-to-perform-code-coverage-testing-for-c-c-projects-c85708b91c78

- https://danielsieger.com/blog/2022/03/06/code-coverage-for-cpp.html
