### ISSUE TITLE
Repos never sync

### ISSUE THREAD

**Issue by hassankhan** [lemurheavy/coveralls-public#284]
Every time I try to add a new repo, it keeps trying to sync my repos endlessly. I changed the name of a repo on GitHub, and wanted to update that.

**Comment by uLow** [comment]
Having same issue. 
Your repos are syncing...
USERS/ORGS WITHOUT COVERALLS PRO

**Comment by dchaplinsky** [comment]
@uLow, log out and log in again with your github acc.

**Comment by uLow** [comment]
@dchaplinsky seems the same

**Comment by jmorford** [comment]
I am also having this issue. I can't see organisation (I am a public team member), nor personal public repos. Tried everything. This is a very unsatisfying sign-on process.

**Comment by fukuball** [comment]
I get also the same error as @anjos

**Comment by jmorford** [comment]
Is https://coveralls.io/ down?

**Comment by tomekwi** [comment]
Same with me. It looked the same as with @uLow for about 4 hours. Now it looks like this:

![image](https://cloud.githubusercontent.com/assets/4624660/7397156/d6b388da-eea6-11e4-9746-75bc2a2cf570.png)

:)

**Comment by tomekwi** [comment]
Update: back to

![image](https://cloud.githubusercontent.com/assets/4624660/7397223/3ef3d206-eea7-11e4-9bf3-094105a4af2f.png)

I’ve tried logging in and out – and resetting my GitHub token.

**Comment by tomekwi** [comment]
Things seem to be back to normal again.

**Comment by jmorford** [comment]
Working for me now. But still no response from Coveralls.io, and no acknowledgement at http://status.coveralls.io

**Comment by nickmerwin** [comment]
Sorry everyone for the downtime, we had to put some major DB optimizations through in the last 24 hours. Things are humming along now.

**Comment by tomekwi** [comment]
:tada:

Thanks for a great service BTW :)

**Comment by unindented** [comment]
@nickmerwin I'm seeing this again: https://github.com/lemurheavy/coveralls-public/issues/539

Is there a way to get out of this bad state?

**Comment by dthree** [comment]
This just happened to me.

**Comment by kashefy** [comment]
Just happened to me to. I saw a notification at the top in the coveralls page to enable access to private repos, so I clicked on it. The notification changed to "re-authorize with github". Did that too, now it works.

Not sure if clicking the buttons for those two notifications had anything to do with resolving the sync. I don't have any private github repos to begin with.

**Comment by shoyer** [comment]
@kashefy good tip -- that worked for me

**Comment by n9code** [comment]
@nickmerwin this issue happened again for me. Pressing *re-sync repos* is not helping. Only *sign-out/sign-in* helped.

**Comment by yargevad** [comment]
I had to disable EFF's Privacy Badger in order to refresh my repo list - got the never-ending spinner otherwise.

**Comment by Qix-** [comment]
_Still_ an issue, even after revoking access, signing out, and then signing back in. Sync just sits there infinitely, and then refreshing seems to show my repositories _sans_ the one I just created.

Between Coveralls and Travis, I'm beginning to think syncing from Github is impossible.

**Comment by iacopy** [comment]
Repo sync Is not working at all 👎

**Comment by martoriro** [comment]
Still an issue, i've been stuck on syncing for at least twenty minutes now
