### ISSUE TITLE
Pull Request Comments Not Working

### ISSUE THREAD

**Issue by skriptble** [lemurheavy/coveralls-public#298]
I'm evaluating coveralls for a project I'm working on, but when I created a pull request, Travis updates the status but coveralls isn't adding a comment with the coverage information. I added the coveralls account as a collaborator and it still didn't make the comments show up. Coveralls is getting the coverage reports from travis, am I doing something wrong?
https://coveralls.io/r/skriptble/goReviewSbx

**Comment by peterbe** [comment]
I have this problem too. Coveralls used to submit PR comments but it, at some point, stopped and no longer does. This issue is over a year old :(
