### ISSUE TITLE
Webhook not working for Slack notifications

### ISSUE THREAD

**Issue by shedd** [lemurheavy/coveralls-public#299]
I tried to configure a webhook for https://slack.com using their webhook integration instructions, but it's returning a 500 server error.

Slack is great - would love to see it supported for notifications.

**Comment by blueplanet** [comment]
+1

**Comment by nickmerwin** [comment]
Hi everyone, Slack is now an officially supported notification!

![image](https://cloud.githubusercontent.com/assets/1129/5807992/669c64ee-9fdd-11e4-996b-f674c415f52e.png)


Thank you for your patience. Cheers!

**Comment by blueplanet** [comment]
Good job!!! :+1:

**Comment by pjbull** [comment]
:+1:  Thanks!

**Comment by sckott** [comment]
it's not clear what the webhook URL should be ? Any help on this

**Comment by iwasrobbed** [comment]
@nickmerwin Getting an error when I try testing to the Slack-provided webhook: `Error: wrong number of arguments (1 for 0)`

**Comment by partydrone** [comment]
Same here: `Error: wrong number of arguments (1 for 0)`.

**Comment by partydrone** [comment]
Also, for the notification boxes, it's unclear whether you mean coverage changes _by_ a certain percent, or _above/below_ a certain percent. I'm guessing the latter.…

**Comment by ObjectiveTruth** [comment]
@iwasrobbed same here, `Error: wrong number of arguments (1 for 0)`

**Comment by ogreface** [comment]
@nickmerwin Same issue as others. 

> Error: wrong number of arguments (1 for 0)

**Comment by analytically** [comment]
+1
