### ISSUE TITLE
Not receiving feedback from Coveralls on PRs (using CircleCI)

### ISSUE THREAD

**Issue by dansowter** [lemurheavy/coveralls-public#30]
The pull request in question --

https://github.com/net-engine/resthooks/pull/4

Available on Coveralls here -- (note the comment on PR box is checked).

https://coveralls.io/r/net-engine/resthooks

**Comment by sguha00** [comment]
Are git PR statuses supported for CircleCI now?

**Comment by geeknam** [comment]
Is Jenkins supported?

**Comment by msaspence** [comment]
+1

**Comment by mr337** [comment]
+1 for Jenkins, just signed up, but quickly noticed if your not using Travis you lose some features. Is this ture?

**Comment by pboling** [comment]
I've had problems getting CircleCI working with coveralls every single time I have attempted it.  This time is no different.
