### ISSUE TITLE
Bad percentage value on the repository view

### ISSUE THREAD

**Issue by MartinDelille** [lemurheavy/coveralls-public#303]
Since the last three build, the repository view summing up the coveralls job for my repository show a weird question mark:
![capture d ecran 2014-05-17 16 26 23](https://cloud.githubusercontent.com/assets/879889/3005131/f01a7ae2-ddcf-11e3-8e99-5ea74c95e453.png) 
(from https://coveralls.io/r/Phonations/Joker)
The strange think is that if I click the jobs details I have a correct coverage:
https://coveralls.io/builds/779762
Notice that the notification hasn't been sent.

**Comment by anonx** [comment]
I have the same issue. Is there a way to fix this?

![Coveralls: Bad percentage value](http://i.imgur.com/GzbJAN0.png)
