### ISSUE TITLE
Branch coverage

### ISSUE THREAD

**Issue by myint** [lemurheavy/coveralls-public#31]
Does Coveralls support [branch coverage](http://nedbatchelder.com/code/coverage/branch.html)? (See [example](http://nedbatchelder.com/files/sample_coverage_html/cogapp_whiteutils_py.html).) I know Coveralls supports "hits per line", but that alone does not really tell you if the tests have covered both branches of a conditional.

**Comment by xanderdunn** [comment]
+1 This would be amazing.

**Comment by murielsilveira** [comment]
:+1:

**Comment by mrname** [comment]
Kind of surprised that this has been sitting dormant for two years. Are there any plans to implement this at all in the future?

**Comment by carangorango** [comment]
The lack of branch coverage statistics in coveralls.io made me switch to codecov.io. I like your interface more though, so please fix this issue so I can come back ;)

**Comment by tvavrys** [comment]
👍 +1

**Comment by DimmuR** [comment]
:+1:

**Comment by PlasmaSheep** [comment]
+1

**Comment by epoberezkin** [comment]
+1

**Comment by jcubic** [comment]
+1

**Comment by jcubic** [comment]
It seems that there is branch coverage. For my project jQuery Terminal:

Master [![Coverage Status](https://coveralls.io/repos/github/jcubic/jquery.terminal/badge.svg?branch=master)](https://coveralls.io/github/jcubic/jquery.terminal?branch=master)

Devel [![Coverage Status](https://coveralls.io/repos/github/jcubic/jquery.terminal/badge.svg?branch=devel)](https://coveralls.io/github/jcubic/jquery.terminal?branch=devel)

**Comment by Peque** [comment]
@jcubic I think you may be misunderstanding the term "branch coverage" here. :wink:

References:

- http://stackoverflow.com/questions/8229236/differences-between-line-and-branch-coverage
- http://coverage.readthedocs.io/en/latest/branch.html
- https://www.tutorialspoint.com/software_testing_dictio

**Comment by kasperlewau** [comment]
Looks to me like Coveralls is now doing branch coverage. Had a 2.5% drop today upon merging into master. 

![screenie](https://i.imgur.com/j5uRSAA.png)

**Comment by nickmerwin** [comment]
Hey @kasperlewau, yes! We quietly released it over the weekend and are watching for issues before making a wider announcement.

Let me know if you come across anything fishy. Thanks!

**Comment by Pr0methean** [comment]
@kasperlewau I still don't see it at https://coveralls.io/github/Pr0methean/BetterRandom. Is Java supported for branch coverage yet?
