### ISSUE TITLE
BUG: Intermittent 504's when uploading coverage data

### ISSUE THREAD

**Issue by pimterry** [lemurheavy/coveralls-public#326]
See https://travis-ci.org/pimterry/frontkit/builds/30436469 and https://travis-ci.org/pimterry/frontkit/builds/30437378, two subsequent builds on travis with grunt-coveralls, one of which fails and one succeeds, despite no relevant changes (expand the 'grunt coveralls:core' line at the bottom for details).

Repeated rerunnings of these jobs gets different results, with 504s appearing for some number of the lcov uploads. See the [first build](https://travis-ci.org/pimterry/frontkit/builds/30436469) for an example failure, or take a look at the HTML returned (with a 504) at https://gist.github.com/pimterry/df857ec94a535d589773. Looks like CloudFront is returning the 504.

**Comment by ethanmick** [comment]
This just happened to me.

**Comment by revett** [comment]
+1

**Comment by Integralist** [comment]
+1

**Comment by darnould** [comment]
+1
