### ISSUE TITLE
'source change' and 'coverage change'  not detected

### ISSUE THREAD

**Issue by erossignon** [lemurheavy/coveralls-public#327]
the feature that detects the file that have changed between 2 commits and file with change in coverage doesn't seem to work well in my case since a little while now.

see https://coveralls.io/builds/985280 and related

**Comment by kentfredric** [comment]
It looks like this *may* be fixed, hard to say. Picking a random project or two:

- https://coveralls.io/github/fog/fog # shows non-zero values
- https://coveralls.io/github/intridea/omniauth # shows non-zero values
- https://coveralls.io/builds/25164198 # shows zeros despite coverage changing and the causal PR ( https://github.com/tornadoweb/tornado/pull/2024/files )  *absolutely* changing.
- https://coveralls.io/builds/29187852 # shows zeros despite coverage changing and the causal PR ( https://github.com/twitter/scalding/pull/1752/files ) *absolutely* changing.

So it looks like its still broken. 

But perhaps the breakage is language specific. ( Candidates taken from repositories listed at the bottom of coveralls "opensource" section on their front page, the first two (successes) are from Ruby and JavaScript respectively, the second two (failures) are from C+Python and Scala, respectively ).

So I guess I'll have to do something with my repositories I did something with coveralls with ages ago at some point to be sure.

[stale bot is dumb though]
