### ISSUE TITLE
Add support page for getting D coverage info

### ISSUE THREAD

**Issue by ColdenCullen** [lemurheavy/coveralls-public#334]
I wrote a little utility called [doveralls](https://github.com/ColdenCullen/doveralls) for uploading D code coverage results to Coveralls, and I'd love it if you could give me a shout out on the docs page!

**Comment by MartinNowak** [comment]
Done
https://coveralls.zendesk.com/hc/en-us/articles/204189715

**Comment by ColdenCullen** [comment]
Neato, thanks for pointing that out.
