### ISSUE TITLE
Way to merge coverage from Grunt/Karma JavaScript tests and Ruby rspec tests?

### ISSUE THREAD

**Issue by gigiJackson** [lemurheavy/coveralls-public#338]
We have a suite of JavaScript unit tests that are run using Grunt and Karma.  

I can get these generating either a local coveralls.json report or submitting to Coveralls service, using grunt-karma-coveralls ( https://github.com/mattjmorrison/grunt-karma-coveralls )

We also have an Rspec suite in which we are using the coveralls gem, but also have simplecov.  The Rspec coverage report is also successfully submitting a report to coveralls.

However, when we run our tests on Codeship, we then have two reports submit to Coveralls that look like two separate builds.

![screen shot 2014-08-13 at 3 31 41 pm](https://cloud.githubusercontent.com/assets/4481511/3913672/cce41038-2339-11e4-959e-a6b2fbed3888.png)

Is there are way for us to merge these or submit them with the same build number, so that we don't have two rows for each build, the JS coverage and the Ruby coverage?

It looks like I might be able to do some hackery with simplecov to try and merge two json files and use the coveralls push rake task. 

Any examples or Doc on this use case would be really helpful.

**Comment by joshma** [comment]
+1 to this, are the coveralls folks still working on the service or addressing issues?

**Comment by robertomstocker** [comment]
You can use a [tool for merging both lcov files](https://github.com/mweibel/lcov-result-merger), (Example: `./node_modules/.bin/lcov-result-merger './coverage/*.info'`). 

Make sure that the coverage tools you use are generating lcov file format. You can use [this formatter](https://github.com/fortissimo1997/simplecov-lcov) to generate a lcov file on the ruby side and `istanbul` with the correct `--report` flag on the javascript side, for example. Then, push the merged file to Coveralls (example: `cat ./coverage/merged.info | ./node_modules/coveralls/bin/coveralls.js`). 

Make sure the merged lcov file has the correct source code file paths.

**Comment by blaskovicz** [comment]
As an alternative, crazy-option, you can check out my grunt file in the commit referenced above.
I run karma to generate test coverage for my frontend sources, which is output to `coverage/.frontend.json`. I created a custom grunt task, `karma-simplecov-format`, to translate from karma json format to simplecov format and merge with the `coverage/.resultset.json` file coveralls/simplecov uses.

After this change, running with `COVERALLS_NOISY=true` shows that the `.js` files are being picked up and their coverage is being factored in to the overall status.
