### ISSUE TITLE
Please make it possible to link to a specific line number in reports

### ISSUE THREAD

**Issue by mgedmin** [lemurheavy/coveralls-public#34]
Github lets me click on the line number and get a link that points to that particular line (using an anchor like `#L35` for line 35).  It would be nice if I could do the same for source-level reports, e.g. https://coveralls.io/builds/15675/source?filename=check_manifest.py#L35 (which doesn't work because the HTML doesn't have IDs).

**Comment by baldurh** [comment]
:+1:

**Comment by gaining** [comment]
Can you do that for README.md files too, that would be so convinient.

**Comment by mgedmin** [comment]
Thank you for implementing this!

(I'm commenting because *usually* a bug getting closed after a few years without any comments means WONTFIX, which is not the case here.)
