### ISSUE TITLE
Changes Unknown when pulling X on user:branch into ** on repo:master**.

### ISSUE THREAD

**Issue by hugovk** [lemurheavy/coveralls-public#351]
We're using Coveralls with [Pillow](https://github.com/python-pillow/Pillow) and pull requests are built by Travis CI. We get a Coveralls comment after each PR build, but often it says "Changes Unknown".

For [example](https://github.com/python-pillow/Pillow/pull/874#issuecomment-53533104):

> [![Coverage Status](https://coveralls.io/builds/1134201/badge)](https://coveralls.io/builds/1134201)
> 
> Changes Unknown when pulling **[998955b](https://github.com/python-pillow/Pillow/commit/998955b024fbd98255bf806f17e24dde639dc1a9) on hugovk:GimpGradientFile** into *\* on python-pillow:master**.

The master's last commit should be shown between the asterisks after "into" (like [this](https://github.com/python-pillow/Pillow/pull/872#issuecomment-53460781)).

Some other example PRs:
- https://github.com/python-pillow/Pillow/pull/859
- https://github.com/python-pillow/Pillow/pull/847
- https://github.com/python-pillow/Pillow/pull/844
- https://github.com/python-pillow/Pillow/pull/843
- https://github.com/python-pillow/Pillow/pull/839
- https://github.com/python-pillow/Pillow/pull/837

Please can you fix it so it shows the correct changes for each comment?

**Comment by arschles** [comment]
Anyone know what's going on here? I just started [seeing this problem also](https://github.com/paypal/cascade/pull/81)

**Comment by hugovk** [comment]
I emailed Coveralls in September about it as well, but got no reply.

**Comment by arschles** [comment]
@anjin @eli @nickmerwin any ideas what's going on here?

**Comment by evoskuil** [comment]
The similar emails goes away when you clear the value here:
```
COVERAGE DECREASE THRESHOLD FOR FAILURE   [        ]   %
```

**Comment by hugovk** [comment]
@aclark4life Please could you check https://coveralls.io/r/python-pillow/Pillow and scroll down to the settings section? I'm guessing they're blank, but do we have any values set for these?

```
COVERAGE THRESHOLD FOR FAILURE   [        ]   %
COVERAGE DECREASE THRESHOLD FOR FAILURE   [        ]   %
```

**Comment by aclark4life** [comment]
Blank indeed
![screenshot 2015-06-08 15 38 15](https://cloud.githubusercontent.com/assets/72164/8043477/71fb5c70-0df4-11e5-8084-22bfbb6119c4.png)

**Comment by hugovk** [comment]
@lemurheavy @nickmerwin Any news on this issue? We're still getting "Changes Unknown" for virtually every PR, for example: https://github.com/python-pillow/Pillow/pull/1932

Also looks like this has been around for three years: https://github.com/lemurheavy/coveralls-public/issues/275 https://github.com/lemurheavy/coveralls-public/issues/97.

**Comment by b-lambert** [comment]
I'm also having this issue in a private repo.

**Comment by ryan-williams** [comment]
I believe [this](https://github.com/hammerlab/guacamole/pull/576#issuecomment-246885274) an example of this bug on a public repo; coverage increased by 3% but coveralls says "unknown" for some reason.

**Comment by monotek** [comment]
Same here:

https://github.com/zammad/zammad/pull/497#issuecomment-264894322

**Comment by Haroenv** [comment]
I have this all the time 🙍 https://github.com/Haroenv/holmes/pull/80#issuecomment-272325066 for example

**Comment by kasperlewau** [comment]
Opened up my first PR in a new private repo. Coveralls reported back with the correct % increase and was able to find the latest SHA in master. 
 
Opened up a second PR. Now I'm stuck at `unknown`. 

Trying out different settings of pull_request/push/tag hooks to see what gives, so far no luck.

**Comment by mjarvis** [comment]
based on the lack of feedback from coveralls on this issue over the years, we've switched to codecov.io

**Comment by arackaf** [comment]
Can confirm. codecov.io works wonderfully.  Switched to that. Thanks a ton @mjarvis
