### ISSUE TITLE
Pull Request comments for organization repo

### ISSUE THREAD

**Issue by shirakia** [lemurheavy/coveralls-public#352]
Hi,

I set up coveralls with travis-pro and it works very well on your web site. Now I setting up Pull Request comment.

https://coveralls.io/docs/notifications
Here you said "you will need to allow pull access for our Coveralls bot: @coveralls". But actually what should i do?

I created a team which has "Read Access" for Coveralls bot.
I confirmed a user in the team can write comments.
And finally I sent a invitation to https://github.com/coveralls 4 days ago. But nothing has happened.
Just should I wait for the bot to accept invitation?

Thanks

**Comment by donvigo** [comment]
Same for me, I just sent an invitation to @coveralls from our private repo.
How long it takes usually to accept the invitation?

**Comment by jspiro** [comment]
@nickmerwin Are these instructions still how things work? We haven't been getting PR comments, but we do see the status checks. https://github.com/integrations/coveralls is configured for our private repo at github.com/DotDashPay.
