### ISSUE TITLE
Showing wrong github repository

### ISSUE THREAD

**Issue by suguru** [lemurheavy/coveralls-public#357]
I am using travis pro to build my private repository in github.com. When I connect and upload coverage to coveralls, it shows strange commit logs of another repository. It shows random build number after submitting to coveralls API.

I have tried to reconnect repository and regenerate tokens. But it still showing commit logs of unknown repositories which does not belong to my repository.

The URL is https://coveralls.io/r/liverpool-music/liverpool-api

**Comment by mcqueary** [comment]
I also had this exact problem. The solution was adding this to the plugin config in my pom (although I still have the history items from the 'other'/wrong repo in the commit history):

```
<configuration>
    <serviceName>travis-pro</serviceName>
<configuration>
```
