### ISSUE TITLE
[Feature request] support displaying differential coverage between builds

### ISSUE THREAD

**Issue by daira** [lemurheavy/coveralls-public#359]
i.e. not just the change in number of lines covered, but the full diff of lines covered in a given file between two specified builds (defaulting to between this and the previous reported build).

**Comment by kroeckx** [comment]
It's in general rather hard to see what the coverage changed, it says something like -0.07%, and then you first have to go and look for files where the coverage gets less, but there is really no such column you can sort on.  Then you just get a file that shows the coverage for the current build without an indication what the difference between the previous build is.

**Comment by ScottFreeCode** [comment]
This would still be great to get; it would make Coveralls exponentially more helpful. Also there's suport expressed for substantially the same idea, if I'm reading it right, in #459.

Besides lines, functions and branches would be nice too; Coveralls added branch coverage summaries not too long ago.
