### ISSUE TITLE
Unable to change "main" branch view from master

### ISSUE THREAD

**Issue by senturio** [lemurheavy/coveralls-public#36]
We don't use "master" as our development branch, so it's more helpful for us to have "develop" set as the default branch to view. It'd be nice to be able to pick which branch is set as default.

**Comment by izquierdo** [comment]
:+1:

**Comment by barrypickering** [comment]
:+1:

**Comment by rmccue** [comment]
:+1: We're using Coveralls over on [WP-API/WP-API](https://github.com/WP-API/WP-API), where we also use `develop` as our "main" branch.

**Comment by PyroSA** [comment]
Same problem. :+1:

**Comment by anselmbradford** [comment]
:+1:

**Comment by jimmynotjim** [comment]
We're having the same problem with [cfgov-refresh](https://github.com/cfpb/cfgov-refresh) where we don't even use a `master` branch.

**Comment by danielgomezrico** [comment]
+1

**Comment by RazzYoshi** [comment]
I kind of looks to me as if the first branch you run coveralls on gets set as main branch. I set up coverage using a side branch and now can't seem to set main branch to master. Has there been any response about this issue yet?

**Comment by MoOx** [comment]
In theory, you should be able to got to

Repo settings > Resync with github

> Sync the location, privacy setting, and **default branch** of this repo with Github.

In my case it worker once (change from master to "next"), but recently I switched back to master as a default branch on github and when I sync again, it does not take my branch into account and keep "next"...

It says

>  No new info detected. 

when I sync. I don't even have a next branch anymore :'(

**Comment by cemsbr** [comment]
I had to delete my repository and add it again for coveralls to recognize the new default branch. But this erases all coverage data (my repo was just a test)!

**Comment by lkraider** [comment]
Having same issue for https://coveralls.io/github/schematics/schematics , development branch was deleted and now cannot switch back to master as default branch.
