### ISSUE TITLE
Unable to delete repo

### ISSUE THREAD

**Issue by kura** [lemurheavy/coveralls-public#37]
I've been repeatedly trying to delete my repo - https://coveralls.io/r/kura/blackhole to try and reset the test coverage.

I have 2 issues, 1. the test coverage is weirdly covering my project and all of the third party libraries it uses, even though I tell nose to specifically only do my library;
- https://github.com/kura/blackhole/blob/master/.travis.yml
- https://github.com/kura/blackhole/blob/master/Makefile

That aside, each time I press the delete repository button I am met by a 500 error page and cannot go further.

**Comment by zillou** [comment]
I can't see the delete button any more.

**Comment by boberj** [comment]
It has been moved to the settings for the repo (i.e. `https://coveralls.io/github/<user>/<repo>/settings`). You can only delete repositories that you own.
