### ISSUE TITLE
Wrong coverage data - Shows 0% on a file instead of 100%

### ISSUE THREAD

**Issue by ggiamarchi** [lemurheavy/coveralls-public#371]
On an open source ruby project on Github with a travis build that subimit coverage to coveralls.io, travis shows a `76.88%` coverage but coveralls.io shows `70.91%`.

```
https://travis-ci.org/ggiamarchi/vagrant-openstack-provider/jobs/35970538
https://coveralls.io/jobs/2864490
```

Taking a closer look, coverage for some files is wrong. For instance `nova.rb` is `0%` instead of `100%`.

**Comment by mediavrog** [comment]
+1

**Comment by DyslexicChris** [comment]
+ 1
