### ISSUE TITLE
Coverage for multiple languages

### ISSUE THREAD

**Issue by muhammad-ammar** [lemurheavy/coveralls-public#373]
Hi,

I have a repo in which i am collecting coverage for Python and Javascript. I didn't found a way to send coverage data for both languages to coveralls.io. Can this thing is even possible right now? I want a single badge on my repo or two badges for each language?

Thanks

**Comment by asfaltboy** [comment]
Just in case anyone is looking here for multi-language python/js solution, have a look at the [coveralls-python client for their implementation](https://github.com/coagulant/coveralls-python#multiple-languages-experimental). The PR coagulant/coveralls-python#53 mentions this issue, but some people may miss it.

**Comment by Qix-** [comment]
This is something that you guys _should_ have. Native node.js modules will have lcov data for the Javascript portions and gcov or compatible data for any native portions - both of which are not entirely compatible with each other.

**Comment by josephspurrier** [comment]
I was able to achieve this for Go and JavaScript (Vue) by converting Go to lcov format (https://github.com/josephspurrier/covfmt), concatenating with the lcov generated by Jest, and then using the coveralls node module to upload (https://github.com/nickmerwin/node-coveralls). You can see the coverage combined here: https://coveralls.io/github/josephspurrier/govueapp?branch=master. The travis example is here: https://github.com/josephspurrier/govueapp/blob/b530517e5448a88b8a1861bf9ce54e0b1b59661c/.travis.yml#L43
