### ISSUE TITLE
Source file is not python

### ISSUE THREAD

**Issue by numberoverzero** [lemurheavy/coveralls-public#386]
[Travis Build #9.1](https://travis-ci.org/numberoverzero/declare/jobs/37570385)
[Coveralls Job #9.1](https://coveralls.io/jobs/3042243)
[GitHub Repository](https://github.com/numberoverzero/declare)

No luck finding related issues - it seems as though the coverage file is being parsed incorrectly when coveralls run on travis.  I have a single file, declare.py which has 100% coverage, which I see in the travis build output.

[.travis.yml](https://github.com/numberoverzero/declare/blob/9f3262027c52e66e19302f1edf273d57f8e3c991/.travis.yml)
[tox.ini](https://github.com/numberoverzero/declare/blob/9f3262027c52e66e19302f1edf273d57f8e3c991/tox.ini)
[setup.cfg](https://github.com/numberoverzero/declare/blob/9f3262027c52e66e19302f1edf273d57f8e3c991/setup.cfg)

I've got other single-file projects that are getting covered without a problem, and I've tried removing/adding the repository in coveralls already.

Have I missed something obvious?  When I run coveralls locally it successfully uploads coverage.  From the build output it looks like it's dropping the `.py` but that could also be package name..

    $ coveralls --rcfile=setup.cfg
    Submitting coverage to coveralls.io...
    Source file is not python .tox/py33/lib/python3.3/site-packages/declare
    Coverage submitted!

**Comment by fahhem** [comment]
This turns out to be due to coveralls on travis using python 2.7 to parse python 3.4 files. If you specify "python: 3.4" in .travis.yml, it should work.

**Comment by fahhem** [comment]
Confirmed this fixes the problem for numberoverzero as well as for my project.

**Comment by numberoverzero** [comment]
Thanks again!
