### ISSUE TITLE
Renaming Github URL does not make changes to coveralls

### ISSUE THREAD

**Issue by jaypatel512** [lemurheavy/coveralls-public#399]
Hey Guys, 

I recently renamed a github repository, which is still not getting fetched properly in coveralls. Can you please help me with that.

Old Coverall : https://coveralls.io/r/paypal/rest-api-sdk-php
New Github Repository: https://github.com/paypal/PayPal-PHP-SDK

**Comment by perki** [comment]
Hello,

Same for us.. 
Old Coverall: https://coveralls.io/github/pryv/sdk-objectivec-apple
New Github repos: https://github.com/pryv/lib-cocoa

Can I do something to fix it ?

Thanks

**Comment by nickmerwin** [comment]
Hi @perki we've just released a new name-sync'ing function, it's on your repo page here now:

<img width="424" alt="screen shot 2015-08-06 at 12 46 36 pm" src="https://cloud.githubusercontent.com/assets/1129/9121760/34b6c82c-3c39-11e5-9c5a-918b76990c74.png">

Give it a try and let me know. Thanks!

**Comment by perki** [comment]
Hello @nickmerwin 

Thanks a lot.. I didn't found the "Synch name" button, but everything was fine today.

**Comment by stevenvachon** [comment]
No "sync name" button for me. I added the new name after re-synching my GitHub account, and now I have both listed. Hopefully your system removes it.

old: https://coveralls.io/github/stevenvachon/postgres-bootstrapper
new: https://coveralls.io/github/stevenvachon/gres
