### ISSUE TITLE
Badge % is off

### ISSUE THREAD

**Issue by chriscct7** [lemurheavy/coveralls-public#403]
For this repository: https://coveralls.io/r/easydigitaldownloads/Easy-Digital-Downloads

The badge shows 90% coverage even when coveralls only has us at 34%

**Comment by jmthomas** [comment]
Same here. Coverage is at 91.37 (green!) but badge says 89.34 (yellow!). https://coveralls.io/r/BallAerospace/COSMOS

**Comment by nickmerwin** [comment]
Hi @jmthomas the last non-pull-request build on master was:
https://coveralls.io/builds/1836380 @ 89%

@chriscct7 that's updated now.

**Comment by jmthomas** [comment]
@nickmerwin I'm confused by when I should expect the coverage to update. The build you referenced WAS a pull-request build but you said it was the last NON-pull-request build. When I look at the Updates page I see everything has now been updated with coverage information while before it was unknown. Was there just a glitch in the system? Is it documented somewhere when we should expect our badge to update? In any case everything looks awesome now. Thanks for the great service for the open source community!

**Comment by nickmerwin** [comment]
@jmthomas thank you for the kind words! It's a labor of love :-)

We had a queue delay yesterday that lasted an hour or two, it's all processed now and jobs usually complete within a few seconds.

**Comment by jmthomas** [comment]
If you had some sort of system status indicator on your site you might avoid a lot of tickets. Just a suggestion. Keep up the great work!

**Comment by nickmerwin** [comment]
@jmthomas thank you, and good idea! Adding to dev list.
