### ISSUE TITLE
Moved Github repositories fail

### ISSUE THREAD

**Issue by danez** [lemurheavy/coveralls-public#405]
I moved two repositories on github to a new org.
Travis just migrated them somehow on the fly, haven't had to do anything.
But coveralls failed hard. First I tried to change the source of the old projects on coveralls, but that got me an timeout. Afterwards I had to logout and relogin as everything was broken and I only saw the red error page. Since the relogin(and probably a sync?) I cannot change the old ones, as I'm not admin of the old github repos anymore, obviously as they do not exist anymore.

Could you please fix these projects and rename and change source. Or in the worst case remove the old projects.

Maybe it would be good if coveralls could detect that github is redirecting to the new repo and then also change on the fly like travis.

https://coveralls.io/r/project-a/Silex-Routing
https://coveralls.io/r/project-a/AclBundle

Old Repos:
https://github.com/project-a/Silex-Routing
https://github.com/project-a/AclBundle

New Repos:
https://github.com/chili-labs/Silex-Routing
https://github.com/chili-labs/AclBundle

**Comment by matt-newell** [comment]
I am having the same issue after moving the repo
