### ISSUE TITLE
https://coveralls.io/builds/1499070 shows coverall build changes, but Files section has no data

### ISSUE THREAD

**Issue by jaypatel512** [lemurheavy/coveralls-public#406]
For the PayPal-PHP-SDK, the result shows the appropriate coverage changes, however, under files section, these are still 0.

CHANGED 0 
SOURCE CHANGED 0
COVERAGE CHANGED 0

![screen shot 2014-11-19 at 3 53 25 pm](https://cloud.githubusercontent.com/assets/1309895/5115133/3a8c5c82-7004-11e4-8b84-6be1cceb7f70.png)

**Comment by mossprescott** [comment]
I'm seeing something similar with https://coveralls.io/r/slamdata/slamengine as of build 824.
