### ISSUE TITLE
Merge cover result from all jobs

### ISSUE THREAD

**Issue by michalwski** [lemurheavy/coveralls-public#407]
Is it possible to see merged coverage results from all jobs on the build page? For example here: [https://coveralls.io/builds/1508268](https://coveralls.io/builds/1508268) I see all my 6 jobs which is correct, but **Files** section presented below **Jobs** shows coverage taken only from one job. I'd like to see there files with merged coverage from all jobs.

**Comment by BenMorel** [comment]
:+1: It would be nice to get the global coverage across all jobs.

**Comment by xfguo** [comment]
:+1: I got the same problem, https://coveralls.io/builds/1818465, I thought that _coveralls_  should  support merge the coverage reports from all jobs, but sadly it is not.

**Comment by nickmerwin** [comment]
Hi @michalwski, @BenMorel, and @xfguo, this feature is live now!

**Comment by xfguo** [comment]
hi, @nickmerwin, it is always there or it is a new feature added recently?

**Comment by michalwski** [comment]
Good to hear! Does this feature work for old builds or only for new ones?

**Comment by BenMorel** [comment]
@nickmerwin I just tried to push a new commit, but the coverage is still as low as usual:
https://coveralls.io/r/brick/geo?branch=master

All jobs cover the same files, and some jobs cover up to 58% alone, so the overall coverage shouldn't be lower than 58%, but it's still 36%?

**Comment by nickmerwin** [comment]
hi @BenMorel, we calculate overall coverage based on the total number of relevant lines, and some jobs have different relevant line counts. 

This job reporting 58% coverage only has 648 relevant lines:
https://coveralls.io/jobs/4224482

Whereas the others have over 2K:
https://coveralls.io/jobs/4224527

So the merged coverage is lower than the highest job @ 58% since there are 2436 total relevant lines in the codebase and only 881 total were hit. 

Hope that helps clear it up!

**Comment by nickmerwin** [comment]
@michalwski yes, it applies to all in our system! Let me know if see any evidence to the contrary. Thanks!

@xfguo this feature was lost for a while due to optimization issues; I just resurrected it.

**Comment by BenMorel** [comment]
@nickmerwin Hmm indeed, those are the HHVM jobs whose lines are not counted properly, thanks for pointing this out!

So if one line is covered by a job and another line is covered by another job, both lines are considered covered in the overall build, is that right?

**Comment by nickmerwin** [comment]
@BenMorel that's right! The overall coverage % for a build will look at each source file's hits in each job, merging them together before doing:

```covered_percent = covered_lines / relevant_lines```

**Comment by BenMorel** [comment]
That's great news, thank you @nickmerwin !

**Comment by michalwski** [comment]
I think that the file browser still doesn't show merged results. For example here: https://coveralls.io/builds/1826803. In the "Files" section I see file "apps/ejabberd/src/eldap.erl" with 0% coverage. This file is used in one of travis jobs - https://coveralls.io/jobs/4210258. Here the coverage of the file is: 49.38%

**Comment by nickmerwin** [comment]
Hey @michalwski ok that's updated, but it's not very performant yet. It's taking about 5 seconds per call on your repo (sorting/search/paging etc) since you have aggregate 1288 source files between all jobs that need to be merged at once. 

Working on optimizations now!

**Comment by michalwski** [comment]
Hey @nickmerwin, that's great. I can accept such delay but I keep my fingers crossed for the optimisation!

Thanks a lot!
