### ISSUE TITLE
Invalid coverage results

### ISSUE THREAD

**Issue by Neamar** [lemurheavy/coveralls-public#409]
Hi there,

I have a repo displaying invalid coverage values -- the data sent to Coveralls is not properly displayed.

Here is the file on coveralls: https://coveralls.io/files/368605222: 0% coverage.

When looking at the actual build on TravisCI https://travis-ci.org/AnyFetch/anyfetch-provider.js/builds/42178301, we can see that the coverage for this file is 97.14 (there is indeed a test covering this section, as can be attested by adding a console.log in the function). (i've added a `cat ./coverage/lcov-report/index.html` to see the coverage data)

Actual line on Travis: https://travis-ci.org/AnyFetch/anyfetch-provider.js/builds/42178301#L679

Looks like the information is lost somewhere between Travis and the coveralls UI.

**Comment by ccarpita** [comment]
Having the same issue on this build: https://coveralls.io/github/ccarpita/react-observer-mixin  -- coverage is 100% but reported as 0%

**Comment by nicolaasuni** [comment]
I am experiencing the same bug.
The the coverage of individual files is reported as 100% but the total is 0%:
https://coveralls.io/builds/4231263

I am using a Clover XML report and my project has no methods, hence: 
methods="0" coveredmethods="0"
In this particular case the coverage should be 100% and not 0%

I suppose that in the cloverall code there is some division-by-zero control that set the result to 0.
