### ISSUE TITLE
HTTP 504 when submitting coverage reports to coveralls.io

### ISSUE THREAD

**Issue by kyleget** [lemurheavy/coveralls-public#411]
Appears other people on Twitter are getting the same errors when submitting their coverage reports.

Help! I have a Pro subscription. Coveralls is part of my CD process, and it's causing my builds to fail.

**Comment by sochka** [comment]
+1

**Comment by BerkeleyTrue** [comment]
Also experiencing this intermittently.

![r3dm_thundercats__107_-_circleci](https://cloud.githubusercontent.com/assets/6775919/7341637/55e3263c-ec5a-11e4-84c4-cadcd7db73f2.png)
.
