### ISSUE TITLE
Overall coverage is outdated

### ISSUE THREAD

**Issue by PragTob** [lemurheavy/coveralls-public#412]
for [Shoes 4](https://coveralls.io/r/shoes/shoes4?branch=master) the coverage is a bit weird.

On the top right it says 90%. The badge is stuck at 91%: [![Coverage Status](https://img.shields.io/coveralls/shoes/shoes4.svg)](https://coveralls.io/r/shoes/shoes4?branch=master)

But all the latest builds on master report 93+%.

I'd like it if the badge showed 93% or 94%

**Comment by jmthomas** [comment]
Same here. Coverage is at 91.37 (green!) but badge says 89.34 (yellow!). https://coveralls.io/r/BallAerospace/COSMOS
