### ISSUE TITLE
Use GitHub's Status API to report PR coverage changes

### ISSUE THREAD

**Issue by hugovk** [lemurheavy/coveralls-public#415]
Rather than commenting, use this sort of thing: 

![](https://cloud.githubusercontent.com/assets/483/5332863/0f58f9b6-7e1a-11e4-9884-e362ec566f2b.png)

https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by nickmerwin** [comment]
hi @hugovk this is feature is live now!
