### ISSUE TITLE
Disappearing jobs when there are multiple submissions

### ISSUE THREAD

**Issue by ionelmc** [lemurheavy/coveralls-public#416]
This coveralls job is 404: https://coveralls.io/jobs/3633633

This was created from a travis job that makes multiple submissions: https://travis-ci.org/ionelmc/python-lazy-object-proxy/jobs/43413398 (one for the python code and one for the C code). 

It seems that only the last submission is registered, even if it would be kinda empty, eg: https://travis-ci.org/ionelmc/python-lazy-object-proxy/jobs/43413400

**Comment by paralin** [comment]
Did you ever find a solution to this?
