### ISSUE TITLE
Public Github repo not visible

### ISSUE THREAD

**Issue by zopyx** [lemurheavy/coveralls-public#417]
I created a account 'zopyx' but I can not find this repo that I created for the Github team "xml-director":

https://github.com/xml-director/xmldirector.plonecore

Bug or feature?

**Comment by drphilmarshall** [comment]
Here's another one that won't show up in the list when I try to "add repos":

https://github.com/DarkEnergyScienceCollaboration/SLCosmo

Is there a limit to the number of public repos that can be added from an organization?

**Comment by k00ni** [comment]
I think there is a bug somewhere. I also can't see one of the repositories: https://github.com/SaftIng/Saft.hardf

Its funny because other repositories of the organization i can see and have already added in coveralls.
