### ISSUE TITLE
Source mapping support

### ISSUE THREAD

**Issue by Noah-Huppert** [lemurheavy/coveralls-public#420]
When working with certain pre-compiled languages like [Typescript](http://www.typescriptlang.org/) the only files that are in the repo are the Typescript files. The Javascript files are generated later on, usually when the code is deployed or right before tests are run.   

This creates an issue with Coveralls. On the Coveralls site when you try to view the coverage for a certain JS file, Coveralls does not know were the source for that file is because the generated file is not in the repo.  

The solution to this would be to look at the generate `.map` files. Google Chrome does this when debugging code. It will see that there is an error on line 20 of the JS file and then look at the `.map` file and see that this is actually line 4 in the Typescript file.  

It would be nice if Coveralls did the same thing, maybe when you are submitting a coverage report you could also submit the `.map` data.

**Comment by tomprince** [comment]
This seems like it would be something that should live in the tool that generates the coverage (or a tool that post-processes it), rather than in the display.
