### ISSUE TITLE
Not able to set up web hook notification

### ISSUE THREAD

**Issue by muktaa** [lemurheavy/coveralls-public#421]
I see the error as "500 internal server error". Would be good to see the details of the error.
The webhook URL that I am trying seems right - I can curl to that URL & do curl -X POST

**Comment by nickmerwin** [comment]
hi @muktaa was it a Slack webhook? We just released official Slack support if so.

**Comment by nickmerwin** [comment]
Closing for now.

**Comment by muktaa** [comment]
Yup, that works now. Thanks!
Can you also include the coverage percentage too in the notification?

**Comment by nickmerwin** [comment]
Ah it's already there as "covered_percent" in the json. Are you not seeing
it come through?

On Tuesday, January 20, 2015, Mukta Aphale <notifications@github.com> wrote:

> Yup, that works now. Thanks!
> Can you also include the coverage percentage too in the notification?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lemurheavy/coveralls-public/issues/421#issuecomment-70785194>
> .
>


-- 
Nick Merwin
*LEMUR Heavy Industries*
*p 323.275.4588 | c 213.304.2136 | lemurheavy.com <http://lemurheavy.com/>*

**Comment by muktaa** [comment]
I see the notification look like this on Slack (and email)
`gitorg/repo First build on git-sha on git-sha after commit: "commit-message" by user (https://coveralls.io/builds/id)`

**Comment by nickmerwin** [comment]
Good call @muktaa, ok I've added that to the notification:

![image](https://cloud.githubusercontent.com/assets/1129/5841734/fb33276a-a153-11e4-915f-78d9dbdd199f.png)

**Comment by muktaa** [comment]
Thanks a lot! Works now!
