### ISSUE TITLE
Feature request: update the svg badge

### ISSUE THREAD

**Issue by tagliala** [lemurheavy/coveralls-public#424]
Hi,

I love badges and I love them even more when all of them look the same :smile: 

edit:
![image](https://cloud.githubusercontent.com/assets/556268/5672658/d7afc7e6-9792-11e4-8e6a-8b73c40ff7d6.png)

Best regards

Geremia

**Comment by tagliala** [comment]
gemnasium and gemfury just switched to the new layout :)

https://github.com/badges/shields/issues/185#issuecomment-65898604

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/5672658/d7afc7e6-9792-11e4-8e6a-8b73c40ff7d6.png)

**Comment by nickmerwin** [comment]
hi @tagliala we now default to the svg badge to match the others.

Thank you!
