### ISSUE TITLE
Support AppVeyor

### ISSUE THREAD

**Issue by giggio** [lemurheavy/coveralls-public#429]
AppVeyor is a very nice .NET/Windows CI Server:
http://www.appveyor.com/
And it already works with Coveralls. Here is an example build with AppVeyor, using [Coveralls.NET](http://www.nuget.org/packages/coveralls.io):
Build:
https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.303
Coveralls site:
https://coveralls.io/r/code-cracker/code-cracker
Source is here:
https://github.com/code-cracker/code-cracker/

I am not sure what is needed to have a supported CI server on Coveralls, but as it is already working, you might want to include it.

**Comment by barryokane** [comment]
+1 for this :)

**Comment by laedit** [comment]
:+1:

**Comment by ethanhann** [comment]
+1

**Comment by nickmerwin** [comment]
Hi all, good call -- I've added http://www.nuget.org/packages/coveralls.io to our docs and listed AppVeyor to our supported CI's.

Thanks!

**Comment by giggio** [comment]
@nickmerwin Does this mean that Coveralls will be able to comment on PRs when the build happens in AppVeyor?

**Comment by nickmerwin** [comment]
@giggio it's possible, but I'm not sure that integration library supports it, although it would be trivial to add.

From Appveyor's docs (http://www.appveyor.com/docs/build-configuration):

```APPVEYOR_PULL_REQUEST_NUMBER```

Our API docs (https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference) show how to associate a build with a PR:

```service_pull_request```

**Comment by jayvdb** [comment]
Multi-job builds do not appear to group reports together.

**Comment by stevenvachon** [comment]
I had to add an env variable to make it work: https://github.com/lemurheavy/coveralls-public/issues/888#issuecomment-287960425
