### ISSUE TITLE
unicode in sourcefile not rendered

### ISSUE THREAD

**Issue by hayd** [lemurheavy/coveralls-public#430]
https://coveralls.io/files/422931532#L397 vs https://github.com/JuliaLang/julia/blob/8938e3a32c68910ccfa84d5bb5f6c7850920a38a/base/reduce.jl#L397

**Comment by laedit** [comment]
:+1:

**Comment by lexi-lambda** [comment]
:+1:, I have this problem, too.

Same as https://github.com/lemurheavy/coveralls-public/issues/273, but more general.

**Comment by msakai** [comment]
:+1:

**Comment by diplay** [comment]
:+1:

**Comment by ocadaruma** [comment]
:+1:

**Comment by hiraiva** [comment]
:+1:

**Comment by Dawny33** [comment]
Is there any progress made on this?

As JuliaLang is developing very fast, it would be really good if unicode rendering support is added for the source code.
