### ISSUE TITLE
Source code not found for files in subdirectory

### ISSUE THREAD

**Issue by aimeos** [lemurheavy/coveralls-public#431]
I've tried to upload a new coverage file for an Aimeos extension using php-coveralls which has it's own repository but is located in an ext/ai-container/ subdirectory during code coverage analysis.

Changing the Git repo root option to "ext/ai-container" doesn't work, it still says that the source file on GitHub couldn't be found (https://coveralls.io/files/427024809). Then, I've patched php-coveralls to create relative path names without "ext/ai-container" and removed the repo root option again but that doesn't work either (https://coveralls.io/files/427056480).

**Comment by nickmerwin** [comment]
Hi @aimeos looks like the files are loading now. Thanks!
