### ISSUE TITLE
Commit information is displayed from other random repos!

### ISSUE THREAD

**Issue by aq1018** [lemurheavy/coveralls-public#432]
This is a private golang repo: https://coveralls.io/r/3dna/gopkg

However, it is displaying commits, authors, and branches from a unknown rails based repo. This is outrages! This can potentially leak private information and should be fixed immediately!

**Comment by nickmerwin** [comment]
Hi @aq1018 please see our troubleshooting section here:

https://coveralls.zendesk.com/hc/en-us/articles/201342479-Quick-help-For-Common-Problems

> Make sure you have "service_name: travis-pro" in your .coveralls.yml.
> Travis uses non-unique job id's between its free and pro services, so when Coveralls doesn't know that your service-name is Travis-pro, it looks up the info for those job ids using the free Travis API -- that's why they will show random committers, etc. The opposite cannot happen with the proper credentials, so you don't need to worry that your data is leaking out. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis's pro API.
