### ISSUE TITLE
Switch source hangs

### ISSUE THREAD

**Issue by tbekolay** [lemurheavy/coveralls-public#434]
After renaming a repo on Github, I was delighted to see that the "switch repo source" option existed! However, when I try to switch the repo source, the "Change repo source" button changes to "Please wait..." and nothing happens, no matter how long I wait.

I've given coveralls the OAuth credentials it wants, but this still doesn't seem to work. Any help would be appreciated, though if we love the coveralls history, no bigs :)

**Comment by nickmerwin** [comment]
hi @tbekolay sorry about that, this is fixed now!

**Comment by tbekolay** [comment]
Can confirm that it's fixed now. Thanks very much!
