### ISSUE TITLE
Coverage badge outdated

### ISSUE THREAD

**Issue by simon3z** [lemurheavy/coveralls-public#436]
The badge shown by the readme file at:

https://github.com/simon3z/virt-deploy

is outdated (1 day old at the moment of this writing). Badge is showing 12% and should display 31%.

**Comment by nickmerwin** [comment]
Hi @simon3z sorry about that -- it's updated now. 

Also I noticed your badge isn't linking to the repo on Coveralls, but just to the image itself.

**Comment by simon3z** [comment]
@nickmerwin actually it's not updated yet, it's still flapping between "unknown" and "12%". Real coverage is ~80%.

**Comment by nickmerwin** [comment]
Hi @simon3z sorry, the issue was the cache-control header on our SVG badges -- I just fixed that yesterday so I think Github is serving the cached image. You could break the cache by removing "branch=master" from the url since it will default to that.
