### ISSUE TITLE
Not getting updates at all

### ISSUE THREAD

**Issue by teleyinex** [lemurheavy/coveralls-public#438]
Hi,

It looks like your service is not updating our coverage in the last month. How can we force a run?

**Comment by teleyinex** [comment]
Ok, I've found the issue. It's related to probably running within the new Travis Docker containers. I'll keep you posted.

**Comment by fattenap** [comment]
Hi,

I'm too am experiencing problems with updates. I received the initial update but haven't received once since. It's been a few days now.
https://coveralls.io/r/entrendipity/astarisx?branch=master

Thanks

**Comment by teleyinex** [comment]
Hi,

The problem was Travis docker containers. We were installing coveralls in the before section, and now it's been moved to the after section solving the issue. To me this issue is solved. @fattenap are you using docker in Travis?

**Comment by fattenap** [comment]
No. So unfortunately my problem still persists. Thx

**Comment by teleyinex** [comment]
Sorry to hear that. I'm closing this issue, as this has been solved for me.
