### ISSUE TITLE
Unable to delete repository

### ISSUE THREAD

**Issue by vonnagy** [lemurheavy/coveralls-public#439]
I would like to delete one or more repositories. By looking at some documentation, it showed a "Delete" button, but I can not find that. I have also deleted my account and revoked access to Coveralls from GitHub.

I am using a free account by using my GitHub credentials and building through TravisCI.

Please help me delete my repositories as I want to start over.

Thanks,

Ivan

**Comment by nickmerwin** [comment]
Closing since we're conversing via help desk. Thanks.
