### ISSUE TITLE
Can't add repo from organization

### ISSUE THREAD

**Issue by trevorallred** [lemurheavy/coveralls-public#444]
I just created an account but one of my connected organizations isn't visible, so I'm not able to add any repos from that org. I'm on https://coveralls.io/repos/new

I've checked the settings for each of my organizations and there doesn't seem to be any difference.

My organization that's missing is https://github.com/tantalim

**Comment by nickmerwin** [comment]
Hi, it looks like your membership to that organization isn't public so you'll need to upgrade your OAuth for Coveralls to see it:

Https://coveralls.io/refresh?private=true

**Comment by trevorallred** [comment]
Thanks! That fixed it.
