### ISSUE TITLE
Provide API for specifying PR or branch information with coverage reports.

### ISSUE THREAD

**Issue by tomprince** [lemurheavy/coveralls-public#446]
Currently, if one isn't use one of the supported CI providers, there is no way to associate results with a PR. It would be nice if the API allowed me to pass this information to coveralls, if I have access to it.

Ideally, I'd like to specify the commit, the branch it will be merged to, and whether the build is against the result of merging, since we do builds before creating a PR, rather than after. This seems like it should be enough information to report commit status (#25).

**Comment by nickmerwin** [comment]
Hi @tomprince actually you can pass this to the API already. See this section of the ruby gem: 
https://github.com/lemurheavy/coveralls-ruby/blob/master/lib/coveralls/configuration.rb#L86

What integration library are you using?

**Comment by tomprince** [comment]
It doesn't appear to be [documented](https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction).

Also, it would be nice not to need to know the pull request. We often (usually?) build and test things before opening a PR, so that information isn't available when we submit it.

**Comment by nickmerwin** [comment]
Ok I've updated the docs.

Sorry I'm not sure what you mean by not needing the know the PR -- if it wasn't yet associated with one it would build on another branch per usual. Could you clarify?

Thanks!
