### ISSUE TITLE
Mention Julia in plugins page

### ISSUE THREAD

**Issue by IainNZ** [lemurheavy/coveralls-public#447]
Can you mention the Julia package for reporting to Coveralls, [Coverage.jl](https://github.com/IainNZ/Coverage.jl), somewhere in your docs? As you can see from the partial list of packages using it, its fairly popular in the Julia packaging world (I've been evangelizing it!) and I want to make sure no one misses that the functionality is there.

I've [tweeted](https://twitter.com/iaindunning/status/558288364475252736) `@CoverallsApp` a couple of times, but haven't got a response, but it may be on someones radar already.

**Comment by anjin** [comment]
Added to the docs. Thanks for letting us know Iain!

**Comment by IainNZ** [comment]
:+1:
