### ISSUE TITLE
Python and codeship: Couldn't find a repository matching this job. 'url'

### ISSUE THREAD

**Issue by leebrooks0** [lemurheavy/coveralls-public#449]
Here is what we are doing on Codeship:

```
source ~/.python3_venv/bin/activate
pip install -r requirements.txt
pip install coveralls
flake8 .
coverage run -m py.test
coveralls
```

We are using this library for python support

Here is the error we get after running ```coveralls```:

```(.python3_venv)Submitting coverage to coveralls.io... Coverage submitted! Couldn't find a repository matching this job. 'url' (.python3_venv)```

**Comment by nickmerwin** [comment]
Hi @leebrooks0, that sounds like the integration library isn't passing your repo token properly in the API call. Could you double check their docs?

If everything still looks good from your end you may need to open an issue with the maintainers.

Closing for now, but will watch out for your response.

Thanks!
