### ISSUE TITLE
Badge showing "coverage unknown", page showing 94%

### ISSUE THREAD

**Issue by jmcvetta** [lemurheavy/coveralls-public#45]
I have been working on [a fork](https://github.com/jmcvetta/goveralls) of [`goveralls`](https://github.com/mattn/goveralls), a Coveralls client for [Go](http://golang.org).  So far as I can tell it is now submitting a correctly formed [API request](https://coveralls.io/docs/api_reference).  

When I look at the page for a project I have been testing with - https://coveralls.io/r/jmcvetta/o2pro - it shows 94% coverage.  Yet the badge continues to read "coverage unknown".  Is my client not submitting some required piece of information?

**Comment by petemoore** [comment]
I get this too, e.g. see https://coveralls.io/repos/taskcluster/taskcluster-proxy/badge.svg?branch=master&service=github (but i have this for several repos, not just this one)

**Comment by andela-sjames** [comment]
https://coveralls.io/builds/3649289, but on my repo i have coverage unknown on my repo

**Comment by nickmerwin** [comment]
@andela-sjames I see 40% coverage now on that repo, could you confirm?

**Comment by andela-sjames** [comment]
https://github.com/andela/troupon/tree/feature-coverage .... not sure why i can't see it though...

**Comment by nickmerwin** [comment]
@andela-sjames since you're not using the `master` branch, your badge code should include `?branch=feature-coverage`, i.e.:

[![Coverage Status](https://coveralls.io/repos/andela/troupon/badge.svg?branch=feature-coverage&service=github)](https://coveralls.io/github/andela/troupon?branch=feature-coverage)

**Comment by andela-sjames** [comment]
Thanks.... It's working now.....

**Comment by trodicaro** [comment]
https://github.com/chi-cicadas-2015/hey-9 - Coverage unknown. Not sure why it doesn't work.

**Comment by AidanRocke** [comment]
Same problem here: https://coveralls.io/github/AidanRocke/behavioral_syntax

**Comment by frecco75** [comment]
Hi, I have the same problem here: https://coveralls.io/github/frecco75/mowitnow
95%, but the readme badge using markdown still show "coverage unknown".

**Comment by joshblum** [comment]
+1
note: i noticed if i change the badge to be `.png` instead of `.svg` it renders the correct number (although png doesn't look as nice :/)

**Comment by eikebartels** [comment]
For me too! Always unknown!

**Comment by tclose** [comment]
Is it related to this https://github.com/github/markup/issues/224 or this https://github.com/lemurheavy/coveralls-public/issues/220?

**Comment by 1fabiopereira** [comment]
Me too https://github.com/1fabiopereira/node-sortable

**Comment by povilasb** [comment]
Same here: https://github.com/povilasb/scrapy-html-storage

**Comment by kboygit** [comment]
hello coverage unknown too : https://github.com/kboygit/cebu

**Comment by Ashaba** [comment]
Hello, was showing a badge before, but now everything is lost:

https://coveralls.io/github/Ashaba/BucketList

**Comment by Ashaba** [comment]
https://github.com/Ashaba/BucketList

**Comment by AlbertoLourenco** [comment]
I have same problem here. What happens and what I have to do?

**Comment by softprops** [comment]
same with me for a private repo. coverages seems correct but badge says unknown, presumably because it looks like branch is unknown. Im using the repo token from travis. the coveralls ui shows me that their is coverage but the badge shows unknown

**Comment by bingo-soft** [comment]
In 2019 still get this "coverage unknown" issue in my [repo](https://github.com/bingo-soft/graphp)
