### ISSUE TITLE
Question re Coveralls.io permissions

### ISSUE THREAD

**Issue by sabhiram** [lemurheavy/coveralls-public#452]
Hey Folks,

Any idea why Coveralls needs Repository access to github for private and public repos? I never signed up for Coveralls Pro, but yet am being prompted to grant it permissions. What gives? Sorry to create an issue if this is common knowledge.

**Comment by sabhiram** [comment]
Seems like logging out and logging back in resolved the issue. Perhaps this has to do with the omni auth changes made recently?

**Comment by nickmerwin** [comment]
Hi @sabhiram, that's odd, we recently included the request for "commit:status" OAuth permissions, but didn't change the private repo requesting. Could you have come to the site via this link?

https://coveralls.io/refresh?private=true

That URL forces an OAuth upgrade.
