### ISSUE TITLE
How is the "coverage increased" percent determined??

### ISSUE THREAD

**Issue by GeorgeJahad** [lemurheavy/coveralls-public#453]
Hi we recently started using coveralls, and are seeing some odd numbers in coverage changed field.  For example, this build: https://coveralls.io/builds/1822610, says there is a 23% increase in coverage.  I'm pretty sure that is wrong but I'm having trouble determining what it is being compared to?  When you see the percent changed, how do you determine which are the two builds being compared?

Thanks much for any insight you can offer!

George

**Comment by nickmerwin** [comment]
Hi @GeorgeJahad when the build is a PR, it calculates the change from the base build; in this case GH reported that is was:

https://coveralls.io/builds/1749301
