### ISSUE TITLE
judy/kanina has builds on Travis CI, but isn't showing up in Coveralls.

### ISSUE THREAD

**Issue by judy-zz** [lemurheavy/coveralls-public#454]
I've renamed this project from Hare to Kanina, in order to get the gem up on Rubygems.org. (Hare was already taken as a gem name.) Hare was working on Coveralls fine, but after creating a new repo, I'm not seeing any coverage for [Kanina on Coveralls](https://coveralls.io/r/judy/kanina). The [build on TravisCI](https://travis-ci.org/judy/kanina) is working. I'm not sure what's going on.

**Comment by nickmerwin** [comment]
Hi @judy I don't see Coveralls API submit output in your Travis job:
https://travis-ci.org/judy/kanina/jobs/50234764

Could you try running it without CodeClimate's reporter? It may be conflicting.

Thanks!
