### ISSUE TITLE
Jobs appear on sidebar but no coverage displayed

### ISSUE THREAD

**Issue by argon** [lemurheavy/coveralls-public#456]
I am trying to setup my project argon/node-apn but my coverage reports aren't being processed.

Am I doing something wrong?

I initially uploaded a report from my local machine using node-coveralls, which worked correctly and appeared in the UI. I next configured my [Travis build](https://travis-ci.org/argon/node-apn) to upload coverage with the same commands, but it failed to work.

The travis **jobs** were appearing on the sidebar UI but the **latest build** always showed the initial upload I performed, never updating to display newer results.

I was able to click on **latest job** and it displayed the repository but claimed there was no coverage information available and all icons were gray.

After trying a number of things I deleted the entire repo on coveralls, started again and now nothing is appearing except the jobs on the sidebar. On the latest job the files appear but show **no data**

Am I doing something wrong?

**Comment by tofu-rocketry** [comment]
I'm having a similar issue here.

#457 sounds like it could be the same problem.

**Comment by nickmerwin** [comment]
Hi guys, we had a queue pile up last night, your builds should all be processed now -- please let me know if that's not the case.

Thanks!
