### ISSUE TITLE
Builds behind?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [lemurheavy/coveralls-public#457]
My builds (https://coveralls.io/r/sunsetmtn84/video_processing_pipeline?branch=master) say 7 hours ago for the last build, but I've been doing a bunch of data-sends since then, same as before hours ago.

Is there a status.coveralls.io so I know when things are down?

**Comment by nickmerwin** [comment]
Hi @GeoffreyPlitt we had a queue pile up last night, your builds should all be processed now -- please let me know if that's not the case.

We're working on a status page now.

Thanks!

**Comment by GeoffreyPlitt** [comment]
Thanks!

On Thu, Feb 12, 2015 at 9:31 AM, Nick Merwin <notifications@github.com>
wrote:

> Hi @GeoffreyPlitt <https://github.com/GeoffreyPlitt> we had a queue pile
> up last night, your builds should all be processed now -- please let me
> know if that's not the case.
>
> We're working on a status page now.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lemurheavy/coveralls-public/issues/457#issuecomment-74114211>
> .
>



-- 
http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915
