### ISSUE TITLE
Public github org (with publicised membership) not showing up

### ISSUE THREAD

**Issue by rebkwok** [lemurheavy/coveralls-public#458]
I have a public repo in a public github organisation, https://github.com/djangogirlsjobs/djangogirls.  My membership of the organisation is publicised.  I'm not getting any coverage reports on coveralls, and the coverage link from the PR (https://github.com/djangogirlsjobs/djangogirls/pull/8) goes to a permission denied page.  How can I get this repo to show up?

**Comment by nickmerwin** [comment]
Hi @rebkwok it doesn't look like we have any builds from your repo:

https://coveralls.io/r/djangogirlsjobs/djangogirls

What CI are you using?

Closing for now. Thanks!

**Comment by rebkwok** [comment]
Travis CI - if you look at the PR link I posted you can see that it shows
the Travis build as passed and the Coveralls coverage as pending. If I
click the details link, I get a you-don't-have-permission-to-view-this page.

**Comment by nickmerwin** [comment]
Ok, it appears the repo was removed from Coveralls, and then re-added. The build that the PR status links to no longer has an associated repo in our system.

Could you trigger another build to test the new repo?

**Comment by rebkwok** [comment]
That's working now, thanks a lot
