### ISSUE TITLE
More intuitive error message on invalid repo_token

### ISSUE THREAD

**Issue by theon** [lemurheavy/coveralls-public#46]
If I send an incorrect repo_token to the coveralls API I get the following error message back.

```
Build processing error.
```

This message doesn't make it very obvious that the repo_token is the problem. Could it be changed to return a more intuitive error message?

**Comment by rorygraves** [comment]
@theon I think this is changed now - I see 'Couldn't find a repository matching this job' rather than 'Build processing error'  (I'm working on some fixes for sbt-coveralls.
