### ISSUE TITLE
coverage badge not being reported properly

### ISSUE THREAD

**Issue by cluttered-code** [lemurheavy/coveralls-public#460]
the current build is showing 100% coverage but my badge says unknown.

**Comment by Bogardo** [comment]
+1 I'm also having this problem.
See https://github.com/github/markup/issues/224

According to [bkeepers](https://github.com/bkeepers):
> Assets must include Cache-Control: no-cache and ETag headers. If a badge is not updating, then it means they are not properly setting these headers. See [my comment](https://github.com/github/markup/issues/224#issuecomment-37663375) for more info

**Comment by nickmerwin** [comment]
hi @cluttered-code which repo is the one you're seeing an issue with?

**Comment by cluttered-code** [comment]
The issue is gone for me, I switched me continuous build environment from
codeship to Travis and the issue is gone. I believe I wasn't setting all
the environment variables correctly using codeship. I did also destroy that
project on your site and then add it again with Travis

**Comment by evoskuil** [comment]
Coveralls is not setting an ETag, which GitHub [claims is important](https://github.com/github/markup/issues/224):
```
HTTP/1.1 302 Found
Server: cloudflare-nginx
Date: Sat, 16 May 2015 22:11:13 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=[snip]; expires=Sun, 15-May-16 22:11:13 GMT; path=/; domain=.coveralls.io; HttpOnly
Status: 302 Found
Location: https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_unknown.svg
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
X-Request-Id: 1a5a30d4e9f1e28d34f22cf526d89918
X-Runtime: 0.039427
X-Rack-Cache: miss
X-Powered-By: Phusion Passenger 4.0.42
X-Powered-By: cloud66
CF-Cache-Status: MISS
CF-RAY: 1e7a6acbe6b51bd3-SEA
Content-Length: 139

<html><body>You are being <a href="https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_unknown.svg">redirected</a>.</body></html>
```
So the image references cached by GitHub are not refreshed when status changes. From reading over the history this has been a *very* longstanding problem.

**Comment by simonjbeaumont** [comment]
:+1:

**Comment by gvolpe** [comment]
I'm facing the same issue. The last build report a coverage of %95.45 but the badge shows unknown.

It seems that the problem is that Coveralls is creating a new branch for every commit but I can see only the master branch.

This is my project: https://coveralls.io/github/gvolpe/light-play-rest-api. I'm using Codeship for CI.

**Comment by nickmerwin** [comment]
Hi @gvolpe your branch is showing ```5d6b8dc3f59139fd116943141fff1bb627036128```, and Coveralls is looking for `master` by default. Could you check your Coveralls integration library configuration?

@evoskuil we're now including an ETag for badges, thank you!

**Comment by evoskuil** [comment]
@gvolpe Cool, thanks!

**Comment by gvolpe** [comment]
Hi @nickmerwin 

I think the configuration is fine. The branch you mentioned is created by Coveralls using the commit hash as a name (https://github.com/gvolpe/light-play-rest-api/commit/5d6b8dc3f59139fd116943141fff1bb627036128), and actually it's creating a new branch with every commit. If you take a look at my repository the only existent branch is master (https://github.com/gvolpe/light-play-rest-api/branches).

I'm using this version: addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.0.0")
