### ISSUE TITLE
Coveralls.io permissions

### ISSUE THREAD

**Issue by powerman** [lemurheavy/coveralls-public#461]
I see there are some closed issues related to this (like #452) but this bug happens again, so something should be fixed before closing this issue.

I've used travis-ci.org and coveralls.io for my public repos. A couple of days ago one of organizations I work for has signed for travis-ci.com for it private repos. Today I open coveralls to add my new public repo. At first, it asked me to allow "Access commit status" permission, which I've allowed. Next, I've press "reload repos" button to add new repo into the list, and it say "repos refreshing..." and then hangs. After I've reloaded this page I got request to allow full access to my repos. And now when I try to open http://coveralls.io/ it request full read/write permissions to all my public/private repos, which I won't wanna allow - why the hell you need WRITE permissions to my code, issues and wiki for coveralls functionality???

I'm now going to revoke all coveralls permissions and start over again - maybe this will helps.

**Comment by powerman** [comment]
After revoking access I still see request for email+full repos permissions.

After deleting all cookies for coveralls.io I was able to open website without being redirected to github's authorize access page. On SignIn I got request for email+commit status. After that I've found my new public repo in list and was able to enable coveralls for it. So, this "work around" is working.

Now I've tried again to push "sync github repos" button. I see "Your GitHub repositories are being refreshed!" and "Your repos are syncing...", but looks like it hangs again. But reloading this page now works ok - it didn't request any new permissions, just show list with repos.

**Comment by jmorford** [comment]
@powerman did you ever find a solution to this problem? Is coveralls.io still being maintained and supported?

**Comment by powerman** [comment]
@jmorford Not a solution, but after all workarounds and page reloads mentioned in my previous comment it works ok.

**Comment by moofish32** [comment]
I'm facing this exact issue currently.  I am getting a 422 when I click add repo and seeing the following message:
base: ["Couldn't determine GitHub settings."]

I've authorized coveralls on github, revoked, re-authed, cleared cookies, and tried firefox and chrome via Mac Yosemite.

**Comment by ericdouglas** [comment]
Same issue here...

**Comment by anshulverma** [comment]
There seems to be a migration going on at the moment. So if this is still happening for anyone, keep an eye out for this: http://blog.coveralls.io/2015/07/23/Downtime-From-Big-Migration/

**Comment by nickmerwin** [comment]
Thanks @anshulverma -- the migration is done, if anyone still has issues, please log out / in to refresh your github token.

Thank you!

**Comment by anshulverma** [comment]
Yup..that fixed it. Thanks @nickmerwin
