### ISSUE TITLE
Automating the process of enabling repo in Coveralls and fetching tokens for Travis

### ISSUE THREAD

**Issue by lakomiec** [lemurheavy/coveralls-public#464]
As stated in subject, I am trying to automate the process of enabling github repository in Coveralls and fetching tokens for Travis CI. That way I could quickly setup new projects from a template with basic code coverage tests.

Unfortunately current API doesn't seem to allow that and one has to manually login to coveralls.io, enable repository manually and fetch tokens to .coveralls.yml file.

Is my understanding wrong and I am missing something or everyone does that step manually? :)

**Comment by simonewebdesign** [comment]
I wish it was easier too. It is also sad that 2 years later the process hasn't improved at all.

**Comment by kopax** [comment]
I am having the same issue.

We want to have coveralls for all our repo and we need this automated. Why is the API not purposing at least:

- refresh repo endpoint
- activate repo endpoint

?

**Comment by kopax** [comment]
Is there a way to do it using the request used by the web ? I see there is a x-csrf-token when enabling the repo :  


```bash
curl 'https://coveralls.io/repos.json' -H 'origin: https://coveralls.io' -H 'accept-encoding: gzip, deflate, br' -H 'x-csrf-token: [secure]' -H 'accept-language: en-US,en;q=0.9,fr;q=0.8,vi;q=0.7' -H 'x-requested-with: XMLHttpRequest' -H 'cookie: __cfduid=[secure]; optimizelyEndUserId=[secure]; optimizelyBuckets=%7B%7D; _ga=[secure]; __stripe_mid=fda31177-40b7-4e54-ab87-849b11d58750; optimizelySegments=%7B%222412740790%22%3A%22gc%22%2C%222436200870%22%3A%22referral%22%2C%222450690451%22%3A%22false%22%7D; after_oauth_redirect=; _coveralls_session=[secure]; _gid=[secure]; _gat=1; __stripe_sid=[secure]' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'accept: */*' -H 'referer: https://coveralls.io/repos/new' -H 'authority: coveralls.io' -H 'dnt: 1' --data 'authenticity_token=[secured]&service=github&repo%5Bname%5D=kopax%2FDATAREST-991&repo%5Bcached_repo_info%5D%5Bservice%5D=github&repo%5Bcached_repo_info%5D%5BpermissionsPush%5D=&repo%5Bcached_repo_info%5D%5BpermissionsPull%5D=&repo%5Bcached_repo_info%5D%5BpermissionsAdmin%5D=&repo%5Bcached_repo_info%5D%5BfullName%5D=kopax%2FDATAREST-991' --compressed
```

There are quite a few `[secure]` value here like the `x-csrf-token`, the `session` and the `token`. 

Would be interesting to know if somebody did already reverse engineering all that.
