### ISSUE TITLE
Keep getting {"message":"Couldn't find a repository matching this job.","error":true}

### ISSUE THREAD

**Issue by ayanonagon** [lemurheavy/coveralls-public#465]
I read through a related sounding issue (https://github.com/lemurheavy/coveralls-public/issues/279) but we’re getting the same problem on a public GitHub repo.

```
RestClient::UnprocessableEntity
422 Unprocessable Entity
...
{"message":"Couldn't find a repository matching this job.","error":true}
```

Entire build log: https://travis-ci.org/venmo/slather/builds/43872184

Any insight would be much appreciated, thank you! :octocat:

**Comment by nickmerwin** [comment]
hi @ayanonagon when you use Travis you don't need to include the .coveralls.yml file, it's implied. Could you try removing it and triggering another build?

Thanks!

**Comment by ayanonagon** [comment]
Hi @nickmerwin, thank you for the quick reply. I tried removing `.coveralls.yml` but seem to still be getting the same error: https://travis-ci.org/venmo/slather/builds/51772528 Let me know if I can give any more info to help debug, thanks again!

**Comment by nickmerwin** [comment]
Ok, that's odd, this is throwing it off:
```"travis_job_id": "9182"```

That job id is way too low for Travis, which is usually something more like "51378452". And since your build isn't split out into multiple jobs, there isn't an actual job id, yet that ENV var is still getting set at build time. 

I'm digging into the Travis docs now to see what I can find about this.

**Comment by nickmerwin** [comment]
Found it! Travis pointed out the issue -- the ENV var is being overwritten in your test suite:

https://github.com/venmo/slather/blob/c4e7c911d06490ea316fcd1d75aa0515d5c726d7/spec/slather/coverage_service/coveralls_spec.rb#L17

**Comment by ayanonagon** [comment]
Wow, nice catch @nickmerwin!! Thanks so much for your help. I’ll update my PR with that fix. Thanks again. :smile_cat:
