### ISSUE TITLE
Repo percent not updating

### ISSUE THREAD

**Issue by lynxbat** [lemurheavy/coveralls-public#467]
The reported coverage for my repo on the coveralls page is showing 77% when it is 95%. The badge appears to work anyways but this has been frozen for a while.

**Comment by nickmerwin** [comment]
Hi @lynxbat could you link me to the repo in question?

**Comment by denera** [comment]
I'm piggybacking on this to say that we're having the same problem with our repo.

There are a lot of support tickets online about this that point to GitHub's aggressive image caching as the source of the problem. They kind of push the issue onto the badge sources, saying badges should come with a no-cache tag, and then the badge sources push the issue onto GitHub. Round and round it goes.

It would be nice to get a reliable solution implemented for this.

Problematic repo in question: https://github.com/OptimalDesignLab/Kona

**Comment by arnodb** [comment]
Hi, I suspect this is related to the so called aggressive caching issue https://github.com/github/markup/issues/224 which says "make sure the image has the Cache-Control: no-cache header, and either Expires, Last-Modified or Etag".

I am pretty sure the "coverage: unknown" badge is missing the last 3 headers, I also suspect the "coverage: 0%" to be affected. For the other values the headers seem OK.

Note: experimentation shows that the github cache lasts 1h.

**Comment by jedwards1211** [comment]
see github/markup#949
