### ISSUE TITLE
Organizations won't show up in my list of repositories.

### ISSUE THREAD

**Issue by nicolasnoble** [lemurheavy/coveralls-public#470]
So I want to use the service, but in the add repos page - https://coveralls.io/repos/new - I see only my personal repositories, and not my organizations repositories. I am the owner of one organization - https://github.com/grumpycoders - that has a few repositories in it, and I am part of two other organizations, that have quite a few repositories in it. Travis-ci or review-ninja both see my organization's repositories without issues, but coveralls don't.

Please advise.

**Comment by nicolasnoble** [comment]
Actually, it was a matter of enabling "private" repos, even though they are not privates. This is a confusing bit of UI right there.

**Comment by tomekwi** [comment]
Thanks @nicolasnoble – I struggled with that as well.

**Comment by tobiasmcnulty** [comment]
@nicolasnoble @tomekwi what do you mean by "enabling" private repos? I'm having the same problem but I can't even find my organization in coveralls, so I can't enable anything. Thanks for your help!

**Comment by tobiasmcnulty** [comment]
My organization is here and as you can see my membership is public: https://github.com/django-cache-machine

**Comment by tobiasmcnulty** [comment]
For anyone else with this issue, I finally found a solution. We had a "Third-party application access policy" set up in GitHub, and even though Coveralls was authorized by this policy, it wasn't showing this organization or any of its repos. As soon as I removed the policy and resynced the repos, it showed up in Coveralls (twice, actually).
