### ISSUE TITLE
Git repo root directory changes have no effects

### ISSUE THREAD

**Issue by bugalood** [lemurheavy/coveralls-public#471]
Dear Coveralls,

Thanks for this wonderful project ! Everything works fine with me but a single thing. Indeed, when I try to look at the source code of a file through the coveralls website, it tells me **Source unavailable** and advise to change the values of the **Git repo root directory** and **Git repo sub directory** fields.

When I change values and click the **update** button, I'm redirected to the *Latest builds* page of my repo with the success message **Repo was successfully updated**. However, when I go back on the source file to check if my changes are correct, the original values appear for the **Git repo root directory** and **Git repo sub directory** fields.

Maybe I am doing something wrong? Can you help me to solve this?

All the best!
Jérôme

**Comment by nickmerwin** [comment]
Hi @bugalood, we've just deployed a fix for this. Could you give it another try and let me know if you're still seeing the issue?

Thank you!

**Comment by bugalood** [comment]
I just changed the values, and it now works perfectly! I can see the source code.

Thanks a lot for your reactivity and for coveralls!

Cheers,
Jérôme
