### ISSUE TITLE
Fail to detect my badge on my readme.me

### ISSUE THREAD

**Issue by stevemao** [lemurheavy/coveralls-public#474]
I have this kind of badge format

``` md
 [![Coverage Status][coverall-image]][coverall-url]

[coverall-image]: https://coveralls.io/repos/stevemao/conventional-commits-parser/badge.svg
[coverall-url]: https://coveralls.io/r/stevemao/conventional-commits-parser
```

I like this format because it makes my markdown very clean. But https://coveralls.io/ thinks I don't have a badge.

**Comment by kevmoo** [comment]
Ditto for this repo

![screen shot 2015-06-03 at 4 22 44 pm](https://cloud.githubusercontent.com/assets/17034/7973655/dc332a14-0a0c-11e5-9263-5b478d660efc.png)

**Comment by WoLpH** [comment]
And I can report the same for https://coveralls.io/r/WoLpH/mt940?branch=master / https://github.com/WoLpH/mt940/
