### ISSUE TITLE
Coveralls failing to show coverage information

### ISSUE THREAD

**Issue by es128** [lemurheavy/coveralls-public#475]
https://coveralls.io/builds/2082448

The lcov was clearly received - in the files section it shows lines covered and missed, even the change from previous builds. However, all the coverage percentages are showing as "No Data".

What is going wrong?

**Comment by makmanalp** [comment]
I think I have the exact same issue, though mine is a new project: https://coveralls.io/builds/2083023

**Comment by flippmoke** [comment]
I have the same issue as well with my project https://coveralls.io/r/mapnik/node-mapnik

**Comment by es128** [comment]
Seems to have been resolved now
