### ISSUE TITLE
Badge show "unknown" coverage

### ISSUE THREAD

**Issue by Trufi** [lemurheavy/coveralls-public#477]
Hi, i added coverage statistics at map a long time ago, but badge is still showing "unknown" coverage https://github.com/2gis/mapsapi. However, coverage show on https://coveralls.io/r/2gis/mapsapi page. Can you help me?

**Comment by nickmerwin** [comment]
Hi @Trufi the issue is that all of the builds on your repo are for pull requests. The Coveralls badge will only show the current coverage % for builds on the repo itself.

Thanks!

**Comment by Trufi** [comment]
Thank you!

**Comment by marcellodesales** [comment]
This is happening to my repository...

https://github.com/intuit/node-pom-parser/
https://coveralls.io/github/intuit/node-pom-parser?branch=master

How can I fix this??? I noticed that the URL redirects to a resource on Amazon with the percent value... Would that be a problem? Accessing the URL from the browser works, but not from the README.md.
