### ISSUE TITLE
Seeing commits from other private repos

### ISSUE THREAD

**Issue by binarylogic** [lemurheavy/coveralls-public#483]
I have a [private project](https://coveralls.io/r/seatgeek/paulbunyan). I'm seeing commits / builds from people I don't know.

**Comment by binarylogic** [comment]
Deleted my repo, created a new one, and regenerated the token. I'm still seeing commits from people I don't know. This is awesome!

**Comment by nickmerwin** [comment]
Hi Ben, make sure you have ```service_name: travis-pro``` in your .coveralls.yml

More info here: https://coveralls.zendesk.com/hc/en-us/articles/201342479-Quick-help-For-Common-Problems

Thanks!

**Comment by binarylogic** [comment]
Yep, definitely have that.

**Comment by nickmerwin** [comment]
Ok which Coveralls integration library are you using?
