### ISSUE TITLE
Provate/Pro: Coveralls stopped showing coverage for all files

### ISSUE THREAD

**Issue by jacogr** [lemurheavy/coveralls-public#486]
https://coveralls.io/builds/2205746

I double-checked the lcov.info file that gets generated, all feels seem to be present and accounted for. In the coveralls console all files show up, but only some of them are showing coverage. This stopped working in the last day or so.

**Comment by nickmerwin** [comment]
Hi @jacogr sorry for the delayed response. It looks like from your latest builds that your files' coverage is being accounted for.

Did you recently change the version of your Coveralls integration library? That could have affected it.

Closing for now unless you can still see an issue.

Thanks!
