### ISSUE TITLE
Randomly getting error 'Couldn't find a repository matching this job'

### ISSUE THREAD

**Issue by szwacz** [lemurheavy/coveralls-public#487]
I'm randomly getting this error for open source Node.js repo and travis-ci build:
```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```
Most of the time the connection goes well, but once in a while it fails with this error.

Here is full data of such incident: https://travis-ci.org/szwacz/fs-jetpack/jobs/56279033

Hint: as I seen the error happens with Node.js version 0.12, but never noticed it on version 0.10 (https://travis-ci.org/szwacz/fs-jetpack/builds/56279031).

**Comment by TheSavior** [comment]
I'm getting this issue as well, about 1/6 builds. Since I have a matrix with 3 builds, that makes this extremely flaky.

**Comment by s0ph1e** [comment]
Some travis-ci builds throw error:
```
/home/travis/build/s0ph1e/node-css-url-parser/node_modules/coveralls/bin/coveralls.js:18
        throw err;
              ^
Bad response: 504 <!DOCTYPE html>
<html lang="en">
  <head>
<meta http-equiv="refresh" content="0">
<meta http-equiv="set-cookie" content="cf_use_ob=443; expires=Sat, 25-Apr-15 14:24:25 GMT; path=/">
<meta http-equiv="set-cookie" content="cf_ob_info=504:1dcab4a4a2ab0856:IAD; expires=Sat, 25-Apr-15 14:24:25 GMT; path=/">
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>
```
and
```Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}```

**Comment by s0ph1e** [comment]
@nickmerwin 
I started receiving 500 error randomly for my packages.
https://travis-ci.org/s0ph1e/node-website-scraper/jobs/59368954
https://travis-ci.org/s0ph1e/node-css-url-parser/jobs/60011110

**Comment by lukasoppermann** [comment]
I have the same error. Are you working on a fix?

**Comment by nlamirault** [comment]
Same thing here. Any news ?

**Comment by nickmerwin** [comment]
hi all, we're working on this now. Could one of you re-trigger a build for testing?

Thanks!

**Comment by koddsson** [comment]
Still getting it over here :<

**Comment by victorquinn** [comment]
Getting it [here](https://coveralls.io/r/victorquinn/chancejs) too.

The interesting bit is that everything seems to work otherwise. When I go to "Updates" from the left nav, I see that the builds hit Coveralls but they're gray and have a question mark that, when hovered, says "No data" so I'm not sure what happened. 

![screen shot 2015-05-05 at 4 08 53 pm](https://cloud.githubusercontent.com/assets/660139/7481822/0e2a9c88-f341-11e4-95ac-0297ccfbb734.png)

Seems like Coveralls got the request and failed to process it somehow?

**Comment by nickmerwin** [comment]
hi @victorquinn ok I found the issue -- your service_name parameter was coming in as "travis", as opposed to "travis-ci", which was tripping up our API. I've updated it to accept "travis" also now. Could you trigger another build?

Thanks!

**Comment by victorquinn** [comment]
That seemed to fix it! I can update my end to use "travis-ci" explicitly from here on if you need. 

I was under the impression that string was any string identifier; I did not know it had a set enumeration of values. 

Regardless, it would be nice in the future if the error message made a bit more sense. 

Thanks though @nickmerwin things look like they work!

**Comment by kunalgolani** [comment]
Still getting the error

**Comment by mkfifo** [comment]
I am now also getting this error constantly, my last successful update was from 23 hours ago.

I have tried this from both my work and home pcs, I also tried regenerating my tokens, all to no avail.

I am using cpp-coveralls to handle the upload, last night (23 hours ago) this was working 'fine'.

**Comment by tkoomzaaskz** [comment]
also got it here: https://travis-ci.org/tkoomzaaskz/json-schema-faker/builds/61471059

**Comment by jessamynsmith** [comment]
I just started getting this error on a previously working build.
https://circleci.com/gh/jessamynsmith/taotrack

**Comment by nickmerwin** [comment]
Hi guys we fixed an issue that should mitigate the 422 issue. Please try again now, thank you!

**Comment by tkoomzaaskz** [comment]
Shall we bump the version or do something else?

**Comment by nickmerwin** [comment]
@tkoomzaaskz have you set up the repo on Coveralls yet? I don't see it here: https://coveralls.io/r/tkoomzaaskz/json-schema-faker

**Comment by jessamynsmith** [comment]
It's working for me again.

**Comment by koddsson** [comment]
Thanks @nickmerwin :tada:

**Comment by mkfifo** [comment]
It is also working for me again.

**Comment by tkoomzaaskz** [comment]
I'm still getting this error (https://travis-ci.org/tkoomzaaskz/json-schema-faker/builds/62396254), but I've got no idea what is going on and what should I do.

**Comment by mantyr** [comment]
$ go get golang.org/x/tools/cmd/cover
$ go get github.com/mattn/goveralls
$ go install github.com/mattn/goveralls

$ go test github.com/mantyr/goquery -covermode=count -coverprofile=123.cov
ok  	github.com/mantyr/goquery	0.025s	coverage: 85.7% of statements
$ /usr/gobin/goveralls -coverprofile=123.cov -service=travis-ci
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}

I see https://github.com/mattn/goveralls and https://coveralls.zendesk.com/hc/en-us/articles/201342809-Go

Tried to use:
-repotoken
-service = travis-ci
-service = travis

Tell me how it is run, please.

**Comment by mantyr** [comment]
cat ./.travis.yml
language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci

This configuration returns:
Bad response status from coveralls: 500 - {"message":"Build processing error.","error":true,"url":""}
The command "$HOME/gopath/bin/goveralls -service=travis-ci" exited with 1.

**Comment by aivus** [comment]
I still getting 422 error:
https://travis-ci.org/s0ph1e/node-website-scraper/jobs/71037428

**Comment by ChristopherRabotin** [comment]
Any update on this issue? I get it on either travis Push or travis PR randomly it seems:
+ https://travis-ci.org/ChristopherRabotin/sg/jobs/82901327
+ https://travis-ci.org/ChristopherRabotin/sg/jobs/82781804
+ https://travis-ci.org/ChristopherRabotin/sg/jobs/82782681

**Comment by iamqizhao** [comment]
seeing this just now:
https://travis-ci.org/grpc/grpc-go

**Comment by iamqizhao** [comment]
It is flaky. I re-ran it several times to get green ...

**Comment by michaelaye** [comment]
Also got this at the end of my Travis job, trying to set up another repo with coveralls

**Comment by vitorbaptista** [comment]
Having the same issue on https://github.com/okfn/datapackage-py. If it helps, here's a build with `coveralls --verbose` https://travis-ci.org/okfn/datapackage-py/jobs/106964243

**Comment by Stasik0** [comment]
Same here

**Comment by miigotu** [comment]
Also getting this now
https://travis-ci.org/SickRage/SickRage/builds/106970461
.travis.yml simply has `after_success: coveralls` with no local coveralls config.
It was working until about 17 hours ago

**Comment by j-towns** [comment]
Also getting this issue
[https://github.com/j-towns/pymanopt](https://github.com/j-towns/pymanopt)

**Comment by ioquatix** [comment]
Same issue https://travis-ci.org/ioquatix/http-accept/builds/106922036

**Comment by lmjohns3** [comment]
I'm seeing this too: https://travis-ci.org/lmjohns3/theanets/jobs/106906300#L767

**Comment by saroele** [comment]
Same issue here on a previously working build: https://travis-ci.org/opengridcc/opengrid/jobs/107034976

**Comment by nickmerwin** [comment]
Hi all, we just deployed a potential fix for that. Could builds be re-triggered now?

Thank you!

**Comment by saroele** [comment]
Something is indeed working again, but the results are not correct.  I suddenly get 100% coverage on my files (was much lower), and the overall statistics say "coverage remained the same at ?%"
https://coveralls.io/builds/4971869

**Comment by saroele** [comment]
Everything seems ok now for me.  Thanks.

**Comment by vitorbaptista** [comment]
Working for me as well, thanks for the quick fix :+1:

**Comment by Stasik0** [comment]
+1 for working

**Comment by mweibel** [comment]
Getting this randomly as well, example links:

https://travis-ci.org/mweibel/lcov-result-merger/jobs/122562586
https://travis-ci.org/mweibel/lcov-result-merger/jobs/122562588

**Comment by miigotu** [comment]
@mweibel me too, seems to happen when both PR and PUSH jobs are submitting near the same time. I have added a `-` to the beginning of the coveralls line in my tox.ini so it submits when it succeeds but doesnt fail the build if coveralls fails to submit.

**Comment by michaelaye** [comment]
@miigotu Could you please show an explicit example tox.ini with the positioning of that dash? thx

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/blob/master/tox.ini#L17

**Comment by gilles-duboscq** [comment]
Same thing there:
https://travis-ci.org/chimpler/pyhocon/builds/122821766
2 jobs worked and 2 jobs failed
https://github.com/chimpler/pyhocon/blob/master/tox.ini

**Comment by touilleMan** [comment]
Same thing for me:
https://travis-ci.org/Scille/umongo/jobs/123910062#L375

My CI starts 6 jobs, jobs 3 and 6 couldn't send to coveralls, I restarted manually job 3 and this time it worked fine.

**Comment by TheSavior** [comment]
@nickmerwin This is clearly still an issue. Does it make sense to re-open this ticket?

**Comment by uptownhr** [comment]
I have just started receiving this error as well. Ran manually twice and still getting the error.

**Comment by vitalyisaev2** [comment]
This error is still here.

**Comment by pylover** [comment]
+1 , it's happened for me with last versions of python, coveralls

**Comment by aknuds1** [comment]
Having this issue for [html-to-react](https://github.com/aknuds1/html-to-react).

**Comment by pylover** [comment]
It seems the problem is pyyaml or libyaml.

Every project that used yaml in the code, will not working, for example:

https://travis-ci.org/pylover/pymlconf/jobs/166512950

**Comment by pylover** [comment]
The coveralls command just working fine on my local machine. But the same version is not working on travis box.

**Comment by cce** [comment]
I get this occasionally. Should I just my travis script sleep a bit and retry?

**Comment by cce** [comment]
For those who are also having this problem, using `travis_retry` seems to help as in: https://github.com/thriftrw/thriftrw-go/pull/69

**Comment by jedwards1211** [comment]
@nickmerwin could one of the causes be that two jobs in a build matrix try to upload coverage at the same time?

**Comment by pylover** [comment]
No, I used a condition, which prevents concurrent uploads.

**Comment by pylover** [comment]
```
5.44s$ if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry coveralls ; fi
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
The command "coveralls" failed. Retrying, 2 of 3.
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
The command "coveralls" failed. Retrying, 3 of 3.
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
The command "coveralls" failed 3 times.
```

**Comment by mirismaili** [comment]
Similar issue:

[Jub **45**](https://circleci.com/gh/mirismaili/simplatic-http-server/45):

```bash
/home/circleci/.npm/_npx/845/lib/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
Exited with code 1
```

Restarting the job without any change:

[Jub **46**](https://circleci.com/gh/mirismaili/simplatic-http-server/46): OK
