### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by fertapric** [lemurheavy/coveralls-public#488]
Hi!

When I try to see a file coverage I get `The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.`. I revoked permissions through GitHub admin, and re-authorized permissions using "PRO Sign-up" section". Still no luck.

Thanks for your help!

**Comment by nickmerwin** [comment]
Hi @fertapric what is the repo in question? I'll see what's up.

Thanks!

**Comment by fertapric** [comment]
Hi @nickmerwin!

The repo is `designerboard/designerboard`.

**Comment by nickmerwin** [comment]
hi @fertapric it looks like your account was re-initialized so it lost association with the subscription and repo. That's fixed now!

Happy covering!

**Comment by lmjohns3** [comment]
I'm just getting this same issue -- is there anything I can do to fix it? The repo is lmjohns3/theanets.

**Comment by lmjohns3** [comment]
Sorry for the false alarm, it seems to be working now!
