### ISSUE TITLE
Can't see private orgs repo

### ISSUE THREAD

**Issue by retospect** [lemurheavy/coveralls-public#489]
Hi, 
I can't see our orgs private repo here:
https://github.com/twoporeguys/tpg-code
I am an owner. 
I created a dummy public repo as well, can't see that either.

**Comment by nickmerwin** [comment]
Hi @retospect could you try the "refresh private repos" button at the top of this page:

https://coveralls.io/repos/new

Thanks!

**Comment by retospect** [comment]
Tried that, this organization/repo does not show up.
https://github.com/twoporeguys/tpg-code
I figured if I upgrade it would, but it did not.
I also tried https://coveralls.io/refresh?private=true, to no avail.
And I created a simple public repo at https://github.com/twoporeguys, but
that does not show either.

Thanks!

Reto

**Comment by nickmerwin** [comment]
Hi @retospect did you use the same user to create the "twoporeguys" organization? I've confirmed that even with a private scope, the GH API isn't returning anything from org when querying for your accessible repos.

**Comment by retospect** [comment]
I got it to work. I needed to turn off the "Third Party Access
restrictions" even though the app was authorized. Now it seems to work even
though I turned them on again.

Reto
