### ISSUE TITLE
Jenkins + GitHub Status API

### ISSUE THREAD

**Issue by ohwutup** [lemurheavy/coveralls-public#490]
I just switched over our builds from using Travis to using Jenkins now but Coveralls is not posting the results to the PR status API.

Any thoughts as to why?

**Comment by nickmerwin** [comment]
Hi @ohwutup unfortunately Jekins doesn't expose the PR number during build time like Travis/Circle, etc.

This plugin may be a solution though:
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by ohwutup** [comment]
thanks for the quick reply @nickmerwin, i am using that plugin, and it does report the status of the build to the status API upon initialization and completion (success or failure), but we no longer get the extra line item in there like when we were using travis that had coveralls separately.

**Comment by nickmerwin** [comment]
@ohwutup oh do you mean the Coveralls comment as the line item? Or the Status API line item?

It could be that you need to set up a webhook to let Coveralls know when the build is completed if they're running in parallel.
