### ISSUE TITLE
coveralls is posting  multiple  responses  for single pr

### ISSUE THREAD

**Issue by ChillarAnand** [lemurheavy/coveralls-public#491]
checkout these https://github.com/jorgenschaefer/elpy/pull/529   https://github.com/jorgenschaefer/elpy/pull/485

**Comment by Natim** [comment]
This is because your test matrix is running coveralls multiple times per coveralls.

**Comment by Natim** [comment]
My concern is how can we deactivate this comments?

**Comment by noirbizarre** [comment]
I confirm there seem to be a multiple comment by PR issue.
See MongoEngine/mongoengine#960 for an example.

There is many comments sent by coveralls on each commit and comments are sent before the test matrix is complete.
You can notice that reports are not complete and the build is.

See by exemple:
- partial report: https://coveralls.io/builds/2368083
- complete build with success: https://travis-ci.org/MongoEngine/mongoengine/builds/59021554

**Comment by Ward9250** [comment]
I also have an issue with multiple coveralls comments on PR's with Travis CI, here is my travis configuration.

```
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly  
notifications:
  email: false
# sudo: false
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y ncbi-blast+;
    elif [ `uname` = "Darwin" ]; then
      brew tap homebrew/science;
      brew update;
      brew install blast;
    fi
before_script:
  - export PATH=$HOME/.local/bin:$PATH
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Bio"); Pkg.test("Bio"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("Bio")); Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl"); include(joinpath("docs", "make.jl"))'
```

**Comment by gravyboat** [comment]
We're encountering this over here as well: https://github.com/streamlink/streamlink/pull/54 I know this issue is a bit old, but I don't see a resolution and it's quite annoying.

**Comment by simlu** [comment]
I'd also be interested in an improvement here. Semantic-release seems to have solved this nicely. Maybe take a look there?
