### ISSUE TITLE
Can't enable coverall for chromium/web-page-replay repo

### ISSUE THREAD

**Issue by nedn** [lemurheavy/coveralls-public#492]
Hi, I have the admin access of https://github.com/chromium/web-page-replay, and I would want to add that repo to coverall. However, when I click Add repo (https://coveralls.io/repos/new), I can't find it.

![screenshot from 2015-04-09 08 44 58](https://cloud.githubusercontent.com/assets/911877/7070593/d69a93a6-de94-11e4-9a0b-efd3eeea78db.png)

**Comment by nickmerwin** [comment]
Hi @nedn, it doesn't look like your membership of the Chromium org is public:
https://github.com/chromium

That means Coveralls can't see it either; you'll need to publicize it or upgrade your OAuth credentials to include private:

https://coveralls.io/refresh?private=true

Thanks!

**Comment by nedn** [comment]
Thanks Nick!
