### ISSUE TITLE
Coverage report not submit

### ISSUE THREAD

**Issue by vsoch** [lemurheavy/coveralls-public#493]
I apologize in advance for the noobie question!

It looks like my report is successfully submit:
- [https://travis-ci.org/vsoch/pybraincompare/builds/57930218](https://travis-ci.org/vsoch/pybraincompare/builds/57930218)

But there is no data or files, and I'm not sure what I am doing wrong:
- [https://coveralls.io/jobs/5369622](https://coveralls.io/jobs/5369622)

I am using the nosetests for testing, so my submission command looks like this:

```
 nosetests --verbosity=3 --with-doctest --with-coverage --cover-package=pybraincompare $TESTDIR/test_correlation.py $TESTDIR/test_masking.py
```

and it looks like it runs successfully in travis, but possibly the result is not sent? I do my testing in $tmp, and is it an issue of needing to copy some file from $tmp to where the coveralls command is issued from?

**Comment by nickmerwin** [comment]
Hi @vsoch it looks like no coverage data is coming along for your source files. Could you check the configuration of your Coveralls integration library or try a different one?

Thanks!

**Comment by vsoch** [comment]
Will do! Is there one you would recommend over the others?
