### ISSUE TITLE
PR status not showing up all checks

### ISSUE THREAD

**Issue by simov** [lemurheavy/coveralls-public#494]
I created a test PR here https://github.com/simov/request/pull/1 where the _Show all checks_ button is available, so I can click on it and see all of the checks, including the coverage report.

Then I created the same PR but in request https://github.com/request/request/pull/1541 - here I can see only the default _Details_ button which points to the travis build.

I can confirm that the data is sent correctly to coveralls.io https://coveralls.io/builds/2316175

The repo settings seems to be set correctly to use the Status API, but it seems to be not reporting back.

**Comment by simov** [comment]
@nickmerwin could that be related to the fact that I'm not the one who initially added request to coveralls? Currently I'm an owner of the request org and my coveralls access token have granted access to the status API (obviously) but that doesn't work for the request repo only. 

I can see the repo settings to the left here https://coveralls.io/r/request/request I'm not seeing only the delete repository section to the right, and that might have something to do with the fact that the repository was not added initially by me?

**Comment by nickmerwin** [comment]
Hi @simov sorry for the delay! Yes, the repo is owned by @nylen, so the status API call is made on his behalf.

@nylen if you're listening could you logout and back into Coveralls? It seems your OAuth credential have rolled.

Thank you!

**Comment by simov** [comment]
Thanks for the response @nickmerwin is there any chance to transfer the ownership to me? Because certainly I'm the one responsible for the coveralls integration but I didn't had the ownership rights back then. And @nylen is nowhere to be seen lately.

**Comment by nylen** [comment]
@nickmerwin I've re-authorized `request` on Coveralls.  Let me know if that fixes the issue.  And, :+1: for transferring ownership to @simov.

**Comment by simov** [comment]
Doesn't seems to be working. At first I got some [weird git error](https://github.com/cainus/node-coveralls/issues/80) then I force pushed one commit and everything passed again, plus the coveralls report is being created, but without status messages. I'm no longer seeing the _Show all checks_ button even for my [own repo](https://github.com/simov/request/pull/1)

**Comment by simov** [comment]
@nickmerwin this is our latest [PR on coveralls](https://coveralls.io/builds/2399529) still no luck with the status API.

**Comment by karyon** [comment]
We do have the same problem [in this repo](https://github.com/fsr-itse/EvaP/), here's a [pull request](https://github.com/fsr-itse/EvaP/pull/785) with which we tested this. Comments from coveralls are working, the status API is not. Like the original reporter, coveralls support for the repo was added by someone else (@cyroxx) who does not have access to the repository anymore, current admin is @janno42.

@cyroxx: hi :)

**Comment by karyon** [comment]
fwiw https://github.com/lemurheavy/coveralls-public/issues/526 seems to be the same issue.

**Comment by karyon** [comment]
deleting the repository from coveralls and re-adding it fixed the issue.
