### ISSUE TITLE
Transitioning repo from private to public

### ISSUE THREAD

**Issue by lbergelson** [lemurheavy/coveralls-public#497]
We recently transitioned our repo, https://github.com/broadinstitute/hellbender from being a private repo to a public one.  Coveralls is still making comments on our pull requests, but the badge isn't working anymore.  If I click on the badge I get a ["halt, access denied page"](https://coveralls.io/r/broadinstitute/hellbender).   Is there something I can do to fix this?  It's ok if we lose our coverage history.

**Comment by nickmerwin** [comment]
Hi @lbergelson ok that repo is public on Coveralls now.

Thank you!

**Comment by lbergelson** [comment]
Thanks!
