### ISSUE TITLE
Adding more unit tests causes Coveralls coverage to *decrease*

### ISSUE THREAD

**Issue by mgoelzer** [lemurheavy/coveralls-public#499]
Docker Swarm (github.com/docker/swarm) is using Coveralls to compute coverage.

Recently this pull request was submitted:  https://github.com/docker/swarm/pull/614.  

That PR adds two unit test functions that add test coverage to previously uncovered lines.  It adds no other code besides these test functions.  Therefore, I would expect Coveralls coverage to increase.

Insteasd, Coveralls reported "Coverage decreased (-13.66%) to 39.6%" as you can see [on the PR page](https://github.com/docker/swarm/pull/614):

![coveralls1-coveragedecreased](https://cloud.githubusercontent.com/assets/225111/7150411/8101f8f0-e2cf-11e4-9f36-57fe22b19244.png)

How could overall coverage decrease when PR contains no new code except unit tests which increase test coverage?

**Comment by nickmerwin** [comment]
Hi @mgoelzer it looks like the pull request base build failed on travis (https://coveralls.io/builds/2316772) but was counted as 53.26% covered. That's what caused a 13% reduction.
