### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by shedd** [lemurheavy/coveralls-public#504]
Seeing a number of timeouts when my CI builds submit coverage data to you:

```
[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::GatewayTimeout
504 Gateway Timeout
```

With this response:

```
<!DOCTYPE html>
<html lang="en">

  <head>
<meta http-equiv="refresh" content="0">

<meta http-equiv="set-cookie" content="cf_use_ob=443; expires=Sat, 25-Apr-15 19:29:01 GMT; path=/">

<meta http-equiv="set-cookie" content="cf_ob_info=504:1dcc72d3982702ba:IAD; expires=Sat, 25-Apr-15 19:29:01 GMT; path=/">


    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>
    [snip]
  </head>

  <body id="errorPage">
    <div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 1dcc72d3982702ba</li>
    <li>Your IP address: [snip]</li>
    <li>Error reference number: 504</li>
    <li>CloudFlare Location: Ashburn</li>
  </ul>
</div>

    <div class="footerWrap">
      <div class="footerPad">
        <div class="top-nav">
          <div class="container">
            <a href="https://coveralls.io/" class="logo">Coveralls</a>
            <ul>
              <li><a href="https://coveralls.io/"><i class="icon-home"></i> Home</a></li>
            </ul>
            <ul class="navRight">
              <li><a href="/info/features"><i class="icon-star"></i> FEATURES</a></li>
              <li>
                <a href="/pricing" onclick="_gaq.push([&#x27;_trackEvent&#x27;, &#x27;headerPricing&#x27;, &#x27;indexClick&#x27;]);">
                  <i class="icon-plus-sign"></i> PRIVATE REPOS
                </a>
              </li>
              <li><a href="https://coveralls.io/docs"><i class="icon-question-sign"></i> Docs</a></li>
              <li><a href="http://blog.coveralls.io/" target="_blank"><i class="icon-comment"></i> Blog</a></li>
              <li>
                <a href="/authorize/github" data-no-turbolink="true"><i class="icon-user"></i> Sign in with GitHub</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="container site-wrapper">
          <h1>
          [snip]
            Five Zero Zero
          </h1>
          <div class="alert alert-error">
            <h3>It's Gone Pear Shaped</h3>
            <p>There has been a hiccup, the revolution will continue after we stamp out the refusniks. You could also try refreshing or returning to the home page.</p>
          </div>
          <div class="twitter-feed">
            <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/CoverallsApp" data-widget-id="380835385749667840">Tweets by @CoverallsApp</a>
            <script>
//<![CDATA[
!function(t,e,r){var n,s=t.getElementsByTagName(e)[0],i=/^http:/.test(t.location)?"http":"https";t.getElementById(r)||(n=t.createElement(e),n.id=r,n.src=i+"://platform.twitter.com/widgets.js",s.parentNode.insertBefore(n,s))}(document,"script","twitter-wjs");
//]]>
</script>
          </div>
        </div>

      </div>
    </div>

    <footer class="footer">
      <div class="pad">
        <a href="/info/legal">Legal &amp; Privacy</a>
        &middot;
        <a href="https://github.com/lemurheavy/coveralls-public/issues">Open an Issue</a>
        &middot;
        <a href="mailto:coveralls@lemurheavy.com">FEEDBACK or THOUGHTS</a>
        &middot;
        <a href="http://blog.coveralls.io/" target="_blank">BLOG</a>
        <p>&copy; 2013 <a href="http://lemurheavy.com">Lemur Heavy Industries</a></p>
      </div>
    </footer>
  </body>
</html>
```

**Comment by composer22** [comment]
Im getting the same thing.  Really flaky when posting results from Travis.  

<body id="errorPage">
    <div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 1dcfbf7445400f39</li>
    <li>Your IP address: 54.172.141.90</li>
    <li>Error reference number: 504</li>
    <li>CloudFlare Location: Ashburn</li>
  </ul>
</div>

**Comment by stevenbrichards** [comment]
I am also getting this

**Comment by aivus** [comment]
Getting this in tests too:
https://travis-ci.org/s0ph1e/node-website-scraper/jobs/59368954
https://travis-ci.org/s0ph1e/node-css-url-parser/jobs/60011110

**Comment by jakirkham** [comment]
Same problem. Also, seeing in Travis. More details at the issue opened here ( https://github.com/z4r/python-coveralls/issues/32 ).

**Comment by composer22** [comment]
Same here:

```
Bad response status from coveralls: 504 - <!DOCTYPE html>
<html lang="en">
  <head>
<meta http-equiv="refresh" content="0">
<meta http-equiv="set-cookie" content="cf_use_ob=443; expires=Mon, 27-Apr-15 17:29:27 GMT; path=/">
<meta http-equiv="set-cookie" content="cf_ob_info=504:1ddc3e7315d1020d:IAD; expires=Mon, 27-Apr-15 17:29:27 GMT; path=/">
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>
```

Then a bunch of graphic font shit...and then:
```
<body id="errorPage">
    <div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 1ddc3e7315d1020d</li>
    <li>Your IP address: 54.172.141.90</li>
    <li>Error reference number: 504</li>
    <li>CloudFlare Location: Ashburn</li>
  </ul>
</div>
```
and then some more nothingness...

**Comment by stevenbrichards** [comment]
Perfect issue number for this by the way... 
I've had this sporadically on different jobs, same as above.

**Comment by sochka** [comment]
This just drives my crazy, all travis builds fail because of this.

**Comment by jakirkham** [comment]
@stevenbrichards Thinking the same thing.

**Comment by gogoLuby** [comment]
+1

**Comment by sochka** [comment]
For those who use travis and builds fail because of this issue - move your coveralls submission to `- after_succes` section

**Comment by CID-DAVE** [comment]
even after moving to after_success I am still getting this error.

**Comment by arjenvanderende** [comment]
I'm having the same issue for a Java project. Coveralls submission fails with a `504 Gateway Timeout` and the following response:
> Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

The error message above leads me to believe that the JSON being submitted is invalid. It's generated with a [coveralls Maven plugin](https://github.com/trautonen/coveralls-maven-plugin). I've validated the generated `coveralls.json` with several validators and they all report that the JSON is valid. Not sure how to debug this any further. :disappointed:

**Comment by arjenvanderende** [comment]
Nice, our code coverage is available now in coveralls. Submission works fine now and I don't get a gateway timeout anymore. Even yesterdays submissions came through. :smile:

**Comment by davidbarratt** [comment]
I'm getting this as well:
https://travis-ci.org/phototech/sailvenice/builds/152136061#L819-L820
Also, I have it in the `after_success` section:
https://github.com/phototech/sailvenice/blob/develop/.travis.yml#L17-L18

**Comment by cdgriffith** [comment]
Looks like it's rearing it's head again, I am also experiencing it:
https://travis-ci.org/cdgriffith/Reusables/jobs/152149404#L460

**Comment by ShivamSarodia** [comment]
I'm also experiencing the same issue.
https://travis-ci.org/ShivamSarodia/ShivyC/builds/152163524#L196

**Comment by GandaG** [comment]
[Same here :/](https://travis-ci.org/GandaG/fomod-designer/builds/152238827#L560)

**Comment by groovecoder** [comment]
+1 getting this a lot today.

**Comment by Supernomad** [comment]
Just ran into [this](https://travis-ci.org/Supernomad/quantum/builds/152278065) as well

**Comment by mcqueary** [comment]
+1. Busy weekend I guess.

**Comment by johnyf** [comment]
Same problem here: https://travis-ci.org/johnyf/omega/builds/152316805

**Comment by c24w** [comment]
Recurring issue for me in [Travis](https://travis-ci.org/c24w/try-catch-finally.js/jobs/152352993#L777-L780).

Also, I'm pleased this is issue #504.

**Comment by nicolaasuni** [comment]
+1
https://travis-ci.org/miracl/maas-sdk-python/jobs/152363127

**Comment by mattbishop** [comment]
I had trouble yesterday with this error on a node 4 job of a build. Other jobs in same build worked fine. You can see the failed job timed out: https://travis-ci.org/prayerslayer/js.spec/builds/211594375

**Comment by Expert-Newbie** [comment]
Hello, 


For users of "**Red Hat Openstack Platform**" who have error as "proxy horizon has no available server" or "504 gateway",  I found a solution in the deep of the web so I think it is a good thing to post here ;) 

**The solution is simple :** 

1. Edit the file of horizon on the controller :  `vi /etc/httpd/conf.d/10-horizon_vhost.conf`

2. Add this line before  <\/VirtualHost> : `WSGIApplicationGroup %{GLOBAL}`

3. Restart the httpd service: ` systemctl restart httpd`

4. Restart the haproxy service : `systemctl restart haproxy.service`


And that's it !
