### ISSUE TITLE
Can't see repos to add

### ISSUE THREAD

**Issue by dueyfinster** [lemurheavy/coveralls-public#505]
Just stays with this animation, looping... forever...
![ss](https://cloud.githubusercontent.com/assets/166151/7371401/98e2ec10-edb8-11e4-86ea-785244b59032.png)

**Comment by jmorford** [comment]
I have the same issue

**Comment by cid-scardinale** [comment]
Yep, same thing on my end as well.

**Comment by ayush** [comment]
Me too.

**Comment by jwaldrip** [comment]
Me too. Can this be fixed. I just paid for my subscription and would love to use the service!

**Comment by edmorley** [comment]
I'm seeing this too, after pressing "sync github repos", when I couldn't see my org ("mozilla") in the list.

**Comment by FichteFoll** [comment]
Had the same problem.

As mentioned in https://github.com/lemurheavy/coveralls-public/issues/597, logging off and on again made the synced data available.
