### ISSUE TITLE
"Coverage pending from Coveralls.io" in Github

### ISSUE THREAD

**Issue by ahocevar** [lemurheavy/coveralls-public#508]
I noticed that since about 12 hours, coverage tests started from Travis do not seem to be run properly and are pending even after many hours. A few example pull requests for this:

https://github.com/KaiVolland/geoext3/pull/9
https://github.com/openlayers/ol3/pull/3639

**Comment by uLow** [comment]
Same problem. 
build/logs/coveralls-upload.json
File size: 19.69 kB
Submitting to https://coveralls.io/api/v1/jobs
Finish submitting. status: 200 OK
Accepted Job #148.1

But still no coverage info.

**Comment by ahocevar** [comment]
Apparently this has been fixed in the meantime.
