### ISSUE TITLE
Coveralls not picking up coverage data from travis-ci

### ISSUE THREAD

**Issue by bahrom-matyakubov** [lemurheavy/coveralls-public#509]
Here are the outputs of the two travis builds:
https://travis-ci.org/bahrom-matyakubov/PyParser/jobs/60467069
https://travis-ci.org/bahrom-matyakubov/PyParser/jobs/60484200

Looks like the table was present in both, however the coverage was only reported on the first one:
https://coveralls.io/builds/2446182
https://coveralls.io/builds/2447337

Also, subsequent build has the same issue:
https://travis-ci.org/bahrom-matyakubov/PyParser/jobs/60547711
https://coveralls.io/builds/2449320

Could someone take a look at why coverage stopped updating please?
Thanks!

**Comment by bahrom-matyakubov** [comment]
Also I kept getting 503 service unavailable error a few hours ago when trying to access the coveralls website

**Comment by CJ-Wright** [comment]
I am having this issue, too.  I have stopped getting coverage updates, although Travis keeps sending them.

**Comment by arthurlockman** [comment]
Same here for https://github.com/arthurlockman/sixeswild. Messages appear to send from travis-ci ok, but nothing shows in coveralls builds: https://coveralls.io/jobs/5716992.

**Comment by Matt3o12** [comment]
Drone builds aren't picked up, either ([drone.io](https://drone.io/github.com/Matt3o12/gowork/11), [coveralls.io](https://coveralls.io/jobs/5718430))

**Comment by Matt3o12** [comment]
It works for me now.

**Comment by bahrom-matyakubov** [comment]
Works for me too, thanks!

**Comment by emmett9001** [comment]
This issue appears to still be affecting at least [pykafka](https://coveralls.io/github/Parsely/pykafka)'s coveralls page.
