### ISSUE TITLE
Branches can't be synchronized

### ISSUE THREAD

**Issue by Matt3o12** [lemurheavy/coveralls-public#510]
Probably related to #509 and an issue which [prevented all github repos to be `sync`ed](https://twitter.com/Skierkowski/status/593463311645151232).

I can't refresh (or even load) the list of all github brachnes. When I hit "synch branches", it loads for a few seconds but nothing happens. I currently have 3 branches.  

![screen shot 2015-04-29 at 10 00 42 pm](https://cloud.githubusercontent.com/assets/1218474/7400150/11a076f6-eebb-11e4-8884-824e5f88489d.png)

This is a brand new repo which is also effected by #509 .

**Comment by Matt3o12** [comment]
Seems to be fixed now (as the latest builds were appearing).

**Comment by emmett9001** [comment]
This issue appears to still be affecting at least [pykafka](https://coveralls.io/github/Parsely/pykafka)'s coveralls page.
