### ISSUE TITLE
My Repo thinks there are no builds

### ISSUE THREAD

**Issue by macskay** [lemurheavy/coveralls-public#514]
I tried adding my repo and it keeps telling me to add .travis.yml, when Travis-CI is already running for some time. It seems to not get the updates of builds

**Comment by nickmerwin** [comment]
Hi @mkli90, the problem is likely that your builds are being run in parallel on your CI but you haven't set up a post-build webhook set up to set them as complete:  https://coveralls.zendesk.com/hc/en-us/articles/203484329

What repo is it?

**Comment by mkli90** [comment]
It's tekmate. My taz is working well however. :)

Nick Merwin <notifications@github.com> schrieb am Di., 5. Mai 2015 um
18:57 Uhr:

**Comment by mkli90** [comment]
I've also setup a webhook, but still nothing

**Comment by nickmerwin** [comment]
Hi @mkli90, could you check again now? What's the name of your repo?

Thanks.

**Comment by mkli90** [comment]
The name of the repo is mkli90/tekmate (https://coveralls.io/r/mkli90/tekmate) Still nothing

**Comment by nickmerwin** [comment]
@mkli90 ok could you trigger another build now?

**Comment by mkli90** [comment]
sure one second

**Comment by mkli90** [comment]
done branch "enhancement/31-make-the-player-appear-on-the-screen"

**Comment by mkli90** [comment]
Request URL: https://coveralls.io/webhook?repo_token=<my repo token deleted for security>
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/8a76be2
X-GitHub-Delivery: 845ded80-f41b-11e4-96f1-a56a52021d80
X-GitHub-Event: push

**Comment by nickmerwin** [comment]
@mkli90 it doesn't look like your "coveralls" after_success hook is working properly on Travis:
https://travis-ci.org/mkli90/tekmate
