### ISSUE TITLE
Coveralls command-line tool can't find repos

### ISSUE THREAD

**Issue by tesh11** [lemurheavy/coveralls-public#515]
Hello,

As of around noon CDT, our builds all failed trying to upload coverage data. We haven't changed anything and they continue to fail. The errors we're getting:
```
INFO:sh.command:<Command '/bin/pwd' call_args {'bg': False, 'timeo...(476 more)>: starting process
INFO:sh.command:<Command '/usr/bin/git --no-pa...(53 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
INFO:sh.command:<Command '/usr/bin/git rev-par...(20 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
INFO:sh.command:<Command '/usr/bin/git remote ...(2 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): coveralls.io
INFO:coveralls:422
INFO:coveralls:{"message":"Couldn't find a repository matching this job.","error":true}
```
Is this a known issue? ETA for a fix?

Thank you,
Meetesh Karia
VP of Engineering
The Zebra

**Comment by nickmerwin** [comment]
hi @tesh11 could you link me to your repository?

Thanks.

**Comment by tesh11** [comment]
@nickmerwin They're all private repos so the links wouldn't work. But, they're failing for all of our repos. Anything else I can do to help? Thanks!

**Comment by joshuarubin** [comment]
+1

**Comment by bkon** [comment]
Same for us; re-generating repository token did not solve the issue.
We're using it with our company private repository https://github.com/range-me/range-me

**Comment by zhevron** [comment]
+1. I've got several public projects also failing with this error now.

**Comment by nickmerwin** [comment]
Hi all we just fixed an issue that should mitigate the 422 issue. Please try again now, thank you!

**Comment by zhevron** [comment]
@nickmerwin Confirmed working for my projects. Thanks for the fix.

**Comment by tesh11** [comment]
@nickmerwin The fix works for us as well. Thank you!
