### ISSUE TITLE
Can't add repo

### ISSUE THREAD

**Issue by drabiter** [lemurheavy/coveralls-public#517]
![screenshot from 2015-05-06 12 12 52](https://cloud.githubusercontent.com/assets/2654586/7487807/43fbbc22-f3e9-11e4-98a7-09cd8744705c.png)

The loading indicator keep going and never ends after click the ON switch.

**Comment by nickmerwin** [comment]
Hi @drabiter could you log out and log back in? It looks like your Github OAuth token may have rolled.

Thanks!

**Comment by drabiter** [comment]
@nickmerwin Have tried that. I also revoke the github access. Didn't work. Here's what happened when i switched the button.

![screenshot from 2015-05-07 09 37 27](https://cloud.githubusercontent.com/assets/2654586/7507633/d28835de-f49c-11e4-8252-dcaf38b4c78c.png)

**Comment by drabiter** [comment]
@nickmerwin Here is what I got as `repos.json`,
```
{"base":["Couldn't determine GitHub settings."]}
```
Is it because my organization? The organization is restricted and not under my control.

**Comment by ktsashes** [comment]
I actually get the same thing, looks to be at least somewhat unrelated though. The post request to repos.json is returning a 500 error

**Comment by ericelsken** [comment]
I am having the same problem. I cannot add an organization repo, it stays stuck at the loading gif after toggling to add repo.

Any updates or fixes?

**Comment by hugovk** [comment]
Same thing here, also seeing the 500 error from repos.json:

```
POST https://coveralls.io/repos.json 500 (Internal Server Error)
send @ application-492688d39a22faf2b9522f9e2a4d05cd.js:26
ae.extend.ajax @ application-492688d39a22faf2b9522f9e2a4d05cd.js:26
ae.(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:26
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:77
ae.event.dispatch @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
m.handle @ application-492688d39a22faf2b9522f9e2a4d05cd.js:24
ae.event.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
ae.extend.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.ae.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.extend.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:64
ae.event.dispatch @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
m.handle @ application-492688d39a22faf2b9522f9e2a4d05cd.js:24
ae.event.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
ae.extend.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.ae.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.extend.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:64
ae.event.dispatch @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
m.handle @ application-492688d39a22faf2b9522f9e2a4d05cd.js:24
ae.event.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
ae.extend.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.ae.each @ application-492688d39a22faf2b9522f9e2a4d05cd.js:14
ae.fn.extend.trigger @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
d @ application-492688d39a22faf2b9522f9e2a4d05cd.js:64
(anonymous function) @ application-492688d39a22faf2b9522f9e2a4d05cd.js:64
ae.event.dispatch @ application-492688d39a22faf2b9522f9e2a4d05cd.js:25
m.handle @ application-492688d39a22faf2b9522f9e2a4d05cd.js:24
```

**Comment by oryband** [comment]
happens to me as well with github.com/oryband/go-web-mapreduce

**Comment by hugovk** [comment]
Well, seems to be working now.

**Comment by oryband** [comment]
yup, seems to work now

**Comment by spiralx** [comment]
I'm getting this error now for my repository https://github.com/spiralx/jshint-summary.

Actually, it's the same on every one of my repos that I've tried to add.

**Comment by nickmerwin** [comment]
@spiralx we just deployed better OAuth token expiration handling when adding repos. Could you try again now please?

Thanks!

**Comment by spiralx** [comment]
That seems to have worked - it says my OAuth token had expired, then reloaded the page and I've been able to add the repo - my repos were showing twice in the list though, once with the GitHub button on the right, once without!
