### ISSUE TITLE
Bad response: 422

### ISSUE THREAD

**Issue by sberryman** [lemurheavy/coveralls-public#519]
Seeing this error when trying to submit coverage data:
`Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`

Please see issue cainus/node-coveralls#93

This happens for all of my projects and is a new error, I haven't changed any code (just tried re-running a build that was previously working).

**Comment by designfrontier** [comment]
I am getting the same thing

**Comment by nickmerwin** [comment]
Hi guys we fixed an issue that should mitigate this. Please try again now, thank you!

**Comment by sberryman** [comment]
Confirmed that this issue is fixed, still seeing weird issues on builds though. The custom script for deployment is not executing properly. It looks like it is running an older version of the script to be honest.

I added:
`echo "testing 123" > ./test.txt" and didn't see the file from a debug ssh session.

**Comment by sberryman** [comment]
To be clear, if I manually run my custom script from the debug shell exactly as it is listed on your website it works fine.

**Comment by designfrontier** [comment]
working for me now. Thanks

**Comment by tomekwi** [comment]
I’m having the same issue. See <https://travis-ci.org/tomekwi/isomorphic-ensure/jobs/65559955>.

Maybe I should rather post this to [caisus/node-coveralls](/caisus/node-coveralls)?

**Comment by matee911** [comment]
@nickmerwin I'm still getting 422 error. See https://travis-ci.org/matee911/GrimReaper/jobs/80154049

**Comment by antoinehage** [comment]
all of a sudden started getting this and tried all the possible solutions and no luck :(

travis_time:start:0bcb86ed
[0K$ $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
travis_time:end:0bcb86ed:start=1551700526157886345,finish=1551700528717789475,duration=2559903130
[0K[31;1mThe command "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro" exited with 1.[0m

**Comment by nickmerwin** [comment]
@antoinehage can you email us the name of the repo in question to support@coveralls.io please? Since it's a private one we can take it from there.
