### ISSUE TITLE
Support gzip compression

### ISSUE THREAD

**Issue by satooshi** [lemurheavy/coveralls-public#52]
In order to reduce submitting time of json_file to Coveralls API, it would be nice if gzip or other compression format could be supported.

I got 503 error sometimes during submitting 7 MB json_file. This error was occurred while I tried to use Coveralls for Zend Framework 2 (also please take a look at issue #51).

**Comment by marco-c** [comment]
This makes a lot of sense, I have a 32 MB JSON, which gzipped is 2 MB.

**Comment by nickmerwin** [comment]
Hey @satooshi and @marco-c, we've just deployed support for this!

The integration libraries will need to be updated also, but if you'd like to try it in the meantime the request should have a `gzip/json` content-type.

Let me know how it goes, thanks!

**Comment by satooshi** [comment]
Thanks!

**Comment by marco-c** [comment]
I was testing this, but I couldn't get it to work:
```
POST /api/v1/jobs HTTP/1.1
Host: coveralls.io
User-Agent: python-requests/2.13.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 439
Content-Type: multipart/form-data; boundary=40f0a032149944d8a1cccbdfb997b509

--40f0a032149944d8a1cccbdfb997b509
Content-Disposition: form-data; name="json_file"; filename="json_file"
Content-Type: gzip/json

\x1f\x8b\x08\x08\xe5\x0f\xf0X\x00\x03json_file\x00\x85P\xd1j\xc3 \x14}\xcfW\x88\xcfa\x8b1Y\xeb^\xf7\x0b{\x08\x94\x124^\x9d\xad\x89EM7(\xfd\xf7i\x96Q:\x06\x05\xbd\x1c\xce9\xf7\x1c\xf1R \x84\x83\x9b\xfd\x00\xbd2\x16\x02~E\xbb\xc4!tYfR\'>Bb1|\xf1\xf1d\xe1\xc9\x0b\\\xfej\xeb\xa64\x1aB\xcc&\x1e\xa4\xca\x97\xd4\xb4\xe1a\x81\t\xb5\xb7\x8d\xc1\x9d\xc1s\x9d\x13w\xd3lm\x89H\x892\xd8/\x8ek\xf9\x7f\xb95\xe29~\xba\xc7\xe5?\xc5R\xa5\xa3uPZ\xb2\xa6\xa6\x0f\xea\xab\xbb\x17\xa4\xb9\xcf~\xec\xe1\xe4\xfa\xe8\x8e0\xe5\xf0\xae\xeb\x96\x18\x1c\xc0\x9fM\xea=8\xd1O\xf3(\xc0g\x99\xdc\x8b7\xa1^\x95\xc1\x8d\xa3\x89}\xf8\xe0\x99e\r\xa3|\x03\\\xb4D\x01m\x15c/dK\xb9 \xdb\n6\xcdP)\xd9\nJ\t\xfb\x93\xba\xfe\xc6;\x0f\xc77;\x87\x98*\x8ak\xf1\rb]\xd8\x0c\xc5\x01\x00\x00
--40f0a032149944d8a1cccbdfb997b509--
```

The reply was 422 with `{'url': '', 'error': True, 'message': 'JSON file not found or failed to parse.'}`.

**Comment by nickmerwin** [comment]
@marco-c could you try with the data in a `json` parameter instead of using the `json_file` multipart form-data param?

**Comment by marco-c** [comment]
> Edit: we've deployed an update for this; you can try once more with your current request structure.

Thanks, it appears to work now (at least with the basic test payload I'm using)! I will test again tomorrow with a proper payload.

**Comment by nickmerwin** [comment]
@marco-c great! Will stand by for that.

**Comment by marco-c** [comment]
It worked flawlessly, thanks!
