### ISSUE TITLE
No PR comments

### ISSUE THREAD

**Issue by RyanCopley** [lemurheavy/coveralls-public#520]
https://travis-ci.org/BlockSync/BlockSync/builds/61559172

https://coveralls.io/r/BlockSync/BlockSync

:octocat: https://github.com/BlockSync/BlockSync/pull/5

Travis built and it posted the coverage to Coveralls successfully, and the PR information is in coveralls, but I do not see a comment telling me if the code coverage changed. How do I fix this?

Thanks

**Comment by RyanCopley** [comment]
![screen shot 2015-05-06 at 10 44 42 pm](https://cloud.githubusercontent.com/assets/819591/7507675/8ca7b554-f441-11e4-8b7b-df7bd016e313.png)

**Comment by nickmerwin** [comment]
Something seems to be up with the Github API here; it's returning a 404 on trying to post the comment.

Try this, with your API key:
```bash
curl -XPOST --data '{"body": "test"}' https://api.github.com/repos/BlockSync/BlockSync/issues/5/comments?access_token=...
```

It should create the comment but instead returns:
```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

**Comment by RyanCopley** [comment]
I bet I know why... I transferred the repo from my account to BlockSync

**Comment by RyanCopley** [comment]
actually, the API is returning this for me:

```
{
  "url": "https://api.github.com/repos/BlockSync/BlockSync/issues/comments/100760268",
  "html_url": "https://github.com/BlockSync/BlockSync/pull/5#issuecomment-100760268",
  "issue_url": "https://api.github.com/repos/BlockSync/BlockSync/issues/5",
  "id": 100760268,
  "user": {
    "login": "RyanCopley",
    "id": 819591,
    "avatar_url": "https://avatars.githubusercontent.com/u/819591?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RyanCopley",
    "html_url": "https://github.com/RyanCopley",
    "followers_url": "https://api.github.com/users/RyanCopley/followers",
    "following_url": "https://api.github.com/users/RyanCopley/following{/other_user}",
    "gists_url": "https://api.github.com/users/RyanCopley/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RyanCopley/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RyanCopley/subscriptions",
    "organizations_url": "https://api.github.com/users/RyanCopley/orgs",
    "repos_url": "https://api.github.com/users/RyanCopley/repos",
    "events_url": "https://api.github.com/users/RyanCopley/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RyanCopley/received_events",
    "type": "User",
    "site_admin": false
  },
  "created_at": "2015-05-11T04:24:18Z",
  "updated_at": "2015-05-11T04:24:18Z",
  "body": "test"
}
```

**Comment by RyanCopley** [comment]
and it's posting comments :/

**Comment by RyanCopley** [comment]
I asked GitHub to look into this...

**Comment by kruton** [comment]
I have the same issue with a transferred repo; did anything come from your inquiry to GitHub?

**Comment by j0k3r** [comment]
Same issue here after transferring a repo from an account to an organisation.
Any news ?

**Comment by mkroetzsch** [comment]
FWIW, we are seeing similar symptoms on our project, Wikidata Toolkit. This public project has not been transferred or otherwise changed its coveralls/Travis configuration in the past year. The coveralls comments on PRs just stopped working recently. Coveralls has all relevant coverage results on its pages, including coverage for merging PRs into master, and the configuration is set to enable "leave comments" and "use status api". The only change I noticed when logging in to Travis and Coveralls recently was that it updated its github permissions.

**Comment by nickmerwin** [comment]
hi @mkroetzsch I checked your account and your Github token has rolled -- could you log out and back in? PR statuses should be posted correctly for your repos after that.

@j0k3r we're working on a repo location sync'ing function right now.

I'm going to close this issue for now, thanks!

**Comment by fieldju** [comment]
Hello @nickmerwin , it's 2018, and I just had a repo transferred from a user to an org and comments on PRs are still not working.

This PR should have a comment: https://github.com/yaorg/node-measured/pull/36

Did ```@j0k3r we're working on a repo location sync'ing function right now.``` ever become a thing?

Cheers,

@fieldju

**Comment by fieldju** [comment]
Hrm, a comment came in on the PR, must have just been delayed.
