### ISSUE TITLE
Why do Coveralls request *write* permissions for GitHub account?

### ISSUE THREAD

**Issue by HenrikBengtsson** [lemurheavy/coveralls-public#521]
What's the reason Coveralls Pro request **write** permissions to my GitHub account?  It appears to be a recent update - I cannot recall seeing it before.

I'm using Coveralls "Open Source", and I don't understand the reason why write permission is needed, especially since all I think is used is an HTTP POST to coveralls.io.  What is the need to write/update my repositories etc?  It seems as if all the information needed should be available already (when it comes to public/open-source repositories).

Some references related to this issue:
* [GitHub's note](https://help.github.com/articles/connecting-with-third-party-applications/#types-of-application-access-and-data) on the read+write permissions.
* Wercker CI also have this [issue](https://github.com/wercker/support/issues/20) which concerns several (unresolved as of May 11, 2015).
* Codecov.io responded to our concerns and now [asks only for read-only access for public repository](https://twitter.com/codecov/status/593419859431542784) (fixed Apr 29, 2015)

PS. Thanks for a great service.

**Comment by nickmerwin** [comment]
Hi @HenrikBengtsson, Coveralls detected that you have access to private repos based on your organization memberships, so that's why we prompted you for "repo" access. Unfortunately Github doesn't have a read-only OAuth scope for private repos.

You can revoke the private scope if you prefer, Coveralls can still use your public permissions alone.

Thanks!

**Comment by HenrikBengtsson** [comment]
Thanks for the prompt reply.  Interesting. So, if I understand you correctly, it's related to your GitHub account and not related to the type of Coveralls plan/account you have.

# Workaround: Revoke access
The following works to revoke access: (details for followers/future readers)
1. Go to GitHub account -> Application -> Authorized applications
2. There are two Coveralls related entries owned by @lemurheavy: `Coveralls` and `Coveralls Pro`.  It's the `Coveralls Pro` application/connection that needs/uses *Access private repositories*.
3. Click Revoke access for `Coveralls Pro`.

I can confirm that:
1. you can still access Coveralls.io, and
2. your Coveralls data is updated correctly (via HTTP POST from Travis CI).

# When 'Coveralls Pro' is added back
I noted that `Coveralls Pro` is forced back if:
1. you click 'REFRESH PRIVATE REPOS' that appears on top of https://coveralls.io/repos/new.  If clicked, then there is an endless "spinning wheel" on that page and nothing is updated.  It appears as the page stalled.
2. The above seems to trigger a flag on Coveralls, such that you cannot access Coveralls.io website without first approving `Coveralls Pro`, i.e. you get forwarded to GitHub Authorize application page for "Coveralls Pro by [at]lemurheavy would like permission to access your account [...]".
3. Then only option is to approve and then revoke access as above.  This is to trick Coveralls to unflag the account again.  After doing this, you can access Coveralls and all of your Coveralls pages again.

BTW, given this, I'm not sure if there is a way to sync repositories if you have revoked `Coveralls Pro`. Is there?

# Feature request
After the above troubleshooting, I believe I clicked 'REFRESH PRIVATE REPOS' in order to sync my  repositories.  Then nothing happened, I might have left and got surprised about the GitHub Application request when I got back a few days later.  If this is the connection/cause, would you mind making the addition of the `Coveralls Pro` app more clear, e.g. when you click on 'REFRESH PRIVATE REPOS' you'll see a dialog explaining that `Coveralls Pro` needs to be added yada yada?  I think that would be helpful to users.

**Comment by HenrikBengtsson** [comment]
Actually, it's seem that revoking the `Coveralls Pro` permissions causes the following:

> SOURCE NOT AVAILABLE
> The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

It's no longer possible to inspect the code coverage per line and file.

Example: https://coveralls.io/builds/2579876/source?filename=.%2Fsrc%2FpsortKM.c

Comment: The Coveralls badges and summary tables do indeed give coverage stats.

**Comment by clphillips** [comment]
Coveralls won't work if you have **ANY** private repos in any of your organizations *UNLESS* you approve the Coveralls Pro app. Even if you have no intention of using coveralls for the private repos.

That is so annoying.

**Comment by 153957** [comment]
Indeed, very annoying, just had this happen to me yesterday.
I did not accept the extra access that Coveralls Pro was asking for, and I did get the 'SOURCE NOT AVAILABLE' message, however, a day later it seems to be working fine again for my public repo.
