### ISSUE TITLE
Badge always "unkown" state and github reporting always "first build"

### ISSUE THREAD

**Issue by creack** [lemurheavy/coveralls-public#523]
Hello,

I have an issue with a private repo. The builds works fine, I can see the details on coveralls page, however:

1) The badge is always in "unkown" state, even the sample one on coveralls page.
2) The github reporting always pass and says "first build from master"

Regards,

**Comment by nickmerwin** [comment]
Hi @creack could you open a support ticket here with a link to your repo? https://coveralls.zendesk.com/hc/en-us/requests/new

Thank you!
