### ISSUE TITLE
Github status not working 

### ISSUE THREAD

**Issue by arschmitz** [lemurheavy/coveralls-public#526]
We are trying to use the new status api for PR coverage status but cant get anything to work. This is for jquery/jquery-mobile. Iv read other issues and tried everything in those none of the other things seem to apply. I'm the owner of the repo. I have logged in and out several times. Iv changed settings and pushed multiple times but all to no avail, I have yet to see a status.

**Comment by dougmoscrop** [comment]
Ditto here, have tried having an org owner login and activate the repo vs. myself, we see the build for a PR, but neither a comment nor status API update is provided. We are paying for pro.

**Comment by d3ming** [comment]
Was there eventually a resolution to this issue?  I've also had no luck getting it to work on some repos (but I have seen it work before on others)

**Comment by arschmitz** [comment]
@d3ming no as you can see there was never even a response to this issue
