### ISSUE TITLE
"DID NOT CHANGE" or "COVERAGE REMAINED THE SAME AT ?%"

### ISSUE THREAD

**Issue by steverobbins** [lemurheavy/coveralls-public#530]
[https://coveralls.io/r/steverobbins/magescan](https://coveralls.io/r/steverobbins/magescan)

This is what I'm seeing in my updates tab

![image](http://i.imgur.com/T2E0NZ9.png)

From the travis-ci builds you can see the coverage has changed, and obviously `?%` isn't a number
- Coverage: [62.93](https://travis-ci.org/steverobbins/magescan/jobs/63222839#L299)
- Coverage: [65.03](https://travis-ci.org/steverobbins/magescan/jobs/63232378#L297)
- Coverage: [63.15](https://travis-ci.org/steverobbins/magescan/jobs/63238806#L301)

**Comment by nylar** [comment]
I have also come across this: https://coveralls.io/builds/2602114. Only coverage report that has failed but was successful on [Travis](https://travis-ci.org/nylar/fora/builds/63232951#L395).

**Comment by joshma** [comment]
I'm seeing the same thing on our private repos, happens about 80% of the time.

**Comment by Ptidel** [comment]
Like joshma, same thing on our private repos. And github status is stuck with : 

 coverage/coveralls — Coverage pending from Coveralls.io

**Comment by hectorj** [comment]
Same thing here : https://coveralls.io/jobs/6314686 (Travis Job is there : https://travis-ci.org/hectorj/gesi/jobs/64787958)

**Comment by jbender** [comment]
:+1: Also seeing this issue on private repos, any update on this @eli @nickmerwin @anjin, disappointing to see so little activity on such a large issue

**Comment by mamaral** [comment]
Seeing this as well... Any updates?

**Comment by sanastasiou** [comment]
Same issue here. 

![image](https://cloud.githubusercontent.com/assets/2955627/7904580/186b8e48-0802-11e5-9401-d98f5369cad4.png)

Last two update had at least 5% increase but somehow it did not appear online.

**Comment by steverobbins** [comment]
After a few days they corrected themselves.  But I still think this issue should be addressed.

**Comment by mamaral** [comment]
Will confirm this took about 24 hours to actually update.

**Comment by elboletaire** [comment]
Same here

**Comment by htynkn** [comment]
Same issue.

For all PR,  `coverage/coveralls — Coverage pending from Coveralls.io`

**Comment by eran10** [comment]
same issue in our repo,
any new ?? what can cause that??
