### ISSUE TITLE
Commits are being shown with first line of body instead of commit message

### ISSUE THREAD

**Issue by joshma** [lemurheavy/coveralls-public#532]
Given a commit like
```
Main commit message

And this is the first line of the body
```

Coveralls is showing "And this is the first line of the body" as the commit message instead of "Main commit message". Using CircleCI + node-coveralls, if it helps.

**Comment by joshma** [comment]
I just wanted to bump this - we're a proud coveralls customer, but the fact that our repo consistently shows the least important part of the message makes the service much less usable. For the coveralls folks (hi @anjin), our repo in question is the one under the `benchling` org - you'll notice most changes just say `Summary:` The commit message looks like:

```
    Enable source maps for production JS builds

    Summary:
    Tweaks webpack config to enable source maps in production.
    [More metadata - we use Phabricator]
```

And instead of `Enable source maps for production JS builds` all the messages just say `Summary:`

<img width="145" alt="t2jrf" src="https://cloud.githubusercontent.com/assets/64739/8663477/2cfb12da-2980-11e5-8705-7976f929de72.png">

**Comment by nickmerwin** [comment]
@joshma I'm suspecting it's Circle's git version -- node-coveralls uses this command to get git info which is then passed to our API:

```bash
git cat-file -p HEAD
```
https://github.com/nickmerwin/node-coveralls/blob/master/lib/fetchGitData.js#L64

Which should return something like this:
```
tree 83b0f0b746570eed9c78ee7bb6bc3b0928b380e4
parent d5e1372bbd79a9fabbceec9624a220f1a8f75348
author Nick Merwin <nick@lemurheavy.com> 1435857697 -0700
committer Nick Merwin <nick@lemurheavy.com> 1435857697 -0700

updated travis badge
```

But perhaps on Circle it's returning the summary instead of the commit message. Could you check the output of that command during a build?

Thank you!

**Comment by joshma** [comment]
Thanks @nickmerwin - looks like a bug in the commit regex - could you check out https://github.com/nickmerwin/node-coveralls/pull/99 and let me know if that looks right?
