### ISSUE TITLE
Neither comments nor status API working

### ISSUE THREAD

**Issue by oyiptong** [lemurheavy/coveralls-public#533]
Hello,

I'm trying to use CircleCI to get coveralls notified.
While that part works, coveralls is not updating my PR, neither via StatusAPI nor via comments:

This seems to work: https://coveralls.io/builds/2653756
But there are no notifications nor comments on the PR: https://github.com/oyiptong/splice/pull/66

**Comment by oyiptong** [comment]
Note that StatusAPI and comments used to work fine before.

Not much seems to have changed configuration-wise.

**Comment by hockeybuggy** [comment]
I am having what may be the same issue. Any resolution?

**Comment by d3ming** [comment]
Hitting the same issue, has anyone figured out a workaround or fix for this?
