### ISSUE TITLE
my repo non-tam-fits does not show any data anymore

### ISSUE THREAD

**Issue by ritchieGitHub** [lemurheavy/coveralls-public#537]
After reaching ~83% coverage all builds fail to show up. It should be88% by now. I tried deleting the repo and adding it new but that did not help... Any suggestions?

**Comment by jnmclarty** [comment]
See #538, possibly related.  Maybe post a link to your build, and the blank coveralls.

**Comment by ritchieGitHub** [comment]
ok, here the links are:
repo: https://github.com/nom-tam-fits/nom-tam-fits
travis: https://travis-ci.org/nom-tam-fits/nom-tam-fits
coverals:  https://coveralls.io/r/nom-tam-fits/nom-tam-fits

**Comment by ritchieGitHub** [comment]
thanks, working again
