### ISSUE TITLE
Coveralls report sent from pull request no longer visible

### ISSUE THREAD

**Issue by astrofrog** [lemurheavy/coveralls-public#538]
The following job submitted a coverage report to coveralls:

https://travis-ci.org/astrofrog/wcsaxes/jobs/64803514

(see the full debug output at the bottom). However, if I go to the URL, I see nothing:

https://coveralls.io/jobs/6315951

What could be causing this?

**Comment by astrofrog** [comment]
In addition, the PR status gets stuck at 'pending': https://github.com/astrofrog/wcsaxes/pull/164 - is this a transient issue with the server?

**Comment by jnmclarty** [comment]
I'm having a similar issue, which started over the weekend.

###### My Build 96 (~13h ago)
https://travis-ci.org/Equitable/trump/jobs/64849583
https://coveralls.io/jobs/6321143

###### My Build 97 (~2h ago)
https://travis-ci.org/Equitable/trump/builds/64899485
https://coveralls.io/jobs/6328084

**Comment by 153957** [comment]
+1, I also have PR statuses also stuck at Pending..

**Comment by astrofrog** [comment]
This was resolved for me in the end during last week.
