### ISSUE TITLE
"COVERAGE REMAINED THE SAME AT ?%"

### ISSUE THREAD

**Issue by bkon** [lemurheavy/coveralls-public#540]
Hi guys,

It seems that we have an issue with coveralls data since this morning in our private repository.

We got CircleCI build submitting data to coveralls, but coveralls never shows the data or updates the status of the coverall check on the pull request. If I visit the job page, I see "COVERAGE REMAINED THE SAME AT ?%"

For example:

```
[Coveralls] Submitting with config:
{
  "environment": {
    "pwd": "/home/ubuntu/range-me",
    "rails_root": "/home/ubuntu/range-me",
    "simplecov_root": "/home/ubuntu/range-me",
    "gem_version": "0.8.1",
    "circleci_build_num": "1997",
    "branch": "master",
    "commit_sha": "15d90fa0be170be31e9b2ba0031266ced8533f0a"
  },
  "git": {
    "head": {
      "id": "15d90fa0be170be31e9b2ba0031266ced8533f0a",
      "author_name": "Konstantin Burnaev",
      "author_email": "kon@rangeme.com.au",
      "committer_name": "Konstantin Burnaev",
      "committer_email": "kon@rangeme.com.au",
      "message": "Fixed: any error in setting up remote memcache will not cause a fallback to the local caching."
    },
    "branch": "master\n",
    "remotes": [
      {
        "name": "origin",
        "url": "git@github.com:range-me/range-me.git"
      }
    ]
  },
  "repo_token": "[secure]",
  "service_name": "circleci",
  "service_number": "1997",
  "service_pull_request": null,
  "parallel": false,
  "service_job_number": "0",
  "service_job_id": null,
  "service_build_url": null,
  "service_branch": null
}
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #1997.1
[Coveralls] https://coveralls.io/jobs/6322651
```

Visiting https://coveralls.io/jobs/6322651 just gives the "COVERAGE REMAINED THE SAME AT ?%"; pull request is in yellow "pending" state.

Any clues?

Thank you,
Kon

**Comment by bkon** [comment]
@ricky-f FYI

**Comment by valendesigns** [comment]
I am having this same issue all of the sudden.

**Comment by sanastasiou** [comment]
See also https://github.com/lemurheavy/coveralls-public/issues/530

**Comment by super3** [comment]
Having the same issue on this repo: https://github.com/storj/dataserv

**Comment by jnmclarty** [comment]
Likely same/related to #538 and #537

**Comment by DanielHKim** [comment]
Same problem here pretty much. It says "COVERAGE REMAINED THE SAME AT ?%" and the report is stuck as pending in the GitHub checks. Also falsely reports every file as 100% covered while the overall coverage is ?%. Seems like coveralls has a lot of work to be done before it's an actually fully reliable coverage tool; I've been seeing a ton of similar issues recently.
