### ISSUE TITLE
Merged coverage reports > 100%

### ISSUE THREAD

**Issue by BenMorel** [lemurheavy/coveralls-public#543]
This is related to #407 : _Merge cover result from all jobs_.

If you check this build: https://coveralls.io/builds/2742008

You'll notice that several files are reported with coverage > 100%:
- **101.52 %**      `src/Internal/Calculator/NativeCalculator.php`
- **101.93 %**      `src/BigDecimal.php`
- **103.29 %**      `src/BigInteger.php`
- **125.0 %**       `src/ArithmeticException.php`

Looks like there is a problem in the counting of the covered lines?

**Comment by daurnimator** [comment]
This seems to be oldest >100% issue.
