### ISSUE TITLE
Github integration says failing at -0.0% change

### ISSUE THREAD

**Issue by jcoyne** [lemurheavy/coveralls-public#545]
![screen shot 2015-06-11 at 12 21 14 pm](https://cloud.githubusercontent.com/assets/92044/8113583/95c86da4-1034-11e5-8411-3fb19c142520.png)

**Comment by jcoyne** [comment]
See also: https://github.com/projecthydra/sufia/pull/1223  I'm removing lines of code, so the coverage ratio *must* increase. Still getting "decreased (-0.0%)"

**Comment by randfur** [comment]
If you remove lines that were covered by tests then the coverage will decrease (assuming there are parts uncovered).

**Comment by jcoyne** [comment]
The question is why does it fail with no change (0.0%)

**Comment by 153957** [comment]
There may be a change in digits that were removed (e.g. 0.04% rounds to 0.0%).

As randfur said, removing lines of code that were covered reduces your coverage (unless you have 100% coverage). For example 4 lines of code 2 not covered: 50% coverage, remove a covered line and you get : 3 lines of code 2 not covered: 33.33% coverage

**Comment by jcoyne** [comment]
If the digits were significant enough to cause a failure, shouldn't they then be shown on the report? I think you have a UX issue here.

**Comment by joshma** [comment]
Agreed - I'd personally be happy if 2 places of precision were shown instead, and if the change is less than that either always round up to `0.01%` or indicate no significant change.

If you have just 10,000 lines of code, changing just one line will change coverage by `0.01%`, and if you have 100k loc changing <10 lines will also hit this issue, so any code base larger than that will see this issue often.

**Comment by 153957** [comment]
Agreed. It should show at least enough significant digits to indicate the change, however small.

**Comment by anjin** [comment]
Deployed a change to show minimum sigfigs
