### ISSUE TITLE
Getting "Build processing error"

### ISSUE THREAD

**Issue by adamcharnock** [lemurheavy/coveralls-public#547]
Hello, I'm getting the error "Build processing error" when submitting my coverage report.

Note that I tried deleting & recreating but to no avail.

``` javascript
{
   "git":{
      "remotes":[
         {
            "url":"git@github.com:adamcharnock/smalluuid.git",
            "name":"origin"
         }
      ],
      "head":{
         "author_name":"Adam Charnock",
         "committer_name":"Adam Charnock",
         "committer_email":"...",
         "id":"...",
         "author_email":"...",
         "message":"Fixes for bug in python 3.2. See: http://bugs.python.org/issue4769"
      },
      "branch":"master"
   },
   "repo_token":"[secure]",
   "service_name":"coveralls-python",
   "source_files":[
...
   ],
   "config_file":".coveragerc"
}

==
Reporting 3 files
==

smalluuid/__init__.py - 4/15
smalluuid/smalluuid.py - 43/90
smalluuid/utils.py - 12/25
```

Could you take a look? Thank you!

**Comment by joshma** [comment]
Same here - our CI is failing from `Bad response: 500 {"message":"Build processing error.","error":true,"url":""}`

**Comment by mantyr** [comment]
In golang same: https://github.com/lemurheavy/coveralls-public/issues/487

**Comment by adamcharnock** [comment]
This seems to have resolved itself for me now

**Comment by Stasik0** [comment]
Same on our repository: https://travis-ci.org/acplt/open62541/builds/66687822#L2055. ```{u'url': u'', u'message': u'Build processing error.', u'error': True}```

**Comment by csMACnz** [comment]
Same here. Happened yesterday but came right a few hours later, now back again.

**Comment by mantyr** [comment]
Authors need to identify the problem:
1. The problem is the service
2. The problem of the library
3. The problem of data format
4. The problem is something else.
I do not want to waste time on such trivial.

**Comment by mfittko** [comment]
Same errors occur again right now :(

**Comment by notaphplover** [comment]
I'm having the same problem

**Comment by mfittko** [comment]
this is a server problem, not a client problem. I'm using the yarn client, but I think that makes no difference. Hope this does not take days again to get fixed...

**Comment by enahs** [comment]
time to switch to codecov

**Comment by nickmerwin** [comment]
Hi all, apologies for the outage -- we had a Redis server go down earlier today and are back to normal now.

Thanks.
