### ISSUE TITLE
Error 500 submitting coverage data

### ISSUE THREAD

**Issue by jsotuyod** [lemurheavy/coveralls-public#549]
For a couple of days now, I'm seeing an error 500 when my build submits data to coveralls API from a Travs build using the [coveralls maven plugin](https://github.com/trautonen/coveralls-maven-plugin). However, the [coveralls status page](http://status.coveralls.io/) reports no incidents.

Both, version 2.0.1 and 3.0.1 of the plugin show the same error, so I assume it's not due to API changes of any sort.

The build log (and error line) can be sen [here](https://travis-ci.org/Monits/findbugs-plugin#L1530)

**Comment by jknack** [comment]
have same problem. here is the build: https://api.travis-ci.org/jobs/66716530/log.txt?deansi=true

**Comment by liry** [comment]
I have the same problem: https://api.travis-ci.org/jobs/66730795/log.txt?deansi=true

**Comment by ernado** [comment]
I have same problem with goveralls

**Comment by jdalton** [comment]
:+1: same issue.

https://travis-ci.org/bestiejs/benchmark.js/jobs/66707580
https://travis-ci.org/lodash/lodash/jobs/66710793

**Comment by reidab** [comment]
ditto with on calagator/calagator PRs: https://travis-ci.org/calagator/calagator/jobs/66730155#L751z

**Comment by jknack** [comment]
seems to be OK now: https://api.travis-ci.org/jobs/66811632/log.txt?deansi=true

Thanks

**Comment by oryband** [comment]
still happens to me with go, goveralls
