### ISSUE TITLE
Better documentation for Circle-CI configuration

### ISSUE THREAD

**Issue by PaulWoodIII** [lemurheavy/coveralls-public#552]
Coveralls should make a tutorial or add documentation on how to set up coveralls with circle-ci

**Comment by glmdevops** [comment]
+1

**Comment by jbender** [comment]
:+1: You've probably solved it for yourself, but for anyone else who ends up on this issue we were able to solve this by adding the following to our `circle.yml`

    machine:
      environment:
        COVERALLS_REPO_TOKEN: <<YOUR TOKEN>>
        COVERALLS_PARALLEL: true

    notify:
      webhooks:
        - url: https://coveralls.io/webhook?repo_token=<<YOUR TOKEN>>

**Comment by wli** [comment]
If you're using rspec with rails, this is what worked for me:

```ruby
# spec/spec_helper.rb
require 'simplecov'

# Check to see if we're inside a CI environment. If not, we don't want to override the default formatter.
if ENV['CI']
  require 'coveralls'
  SimpleCov.formatter = Coveralls::SimpleCov::Formatter
end

# The NO_COVERAGE clause is optional - Coveralls and CircleCI don't use it by default, but may be useful for you in other circumstances.
SimpleCov.start 'rails' unless ENV.key?('NO_COVERAGE')
```

I didn't need any changes to my `circle.yml` file.

**Comment by autobolt** [comment]
The documentation for setting up circleci is still lacking.  I have been trying to get it working, but despite pushing to my repo, and adding the key to my circle ci environment variables, I still see:

```
[Coveralls] Outside the Travis environment, not sending data.
```

In the test output, and nothing ever gets to Coveralls.

**Comment by kenske** [comment]
I think this got eventually updated for CircleCI 1.0, but the documentation doesn't help for 2.0.

**Comment by lifenautjoe** [comment]
Anyone has successfully integrated CircleCI and coveralls yet? 🤷‍♀️

**Comment by kenske** [comment]
I did, but ended up moving to codecov because the coveralls reports took too long (sometimes hours)

**Comment by muryanto1** [comment]
coveralls is working for me with circleci 2.0.
+ add my repo to coveralls, get the "TOKEN" for that repo, and 
+ add "COVERALLS_REPO_TOKEN" environment variable in Circleci setting for my project.
+ run "coverage xml" after running my tests with coverage on <-- I think this is needed.
+ run 'coveralls' in circleci

**Comment by lifenautjoe** [comment]
Hi all, thanks for the replies! @muryanto1 your answer worked! However I also found CodeClimate a better documented tool which I integrated easily and with code quality analysis included too.

Would recommend giving it a look :-)

**Comment by joelethan** [comment]
@lifenautjoe and @muryanto1 Could you please share how you set up the config.yml. I am abit stuck configuring circleCI with coveralls. Thank you.

**Comment by caleb15** [comment]
I was able to get coveralls working with circleci using the `coveralls-python` python library and `coveralls` node library.

I did have a bug with running the python library in parallel so I had to do a workaround: https://github.com/coveralls-clients/coveralls-python/pull/233#issuecomment-670072026
