### ISSUE TITLE
Coveralls measuring coverage of files not in git repo

### ISSUE THREAD

**Issue by blengerich** [lemurheavy/coveralls-public#555]
On repo blengerich/thesis, I am having a problem where coveralls creates a coverage report for too many files.  Not only does it check the files in the git repo, it also checks the source of imported packages.  I don't care about the coverage of these files, I only want coverage stats for my own repo.

**Comment by paddor** [comment]
+1. Same here. I get coverage measures for files of **another** one of my repositories.
