### ISSUE TITLE
Setting parallel builds as done gives an access denied page

### ISSUE THREAD

**Issue by iainx** [lemurheavy/coveralls-public#556]
I've uploaded all the coverage for my parallel build. They are all sitting in the "pending completion". If I click on the Set Done button it gives me an Access Denied page.

**Comment by jbender** [comment]
:+1: Seeing this as well, would love to get an update given that it's been almost 3 weeks

**Comment by nickmerwin** [comment]
hey @iainx and @jbender we've deployed an update for that security warning -- could you try again now?

Thank you!

**Comment by jbender** [comment]
Hey @nickmerwin, your fix worked for two of my builds, but two other ones are still not closing, but (at least?) not giving me an error, just refreshing the page without effect.

**Comment by nickmerwin** [comment]
@jbender ok could you link me to the builds that aren't finished? If it's a private repo you can email me: nick@coveralls.io

Thanks.

**Comment by varya** [comment]
I have the same problem. For example, with this PR https://github.com/SC5/sc5-styleguide/pull/723
