### ISSUE TITLE
Repos not showing up

### ISSUE THREAD

**Issue by bauerj** [lemurheavy/coveralls-public#557]
I've tried to add a repository to Coveralls today.

After waiting an hour, it still shows my repos are syncing. I remember having this issue when I registered at coveralls.io quite a long time ago so I guess it's not just slow but not working at all.

<img src="http://bauerj.link/file/tGZdNq.png">

**Comment by lexi-lambda** [comment]
+1, I hit the "Sync Github Repos" button today to add a new repo, and it's been stuck "syncing" my repos for over an hour.

**Comment by nickmerwin** [comment]
@lexi-lambda @bauerj the issue you hit should be fixed now -- your github OAuth tokens had rolled.

Use this link to start the sync again:
https://coveralls.io/refresh

Thanks!

**Comment by brianmd** [comment]
I just signed up today and am getting the same never-ending 'your repos are syncing'. Upon sign-up, I initially was getting a 503 error when trying to get github authorization, and maybe that has something to do with it?

**Comment by nickmerwin** [comment]
hi @brianmd we've had a slower than usual connection to Github today, causing some timeouts. Could you try a couple more times and let me know if you're successful?

Thanks!

**Comment by brianmd** [comment]
Absolutely! If I need to do anything other than refresh the page (e.g.,
delete account and re-create), just let me know.

**Comment by brianmd** [comment]
It is all good, thank you for your help!
