### ISSUE TITLE
Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Build processing error.) 

### ISSUE THREAD

**Issue by neoremind** [lemurheavy/coveralls-public#559]
Hi there,

I was using coveralls-maven-plugin and had integrated with travis ci. My project is java and maven based and while travis builds successfully and then execute "after-success" procedure, I got the following failure, which seems to have some problems when delivering report via converalls API to your platform. I tried a few times but failure still persists, I suppose it was a stable reproduced issue. So could you please help me figure out? My repo addr is https://github.com/neoremind/navi-pbrpc.

Downloaded: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar (5 KB at 16.5 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar (28 KB at 110.7 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 51.1 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/3.4.1.201406201815-r/org.eclipse.jgit-3.4.1.201406201815-r.jar (1862 KB at 6893.1 KB/sec)
[INFO] Starting Coveralls job for travis-ci (69604834)
[INFO] Git commit e80f44f in master
[INFO] Writing Coveralls data to /home/travis/build/neoremind/navi-pbrpc/target/coveralls.json...
[INFO] Processing coverage report from /home/travis/build/neoremind/navi-pbrpc/target/site/cobertura/coverage.xml
[INFO] Successfully wrote Coveralls data in 517ms
[INFO] Gathered code coverage metrics for 71 source files with 7052 lines of code:
[INFO] - 1451 relevant lines
[INFO] - 810 covered lines
[INFO] - 641 missed lines
[INFO] Submitting Coveralls data to API
[ERROR] Submission failed in 4459ms while processing data
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2015-07-05T10:40:57+00:00
[INFO] Final Memory: 36M/465M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report (default-cli) on project navi-pbrpc: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 500: Internal Server Error (Build processing error.) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by automatictester** [comment]
Same happened to me:
https://travis-ci.org/automatictester/lightning/builds/69612087#L216

Since last successful build only thing that has changed was readme file.

**Comment by AmatanHead** [comment]
I'm getting the same error at https://travis-ci.org/AmatanHead/operational-transforming#L150.

It also can be reproduced locally with almost the same log:

    ...
    > jscoverage lib && OT_COVERAGE=1 nodeunit --reporter=lcov test | coveralls
    process files: 4
    Bad response: 500 {"message":"Build processing error.","error":true,"url":""}
    ...

**Comment by reid-spencer** [comment]
:+1: 

Happens for me too via travis @ https://travis-ci.org/scrupal/scrupal/builds/69636251

The log of the job looks like this:
```
33.71s$ sbt coveralls
Detected sbt version 0.13.8
Using jvm options defined in file /etc/sbt/jvmopts
# Executing command line:
/usr/lib/jvm/java-8-oracle/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/0.13.8/sbt-launch.jar
coveralls
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading project definition from /home/travis/build/scrupal/scrupal/project
[info] Set current project to scrupal (in build file:/home/travis/build/scrupal/scrupal/)
[info] Repository = ./.git
[error] Uploading to coveralls.io failed: Build processing error.
[error] Coveralls.io server internal error: Build processing error.
```
Note that this takes 30+ seconds so I assume something is going wrong during the submission of the upload to coveralls.io.

**Comment by neoremind** [comment]
The problem has been solved anyhow. Thanks for the work done by coveralls teams!

Below is the log:
[INFO] Starting Coveralls job for travis-ci (69728967)
[INFO] Git commit 6587378 in master
[INFO] Writing Coveralls data to /home/travis/build/neoremind/navi-pbrpc/target/coveralls.json...
[INFO] Processing coverage report from /home/travis/build/neoremind/navi-pbrpc/target/site/cobertura/coverage.xml
[INFO] Successfully wrote Coveralls data in 358ms
[INFO] Gathered code coverage metrics for 71 source files with 7052 lines of code:
[INFO] - 1451 relevant lines
[INFO] - 810 covered lines
[INFO] - 641 missed lines
[INFO] Submitting Coveralls data to API
[INFO] Successfully submitted Coveralls data in 4503ms for Job #28.1
[INFO] https://coveralls.io/jobs/6935732
[INFO] *** It might take hours for Coveralls to update the actual coverage numbers for a job
[INFO]     If you see question marks in the report, please be patient
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:44 min
[INFO] Finished at: 2015-07-06T13:08:00+00:00
[INFO] Final Memory: 35M/465M
[INFO] ------------------------------------------------------------------------
