### ISSUE TITLE
The owner of this repo needs to re-authorize with Github?

### ISSUE THREAD

**Issue by ionelmc** [lemurheavy/coveralls-public#562]
I get this:

```
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.
```

I've tried to revoke token and reauth. Did not fix the issue.

**Comment by smetdenis** [comment]
Hi,

I have such proplems too with https://coveralls.io/github/smetdenis/SimpleTypes
For example here https://coveralls.io/builds/3005093/source?filename=src%2Fautoload.php

I see message
```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
```

So I've tried to revoke token and reauth too.
Recently I deleted my account but it still doesn't work. Plz, let me know how to fix it ?

Thanks a lot and best regards, SmetDenis.

**Comment by smetdenis** [comment]
It seems I understood...
After I deleted repo from coversall via button http://llfl.ru/otpcy5 and added it again, my reports started to work fine again. I really don't know why =)

**Comment by bchretien** [comment]
:+1: Same thing for our [older repos](https://coveralls.io/github/roboptim), and deleting the repos on coveralls.io would destroy the data from the last few years, which would be a real shame.

**Comment by smetdenis** [comment]
My project was created several days ago, so history is not so important for me :)
Unfortunately support did not answer and I couldn't find another decision...

**Comment by freefony** [comment]
i clicked on signin and refreshed(even after navigating back to the page after login i still had to refresh for it to work)

**Comment by Thimxx** [comment]
Wow! 2 years open and still happening. A benchmark of reactivity. Is basically this is basically the Hope Telephone
