### ISSUE TITLE
Coverage report by submodule

### ISSUE THREAD

**Issue by cemo** [lemurheavy/coveralls-public#563]
Coverage is displayed currently by file. It would be nice to see by module as well. Especially in java world, multi modules are common practice and coverage by module is important. This is encouraging module owners to increase their coverage.

**Comment by treussart** [comment]
Hi, I have the same problem, I can't read on coveralls.io my files into the submodule.
idea :
SOURCE NOT AVAILABLE
Git repo : [git repo of the submodule like https://github.com/name/repo_submodule]

**Comment by markspl** [comment]
Sorry about commenting a closed issue, but I tried to found more information about does Coveralls support submodules. Is there any new information about this? Thanks!

**Comment by afinetooth** [comment]
hi @markspl the closest thing I can think of to support a coverage report by module would be to use job flags. 

Per the [API reference here](https://docs.coveralls.io/api-reference), you'll want to parallelize your CI build (run it in several jobs), where each job is a module and you send a `flag_name` labeling the job. With that configuration, you'll get separate PR checks for each module and separate jobs in each build view that have their own coverage %.

Here's some [background on configuring parallel builds](https://docs.coveralls.io/parallel-build-webhook). Let me know if you want more help with it. Or let me know if this doesn't get at what you're looking to do.
