### ISSUE TITLE
504 from source_file.json when trying to look at reported coverage

### ISSUE THREAD

**Issue by jerrod** [lemurheavy/coveralls-public#564]
See attached image - essentially I have not been able to view coverage reports within coveralls.io's website.
<img width="1333" alt="screen shot 2015-07-10 at 2 19 23 pm" src="https://cloud.githubusercontent.com/assets/765/8625830/258838a2-270f-11e5-94d2-a515e7ad5ce4.png">

**Comment by nickmerwin** [comment]
@jerrod what repo is that happening on?

**Comment by jerrod** [comment]
`usertesting/orders`

**Comment by nickmerwin** [comment]
Could you link me to the specific url? Or email it to me at nick@coveralls.io

Thanks

**Comment by jerrod** [comment]
emailed - thanks!

**Comment by nickmerwin** [comment]
Hey haven't seen it come through yet, could you double check?

**Comment by jerrod** [comment]
https://coveralls.io/builds/3026683 Or any of the builds on https://coveralls.io/github/usertesting/orders

thanks!

**Comment by nickmerwin** [comment]
Ah I see it's timing out on the aggregated build view. We're working on optimizing that, but in the meantime you can drill down to the individual jobs, e.g. https://coveralls.io/jobs/7029347 to get source file coverage.

**Comment by jerrod** [comment]
ah.  unfortunately any single job doesn’t give an accurate (or actionable) view of coverage.

Is there a timeline on optimizing the integrated view thats timing out?

thanks!
