### ISSUE TITLE
“Coverage decreased (-0.0%) to 99.68%”

### ISSUE THREAD

**Issue by n1k0** [lemurheavy/coveralls-public#565]
![screen shot 2015-07-10 at 19 23 35](https://cloud.githubusercontent.com/assets/41547/8632767/8ae68362-27a9-11e5-9d46-4a31f3c32934.png)

![cjkefu3ukaani3u](https://cloud.githubusercontent.com/assets/41547/8632768/8db96230-27a9-11e5-8748-68cca2b62583.jpg)

See:
- https://github.com/mozilla-services/kinto.js/pull/58
- https://coveralls.io/builds/3027040

I think your percentage computation function is a little picky, I'm even challenging its relevance here :)

**Comment by 153957** [comment]
It is not wrong, your code contains less lines, so each line that is not tested is a larger percentage.
You can change the threshold for the amount of decrease to result in a failed build, on the projects page on coveralls.io.

**Comment by n1k0** [comment]
> so each line that is not tested is a larger percentage

Maybe you should add this information into the failure message?

> You can change the threshold for the amount of decrease to result in a failed build, on the projects page on coveralls.io.

I didn't find where, hint?

**Comment by 153957** [comment]
If you log in on coveralls and yo to the project page: https://coveralls.io/github/mozilla-services/kinto.js
Scroll down, on the lower left you should see these settings:

![coveralls_settings](https://cloud.githubusercontent.com/assets/1433682/8650357/70ad6590-2972-11e5-9497-5a0ffb0d3c82.png)

Change the `COVERAGE DECREASE THRESHOLD FOR FAILURE` to something more than `0.05%` that way you will always at least see `0.1%` when coveralls decides to fail the build.

**Comment by n1k0** [comment]
> > Maybe you should add this information into the failure message?
> Its just math..

I was mostly talking about the travis hook message, which is quite unclear. Also speaking of maths, I know -0 is a valid concept but come on… ;)

> Scroll down, on the lower left you should see these settings

There's nothing on the lower left for me:

![screen shot 2015-07-13 at 15 46 29](https://cloud.githubusercontent.com/assets/41547/8651055/0081fac4-2977-11e5-9957-05c7529ea305.png)

Is this because I'm part of the org owning the repo, and not an admin of it? (I'm the admin of the repo itself)

**Comment by 153957** [comment]
You are not signed in on coveralls, see the 'sign in' in the sidebar.

**Comment by n1k0** [comment]
Ah right. Though signing in didn't fix it :(

![screen shot 2015-07-13 at 23 43 29](https://cloud.githubusercontent.com/assets/41547/8661611/18eb7238-29b9-11e5-9274-cd0e821dfba1.png)

**Comment by 153957** [comment]
That is weird.. Perhaps you need to be the owner..

I would suggest you create another issue about that (badge), it is probably unrelated.
(Note I do not work on/for coveralls)

**Comment by 153957** [comment]
See #545

**Comment by kbrock** [comment]
This is just a common math comparison error in all IEEE float numbers.

Could you use `round` and/or compare using a small rounding factor?

```ruby
max_value = 214.04 # more than this difference will fail
value = 214.04 - 74.79 + 74.79

puts value > max_value # ==> true
puts value.round(0.001) > max_value # ==> false
```

**Comment by kortschak** [comment]
@153957 

>It is not wrong, your code contains less lines, so each line that is not tested is a larger percentage.
You can change the threshold for the amount of decrease to result in a failed build, on the projects page on coveralls.io.

That may be the case for the original issue, but we see exactly the same error [where there is a -2 +2 change](https://github.com/gonum/internal/issues/25. So, zero line count difference, but a -0.0 resulting in a failure. In other PRs I see a stated increase of +0.0! Zero, is special, it should probably be treated as such.

**Comment by 153957** [comment]
@kortschak You have a different issue that the one my comment was aimed at. There the problem was that there was an actual coverage change, it was just very small. In your case you claim not to have a coverage change but coveralls claims a difference. Please make a new issue for that case.

**Comment by kortschak** [comment]
@153957, done #708.

**Comment by laughinghan** [comment]
> It is not wrong, your code contains less lines, so each line that is not tested is a larger percentage.

We're all agreed that the tool is not speaking a *false statement*, but it's still the *wrong thing to say*, right? There are a few ways that test coverage *as a percentage* can decrease:

1. changing tests so that they cover less code
2. adding untested code
3. reducing tested code

Certainly 1. and 2. are bad and should trigger alarms from a CI system, but 3. can often be good thing, like due to simplifying code that happens to be tested (https://github.com/cla-assistant/cla-assistant/pull/115#issuecomment-212577053), right?

I think this is a strong argument that percentage test coverage is the wrong thing to measure, the right thing to measure is whether the number of lines of untested code increased: that would complain if 1. or 2. happened, but not if 3. happened.
