### ISSUE TITLE
Not able to switch branch, only master available

### ISSUE THREAD

**Issue by inirudebwoy** [lemurheavy/coveralls-public#568]
After creating repo from github I am not able to select any other branch beside master. I have more than one branch under this repository.
Sync Branches does not return nothing
Show All reloads page with no change.

**Comment by paulzolnierczyk** [comment]
I'm having the same problem too.  I just started a Coveralls subscription and added a private repo. I have a master branch and a develop branch, I can't see the develop branch or get to it.  develop is where all my code is at right now.

**Comment by nickmerwin** [comment]
hi @inirudebwoy and @paulzolnierczyk the branch dropdown will only show branches that we've received coverage data for. 

If it still looks like there's an error please let me know, thanks!

**Comment by goanpeca** [comment]
I already have data for master and branch 1.2, but the dropdown does not display them

![image](https://cloud.githubusercontent.com/assets/3627835/15518754/ff16b90e-21c3-11e6-89a0-53a3db9a0be9.png)

**Comment by jonathanparrish** [comment]
I am having issues with this as well.  I even changed my default branch in the Repo to the branch that I want the coverage for and it still defaults to Production.  My dropdown only shows the production branch.

**Comment by Sanyambansal76** [comment]
I am also facing the same issue. The branch for which I run coveralls the first time is only shown on the dashboard. Dropdown only showing two option 1. My first branch with which i pushed first and 2. Head

**Comment by zoechi** [comment]
My travis task runs on `develop` branch, but Coveralls shows the result in `master` and `develop` isn't listed.

**Comment by Wokoro** [comment]
I am similiar issue also.

I have my codebase  on my `develop` branch but can't access it on **coveralls**.

**Comment by andykais** [comment]
similar issue, requesting that this issue be re-opened. If it helps, here is my coveralls repo https://coveralls.io/github/andykais/scrape-pages. It only shows master, but I have coveralls running on an open pr. Do pr branches get excluded from branches perhaps? When I log into coveralls I can see coverage information for said branch per each build https://coveralls.io/repos/256446/builds, but the only branch in the dropdown is master.

Here is the travis ci configuration: https://github.com/andykais/scrape-pages/blob/master/.travis.yml#L19-L20
