### ISSUE TITLE
Not syncing with github.

### ISSUE THREAD

**Issue by LucioFranco** [lemurheavy/coveralls-public#569]
I have been trying to sync coveralls with github all day and its just been showing me the syncing from github text. I have tried almost everything to see if it was an account error or a github problem but it seems that it is coveralls causing the problems

**Comment by iamstarkov** [comment]
:+1: the same problem for me

right now it doesnt work for me on both latest firefox and chrome on os x. with uninstalled flash, if it matters

**Comment by cnuss** [comment]
Same problem for me

**Comment by netmask** [comment]
same here, looks like the payments is the only thing working on my account ....

**Comment by nickmerwin** [comment]
@LucioFranco @netmask @cnuss sorry guys, our repo sync worker was stuck. You should be good to go now.

Thanks!

**Comment by iamstarkov** [comment]
@nickmerwin thank you!

**Comment by cnuss** [comment]
@nickmerwin you da man! thanks!
