### ISSUE TITLE
Unable to update credit card info

### ISSUE THREAD

**Issue by cnuss** [lemurheavy/coveralls-public#571]
Hey guys,

I'm unable to update my credit card info for my subscription.  And the wrong card got billed when I upgraded to pro.

Please let me know if you can help.

Cheers,
Christian

**Comment by anjin** [comment]
Hey Christian, try that again. Let me know when the info is changed and I'll refund the original charge and run the charge on the new card.

**Comment by cnuss** [comment]
Still didn't work... any advice?

**Comment by anjin** [comment]
The card with the last 4 of 6530 is the old card?

**Comment by cnuss** [comment]
Yeah, 6530 is the old card.

Also, please don't refund the original charge, I expensed it already, thanks!

**Comment by anjin** [comment]
Gotcha, thanks for letting me know. Alright try changing the card details again.

**Comment by cnuss** [comment]
Worked this time, thanks!
