### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by macfreek** [lemurheavy/coveralls-public#572]
I have a public repository on github, on a personal (non-organisational) account: https://github.com/macfreek/NBT

I was able to configure Travis-CI to push the result on a test to Coveralls. I was also able to push it myself directly, using Python-coveralls.

Whenever I try to view the coverage [report of an individual file](https://coveralls.io/builds/3098649/source?filename=nbt%2Fnbt.py), Coveralls.io gives the following error:

> Source Not Available
> 
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

Based on previous bug-reports, I (1) logged out from coveralls.io, (2) revoked the Coverall [authorisation from Github](https://github.com/settings/applications), and (3) logged back in. I could see that Coverall read authorisation was removed and re-added in Github. Unfortunately, I still get the same error.

I'm actually surprised that coveralls.io needs and OAuth key to access the files: after all, they're from a public repository, and they can simply be fetched with a `git fetch`. In addition, `coveralls debug` contains the full source code in the json data, so I had expected that `coveralls` would have pushed it to coveralls.io.

Is there any way to fix this? Or any way to debug this?

**Comment by shaeberling** [comment]
I have exactly the same problem, tried the same steps to fix it, also didn't help.

This is the repository:
https://coveralls.io/github/shaeberling/winston

**Comment by nickmerwin** [comment]
Hey @macfreek and @shaeberling,

We pull the source from Github on-demand so it doesn't inflate our storage size, and we need to use your Github access token so ours doesn't get rate limited. 

I confirmed your GH token is no longer valid and have manually removed it. Could you log back in to Coveralls and let me know when you do? I'll check to see if there's something else going on.

THanks!

**Comment by macfreek** [comment]
Awesome, it works now!

I went to coveralls.io and was still logged in. I logged out from the menu.
Clicked "Get started for free", then "Github sign-up". I was Immediately logged in.
I Went to repo, and checked out the file.
Coveralls.io displayed the file right away.

**Comment by macfreek** [comment]
@shaeberling Could you close the ticket if it also works for you now?

**Comment by shaeberling** [comment]
Perfect, it worked for me as well, thanks for your help!

(I can't close the ticket since I haven't created it)

**Comment by nickmerwin** [comment]
Glad to hear it, thanks all!
