### ISSUE TITLE
Coverage badge shown as "unknown" even after 3 days

### ISSUE THREAD

**Issue by julianghionoiu** [lemurheavy/coveralls-public#575]
Something seems to be broken with my repo. I get the coverage report:
https://coveralls.io/github/julianghionoiu/tdl-client-java

But the coverage badge still shows as "unknown".
<img width="443" alt="screen shot 2015-07-21 at 19 54 20" src="https://cloud.githubusercontent.com/assets/5089833/8809743/5be037f2-2fe2-11e5-9437-ba86ef2c1cd8.png">

**Comment by nickmerwin** [comment]
hi @julianghionoiu that's updated now -- your builds were coming in mislabeled as pull requests.

Thanks!

**Comment by julianghionoiu** [comment]
Thanks a lot, Nick !
