### ISSUE TITLE
Jobs not processing

### ISSUE THREAD

**Issue by jbender** [lemurheavy/coveralls-public#578]
Looks like your job queue is blowing up, which is leading us to have many "pending" PRs waiting for the results to come back, would be nice to get a heads up about issues like this 

![Screenshot](https://www.dropbox.com/s/v3l6ggdiklj3l6p/Screenshot%202015-07-22%2010.31.11.png?dl=1)

**Comment by devinivy** [comment]
@jbender do you think this explains my issue in #579?

**Comment by jbender** [comment]
@devinivy I'd say that you're more than likely stuck somewhere in that mountain with our pending builds

**Comment by benmcollins** [comment]
Can you tell me where you found the processing queue graph?

**Comment by jbender** [comment]
@anjin more than 24 hours without update on a paid service is very unprofessional please give this more attention

**Comment by benmcollins** [comment]
@jbender I agree.

**Comment by anjin** [comment]
We are still running a large migration and regular service is going to be interrupted until everything is worked through. We are implementing a big change to how we handle and store build data - so we have to process all the historical data as well as the constant influx of new data. We want to remain free for open source forever, and at this time we have over billion rows in our DB.

Please bear with us while we scale the service to make it better for you!

**Comment by benmcollins** [comment]
This is a mixed message. The status page says "Something in our hardware is slowing down our queue processor. We're looking into it."

Is there something wrong or is this a migration, or what?

**Comment by anjin** [comment]
This is more accurate: The queue processor is experiencing slowdowns due to an interaction between resources. We had hoped to keep it running as normal while dealing with our large migration but there will be slowdowns.

**Comment by jbender** [comment]
Please post more updates to your status page when you have downtime like this so we know that you *are* actually working on it/have diagnosed the problem. This also feels like a change that was known about ahead of time and could have been warned about. Just looking for some better communication moving forward.

**Comment by benmcollins** [comment]
Seriously, the status graph looks like nothing is getting processed. If it's was a slow down, I would expect some processing catch-up during night hours and peaks during the day hours. Instead, it's a steady incline of backlog.

If it is a slow down, I would expect paid accounts to get priority. I understand the open source for free thing (I use it for open source as well), but paid should get priority on processing.

**Comment by benmcollins** [comment]
Approaching 24 hours since the last update on the status page...

**Comment by benmcollins** [comment]
Sorry, this is the only place I can get anything through. I'm still unsure why this is marked closed, but anyway:

9:42 - DB restore starts
12:51 - (3 hours later) DB estimated to be half way done
18:05 - (8+ hours later) No update, and 5+ hours since a half way point that took 3 hours to get to.

Please, can we keep the flow of updates coming? I strongly suggest making it hourly, or at least every 2 hours. We are three days into this outage, and the handling has not been what I would call transparent.

**Comment by anjin** [comment]
The restore process is still in the process of finalizing
