### ISSUE TITLE
modal-backdrop blocks ability to subscribe to incidents

### ISSUE THREAD

**Issue by jgrevich** [lemurheavy/coveralls-public#580]
The modal backdrop on http://status.coveralls.io/ blocks user's from being able to subscribe to incidents (unless they manually remove that html element via a browser's dev tools):

![screen shot 2015-07-22 at 3 52 39 pm](https://cloud.githubusercontent.com/assets/24955/8839416/035e8108-308a-11e5-8fe6-4987f1f4f8a8.png)

Also, the text in the alert box may read better if the background is not 100% transparent:

![screen shot 2015-07-22 at 3 52 33 pm](https://cloud.githubusercontent.com/assets/24955/8839446/380d8188-308a-11e5-91b7-8cdebd1b8c88.png)

**Comment by anjin** [comment]
Bit of weirdness from statuspages.io

**Comment by jgrevich** [comment]
Ah, sorry I didn't realize that was a [third party service](https://www.statuspage.io/). Hectic Wednesday :)
