### ISSUE TITLE
Newly sent coverage showing no lines in files

### ISSUE THREAD

**Issue by benmcollins** [lemurheavy/coveralls-public#583]
A newly sent coverage build on my project shows three files as zero lines in the file and zero relevant lines.

**Comment by danmichaelo** [comment]
The same just happened to me: https://coveralls.io/builds/3143621 (this commit actually didn't change any code at all, just setup configuration)

**Comment by kgryte** [comment]
Similar issue occurred for one of my projects. Created a new repo, turned on coveralls, and yet no coverage is appearing on the coveralls [site](https://coveralls.io/github/validate-io/email-address). 

I followed the same procedure I have used for all prior repos. The only difference is that this repo was switched on post migration.

**Comment by lukeapage** [comment]
happening to jshint too

**Comment by lukeapage** [comment]
this stopped happening for me - it only happened processing the queue backlog.

**Comment by benmcollins** [comment]
I've rerun a coverage build several times and it ranges from 4 to 5 files show 0 lines. Not just 0 lines covered, or 0 lines relevant, but it says that the file literally has 0 lines, but even clicking on it for details shows the entire file.

**Comment by gterzian** [comment]
I can see just now that when a file goes __up to 100% coverage__, the relevant lines drop to 0, resulting in a drop of overall coverage for the project

![screen shot 2015-07-27 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/2792687/8900609/2564983a-3474-11e5-800e-b79436d58f53.png)

**Comment by gterzian** [comment]
and it's happening consistently

![screen shot 2015-07-27 at 3 58 45 pm](https://cloud.githubusercontent.com/assets/2792687/8901092/6ba41fc4-3478-11e5-83ed-18c50f95eed6.png)

**Comment by dirkmoors** [comment]
+1, I've just started using coveralls for my project, and I'm getting almost all zeros, and 100% coverage (which is not correct).

![image](https://cloud.githubusercontent.com/assets/1183654/8901514/d337fba8-3449-11e5-8625-ff31e6a97a49.png)

Also, I noticed that I'm getting the error 'SOURCE NOT AVAILABLE'.

![screenshot from 2015-07-27 10 25 07](https://cloud.githubusercontent.com/assets/1183654/8901522/e1b2930a-3449-11e5-909d-a14bb73fc3de.png)

**Comment by joeybloggs** [comment]
Having the same issue myself with my go project
<img width="1031" alt="screen shot 2015-07-27 at 12 48 24 pm" src="https://cloud.githubusercontent.com/assets/8068371/8912016/d2a7eb44-345d-11e5-80a3-3ce43a2d29a3.png">
