### ISSUE TITLE
Relevant lines of 100% covered files drops to 0

### ISSUE THREAD

**Issue by gterzian** [lemurheavy/coveralls-public#587]
I can see just now that when a file goes to 100% coverage, the relevant lines drop to 0, resulting in a drop of overall coverage for the project

![screen shot 2015-07-27 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/2792687/8900609/2564983a-3474-11e5-800e-b79436d58f53.png)

**Comment by lukeapage** [comment]
duplicate of #583

**Comment by gterzian** [comment]
@lukeapage thanks
