### ISSUE TITLE
Add Go to supported languages on Getting Started page

### ISSUE THREAD

**Issue by jmcvetta** [lemurheavy/coveralls-public#59]
For the last couple weeks I have been using [`goveralls`](https://github.com/mattn/goveralls) to upload coverage data for my [Go](http://golang.org) code.  Currently `goveralls` works great from [Drone.io](http://drone.io), but does not work with Travis CI.  The process is simple, and documented on the README for `goveralls` .

Please consider adding Go to the list of supported languages on the Getting Started page.

**Comment by dsoprea** [comment]
This can be closed now.
