### ISSUE TITLE
Coveralls logo on coveralls.zendesk.com is 404

### ISSUE THREAD

**Issue by moreati** [lemurheavy/coveralls-public#593]
I assume it's a side effect of your recent platform upgrade.

It's trying to use https://coveralls.io/assets/coveralls_logo-1f2ba4b3183e47d49d1f7ae1ae9d8d22.png.
It should probably use https://coveralls.io/assets/coveralls_logo-c2066e4cdffe3009caeb1addd5154cde.png

Not exactly high priority, but thought you'd like to know.

**Comment by anjin** [comment]
Thanks!
