### ISSUE TITLE
Coverage data quite incorrect

### ISSUE THREAD

**Issue by sandlerben** [lemurheavy/coveralls-public#594]
The coverage data for the go-torch (https://coveralls.io/github/uber/go-torch) repository is incorrect. Coveralls says that visualization.go and main.go contain 0 lines (which is clearly not true). Moreover, there are lines in graph.go which Coveralls says are uncovered (i.e. 97-102) which are shown as covered by gocov. They are definitely covered. 
<img width="977" alt="screenshot 2015-07-28 09 41 47" src="https://cloud.githubusercontent.com/assets/4823572/8937523/f07ad40a-350d-11e5-8ef7-93167d4c3ad7.png">

**Comment by nickmerwin** [comment]
Hi @sandlerben could you trigger another build? We had a post-hosting-migration issue yesterday where this was a symptom.

Thanks.

**Comment by sandlerben** [comment]
How do I trigger a building without changing my repo?

**Comment by nickmerwin** [comment]
Ah it's a button on Travis:





On Tue, Jul 28, 2015 at 10:05 AM, Ben Sandler <notifications@github.com>
wrote:

> How do I trigger a building without changing my repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lemurheavy/coveralls-public/issues/594#issuecomment-125680355>
> .
>



-- 
Nick Merwin
*LEMUR Heavy Industries*
*p 323.275.4588 | c 213.304.2136 | lemurheavy.com <http://lemurheavy.com/>*

**Comment by nickmerwin** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/1129/8937995/a92eed7c-3510-11e5-803b-e8987996b385.png)

**Comment by reflexdemon** [comment]
Hey,

Just re run your build. The coverage data is captured correctly now.

I was just browsing through https://github.com/lemurheavy/coveralls-public/issues/594 and found that the issue is resolved now.

This issue is good to close now.

**Comment by nickmerwin** [comment]
Thanks @reflexdemon!
