### ISSUE TITLE
repo is not adding

### ISSUE THREAD

**Issue by ashwin31** [lemurheavy/coveralls-public#595]
My repository didn't get added to coveralls and after few re-sync tries, I have asked my colleague to add the repo from his account and it did show up in his account it didn't in my account even after 2hours.

https://coveralls.io/github/MicroPyramid/pietrack

**Comment by nickmerwin** [comment]
Hi @ashwin31 we just released a bit of improved Github token error handling. Could you try re-syncing again now?

Thanks!

**Comment by jessaustin** [comment]
All day long I've been hitting the `RE-SYNC REPOS` button at https://coveralls.io/repos/new. I just get a permanent `Your repos are syncing...` message. When after an hour I give up and reload the page, it lists only my older repos.

**Comment by nickmerwin** [comment]
Hi @jessaustin could you try logging out and back in?

**Comment by JSkimming** [comment]
I've just had the same issue, logging out and back in again fixed it, in that I was then shown the updated repo list.

**Comment by ashwin31** [comment]
Hi @nickmerwin I found no luck https://coveralls.io/repos/new?name=MicroPyramid&service=github

there is a new repository "pietrack" and that is not getting added to my account. Let me know if I can help you by providing any additional information.

**Comment by jessaustin** [comment]
Thanks @nickmerwin that did it.

**Comment by ashwin31** [comment]
Thank you, its working now.
