### ISSUE TITLE
Committer become git username, not sync with github username

### ISSUE THREAD

**Issue by elct9620** [lemurheavy/coveralls-public#598]
My coveralls committer show as github username and working well, but about two days ago it becomes git display name. Is it a bug or a new feature change?

**Comment by nickmerwin** [comment]
Hi @elct9620 we still just use the git committer name that's passed in from the coverage data, perhaps your configuration changed?

**Comment by elct9620** [comment]
Yes, I found my git config missing, and I fixed it.
