### ISSUE TITLE
Coveralls does no longer work after transfering a repository

### ISSUE THREAD

**Issue by bel2125** [lemurheavy/coveralls-public#603]
I have an open source project (MIT licensed) on github, as a repository linked to my user github account (bel2125/civetweb). This repository had a working coveralls integration.
The project has reached a size and level of activity, where it made sense to create a github organization for it. A week ago, I transferred the repository to this organization, where I am the owner, so my GitHub user bel2125, used to sign in at coveralls, still has full access to the repository. The organization has the same name as the project (civetweb), it remains fully open source (MIT licensed), and there is no private repository in this organization.

Transferring the repo on github automatically creates a link from the old site https://github.com/bel2125/civetweb/ to the new site https://github.com/civetweb/civetweb/
Also TravisCI is working again, but
**Coveralls does not seem to recognize, the repository has moved**

I also can not just add the new repository, since I can not see add project page https://coveralls.io/repos/new does not show the civetweb organization. Non of the refresh buttons at this page helped.

(Reference to the issue for the civetweb organization: https://github.com/civetweb/civetweb/issues/183)

**Comment by chrismichaels84** [comment]
I have had the same problem with spider/spider. I moved it from chrismichaels84/spider-graph. Travis CI has updated (after forcing it to), and the new organization is authorized.

When I try to add the new repo, it asks me to Re-authorize github. When I do, it tries to sync my repos, but I've let it sit for an hour and it never gets past the spinning wheel. I have no way of getting the new organization to show up.

**Comment by bel2125** [comment]
I have still no idea how to get "coveralls" to accept `civetweb/civetweb` as a new project source (instead of `bel2125/civetweb`).

If anyone knows, please let me know.

**Comment by bel2125** [comment]
Since I did not find anything in the documentation and did not get any response here, I tried around and finally succeeded.
This is what I did (maybe some steps are unnecessary), maybe it will be helpful for someone:
Login to coveralls with github, go to the "add repo" and push the buttons on the top (resync ...).
Go to github, log in, go to the organisation, go to settings, go to third-party access, explicitly add coveralls.
Go to coveralls, click on your username to the left (between "blog" and "sign out") to get to the "your account" page. Unlink your username from the github account - the service will log you out.
Log in again, relink your username with the github account.
Go to the "add repository" again, and push the "resync" buttons again.
You will see the new organisation.
Then add the repository of this organisation.
The status batches will have a different address, so you need to update the status image (in README.md for my project).

**Comment by AnthonyNahas** [comment]
I am facing the same problem! After transferring my repo into an organization, coveralls is not working anymore for that project ...
