### ISSUE TITLE
Organization not showing up when syncing repos

### ISSUE THREAD

**Issue by electricjones** [lemurheavy/coveralls-public#604]
I have read through the issues here and tried all of the suggestions. I'm not sure what I'm doing wrong.

I have a personal github account and two repositories. One I've had for a long time and it syncs fine. The other I've created in the last month. I've just setup Travis on a public repo in that organization (spider/spider). I am a public team member and owner.

When I go to add repos, it asks me to re-authorize github. I do, and the syncing spinner spins for hours without ever loading the new repos.

I have:
- Logged in and out of coveralls
- Cleared cache
- Tried another browser
- Denied access in github and then reinstated access
- Refreshed my token
- Made myself private and public again.
- Tried across the space of several days.

Is there something I'm missing?

Thank you.

**Comment by chrismichaels84** [comment]
I have found that the only way to get spider to show up is, on github, to remove any third-party restrictions for the organization. That worries me. I tried enabling and disabling, but spider disappeared as soon as it was disabled again.

Coveralls does show up on my list of enabled applications. I've also tried to create another github user with admin rights and couldn't get the organization to show up there either.

**Comment by madhums** [comment]
having the same issue! :(

**Comment by davidrichardson** [comment]
I am having the same issue with the FAANG organization. I am a public member, but coveralls would not recognise this. Coveralls was authorised for access, but wouldn't display the orgs repos for me. I removed all 3rd party restrictions and can now see the repos, but would prefer to reinstate the restrictions when possible.

**Comment by matteobachetti** [comment]
Hi, I'm having the same problem with an organization repo. I'm publicly owner of the organization.

**Comment by jfklingler** [comment]
Also seeing this problem. This appears to still be an issue a year after being initially reported. Does lemurheavy not pay attention to issues here on GitHub?
