### ISSUE TITLE
PRs: "First build on master"

### ISSUE THREAD

**Issue by hugovk** [lemurheavy/coveralls-public#610]
I've noticed pull requests are no longer reporting coverage against the upstream master.

For example, [this PR](https://github.com/python-pillow/Pillow/pull/1398) says:

> coverage/coveralls — First build on master at 75.972%

This isn't much use. The check used to say how much the coverage had increased or decreased based on the upstream fork.

Is there some new setting or something missing from our repo/Coveralls configuration?

**Comment by julienbaley** [comment]
We're having exactly the same problem, no increase/decrease is reported as coveralls weirdly seem to believe this is the first build on master.

Can we get some help here? We're trying to keep coverage high by having a fail condition on coverage decrease, and those "first builds" break the feature.

**Comment by rwd** [comment]
Same here, on the [1246th build](https://coveralls.io/builds/5185616), making it difficult to enforce coverage.

**Comment by McPringle** [comment]
Still not fixed, the same happens here: This is our [109th build](https://coveralls.io/builds/5560626) but the email says `First build on develop …`

**Comment by dougnukem** [comment]
I'm seeing a similar issue as well. Basically travis-ci "push" builds don't show difference in coverage, but "PR" builds do.

Is there any update is this a bad configuration that we can fix on our projects end?

Project: https://github.com/codingsince1985/geo-golang/
**Language:** Go
**CI:** [Travis-CI](https://travis-ci.org/codingsince1985/geo-golang)
**Coveralls Integration:** [goveralls](https://github.com/mattn/goveralls) and [gover](https://github.com/modocache/gover) to aggregate coverage across multiple packages
  - `goveralls -service=travis-ci -coverprofile=gover.coverprofile`

https://coveralls.io/github/codingsince1985/geo-golang?branch=master

- travis-ci "push" build saying "First build on master X%"
  -  https://coveralls.io/builds/5801075 40th build
- travis-ci "PR"  build shows code coverage diff
  - https://coveralls.io/builds/5788017

**Comment by nickmerwin** [comment]
Hey all, we've deployed a fix for this issue. Could everyone check and confirm?

I'll re-open if not.

Thank you!

**Comment by McPringle** [comment]
I can confirm that the fix worked fine for my last two pushes.

Thank you!

**Comment by homm** [comment]
Hi! We are experiencing the same issue again. https://github.com/python-pillow/Pillow/issues/2060

**Comment by lthur** [comment]
We are experiencing the same issue right now.
It is everything ok?

**Comment by paltman** [comment]
We are experiencing this issue with one of our private repositories.

**Comment by hugovk** [comment]
> Hey all, we've deployed a fix for this issue. Could everyone check and confirm?
>
> I'll re-open if not.

@nickmerwin Please can you re-open this?

**Comment by jessica-pixvana** [comment]
Im having the same issue as @Flamefire
