### ISSUE TITLE
ROSS issues

### ISSUE THREAD

**Issue by laprej** [lemurheavy/coveralls-public#611]
Hi,

The ROSS project (https://github.com/carothersc/ROSS) has been happily using Coveralls for quite some time.  After pulling in some CMake-Coveralls related changes, however, we've been getting the "Couldn't find a repository matching this job." error from curl.  It must have been something in the latest commit (carothersc/ROSS@8b5c9ecb776f7fb72c67f0567a2aa9cfa22af08c) but I can't see any problems with that commit.  Another pair of eyes would be great :)

**Comment by nickmerwin** [comment]
Hi @laprej I just checked -- your GH token has rolled, could you log-out and back in and try the build again?

Closing for now, thanks!

**Comment by laprej** [comment]
I didn't even realize that could happen.  I thought I was going to die with that token ;)  Alas, unfortunately that didn't fix the issue.

**Comment by nickmerwin** [comment]
Ok it may be that your Coveralls post isn't passing along the repo token properly any more. Could you check that config?

Thanks.
