### ISSUE TITLE
Another case of 422 http response

### ISSUE THREAD

**Issue by petemoore** [lemurheavy/coveralls-public#612]
See https://travis-ci.org/taskcluster/slugid.py/builds/78554815#L149

It failed the first time, I retriggered, and got the error again, so it seems to be consistent.

The github repo is enabled in coveralls.

This is a _public_ open-source repo, running from travis-ci.org.

Thanks!

**Comment by nickmerwin** [comment]
hi @petemoore did you disable the Coveralls integration in the meantime? I checked your Github tokens and they're valid now -- they might have been expired at the time you were getting the 422 errors. Could you re-enable and try again?

Thanks!

**Comment by petemoore** [comment]
@nickmerwin I didn't (knowingly) disable the integration. To me it looks like the repo is enabled in coveralls now, but when I rebuilt in travis, I still get the same failure. Here is the one I just ran:

https://travis-ci.org/taskcluster/slugid.py/builds/78554815#L148

Thanks,
Pete

**Comment by petemoore** [comment]
@nickmerwin still no change, I just tried again today:

https://travis-ci.org/taskcluster/slugid.py/builds/78554815#L151

Are there any problems with the account?

**Comment by petemoore** [comment]
@nickmerwin I tried again.... Still no change. :/

https://travis-ci.org/taskcluster/slugid.py/builds/91784410#L154

This time instead of just rebuilding, I even pushed a new commit, but it didn't help.

**Comment by petemoore** [comment]
@nickmerwin Is this something you can help me with? Many thanks in advance.

**Comment by petemoore** [comment]
@nickmerwin is there anyone else that can help me here? This seems to be a coveralls problem, and has now been open for 5 months. :(

**Comment by nickmerwin** [comment]
Hi @petemoore apologies this has been lingering for so long!

Looking at your last successful build (https://travis-ci.org/taskcluster/slugid.py/builds/104944842#L161), it appears there's another issue:

``` "Couldn't read '%s' as a config file" % config_file
coverage.misc.CoverageException: Couldn't read '/home/travis/build/taskcluster/slugid.py/.coveragerc' as a config file```

Could there be a new configuration issue for your Coveralls integration library?

**Comment by petemoore** [comment]
Thanks @nickmerwin! No worries at all, and thanks for highlighting the new issue. Indeed the previous issue seems to be resolved now, which is great. :smiley:
