### ISSUE TITLE
repo_token does it need to be public?

### ISSUE THREAD

**Issue by gajus** [lemurheavy/coveralls-public#614]
If I do not add `repo_token` to https://github.com/gajus/react-css-modules/blob/master/.coveralls.yml then my [travis-ci tests fail with an error](https://travis-ci.org/gajus/react-css-modules/jobs/79041532):

```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

However, the documentation says it should not be made public.

How to configure coveralls to work with travis-ci?

**Comment by nickmerwin** [comment]
@gajus you should be able to omit your `.coveralls.yml` file completely since you're using free travis. Could you try that?

Thanks!

**Comment by gajus** [comment]
Thats the first thing I have tried.

```sh
$ rm -f ./.coveralls.yml
$ cat ./coverage/lcov.info | ./node_modules/.bin/coveralls -v
[warn] "2015-09-09T07:19:07.806Z"  'Repo token could not be determined.  Continuing without it.This is necessary for private repos only, so may not be an issue at all.'

/Users/gajus/Documents/dev/gajus/react-css-modules/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by gajus** [comment]
@nickmerwin If this is a bug, then this issue should be open.

**Comment by gajus** [comment]
@nickmerwin ping

**Comment by gajus** [comment]
Related https://github.com/nickmerwin/node-coveralls/issues/93.

**Comment by gajus** [comment]
https://github.com/nickmerwin/node-coveralls/issues/93#issuecomment-140719973
