### ISSUE TITLE
"SOURCE NOT AVAILABLE" even though I've reauthorized

### ISSUE THREAD

**Issue by sbromberger** [lemurheavy/coveralls-public#615]
I keep getting

SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

and I've tried pretty much everything but deleting my coveralls repos and starting over: I've revoked and re-granted coveralls access, and I've logged out and in on both Coveralls and GitHub. I've tried these tasks in different orders; nothing seems to fix this issue.

What am I missing here?

**Comment by nickmerwin** [comment]
Hi @sbromberger could you link me to the repo you're having this issue with?

Thanks!

**Comment by sbromberger** [comment]
https://coveralls.io/builds/3513213 is the build, and https://github.com/JuliaGraphs/LightGraphs.jl is the repo.

**Comment by nickmerwin** [comment]
@sbromberger ok you should be able to access it now. Let me know, thanks!
