### ISSUE TITLE
Pull Request comments no longer working

### ISSUE THREAD

**Issue by peterbe** [lemurheavy/coveralls-public#617]
I used to have it working on github.com/mozilla/airmozilla. Every PR would get a comment by the coveralls bot about the ups or downs. 

I most definitely have it enabled
![screenshot 2015-09-11 11 34 12](https://cloud.githubusercontent.com/assets/26739/9823096/121c22ec-5879-11e5-9ef7-9f230027a52d.png)
But clearly it's not working. 

The FAQ has no information about it.

**Comment by GeneticGenesis** [comment]
So I've seen the status API fail repeatedly. The communication I've had with Coveralls' support suggested it uses the users github oauth token to communicate or comment, and that token is frequently rotated.

I found re-authorising with github would fix issues for a while, and then it would break again.

**Comment by peterbe** [comment]
@GeneticGenesis I've seen that too. I often have PRs wait forever on coveralls even after Travis has finished running tests. 

However, that's unrelated to coveralls's bot posting a PR comment.

**Comment by liry** [comment]
I've got the same problem. No error message anywhere. It's frustrating :(
