### ISSUE TITLE
Coveralls thinks there are no changes, but there are

### ISSUE THREAD

**Issue by drivet** [lemurheavy/coveralls-public#620]
I'm working on this repo:

https://coveralls.io/github/drivet/yawt

My latest changes bumped the coverage by a couple of percent (according to the output of travis ci), but although coveralls sees the new commit, it seems to think that there are no changes. This appears to be a bug.

**Comment by ns3777k** [comment]
Got similar problem. I'm not seeing new commits at all on repo's dashboard or right panel. If I check jobs it says nothing actually changed, but there are changes (~10%).
Didn't have this problem yesterday.
(https://github.com/ns3777k/go-shodan)

**Comment by starcraftman** [comment]
There seems to be some problem on coveralls receiving the data. I run the report command at the end of the tests and that looks fine. I've noticed this started 4 days ago for me.

For some, I get a 503 error on submit: [see bottom](https://travis-ci.org/starcraftman/pakit/jobs/80314687)
Other times they show as submitted but garbage output: [travis](https://travis-ci.org/starcraftman/pakit/jobs/80344598) [coveralls](https://coveralls.io/jobs/8297961)
Also, just like ns3777k I do not see the builds listed at the right or properly on the front of my repo page on coveralls.

I was just starting to get used to having coveralls, a bit disappointing.

**Comment by starcraftman** [comment]
Seems like this morning the coveralls site is properly reporting branches I pushed while down (except the 503 ones). New ones are showing up promptly.

@ns3777k & @drivet check if you are also fixed, if so guess we can close this issue.

**Comment by ns3777k** [comment]
@starcraftman works for me. thx

**Comment by drivet** [comment]
Indeed, things seem okay now.
