### ISSUE TITLE
Paid for Pro account, but now it is gone?

### ISSUE THREAD

**Issue by dylangrafmyre** [lemurheavy/coveralls-public#621]
Hello, 

I signed up and paid for a pro account https://coveralls.io/github/shakacode/ today. The owner of the github org. approved access for coveralls. The repo was synced and updating.

However, after logging back in, coveralls wanted me to re-authorize github and the paid org is missing, but the synced repo is still there https://coveralls.io/github/shakacode/react-webpack-rails-tutorial with all the build data missing. 

I do I rectify this issue?

Thanks,
Dylan

**Comment by nickmerwin** [comment]
hi @dylangrafmyre it looks like your Github OAuth token isn't able to access the Shaka Code organization's repos.

Could you try revoking access (https://github.com/settings/applications) and signing in again through this link?

https://coveralls.io/refresh?private=true

Thanks!

**Comment by dylangrafmyre** [comment]
@nickmerwin Thank you! This issue is resolved.

**Comment by nickmerwin** [comment]
Great, cheers!
