### ISSUE TITLE
Source on public repo not available except to owner

### ISSUE THREAD

**Issue by mtlynch** [lemurheavy/coveralls-public#623]
I mentioned this on #596 but it seems like that issue might be buried since it's closed now.

I have this public repo:

https://github.com/m-lab/telescope
https://coveralls.io/github/m-lab/telescope

If I'm signed in with my Github credentials, I can see [line-level coverage](https://coveralls.io/builds/3516151/source?filename=telescope%2Fquery.py), but when I'm not signed in, Coveralls shows this:

``````
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.```
``````

How can I let Coveralls display the source to users who aren't signed in? The source is public, so Coveralls shouldn't need any special permissions to retrieve it from Github.

**Comment by tldavies** [comment]
We have this problem to. We would want our open source repos to see line-level coverage.

**Comment by sbts** [comment]
We also have this issue.
As one of the other devs said....
"That's ... stupid"

Is there any indication when this may be fixed?

**Comment by zakhenry** [comment]
Having the same issue, but it's not necessarily an issue with open source projects, see https://coveralls.io/builds/5964299/source?filename=src%2Frenderers%2Fdom%2Fclient%2FReactDOMSelection.js for an example of a React file.

Tried all the tricks in #375 but still no dice. My offending repo: https://coveralls.io/builds/7071966/source?filename=..%2Fsrc%2Fcommon%2Fservices%2Flogger.service.ts

**Comment by Bilge** [comment]
Also have this problem except it doesn't even show up for owner any more, either.

**Comment by nickmerwin** [comment]
@Bilge could you link me to the url?

**Comment by Bilge** [comment]
@nickmerwin https://coveralls.io/builds/21868698/source?filename=src/ExponentialBackoffExceptionHandler.php

**Comment by nickmerwin** [comment]
Thanks @Bilge ok this is fixed, I'm closing the issue for now.

**Comment by Bilge** [comment]
Thanks @nickmerwin. Good to see someone is still keeping this project alive.
