### ISSUE TITLE
Getting 422 error.

### ISSUE THREAD

**Issue by whitneyit** [lemurheavy/coveralls-public#625]
I have received a email in regards to this but that was over 2 weeks ago. I spoke with Nick Merwin.

This is an issue with a pro account and I have been waiting almost a month for a response. Can we please esculate this?

The zendesk request is 475.

**Comment by nickmerwin** [comment]
Hi @whitneyit I've replied to the zendesk request. Since it's re: a private repo lets keep the discussion going there.

Thank you!

**Comment by whitneyit** [comment]
@nickmerwin Can you please have another look at that ticket. It's getting dire
