### ISSUE TITLE
Coveralls won't detect travis

### ISSUE THREAD

**Issue by WoLpH** [lemurheavy/coveralls-public#626]
https://travis-ci.org/WoLpH/django-admin-generator/jobs/81219127

The message I'm getting:
```
coveralls runtests: commands[2] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis
ERROR: InvocationError: '/home/travis/build/WoLpH/django-admin-generator/.tox/coveralls/bin/coveralls'
___________________________________ summary ____________________________________
ERROR:   coveralls: commands failed
```

Anyone got an idea of what is wrong here?
I have a very similar setup for a different project and that works without an issue.
https://travis-ci.org/WoLpH/django-tags-input

**Comment by JASchilz** [comment]
I had a similar problem. I was able to solve it by applying the instructions in 78c32393194ee499f380905a3919b0810c0eed4e, as provided in #73.

My [tox.ini](https://github.com/InterSIS/django-rest-encrypted-lookup/blob/master/tox.ini) shows the env passthrough commands.

**Comment by WoLpH** [comment]
Brilliant, that solves the issue @JASchilz :)

For future reference, having somethong along the lines of this in your `tox.ini` should solve the issue:

```
[testenv:coveralls]
commands =
    pip freeze
    python setup.py test
    coveralls

deps = coveralls
```
