### ISSUE TITLE
Repo Access Denied

### ISSUE THREAD

**Issue by hallucinogen** [lemurheavy/coveralls-public#628]
Hi there,

I have this repo on coveralls

https://github.com/ParsePlatform/Parse-SDK-dotNET
https://coveralls.io/github/ParsePlatform/Parse-SDK-dotNET

It was in paid plan since we need to put the repo on private for few days. But then when we open the repo to public and cancel the plan (since it's a public repo now), I keep getting access denied / repo doesn't exist. Anyone having similar problem? Do you know the fix for this?

Thanks!

**Comment by nickmerwin** [comment]
Hi @hallucinogen ok I've sync'd the repo's info, it's public now:

https://coveralls.io/github/ParsePlatform/Parse-SDK-dotNET

You weren't able to access it since you canceled the subscription.

Thanks!

**Comment by hallucinogen** [comment]
That was quick. Thank you very much!
