### ISSUE TITLE
Can't find repo on magnum.travis.com

### ISSUE THREAD

**Issue by alyssa-kwan-cloverhealth** [lemurheavy/coveralls-public#629]
I'm on a Trial with a repo I'm testing out. I'm building with magnum.travis.com, which I assume is `service_name: travis-pro`. I run pytest with pytest-cov through Tox, setting the working directory to `tests/`. I run `coveralls` in the same Tox env in the same directory. I've tried putting the `.coveralls.yml` file with the `repo_token` in both the root of the repo and in the `tests/` directory. I've also tried deleting and re-enabling the repo on coveralls, and tried with both tokens. No joy.

**Comment by alyssa-kwan-cloverhealth** [comment]
Perhaps related to #627? I had a brief issue, even before setting the ``.coveralls.yml``, of test results going to someone else's repo.

**Comment by alyssa-kwan-cloverhealth** [comment]
Remembered what happened with the cross-over issue. The TRAVIS env vars are set, and forwarded via Tox. I had no ``.coveralls.yml`` at the time. Just now, I tried setting the ``.coverage.yml`` to __not__ have the ``repo_token``, hoping it would pick up the ``TRAVIS_JOB_ID``. It did. I ended up sending test results to someone else's repo again. A different one this time (probably because before ``service_name`` was not set at all, so it was mapped to Travis open source and not Travis Pro).

This seems like a pretty serious namespace collision issue. Did something change upstream in Travis?

**Comment by CJ-Wright** [comment]
Yes this is related to #627

**Comment by nickmerwin** [comment]
hi @alyssa-kwan-cloverhealth and @CJ-Wright it sounds like the `service_name: travis-pro` section of .coveralls.yml isn't getting picked up the Python integration library properly. Could one of you paste the pertinent sections of your Travis build output?

**Comment by alyssa-kwan-cloverhealth** [comment]
Sure. I'm running it from Tox. What's the CL args to maximize verbosity for the output? I get a total of 3 lines now.

**Comment by nickmerwin** [comment]
hey @alyssa-kwan-cloverhealth as long as you don't have `COVERALLS_SILENT = true` then it will be default log the config used for posting coverage data to our API.

**Comment by matthewwill** [comment]
Having this issue as well with a private repository. Was first receiving the "Couldn't find a repository matching this job. 'url'" referenced in #627. Now after regenerating the token it's submitting the results to a different project.

**Comment by alyssa-kwan-cloverhealth** [comment]
Hi, @nickmerwin. Sorry for the late reply. I'm using Tox. ``COVERALLS_SILENT`` is unset; Tox crashes because it's not in the Travis env when I try to reference it in the ``tox.ini``. To be clear, I'm using ``coveralls==1.0``, not ``python-coveralls``. There is a total of 4 lines of output. As of right now, runs are successful, but are hitting random repos that belong to others.

Given the lack of account/user/organization level isolation in coveralls (I find this design choice or lack thereof bewildering), I feel very uncomfortable live debugging, so I'm going to bow out and try to find another service.

**Comment by matthewwill** [comment]
I'd like to second alyssa's response above. The fact that private repository information is being posted to public projects is unacceptable. We as well have discontinued use of this service.

**Comment by CJ-Wright** [comment]
@nickmerwin I am not certain what parts of the travis output you consider pertinent but here is the coveralls section
```
0.78s$ coveralls

Submitting coverage to coveralls.io...

Coverage submitted!

Couldn't find a repository matching this job.

'url'
``` 

and here is the coveralls pip install
```
pip install coveralls

Collecting coveralls

  Downloading coveralls-1.0-py2.py3-none-any.whl

Collecting docopt>=0.6.1 (from coveralls)

  Downloading docopt-0.6.2.tar.gz

Collecting coverage>=3.6 (from coveralls)

  Downloading coverage-4.0.tar.gz (166kB)

    100% |████████████████████████████████| 167kB 1.6MB/s 

Collecting requests>=1.0.0 (from coveralls)

  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)

    100% |████████████████████████████████| 471kB 703kB/s 

Building wheels for collected packages: docopt, coverage

  Running setup.py bdist_wheel for docopt

  Complete output from command /home/travis/mc/envs/testenv/bin/python -c "import setuptools;__file__='/tmp/pip-build-ATP0Lz/docopt/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpWFMlgCpip-wheel-:

  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

     or: -c --help [cmd1 cmd2 ...]

     or: -c --help-commands

     or: -c cmd --help

  

  error: invalid command 'bdist_wheel'

  

  ----------------------------------------

  Failed building wheel for docopt

  Running setup.py bdist_wheel for coverage

  Complete output from command /home/travis/mc/envs/testenv/bin/python -c "import setuptools;__file__='/tmp/pip-build-ATP0Lz/coverage/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpOIza_hpip-wheel-:

  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

     or: -c --help [cmd1 cmd2 ...]

     or: -c --help-commands

     or: -c cmd --help

  

  error: invalid command 'bdist_wheel'

  

  ----------------------------------------

  Failed building wheel for coverage

Failed to build docopt coverage

Installing collected packages: docopt, coverage, requests, coveralls

  Running setup.py install for docopt

  Running setup.py install for coverage

Successfully installed coverage-4.0 coveralls-1.0 docopt-0.6.2 requests-2.7.0
```
Please fix this problem ASAP, I like your service but private repos are supposed to remain private.

**Comment by CJ-Wright** [comment]
@nickmerwin Update: I changed from coveralls to python-coveralls and it now seems to be putting the coverage in the correct position.  Although it has the wrong commit message and committed by line:
```COMMITED BY
Forrest Oliphant	
COMMIT MESSAGE
loopback edge control points further out https://github.com/noflo/noflo-ui/issues/53#issuecomment-44077225```

So something weird may still be happening between coveralls and their python APIs.

**Comment by duedal** [comment]
If you are using tox + travis-pro to run your tests, make sure it's tox that runs the `coveralls` command. This fixed the issue for me.
