### ISSUE TITLE
Coveralls returns 422 error: Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by vcernomschi** [lemurheavy/coveralls-public#632]
Steps to reproduce:
1. Generate coverage report by using istanbul.
2. Send lcov.info file to coveralls.io by using: 

cat ${__COVERAGE_PATH}"/lcov.info" | coveralls

where __COVERAGE_PATH  valid path to coverage report.

Expected result: lcov.info file is successfully downloaded. 

Actual result: 
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by vcernomschi** [comment]
[lcov.txt | uploaded via ZenHub](https://files.zenhub.io/5613fdb845697ff42980eec6)

**Comment by eistrati** [comment]
I am experiencing the same issue. Can anyone help?

**Comment by avozicov** [comment]
I have the same issue for public repos.

**Comment by vcernomschi** [comment]
The issue is still reproducible for all public repos.

**Comment by devs-deep** [comment]
The issue is still reproducible for all public repos.

**Comment by nickmerwin** [comment]
@vcernomschi @devs-deep @avozicov @eistrati there are a couple causes for this:

1) if you're using Travis, you don't need to specify a repo token, but your Github OAuth token must be valid -- try logging out / in on Coveralls.io to refresh it
2) on other CI's you have to specify a repo token; check your environment variables at build time to be sure `COVERALLS_REPO_TOKEN` is being set

Let me know how it goes!

**Comment by vcernomschi** [comment]
The issue is not reproducible anymore after removing coveralls token

**Comment by ad-m** [comment]
I have this issues to in public coveralls repo.
Here is travis build log: https://travis-ci.org/watchdogpolska/poradnia/jobs/124069972
Here accordinly travis.yml: https://github.com/watchdogpolska/poradnia/commit/2061f2ec5abdcdc1cfaf182f4471fa3a8eec36b2

**Comment by Jarvin-Guan** [comment]
I got the error
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

link:https://travis-ci.org/Jarvin-Guan/arg-parser/jobs/126830328

**Comment by kienpham2000** [comment]
Deleting the repo inside coveralls.io and add it back works for me, you will loose your coverage history though.

**Comment by kasora** [comment]
I forgot to add .coveralls.yml. It works for me now.

**Comment by p8ul** [comment]
*Set up for JavaScript Coveralls*
Login to coveralls and add your enable your repository. 
Click on details and show you instructions on how to configure .coveralls.yml file

Here are some quick instructions for this JavaScript project:
 add the following line to your .coveralls.yml :

``` repo_token: your_token_goes_here ```

**Comment by PaulRBerg** [comment]
Just for the record, this also happens when you change the repo's name. Deleting, resyncing and toggling did the trick in my case.

**Comment by aleclarson** [comment]
I tried using the free TravisCI Github app (which might be Travis Pro?), and Coveralls doesn't like it, even after adding a `.coveralls.yml`. I've tried deleting the Coveralls repo, disabling TravisCI and re-enabling via the "Legacy Services Integration" page. Next I guess I'll try renaming the Github repo. 😢

**Comment by msangel** [comment]
the error message is very not informative, please make it better
so
for getting it work on public repo I had to do 2 things:
1) add empty .coveralls.yml file to repo
2) push **because it not working from local pc, only from within travis-ci**

**Comment by ElliotNB** [comment]
I had this same issue as well for an open source project. I did not need to add an empty `.coveralls.yml`, but I did need to log in and out of Coveralls.io with my GitHub account a couple of times and disable/re-enable the GitHub apps integration.

**Comment by youtux** [comment]
Same issue here

**Comment by fishcharlie** [comment]
This is happening to me as well. For some reason restarting the builds seems to work most of the time. Any idea how to fix this?

**Comment by davedoesdev** [comment]
Same here except restarting the build doesn't work, nor removing and adding the project in coveralls.io.
https://travis-ci.org/davedoesdev/browser-http2-duplex/builds/495194847

**Comment by leakingtapan** [comment]
Same here https://travis-ci.org/aws/aws-fsx-csi-driver/builds/495534059

**Comment by gregnb** [comment]
I'm affected by this as well https://travis-ci.org/gregnb/mui-datatables

**Comment by nickmerwin** [comment]
Hi all, we've identified this as an intermittent Travis API failure and are working on a solution.

**Comment by nickmerwin** [comment]
Hi everyone, turned out we had our webserver IPs accidentally blacklisted by Travis, so we couldn't query their API to get job info as coverage data was posted.

Apologies for the gap in service here! We're adding failsafes to warn us early about this in the future.

**Comment by analog-nico** [comment]
Thanks a lot @nickmerwin ! Works like a charm again.

**Comment by marcj** [comment]
I get it again :O
https://travis-ci.com/marcj/marshal.ts/jobs/184281038
Any idea?

**Comment by nickmerwin** [comment]
Hi @marcj could you re-run your build with the `--verbose` flag added to Coveralls?

**Comment by marcj** [comment]
It worked a couple of hours later. 👍

**Comment by ViceIce** [comment]
same here

**Comment by kowalk** [comment]
same here: https://travis-ci.org/jorge07/symfony-4-es-cqrs-boilerplate/builds/542196995

```
Collect git info
Read environment variables
Dump submitting json file: /app/build/logs/coveralls-upload.json
File size: 104.94 kB
Submitting to https://coveralls.io/api/v1/jobs
Client error occurred. status: 422 Unprocessable Entity
Couldn't find a repository matching this job.
```

**Comment by piersb** [comment]
Same problem here.

**Comment by boolafish** [comment]
Might be same issue on our open source project: https://app.circleci.com/jobs/github/omisego/plasma-contracts/4631

**Comment by fllprbt** [comment]
I 've resynced
I 've added empty .coveralls.yml
I 've deleted repo and revoked github permissions

Nothing has worked yet... --verbose output:
```
[debug] "2019-10-28T09:11:47.722Z"  'user options undefined'
[warn] "2019-10-28T09:11:47.726Z"  'Repo token could not be determined.  Continuing without it.This is necessary for private repos only, so may not be an issue at all.'
[debug] "2019-10-28T09:11:47.734Z"  { run_at: '2019-10-28T09:11:47.723Z',
  git:
   { head:
      { id: '327d115637167ede478d2585d85e23972f73b8b8',
        committer_name: 'Unknown Committer',
        committer_email: '',
        message: 'Unknown Commit Message',
        author_name: 'Unknown Author',
        author_email: '' },
     branch: '',
     remotes: [] } }
[debug] "2019-10-28T09:11:47.736Z"  'in: ' ''
```

There is another [debug] entry with info from the lcov.info but dunno if it's of any use.

**Comment by jfoclpf** [comment]
I have also a public repo and I was getting that error. Nonetheless I added the file `.coveralls.yml` to my project root directory with the information:

```
service_name: travis-pro
repo_token: **your token**
```
 and it did work. Mind that the token must not be public and thus you have to add this file to `.gitignore`

**Comment by rook2pawn** [comment]
is this still an oustanding issue? I am still getting 


    Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by wbaldoumas** [comment]
I started getting this `##[error]Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}` error as of today on all of my repositories.

To test, I also re-ran an old build on a repository that hasn't had any code changes and got the same error. Any solution here?

**Comment by jasonwaters** [comment]
@itabaiyu same here, must be a coveralls issue? I didn't change anything about my configuration recently.  I'm using github actions.

**Comment by mrspartak** [comment]
Same as @jasonwaters. Just begun to get this error too

**Comment by transmissions11** [comment]
@jasonwaters Same here. Using the Github Action that just requires you to use your GIHTUB_TOKEN (not one provided by Coveralls) and it's not working?


**Update: No longer having this issue, it just resolved itself.**

**Comment by transmissions11** [comment]
Looks like this may be an issue with Github right now: https://www.githubstatus.com/

**Comment by ndelvalle** [comment]
I also have this issue today:
```
Bad response: 422 {"message":"service_job_id (340775507) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
```

**Comment by detrin** [comment]
I also have this issue today, yesterday there was no issue 
```
{"message":"Couldn't find a repository matching this job.","error":true}""")
```
See Github Actions of OpenQuantumSystems.jl https://github.com/detrin/OpenQuantumSystems.jl/runs/1431278845?check_suite_focus=true. I temporarily added `continue-on-error: true` to .yml files.

**Comment by Adadie** [comment]
> @vcernomschi @devs-deep @avozicov @eistrati there are a couple causes for this:
> 
> 1. if you're using Travis, you don't need to specify a repo token, but your Github OAuth token must be valid -- try logging out / in on Coveralls.io to refresh it
> 2. on other CI's you have to specify a repo token; check your environment variables at build time to be sure `COVERALLS_REPO_TOKEN` is being set
> 
> Let me know how it goes!

This worked out for me, also check if the .coveralls.yml file is not in gitignore. Though I'm not sure if it's not dangerous to expose your repo token

**Comment by Icaruk** [comment]
My problem was that i added `coveralls.yml` instead `.coveralls.yml`.
I forgot the dot prefix.
