### ISSUE TITLE
"Source Not Available" with public source

### ISSUE THREAD

**Issue by daleharvey** [lemurheavy/coveralls-public#633]
Not entirely sure how coveralls is trying to find the files, for PouchDB we see no source files ever

https://coveralls.io/builds/3785522/source?filename=..%2Flib%2Fdeps%2FfunctionName.js is an example

https://github.com/pouchdb/pouchdb/blob/master/lib/deps/functionName.js is where that file is

**Comment by nolanlawson** [comment]
Looks like it's because we put the coverage report into the `coverage/` directory, so the path is relative to that? Maybe we need to just dump it into the root directory.
