### ISSUE TITLE
Wrong changed files reported

### ISSUE THREAD

**Issue by warden** [lemurheavy/coveralls-public#634]
Looking here:
https://coveralls.io/jobs/8855372 shows totally different files that the git commit:
https://github.com/jenkinsci/jira-plugin/compare/da1ae78b723a...dec02b839246
Any ideas why that may happen?

**Comment by paddor** [comment]
+1

**Comment by warden** [comment]
Same here: https://coveralls.io/builds/4680080

**Comment by warden** [comment]
See also #463

**Comment by Gnafu** [comment]
I'm experiencing the same issue. We are using cobertura and the html-report shows the correct lines, but once the results are uploaded to codacy they don't match anymore.
https://coveralls.io/builds/9234326

**Comment by smur89** [comment]
Also having this issue with out builds, causes a problem for us as we get some files decreasing coverage, despite having been touched. We fail our build if the coverage decreases by any %.

Any update or resolution to this issue?

**Comment by Gnafu** [comment]
I was able to fix my issue (wrong lines being reported) by instrumenting the code *before* any transpiling.
I work with Javascript so Babel/Istambul.
I don't know if java users having the same issue are using some tool to refactor the code at compile time (Dependency Injection frameworks?)

There is still an issue with totally unrelated files (no coverage change) that are still reported as "modified" with a reported coverage change
