### ISSUE TITLE
Source of public repo not available

### ISSUE THREAD

**Issue by danieldietrich** [lemurheavy/coveralls-public#635]
Hi @nickmerwin,

I invested hours now to get access via coveralls.io to my source - without success. I need your help!

My github account was converted to an organization: http://github.com/javaslang

I enabled 'access restrictions' but coveralls is listed as _approved_ (in the organization settings).

However, the line source code is not shown when I click on a file at coveralls.io. Example: https://coveralls.io/builds/3801923/source?filename=src%2Fmain%2Fjava%2Fjavaslang%2Fcontrol%2FMatch.java

How can that be with a public repo where the source is public visible??

However, when I log in with the repo owner, all is fine - i.e. I can open sources and read line coverage.

I've already has a look at similar issues here but can't get it work.

Do you have a hint?

Many thanks!

Daniel

**Comment by nickmerwin** [comment]
hi @danieldietrich it looks like your GH tokens have rolled -- could you log out and back in?

**Comment by danieldietrich** [comment]
Great, thx for the fast reply!!

**Comment by nickmerwin** [comment]
Done! Now when non-logged in users view source, it will use your user's tokens to retrieve the source.

(We have to use the repo owner's tokens to keep our own from being rate-limitted)

Thanks, and happy covering!

**Comment by danieldietrich** [comment]
Thanks, awesome :-)
