### ISSUE TITLE
Docs access

### ISSUE THREAD

**Issue by dylangrafmyre** [lemurheavy/coveralls-public#637]
Why would i have to sign into the docs when already authenticated via my github account? This makes no sense? I really need to look at the documentation without creating a new sign up with coveralls.

Thanks
Dylan

**Comment by nickmerwin** [comment]
Hey thanks for pointing that out @dylangrafmyre -- fixed!

**Comment by dylangrafmyre** [comment]
@nickmerwin Thank you so much for the quick response! Awesome!
