### ISSUE TITLE
Can't change branch

### ISSUE THREAD

**Issue by whitneyit** [lemurheavy/coveralls-public#641]
Coveralls is not detecting changes pushed to `develop`. It only shows `master`

Re: The zendesk ticket 475.

**Comment by CJ-Wright** [comment]
This might be related to #629 and #627 I am having a similar problem, When I push to master everything is ok, but I am getting a `NFO:coveralls:{"message":"Couldn't find a repository matching this job.","error":true}` on anything that is on a branch
