### ISSUE TITLE
Commit message body and title are shown on one line

### ISSUE THREAD

**Issue by davidvuong** [lemurheavy/coveralls-public#646]
<img width="1119" alt="screenshot 2015-10-25 16 41 10" src="https://cloud.githubusercontent.com/assets/1312550/10714214/3d151dce-7b37-11e5-9b87-8cb4825a030f.png">

I've recently started using coveralls, and I think the service is great. I just have one problem with how commit messages are displayed (ref screenshot). The commit message body seems to be mashed into the message title in the list view (as well as the last commit on the right side-bar).

When I click on the commit (https://coveralls.io/builds/3941689), the title and body are correctly formatted so I don't think it's the way I had formatted the original commit message. Is it possible to only display the title of the comment message and not the body?

**Comment by jnpkrn** [comment]
At least `Signed-off-by` lines (and similar) should be omitted in such
a compressed overview, IMHO.
