### ISSUE TITLE
Public repository details is not available

### ISSUE THREAD

**Issue by vcernomschi** [lemurheavy/coveralls-public#648]
Valid public repository is not available (https://coveralls.io/github/MitocGroup/deep-microservices-root-angularjs).

Steps to reproduce:
1. Open "https://coveralls.io/repos".
2. Check the mentioned repository exists and enabled in coverall.
3. Click on details button

Expected result: Repository details is displayed
Expected result: Error page is displayed instead of repository details

**Comment by eistrati** [comment]
+1
Tried as owner or admin, from multiple accounts, still nothing works.

**Comment by Lourenc** [comment]
+1

**Comment by avozicov** [comment]
+1 I have the same issue

**Comment by dsasov** [comment]
+1
I am experiencing the same issue
