### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by icot** [lemurheavy/coveralls-public#653]
Hello, 
Where can I modify the  'repo root directory' configuration parameter? On the _.coverals.yml_ file?
I'm getting the following kind of messages when trying to access the source code:

`The file "PATH/TO/FILE" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.`

This is actually true, as the right path would be 'src/PATH/TO/FILE' relative to the root (after cloning) of the repository but I don't seem to find where this can be changed.

Thank you!

**Comment by paddor** [comment]
I get the same error, but for a file in a DIFFERENT repository. So I don't even want that filename to show up in coveralls.

**Comment by llogiq** [comment]
I also get the same error.
