### ISSUE TITLE
History trend chart not displaying correctly

### ISSUE THREAD

**Issue by pklock** [lemurheavy/coveralls-public#654]
I am having trouble displaying the repository history trend graph from the **REPOS** tab. We definitely have 'trends' that should be showing up (both increased and decreased coverage), but the background stays blank when we click on the **branch** name, i.e. *develop* in the following image:

![Missing Trend](https://i.imgur.com/GPK9rGa.png)

***
However, I noticed that if go into developer tools and disable the `display: none;` tag, the trend chart is properly displayed.

![Trend Div](https://i.imgur.com/VozgbcT.png)

![Trend Shown](https://i.imgur.com/LUOzUy0.png)

***
The history trend should be visible all the time when only 1 branch available, and I should have the ability to switch between graphs when there are multiple branches.

**Comment by dannil** [comment]
Also having this problem, but only with newly created repositories. Any information on this?

**Comment by pklock** [comment]
We never heard any response on this issue. A few weeks after this was posted, they magically started to appear. We now see trends for up to 2 branches (can't choose which branches though, looks like the last 2 'committed to' brances) on the main repos page.

Closing my issue for now, you should open a new one if you have more specific information on what and when trends show up for you.
