### ISSUE TITLE
Build not removed from build list after deleting

### ISSUE THREAD

**Issue by mrbroll** [lemurheavy/coveralls-public#655]
One of my colleagues accidentally pushed his coverage info from a different repo to my repo. I deleted the build using the delete button on the build detail page, but when going back to the latest builds list, it still shows up in the list and the link sends me to a 404.

**Comment by eyal0** [comment]
I'm seey this error, too, when trying to delete large branches.

I accidentally pushed coverage with over 10000 files. When I try to delete the branch, the website times out. The delete doesn't work. Deleting small builds works fine.

I was able to delete by deleting the entire repository from coveralls and then starting it again. That deleted all the builds.

Maybe there is a query that is running too long during the delete?
