### ISSUE TITLE
Libsass not getting comments!

### ISSUE THREAD

**Issue by hcatlin** [lemurheavy/coveralls-public#658]
Hey Coveralls people!

@xzyfer and myself are trying to figure out why sass/libsass PR's aren't getting coveralls comments anymore! Like, this build: https://coveralls.io/builds/4063805 didn't comment at all on the PR here: https://github.com/sass/libsass/pull/1699

After knocking around for a while... can't figure it out.

Halp?

**Comment by nickmerwin** [comment]
Hi @hcatlin, I noticed your OAuth token is no longer valid, could you logout and back into Coveralls?

We use that token for posting to GH's status API on your behalf. After that you could re-trigger the build on Travis to test.

Closing for now, let me know!
