### ISSUE TITLE
Hipchat notification displays wrong % change and total % covered

### ISSUE THREAD

**Issue by jwg2s** [lemurheavy/coveralls-public#660]
![image](https://cloud.githubusercontent.com/assets/832769/11098253/c7c5d778-8871-11e5-9cc9-032d0bbd9b63.png)

![image](https://cloud.githubusercontent.com/assets/832769/11098279/d7d049fa-8871-11e5-9dfc-6a5260bf983e.png)

Coveralls notifies hipchat with the wrong percentage change for the branch mentioned.

**Comment by dhanson358** [comment]
I have this same issue, but dramatically wider differences.  

![image](https://cloud.githubusercontent.com/assets/545837/12901878/7db5a246-ce83-11e5-8fef-f51cf624a8ae.png)

![image](https://cloud.githubusercontent.com/assets/545837/12901893/8bb6fa02-ce83-11e5-9642-37656dce5711.png)

Running simplecov locally, the coverage in the web UI seems to be right (50.76% in this case), but the message getting pushed to Hipchat is way off.
