### ISSUE TITLE
"coverage pending from Coveralls.io" on our pull requests.

### ISSUE THREAD

**Issue by bkon** [lemurheavy/coveralls-public#661]
Repository in question is https://github.com/range-me/range-me

**Comment by FaridW** [comment]
This has been going on with our repository for a couple of days now. All our builds are showing that message.

The last build that reported coverage successfully: https://coveralls.io/builds/4150167.json
The first build that did not report coverage: https://coveralls.io/builds/4151069.json

We are not getting any output when we send coverage data through (via the npm module), please let us know if there's anything else we can do to help diagnose and resolve the problem we're having here.

**Comment by gund** [comment]
+1. Sending coverage reports from Travis CI with no output.

Coverage build: https://coveralls.io/builds/8146543
Travis build: https://travis-ci.org/gund/ng2-http-interceptor/builds/164354601

Sending in lcov format.
Any help to diagnose will be appreciated. Thanks.

**Comment by rmjarvis** [comment]
+1.  This started happening for the GalSim repo starting about a week ago (9/27/2016) both on master (e.g. https://github.com/GalSim-developers/GalSim/commit/51f315eac00992afe087f755973c9ff67892ce49) and in PRs (e.g. https://github.com/GalSim-developers/GalSim/pull/798) 

Every check recently says: "Coverage pending from Coveralls.io", and if I click through to the [Coveralls page](https://coveralls.io/builds/8159258), it shows no source files listed. "No data available in table".

The [Travis build](https://travis-ci.org/GalSim-developers/GalSim/builds/164643861) claims it is sending the data to Coveralls.  In the after_success section, it outputs:
```
Submitting coverage to coveralls.io...
Coverage submitted!
Job #268.1
https://coveralls.io/jobs/18796702
```
Is there anything wrong on our end?  Or is this a Coveralls bug?

**Comment by gund** [comment]
@rmjarvis, I just switched from coveralls to codecov without any other changes in how I generate reports and it immediately started to collect my report data.

So it seems like they have some issues with processing data.
