### ISSUE TITLE
Another Organization Repo Sync Issue

### ISSUE THREAD

**Issue by jbn** [lemurheavy/coveralls-public#664]
I perused the prior issues. But, I couldn't get mine to work. 

- My membership is public.
- Coveralls is approved as a third party app. 

I am trying to add [generativists/ThirdWay](https://github.com/generativists/ThirdWay). Previously, coveralls was working with `jbn/ThirdWay`, now defunct. 

Any suggestions? 
Thanks

**Comment by nickmerwin** [comment]
Hi @jbn could you try revoking access to Coveralls and re-logging in? The OAuth token we have doesn't seem to have access to the generativists org.

Thanks!

**Comment by jbn** [comment]
This worked. Thank you!
