### ISSUE TITLE
can we get test coverage for client side javascript?

### ISSUE THREAD

**Issue by tansaku** [lemurheavy/coveralls-public#665]
From what I see in the docs only server side is supported.  Am I wrong?

**Comment by bkon** [comment]
We generate coverage for both server-side Ruby code and client-side JS. 
It might require you some manual tweaking (as you'd need to generate lcov files and merge them together), but it's totally possible.

**Comment by anthonycintron** [comment]
@bkon - interested in knowing the best route to accomplish this. 

How can I get Coveralls to grab our teaspoon coverage and merge it into our general rspec coverage. I'm assuming we would need something similar to Coveralls.wear_merged! in our spec_helper.coffee file.

*All is executed during a CodeShip.io build*

Ultimately I am running:
` bundle exec teaspoon --coverage=default`

Then:
`bundle exec rake coveralls:push`

It's not obvious to me that Coveralls supports this type of workflow. We're using istanbul to write out the lcov report via teaspoon. 

**On another note:** Generating the lcov file is pretty straight forward. However, evaluating js files that do not have coverage versus what has test coverage seem to be a little muddied. Specifically related to code that has no jasmine specs. They seem to not be part of the evaluation process. Requiring all of those js files into the spec_helper doesn't seem resolve any of it. I'm assuming we would have to generate shell specs for all js files that we want to include in the coverage report (including the js files that have no specs). Unfortunately, I just asked to questions in one thread  :smile:
