### ISSUE TITLE
Yet another "Couldn't find a repository matching this job" issue.

### ISSUE THREAD

**Issue by jMyles** [lemurheavy/coveralls-public#669]
This is for a private github repo on Travis Pro.

So, first, I have read the other similar issues and ensured that the following are in place:

* I have "service_name: travis-pro" (and not "service_name: travis-ci") in my .coveralls.yml
* I have logged out and back in to Coveralls (although my token did not change)
* I have confirmed that the repo token matches the value for "repo_token" in my .coveralls.yml

Nevertheless, when I build on Travis - and run coveralls at the conclusion of the build - the console displays the message "Couldn't find a repository matching this job" and no build is triggered on Coveralls.

*However* - and I find this quite odd - when, with the exact same configuration, I run the coveralls command from my local terminal, a build *is* triggered.

I have run the build with --debug in both my local environment and on Travis, but it's not evident to me which parts of the resulting output might be useful in tracking this down.

**Comment by nickmerwin** [comment]
Hi @jMyles could you tell me what repo this is for?

**Comment by nickmerwin** [comment]
Continuing on private support.
