### ISSUE TITLE
Coverage decrease when adding comments to repository?

### ISSUE THREAD

**Issue by chrisbra** [lemurheavy/coveralls-public#670]
Hi, this just happened on the vim/vim repository:
[PR 497](https://github.com/vim/vim/pull/497), [diff](https://github.com/mgedmin/vim/commit/173d85df1a30dfd33bd0319adeceba06c2a95693)
Coverage decrease by 0.02% Why does this happen? Is there a way to configure coveralls to skip commented lines?

**Comment by nickmerwin** [comment]
Hi @chrisbra, Coveralls analyzes the coverage data that is posted to us, so you may need to open a ticket with the C coverage library maintainers the project is using; skipping comment lines would happen at that level.
