### ISSUE TITLE
Can't find source for non-default GitHub branch

### ISSUE THREAD

**Issue by dokie** [lemurheavy/coveralls-public#672]
When I commit to a branch (non the default branch which is master) on GitHub, then files which are covered OK in the report cannot be picked up from GitHub as they are not yet on master.

See for example
https://coveralls.io/builds/4250205/source?filename=lib%2Fdatastores%2Ftimeseries%2Fin_memory_store.ex

**Comment by nickmerwin** [comment]
Hi @dokie we take the branch into consideration when pulling source files from the Github API -- have you tried other combos of the git repo root directory or sub directory settings? That may be the issue.

**Comment by dokie** [comment]
I have, and files that get pulled ok are on master and others which are only on the branch do not. If I change the default branch on GitHub to my working branch then that situation reverses - the files that had no source now do and the one that did (that still exists on the working branch), did not.
I do find the settings on that page confusng though and have tried numerous combinations - it should not be that hard!

**Comment by nickmerwin** [comment]
Ok could you link me to a file that is being pulled properly?

Also, I noticed some of your builds came in without a rev sha; that would prevent Coveralls from being able to get the file from Github.

**Comment by dokie** [comment]
Correct
https://coveralls.io/builds/4253417/source?filename=lib%2Finflownet_server.ex

Incorrect
https://coveralls.io/builds/4253417/source?filename=lib%2Fdatastores%2Ftimeseries%2Fin_memory_store.ex

Those builds were me pushing from local as a test to capture the JSON payload.

**Comment by nickmerwin** [comment]
@dokie it doesn't appear that either of those are loading the file properly. Was there a previous sub directory value that was correct?

**Comment by dokie** [comment]
Weird as the top url works for me now as I just clicked it here to try it.

The code lives in apps/inflownet_server/lib... relative to GitHub root dir so I have the subdirectory set as /apps/inflownet_server/

**Comment by nickmerwin** [comment]
Ah ok I see the issue! Your builds don't have a commit SHA; when using Travis, we get this automatically by querying their API, but on other CI's it needs to be set in the post data to Coveralls.

Here's the spot in excoveralls that needs it:

https://github.com/parroty/excoveralls/blob/00803bf9a8cc291eb67f7b0e8d0290fdce9db9b0/lib/excoveralls/post.ex#L25

There should also be an `id` field in `head` that specifies the commit SHA. To follow their convention it could be added to the command parameters as doc'd here:

https://github.com/parroty/excoveralls/blob/db50630eac1f981cc79bdafab1af8fb1fce435d7/lib/excoveralls/task/util.ex#L33

But this could also all be read from the environment using `git log -1`. Here's how our coveralls-ruby gem does it:

```ruby
hash[:head] = {
  :id => ENV.fetch("GIT_ID", `git log -1 --pretty=format:'%H'`),
  :author_name => ENV.fetch("GIT_AUTHOR_NAME", `git log -1 --pretty=format:'%aN'`),
  :author_email => ENV.fetch("GIT_AUTHOR_EMAIL", `git log -1 --pretty=format:'%ae'`),
  :committer_name => ENV.fetch("GIT_COMMITTER_NAME", `git log -1 --pretty=format:'%cN'`),
  :committer_email => ENV.fetch("GIT_COMMITTER_EMAIL", `git log -1 --pretty=format:'%ce'`),
  :message => ENV.fetch("GIT_MESSAGE", `git log -1 --pretty=format:'%s'`)
}

hash[:branch] = ENV.fetch("GIT_BRANCH", `git rev-parse --abbrev-ref HEAD`)
```

Anyway, I'm going to try out some Elixir and open a PR with them to add it. Closing this issue for now.

**Comment by dokie** [comment]
Ok thanks for digging into it. I can fix it up locally as a test and then if it works, send a PR myself if you'd prefer?

**Comment by nickmerwin** [comment]
Ok PR sent: https://github.com/parroty/excoveralls/pull/36

And here's the parameter your build command will need added:
`-s ${CIRCLE_SHA1}`

**Comment by dokie** [comment]
Yup, got that - cheers! 👍
