### ISSUE TITLE
New gem version of simplecov - 0.11.0

### ISSUE THREAD

**Issue by jasnow** [lemurheavy/coveralls-public#675]
Please upgrade coveralls-ruby' Gemfile to use new (0.11.0) version of simplecov.
  * https://rubygems.org/gems/simplecov

Thanks.

**Comment by nickmerwin** [comment]
Thanks @jasnow we're upgraded now:
https://github.com/lemurheavy/coveralls-ruby/releases/tag/v0.8.10

**Comment by jasnow** [comment]
You are welcome - Happy Holidays
