### ISSUE TITLE
after turning private repo public, cannot get to the repo detail page

### ISSUE THREAD

**Issue by markelliot** [lemurheavy/coveralls-public#678]
I turned one of my private repos public, but can no longer get to the detail page for the repo. I'm an admin for the project on GitHub, and the project is owned by an organization that I'm a member of: https://coveralls.io/github/palantir/resource-identifier?branch=develop

**Comment by nickmerwin** [comment]
Hi @markelliot, ok I sync'd the repo's info and it's set to public now.

Thanks!
