### ISSUE TITLE
Bad show utf-8 source files

### ISSUE THREAD

**Issue by rekby** [lemurheavy/coveralls-public#683]
For example it doesn't show russian text in 
https://coveralls.io/builds/4370746/source?filename=main.go#L69

Line 69-70

**Comment by jnpkrn** [comment]
+1
https://coveralls.io/builds/4402686/source?filename=commands%2Fcmd_wrap.py#L6

**Comment by tarlepp** [comment]
What is the status of this?

https://coveralls.io/builds/7136664/source?filename=src%2FApp%2FRepository%2FUserLogin.php#L5

**Comment by RobinDaugherty** [comment]
Fixed!

For example: https://coveralls.io/builds/4821344/source?filename=main.go#L108

**Comment by jnpkrn** [comment]
Thanks!
