### ISSUE TITLE
date error on commit date

### ISSUE THREAD

**Issue by arzynik** [lemurheavy/coveralls-public#684]
![image](https://cloud.githubusercontent.com/assets/27974/11616340/319b1400-9c2d-11e5-8c2b-445ff6cd096a.png)

notice top 3 items

date works fine when clicking an item

![image](https://cloud.githubusercontent.com/assets/27974/11616334/2074f38a-9c2d-11e5-878c-6f58f4f40896.png)

**Comment by nickmerwin** [comment]
Hi @arzynik we use the `run_at` field of the last job from the build that was reported through the API. Depending on your Coveralls integration library, it may have been reported incorrectly.

**Comment by arzynik** [comment]
Noted. I'll take a look at my phpunit/Travis stuff
