### ISSUE TITLE
Can't add organization's repository

### ISSUE THREAD

**Issue by bubenkoff** [lemurheavy/coveralls-public#685]
Hi
tried to add this repo https://github.com/InnovativeTravel/it-data-api to coveralls, refreshed repos couple of times, still, it doesn't see it under my account, even though im an admin in that organization

**Comment by shadowhand** [comment]
I'm having a really similar problem. Tried refreshing every possible thing but my organization is not appearing in the list.

**Comment by shadowhand** [comment]
https://github.com/destruktphp/destrukt

**Comment by nickmerwin** [comment]
hi @shadowhand and @bubenkoff could you guys check your 3rd party access restrictions for the organization?

Also you may need to upgrade your OAuth scope if the org memberships aren't public:
https://coveralls.io/refresh?private=true

**Comment by shadowhand** [comment]
@nickmerwin that didn't work. I even tried removing Coveralls from my authorized applications and re-connecting. My org membership is public:

<img width="1022" alt="screenshot 2015-12-19 10 47 39" src="https://cloud.githubusercontent.com/assets/38203/11914166/f37e095a-a63d-11e5-8874-d59025c216cc.png">

**Comment by shadowhand** [comment]
It seems like Coveralls isn't properly requesting access to organizations. For instance, when I do a private repo request with Scrutinizer, this is what comes up:

<img width="501" alt="screenshot 2015-12-19 10 51 33" src="https://cloud.githubusercontent.com/assets/38203/11914185/841ca1c4-a63e-11e5-8592-b39cfd8ca316.png">

Notice how I am given the option to grant access to the Destrukt org. This page never appears with Coveralls, no matter how many times I press the Refresh or Reauthorize buttons.

**Comment by chfw** [comment]
Same problem here. Organisation does not show up no matter how many times it have been tried.

**Comment by chfw** [comment]
Heads up, codecov.io can see my organisation correctly while coversall.org couldn't.

**Comment by dotnetCarpenter** [comment]
@nickmerwin https://coveralls.io/refresh?private=true does not seem to do anything. Is it b0rken?
