### ISSUE TITLE
Hipchat integration not working?

### ISSUE THREAD

**Issue by brandonkane** [lemurheavy/coveralls-public#687]
I have confirmed the API token I'm using is correct but when testing in the coveralls UI I get:

Error: Access denied to room `dev'

Tried with several different rooms/tokens but got the same result.  Any ideas?

**Comment by nickmerwin** [comment]
Hi @brandonkane we haven't gotten any other reports of Hipchat notifications having issues; is it still giving your the error? If yes, what is the repo in question?

**Comment by ghiculescu** [comment]
Hi, having the same issue here. Repo is TandaHQ/payaus.

**Comment by brandonkane** [comment]
our main one is /VantageAnalytics/vantage/ but this is happening with all our repos.

**Comment by d3ming** [comment]
Also seeing this issue

**Comment by geeknam** [comment]
we're also seeing the same error
