### ISSUE TITLE
Could not open input file: vender/bin/coveralls

### ISSUE THREAD

**Issue by RudyJessop** [lemurheavy/coveralls-public#690]
I am having a minor issue. I am getting this output in my CI build (Travis). 
`Could not open input file: vender/bin/coveralls` 

What could possibly be causing this. In my local repo the `build` directory is there. Should i remove it from my `.gitignore`? 

You can take a further look at the 
`.travis.yml`: https://github.com/Core-Tech-Labs/LAZ/blob/master/.travis.yml
`phpunit.xml`: https://github.com/Core-Tech-Labs/LAZ/blob/master/phpunit.xml
`Travis CI Build`: https://travis-ci.org/Core-Tech-Labs/LAZ/jobs/97767995 (scroll all the way to the bottom)

**Comment by nickmerwin** [comment]
Hi @RudyJessop is see this in your Travis logs:

```
Failed to download satooshi/php-coveralls from dist: Could not authenticate against github.com
```

Which would explain why the coveralls binary wasn't present at build time. Could you check your external library configuration and try again?

Thanks!

**Comment by RudyJessop** [comment]
@nickmerwin I get that with all composer packages. It still downloads and my test still shows up successful. I find it hard to believe thats this is the reason.
