### ISSUE TITLE
Repos not synching

### ISSUE THREAD

**Issue by diogobaeder** [lemurheavy/coveralls-public#692]
Hi,

I have a sort-of-new repository here:
https://github.com/diogobaeder/convertfrom

However, even if I click the Coveralls button to re-synch repos, I can't add this repo to my profile at Coveralls, it simply doesn't show up - as if it doesn't even exist in my GitHub account.

Am I perhaps doing something wrong?

Thanks!

**Comment by robertotru** [comment]
I have the same issue with this new repository
https://github.com/ozimov/cirneco/

**Comment by skytreader** [comment]
Similar to my report at #638. Curiously, I've forgotten about the issue I filed then and it only came to my mind recently, when I got back to some of my side projects.

It seems that re-authorizing Coveralls for GitHub does the trick; I can now add my recently-created repos to Coveralls. You may want to try that and see if it works.

(Authorizations being there for the sake of _security_, I still hope to hear officially from Coveralls about this.)

**Comment by mfrasca** [comment]
I was experiencing the same, and I was not doing **two** things, both on github:
1) make my membership in the new organization **public**.
2) review my settings, applications, coveralls, organization access.
