### ISSUE TITLE
Email is being exposed in travis log

### ISSUE THREAD

**Issue by tansaku** [lemurheavy/coveralls-public#695]
Hi there, 

I notice that emails of users sending us pull requests are being added to the travis log as the result of using coveralls, e.g. 

https://travis-ci.org/makersacademy/chitter-challenge/builds/100079304

```
"git": {
    "head": {
      "id": "c3d9301da735bc0f61101f609570af442991164a",
      "author_name": "...",
      "author_email": "...",
      "committer_name": "...",
      "committer_email": "....",
      "message": "Merge ec83ebaf0cff5cb31e7033f823bd93dec71ad006 into 197661c9e9c3855ee1f464e804d754e0fdcd9994"
    },
```

which doesn't seem ideal since that could then be harvested by spammers.  Is there a simple way to avoid this?

Many thanks in advance

**Comment by aeberlin** [comment]
This is bothering me also. I would prefer to be able to configure this display, preferably to hide it entirely.
