### ISSUE TITLE
Blank lines and "end" counted as not covered

### ISSUE THREAD

**Issue by ianjepperson** [lemurheavy/coveralls-public#696]
We're trying to start using Coveralls for our Rails app.  However, Coveralls is sometimes counting blank lines as not covered where Simplecov is showing them correctly as not relevant.

Here is the coverage report I expect as provided by Simplecov (100%):
![2016-01-06 02 59 38 pm](https://cloud.githubusercontent.com/assets/16088570/12157628/f2b4071a-b487-11e5-96ad-b7070128daea.png)

But here is what Coveralls reports for the same file (76%):
![2016-01-06 03 00 02 pm](https://cloud.githubusercontent.com/assets/16088570/12157637/fc7c0400-b487-11e5-892f-04da47f6998e.png)

Update to add more info:
We're using CircleCI and have nine parallel builds set up.  

Our `spec_helper.rb` contains:

```
if ENV['CIRCLECI']
  # If running in CircleCI, run with Coveralls too
  require 'coveralls'
  Coveralls.wear!('rails')
end
```

Our `circle.yml` contains:

```
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=(our actual token)
```

We have an environment variable defined for `COVERALLS_PARALLEL=true` in the CircleCI configuration.

**Comment by nickmerwin** [comment]
Following up via email, thanks @ianjepperson

**Comment by ketiko** [comment]
@nickmerwin We are also having this issue.  Our percentage drops way down after using parallel because of this.

**Comment by cayter** [comment]
@nickmerwin What's the solution for this issue? This bug has been troubling our team for a few days.

**Comment by Kolyunya** [comment]
Please [fix this](https://coveralls.io/builds/11193967/source?filename=sources%2FLib%2FMarkupValidator%2FDefaultMarkupReporter.php#L62)! I want my 100%. :laughing:
