### ISSUE TITLE
coverage reported is clearly wrong (35% -> should be 96%)

### ISSUE THREAD

**Issue by dnozay** [lemurheavy/coveralls-public#698]
see badges from https://github.com/xmlrunner/unittest-xml-reporting.

https://coveralls.io/github/xmlrunner/unittest-xml-reporting?branch=coveralls, coverage reported is 35% when it should be above 90%.

**Comment by eranhirs** [comment]
Your coveralls badge is configured against the "coveralls" branch and not master

**Comment by dnozay** [comment]
When I tested turning on reporting coverage status from coveralls, I was using `coveralls` branch which at that point in time had more commits than `master`, the number was wrong in `coveralls` branch. After fixing the branch name in `master` the number is still wrong.
