### ISSUE TITLE
Coveralls seem stuck... is service up?

### ISSUE THREAD

**Issue by meirwah** [lemurheavy/coveralls-public#700]
![image](https://cloud.githubusercontent.com/assets/6059211/12398283/579d8146-be1b-11e5-9075-0f5763610080.png)

**Comment by tomvlk** [comment]
Same here. This is a job thats stuck: https://coveralls.io/jobs/11288976

**Comment by tomvlk** [comment]
Ah, I found out that they are upgrading the infrastructure.
Status page: http://status.coveralls.io/

**Comment by meirwah** [comment]
seem to be fixed...
