### ISSUE TITLE
"Couldn't find a repository matching this job. 'url'" on a private repo

### ISSUE THREAD

**Issue by doodyparizada** [lemurheavy/coveralls-public#703]
Hi
After successfully configuring coveralls on a private repo using travis I tried to do the same for a second repo.
I followed the exact same steps (both are python projects), yet my second repo keeps getting:

```
$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
```

After a few days the error changed to success but was sending my coveralls data to someone elses project...:

```
Submitting coverage to coveralls.io...
Coverage submitted!
Job #322.8
https://coveralls.io/jobs/11463512
```

I deleted the repo from coveralls and restarted the process (got a new repo_key), but now I'm stuck again with the first error: `Couldn't find a repository matching this job.`

Please help.

CC @oryband @avivl

**Comment by oryband** [comment]
:+1:

**Comment by JayThomason** [comment]
We have seen a similar problem. While using travis-pro, setting the repo token and travis `service_job_id` recently stopped working correctly, often linking to different commits from other users/repos or failing to upload with the `Couldn't find a repository` error.

**Comment by jfeiber** [comment]
^ :+1:

**Comment by nickmerwin** [comment]
Hi all, could you make sure the owner of the repo on Coveralls hasn't been removed from the org, and has up-to-date login creds; they can reset those by following this link:

https://coveralls.io/refresh?private=true

**Comment by jfeiber** [comment]
@nickmerwin resetting the login credentials worked for us, thanks!

**Comment by bambielli** [comment]
:+1:, but I'll try resetting the login credentials.

**Comment by bambielli** [comment]
it work

**Comment by johnthagen** [comment]
@nickmerwin I am getting this same error, but for my public repos. I tried resetting my login credentials, but that did not work.

https://travis-ci.org/johnthagen/cpplint-junit/jobs/106887025
https://travis-ci.org/johnthagen/cppcheck-junit/jobs/106886401

**Comment by jamiebull1** [comment]
+1 same problem on a python project. Resetting login credentials hasn't worked.

https://travis-ci.org/jamiebull1/eppy/builds/106929506

**Comment by doodyparizada** [comment]
I tried resetting my credentials and the account owner's. nothing works

**Comment by jamiebull1** [comment]
After several hours trying to get this working I tried with [CodeCov](https://codecov.io) and it worked first time. It seems a little less polished in terms of UI but the backend seems much less flaky. Also the leaking of private repos, though not a concern on my current project, seems like an absolute disaster!

**Comment by larubbio** [comment]
I'm getting this same error.  I just created a travis-pro account (currently in free trial) and a paid account on coveralls.

**Comment by duedal** [comment]
If you are using tox + travis-pro to run your tests, make sure it's tox that runs the `coveralls` command. This fixed the issue for me.

**Comment by larubbio** [comment]
If I move the coveralls command to tox it works locally but it still fails when run by travis.  

My build output on travis:

```
Coverage submitted!
Couldn't find a repository matching this job.
'url'
ERROR: InvocationError: '/home/travis/virtualenv/python2.7.9/bin/coveralls --verbose'
___________________________________ summary ____________________________________
ERROR:   py27-1.9: commands failed
The command "tox" exited with 1.
```

What is interesting is in .coveralls.yml I have my `service_name: travis-pro`, but in the verbose output it is travis-ci.  Also config_file is .coveragerc and not .coveralls.yml

**Comment by duedal** [comment]
Another thing to try if you didn't already, make sure the travis env vars is passed along to the tox env.

Make sure `TRAVIS*` is in your passenv.
```
[testenv]
passenv = TRAVIS* 
```

**Comment by larubbio** [comment]
I was passing the vars explicitly like this:

```
passenv = TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH
```

Changing to TRAVIS* didn't do anything different

It seems like it isn't picking up the correct service from .coveralls.yml.
Since I'm on a private repo service needs to be travis-pro but it is
sending travis-ci instead.

**Comment by nueverest** [comment]
This seems to randomly occur for me in 1 out of 4 python environments.  I using 27, 33, 34, and 35.  Sometimes 34 fails with this error.  Sometimes 35 fails, but the three others pass without a coveralls error.

**Comment by dijs** [comment]
I have a private repo, travis pro, and was also seeing this "linking to different commits" issue...

I have added the ".coveralls.yml" file as the setup told me to do, but no luck.

I also tried manually pushing my code using "https://github.com/nickmerwin/node-coveralls", and that works if I have my YAML file in that directory... But still does not trigger github comments.

Very confused by this since public repos and coveralls have always worked great for me.

**Comment by djordon** [comment]
Just wanted to point out that adding PyYAML as a requirement to python projects may fix this issue. Worked for me.

**Comment by pylover** [comment]
Not working at all for me. the same configuration with my another two repo. just the name of projects are differ. but not working on travis. but only from local

**Comment by ekelleyv** [comment]
Had the same issue, adding PyYAML as a req also fixed. Thanks Dr. @djordon

**Comment by pylover** [comment]
PyYaml is the main dependency of my project.

**Comment by pylover** [comment]
PyYaml is the main dependency of my project and it's already added as requirement.

**Comment by joseluisq** [comment]
> This seems to randomly occur for me in 1 out of 4 python environments. I using 27, 33, 34, and 35. Sometimes 34 fails with this error. Sometimes 35 fails, but the three others pass without a coveralls error.
> 
> My solution was to click the "sync" button in coveralls.io.
> 
> 
> 
> And then go over to Travis CI and Re-run the failing test.

Yep, Syncing repos on Coveralls and then "restart build" on Travis solves it. :+1:

**Comment by pylover** [comment]
@joseluisq not working for me. It's random

**Comment by PetrDlouhy** [comment]
For anyone seeking help here, I have one more potential reason. I had set the repo token in `COVERALLS_REPO_TOKEN` on CircleCI and I also had `repo_token` set in the `.coveralls.yml` file. The environmental variable has priority. I was wondering, that it doesn't work if I change the `.coverals.yml` for very long time until I realized, that I have to set the environmental variable.

**Comment by pylover** [comment]
@PetrDlouhy, not working

**Comment by TugrulAsik** [comment]
The same problem. Not working. Firstly my results pushed to somebody's repo. Now I got 422 error.
