### ISSUE TITLE
GitHub username case change, Coveralls now shows old repo runs

### ISSUE THREAD

**Issue by HariSekhon** [lemurheavy/coveralls-public#706]
I tweaked my GitHub username to be camelcased but Coveralls defaults to showing the last runs of the repos before that time and only shows the new repo runs when giving a more explicit suffix. There doesn't seem to be any way to address this issue in the Coverals.io UI settings?

I've tried unlinking and relinking the GitHub repo, but wasn't prompted for a github url or authentication and it still exhibits the same behaviour or showing very outdated information by default.

**Comment by ARenfroe** [comment]
Can you restrict access from github then try to relink the account on coveralls?
