### ISSUE TITLE
Coverage "changed" by -0.0% - blocks pull request

### ISSUE THREAD

**Issue by glenjamin** [lemurheavy/coveralls-public#709]
You can see an example of this here:

https://github.com/glenjamin/webpack-hot-middleware/pull/68

A docs-only PR is somehow calculated to be a coverage change of -0.0%

This can be overridden on desktop, but not on mobile for some reason.

![img_2867](https://cloud.githubusercontent.com/assets/151272/12743112/6b9b4d40-c983-11e5-97f2-b646c8ecfc3a.jpg)

**Comment by nCrazed** [comment]
Is there an ETA for a fix on this?

**Comment by shahdewang** [comment]
+1
Would be good to have this fixed.

**Comment by dimbleby** [comment]
Duplicates #708 presumably
