### ISSUE TITLE
Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by jsdevel** [lemurheavy/coveralls-public#713]
I'm randomly getting this error on travis right now.  I have no idea why.  Thoughts?

![2016-02-03-210721_1290x711_scrot](https://cloud.githubusercontent.com/assets/2605980/12805610/56617f52-caba-11e5-970b-2da8bb397fdc.png)

Here's a link to the failed build: https://travis-ci.org/kogosoftwarellc/express-openapi/jobs/106901792

**Comment by deadprogram** [comment]
Same problem here:

https://travis-ci.org/hybridgroup/gobot/jobs/106904961#L676

```
coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by derekcollison** [comment]
Same thing here: https://travis-ci.org/nats-io/gnatsd/builds/106917788

**Comment by renaesop** [comment]
same issue [address](https://travis-ci.org/renaesop/pss/jobs/106917545)

**Comment by shinnn** [comment]
Having the same problem: https://travis-ci.org/shinnn/modernizr-stream/jobs/106954298#L390

**Comment by dkatzberg** [comment]
We have the same issue: https://travis-ci.org/dzhw/metadatamanagement/builds/106730060

**Comment by cliffano** [comment]
Same issue across several repos. https://travis-ci.org/cliffano/cmdt/jobs/106961786#L652

**Comment by weppos** [comment]
I have the same issue. I thought it was isolated to my repo (as I rename it a few days ago), but apparently it seems to affect several repos.
https://travis-ci.org/weppos/dnsimple-go/builds/106972221

**Comment by dokipen** [comment]
Same.

**Comment by scorphus** [comment]
Yeah. Same. Moved it to `after_success`, unfortunately: https://travis-ci.org/scorphus/gothumbor/builds/106984372

**Comment by bitinn** [comment]
same here, would be interesting to see if this is due to travis or coveralls

https://travis-ci.org/bitinn/vdom-parser/builds/106983754

**Comment by o1egl** [comment]
I have the same issue https://travis-ci.org/o1egl/elogs/jobs/106987802

**Comment by figurebelow** [comment]
Same error here.
Even running the line from the command line returns the error, so it seems a coverall issue:

cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
C:\testdev\nr\node-red\nodes\svgart\node_modules\coveralls\bin\coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by javadev** [comment]
+1

**Comment by cardil** [comment]
Dear Coveralls,

Rollback, please.

Sincerely,
Me

**Comment by fisharebest** [comment]
The problems have been fixed (for me).

I guess the coveralls engineers have given the system a kick.  (Thanks guys!)

**Comment by nickmerwin** [comment]
Hi all, we've deployed a potential fix for this issue, could you re-trigger builds?

Thanks!

**Comment by jsdevel** [comment]
Looks good!

**Comment by scorphus** [comment]
All systems are GO! Thanks, Coverallers! :+1:

**Comment by cardil** [comment]
Seems to be OK now. Thanks for reaction :smile:

**Comment by deadprogram** [comment]
Likewise.

**Comment by figurebelow** [comment]
Thanks for the quick response, up and running again :smiley:
