### ISSUE TITLE
Coveralls throw a HTTP 422 with travis-ci and github public repos

### ISSUE THREAD

**Issue by sangupta** [lemurheavy/coveralls-public#714]
Example log can be seen at https://travis-ci.org/sangupta/dryrun/jobs/106965084

I have the repo configured in coveralls.io - but nothing seems to work.

**Comment by o1egl** [comment]
Have the same issue https://travis-ci.org/o1egl/elogs/jobs/106987802

**Comment by javadev** [comment]
+1

**Comment by PascaleBorscia** [comment]
+1

**Comment by marcc-orange** [comment]
+1

**Comment by cardil** [comment]
This issue blocks our work at: https://github.com/coi-gov-pl/puppet-jboss/pull/54

**Comment by cardil** [comment]
This issue is fixed now. See #713

**Comment by o1egl** [comment]
Periodicaly I see this error.
https://travis-ci.org/o1egl/elogs/builds/107173217

**Comment by sangupta** [comment]
Seems to be fixed with #713  - closing this down.
