### ISSUE TITLE
Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by Diggsey** [lemurheavy/coveralls-public#715]
While trying to submit coverage data using kcov on travis for a public repo, I just get the error:
`kcov: warning: coveralls write failed: {"message":"Couldn't find a repository matching this job.","error":true}`

The travis job ID is correct, as you can see from the build log: https://travis-ci.org/Diggsey/multirust-rs/jobs/106891443

**Comment by ioncube** [comment]
Did you try the job again? It may have worked a second time. The same issue just occurred for me on a travis job, but rerunning the job with no changes it worked the second time. The GH integration seems flakey.

**Comment by Diggsey** [comment]
The problem was the command line I was passing to `kcov` was incorrect: this error message is very misleading, I think it can occur if you try to submit empty coverage data.
