### ISSUE TITLE
Successful Job -- Coverage Unknown

### ISSUE THREAD

**Issue by quasiben** [lemurheavy/coveralls-public#716]
Hi All,

I may be doing something unorthodox in that I'm running my tests in docker.  But I am getting coverage statistics and a successful job submission to coveralls.io.  Still, my badge is `coverage unknown`

- https://travis-ci.org/blaze/knit/jobs/107523266
- https://coveralls.io/github/blaze/knit

**Comment by s-a** [comment]
Same here https://coveralls.io/github/s-a/time-track?branch=master

**Comment by quasiben** [comment]
After a 1 or 2 things seemed to be working for me.  @s-a feel free to keep this open if you are still having trouble, but I'm good to close

**Comment by s-a** [comment]
Yes it works. We can close this.

**Comment by nickmerwin** [comment]
Thanks all! Closing for now.
