### ISSUE TITLE
Access denied to repo following conversion private -> public

### ISSUE THREAD

**Issue by ewindisch** [lemurheavy/coveralls-public#719]
We recently moved a repo from private to public and now I'm unable to access, modify, remove, or otherwise access the URL (https://coveralls.io/github/iopipe/iopipe). Coveralls is no longer gating our changes for the repo, either.

**Comment by ewindisch** [comment]
As a workaround, I managed to delete the private repo from the subscriptions page (although it no longer showed under "repos") and was able to re-add it. History was lost, but I'm back in business.

**Comment by valendesigns** [comment]
I'm having this exact same issue. Unfortunately, I cannot use your workaround as the repo does not show up on the Subscription page.
