### ISSUE TITLE
Private Access Permissions for Public Repo?

### ISSUE THREAD

**Issue by danrbailey** [lemurheavy/coveralls-public#722]
Hi,

I'd like some help retrieving the repo token for a public open-source project. We have an admin user with public membership to the GitHub organisation that hosts the project and have granted read/write commit access, but _not_ read and write access to public and private repositories (as we don't wish to grant access to private repositories).

Is this possible? Going to this page:

https://coveralls.io/refresh

appears to request access to private repos?

Thanks

**Comment by InsidersByte** [comment]
+1
