### ISSUE TITLE
pull request comment not appearing in BetterWorks/BetterWorks repo

### ISSUE THREAD

**Issue by diwu1989** [lemurheavy/coveralls-public#724]
I'm not seeing comments on pull requests for my private repo

**Comment by duedal** [comment]
The bot stopped [adding comments 20 days ago](https://github.com/coveralls?tab=activity)? And the status API does not work either for private repos?!

**Comment by liry** [comment]
Pull request comments unfortunately doesn't work even for many public repos for a long time :(
