### ISSUE TITLE
Coverage is not reported on pull request build

### ISSUE THREAD

**Issue by BrotherLogic** [lemurheavy/coveralls-public#731]
e.g. https://github.com/BrotherLogic/beer/pull/48

builds from travis and shows up correctly on coveralls (https://coveralls.io/builds/5322800) but the < 99.99 test coverage is not reported to github and so the build suceeds when it should fail.

**Comment by marcjansen** [comment]
Same here: https://github.com/openlayers/ol3/pull/4977

**Comment by BrotherLogic** [comment]
I deleted the repo in coveralls, and recreated it to no avail.

**Comment by nickmerwin** [comment]
Hey all, we've deployed a fix for this. Could you please re-trigger your PR builds?

Thank you!

**Comment by BrotherLogic** [comment]
Hmm, now I get:

$ $HOME/gopath/bin/goveralls -service=travis-ci github.com/BrotherLogic/beer
{"service_job_id":"116299486","service_pull_request":"48","service_name":"travis-ci","source_files":...

In the travis logs, and coveralls doesn't seem to be running on that build.

**Comment by marcjansen** [comment]
It's working for us again: see e.g. https://github.com/openlayers/ol3/pull/5031

Thanks for the fix!
