### ISSUE TITLE
Coverage not reported: ?%

### ISSUE THREAD

**Issue by asottile** [lemurheavy/coveralls-public#734]
https://coveralls.io/jobs/12626756
https://travis-ci.org/Yelp/yelp_cheetah/jobs/114631795

It's definitely at 100% but not displaying :(

Also

https://travis-ci.org/asottile/setuptools-golang/jobs/114167075
https://coveralls.io/jobs/12565817

**Comment by nmohoric** [comment]
Same problem here. Very weird, never shows up with any actual data in there. :(

**Comment by asottile** [comment]
I ran a job with --verbose as well: https://travis-ci.org/Yelp/yelp_cheetah/jobs/114642665

seems on coveralls side?

**Comment by blampe** [comment]
Also seeing this.

**Comment by Layoric** [comment]
Same here, multiple project builds all showing up with no data.

**Comment by cooperkong** [comment]
just got coveralls setup with CircleCI, getting unknown % now!

**Comment by dojoteef** [comment]
+1
Mine is also at 100% but not updating :-(

https://travis-ci.org/dojoteef/lualol/jobs/114712451
> Line 794: Uploaded Job #9.1 to https://coveralls.io/jobs/12637880


(btw, hey @asottile it's been a while; hope Yelp's still doing well!)

**Comment by Risto-Stevcev** [comment]
Same

**Comment by makots** [comment]
+1

**Comment by nadar** [comment]
same here, shows "no data".

https://travis-ci.org/luyadev/luya/jobs/114728169
https://coveralls.io/jobs/12640024

**Comment by rockuw** [comment]
Same

https://coveralls.io/builds/5359587

**Comment by nickmerwin** [comment]
Sorry all, we're running an emergency database migration to fix this issue.

Stay tuned here: https://status.coveralls.io

Thank you!

**Comment by ehuelsmann** [comment]
@nickmerwin will that resolve the issue with all builds reported as "new coverage" as well?

**Comment by Layoric** [comment]
Builds now showing data for me, thanks @nickmerwin !

**Comment by ehuelsmann** [comment]
The database update didn't fix our issue #732 -- which not only our project is experiencing. Was the fix intended to solve that issue too?

**Comment by kako-nawao** [comment]
Still "no data" here. Well, that's inaccurate: the files do show the lines covered properly, but there's no percentage per file, nor overall.

**Comment by Risto-Stevcev** [comment]
Same... still no data: https://coveralls.io/builds/5442485

**Comment by Risto-Stevcev** [comment]
On another note, it would be nice if coveralls provided a way to view the actual coverage file it received so that we won't attempt to debug it on our end if it was properly submitted.

**Comment by Risto-Stevcev** [comment]
Seems to work now, I guess it was a server delay

**Comment by gerddie** [comment]
For me there is also a build that is not showing up:   
https://coveralls.io/builds/5729655
Only when I go to the last build on the dashboard I can move to this one, and then the covered line numbers are reported, but no overall or percentage.

**Comment by gerddie** [comment]
Today I submitted a new build that actually provided a proper coverage report, and the change that triggered proper processing was that I set the optimization flag on this C++ project to **-O0** instead of *-O1*, so I assume that either *gcov* or *coverallls* doesn't know how to deal with optimization properly.

**Comment by otraore** [comment]
Same issue: https://coveralls.io/github/EngoEngine/engo

**Comment by asottile** [comment]
My two projects listed here are now showing coverage, closing.
