### ISSUE TITLE
Coverage remained the same from ​0.0% to ​94.215%

### ISSUE THREAD

**Issue by Miserlou** [lemurheavy/coveralls-public#738]
Coverage is being reported as "remained the same", from 0% to whatever it is now. The 'change' box value is at 94% when it should be 0. This is in a Slack integration. 

It should be 'remained the same at 95%', I assume.

**Comment by devights** [comment]
I'm also seeing this when coverage increases, reporting from 0.0% to [current coverage]%. Ex:

`Coverage remained the same on [repo]​ from ​*0.0%*​ to ​*51.078%`

**Comment by naservere** [comment]
Have the same problem. Please give us any comment on it.

**Comment by carlansley** [comment]
We are still seeing this on all our private repos, for a couple of weeks now.

**Comment by brookslyrette** [comment]
Also seeing on our private repos

**Comment by naservere** [comment]
Dear Coveralls! Any reaction on this? It's already one month since the issue was reported...

**Comment by nickmerwin** [comment]
Hey all, we just deployed a fix addressing the "new coverage" issue, this may have been affected too. Could you check your repos, and if there's still an issue, post a link here?

Closing for now. Thanks!

**Comment by marktheunissen** [comment]
Yes, we are still seeing this problem.

It says `Coverage remained the same on ​*pantheon-systems/titan-mt*​ ​_ygg_provision_instructions_​ from ​*0.0%*​ to ​*57.504%*​`

**Comment by marktheunissen** [comment]
Slack integration,

**Comment by brookslyrette** [comment]
I'm seeing 0% in the slack webhook as well

**Comment by greatislander** [comment]
@nickmerwin This issue is still present for https://github.com/pressbooks/pressbooks in our Slack webhook.

**Comment by mbdevpl** [comment]
@nickmerwin I've just experienced the same issue yesterday in 1st build of my new repo. The Slack message said:

> Coverage remained the same on *mbdevpl/horast* _devel_ from *0.0%* to *72.271%*

link to build is here: https://coveralls.io/builds/13031263

And then today in the 1st build of master branch of that repo:

> Coverage remained the same on *mbdevpl/horast* _master_ from *0.0%* to *72.773%*

link to that build: https://coveralls.io/builds/13044667
