### ISSUE TITLE
Coveralls not commenting on Pull Requests

### ISSUE THREAD

**Issue by sahilTakiar** [lemurheavy/coveralls-public#740]
I recently setup Coveralls for our GitHub project: https://github.com/linkedin/gobblin

The project is public. The coveralls page is: https://coveralls.io/github/linkedin/gobblin

Everything is working correctly, except the coveralls bot is not posting comments on new Pull Requests, even though this feature is enabled in the settings.

How can this be fixed?

**Comment by nickmerwin** [comment]
Hi @sahilTakiar we've recently re-enabled our commenter bot. Your next PR build should receive one.

Please re-open if it doesn't. Thank you!
