### ISSUE TITLE
Numbers don't add up and coverage is > 100%

### ISSUE THREAD

**Issue by cpitclaudel** [lemurheavy/coveralls-public#742]
Hi there,

How does the following screenshot make sense? (https://coveralls.io/builds/5524548)

![screenshot from 2016-03-23 15 47 18](https://cloud.githubusercontent.com/assets/8181630/13998642/8c8eab02-f10e-11e5-8d84-b84240ba063c.png)

In particular, how can the total be > 100%? How can there be 267 covered lines for 266 lines of interest, and still three lines not covered?

And with every file at 100%, how can the total be <100%?

Thanks!

**Comment by swapnilsm** [comment]
Same with this https://coveralls.io/builds/2153201

**Comment by cpitclaudel** [comment]
@swapnilsm 225%? Now that's what I call serious coverage. My 101% looks unprofessional in comparison :P

**Comment by cpitclaudel** [comment]
Was this ever fixed?

**Comment by daurnimator** [comment]
> Was this ever fixed?

I don't think so

**Comment by afinetooth** [comment]
@daurnimator this would not be fixed for old builds, but given the age and nature of the issue I would suspect it's been long fixed, otherwise we'd hear about similar cases a lot more.

if you want to share your recent case, we'll look into it for you.

**Comment by cpitclaudel** [comment]
I've stopped using Coveralls, so we can close this issue
