### ISSUE TITLE
Coverage raise/fell does no longer work when omitting the unit tests

### ISSUE THREAD

**Issue by jabdoa2** [lemurheavy/coveralls-public#744]
We test a python module and moved our tests inside the module. To get correct coverage results we exclude them from the calculation in .coveragerc (using omit). Since doing that coveralls no longer tells if coverage raised or fell. It just displays "new coverage" on every commit. This worked when the tests were outside the module. Is there any way to fix that?

https://coveralls.io/github/missionpinball/mpf

**Comment by willnewton** [comment]
I'm not sure if this is related to the omitting of tests. I only get new coverage on all my repos in Python and Go for all pushes. Pull requests seem to work ok.

I have tried to create a Zendesk issue (I have a "pro" account) but had no response.
