### ISSUE TITLE
proprietary project using your open source service

### ISSUE THREAD

**Issue by fommil** [lemurheavy/coveralls-public#747]
This project https://github.com/outworkers/phantom is proprietary but is using your open source service.

Please restrict their usage, as it makes it unfair to other organisations who have released free / libre software versions of their software to make use of the community support, not to mention your paying customers.

**Comment by nickmerwin** [comment]
Hi @fommil, we don't actively distinguish the license of the projects who's code we're tracking coverage for. We want to be as code-agnostic as possible.

But thank you for the suggestion.
