### ISSUE TITLE
deeper coverage history graphs

### ISSUE THREAD

**Issue by snarfed** [lemurheavy/coveralls-public#749]
the per-repo coverage history graphs on the user page are great!

<img width="857" alt="screen shot 2016-03-31 at 5 02 15 pm" src="https://cloud.githubusercontent.com/assets/778068/14194349/63173230-f762-11e5-93c7-e35c2a0f5836.png">

...but they're pretty bare bones. it'd be nice to expand them into a full feature. rendering in the foreground with labels, customizable time window, etc. bonus points would be to graph just a subset of files based on path, search, etc.

the simplest first step could just be timestamp labels on the existing graphs so you know the time window they're displaying.

thanks in advance!

**Comment by nickmerwin** [comment]
Thank you for the suggestion @snarfed! We're working on revamping these currently and will def add more control.

Closing for now, stay tuned!
