### ISSUE TITLE
Local Coverage Does Not Match Coveralls Coverage

### ISSUE THREAD

**Issue by Miserlou** [lemurheavy/coveralls-public#751]
My local coverage is 100%, but my Coveralls coverage is 96.3%.

Any reason for this? Does Coveralls not respect pragma: no cover?

**Comment by joshrlesch** [comment]
Im getting the same thing with JaCoCo. After running the coverage tool locally and viewing the generated html, it says that I have 7% coverage. But coveralls says I only have 5.931%
