### ISSUE TITLE
Is the random 422 error: `Couldn't find a repository matching this job` a code word for `you are sending coverage request too frequently`?

### ISSUE THREAD

**Issue by bitinn** [lemurheavy/coveralls-public#752]
If yes, then maybe a better message is needed and I really want to see an example on how to send coverage report less frequently when you have testcases that run multiple times on Travis CI (eg. we run testcases for node v0.10, v0.12 & latest, should I send coverage report only once?)

If no, then I still see random failure for a perfectly fine build, eg. https://travis-ci.org/bitinn/node-fetch/builds/120379861

**Comment by papandreou** [comment]
As far as I know, you are supposed to send the coverage report for every build, as different node.js versions might exercise different lines of code. The combining the coverage reports is part of the service provided by coveralls.

**Comment by lcalvy** [comment]
I confirm, that i also randomly receveid same error message

```
Failed to submit 'test/coverage/mergelcov.info' to coveralls: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
>> WARNING: Failed to submit coverage results to coveralls
```

**Comment by strarsis** [comment]
Same issue occurred for one test in Travis: https://travis-ci.org/svg/svgo/jobs/221976154#L1045
