### ISSUE TITLE
Badge does not update

### ISSUE THREAD

**Issue by s-a** [lemurheavy/coveralls-public#760]
The badges of my projects will not update and are in state "unknown" forever at https://github.com/s-a/user-appdata and https://github.com/s-a/ntcc.

**Comment by nickmerwin** [comment]
Hi @s-a Coveralls hasn't received any coverage data for those repos yet:
https://coveralls.io/github/s-a/user-appdata?branch=master
https://coveralls.io/github/s-a/ntcc?branch=master

You'll need to set up a Coveralls integration library for your test suite running on Travis to get data posted to Coveralls.

Thanks!
