### ISSUE TITLE
Private Repo | 422 | Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by mcalhoun** [lemurheavy/coveralls-public#767]
I have just signed up for the pro service and we're building on travis-pro. I've authorized the repo through coveralls and it shows up on my list of repos in coveralls.

This is a node project, so we're using grunt-coveralls. When we run the "grunt coveralls" task, we're getting a 422. Not sure what to do to troubleshoot this?

> > Done. Minimum coverage threshold succeeded.
> > Running "coveralls:src" (coveralls) task
> > Failed to submit 'coverage/lcov.info' to coveralls: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
> > Failed to submit coverage results to coveralls
> > Warning: Task "coveralls:src" failed. Use --force to continue.
> > Aborted due to warnings.
> > npm ERR! Test failed.  See above for more details.
> > The command "npm test" exited with 1.

**Comment by mathieujobin** [comment]
also getting this error at the end of the rspec run

[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity

push properly worked at the end of cucumber though... 
but it pushed my private repo data to an open source repo

**Comment by dijs** [comment]
Also getting this error.

My story: https://github.com/lemurheavy/coveralls-public/issues/703#issuecomment-222791888

**Comment by powerman** [comment]
Same here. I'm using Go, repo is https://coveralls.io/github/inCaller/srv-wakeup
```
$ goveralls -coverprofile=cover.out -service=travis-pro -repotoken=MYTOKENHERE
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
```
I've tried, without luck:
- sync repo on coveralls
- regenerate coveralls token
- delete and add repo on coveralls

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861
