### ISSUE TITLE
Create an API or CLI for enabling repos.

### ISSUE THREAD

**Issue by jamestalmage** [lemurheavy/coveralls-public#769]
You can create a new GitHub repo and enable Travis support with two simple commands:

```
$ hub create
$ travis enable
```

It is unfortuneate that you can't do the same for coveralls. Currently it is the only step in creating a new module where I have to touch a browser. Having an equivalent `coveralls enable` command would make setting up new repos so much nicer.

**Comment by adigherman** [comment]
Based on this https://coveralls.io/api/docs, you can use curl to do:
`curl -d {"repo": {"service": "github","name": "<your repo slug>","comment_on_pull_requests": false,"send_build_status": true,"commit_status_fail_threshold": <your defined fail threshold>,"commit_status_fail_change_threshold": null}} -H "Content-Type: application/json" -H "Authorization: token <your coverall generated token>" -X POST https://coveralls.io/api/repos`

**Comment by nickmerwin** [comment]
Thanks @adigherman that's correct, closing issue.
