### ISSUE TITLE
API read requests with repo-token for private repo 500

### ISSUE THREAD

**Issue by snarfed** [lemurheavy/coveralls-public#773]
just fyi, when i try to use the API to get recent coverage data for a private repo with a repo-token, i consistently get a 500:

``` sh
$ curl 'https://coveralls.io/github/ColorGenomics/color.json?repo-token=...'
{"status":"500","error":"Internal Server Error"}
```

same if i add `?page=1`.

public repos work fine:

``` sh
$ curl https://coveralls.io/github/snarfed/bridgy.json
{"created_at":"2016-05-05T16:25:20.885Z","url":null,"commit_message":"test_handlers: minor noop cleanup","branch":"master","committer_name":"Ryan Barrett","committer_email":"git@ryanb.org","commit_sha":"e0111d75765312e7e815a955b91aadb2fd5f1411","repo_name":"snarfed/bridgy","badge_url":"https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_92.svg","coverage_change":0.0,"covered_percent":92.4860853432282}
```

thanks in advance!

**Comment by snarfed** [comment]
fwiw, i also get a 500 for a private repo if i omit `repo-token`.

**Comment by eshares-chris** [comment]
it's repo_token

**Comment by snarfed** [comment]
ahhhhh so it is! thank you!

coveralls people, you might want to improve the error handling so you don't 500, and ideally return a better error message, but up to you. feel free to close otherwise.
