### ISSUE TITLE
mismatch between coverage change reported in email and on PR page

### ISSUE THREAD

**Issue by drammock** [lemurheavy/coveralls-public#774]
I just got an email saying this:

> Coverage decreased (-13.1%) to 77.687% when pulling 878f894 on drammock:read-events-warning into 40b668f on mne-tools:master.

But when I view the PR on GitHub a few seconds later, I see a coveralls comment:

> Coverage: 91%
> Coverage increased (+0.03%) to 90.837% when pulling 878f894 on drammock:read-events-warning into 40b668f on mne-tools:master.

This is not the first time I've seen this; it's been happening for at least a month.

**Comment by sambrightman** [comment]
I see this with a change of 0.0% - it looks like a subtraction that is the wrong way around. E-mail says coverage decreased by 91.5% to 0.0% but PR page says 91.5% coverage, 0.0% change.
