### ISSUE TITLE
"Your repos are syncing..." spins forever

### ISSUE THREAD

**Issue by CharlesWarsh** [lemurheavy/coveralls-public#780]
I am having trouble getting "Your repos are syncing..." to complete. I don't know if broken or simply taking a long time. How long should that take?

**Comment by trodrigues** [comment]
Same here. If I look at the browser network inspector, after pushing the button I see a failed request to pusher.

**Comment by Khaledgarbaya** [comment]
Same here, pusher is returning a 400 BadRequest

**Comment by nickmerwin** [comment]
Hi all, we're aware of that response from Pusher, but it's not effecting the sync'ing process. 

If your repos never sync it's a different issue (even after a refresh) -- if you have access to a lot, it can take some time gathering them all from Github. Let me know if that's the case.

Thanks!

**Comment by trodrigues** [comment]
Hi! Yes, that turned out to be a red herring. One of our coworkers recently invalidated all our 3rd party app authorizations on github during a security audit and we hadn't really noticed coveralls wasn't really aware of our org anymore.

**Comment by jackfranklin** [comment]
Hey, I work for Pusher and if it is an issue at our end please let me know, or email support at pusher.com 👍

**Comment by OpenDog** [comment]
It is still happening to me ...

**Comment by tripu** [comment]
It's happening to me now, too.

**Comment by joshuaquek** [comment]
same here :(

**Comment by lizz24** [comment]
me too, it is syncing forever

**Comment by seunkoko** [comment]
me too!!
