### ISSUE TITLE
Changed Organization of Repo (broken status / details)

### ISSUE THREAD

**Issue by matt-newell** [lemurheavy/coveralls-public#781]
I created a public repo http://github.com/matt-newell/generator-force but then later transferred ownership to http://github.com/CodeScience/generator-force. Next as admin I linked the CodeScience repo to coveralls but I still see the broken status image and no stats. 

I think the issue may have been me not being admin when the repo was transferred. 

Any help to get this working again is much appreciated.

**Comment by bmcfee** [comment]
I'm seeing a similar problem.

I transferred a public repo from my account to an organization, and after some fddling, the new name shows up on coveralls.io and reports from travis work as before.  However, coveralls no longer sends status updates back to github.

**Comment by bmcfee** [comment]
One additional update on this:

It's still broken (no status responses), but I've also noticed that the new organization does not show up on my "add repos" index.  However, the webhook is enabled for the org on github's end.  Maybe this is the source of the problem?
