### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by rabbitstack** [lemurheavy/coveralls-public#784]
I have an AppVeyor CI pushing the test reports to Coveralls. I'm not able to view the sources of the covered files. I get this error:

_The file "xxx\xxx.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated._

The repo name is rabbitstack/fibratus

**Comment by aimeos** [comment]
Same for us, e.g.
https://coveralls.io/builds/5713311/source?filename=ext%2Fai-payments%2Flib%2Fcustom%2Fsrc%2FMShop%2FService%2FProvider%2FPayment%2FAuthorizeAIM.php

There's no way to change the root directory and removing the `ext/`part

**Comment by rabbitstack** [comment]
Can anyone shed some light on this?
