### ISSUE TITLE
Information not updated, branch selector not showing all branches

### ISSUE THREAD

**Issue by goanpeca** [lemurheavy/coveralls-public#788]
Although the repo has received data
https://coveralls.io/github/ContinuumIO/navigator

The percent does not appear
![image](https://cloud.githubusercontent.com/assets/3627835/15519478/481a621a-21c7-11e6-9b14-a52eca8eb194.png)

Also the branch selector dropdown does not display all the branches

![image](https://cloud.githubusercontent.com/assets/3627835/15519505/60dda140-21c7-11e6-8523-93e293b92a1e.png)

The badge also displays **unknown**

**Comment by goanpeca** [comment]
Since may 25th no answer here or on the ZenDesk help tracker...

>Your request (885) has been received and is being reviewed by our support staff.
To add additional comments, reply to this email.

Being a paid customer, this is really showing a bad service...

**Comment by nickmerwin** [comment]
Hi @goanpeca all of your builds are marked as Pull Requests, e.g.:

![image](https://cloud.githubusercontent.com/assets/1129/16390705/f90779e0-3c58-11e6-82dc-85992080914e.png)

So the coverage data within won't be applied to your overall coverage levels. Only non-pull request builds will be factored into the badge / graphs.

**Comment by goanpeca** [comment]
@nickmerwin, so what I am suppose to do? or what am I doing wrong...?

**Comment by cioreposervices** [comment]
Looks like he closed your issue....

**Comment by nickmerwin** [comment]
@goanpeca could you trigger a build using "coveralls debug" (as documented here https://github.com/coagulant/coveralls-python#troubleshooting) and email me the build output?

nick@coveralls.io

**Comment by goanpeca** [comment]
@nickmerwin as in my local machine? or as in a travis machine through a PR ?

**Comment by nickmerwin** [comment]
@goanpeca from Travis, thanks.
