### ISSUE TITLE
coverage for different environments/python versions 

### ISSUE THREAD

**Issue by cleder** [lemurheavy/coveralls-public#80]
I have some code that supports python 2 and 3 with and without lxml. depending on the configuration not all code is executed. 

e.g: https://coveralls.io/r/cleder/fastkml

a) I like to see the code that is not covered by any of the test runs 

b) It seems to me that the coverage does not take into account that code may be covered in one test run but not in another

**Comment by ramsey** [comment]
I'm experiencing a similar issue here: https://coveralls.io/builds/2162054

I'm running tests on PHP 5.3, 5.4, 5.5, 5.6, and 7.0—jobs 25.1, 25.2, 25.3, 25.4, 25.5, and 25.6, respectively, at the link above.

In PHP 5.3 and 5.4, all lines of the code should run and have 100% code coverage, and they do. However, I understand and expect that none of the lines of code should run in PHP 5.5, 5.6, and 7.0, however, I want the tests to still run and they should all pass (as you can see they are doing on Travis CI).

Unfortunately, the aggregate result in Coveralls comes out to 84.06% lines covered, which isn't really true.

I'm not sure how you could address this, but I definitely expect 0% coverage for some of these builds, while I expect 100% coverage for others. It's just a result of what it is I'm testing, but for my README badge to show 84% coverage is misleading.
