### ISSUE TITLE
coverage badge not updated

### ISSUE THREAD

**Issue by KhagayN** [lemurheavy/coveralls-public#800]
The coverage has increased and is shown on the coveralls online site but, not on the GitHub repo.

Problem happening for mskilab/gTrack repo. 

-Thanks

**Comment by avysk** [comment]
Same here, avysk/squotter repo.

**Comment by siaw23** [comment]
same with me ;)

**Comment by KhagayN** [comment]
coverage badge has been updated. thanks.
