### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by pixelass** [lemurheavy/coveralls-public#804]
When I press sync basically nothing happens.  
- The listed repos are either old or do not exist anymore.  
- new repos and organizations are not listed
- Organizations I don't belong to anymore are still listed.

No errors in the console.  
I get the message: "Your repositories are being refreshed!"  but that's it

**Comment by pixelass** [comment]
Seems to work after logout & login

**Comment by ararslan** [comment]
I'm having the same issue except logging out and logging back in doesn't fix it for me. 😕

**Comment by dwmkerr** [comment]
Same here, no response from coveralls on online chat support, github or twitter. Pretty disappointing service, probably going to switch to Codecov

**Comment by zmarcantel** [comment]
Same issue. Just spinning with the ` Your repos are syncing...` message even after multiple log out & login attempts. Even logged out and in of github. Github status seems to be fine....

**Comment by Ismael-VC** [comment]
Seems to be the same issue as https://github.com/lemurheavy/coveralls-public/issues/822

**Comment by Ismael-VC** [comment]
> Seems to work after logout & login

I think I've found the solution, or at least it worked for me. In my case the trick was not to logout and login again, but to **unlink** my account from GitHub and then link it again.

This is done in the *account* section:

* https://coveralls.io/account

![image](https://cloud.githubusercontent.com/assets/4594825/19209788/b62a69b4-8cd7-11e6-8a71-8515694ae475.png)

After that it worked **instantly**. 🎉

**Comment by kako-nawao** [comment]
So, still nothing, huh?

**Comment by bbttxu** [comment]
I had this issue and unlinking my Github account, and then signing back in via Github, showed the "missing" repositories in the Repos section, per Ismael-VC's suggestion. The data from previously linked repositories remained as well.
