### ISSUE TITLE
After turning private repo public, cannot get to the repo detail page

### ISSUE THREAD

**Issue by magemello** [lemurheavy/coveralls-public#807]
I turned some of my private repos public, but can no longer get to the detail page:

https://github.com/Alfresco/alfresco-ng2-components
https://github.com/Alfresco/generator-ng2-alfresco-app
https://github.com/Alfresco/generator-ng2-alfresco-component
https://github.com/Alfresco/alfresco-js-api

Can anyone helps me with that?
Thank you

**Comment by magemello** [comment]
Guys 2 days without answer, I have also sent a message to your support but no answer either....and we have a paying subscription :|

**Comment by magemello** [comment]
5 days...

**Comment by magemello** [comment]
8 days...any hope is lost we are switching to another tool

**Comment by magemello** [comment]
11 days...we switched to another tool 👎

**Comment by crisnieto** [comment]
Hi @magemello, could you tell me what tool are you using now? We are having the same support experience and evaluating to change the tool.

**Comment by magemello** [comment]
https://codecov.io
