### ISSUE TITLE
Source code not available (Bitbucket / Appveyor)

### ISSUE THREAD

**Issue by dam5h** [lemurheavy/coveralls-public#813]
I am unable to browse source code in coveralls.io.  I am on a paid plan with a repo on Bitbucket and CI server is Appveyor.  The help screen says to update root directory of my CI environment, which I tried but the "Update" button doesn't seem to bring down the code.  How can I configure things so that my source is browsable in coveralls?

Thanks!
Dave

**Comment by nickmerwin** [comment]
This is fixed for Bitbucket repos with windows-style backslashes in source paths. 

Thanks!
