### ISSUE TITLE
Cannot access notifications settings (non existent)

### ISSUE THREAD

**Issue by dam5h** [lemurheavy/coveralls-public#814]
When I look at your documentation for notifications it says there will be a button on the Repo detail page, however I don't see any such button on my repo detail page.  I also I only have the most basic settings on the settings page.  It does not show anything about "Allow Pull Request Comments".

Also I see no instructions on how to enable pull request access for the @coveralls bot.

This is all for a private repo on bitbucket.  I connect the coveralls account to our company bitbucket group and when I look at my subscription page it shows the company name but has nothing after "Managed By:".  Perhaps since I am a user within the company group it doesn't recognize me the admin?  I am the team admin and owner of the bitbucket as well as coveralls accounts, but I cannot confirm admin status on coveralls and wonder if this is why settings are invisible for me?

Thanks

**Comment by nickmerwin** [comment]
Closed to take to email. Thanks.
