### ISSUE TITLE
Badge doesn't update on private repo

### ISSUE THREAD

**Issue by pradyuman** [lemurheavy/coveralls-public#816]
I have a private repo, and the badge never updates. It's been 4-5 hours and my badge still hasn't updated. I've looked up everything about the aggressive image caching on Github, but none of that are things I can fix as far as I know.

How can I get these badges to update as fast as my Travis ones?

**Comment by pradyuman** [comment]
Bump - does coveralls even have a support team?

**Comment by afinetooth** [comment]
https://github.com/lemurheavy/coveralls-public/issues/1828
