### ISSUE TITLE
[SYNC REPOS] button on ADD REPO page doesn't work for public repos

### ISSUE THREAD

**Issue by Zloy** [lemurheavy/coveralls-public#822]
On `/repos/new` I press [SYNC REPOS] button, it refreshes the page, but the repositories list stays unchanged, so outdated. No error messages, no errors in Firebug, just doesn't work.

**Comment by Sweetchuck** [comment]
I can confirm this bug report

**Comment by Ismael-VC** [comment]
Seems to be the same issue as: https://github.com/lemurheavy/coveralls-public/issues/804

I can confirm that this still happens.

![image](https://cloud.githubusercontent.com/assets/4594825/19168146/5302adc8-8bd4-11e6-89c9-2e5808fad7ec.png)
