### ISSUE TITLE
Coveralls npm package never sends data from travis. Tried 10 times

### ISSUE THREAD

**Issue by nojvek** [lemurheavy/coveralls-public#823]
Always gives error:

422 {"message":"Couldn't find a repository matching this job.","error":true}

The error message is pretty vague. 

Here's my coveralls.yml

```
service_name: travis-pro
repo_token: xxx
```

running from mac works "cat coverage/lcov.info | node_modules/.bin/coveralls"

Same thing on travis fails every single time.

The whole experience of setting up coveralls is pretty complicated.  I wish it was simpler

**Comment by JackStat** [comment]
I have the same issue. The repo on github is private and in an organization. I am a public member of that organization. What have I tried?

- Refreshed the token
- Created coveralls.yml and .coveralls.yml

Pulling apart the API request that is sent I am getting an internal server error status code: 500
