### ISSUE TITLE
Only I can view the code coverage

### ISSUE THREAD

**Issue by ARenfroe** [lemurheavy/coveralls-public#827]
I created the account in such a manner that should have allowed anyone with git access to our private repo to be able to view the coverage stats.  Unfortunately I am the only one who can see the coverage reports for the private repo.  Do you have any guidance?
@anjin 
@nickmerwin

**Comment by ARenfroe** [comment]
@wilg is there any support...?
@anjin 
@nickmerwin

**Comment by anjin** [comment]
@ARenfroe have you had them refresh the GitHub scope by going to https://coveralls.io/refresh?private=true ?

**Comment by ARenfroe** [comment]
@anjin 
Yes I tried that.  It did not work the first few times for multiple users.  I had them revoke coveralls permissions from github and set it back up and the reports displayed.  

This led to a follow up question.  Is there any way we can limit coveralls access to our repos without interrupting the coverage reports?
