### ISSUE TITLE
Foreign builds/commits in private coveralls repo

### ISSUE THREAD

**Issue by MainAero** [lemurheavy/coveralls-public#831]
Seems that coveralls messed up something.
Commits/Builds (travis-ci) of others appears in one of our private repos.

Regenerating token does not help.

**Comment by aullman** [comment]
I'm getting this issue as well. I see a commit from someone that does not contribute to our project showing up as the most recent commit. I also see that the branch name is wrong. I use travis-ci.com and the Node coveralls.js project.

@MainAero did you ever figure out this issue?
