### ISSUE TITLE
Unable to sync my private repos

### ISSUE THREAD

**Issue by dwmkerr** [lemurheavy/coveralls-public#832]
Hi team.

I'm a pro subscriber, I'd like to add another pro subscription. At the moment I've tried re-syncing github a number of times and the 'syncing' message never disappears.

Can you help?

Cheers,

Dave

**Comment by kyrylo** [comment]
We have the same issue, except we are on a free plan, I believe. We would like to try the Trial plan, but this bug prevents us from upgrading.

**Comment by WhileLoop** [comment]
I am having the same issue.

**Comment by dwmkerr** [comment]
I switched to codecov.io, couldn't get any support from coveralls. Can't recommend them any more, would suggest codecov.
