### ISSUE TITLE
504 error when submitting coverage from Travis

### ISSUE THREAD

**Issue by mandeep** [lemurheavy/coveralls-public#834]
When submitting to coveralls from Travis CI, I receive the following error that results in no coverage being reported:

```
Coverage submitted!
Failure to submit data. Response [504]: <!DOCTYPE html>
```

A link to the full build is here: https://travis-ci.org/mandeepbhutani/Mosaic/builds/152141900

**Comment by Slashgear** [comment]
:+1:
Same here, nothing in the status page, but it seems the server are not ok.

**Comment by Primordus** [comment]
I think I'm getting a similar error, for me it gives the following:

```
Upload error: JSON decode error:
1
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>

...
```

My full build log can be found here: https://travis-ci.org/Primordus/lua-quickcheck/jobs/152160400

Note: sometimes seems to work, sometimes fails?

**Comment by bakwc** [comment]
+1 https://travis-ci.org/bakwc/PySyncObj/jobs/152181122

**Comment by kuba-orlik** [comment]
[Also affected](https://travis-ci.org/sealcode/sealious/builds/152234351#L934)

**Comment by oshalygin** [comment]
[This build as well](https://travis-ci.org/oshalygin/FSAESimRevamp/builds/152296220)

It started happening approximately 2 days ago.  Any input would be stellar.  Tried running locally and got a 422 which is related to not having the req token(expected).

**Comment by johnyf** [comment]
Looks the same as #504, #411, #564.

**Comment by nickmerwin** [comment]
Hey all, we've identified a server performance degradation and are working on it now:

http://status.coveralls.io/incidents/yhfwntc6bw7r

**Comment by nicolaasuni** [comment]
I am still experiencing 504 error:
https://travis-ci.org/miracl/maas-sdk-python/jobs/152363127

**Comment by Bilge** [comment]
@nickmerwin Why is there no link to the status site from the main site?

**Comment by michaelaye** [comment]
Still happens: (https://travis-ci.org/michaelaye/planet4/builds/211128898)
Interestingly, the data arrived well at coveralls.io though: https://coveralls.io/builds/10593863 (note the correct build number 212 from Travis.

**Comment by oshalygin** [comment]
exiting this discussion, nothing but issues with coveralls lately.

**Comment by colecrtr** [comment]
Just received a 504 error after submitting coverage.

```
Submitting coverage to coveralls.io...
Coverage submitted!
Failure to submit data. Response [504]: <!DOCTYPE html>
...
```

**Comment by nickmerwin** [comment]
@colecrtr could you link to your repo and CI build please?

**Comment by colecrtr** [comment]
> @colecrtr could you link to your repo and CI build please?

@nickmerwin Sadly I cannot, it is a private repo & CI pipeline.

**Comment by nickmerwin** [comment]
@colecrtr ok you can email us here: support@coveralls.io

We'll take it from there, thanks!
