### ISSUE TITLE
Coveralls package for node.js fails to submit coverage from travis-ci

### ISSUE THREAD

**Issue by epoberezkin** [lemurheavy/coveralls-public#837]
For package https://coveralls.io/github/epoberezkin/ajv-merge-patch

Coveralls response status code is 504: https://travis-ci.org/epoberezkin/ajv-merge-patch/jobs/152277378
Response is the page with the title "Coveralls :: Oops, something went wrong (500)"

Adding / removing repo_token doesn't help

**Comment by nickmerwin** [comment]
Hi @epoberezkin I see that there's a successful build in your repo now.

Thanks!
