### ISSUE TITLE
Redundant comments on coveralls globally

### ISSUE THREAD

**Issue by CrazyPython** [lemurheavy/coveralls-public#838]
See [this pull request.](https://github.com/tqdm/tqdm/pull/240) Coveralls made 5 of the same comments about the same hashes (same commits). In addition, it also crashes Travis CI upon inspecting the logs - which it shouldn't, given the fact that it's a README change.

**Comment by nickmerwin** [comment]
@CrazyPython we're investigating the redundant comments.

Also the single 422 error in job 3 (https://travis-ci.org/tqdm/tqdm/jobs/152735481) looks like it was a Travis API error.

**Comment by CrazyPython** [comment]
@nickmerwin I see. However, no config changes occurred, and this coincided with the redundant comments.

**Comment by CrazyPython** [comment]
@nickmerwin this is still occurring. I committed an empty commit (no files changed with the magic of client-side HTML inspector) and Coveralls spammed 5 messages.

**Comment by nickmerwin** [comment]
@CrazyPython ok we have fix in place for the redundant comments. Also confirmed that job failed due to a Travis API error -- working on better handling.

Thank you!

**Comment by CrazyPython** [comment]
@nickmerwin This still occurs with Coveralls. Take a look at [this issue](https://github.com/tqdm/tqdm/pull/251#issuecomment-243468502). I suppose you have deployed by now.

**Comment by lrq3000** [comment]
Sorry I deleted the redundant comments in https://github.com/tqdm/tqdm/pull/251#issuecomment-243468502, but it indeed still happens. If you have any idea what we could try to fix this issue, it would be great, because it's quite tedious to delete redundant comments manually!
Incidentally, I think it began to happen with the activation of Travis cache?

**Comment by CrazyPython** [comment]
@nickmerwin No response yet, it's been four days. I'm not so sure about the quality of your testing. 💢 💢
