### ISSUE TITLE
Remove a build

### ISSUE THREAD

**Issue by BertrandBordage** [lemurheavy/coveralls-public#84]
As you can see, the first build of https://coveralls.io/r/dezede/dezede was using a bad configuration file (it was testing my apps plus all dependencies…).

With this erroneous build, I can't read the timeline.  Plus it says I'm a "bad tester", which is quite unpleasant.

Is there a way to remove that build?

**Comment by daniele-orlando** [comment]
+1

**Comment by patrickpilch** [comment]
:+1:

**Comment by WhileLoop** [comment]
+1

**Comment by tgsmith61591** [comment]
+1

**Comment by ELLIOTTCABLE** [comment]
(Just a little note: GitHub now supports emoji-reactions to Issue comments, which has become the de-facto standard for “voting” on Issues.

If you want to `+1` this, I suggest you click the :+1:-react on the OP; as this avoids sending an e-mail to everybody who's ever commented on this Issue … as this reply itself inevitably will! 😰)
