### ISSUE TITLE
Relevant and covered line graph have wrong color

### ISSUE THREAD

**Issue by kroeckx** [lemurheavy/coveralls-public#842]
It seems that the curves with the relevant and covered lines are switched.  When the coverage goes up without the relevant lines changing, the grey curve gets higher.  According to the legend that's the relevant lines.  The numbers in the legend seem to be correct, but the color wrong.

**Comment by tclose** [comment]
I have noticed this too

**Comment by kroeckx** [comment]
I think this was fixed now, when the coverage goes up the red line gets higher.
