### ISSUE TITLE
Can't remove / disable coveralls for repo (Pro)

### ISSUE THREAD

**Issue by maciejmrowiec** [lemurheavy/coveralls-public#844]
On/Off switch in the interface for switching on/off coveralls for repository is blocked, I can enable new repo but can't disable existing one.

Tried for several repos where I'm an admin on github.

**Comment by raymondschouten** [comment]
I'm also unable to disable previously enabled repositories:
https://coveralls.io/github/darkwebdesign

I even tried to delete my account, but after re-creating it, my repositories are still there and enabled!

**Comment by Zlate87** [comment]
I have the same problem. Any update on the issue?

**Comment by ChristianKuehnel** [comment]
same for me

**Comment by QCaudron** [comment]
Same issue here.

**Comment by damorton** [comment]
👍

**Comment by boberj** [comment]
The toggle can only be used to add repositories. To delete one, you have to go to the settings for the repository (i.e. `https://coveralls.io/github/<user>/<repo>/settings`). 

From Coverall's [blog](http://blog.coveralls.io/2013/02/20/Onboarding-Repos):

> We have deployed a new interface for the Add Repository page that now allows you to toggle repos on [...]. One flip of a toggle is all it takes. However, for safety, you cannot remove a repo the same way. To do that you will need to go to that repository’s page on Coveralls and, if you are the owner, click the “Delete Repo” button.

**Comment by cedx** [comment]
This does not seeem to work for old repositories that don't have any code coverage.
Some examples:
https://coveralls.io/github/cedx/apinegoce.cs
https://coveralls.io/github/cedx/miniframework.cs

If I access the settings page (https://coveralls.io/github/cedx/apinegoce.cs/settings), it only shows the readme badge and nothing else. So I can't remove these projects... that appears on top of my profile page (https://coveralls.io/github/cedx). You must scroll down to see the active projects (!).
