### ISSUE TITLE
Github signin fails

### ISSUE THREAD

**Issue by jgarzik** [lemurheavy/coveralls-public#846]
Chapter I
- In past ~24 hours, coveralls is indefinitely in-process on public repo https://github.com/jgarzik/picocoin ; Travis-CI is succeeding as expected.
- Previously, coveralls has worked fine for this repo, used with great success (thanks for a great service!)

Chapter II
- Attempt to login to https://coveralls.io to see what's going on...
- Homepage loads (presumably no auth cookie set)
- Sign in via github ('jgarzik' on github)
- Returns "five zero zero" page
- Close window
- Homepage itself now returns "five zero zero, it's gone pear shaped"

ETA, Chapter III:
- coveralls returns build output successfully.  Login to website still fails with five-zero-zero.

**Comment by stefano-maggiolo** [comment]
Is github login working now? I was starting to use coveralls a couple of days ago, and I was unable to enable repository (status 422 retrieving "repos"). Now I cannot even login (500 page when signing in with github). Is this expected to be solved?

**Comment by gonzaloserrano** [comment]
Hey there, maybe it's related: I haven't opened coveralls in a while, and have been used it with my company (Social Point) for some repos for some months now. Clicking in a report link gave permission error but after login in i didn't see any of my company's repos. Tried several times and nothing. Then i deleted the site cookie and tried again and now works.

**Comment by stefano-maggiolo** [comment]
Just checked again, same 500 page after trying to sign in with github, even in an incognito window.

**Comment by nickmerwin** [comment]
Hi all, we've pruned some old data that was causing these errors, you should be able to login without issue now.

Thank you!
