### ISSUE TITLE
Angular 2 CLI coverage generated on Travis but not shown in Coveralls

### ISSUE THREAD

**Issue by textbook** [lemurheavy/coveralls-public#854]
I'm working on an Angular 2 project, using the Angular CLI, called [Known For](https://github.com/textbook/known-for-web). The basic `karma.conf.js` from the CLI does include generating `lcov`-format coverage, so I thought that getting this information published would be easy.

The coverage on Travis is being calculated (and now displayed, see [build 57](https://travis-ci.org/textbook/known-for-web/builds/162545612)) correctly, and the `coveralls` command I'm running on `build_success`: 

```
cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
```

doesn't raise any errors. Locally, I can see that the `coverage.lcov` file contains what appears to be the correct information, as follows:

```
TN:
SF:/Users/jonrsharpe/WebstormProjects/known-for-web/node_modules/angular2-template-loader/index.js!/Users/jonrsharpe/WebstormProjects/known-for-web/node_modules/tslint-loader/index.js!/Users/jonrsharpe/WebstormProjects/known-for-web/src/test.ts
FN:14,(anonymous_1)
FN:24,(anonymous_2)
FN:31,(anonymous_3)
FN:33,(anonymous_4)
FNF:4
FNH:4
FNDA:1,(anonymous_1)
FNDA:1,(anonymous_2)
...
```

However, the coverage for the [project](https://coveralls.io/github/textbook/known-for-web) shown in Coveralls is _"unknown"_, with the proportion at _"?%"_ and the file list reading _"No data available in table"_. Where is the coverage data getting lost?

I have tried using the same command directly from my machine, using a `.coveralls.yml` file, but still no joy.

**Comment by gund** [comment]
Having exactly the same issue with [this repo](https://coveralls.io/github/gund/ng2-http-interceptor).
Coverage [generated](https://github.com/gund/ng2-http-interceptor/issues/1) with angular-cli as well and no percentage nor coverage data has been displayed except builds.

Help will be much appreciated.

**Comment by harunurhan** [comment]
I am also having the same issue [here](https://coveralls.io/github/inspirehep/ng2-json-editor)
 
Also it seems to be an old issue #661

**Comment by tarlepp** [comment]
Any updates on this? facing the same issue.

**Comment by kucharzyk** [comment]
I have also problem with Coveralls with latest angular-cli

**Comment by netstart** [comment]
This is probably because coverage was not generated.
We need pass --code-coverage (ng test --code-coverage)

See .travis.yml in the
https://github.com/codigorefinado/curso-refinado-angular/

**Comment by textbook** [comment]
@netstart no, the coverage *is* being generated (as above, you can see the summary in the logs); that project predates the `--code-coverage` flag and always uses the coverage reporter, as you can see in [`karma.conf.js`][1].

  [1]: https://github.com/textbook/known-for-web/blob/master/karma.conf.js#L35

**Comment by harunurhan** [comment]
Btw, for me it just started working, It might be some dependency update or internal coveralls fix.

**Comment by textbook** [comment]
It works fine on a [new project](https://coveralls.io/github/textbook/salary-stats) I just set up, too - I'll close this until I figure out if it's still reproducible on the old one.
