### ISSUE TITLE
default branch change

### ISSUE THREAD

**Issue by timc13** [lemurheavy/coveralls-public#862]
Hi, I recently changed the default branch of a private github repo from `develop` to `master`, however this is not reflected in coveralls.  I've tried the Resync with Github button to no avail.

**Comment by kinday** [comment]
Same here. Any ideas?

**Comment by nickmerwin** [comment]
Hi @kinday @timc13 could you let me know what the repo names are? I'll take a look.

**Comment by kinday** [comment]
@nickmerwin, `RushPlay/betser`: `develop` → `master`

**Comment by steveschnepp** [comment]
Same here with `munin-monitoring/munin` : `devel` → `master`. Seems there's a global issue.

**Comment by jonathanong** [comment]
same here

**Comment by r3m0t** [comment]
@nickmerwin `festicket/festicket`

**Comment by tsieprawski** [comment]
Same here with `tsieprawski/ubjsc`, just that branch name does not originate from git (default: `master`), but from mercurial (default: `default`).
