### ISSUE TITLE
I cannot find repo_token

### ISSUE THREAD

**Issue by chylli** [lemurheavy/coveralls-public#869]
From doc: 

> The secret token for your repository, found at the bottom of your repository's page on Coveralls.

But I cannot find the repo token on that page:
Sorry I cannot post the picture here. But I really cannot find the repo_token at that page.

And I cannot drop & re-add my repo to coveralls.

**Comment by nabot93** [comment]
Same issue here: https://coveralls.io/bitbucket/ring_team/ringmesh
