### ISSUE TITLE
Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by chylli** [lemurheavy/coveralls-public#871]
When I do a report with following .coveralls.yml:

```
service_name: travis-pro
repo_token: rZZqaGuPO8EpeiMlP66kE6yzpQNlLYuyw
```

https://github.com/binary-com/perl-FlyBy/blob/e7bee682cd2120d02aade6e1091c6ceb40ad8f6e/.coveralls.yml

It will report this error:
`Couldn't find a repository matching this job.`

If I update the report with this command by hand:
`TRAVIS=false cover -report coveralls`
or I set service_name as `travis_ci`, the result will be ok.

Pleases refer to this issue https://github.com/kan/coveralls-perl/issues/16

**Comment by joscha** [comment]
references #997

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861
