### ISSUE TITLE
Billing issues

### ISSUE THREAD

**Issue by sarahlouthorne** [lemurheavy/coveralls-public#872]
Hi

My organisation 1minus1 Limited is being billed around £20 per month, however the only invoice that we receive is to George1minus1 and is for $5 per month. We've tried to cancel the account and George has raised multiple tickets with you for assistance.

Can someone please get in touch with us to provide support, thus far the support offered has been less than adequate and we've been paying a subscription in the mean time which should have been cancelled.

**Comment by chasevida** [comment]
Just wanting to jump in here and see if this was ever resolved?
