### ISSUE TITLE
Wont update SimpleCov locally

### ISSUE THREAD

**Issue by rjrobinson** [lemurheavy/coveralls-public#881]
After in installed, I get a "Outside CI Env, not sending to Coveralls" , but it also is not updating the local coverage. 

How do I get it to update local coverage HTML page again?
If I remove coveralls.wear!, it works fine. I dont want to have to keep adding and removing that line of code.

**Comment by revolter** [comment]
I have this same problem!

**Comment by bytewalls** [comment]
It sounds like you will want the use the `SimpleCov::Formatter::HTMLFormatter` alongside the coveralls formatter.

I believe that the `SimpleCov Customization` area on [this page](https://docs.coveralls.io/ruby-on-rails) should help you get there.

**Comment by revolter** [comment]
Yep, the `MultiFormatter` snippet works. Though you should use `MultiFormatter.new([...])` instead of `MultiFormatter[...]`. And not using `Coveralls.wear!` looks like Coveralls will not run on the CI for a newbie like me.

**Comment by rjrobinson** [comment]
pretty stale bot is having a hard time
