### ISSUE TITLE
Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by BotellaA** [lemurheavy/coveralls-public#882]
I am trying to use coveralls.io on my C++ project: https://coveralls.io/bitbucket/ring_team/ringmesh

I have two issues:

- Coveralls does not seem to find the corresponding badge located here: https://bitbucket.org/ring_team/ringmesh
- Using coveralls-cmake (https://github.com/JoakimSoderberg/coveralls-cmake), I manage to get a json file which look like this:

`{
  "service_name": "no_mane",
  "repo_token": "**********************************",
  "source_files": [{
      "name": "include/ringmesh/geomodel/geomodel_indexing_types.h",
      "source_digest": "c325b622d79e3c7a112c04b14c865dd1",
      "coverage": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, null, null, null, null, null, 0, 0, null, 0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
  }, ...
  }]
}`

but I got the message: `{"message":"Couldn't find a repository matching this job.","error":true}`

Thank you for your help!

**Comment by nabot93** [comment]
Actually, I do not have the token of the repository. I used the one related to my account.
So I guess I have the same issue than #869

**Comment by joscha** [comment]
references #997

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861
