### ISSUE TITLE
Coveralls is attributing commits incorrectly

### ISSUE THREAD

**Issue by edcs** [lemurheavy/coveralls-public#883]
I've got this issue on several repos - the commit message and name is being attributed to people who aren't in our organisation and to commits which don't exist. For example:

<img width="1033" alt="screen shot 2016-11-16 at 11 29 00" src="https://cloud.githubusercontent.com/assets/754498/20345702/4a19e55a-abf0-11e6-8098-fa5d2defd7d4.png">

I'm also getting error messages like this in the code coverage view for individual classes:

>The file "app/Http/Controllers/Controller.php" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

The directory structure displayed matches our project structure exactly.

**Comment by evertlammerts** [comment]
Same here:
![image](https://cloud.githubusercontent.com/assets/2683350/20386813/97a102ea-acbd-11e6-8f49-751795df1da4.png)
