### ISSUE TITLE
Too difficult to set root source directory for a repo

### ISSUE THREAD

**Issue by fitzgen** [lemurheavy/coveralls-public#886]
Every time a set up coveralls.io for a Rust project, coveralls.io always misses the leading "src" in every file path, and every time I can't figure out how to set the root source directory for the repo.

I've done this at least three times before, and I still can't remember or figure out how to do it this time...

**Comment by nbigaouette** [comment]
Wow, so I'm not crazy fighting this too! :D

See my attempts: https://github.com/nbigaouette/gitlab-api-rs/pull/10

**Comment by nbigaouette** [comment]
I'm calling my binary like this (using `kcov`):
```
kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern='/.cargo,target' target/kcov target/debug/my_rust_binary-*
```

Note the `target` added in the `--exclude-pattern`. Without it coveralls properly finds the source files without me doing anything (see for example https://coveralls.io/builds/9200321). The file names in the coveralls list have a `src` prefix.

I want to hide code generated by my `build.rs` (automatically generated `serde_types.rs` files) from the coverage, so I add `target` to `--exclude-pattern`.

If I add the `target` to the `--exclude-pattern`, then coveralls will _not_ use a `src` prefix for the source listing, resulting in it not finding the files (see for example https://coveralls.io/builds/9212128).

The _only_ way I was able to let coveralls show my source file _and_ ignore what appeared in the `target` directory was to tell coveralls to set the a prefix of `src`. To do this I clicked on a file in coveralls' listing. Coveralls report that it can't find the file (without the `src` prefix) on github. If I'm _not_ logged in on coveralls.io, it's the only info shown. What I missed was that I needed to be logged in to coverall. If 

I'm logged in and I click on a file listing, I still get the "file not found on github), but then the UI shows me two text fields.

If I recall correctly, the first one is to set the root directory to use. The second one is to use a specific prefix. I had to put `src` in that second text field. Now when I click on a file in a coveralls report, it properly shows the coverage.

Unfortunately I can't get to this UI where the setting is entered. It seems that once it's set, I can't change it! So now I can see the coverage (for example https://coveralls.io/builds/9212128/source?filename=projects%2Fid.rs ), even though coveralls.io still does not show the `src` prefix in the file listing.

**Comment by nbigaouette** [comment]
I was able to find a way to change the prefix.

I found a build that was working initially but that got broken by the change of prefix. For example https://coveralls.io/builds/9200321 . Now clicking on one of the files will say complain that _SOURCE NOT AVAILABLE_ and "The file _src/gitlab.rs" isn't available on github. Either it's been removed, or the repo root directory needs to be updated. _

If you are logged in, you will be able to change either the _Git repo root directory_ or the _Git repo sub directory_.

![image](https://cloud.githubusercontent.com/assets/112988/21060928/111d340c-be18-11e6-966d-d70584d7b9d4.png)

**Comment by PaulRBerg** [comment]
Is there a way to set the "git repo sub directory" using a config file?

**Comment by fredden** [comment]
Has this been fixed? Marking as stale & closing doesn't seem like a good solution if the user experience is still poor. I've not been able to find how to access this setting except via a failed run.

**Comment by afinetooth** [comment]
Hi @fredden. This issue precedes me, but I think presenting the Git Repo Root Directory and Git Repo Sub Directory settings in context was considered sufficient for users experiencing the issue.

If I understand you correctly, you would rather see those settings ahead of time, in SETTINGS, as a user who is familiar with the problem and wants to verify you can address it before proceeding "blindly"? (If I misunderstand, let me know.)

In response I've added a feature request to our backlog to add these settings to the REPO SETTINGS page. Thanks for the input.
