### ISSUE TITLE
details/builds are included from commits in another repo

### ISSUE THREAD

**Issue by matt-deboer** [lemurheavy/coveralls-public#889]
Viewing the coveralls url for my repo https://coveralls.io/github/matt-deboer/dcos-auth-proxy recently shows a build [#28] that is not a part of my repo, and incorrectly skews the coverage report.
I'm showing a build and commit by 'Behdad Esfahbod' which is not the most recent commit, but seems to be negatively affecting the overall results (displaying 40%, when the current results are 75%).

**Comment by davewalk** [comment]
I'm seeing this also - commits, branches and users that have nothing to do with my (private) repo. This is pretty bad - are you doing anything about this? Are you recycling tokens so two different Travis repos are pushing to the same Coveralls token???
