### ISSUE TITLE
coverage unknown

### ISSUE THREAD

**Issue by leonardloo** [lemurheavy/coveralls-public#890]
Hi my coverage is unknown in the ATeamHasNoName/CS207Project master branch. Why is that the case? My Travis is passing.

**Comment by joohoi** [comment]
I'm seeing this as well

**Comment by leonardloo** [comment]
How do we fix that?

**Comment by slivingston** [comment]
This issue seems to be a duplicate of #351

**Comment by slivingston** [comment]
not necessarily duplicate behavior as reported in #351, but the cause might be the same.
