### ISSUE TITLE
Old build covers newer build because it has higher build number

### ISSUE THREAD

**Issue by therooftopprinz** [lemurheavy/coveralls-public#891]
My colleague accidentally used my token in uploading coverage report from other repo. I have regened the token. And now I instructed travis to rebuild. The build was added but the older build gets listed first because it has higher build number. Please fix this 

https://coveralls.io/github/rooftopprinz/propertytree

**Comment by mkfifo** [comment]
This has also been happening for a few of my repositories despite me not 'doing anything'
