### ISSUE TITLE
Some problems with Coveralls now?

### ISSUE THREAD

**Issue by dmitry-ivanov** [lemurheavy/coveralls-public#892]
Hi!

I have a project with Travis and Coveralls integrations enabled:
https://github.com/dmitry-ivanov/laravel-testing-tools

It worked fine yesterday, but today my Travis builds have no effect on Coveralls statistics.
It looks like coverage data was successfully committed to Coveralls, but Coveralls builds are saying
> No data available in table

Coveralls status page shows no errors now.

Help please!

**Comment by nescalante** [comment]
same here

**Comment by dmitry-ivanov** [comment]
It looks like github have some problems now

**Comment by tmaszk** [comment]
same here

**Comment by rdenmark** [comment]
Our company is also observing this behavior across multiple repository builds. Last successful coverage update was ~18 hours ago.

**Comment by nickmerwin** [comment]
Hi all, we're putting through some database updates to mitigate this issue:

http://status.coveralls.io/incidents/yh1xjbhx6zk4

**Comment by dmitry-ivanov** [comment]
@nickmerwin Hi! Thanks for your fix!
It looks like ok now, but `SOURCE FILES` are still empty for me.
It's loading, and loading, and loading... :)
![dmitry-ivanov_laravel-testing-tools___coveralls_-_test_coverage_history___statistics](https://cloud.githubusercontent.com/assets/1286821/20966358/8c4efb66-bc82-11e6-8e42-eb9396df81cf.png)

**Comment by ipjohnson** [comment]
@nickmerwin I've run into the same issue as dmitry with no source files loading

**Comment by dmitry-ivanov** [comment]
@nickmerwin It looks like issue solved. Thanks!

**Comment by tom-lord** [comment]
I'm having the exact same problem as described above.

Was it actually fixed? Only partially fixed? Did the bug get re-introduced in a regression?
