### ISSUE TITLE
Style z-index error

### ISSUE THREAD

**Issue by microshine** [lemurheavy/coveralls-public#896]
![image](https://cloud.githubusercontent.com/assets/7333669/21472381/e25818da-cae7-11e6-882a-989ab8df881c.png)

**Comment by anjin** [comment]
@microshine Where did you see that?

**Comment by microshine** [comment]
OS: Windows 10
Chrome: 55.0.2883.87m

https://coveralls.io/github/PeculiarVentures/node-webcrypto-ossl
