### ISSUE TITLE
Homepages of projects whose name end with ".php" result in 403 errors

### ISSUE THREAD

**Issue by cedx** [lemurheavy/coveralls-public#897]
Hello. I'm using your service for my Open Source projects, and I'm happy :o) But I've encountered an issue with 2 of them:

- https://coveralls.io/github/cedx/enum.php
- https://coveralls.io/github/cedx/free-mobile.php

When I try to access the landing page of these projects, a "403 Forbidden" error is raised by the nginx server.

The coverage is working fine:
- enum.php: https://coveralls.io/builds/9423947
- free-mobile.php: https://coveralls.io/builds/9423956

It's only their homepage that is inaccessible.
Thanks in advance for checking this issue.

**Comment by cedx** [comment]
This project is also affected by this issue:
https://coveralls.io/github/cedx/couchdb.php

Can it be related to the project name extension (e.g. ".php")?

**Comment by cedx** [comment]
Another project affected:  
https://coveralls.io/github/cedx/lcov.php

Very annoying: as you can see, I have numerous project names ending with ".php".

**Comment by cedx** [comment]
The list of projects having an erroneous (403) homepage is growing...

https://coveralls.io/github/cedx/coveralls.php  
https://coveralls.io/github/cedx/lcov.php  
https://coveralls.io/github/cedx/akismet.php

Please, it would be so cool if this issue was fixed. Thanks in advance.

**Comment by mstruebing** [comment]
Mine is affected too:
https://coveralls.io/github/editorconfig-checker/editorconfig-checker.php

**Comment by cedx** [comment]
Any chance to see this issue solved? I'm globally satisfied with the Coveralls service, but I plan to switch to another service just because of this problem. In all my README files, I put a link to the coverage results... and it's currently impossible for my PHP projects.

**Comment by andreskrey** [comment]
Also fails with [readability.php](https://coveralls.io/github/andreskrey/readability.php)

**Comment by andreskrey** [comment]
You can bypass this error by adding a forward slash at the end of the url:

`https://coveralls.io/github/andreskrey/readability.php/`

**Comment by cedx** [comment]
@nickmerwin Do we keep this issue open? A simple notice in the documentation (i.e. https://docs.coveralls.io/) about the slash requirement should be sufficient.

**Comment by andreskrey** [comment]
Links in badges also point to the URL without a forward slash

**Comment by bytewalls** [comment]
Thanks all, we are working on a fix for this for now obviously putting forward slashes will work. Sorry for the inconvenience.

**Comment by cedx** [comment]
Closing this issue as it's not a priority, and I'm starting to doubt that it will be fixed one day (it has been open for more than 2 years). On the other hand, we already have an alternative solution (see comment from @andreskrey) that personally satisfies me.
