### ISSUE TITLE
Builds from semaphore are not shown in coveralls.

### ISSUE THREAD

**Issue by eladams** [lemurheavy/coveralls-public#904]
I've setup as described in the docs:
1. Purchased a trial (5$ - single private repo) subscription from coveralls
2. Added my private repo
3. Created a branch to try coveralls integration, added coveralls gem, added the specified 2 lines code to my spec_helper.rb
3. Specified the COVERALLS_PARALLEL : true  in a semaphore environment variable.
4. Added a webhook to coveralls in semaphore notification settings
5. Built the branch with semaphore, waited for all the specs to run.
6. **Nothing happened in coveralls after the build ended.**

Help.

**Comment by revelt** [comment]
Having same problem. @eladams Did you solved it since?
