### ISSUE TITLE
Renamed repository can't be refreshed

### ISSUE THREAD

**Issue by nickmccurdy** [lemurheavy/coveralls-public#908]
I have a Coveralls project here: https://coveralls.io/github/nickmccurdy/purified

I have renamed it from `purified` to `purespec`. Coincidentally, I also reset all my GitHub account authorizations before I did this, and now that I reauthorized Coveralls I am unable to refresh the rename of this repository. I would see a settings button with the usual refresh tool on other projects, but since I logged back into Coveralls I only see `Repo on GitHub`, and not `Settings, on the left sidebar.

**Comment by ceritium** [comment]
Hi, I have a similar problem, after rename my repo `ceritium/camel_race` to `ceritium/bario` coveralls stopped to show the graph coverage and the badge is always grey. At least coveralls is able to comment in the PR the coverage, but I am not sure if the information is correct.
