### ISSUE TITLE
coveralls.io leaks and displays information from other accounts

### ISSUE THREAD

**Issue by aviaoh** [lemurheavy/coveralls-public#909]
We signed up to coveralls.io today and currently able to see commits from other people _**private**_ repositories. I also searched the committers appears and seems like they don't have common public repo:
![image](https://cloud.githubusercontent.com/assets/22256371/21892658/84838f94-d8e0-11e6-9db9-6bef6b11dca3.png)

Also, pull request number seems to be missing and links to source files and travis are broken. only link that works is link to main repo on github.
Any idea how can we configure coveralls.io to show only our builds and commits?

**Comment by Karnich** [comment]
why is there absolutely no response on this issue? We have the same problem... Basically our commits get registered. The coverage on our files are registered.. but the build number, commit message and branch are not ours and therefore incorrect

**Comment by aviaoh** [comment]
we left coveralls. if i can see other people's data there it make no sense to let them extensive permissions on our repo.
@Karnich - we moved to codecov in case you are looking for alternative :)

**Comment by tbazko** [comment]
+1

**Comment by nickmerwin** [comment]
Hi all, this is a symptom of having `service_name: travis` when it should be `service_name: travis-pro`, more info here:

https://coveralls.zendesk.com/hc/en-us/articles/201342479-Quick-help-For-Common-Problems#random

> Travis uses non-unique job id's between its free and pro services, so when Coveralls doesn't know that your service-name is Travis-pro, it looks up the info for those job ids using the free Travis API -- that's why they will show random committers, etc. The opposite cannot happen with the proper credentials, so you don't need to worry that your data is leaking out. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis's pro API.

**Comment by tbazko** [comment]
I do have service_name: travis in .coveralls.yml
