### ISSUE TITLE
Coverage Unknown

### ISSUE THREAD

**Issue by collins-b** [lemurheavy/coveralls-public#910]
Coverage displaying unknown for the past one week.What can be the issue?

**Comment by ShMcK** [comment]
Having the same issue for the past month.

Although test coverage listed in the table is always "100%", the badge status remains "coverage: unknown".

https://coveralls.io/github/rematch/rematch?branch=master

**Comment by ShMcK** [comment]
I had the same issue, but finally got it working. In my case I had to trigger a master branch update for my CI (Travis).

Running updates through PRs merging onto master wasn't doing the job.
