### ISSUE TITLE
Bitbucket repo not working

### ISSUE THREAD

**Issue by Ivor** [lemurheavy/coveralls-public#915]
Hi!

I am trying to add a bitbucket repo to a coveralls account. 
When I try to add/remove repos I keep getting the 500 error page with the stomping foot. 

I seem to get Four Oh Four when I try to view details for the repo. 

Looking forward to your feedback :)

**Comment by tsieprawski** [comment]
Seconding. If I am logged in and go to https://coveralls.io/bitbucket/tsieprawski/ubjsc, I get `Five Zero Zero`.
But when I am unlogged, and/or browser's private mode, the page renders properly.

**Comment by zaidisalman** [comment]
I'm having the same problem, also I can't change unlink my repos and it doesn't show me my repo keys.

**Comment by tsieprawski** [comment]
Looks like today you can access bitbucket repos on coveralls. IMHO the issue is to be rejected.

**Comment by Ivor** [comment]
Resolves perhaps. Rejected would suggest that the report was a mistake.

**Comment by Ivor** [comment]
I can confirm you can add a Bitbucket repo now. I cannot see the source files though. Will file a separate bug for that.
