### ISSUE TITLE
Impossible to upload coverage info to a private repo with goveralls

### ISSUE THREAD

**Issue by rossille** [lemurheavy/coveralls-public#916]
I'm trying to upload coverage information to coveralls using goveralls (latest version as of today).

This is the command I use:

    goveralls -coverprofile=coverage.txt -repotoken=$COVERALLS_TOKEN

The `COVERALLS_TOKEN` variable contains the token of the repository, visible on the repo's page

It fails with this error:

    Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by wlaoh** [comment]
I am also having the same issue, have you heard anything back from Coveralls?

**Comment by rossille** [comment]
I didn't head anything back. I switched to codecov, which works like a charm

**Comment by wlaoh** [comment]
I see, thanks for getting back.  We managed to fix it by completely deleting the project from Coveralls and then reloading it with a new token.

**Comment by joscha** [comment]
references #997
