### ISSUE TITLE
"Last build on branch master" is not most recent from "Recent builds"

### ISSUE THREAD

**Issue by dpifke** [lemurheavy/coveralls-public#926]
The "last build on branch master" shown here is from November, despite there being completed runs from a month ago and from yesterday on branch master listed under "recent builds":

https://coveralls.io/github/dpifke/golang-fastmatch

**Comment by nickmerwin** [comment]
Hi @dpifke I removed the old build from before you switched to drone; the most recent is being reflected properly now.

Thanks!
