### ISSUE TITLE
Coveralls not commenting in PRs

### ISSUE THREAD

**Issue by RedCraig** [lemurheavy/coveralls-public#928]
Coveralls is not commenting on our private repo's PRs.
* we're using Coveralls Trial level coverage at $5 a month for one private github repo.
* Our github organisation has granted coveralls third-party access to 'coveralls', and 'coveralls-pro'
* we're using CircleCI and [coveralls-python](https://github.com/coveralls-clients/coveralls-python)
* circle.yml file has our `COVERALLS_REPO_TOKEN`, which works as coveralls is receiving/displaying our coverage reports from CircleCI
* in coveralls settings, our repo has 'pull request alerts -> leave comments' enabled

Is there anything else I need to configure for coveralls to comment on PRs?

Thanks for any help.

**Comment by judikdavid** [comment]
I have the same issue with Coveralls, commenting works with public repos, but it's not working with private ones. What are we missing?

**Comment by MindfulBell** [comment]
Is this still a thing? I am having the issue on coveralls for a private repo.

**Comment by bytewalls** [comment]
What repo are you having issues with @MindfulBell?
