### ISSUE TITLE
Prevent coveralls commenting on pull requests

### ISSUE THREAD

**Issue by robyoung** [lemurheavy/coveralls-public#93]
How can I prevent coveralls from commenting on pull requests? In fact, how can I prevent coveralls commenting on _anything_?

**Comment by marklarr** [comment]
I just want to say, I had to come here to find that setting. It might make more sense to put it in the `Notifications` area 

![notifications venmo slather coveralls - test coverage history statistics 2015-03-11 14-32-48](https://cloud.githubusercontent.com/assets/760261/6607375/7af9cbf2-c7fb-11e4-9c53-ee54ca4c0f02.png)
