### ISSUE TITLE
Coverage %age semantics changed?

### ISSUE THREAD

**Issue by jbarnettwomply** [lemurheavy/coveralls-public#934]
It appears that coverage percentage now applies to branch coverage instead of line coverage.  Is there a way to have it calculated based on line coverage again?  Coveralls is now reporting decreases in coverage due to this change on rebuilds of the exact same codebase...

**Comment by nickmerwin** [comment]
Hi @jbarnettwomply yes, we're rolling out branch coverage and now counting them into the aggregate coverage numbers. Since a line with multiple branches is basically multiple lines condensed, we feel that it should be counted this way. 

We realize many repos may drop in overall coverage % now that there are more relevant things to count, but this change is part of our goal of giving you insight into where bugs may be hiding and where more tests should be added.

**Comment by bcguan2008** [comment]
@nickmerwin i agree add branch coverage, but how we do trouble-shooting  when found something Inaccurate data

for example: https://coveralls.io/builds/10524941/source?filename=lib%2FButton%2Fbutton.js#L7
my code only 65% cov, but i donot know how to improvement unit test (looks like almost 90%)

**Comment by jbarnettwomply** [comment]
hi @nickmerwin , I totally understand that branch coverage is more accurate than line coverage, and once a codebase has "good" line coverage, ensuring that it also has "good" branch coverage is the next logical step.  To the extent, however, that our existing processes rely on decisions that were made when the %age was reported as line, they need to be updated, and there appears to have been no announcement of this change anywhere to allow those updates to be proactive rather than reactive.  To the extent that you're going to change things for other language types (ie, we've seen the change in our js repos but not yet in our java repos), some amount of notice / option to remain in line coverage mode for a sunset period would be appreciated.

Thanks!

**Comment by nickmerwin** [comment]
Hi @jbarnettwomply, we've made branch coverage inclusion into the aggregate % opt-in now as a toggle on your repo settings page. I agree the opt-out rollout was too disruptive to people's existing workflows so we've made this change based on community feedback.

Thank you!
