### ISSUE TITLE
Is this a bug about  "SOURCE NOT AVAILABLE"?

### ISSUE THREAD

**Issue by bcguan2008** [lemurheavy/coveralls-public#937]
this issue starting from this morning (CN,Time), i want to sure is coveralls's bug ? or we commit something wrong ....  

[link this](https://coveralls.io/builds/10522693/source?filename=lib%2FButton%2Fbutton.js)

![snip20170310_3](https://cloud.githubusercontent.com/assets/6290186/23779002/8b461a08-0578-11e7-93c5-ee6ab3322c92.png)
)
PS: not only this file, all my file in repos(fancyui) have this issue

**Comment by bcguan2008** [comment]
and now i cant see the public repos in organization (ffan-fe) ... 

there is still a problem after i did follow:

1. i set my membership in organization is public
2. RE-AUTHORIZE in https://coveralls.io/repos/new

**Comment by Ivor** [comment]
I have the same problem, with a bitbucket repo.

**Comment by lthurner** [comment]
I have the same problem: https://coveralls.io/github/lthurner/pandapower

Resyncing or even deleting the account and registering again has not changed anything, Is there another solution for this?

**Comment by andreagrandi** [comment]
We have exactly the same problem with https://coveralls.io/github/alphagov/land-availability-ui and another repository using the same integration. If anyone knows a solution please post an update here, thanks.
