### ISSUE TITLE
GitHub status API integration broken

### ISSUE THREAD

**Issue by Bilge** [lemurheavy/coveralls-public#938]
Coveralls did not show up to validate any of the commits of [a recent PR](https://github.com/ScriptFUSION/Mapper/pull/6).

**Comment by hkdobrev** [comment]
We're just integrating Coveralls with a private repo and it seems we're also affected by this. I would expect the commit status to be added as pending as soon as the PR is opened, but it's not there.

@nickmerwin Why adding the `legacy` label? Could you share an update on this?
