### ISSUE TITLE
Coveralls suddenly started to ignore the "istanbul ignore next" directive

### ISSUE THREAD

**Issue by ascartabelli** [lemurheavy/coveralls-public#939]
My Travis build on the 3th of March [was still at 100% coverage](https://coveralls.io/builds/10415231/source?filename=dist%2Flamb.js#L6516), but today [coverage dropped](https://coveralls.io/builds/10559014/source?filename=dist%2Flamb.js#L6514) as if the "istanbul ignore next" directive was missing.

Is something changed about coveralls that I don't know of?

**Comment by bcguan2008** [comment]
As coveralls said 'we're rolling out branch coverage and now counting them into the aggregate coverage numbers'

**Comment by ascartabelli** [comment]
Ok, thanks, never paid attention and thought you already considered branch coverage.

But my problem still stands, though: it's pretty common to use that directive to bypass, in my case, UMD boilerplate code or similar situations.

How should we deal with such cases?

**Comment by ascartabelli** [comment]
I took some time to look at the lcov format and seems that, if I understand correctly, the problem has no solution examining that file only.
For example in my case above:
```
BRDA:6515,148,0,1
BRDA:6515,148,1,0
BRDA:6517,149,0,0
BRDA:6517,149,1,0
BRDA:6517,150,0,0
BRDA:6517,150,1,0
BRF:304
BRH:304
```
The "BRDA" records refers to branches and can be read as "line / block / branch / taken": so the lcov file records that I haven't taken some branches.
The "BRF" and "BRH" stand for branches found and hits: by reading this I have 100% coverage.

Problem is when you also miss a branch by negligence, because I see no info there to distinguish which branch was skipped on purpose.

Seems there are [workarounds](http://stackoverflow.com/questions/16940548/grunt-test-for-umd) for my specific case and I'll try to investigate in that direction.

P.S.
I realize that the issue title is very misleading, I'm sorry, was very absent-minded while writing that yesterday.

**Comment by ascartabelli** [comment]
Ok, the workarounds I mentioned aren't worth pursuing, but it seems the for the time being the answer is in [this](https://github.com/nickmerwin/node-coveralls/issues/158#issuecomment-286318287) @nickmerwin comment.

It's a pity, but still...

**Comment by danday74** [comment]
Downgrade to npm coveralls@2.11.16 to fix this

**Comment by danday74** [comment]
I'm still stuck on 2.11.16 because of this ... is there a way of setting this in coveralls.yml to allow istanbul ignore statements without having to make the change on the web UI as discussed in the link referred to above by @ascartabelli ?

**Comment by danday74** [comment]
Just tested this on travis.yml not only does upgrading from 2.11.16 to 3.0.0 cause probs with coverage info, it also causes the build to break on node 4.0.0 - will raise a separate issue for this
