### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by joernhees** [lemurheavy/coveralls-public#94]
It would be cool if the file overview would offer a CSV export so you could easily sift through the files and find important ones on your local machine instead of putting load on the coveralls infrastructure (on which the pagination through hundreds of files is quite slow, try https://coveralls.io/builds/84764 ).

I'm talking about an overview export, not the individual files.

**Comment by callkathy** [comment]
+1 for any kind of an export....

**Comment by jamesrom** [comment]
I don't know if this is documented. But if you put .json on the end of most URLs (at least before they query string) it seems to give you stuff you'd expect. Not sure if this is helpful in your case, but useful for others looking to export data.
