### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by strarsis** [lemurheavy/coveralls-public#941]
Suddenly some builds of a [svgo PR](https://github.com/svg/svgo/pull/592) in Travis fail with coveralls service responding with HTTP 500:
https://travis-ci.org/svg/svgo/jobs/213448873#L1166

**Comment by dominique-mueller** [comment]
Same here, my Travis CI build failes due to coveralls returning an 500 status code (see https://travis-ci.org/dominique-mueller/angular-notifier/builds/213470146#L705).

**Comment by dominique-mueller** [comment]
Seems that Coveralls is working again ...

**Comment by cdornan** [comment]
I am seeing a lot of 500s from the web app, though they seem to be clearing up now. Last night jobs started showing "No data available in table" on the breakdowns, which they are still doing. Is this related? Should I re-submit them?

**Comment by cdornan** [comment]
I think I know what has been happening with the "No data available in table" -- because I have been trying to debug the coverage reports I have been cancelling all of the other travis jobs that do not contribute to the coveralls report (i.e., all but one), so Travis reports the job as cancelled and coveralls doesn't associates any coverage data with the job -- but it does with the only sub-job that generates any coverage data. All very confusing when combined with the other things that were failing (of which coveralls was only responsible for the brief spate of 500s).

**Comment by jacobbaskin** [comment]
We are seeing HTTP 500s from the Web UI intermittently.

**Comment by benjamincharity** [comment]
I am no longer seeing the 500s on the site itself, but all coverage pushes from CI builds are now throwing 500s. We've had to disable the coveralls push so that our builds continue passing.

**Comment by kristofclaes** [comment]
We're getting a lot of 500's when Circle CI tries to upload our coverage.

**Comment by ryan-williams** [comment]
https://coveralls.io/repos/ is giving me 500s consistently for the last couple hours.

Seems like it may have been triggered by / related to [this TravisCI job](https://travis-ci.org/hammerlab/adam/builds/218139980) attempting to report coverage stats, and getting an error back (all 6 builds in the job have this error):

```
[info] Statement coverage.: 84.19%
[info] Branch coverage....: 79.41%
[info] Coverage reports completed
[info] All done. Coverage was [84.19%]
[success] Total time: 6 s, completed Apr 3, 2017 4:42:28 PM
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Repository = ./.git
[error] Uploading to https://coveralls.io failed: Couldn't find a repository matching this job.
[error] The error message 'Couldn't find a repository matching this job' can mean your repo token is incorrect.
```

[example full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/218139985/log.txt)

**Comment by strarsis** [comment]
Just HTTP 500 again in travis log ([svgo prefixIds plugin](https://github.com/svg/svgo/pull/700)):
```html
[...]
<title>Coveralls :: Oops, something went wrong (500)</title>
[...]
````
