### ISSUE TITLE
Coveralls not showing per-file test coverage in build summary

### ISSUE THREAD

**Issue by vsreekanti** [lemurheavy/coveralls-public#944]
I have an [open-source project](https://github.com/ground-context/ground) that publishes test coverage to Coveralls as a part of a CI build. As of [this build](https://coveralls.io/builds/10691373) from earlier this week, under "Source Files on Master", it consistently says "No data available in table" but the coverage percentage is still changing. If click on a build and specify the path to a file, I still see coverage information for that file. e.g., if you go to [this file](https://coveralls.io/builds/10743597/source?filename=ground-core%2Fsrc%2Fmain%2Fjava%2Fedu%2Fberkeley%2Fground%2Fdb%2FPostgresResults.java), which is from the most recent build, you still see coverage information.

I haven't changed my CI build configuration across the change in Coveralls, and I haven't been able t find a change in the API that might be causing this. I'd appreciate any pointers towards how to fix this.

Thanks in advance!

**Comment by mcqueary** [comment]
Same here with our [project](https://github.com/nats-io/gnatsd). Here's [a build from last night](https://coveralls.io/builds/10731591) showing the same problem as OP.  Yet, just like OP, [individual file info is there](https://coveralls.io/builds/10731591/source?filename=server/route.go), just not present in the summary table.

**Comment by cdornan** [comment]
I have been seeing this problem for the last few days -- the coverage for the sub-jobs are being reported but this is not being merged into the summary.

**Comment by nickmerwin** [comment]
Hi all, the merge summary issue is fixed now. Sorry for the confusion!

**Comment by vsreekanti** [comment]
Thank you!
