### ISSUE TITLE
No data available in Source Files

### ISSUE THREAD

**Issue by pintux** [lemurheavy/coveralls-public#945]
Hi,
source code for my github project is not listed under the project Source Files section.
Project is: https://coveralls.io/github/vivocha/api-piki
Any idea?
Many thanks.
Antonio

**Comment by lthurner** [comment]
I have the same problem: https://coveralls.io/github/lthurner/pandapower

**Comment by mseminatore** [comment]
I am seeing the same issue

**Comment by nickmerwin** [comment]
Hi all, this issue is fixed now -- sorry for the confusion!

**Comment by mseminatore** [comment]
Confirmed that I see source file information now.  Thanks!  However, and not sure if it is related but now the badge next to the source file reports a cov% that is different than the regular badge.  See https://coveralls.io/builds/10773579/source?filename=TeslaJS.js for an example - 91.75% vs. 93.827%.

**Comment by pintux** [comment]
@nickmerwin: It works now, many thanks!

**Comment by nickmerwin** [comment]
Hi @mseminatore that file coverage % includes branch coverage; each branch is treated like a line, so:

`(304 + 74) / (324 + 88) = 0.9174`

**Comment by mseminatore** [comment]
Thanks for the clarification!
