### ISSUE TITLE
error syncing repos and managing subscription for `tigertext`

### ISSUE THREAD

**Issue by tonymet** [lemurheavy/coveralls-public#946]
We're having trouble syncing our private repos from the `tigertext` organization. Moreover, the subscription page is missing info (see errors below)

username = `tonymet`
organization = `tigertext`

## Steps to Repeat

1. Click 'private repos'
1. Click 'sync private repos' 
1. Click 're-authorize oauth'
1. click 'subscriptions'

## Actual Results
* sync private repos shows only public repos (see screenshot)
* reauthorize o-auth doesn't open o-auth prompt
* subscriptions page is not showing subscription info (see screenshot)

## Screenshots

![coveralls_-_test_c2overage_history___statistics](https://cloud.githubusercontent.com/assets/397995/24385300/41e31ff6-131e-11e7-8c61-449c58681a43.jpg)
![coveralls_-_test_coverage_history___statistics](https://cloud.githubusercontent.com/assets/397995/24385301/41e5689c-131e-11e7-9f67-73824095c8fd.jpg)

**Comment by tonymet** [comment]
@tt-molson fyi

**Comment by tonymet** [comment]
@tt-molson

**Comment by dschinkel** [comment]
Was this ever resolved?  My private repos aren't _all_ syncing either.

**Comment by tonymet** [comment]
i haven't heard from anyone

**Comment by ZsoltFabok** [comment]
I also have a sync issue with @zsoltfabok / it's been syncing for two hours now...

**Comment by tonymet** [comment]
@lemurheavy could you help us find another support channel? we're working to add further projects

**Comment by tonymet** [comment]
closing old stuff.
