### ISSUE TITLE
New public repos not showing up

### ISSUE THREAD

**Issue by robby-dermody** [lemurheavy/coveralls-public#948]
Hi, we've transferred the following repos to our organization (CounterpartyXCP):

* https://github.com/CounterpartyXCP/micropayment-core
* https://github.com/CounterpartyXCP/picopayments-hub
* https://github.com/CounterpartyXCP/picopayments-cli-python

Similar to https://github.com/lemurheavy/coveralls-public/issues/196, I can't see these repos listed on the New Repos page when logged in. I have Admin access to all of them, and my profile in the CounterpartyXCP org is public. I've tried refreshing numerous times, no dice.

**Comment by pixelass** [comment]
#965 
#972
