### ISSUE TITLE
https://coveralls.io/repos returns 500

### ISSUE THREAD

**Issue by ryan-williams** [lemurheavy/coveralls-public#952]
As mentioned in https://github.com/lemurheavy/coveralls-public/issues/941#issuecomment-291280223, something on my coveralls homepage is causing the server to error, for the last 24hrs:

![](https://cl.ly/0X131Y162G3H/Screen%20Shot%202017-04-04%20at%2011.56.43%20AM.png)

Other pages, like https://coveralls.io/repos/new or repo-specific pages like https://coveralls.io/github/hammerlab/test-utils, work fine.

Separately, after this issue began I triggered a repo-rename black hole described at https://github.com/lemurheavy/coveralls-public/issues/899#issuecomment-291548186, but I don't think it is related, since it only started after this, but this issue is also making it harder for me to debug that.

**Comment by omkiran** [comment]
Facing the same issue

**Comment by ryan-williams** [comment]
This is still happening to me; homepage and /repos 500, /repos/new and per-repo pages seem to work fine.

**Comment by alfa-jpn** [comment]
I have happen the same issue since 8 days ago.
