### ISSUE TITLE
Coveralls doesn't detect branch 

### ISSUE THREAD

**Issue by xd009642** [lemurheavy/coveralls-public#953]
I'm using coveralls via travis on a rust project. My branch isn't detected and just shows up as a question mark. How do I remedy this? Also, I feel that if coveralls can't detect the branch you should allow the user to set it manually in the event they know exactly which branch it is.

![screenshot from 2017-04-06 19-41-01](https://cloud.githubusercontent.com/assets/3472518/24770215/105bd6fe-1b01-11e7-8b5a-f098c1be5498.png)

**Comment by xd009642** [comment]
I found personally if when you submit the report you use your Travis_job_id as the coveralls token and specify the ci type as Travis-ci it works better. Depends on what tool you're using to submit the reports.

Sadly, I've never had an issue I've raised with coveralls get a response. Might be worth trying codecov instead

**Comment by bytewalls** [comment]
@Pinto18  which repo are you having these issues with, we can take a look and see how we can improve this.

@xd009642 Sorry you never got a response from us previously. If this is still and issue for you please let me know, as well as the repo you are having issues with, we will look into those as well.
