### ISSUE TITLE
Project stopped updating

### ISSUE THREAD

**Issue by vinniefalco** [lemurheavy/coveralls-public#959]
My project stopped updating on coveralls in November 2016 and I have no idea why:
https://coveralls.io/github/vinniefalco/Beast

Its been building faithfully on Travis for months:
https://travis-ci.org/vinniefalco/Beast/builds

It looks like it is uploading the coverage reports:
https://travis-ci.org/vinniefalco/Beast/jobs/222269403#L1288-L1311

But no updates? I'm a bit baffled.

**Comment by vinniefalco** [comment]
Bueller?

**Comment by suddenrushofsushi** [comment]
This is clearly still a problem

**Comment by bytewalls** [comment]
@suddenrushofsushi,

It appears as though the initial issue was solved in late April of 2017 Are you seeing other behavior similar to this in your own repository?

**Comment by suddenrushofsushi** [comment]
Yes, I opened a new issue earlier with a number of items that are echoed by others. They are currently occurring.

**Comment by bytewalls** [comment]
@suddenrushofsushi,

We are working on that issue right now, I'll be replying to it shortly. It does not seem to be related to this? Sorry for the inconvenience I certainly understand frustration with the service not working the way it should for you.
