### ISSUE TITLE
Coverage badge is wrong?

### ISSUE THREAD

**Issue by epoberezkin** [lemurheavy/coveralls-public#960]
The badge shows 85%, the build - 99.7%

https://coveralls.io/github/epoberezkin/ajv

**Comment by eisbehr-** [comment]
GitHub will cache all images in your files, like readme. So it will take up to 24 hours to be updated on your repository page. Actually your badge is correct.

**Comment by islemaster** [comment]
I think this problem might be more complicated than a 24-cache.  For example, on the [Code.org repo](https://github.com/code-dot-org/code-dot-org) this morning:

![image](https://cloud.githubusercontent.com/assets/1615761/26117957/1253ecb8-3a1d-11e7-8c42-aefdd7c19c21.png)

* Coveralls' UI reports 88% coverage
* The badge within Coveralls' UI (or opening `https://coveralls.io/repos/github/code-dot-org/code-dot-org/badge.svg?branch=staging` directly) shows 64% coverage.
* The badge in the README on GitHub shows 18% coverage (definitely not accurate 24 hours ago).

**Comment by jleni** [comment]
@eisbehr- This is not the case in most other badges (travis-ci, etc, etc..). Any chance this issue could have higher priority?
