### ISSUE TITLE
Parallel Build not working with Codeship

### ISSUE THREAD

**Issue by kessiler** [lemurheavy/coveralls-public#962]
I followed the instructions at https://coveralls.zendesk.com/hc/en-us/articles/203484329-Parallel-Build-Webhook to notify Coveralls after the build is complete.

However, coveralls isn't merging the test coverage reports and also leaving the builds with status `pending`.

I've sent 3 emails to the support team a couple days ago but no one has replied yet.

**Comment by artemave** [comment]
I am experiencing similar issue. @kessiler did you manage to sort it out?

**Comment by kessiler** [comment]
I did not. I started using codecov instead.
