### ISSUE TITLE
Badge Percentage not updating

### ISSUE THREAD

**Issue by sp71** [lemurheavy/coveralls-public#963]
My [Github](https://github.com/sp71/SnapLayout) has a badge displaying **69%**; however, the coveralls [website](https://coveralls.io/github/sp71/SnapLayout?branch=master) value is **89%**. Not sure why it is using an older value.

**Comment by eisbehr-** [comment]
GitHub will cache all images in your files, like readme. So it will take up to 24 hours to be updated on your repository page. Actually your badge is correct.
