### ISSUE TITLE
weird/random build reports

### ISSUE THREAD

**Issue by lemoustachiste** [lemurheavy/coveralls-public#964]
Hi,

I have just setup a test reporting for my project, but it seems build reports come from other projects?

if you look at the following image

<img width="1126" alt="screen shot 2017-05-02 at 14 00 48" src="https://cloud.githubusercontent.com/assets/12797962/25616964/fe3e66c8-2f3f-11e7-988c-54e82abfe607.png">

- build #20 was triggered by another project, but concurrently to me testing in Travis
- I regenerated a repo token and ran build #21 from my local, so was happy to see it works
- testing in Travis again (updating the new repo token there), 3rd build seems to be also coming from a external project.

Both committers of build 1 and 3 aren't part of my organization, nor somewhat related as external resources. 

Is this something I'm doing wrong?

**Comment by swiftfoot** [comment]
I have this same issue with my Coveralls Enterprise and Travis Enterprise.  For me it's only on the master branch.  My recent build list in coveralls are wildly incorrect not limited to my repository at all (but pulling from every repository I think), did you ever figure this out?

**Comment by swiftfoot** [comment]
When the very last build is from a branch/repo that isn't yours, it screws up your coverage detail reports too as it can't locate the files within their repo.
