### ISSUE TITLE
I can't see my %

### ISSUE THREAD

**Issue by tundewritescode** [lemurheavy/coveralls-public#966]

**Comment by tundewritescode** [comment]
Coveralls is seeing all my Travis Builds, but still, I can't see any percentage on Coveralls.io
![pasted image at 2017_05_09 02_00 pm](https://cloud.githubusercontent.com/assets/26854731/25852979/159516cc-34c3-11e7-9d0e-8ef910077baa.png)

**Comment by tylerlong** [comment]
I have the same issue.

**Comment by mohierf** [comment]
The same for me

**Comment by hristo-vrigazov** [comment]
Me too

**Comment by nickmerwin** [comment]
Hi all, we had a processing queue clog earlier today and have bumped up our capacity to work through the backlog as quickly as possible -- we should be back to normal within a few hours.

You can follow along here too: https://status.coveralls.io

Thank you!
