### ISSUE TITLE
Coverage changes not being displayed

### ISSUE THREAD

**Issue by essentiallymikey** [lemurheavy/coveralls-public#968]
Hello,

None of our Travis builds today are showing up. The latest build being displayed is from yesterday at about 8:00pm PST.

I can see that Coveralls knows about the builds that have happened today, but it shows no coverage change or no data. Nothing has changed on our side in terms of publishing and we can build coverage locally just fine.

Have we lost the coverage metrics for today's builds?

Thanks

**Comment by nickmerwin** [comment]
Hi @essentiallymikey, we had a processing queue clog earlier today and have bumped up our capacity to work through the backlog as quickly as possible -- we should be back to normal within a few hours.

You can follow along here too: https://status.coveralls.io

Thank you!
