### ISSUE TITLE
Coverage pending from Coveralls.io 

### ISSUE THREAD

**Issue by mohierf** [lemurheavy/coveralls-public#969]
My Pull requests stay in this status `Coverage pending from coveralls.io` on this public repo: https://github.com/Alignak-monitoring-contrib/alignak-module-backend/pull/79

On some other repos, the code coverage results are correctly pushed to coveralls.io but no more coverage results are displayed where as the jobs are visible. Jobs indicate that no changes happened. This behavior is observed since 2 days ...

**Comment by hristo-vrigazov** [comment]
+1. Given that a lot of issues were created with this problem, I think it happens for everyone.

**Comment by nickmerwin** [comment]
Hi all, we had a processing queue clog earlier today and have bumped up our capacity to work through the backlog as quickly as possible -- we should be back to normal within a few hours.

You can follow along here too: https://status.coveralls.io

Thank you!
