### ISSUE TITLE
Badge not updating

### ISSUE THREAD

**Issue by TheFlow0360** [lemurheavy/coveralls-public#971]
I know, by now you must be sick of these issues, but why is it that every other badge works? Only the coveralls badge is stuck...
Here is the curl call for the cached image:

    $ curl -I https://camo.githubusercontent.com/ab5ccd872d8ad47d641e27dd45dddb343311a739/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f546865466c6f77303336302f63726974657269615f6f70657261746f722f62616467652e7376673f6272616e63683d6d6173746572
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
    0   724    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0HTTP/1.1 200 OK
    Cache-Control: no-cache
    Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
    Content-Type: image/svg+xml
    Last-Modified: Tue, 20 Jan 2015 21:36:09 GMT
    Server: github-camo (485b32e9)
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Content-Type-Options: nosniff
    X-Frame-Options: deny
    X-Xss-Protection: 1; mode=block
    X-GitHub-Request-Id: 2398:4C3B:31FD392:33F17D9:5913EFD8
    Content-Length: 724
    Accept-Ranges: bytes
    Date: Thu, 11 May 2017 07:05:30 GMT
    Via: 1.1 varnish
    Age: 84
    Connection: keep-alive
    X-Served-By: cache-hhn1531-HHN
    X-Cache: HIT
    X-Cache-Hits: 1
    X-Timer: S1494486330.160847,VS0,VE0
    X-Fastly-Request-ID: f80e264b2d51db3682eed1ff0994d90279b4b52a
    Timing-Allow-Origin: https://github.com

The original badge URL is this: [https://coveralls.io/repos/github/TheFlow0360/criteria_operator/badge.svg?branch=master](https://coveralls.io/repos/github/TheFlow0360/criteria_operator/badge.svg?branch=master)

**Comment by TheFlow0360** [comment]
See [this Issue](https://github.com/github/markup/issues/224#issuecomment-37663375) for mor information.

**Comment by TheFlow0360** [comment]
I just updated my README with new information and the badge is still the old cached one. This really sucks...

**Comment by smbrd** [comment]
I don't see badge at all - redirects me to coveralls_unknown.svg

**Comment by smbrd** [comment]
...and now it works

**Comment by TheFlow0360** [comment]
Hm.... for me it was still stuck at 24%. Deleting the local cache helped. Anyways, it should work automatically.

**Comment by peterhurford** [comment]
My [badge](https://img.shields.io/coveralls/syberia/tundra.svg) and [build](https://coveralls.io/builds/11590184) are both stuck at 24%, despite the build being at 90.91%. I could understand caching affecting the badge, but why is the build also stuck at 24%?

**Comment by blenoski** [comment]
I am experiencing the same issue.  CirceCI badge is working as expected.  Coveralls badge is not updating on README.md.  I have resorted to manually adding bogus parameters to the query string to get it work, but doing that for every change obviously isn't sustainable.

**Comment by alancast** [comment]
I am also seeing this. Badge is stuck and will update once if I add a bogus query param to it, but as was mentioned above doing that every change isn't sustainable. Did anyone find a fix for this?

**Comment by romarioraffington** [comment]
+1

**Comment by dericcain** [comment]
I am having the same issue. My badge is stuck at 58% coverage and it hasn't been that low in a couple weeks. Not sure why it is not updating.

You guys need a developer to help fix these issues? ;)

**Comment by dericcain** [comment]
Mine updated today, so maybe it just takes time.

**Comment by romankh3** [comment]
I have the same issue =\\

**Comment by whyboris** [comment]
Unsure why this is happening: 
 - my badge is stuck at 81% (https://github.com/whyboris/karma-helpful-reporter)
 - it shows 81% on Coveralls (https://coveralls.io/github/whyboris/karma-helpful-reporter?branch=karma-helpful-reporter)
 - but the last build is 98.638% (same link as above - 16 Aug 2017)

I'm not sure why Coveralls is ignoring my last build and showing the number from several weeks ago. Perhaps this is a different issue than what the others in this thread are having.

**Comment by algorys** [comment]
In my case, adding `&service=github` to badge seems solve problem.

Example:

```rst
.. image:: https://coveralls.io/repos/github/YOUR_REPOS/badge.svg?branch=develop&service=github
```

Works also with markdown syntax.

**Comment by HerveNivon** [comment]
@algorys, your solution doesn't work for me. 😭

**Comment by hammady** [comment]
@algorys it works probably because query string parameters are not so cache-friendly to browsers/cache servers.

**Comment by algorys** [comment]
@hammady yes... not sure if that update only one time and not for other pushes...

**Comment by mnboos** [comment]
Mine doesn't update either. It's stuck at 43%, but actually it's 65%.

**Comment by bbqtd** [comment]
It still doesn't work. It updates only on change the file where the badge is declared (`README.md`) or after manually emptying browser cache.

**Comment by Chaffelson** [comment]
+1

**Comment by whyboris** [comment]
Still stuck since before Aug 2017. 
https://github.com/lemurheavy/coveralls-public/issues/971#issuecomment-322946878
Could it have _anything_ to do with the default branch not being named _master_? Absurd that I can't force a re-count through the UI interface. I don't want to craft a new release of my package just to update coverage (nor can I be sure that it would actually update the coverage anyway).

**Comment by ScottChapman** [comment]
Still stuck

**Comment by efagerberg** [comment]
Also still stuck, one time it worked clearing my browser cached image but I am noticing now that there must be some server side caching of the image because it does not load in like my other badges.

**Comment by inisik** [comment]
Lol my badge says 12% but on coveralls it is 100%. Please fix this.

**Comment by inisik** [comment]
I just switched to shields.io. Works. 😄 

- https://shields.io/

**Comment by hechaoli** [comment]
I found that the badge updates when I change badge.svg to badge.png. But the resolution of the image is not good after the change.

**Comment by njncalub** [comment]
Using [shields.io](shields.io) also worked for me. 

Format:
``https://img.shields.io/coveralls/github/<username>/<repository-name>[/<optional-branch-name>].svg``

**Comment by Quantum-35** [comment]
I cleared cookies on my browser and it worked for me

**Comment by arkadyt** [comment]
@Quantum-35, I confirm. Clearing cookies worked.

**Comment by tdmalone** [comment]
Since this issue has the `legacy` label which I guess means it's not gonna be looked at anymore, see also #1120, which appears to be a newer issue for this problem.

**Comment by iamdefinitelyahuman** [comment]
I was able to fix this issue on my repo by purging GitHub's cached copy of the badge:

```
$ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
```

More detailed info is available here - https://help.github.com/en/articles/about-anonymized-image-urls

Hopefully this saves someone else the frustration I just went through :)

**Comment by czyang** [comment]
> I was able to fix this issue on my repo by purging GitHub's cached copy of the badge:
> 
> ```
> $ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> ```
> 
> More detailed info is available here - https://help.github.com/en/articles/about-anonymized-image-urls
> 
> Hopefully this saves someone else the frustration I just went through :)

This works for me. And it looks like this is the real answer.

**Comment by bedantaguru** [comment]
> curl -X PURGE

Not working

**Comment by bedantaguru** [comment]
> I was able to fix this issue on my repo by purging GitHub's cached copy of the badge:
> 
> ```
> $ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> ```
> 
> More detailed info is available here - https://help.github.com/en/articles/about-anonymized-image-urls
> 
> Hopefully this saves someone else the frustration I just went through :)

Not working for me..

**Comment by wincodes** [comment]
> In my case, adding `&service=github` to badge seems solve problem.
> 
> Example:
> 
> ```
> .. image:: https://coveralls.io/repos/github/YOUR_REPOS/badge.svg?branch=develop&service=github
> ```
> 
> Works also with markdown syntax.

worked.. thanks

**Comment by ajoslin103** [comment]
npm has the new coverage in moments, so it must be the github...

**Comment by ssichynskyi** [comment]
### This workaround works for me for every badge:
@algorys, thanks for the idea!
just add **?service=github** or **&service=github** to every badge URL

For example:
`[![Code Grade](https://www.code-inspector.com/project/<number>/score/svg?service=github)](https://www.code-inspector.com)`
or
`[![Coverage Status](https://coveralls.io/repos/github/<user>/<repo>/badge.svg?branch=master&service=github)](https://coveralls.io/github/<user>/<repo>?branch=master) 
`

**Comment by afinetooth** [comment]
Closing this issue for age, but tagged `badge-issues` for reference.

**Comment by Stannislav** [comment]
> npm has the new coverage in moments, so it must be the github...
> 
> here's what worked for me
> 
> #1 open inspect on the repo page
> #2 open the badge image in a new tab and copy that Url
> #3 in a Terminal window: curl -X PURGE
> #4 right click on the reload for the repo page and choose: hard reload and clear cache
> #5 repeat #3 & #4 again (it didn't work the 1st time for me)

Awesome, thanks! Related GitHub docs: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache

**Comment by afinetooth** [comment]
https://github.com/lemurheavy/coveralls-public/issues/1828
