### ISSUE TITLE
Unable to sync repos

### ISSUE THREAD

**Issue by smbrd** [lemurheavy/coveralls-public#972]
On website https://coveralls.io/repos/new, when I click "Refresh private repos", then "Your repos are syncing..." is spinning endlessly.

**Comment by jameswlane** [comment]
I second this I been trying to add a public repo that I just created

**Comment by jbenden** [comment]
I third this. I've been trying to add a public repo.

**Comment by pixelass** [comment]
Same here. I only see a button to sync "private" repos. (not sure if this suddenly changed)
When I click the button no new "public" repos appear.

Is a button missing?

**Comment by pixelass** [comment]
#965

**Comment by taleinat** [comment]
Likewise.

**Comment by joshuaquek** [comment]
same here... the label "Your repos are syncing..." keeps spinning forever
