### ISSUE TITLE
PHP - not covered sprintf distributed in several lines

### ISSUE THREAD

**Issue by juliangut** [lemurheavy/coveralls-public#974]
Please take a look here: https://coveralls.io/builds/11510034/source?filename=src%2FRepositoryTrait.php#L121

It is happening more than once, when a sprintf is splitted into several lines the one in the middle is considered not covered which is clearly impossible

PHPUnit's coverage report correctly identifies these lines as covered but Coveralls does not

**Comment by Great-Antique** [comment]
Xdebug 2.5.5 fix it
https://xdebug.org/updates.php

**Comment by juliangut** [comment]
Fixed indeed, awesome!
