### ISSUE TITLE
Coverage files are linked to the wrong repository

### ISSUE THREAD

**Issue by ColinSullivan1** [lemurheavy/coveralls-public#975]
We really appreciate the service you provide!  

Unfortunately, I'm running into an issue.  I'm setting up coveralls through a go github [repo](https://github.com/nats-io/prometheus-nats-exporter), with coverage updated through Travis CI.  

After running in Travis, I get a URL linked to coverage which can be found [here](https://travis-ci.com/nats-io/prometheus-nats-exporter/jobs/75666721#L376).  The url is https://coveralls.io/jobs/25791351.

The page the coverage URL links to shows my files (collector.go, exporter.go, etc) associated with a entirely different repository.  Screenshot is attached.  When I click on my coverage badge (reporting unknown), I'm taken to the coveralls setup setup screen, [here](https://coveralls.io/github/nats-io/prometheus-nats-exporter).

Any help would be appreciated.

Thanks,
Colin

![coverallsscreenshot](https://cloud.githubusercontent.com/assets/11180189/26114346/43891eaa-3a1a-11e7-9396-543e229e713d.jpg)

**Comment by dipernaa** [comment]
This is happening to one of my projects. Not cool

**Comment by swiftfoot** [comment]
me too I have Coveralls Enterprise and Travis Enterprise, any ideas for why the incorrect build and repository is linked?

**Comment by swiftfoot** [comment]
I was able to get rid of these invalid reports by disabling the Pull Request settings under each repository.  Seems like a bug with the Travis API Pull Request updates.  This at least gets me valid code coverage reports on each Push for each repository.

**Comment by easiestripes** [comment]
Anyone figure out what's causing this issue?

**Comment by ilya-golovenko** [comment]
I have the same issue. Here is the link: https://coveralls.io/builds/12684012/source?filename=kevro%2Ftaxonomy%2Ftools.py

I never had a file with such name in any of my github repos.

**Comment by petar-andrejic** [comment]
Seems to be happening on the [Julia repo](https://coveralls.io/github/JuliaLang/julia) as well, here's a screenshot of what it looks like on my end, the files listed are most definitely not those of the Julia programming language. The recent builds list seems to be correct though...
![screen shot 2018-10-23 at 7 16 28 pm](https://user-images.githubusercontent.com/17103815/47339595-2e310c80-d6f8-11e8-97b6-04f217487057.png)

**Comment by sagerman4** [comment]
This is happening for my organization as well. Source seems not to be included in the report thankfully, but having another organization have access to our structures is not ideal.

**Comment by leerho** [comment]
This is happening for my organization too.  Results are never returned to the GitHub repo site apparently because it is associated with the wrong repo.  How do we fix this?

**Comment by afinetooth** [comment]
@sagerman4 @leerho 

A few points:

- First, you're right, we don't store any source files! 

- You won't be able to see another repo's source files, and they won't be able to see yours, unless both repos are public.

- There are a couple of reasons you might be seeing refs to source from another repo, the main one being that your CI is identifying a non-unique job. Please have a look at the troubleshooting step, "I see random commits on my Travis-pro private repo," here:
https://docs.coveralls.io/troubleshooting

Hope it helps!
