### ISSUE TITLE
can't log in or set token

### ISSUE THREAD

**Issue by pixelass** [lemurheavy/coveralls-public#978]
Has something changed?
Coverall is attempting to set a new token (Coveralls Pro) though I already ahve one accesToken set.
The new token needs write access to all publich and private repos (why)?

The new token fails:

> Coveralls Pro by @lemurheavy would like permission to access your account
> @pixelass
> Reauthorization required
> This application has made an unusually high number of requests to access your account. Please
> reauthorize the application to continue.

**Comment by pixelass** [comment]
Chrome Version 58.0.3029.110 (64-bit) 
OS X 10.12.4 (16E195)


Worked in Opera

**Comment by porglezomp** [comment]
I'm also experiencing this same issue right now. I was able to sign in using a different browser, and also using a private browsing window so I suspect it's caused by some caching/cookies problem.

**Comment by porglezomp** [comment]
Going into inspect-element and clearing all my cookies for coveralls.io allowed me to log in successfully.

**Comment by mmikowski** [comment]
I am seeing the same issue. It never works even using an incognito browser and after wiping all coveralls.io local data (cookies, etc) for coveralls.io and affiliated sites like stripe.com.  It keeps returning to request invasive Coverall Pro access to everything and then failing. Help?
