### ISSUE TITLE
Coverage pending from Coveralls.io  #167 

### ISSUE THREAD

**Issue by ssubr06** [lemurheavy/coveralls-public#979]
Can you help me here to solve this issue for   #167 ? it says Coverage pending from Coveralls.io as I modified the code for biemond-oradb..

**Comment by nickmerwin** [comment]
@ssubr06 it looks like this build didn't come in with a PR number:

https://coveralls.io/builds/6387145

Could you check your coveralls / CI config to see if anything recently changed?

**Comment by aurelien-rainone** [comment]
Hi, it seems I have a similar issue so not opening a new one. If you'd prefer another issue just tell me.

aurelien-rainone/evolve#8

A bit of context:

This project has always been using a travis-ci build matrix with 2 go versions, 1.10 and tip, reporting coverage for both. That seems unecessary so I disabled coverage reporting for go tip.
