### ISSUE TITLE
Intermittent couldn't find repositories for this job error

### ISSUE THREAD

**Issue by scottdickerson** [lemurheavy/coveralls-public#981]
Intermittent couldn't find a repository matching this job errors when trying to post to coveralls

I am using Travis Enterprise and have correctly set the COVERALLS_REPO_TOKEN, the .coveralls.yml service_name: travis-enterprise

and the COVERALLS_ENDPOINT correctly.

Other repositories work fine, and I believe sometimes this repository works correctly.

/coveralls.js:18

        throw err;

        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by swiftfoot** [comment]
Is there a log on the coveralls enterprise side that I could tail onto for more information?

**Comment by joscha** [comment]
references #997
