### ISSUE TITLE
Report minimal code coverage in CI check on Github

### ISSUE THREAD

**Issue by TomasVotruba** [lemurheavy/coveralls-public#982]
When I set minimal required coverage, it is not reported on pull-request. Only it's change.

## Current Status

So sb sends pull-request that lovers coverage to 70 % and my limit is 80 %, coveralls will fail with no clear message about it.

![image](https://user-images.githubusercontent.com/924196/27071456-5b2bc5ee-501d-11e7-8d9d-8c88c3b13a70.png)

## Desired Response

I'd appreciate informative message like "Minimal required covereage is 80 %. This PR has only 70 %."

**Comment by dvorovenko** [comment]
+1

**Comment by TomasVotruba** [comment]
Outdated
