### ISSUE TITLE
"Couldn't find a repository matching this job" - for a PR in public repo

### ISSUE THREAD

**Issue by gpbl** [lemurheavy/coveralls-public#984]
I've this failing build on a public repo https://circleci.com/gh/gpbl/react-day-picker/322 for [a PR](https://github.com/gpbl/react-day-picker/pull/401):

```bash
$ coveralls < ./coverage/lcov.info 

/react-day-picker/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

Builds on master [it does work](https://circleci.com/gh/gpbl/react-day-picker/323). I've tried to re-sync the repo, refresh the token etc. but without success. What could I do? 🙏 

Thanks!

**Comment by stevenvachon** [comment]
I'm getting this too on [AppVeyor](https://appveyor.com).

**Comment by joscha** [comment]
references #997

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861

**Comment by danascheider** [comment]
I'm having this problem on Travis Pro. Here's my .travis.yml:
```
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  - COVERALLS_REPO_TOKEN=<redacted>
script:
  - yarn test
  - mv coverage/lcov.info coverage/lcov.txt  # this solved another problem
  - cat coverage/lcov.txt | node_modules/coveralls/bin/coveralls.js
```
My .coveralls.yml is:
```
service: travis-pro
repo_token: <redacted>
```
And the Travis build output is:
```
The command "mv coverage/lcov.info coverage/lcov.txt" exited with 0.
1.21s$ cat coverage/lcov.txt | node_modules/coveralls/bin/coveralls.js
/home/travis/build/danascheider/inview-login-service/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
The command "cat coverage/lcov.txt | node_modules/coveralls/bin/coveralls.js" exited with 1.
```
I've tried refreshing my GitHub OAuth token as well as the Coveralls repo token and deleting and re-adding the repo to Coveralls. I've also tried a number of variations on the build script. Nothing helps.

**Comment by p8ul** [comment]
Had the same issue too. But fixed it by adding a `.coveralls.yml` file and added the token from coveralls `repo_token: <your-repo-token-from-coveralls-details>`

**Comment by srepollock** [comment]
@p8ul I hope you didn't publish your `.coveralls.yml` file, it's not good to push your token to open source for privacy concerns.

**Comment by nickmerwin** [comment]
Hi all, we had an issue re: Travis API accidentally blocking our webserver IPs. This is fixed now, thanks.
