### ISSUE TITLE
Links in pull-request comments don't have a domain: https://:/builds/11980914

### ISSUE THREAD

**Issue by jonasrauber** [lemurheavy/coveralls-public#986]
The coverage status links in the pull-request comments are broken, see for example here: https://github.com/bethgelab/foolbox/pull/5

**Comment by nlohmann** [comment]
Same issue here: https://github.com/nlohmann/json/pull/624#issuecomment-309216090

**Comment by ryan-williams** [comment]
Seeing this on all my PRs:

https://github.com/hammerlab/magic-rdds/pull/42
https://github.com/hammerlab/genomic-reference/pull/12
https://github.com/hammerlab/genomic-utils/pull/7
https://github.com/hammerlab/bdg-utils/pull/3
https://github.com/hammerlab/args4s/pull/5
https://github.com/hammerlab/iterators/pull/9
https://github.com/hammerlab/spark-tests/pull/16
https://github.com/hammerlab/test-utils/pull/14

Anyone have insight into how maintained coveralls is? IME I hear nothing on issues here (cf. https://github.com/lemurheavy/coveralls-public/issues/952, https://github.com/lemurheavy/coveralls-public/issues/899), and the most recent activity I see from a maintainer is on a closed issue about a month ago 😔.

**Comment by adoblas** [comment]
Same in #988

**Comment by diasbruno** [comment]
Hi, we are also having this problem. See [reactjs/react-modal#444](https://github.com/reactjs/react-modal/pull/444).

**Comment by diasbruno** [comment]
The badge link is correct now. Thanks!
