### ISSUE TITLE
Build order is broken

### ISSUE THREAD

**Issue by falsandtru** [lemurheavy/coveralls-public#989]
In the following my page, an old build 422 has been incorrectly marked as the latest build.

https://coveralls.io/github/falsandtru/pjax-api?branch=master

**Comment by mpetkov** [comment]
I have the exact same issue, it doesn't sync with the latest build:
https://coveralls.io/github/mpetkov/ng2-finance

**Comment by falsandtru** [comment]
@nickmerwin You log the build 422 with `01 Jul 2017 02:58AM UTC` but I have not done such an operation at the day.

**Comment by diophore** [comment]
this is making the tool almost unusable for us

**Comment by mpetkov** [comment]
I guess I will switch to Codecov since this is not being fixed...
