### ISSUE TITLE
Unable to find my repos

### ISSUE THREAD

**Issue by gclark14** [lemurheavy/coveralls-public#990]
I have two public repos I would like to use on coveralls, neither of which are being found by sync or /refresh. 

https://github.com/gclark14/codecov

https://github.com/gclark14/coveralls

**Comment by DavidS** [comment]
I've got the same issue with https://github.com/puppetlabs/pdk

**Comment by helveticafire** [comment]
I am having this problem too...

**Comment by DavidS** [comment]
In my case it was an issue with some hidden github permissions in our org. Someone with a higher privilege  level could configure coveralls just fine for the repo.

**Comment by tkrotoff** [comment]
#965 #948 #972

**Comment by bartmika** [comment]
I've got the same issue with https://github.com/MikaSoftware/django-trapdoor

**Comment by taleinat** [comment]
I am having this problem too.

**Comment by neilsh** [comment]
One "workaround" I found was to unlink my github account from coveralls, and then re-link it. The new repos will appear in the list after relinking. I think this also resets any data that already exists in coveralls (e.g. previous runs) for your account though, so this isn't really ideal.
