### ISSUE TITLE
Can't find how to unsuscribe

### ISSUE THREAD

**Issue by rossille** [lemurheavy/coveralls-public#991]
Hi,

I'm the manager of the TRANSCOVO org on github, and we want to unsuscribe for coveralls (we use another solution).

I can't find any way to do this from this page: https://coveralls.io/subscriptions

How to ususcribe from coveralls, remove the org, the payment card, etc...

You can contact me at samuel@chauffeur-prive.com if you need more details.

Thanks,
Samuel

**Comment by nickmerwin** [comment]
Hi @rossille it looks like there was an old user of yours that owned the subscription -- I've updated the ownership to your current user so you can manage it from the settings page:

https://coveralls.io/subscriptions/github:transcovo
