### ISSUE TITLE
Commit data in overview is from another project I'm not authorized to view

### ISSUE THREAD

**Issue by tnine** [lemurheavy/coveralls-public#995]
I recently integrated coveralls into a private repository on a paid account.  I'm receiving commit messages that do NOT come from my repository in the synopsis of my repo.  See the attached screenshot. 

<img width="1225" alt="screen shot 2017-08-03 at 8 20 30 pm" src="https://user-images.githubusercontent.com/249532/28951575-40e7fd9e-7889-11e7-8879-303d4a5f57a4.png">

This commit does not exist in my repo, nor does this author have access to my project.

**Comment by joedivita** [comment]
@tnine Have you received any update on this / is this still happening on your account?  I am experiencing the same thing (commits from another repo showing up in my paid private repo), and seeing that you submitted this a month ago I am hoping you have resolved this.  Thanks!

**Comment by mdevar** [comment]
I'm also experiencing the same issue: commits from other unrelated repos are showing up in our private repo. Any updates on this?
