### ISSUE TITLE
Can't unsubscribe

### ISSUE THREAD

**Issue by jmaitrehenry** [lemurheavy/coveralls-public#996]
Hi,

I'm the admin of PetalMD org on Github, I try coveralls on January and Feb, but I remove the subscription at this time.

On coveralls, I have a warning: ACCOUNT EXCEEDED REPO LIMIT
Your subscription for petalmd has exceeded its private repo limit. You won't be able to view your private repos until this is resolved.

But, on https://coveralls.io/subscriptions I have no subscriptions, and on https://coveralls.io/subscriptions/github:petalmd I have a 500 error page.

I still have a charge each month on my credit card for 5$.

Thanks

**Comment by gfreezy** [comment]
I have the same problems.

**Comment by mabon** [comment]
Same - and I need to update billing info.
