### ISSUE TITLE
Coveralls inside Docker Container "Couldn't find a repository matching this job."

### ISSUE THREAD

**Issue by tgockel** [lemurheavy/coveralls-public#997]
In a public repository (https://github.com/tgockel/zookeeper-cpp), I am running jobs on TravisCI within a Docker container. I am specifying repo token through spitting out `COVERALLS_REPO_TOKEN` to a file from `.travis.yml`, loading it in the image and specifying `--repo-token` directly. However, no matter what incantations I try, `coveralls` always exits with:

    {u'message': u"Couldn't find a repository matching this job.", u'error': True}

At the very least, a more informative error message would be nice to have. Ideally, I would like the error message to go away and be able to upload my coverage results.

**Comment by er0ck** [comment]
i have the same problem with a ruby project on travis inside a docker container.

i'm using:
```
script: docker run -it --env CI=true --env TRAVIS_JOB_ID=$TRAVIS_JOB_ID --volume $(pwd):/doctor_teeth us.gcr.io/slv-public/doctor_teeth /bin/bash -c "bundle update; bundle exec rake $CHECK"
```

i can print out the job_id in the rakefile in the container without issue.  
but i always get:

> [Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Couldn't find a repository matching this job.

if i run the docker container locally as above, and sub in the job_id
then it submits correctly (and i get a report in the github PR (the travis_job_id points to a PR, in this case)

**Comment by er0ck** [comment]
this is interesting.  i defined `COVERALLS_REPO_TOKEN` in travis as an encrypted env_var as i stated above.  it didn't alleviate the problem.
but i left it defined, and it broke all the coveralls reporting for the non-containerized jobs until i undefined that env_var again.  

it broke in the same way as above `{u'message': u"Couldn't find a repository matching this job.", u'error': True}`

**Comment by BR0kEN-** [comment]
I'd recommend submitting coverage report outside of the container for public repos.

`.travis.yml`

```yml
language: node_js
dist: trusty

node_js:
  - "9.8"

services:
  - docker

script:
  - docker exec -i cikit-rest-api.loc bash -c 'cd /var/www/cikit-rest-api && npm run lint && npm test'
  - cd docroot && npm run test-report-coveralls
```

Part of `package.json`

```json
{
  "scripts": {
    "start": "node ./index.js",
    "test": "nyc mocha --timeout 10000000 --exit",
    "test-report-html": "nyc report --reporter=html",
    "test-report-coveralls": "nyc report --reporter=text-lcov | coveralls"
  },
}
```

**Comment by paras20xx** [comment]
This comment may help:
https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-387698861
